### ISSUE TITLE
Error while displaying tags

### ISSUE THREAD

**Issue by ducdung0909** [Leantime/leantime#100]
Hi,
   I just got errors after adding new tag of to-do list.
   I have changed code to resolve as below:

/var/www/html/src/domain/tickets/templates/showAll.tpl.php
line 306
/var/www/html/src/domain/tickets/templates/showAll.tpl.php
line 306
if ($row["tags"] != "" && count($row["tags"]) > 0){
---->
if(isset($row["tags"]) && !empty($row["tags"])){

**Comment by marcelfolaron** [comment]
Thanks for reporting. I will take a look and get a fix out with the next release cut. (This weekend)
