### ISSUE TITLE
[BUG] Session timeout still not respected (see #557)

### ISSUE THREAD

**Issue by FalxDrako** [Leantime/leantime#1001]
**Describe the bug**
Same bug as described in #557.

**Leantime Version**
Leantime v2.2.7

**Server**
Apache 2.4

**PHP / MySQL Version**
PHP: 8.1  
MariaDB: 10.3

**Additional context**

- Manifests in Edge and Chrome latest versions. Never tested with other browsers. 
- The **php.ini** workaround suggested in #557 has no effect. Here is my current **php.ini**:

```
; https://github.com/Leantime/leantime/issues/557
;
; If different scripts have different values of
; session.gc_maxlifetime but share the same place for storing the session
; data then the script with the minimum value will be cleaning the data. In
; this case, use this directive together with session.save_path
session.save_path = /opt/alt/php81/var/lib/php/session

; After this number of seconds, stored data will be seen as 'garbage' and
; cleaned up by the garbage collection process.
; http://php.net/session.gc-maxlifetime
session.gc_maxlifetime = 86400
```

**Comment by Vaherastudios** [comment]
**Describe the bug**
Same bug as described in https://github.com/Leantime/leantime/issues/557.

**Leantime Version**
Leantime v2.2.7

**Server**
Apache 2.4

**PHP / MySQL Version**
PHP: 8.1
MariaDB: 10.3

**Additional context** 
I am using Plesk. And Chrome broswer.

**Comment by Naros** [comment]
The solution is to modify `src/core/class.session.php` and in the `__construct()` method, add:
```
        ini_set('session.cookie_lifetime', ($config->sessionExpiration));
```
This will now properly respect the cookie lifetime within the application.

**Comment by FalxDrako** [comment]
> The solution is to modify `src/core/class.session.php` and in the `__construct()` method, add:
> 
> ```
>         ini_set('session.cookie_lifetime', ($config->sessionExpiration));
> ```
> 
> This will now properly respect the cookie lifetime within the application.

Tested this. No effect.

**Comment by marcelfolaron** [comment]
Is it logging you out at a specific time or random times?

You could try to set session.gc_divisor
To 1000 just to see if the garbage collector is the culprit.

**Comment by marcelfolaron** [comment]
Are you closing the browser window in between? Could it be `
*session.cookie_lifetime* ` in php_ini ? If that is set to 0 the cookie
will be destroyed when the browser/tab is closed.
