### ISSUE TITLE
LDAP - user names not visible so cannot add to team

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1007]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
When we want to assign a user as a team member it is impossible because there names do not appear.

**To Reproduce**
Click Project Settings > Team
LDAP users are not identifiable due to missing names

**Expected behavior**
Their usernames should be plainly visible

**Leantime Version**
2.2.7

**Server**
NGINX 

**PHP / MySQL Version**
8.1 / 5.7

**Additional context**
I have created a video to make this problem very clear to you.
* https://www.youtube.com/watch?v=URh6rzWBh-0

Thank you.  This one is a show stopper for using LDAP users in our projects.

**Comment by compumatter** [comment]
I had the wrong youtube video URL there.  It has been corrected https://www.youtube.com/watch?v=URh6rzWBh-0

**Comment by phulstaert** [comment]
Hi @compumatter, I must admit I never have used the LDAP integration myself, but have heard from other users on Discord that it works. 
Because of this, I wanted to check if you have read the [LDAP part of the documentation](https://docs.leantime.io/#/installation/configuration?id=ldap-configuration-beta).
I would assume if the names and other fields are not showing, it is because of a wrong mapping. 

Do you have any information about the name of the fields in your LDAP server?

**Comment by compumatter** [comment]
This is a samba-tool show user username reply if that helps
`ldb_wrap open of secrets.ldb
dn: CN=douglas.lepore,CN=Users,DC=office,DC=compumatter,DC=biz
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn: douglas.lepore
description: Repair Manager
instanceType: 4
whenCreated: 20220818234319.0Z
uSNCreated: 4154
name: douglas.lepore
objectGUID: d44a9b00-f0a3-4909-b0cb-6c249120571a
codePage: 0
countryCode: 0
homeDirectory: \\servermatter\douglas.lepore
homeDrive: H:
lastLogoff: 0
primaryGroupID: 513
objectSid: S-1-5-21-2702295333-2311845208-2253380294-1130
accountExpires: 9223372036854775807
sAMAccountName: douglas.lepore
sAMAccountType: 805306368
userPrincipalName: douglas.lepore@office.compumatter.biz
objectCategory: CN=Person,CN=Schema,CN=Configuration,DC=office,DC=compumatter,DC=biz
mail: douglas@compumatter.com
userAccountControl: 512
memberOf: CN=smportal,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=All Staff,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=Admin Staff,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=Marketing,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=Bookkeeping,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=Receptionist,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=dam-0-a,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=wiki-0-a,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=cloud-a,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=rdp-users,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=vpn-users,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=admin-tools,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=wiki-1-a,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=wiki-4-a,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=wiki-2-a,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=dam-1-a,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=dam-2-a,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=dam-3-a,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=Techs,CN=Users,DC=office,DC=compumatter,DC=biz
memberOf: CN=proj-m-a,CN=Users,DC=office,DC=compumatter,DC=biz
pwdLastSet: 133071452038452340
lockoutTime: 0
badPasswordTime: 133081665094962780
badPwdCount: 0
lastLogonTimestamp: 133083738919576450
whenChanged: 20220923023131.0Z
uSNChanged: 12563
lastLogon: 133092130159207980
logonCount: 171
distinguishedName: CN=douglas.lepore,CN=Users,DC=office,DC=compumatter,DC=biz
`

**Comment by marcelfolaron** [comment]
So, are you saying that first and last name we’re not set when the users
logged in via ldap?

**Comment by compumatter** [comment]
Yes.  However I did just notice that my samba-tool show user did not reflect some of the fields in your mapping ie; givenName and sn.  So I have added a few extra data points in LDAP for this particular user ie;
```
givenName: Douglas
sn: Lepore
telephoneNumber: 360 610 8700
lastLogonTimestamp: 133092313616997280
streetAddress: 123 Some Street
l: Anacortes
st: WA
c: US
countryCode: 840
co: United States
postalCode: 98221
whenChanged: 20221003004429.0Z
homePhone: 360 610 444
title: Repair Department Manager
```
Our mappings are set as follows:
```
       "username":"cn",
        "groups":"memberOf",
        "email":"mail",
        "firstname":"givenName",
        "lastname":"sn",
        "phonenumber":""
        }';

```
I though ahaa that will fix it for sure.  However even after restarting Samba service and logging out and back in via Leantime, the data for douglas.lepore is the same as it was. 

![image](https://user-images.githubusercontent.com/121611/193484384-697527aa-6a62-44c5-b6a8-4d0e624c7a73.png)

**Comment by marcelfolaron** [comment]
Yeah, the first and last name are currently not updated afterwards.

Is it feasible to remove the user in Leantime and try again?

**Comment by compumatter** [comment]
Question: If I remove a user that has many projects applied to them, will lost data occur or can the main admin then reapply to the new user?

**Comment by marcelfolaron** [comment]
The admin can add the user back to the project but any assignments in todos
will be lost (or comments etc)

Let me check and get back to you on updating users on login as well.

**Comment by compumatter** [comment]
In my opinion, this LDAP information should always pull in from the LDAP records on each login.  If a user has their phone, or other data changed it would not repopulate.  Especially in the case of the password which will most certainly change at some point.  Married persons who change their last name.   In addition, I feel you will have other businesses that will run into the same problem as us.  Failure to have a datapoint like givenName or future fields requires teardown of the user.   It removes some of the benefit of LDAP which is the centralized repository of their user data.

Even during the testing phase for businesses it will create confusion if they get this wrong and then correct it and not understand why it didn't populate.   It will save you support issues in the long run.

What do you think?   If this is not resolvable then I will have to delete our two project users and pick up the pieces.  Either way I think for the future you should consider this an issue worth addressing.

**Comment by marcelfolaron** [comment]
Password is not stored on our site and always checked against ldap. But you
are right the rest should update on each login.

I’ll try to get this in as soon as possible.

**Comment by compumatter** [comment]
Thank you.

**Comment by marcelfolaron** [comment]
I added the update to user information on login and it will be released in the next couple days

**Comment by compumatter** [comment]
Thank you again.  Glad to hear it.  Very important of course.
