### ISSUE TITLE
[BUG] INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs) 

### ISSUE THREAD

**Issue by ZoXx** [Leantime/leantime#1010]
Good morning.

iam on the latest docker version and got the problem that dthe docker isnt working anymore.

I see in log:

- 2022-10-02 08:36:18,848 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
- 2022-10-02 08:36:18,850 INFO spawned: 'httpd' with pid 12
- 2022-10-02 08:36:18,896 INFO exited: httpd (exit status 0; not expected)
- 2022-10-02 08:36:20,899 INFO spawned: 'httpd' with pid 13
- 2022-10-02 08:36:21,946 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
- 2022-10-02 08:36:21,946 INFO exited: httpd (exit status 0; expected)
- 2022-10-02 08:36:22,950 INFO spawned: 'httpd' with pid 14
- 2022-10-02 08:36:24,012 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
- 2022-10-02 08:36:24,012 INFO exited: httpd (exit status 0; expected)
- 2022-10-02 08:36:25,017 INFO spawned: 'httpd' with pid 15
- 2022-10-02 08:36:26,096 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
- 2022-10-02 08:36:26,097 INFO exited: httpd (exit status 0; expected)
- 2022-10-02 08:36:27,100 INFO spawned: 'httpd' with pid 16
- 2022-10-02 08:36:27,146 INFO exited: httpd (exit status 0; not expected)
- 2022-10-02 08:36:28,148 INFO spawned: 'httpd' with pid 17
- 2022-10-02 08:36:28,192 INFO exited: httpd (exit status 0; not expected)
- 2022-10-02 08:36:30,196 INFO spawned: 'httpd' with pid 18
- 2022-10-02 08:36:30,245 INFO exited: httpd (exit status 0; not expected)
- 2022-10-02 08:36:33,249 INFO spawned: 'httpd' with pid 19
- 2022-10-02 08:36:33,294 INFO exited: httpd (exit status 0; not expected)
- 2022-10-02 08:36:34,295 INFO gave up: httpd entered FATAL state, too many start retries too quickly

Any help for this? Docker is down.

**Comment by phulstaert** [comment]
@ZoXx , do you have this issue with your current install or with the latest version on a clean install?

**Comment by ZoXx** [comment]
@phulstaert yes.

found the issue!

There is another path in container: **/sessions**
I have now linked this via bind with a path and now it runs cleanly.

**Comment by ZoXx** [comment]
Bad news. The problem still exists. I have already deleted the volume for the session. No improvement. In the meantime I have restarted leantime once. Same problem still exists after Docker restart.

**Comment by phulstaert** [comment]
First things first.  
You state that docker is down. I would read this as "your docker service is down". Or do you mean: one of the two docker containers shuts down after starting it? or do you mean: you get a http 404, but the containers are still running?
That information and distinction is very important.

Next: what kind of setup do you use? You state docker, but you can run this with docker-compose or with arguments on the command line.

If you run the docker with docker-compose and a docker-compose.yml file, did you make any adjustments on it beside a database password?

Did you alter the setup in any other way?

**Comment by ZoXx** [comment]
Good morning.
Docker was set up via Portainer. I have attached my settings via snipping under the post.

The log gives the following persistent error message:
`2022-10-1123:34:35,265 INFO spawned: 'httpd' with pid 40
2022-10-11 23:34:36,375 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-10-11 23:34:36,375 INFO exited: httpd (exit status 0; expected)
2022-10-11 23:34:37,378 INFO spawned: 'httpd' with pid 41
2022-10-11 23:34:37,426 INFO exited: httpd (exit status 0; not expected)
2022-10-11 23:34:38,431 INFO spawned: 'httpd' with pid 42
2022-10-11 23:34:39,517 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-10-11 23:34:39,517 INFO exited: httpd (exit status 0; expected)
2022-10-11 23:34:40,523 INFO spawned: 'httpd' with pid 43
2022-10-11 23:34:40,581 INFO exited: httpd (exit status 0; not expected)
2022-10-11 23:34:41,588 INFO spawned: 'httpd' with pid 44
2022-10-11 23:34:41,654 INFO exited: httpd (exit status 0; not expected)
2022-10-11 23:34:43,658 INFO spawned: 'httpd' with pid 45
2022-10-11 23:34:43,706 INFO exited: httpd (exit status 0; not expected)
2022-10-11 23:34:46,713 INFO spawned: 'httpd' with pid 46
2022-10-11 23:34:46,798 INFO exited: httpd (exit status 0; not expected)
2022-10-11 23:34:47,800 INFO gave up: httpd entered FATAL state, too many start retries too quickly`

The Docker is online, but not reachable. The following error message appears in the browser: `ERR_CONNECTION_REFUSED`

![1](https://user-images.githubusercontent.com/11578454/195268652-e0090443-5ad2-4c4b-abfb-bdd257b164a3.png)
![2](https://user-images.githubusercontent.com/11578454/195268655-12941b5c-c297-4874-aca2-6a9584a6451a.png)
![3](https://user-images.githubusercontent.com/11578454/195268657-2c604db5-ccbe-4538-8490-c1badc84cbbd.png)
![4](https://user-images.githubusercontent.com/11578454/195268658-3e6b9b86-1145-4146-affc-dee6dcdf9826.png)
![5](https://user-images.githubusercontent.com/11578454/195268659-69917f24-53e3-456a-b0a2-28a3787a7794.png)
![6](https://user-images.githubusercontent.com/11578454/195268649-e1a360c4-9bc0-4935-a853-68c8fe1571d9.png)

**Comment by gloriafolaron** [comment]
Were you able to get this sorted out?

**Comment by ZoXx** [comment]
Since the last update it runs without problems

**Comment by mrbbbbbbbb** [comment]
It should be reopened. It keeps happening now on 3.0.7, so annoying.
Leantime is basically unusable lightly speaking, added a lot of data, projects, tasks Nth time now (removed volumes a number of times) and it keeps happening worked fine 2 days and again same story, restarting docker containers does not help. Damn error below
INFO gave up: httpd entered FATAL state, too many start retries too quickly. 
2 years later and still not fixed
