### ISSUE TITLE
[BUG] after installation

### ISSUE THREAD

**Issue by justfor-it** [Leantime/leantime#1011]
Hi,

After installation I get this
![image](https://user-images.githubusercontent.com/68807794/193660158-f8698bde-d4cc-4571-85c8-0ac51677332f.png)

I think this is not right. I have installed in from the original docker file on Unraid.

Is there something i can do?

**Comment by marcelfolaron** [comment]
Seems that a lot of the style files are missing. What do you see in the
chrome console?
Do you use https? You can try to run the docker container with
LEANT_APP_URL = "https://yourdomain"

**Comment by justfor-it** [comment]
Ah Yes fixed


Op 3 okt. 2022 om 22:35 heeft Marcel Folaron ***@***.***> het volgende geschreven:

﻿

Seems that a lot of the style files are missing. What do you see in the
chrome console?
Do you use https? You can try to run the docker container with
LEANT_APP_URL = "https://yourdomain"

**Comment by marcelfolaron** [comment]
Great, glad that worked!

**Comment by justfor-it** [comment]
I don't know why it was not working on edge but with the domain it is working :-)
