### ISSUE TITLE
ToDo Disccussions need Time Tracking Option

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1013]
**Is your feature request related to a problem? Please describe.**
I enter discussions on a regular basis.  It is more often than not related to work that was done as part of keeping a chronological document for me or others to verify work done to the client.  The problem is most of the time this discussion note serves as billable time which are notes I will eventually transfer to my invoice.  As things are I have to notate the time manually, then at a later date copy/paste those notated discussions into the Time Tracking area.

**Describe the solution you'd like**
I think the easiest solution would be to:
1) Have an "Hours", "Date" and  field next to the discussion with a checkbox [x] Billable that gives us the option to add that to time tracking on the spot.
2) The second alternative solution would be to "at least" provide an "hours" field beneath the "Discussion" field entry.  Then, when adding a Time Tracking event there could be a new dropdown where users could select the "Discussion" they would like to apply to this Time Track event.  The text would then pull in the discussion and any hours associated with it.  We would be free to further edit that text and hours at that point if we wish.

**Additional context**
I have created a video make more obvious the work flow problem we are experiencing:

- https://www.youtube.com/watch?v=BU4hf7jy7kE
Thank you!

**Comment by marcelfolaron** [comment]
Thank you for this submission, this is a really interesting use case and I agree that there is a lot of time spent on discussions. Let me review the options again and get back to you on this.

**Comment by compumatter** [comment]
Marcel, is there a document indicating how to install Leantime from source?  I know the vendors file is missing when I've tried it before.  I noticed this feature is fixed and ready to be included in the next release.  Unless you'd recommend against me installing from source just yet I'd really like to get my hands on this feature.  
Your thoughts?
