### ISSUE TITLE
[FEATURE] Expanded Milestones view

### ISSUE THREAD

**Issue by mspacemedia** [Leantime/leantime#1016]
**Is your feature request related to a problem? Please describe.**
A great addition would be to view the current todo's in the Milestone view

**Describe the solution you'd like**
Clicking on the milestone itself, would then expand to show each todo within the constraint of the milestone itself - so for four todo items their bars would be split 25% each of the milestone above them? Or as expanded items below like the "depends on" arrows with extra bars for each todo.

**Additional context**
This would then make viewing the milestones a much more productive overview of each projects elements…

**Plus could we fix printing the milestone views :D as these are broken and produce black printouts…**

**Comment by gloriafolaron** [comment]
Eek on the printing. I'm going to post that in our bug backlog.

If a milestone has 20 to dos associated with it, would you expect to see all 20 items listed out in that view or would you want to see only certain items? 

I think I understand you saying you'd like to be able to filter or sort them. What parameters would you want to sort for?
