### ISSUE TITLE
[FEATURE] Closed projects will dominate the "All Projects" view

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1017]
**Is your feature request related to a problem? Please describe.**
At present, when looking at "all projects" it retains closed projects in the same list.  This will naturally grow to a situation where there are more closed projects than open projects to consider in that view

**Describe the solution you'd like**
If a project is closed, there is no reason to see it "unless" you wish to revive it.  Reviving is an important ability of course and could be accommodated by separating the UI with tabs, buttons or a drop down.  I think a button or tab would be more natural but the important part is the separation of content itself.

**Additional context**
I have created a video for you to make more clear my problem and potential solution
- https://www.youtube.com/watch?v=okOhddVGRrQ

**Comment by gloriafolaron** [comment]
Thanks for the detailed information here! This is a great call out.
