### ISSUE TITLE
[FEATURE] EPICS - Possibility to create Sprints without date range

### ISSUE THREAD

**Issue by D4ykoo** [Leantime/leantime#1018]
**Is your feature request related to a problem? Please describe.**
I want to create sprints without any specific date. That I can define a kind of EPIC which contains a lot of tasks. 
Currently I also have to provide a date, even though for private projects or currently starting companies it is in the beginning to possible to set a fixed date for specific task bundles.

**Describe the solution you'd like**
The possibility to create sprints without setting a date. Or the possibility to create an EPIC which contains all the tasks.

**Comment by marcelfolaron** [comment]
The concept of epics is represented as "milestones" within Leantime. You
can create a new milestone and then assign it to many tasks. In the filter
options you can then filter by milestones.

**Comment by D4ykoo** [comment]
Well that's right, i made a mistake in the issue. Even though the epic concept is possible, i am not able to create a milestone without a date.

**Comment by marcelfolaron** [comment]
Another option is to use Tags. Tags can be set and filtered.

**Comment by D4ykoo** [comment]
Well yes! It would be great to have a tool that is a whole project management software + the capability to do the same thing but just without have to specifying any dates. Just the possibility to not add dates increase the different usage ideas. e. g. just a normal kanban board + milestones/sprints (as epics), to plan a project that isn't full agile due to some time issues.
In my case: I am a working student, which means i work 8 - 9 hours a day if I don't have any lectures.
But i got some projects. I want to plan the projects but if I have to set a date, it makes me 'impossible' to use leantime for my own software projects which can not be timed (sometimes more university stuff to do or just need a pause on one evening).

I tried to present it as some kind of user story, hopefully it makes more sense now!
