### ISSUE TITLE
Timesheets - Invoice Paid Checkbox / Default View

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1019]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to know if a client has paid their invoice.  This leaves the business owner and project manager in a state of never knowing if this ticket has been financially settled.  It forces them to have to open their finance software and check.  Possibly repeatedly over time.

**Describe the solution you'd like**
At a minimum a single checkbox that says [X] Paid.   A step better also a Date: [ 10/04/2022 ].  A step better, the ability to filter the timesheet list view by Pending, Invoiced, Paid in addition to All.

**Additional context**
I have created a video to better explain what we really need in this regard.  Since we are on the subject of Timesheets it also references  a lesser required feature of default timesheet view
- https://youtu.be/bZLMNmPZsL4

Thank you for considering this.

**Comment by gloriafolaron** [comment]
Thanks! The video here was really helpful and the feature makes a lot of sense.  I'm adding this to our feature backlog.
