### ISSUE TITLE
[FEATURE] Subtasks Display in table view

### ISSUE THREAD

**Issue by hnegadi** [Leantime/leantime#1030]
**Is your feature request related to a problem? Please describe.**
Subtasks are now kind of burried and difficult to access and manage.

**Describe the solution you'd like**
Display subtasks in todos table view would be amazing.

**Additional context**

**Comment by gloriafolaron** [comment]
We were just discussing this recently with a similar feeling. Is there an initial thought on how you think you'd want to see that subtask flow on the table?

**Comment by hnegadi** [comment]
Hello. 
A good example is clickup used by one of our clients, please find attached picture.
![clickUpSubTasks](https://user-images.githubusercontent.com/501818/198905832-7dac7e9d-18f7-43ba-8ea9-f5f77f630ac7.jpg)

Thank you.

**Comment by paccmx** [comment]
this would be great, an idea would be making tasks dependent of other tasks, simular to milestones.  In a workflow idea, several times the subtasks inside a tarks go ignored, because they are not shown in the principal task view.

**Comment by hnegadi** [comment]
That would be an amazing feature. Not having this leads to burring subtasks. That would really put leantime on steroids. 
That missing is the only reason some of our clients keeps using clickup unlike us. That would make our life so easier if they could adopt leantime,
