### ISSUE TITLE
[BUG] cannot save users settings.

### ISSUE THREAD

**Issue by hnegadi** [Leantime/leantime#1032]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Upon attempt to save a user's settings, a popup appears asking to enter an email address that already in file.
The changed settings are not being saved.
Please see attached pictures.
![Screenshot 2022-10-13 164949](https://user-images.githubusercontent.com/501818/195632067-399e3e46-cc81-4068-ae23-5f847004360d.jpg)
![Screenshot 2022-10-13 165106](https://user-images.githubusercontent.com/501818/195632097-76742905-73ac-4772-8c59-b7cf8c0c47e4.jpg)
![Screenshot 2022-10-13 165127](https://user-images.githubusercontent.com/501818/195632108-fb932da8-ebe5-4811-820d-fa70978defe3.jpg)

**Leantime Version**
2.2.7

**Server**
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2022-06-23T12:51:37

**PHP / MySQL Version**
PHP Version 8.0.24 / mysql  Ver 14.14 Distrib 5.7.39, for Linux (x86_64) using  EditLine wrapper

**Comment by marcelfolaron** [comment]
What is in the email field? Is it possible that it's not a valid email?

**Comment by gloriafolaron** [comment]
@marcelfolaron any chance this has any connection to the current LDAP bug?

**Comment by marcelfolaron** [comment]
I tried a couple times but wasn't able to recreate the issue. Can you let me know if this is still an issue?
