### ISSUE TITLE
[BUG] Copy URL button doesn't work

### ISSUE THREAD

**Issue by Pheggas** [Leantime/leantime#1039]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
I just spun up latest (v2.2.8) version and tested new features. I went to Documents, created new wiki, new article and clicked the Copy URL button. It didn't copy anything but noticed the text of that button is correct. The copy function just doesn't work. However when i right click -> Copy link adress, It does work perfectly

**To Reproduce**
1. Documents (in left handed list)
2. Create new wiki
3. Create new article
4. Click the Copy URL at the upper right corner
5. The link won't copy to clipboard

**Expected behavior**
To copy link to that article to clipboard.

**Leantime Version**
V2.2.8

**Server**
Ubuntu Server 22.04 LTS; MySQL docker container dedicated only for Leantime

**PHP / MySQL Version**
MySQL 8.0.31-1.el8

**Additional context**
Some pictures referencing the bug:
![image](https://user-images.githubusercontent.com/9994511/195780813-5c808668-13be-4f36-b527-c7ea85e95b12.png)
![image](https://user-images.githubusercontent.com/9994511/195780836-148830e2-e1a4-4ccb-b238-6d256c141f2e.png)

**Comment by marcelfolaron** [comment]
What browser are you using and do you see anything in the browser console ?

**Comment by Pheggas** [comment]
Yep.

![image](https://user-images.githubusercontent.com/9994511/195943005-311a423e-7a23-4fcc-9221-f382941341fa.png)

**Comment by marcelfolaron** [comment]
Hi, 
I think I found the issue, but I am not entirely sure there is a simple solution:
I am using the writeText api to interact with the clipboard. However the clipboard is only available in a secure context (eg https://)
It seems you are accessing the site via http? Can you confirm?

**Comment by marcelfolaron** [comment]
NVM found a solution.

**Comment by Pheggas** [comment]
> Hi, I think I found the issue, but I am not entirely sure there is a simple solution: I am using the writeText api to interact with the clipboard. However the clipboard is only available in a secure context (eg https://) It seems you are accessing the site via http? Can you confirm?

Yes, I'm over http as i have it accessible only over local network.

**Comment by marcelfolaron** [comment]
Can you try to update to the latest version? I have a work around that may
solve this for now.

**Comment by Pheggas** [comment]
I am on latest rn (2.2.10)
