### ISSUE TITLE
LDAP login failure - throws 404 - Can't login at all

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1045]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
After entering the username / password to login it redirects to a 404 page.  It also throws some clear LDAP php file errors at the top of the screen.

**To Reproduce**
Login as LDAP user

**Expected behavior**
Normal UI experience

**Leantime Version**
2.2.8 - Just installed from the releases and not from source

**Server**
NGINX

**PHP / MySQL Version**
8.1 / 5.7

**Additional context**
I have created a video here:
- https://www.youtube.com/watch?v=iWtQyNtPkZ8

![image](https://user-images.githubusercontent.com/121611/196351160-fecbf7b1-2168-40b9-9d1f-2c657a18ab9f.png)

Log file errors noticed:
` *45617 FastCGI sent in stderr: "PHP message: PHP Warning:  ini_set(): Session ini settings cannot be changed when a session is active in /SM_DATA/web_projects/public_html/config/appSettings.php on line 53PHP message: PHP Warning:  ini_set(): Session ini settings cannot be changed when a session is active in /SM_DATA/web_projects/public_html/config/appSettings.php on line 54PHP message: PHP Warning:  ini_set(): Session ini settings cannot be changed when a session is active in /SM_DATA/web_projects/public_html/config/appSettings.php on line 55PHP message: PHP Warning:  ini_set(): Session ini settings cannot be changed when a session is active in /SM_DATA/web_projects/public_html/config/appSettings.php on line 56" while reading response header from upstream, client: 192.168.9.249, server: projects.compumatter.biz, request: "GET /download.php?module=user&encName=f962b812c542fb0e3e48e66142af09ce&ext=png&realName=userPicture HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "projects.compumatter.biz", referrer: "https://projects.compumatter.biz/auth/login"`

As you can imagine, this is a show-stopper for LDAP of course.   Thanks for looking.

**Comment by MrDiba** [comment]
Can confirm, I have the same issue. I suspect there is an issue when the LDAP users are updated in the database on login. 

When I have two LDAP users configured and the first one logs in their `username` disappears` in the database. 

```
mysql> select * from zp_user;
+----+----------------+----------+-----------+----------+-------+-----------+---------------------+--------+---------+------+-----------------------------------------------------------------------------------+-------------+------+-------+-------------+----------+---------------+---------+-------------------+--------------+--------------+----------------+---------------------------------------------------+--------------+-------------+-----------+--------+
| id | username       | password | firstname | lastname | phone | profileId | lastlogin           | status | expires | role | session                                                                           | sessiontime | wage | hours | description | clientId | notifications | pwReset | pwResetExpiration | pwResetCount | forcePwReset | lastpwd_change | settings                                          | twoFAEnabled | twoFASecret | createdOn | source |
+----+----------------+----------+-----------+----------+-------+-----------+---------------------+--------+---------+------+-----------------------------------------------------------------------------------+-------------+------+-------+-------------+----------+---------------+---------+-------------------+--------------+--------------+----------------+---------------------------------------------------+--------------+-------------+-----------+--------+
|  9 | user1@example.com |          | User1     | Last1 |       |           | 2022-10-18 06:33:38 | a      | NULL    | 50   |                                                                                   | 1666074818  |    0 |     0 | NULL        |        0 |             1 | NULL    | NULL              |         NULL |         NULL | NULL           | a:1:{s:6:"modals";a:1:{s:9:"dashboard";s:1:"1";}} |            0 | NULL        | NULL      | ldap   |
| 11 |                |          | User2     | Last2  |       |           | 2022-10-18 06:55:46 | A      | NULL    | 50   | <active-session-id>                                                                 | 1666076146  | NULL |  NULL | NULL        |        0 |             1 | NULL    | NULL              |         NULL |         NULL | NULL           | a:1:{s:6:"modals";a:1:{s:9:"dashboard";s:1:"1";}} |            0 | NULL        | NULL      | ldap   |
+----+----------------+----------+-----------+----------+-------+-----------+---------------------+--------+---------+------+-----------------------------------------------------------------------------------+-------------+------+-------+-------------+----------+---------------+---------+-------------------+--------------+--------------+----------------+---------------------------------------------------+--------------+-------------+-----------+--------+
```
As the second user logs in, the database will also try to clear their username but as the username field is specified as UNIQUE this is not possible and the log will throw an error: 
`[18-Oct-2022 08:57:59 Europe/Amsterdam] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'zp_user.username'`
