### ISSUE TITLE
[FEATURE] Migrating of Leantime

### ISSUE THREAD

**Issue by javaindian** [Leantime/leantime#1049]
Hi @marcelfolaron 

I have been using Leantime in a Xampp Portable.

Today when i wanted to move the Leantime from one xampp PC to another, the Leantime started with an installation script. 

For the record my instance is plain vanilla leantime without any integrations like LDAP/external apps under Windows 10.

What i did is:

1. Took backup of Whole leantime folder under xampp/htdocs/.
2. Exported the leantime DB fromphpmyadmin to an sql file.
3. Copied the leantime folder into new xampp/htdocs.
4. Created a new DB in the new phpmyadmin with the same name as the old one.
5. Imported the sql file into the new leantime DB.
6. Fired the browser to localhost (already httpd is configured to direct it to leantime/public folder)
7. It started as if it is a new installation.

Is there any way to better manage the migration process? 

I know am asking for more, but this is very important, in case we have to migrate for some reason.

Thanks Bala

**Comment by javaindian** [comment]
And i replaced the whole DB folder in the new xampp with the old one, just to check. 

The leantime page goes to install/update.

**Comment by compumatter** [comment]
I just upgraded and this was my process.  It worked perfectly.  Also, if you download from source it will cause you added problems.   Download from the releases page.
![image](https://user-images.githubusercontent.com/121611/196632341-acc95248-1585-4c1f-98dc-3f208f4ed782.png)

If you follow these instructions, after you login Leantime will show you a single button to OK upgrading your database to the new version.  Worked great.

**Comment by marcelfolaron** [comment]
As @Compumatter mentioned there is an upgrade script that should have
started. It looks very similar to the installation page.

The upgrade page is a standard step in the updating process. Can you
confirm that this is the page you are seeing?

**Comment by javaindian** [comment]
> I just upgraded and this was my process. It worked perfectly. Also, if you download from source it will cause you added problems. Download from the releases page.
> 
> Leantime:upgrading
> 
> Assumes you had a working installation prior
> 
> Download the latest release ZIP file to the parent directory of the existing public_html
> 
> [From the releases page](https://github.com/Leantime/leantime/releases) (and NOT from the https://github.com/Leantime/leantime source code or you will be missing the vendors directory)
> 
> After the file is downloaded
> 
> * Move existing public_html to public_html.sav
> * Extract the downloaded file with unzip Leantime....zip
> * Renamed the unzipped folder from leantime... to public_html
> * Checked that .htaccess files from public_html and public_html.sav were the same
> * Compare the public_html.sav/config/configuration.php files and **update the new one** with existing settings including LDAP settings if applicable.
> * Copy the directory public_html.sav/userfiles/* to the new install public_html/userfiles/ (this includes all profile images etc)
> * chown www-data:www-data public_html -R
> * Opened the URL that previously worked and you should be good to go
> 
> If you follow these instructions, after you login Leantime will show you a single button to OK upgrading your database to the new version. Worked great.

Thanks for the reply. I got the upgradation right. I am doing it the same way so far. No issues. 

My problem is migrating from one pc to the other.

**Comment by gloriafolaron** [comment]
I'm sorting through feature requests and want to make sure I don't misunderstand this  -- I see two things here: 1. you are asking for help on if migration of systems is possible and then would I be correct in that 2 would be that if it isn't possible, then it's a feature ask?

**Comment by marcelfolaron** [comment]
If the install script starts the system can't find the zp_user table. Is it possible that your new db credentials are connecting to a different db?

**Comment by marcelfolaron** [comment]
Just saw your other comment on the 500 when you copy the entire db folder. Can yoy go into phpmyadmin and make sure the database structure (db name, user etc) is exactly the same and the table zp_user is indeed in your database? 

On the other side, if you copy the folder again to get the 500 error. Can you check what errors you see in resource/logs/error.log?

**Comment by javaindian** [comment]
I retried the migration. 

For some reason or other, i am not sure, It worked.  And, yes the zp_user was present previously too.

I did the same thing as mentioned in the OP.  The OP looks like the way to migrate in Xampp.

Thanks for the help @marcelfolaron @gloriafolaron @compumatter.

**Comment by javaindian** [comment]
However, I am finding leantime asking to log back (frequently showing a pop-out with a "Welcome back" message).

**Comment by javaindian** [comment]
Error Log in Apache is:

[Thu Oct 27 12:37:26.144924 2022] [php:warn] [pid 17060:tid 1852] [client ::1:58906] PHP Warning:  ini_set(): Session ini settings cannot be changed when a session is active in D:\\xampp\\htdocs\\leantime\\config\\appSettings.php on line 53, referer: http://localhost/tickets/showKanban
[Thu Oct 27 12:37:26.144924 2022] [php:warn] [pid 17060:tid 1852] [client ::1:58906] PHP Warning:  ini_set(): Session ini settings cannot be changed when a session is active in D:\\xampp\\htdocs\\leantime\\config\\appSettings.php on line 54, referer: http://localhost/tickets/showKanban
[Thu Oct 27 12:37:26.145924 2022] [php:warn] [pid 17060:tid 1852] [client ::1:58906] PHP Warning:  ini_set(): Session ini settings cannot be changed when a session is active in D:\\xampp\\htdocs\\leantime\\config\\appSettings.php on line 55, referer: http://localhost/tickets/showKanban
[Thu Oct 27 12:37:26.145924 2022] [php:warn] [pid 17060:tid 1852] [client ::1:58906] PHP Warning:  ini_set(): Session ini settings cannot be changed when a session is active in D:\\xampp\\htdocs\\leantime\\config\\appSettings.php on line 56, referer: http://localhost/tickets/showKanban

**Comment by javaindian** [comment]
@marcelfolaron Pls help.

**Comment by broskees** [comment]
@javaindian more than likely your DB settings are incorrect in your configuration.php file of leantime.

**Comment by marcelfolaron** [comment]
@javaindian Can you check if there is a cookie set in your browser called SID? 
Then next in the configuration file make sure you sessionTimeout is set to something reasonable. Lastly make sure your session path is set and writeable. Any other errors in resources/logs/error.log?

**Comment by marcelfolaron** [comment]
Will close this for now due to inactivity.
