### ISSUE TITLE
Issue 976 was just closed but issue has reappeared - Todos not normalized in appearance.

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1051]
Using 2.2.8 downloaded from source this evening.

After copying the original public_html to a safe place, I copied over public_html with directory structure downloaded from the source.  

I can login find and all appears normal.

However, when I downloaded 2.2.8 yesterday the Todos were displaying very nicely with a normalized height which resulted in the issue 976 being closed:  https://github.com/Leantime/leantime/issues/976

The latest changes that seem to relate to issue number https://github.com/Leantime/leantime/issues/1042 have resulted in a reversal and now I see these huge todos again.

Though I respect that #1042 was used to seeing their descriptions in the todos, it overwhelms the page entirely and when you get many todos, as this image indicates, drastically reduces the number of todos that you can wrap your head around since you have to keep scrolling down to see them.

So that appears to be what has happened.  Unless there's something I don't know about.

A compromise on this issue might be that a maximum of XX characters (for instance 80) are visible before an ellipsis (...) if there is more text to be seen.

They are certainly way too long and most importantly, not normalized in appearance to the viewer. 
![image](https://user-images.githubusercontent.com/121611/196636937-aa291b9b-1101-4f70-a3dc-c6373df0f2b5.png)

![image](https://user-images.githubusercontent.com/121611/196636891-4e802c3b-d8c7-4cc1-88d5-087fad0e3186.png)

Thanks.

**Comment by marcelfolaron** [comment]
Hi,

Can you confirm that the css files are up to date in your local version
(and not cached) The height of the description is capped at 75px and should
fade out.

The kanban.css has a new class kanbanContent that manages that.

**Comment by compumatter** [comment]
Good call of course.  It was a cache issue. Solved.
