### ISSUE TITLE
[BUG] Poor layout of dropdown buttons in specific screen width situations

### ISSUE THREAD

**Issue by diderich** [Leantime/leantime#1066]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
On narrow screen, in specific situations/for specific screen widths, when the page contains 2 or more dropdown menus to the right top, they are poorly rendered, as shown in the figure below:

![formatting](https://user-images.githubusercontent.com/10230144/197199307-6d7d77b4-cd51-4e52-83ae-f668cf011f85.jpg)

**To Reproduce**
1. Simulate a device with small screen (or use an actual such device), e.g.  a device with a width of 790 px.
2. Go to the `/tickets/showKanban` page.
3. See the poorly layed out buttons

**Expected behavior**
Buttons are layed out "correctly"

**Leantime Version**
2.2.10

**Comment by gloriafolaron** [comment]
There is definitely some room for smaller screen optimization needed.

My primary device is 12.9" and I get some goofy renderings.

Adding this to the current bug list.

Thanks for reporting!
