### ISSUE TITLE
[BUG] Strange empty Project Assigment view on iPad

### ISSUE THREAD

**Issue by diderich** [Leantime/leantime#1072]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
When I am looking at **Edit Usere** on my iPad Pro iOS 15.7 (both with Safari and Edge browsers), I see a strange empty list of projects (surrounded in red in the figure below). I have no clue whether this is due to the iPad or due to the JavaScript library used.

![ipad](https://user-images.githubusercontent.com/10230144/197495472-f267a9dd-fcf2-4158-9f3b-a4def1a6e894.jpg)

**To Reproduce**
1. Use an iPad to access Leatime
2. Go to 'User Management' and select a user
3. See the screen as shown on top.

**Expected behavior**
Same behavior as on a desktop/laptop.

**Leantime Version**
2.2.10

**Comment by marcelfolaron** [comment]
We will need to replace this view with a more friendly checkbox selection box (similar to user selection on project settings)

**Comment by marcelfolaron** [comment]
Updated the project assignment boxes to be checkboxes
