### ISSUE TITLE
[BUG] Missing file /images/svg/apps-grid-icon.svg

### ISSUE THREAD

**Issue by diderich** [Leantime/leantime#1078]
**Describe the bug**

The file `/images/svg/apps-grid-icon.svg` is missing in the latest version on github:
![mssing](https://user-images.githubusercontent.com/10230144/198070154-2a1dbed3-3826-4499-b8e7-7388e75db73c.png)

Why not use an icon instead?

**Comment by marcelfolaron** [comment]
Thanks for the call out. I just added the picture to the repo.
To your question: That particular icon is unfortunately not part of the
free fontawesome version. I tried to find another font but was
unsuccessful.
This is an open source SVG with a simple option to change the color. It
seemed like the best compromise.
