### ISSUE TITLE
[BUG] Warning: Undefined array key 5 in /src/domain/tickets/services/class.tickets.php on line 239

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1087]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
When I turn on debug=1 I get a significant number of warnings that appear to be in a loop.  They concern me that some behavior may be effected due to these warnings.
We are trying to troubleshoot some LDAP data sync issues and all these warnings fill up our field of view.  It would be desired to have these minimized to make troubleshooting other important items easier to sift through.  As it is, we cannot even see the login page without scrolling through a full page and 1/2 of such warning notices.

**To Reproduce**
Turn on debug = 1 within configuration.php

**Expected behavior**
It is normal to see some deprecation type warnings of course.   However attempts to access array values that result in null I do not expect to see.  At least not in this abundance.

**Leantime Version**
Version 2.2.9

**Server**
NGINX

**PHP / MySQL Version**
8.1 / 5.7

**Additional context**
I have had to prepend the code with an @ symbol to stop it from notifying so we could work further on debugging other issues.
ie line #239 of class.tickets.php; 

`
if(@$statusLabels[$row['projectId']][$row['status']]['statusType'] != "DONE" ) {
`

Here is an image of what we see when that line is not @prepended: 

![image](https://user-images.githubusercontent.com/121611/198724519-3582ab0f-9388-40ca-b104-7bb2ce5ab862.png)

**Comment by marcelfolaron** [comment]
Thanks for reporting this. I noticed the same issue, this happens primarily when a user has tasks assigned to them but is not "officially" part of the project. 
I have a fix in master for this that also covers some additional edge cases.
