### ISSUE TITLE
LDAP Roles not converting and LDAP Fields not populating - Resolved - Please See Code Contribution

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1098]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
When LDAP users login, their role as would be defined below configuration.php is ignored. **They were always made "Editor"**
```
   public $ldapLtGroupAssignments = '{
          "5": {
            "ltRole":"readonly",
            "ldapRole":""
          },
   .... and other roles below it
        }';
```
When an LDAP user logged in their LDAP data is jumbled, 
* their email address was a strange concatenation of their firstnamedomainname 
* their name showed only their first name
* their phone number does not pull in

**Leantime Version**
2.2.9

**Server**
NGINX 

**PHP / MySQL Version**
8.1 / 5.7

**Additional context**
The original problems were described to our developer in this video. Please review to better understand the problems (3 mins)
* https://www.youtube.com/watch?v=XpFpWEXrMew
He has resolved all the problems with the single exception of the phone number which we will fix later.  

I would like to contribute these code fixes to the project.  **I have attached a zip file with those 2 modified files**. The following files have been modified.
![image](https://user-images.githubusercontent.com/121611/199362394-99d33885-9554-45e0-b60b-3af4d2abe28b.png)

These are important fixes as the program is not usable for LDAP environments otherwise.  I would be grateful if you could apply these to the project so future releases do not revert the improvements made.  Sorry about this method, I am not sure of the proper procedure.

[leantime.zip](https://github.com/Leantime/leantime/files/9914677/leantime.zip)

Of note: our configuration.php LDAP section is structured like this:
```
    public $ldapKeys = '{
        "username":"cn",
        "groups":"memberof",
        "email":"mail",
        "firstname":"givenname",
        "lastname":"sn",
        "phonenumber":"telephoneNumber"
        }';
```

**Comment by marcelfolaron** [comment]
Thank you! I can add those changes to master!

**Comment by compumatter** [comment]
Great.  The phone number import has also been fixed overnight.  I'll pass that along when my dev tells me which code was modified to complete it.  Also, is this the best method to contribute?  If you have another method just let me know.

**Comment by marcelfolaron** [comment]
The usual method to contribute is via Pull Requests.
You can create a PR by "forking" the repository into your github account
and applying the changes there. Then head to
https://github.com/Leantime/leantime/pulls and create a new Pull Request
from your fork to the Leantime Master branch.

**Comment by compumatter** [comment]
Ok Marcel.  If this looks like something I'll be doing more of, I'll use that approach.  I think however this nails the last of the LDAP issues I needed to put in place.  At least for now.

Here is the phone number fix.  Please apply this to the master also as it was not completed in the last code sent.

File:  src/domain/ldap/services/class.ldap.php

Function - public function getSingleUser($username)

```
REPLACE <<$attr = array($this->ldapKeys->groups, $this->ldapKeys->firstname, $this->ldapKeys->lastname,$this->ldapKeys->email);

WITH >>$attr = array($this->ldapKeys->groups, $this->ldapKeys->firstname, $this->ldapKeys->lastname,$this->ldapKeys->email,$this->ldapKeys->phonenumber);
```
This of course requires that the $ldapKeys in configuration.php is set properly which in our case is:
```
public $ldapKeys = '{
"username":"cn",
"groups":"memberof",
"email":"mail",
"firstname":"givenname",
"lastname":"sn",
"phonenumber":"telephonenumber"
}';
```
