### ISSUE TITLE
[BUG] Display bug in chrome while in dark mode

### ISSUE THREAD

**Issue by hnegadi** [Leantime/leantime#1102]
In chrome, the sprints in the todos page menu looks like this in Dark Mode:
![image](https://user-images.githubusercontent.com/501818/199648903-84186ec3-8cff-4653-8ba0-334d14e3d894.png)

It looks like this in Firefox:
![image](https://user-images.githubusercontent.com/501818/199649026-63ff37b2-e911-41bb-83be-a614e5efb924.png)

**Comment by marcelfolaron** [comment]
Thanks for the submission. Will take a look
