### ISSUE TITLE
Error when trying to create milestone

### ISSUE THREAD

**Issue by houseofbugs** [Leantime/leantime#111]
When trying to add a milestone the page just forever loads and sends out the email. When you click the link this is what is received:

`Notice: Undefined property: stdClass::$editFrom in /home/userfolder/public_html/pm/src/domain/tickets/controllers/class.editMilestone.php on line 57

Notice: Undefined property: stdClass::$editTo in /home/userfolder/public_html/pm/src/domain/tickets/controllers/class.editMilestone.php on line 58`

**Comment by houseofbugs** [comment]
Just an update. If I do not select a start/end date I can add them. Any thoughts?

**Comment by marcelfolaron** [comment]
Hi, 
thanks for submitting. I will take a look and report back

**Comment by houseofbugs** [comment]
Thanks! Let me know if there it anything I can test. I am on MySQL 5.6 and PHP 7.4, I can change PHP to other versions but 7.4 is what our platform is hosted on for this site. Apache as well.

**Comment by houseofbugs** [comment]
I think I know what was happening. If I make a task and also add a discussion comment before creating the task that is what the issue is. Maybe have the discussion box hidden on the new task box until it is created?

**Comment by marcelfolaron** [comment]
You are correct. I just noticed that as well. The discussion box should not be visible. 
Also the headline validation is not quite correct. Fixing this now and adding a new release.

**Comment by marcelfolaron** [comment]
Done. New release was cut (all of this was really good timing, I had planned to cut a release today)
