### ISSUE TITLE
[BUG] Duplicating a project messes up dates

### ISSUE THREAD

**Issue by martinkoutecky** [Leantime/leantime#1113]
I take a project whose first milestone is April 1 2022. Click Duplicate, set new starting date to be March 29 2024. Look at the newly created project -- it's first task begins on March 29 **4024**.

Leantime 2.2.10, Docker.

**Comment by marcelfolaron** [comment]
I've been trying to reproduce this issue. Which language are you using?

**Comment by martinkoutecky** [comment]
English shows in Leantime, but my environment is cs_CZ, and it might be
picking up on this. (Still not a RTL language though...)

Dne čt 10. 11. 2022 12:07 uživatel Marcel Folaron ***@***.***>
napsal:

**Comment by martinkoutecky** [comment]
@marcelfolaron Still happening in 2.2.11.

**Comment by marcelfolaron** [comment]
Finally found the date issue.
