### ISSUE TITLE
[BUG] Spanish File

### ISSUE THREAD

**Issue by jarscr** [Leantime/leantime#1114]
Hello, I update to 2.7 to 2.10, and don't load many words, I try to add to es_ES.ini, but don't load text.

Maybe lost the order.

In the headlines lost the order new words, and add in line 87 new word, if organice the order is easy collaborate with the new words, can add English words in the Spanish or another lang, and can change to spanish.

Thanks

**Comment by marcelfolaron** [comment]
Hi, 
If I understand correctly it appears that the spanish file is not loading correctly after changes. Leantime caches the language files. When making updates it is best to set $debug=1 in the configuration file to turn off caching of lanugage file. Loggging out and back in will also clear the cache.

**Comment by marcelfolaron** [comment]
Please go to [crowdin.co ](https://crowdin.com/project/leantime) for translations
