### ISSUE TITLE
[BUG] Docker container continues running after httpd service fails to spawn

### ISSUE THREAD

**Issue by pbarnum** [Leantime/leantime#1116]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Leantime via Docker Compose failed to successfully spawn `httpd` and stopped trying after a few attempts, however the container continued to run as normal. I manually had to run `docker-compose down && docker-compose up -d`.

**To Reproduce**
1. Run lean time in a container
2. Wait for the service to go down. Sorry, I didn't do much else.

**Expected behavior**
The docker container exits with a exit code `> 0` so retry policies can kick in.

**Leantime Version**
`latest`

**Server**
Handled via official docker image

**PHP / MySQL Version**
Handled via official docker image

**Additional context**
Here are the logs from the leantime container starting after the typical HTTP request logs.
```
leantime       | Config file already exists!
leantime       | 2022-11-07 08:02:29,345 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
leantime       | 2022-11-07 08:02:29,349 INFO supervisord started with pid 6
leantime       | 2022-11-07 08:02:30,352 INFO spawned: 'php-fpm' with pid 7
leantime       | 2022-11-07 08:02:30,355 INFO spawned: 'httpd' with pid 8
leantime       | [07-Nov-2022 08:02:30] NOTICE: fpm is running, pid 7
leantime       | [07-Nov-2022 08:02:30] NOTICE: ready to handle connections
leantime       | 2022-11-07 08:02:30,510 INFO exited: httpd (exit status 0; not expected)
leantime       | 2022-11-07 08:02:31,517 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
leantime       | 2022-11-07 08:02:31,519 INFO spawned: 'httpd' with pid 11
leantime       | 2022-11-07 08:02:31,577 INFO exited: httpd (exit status 0; not expected)
leantime       | 2022-11-07 08:02:33,581 INFO spawned: 'httpd' with pid 12
leantime       | 2022-11-07 08:02:33,637 INFO exited: httpd (exit status 0; not expected)
leantime       | 2022-11-07 08:02:36,641 INFO spawned: 'httpd' with pid 13
leantime       | 2022-11-07 08:02:36,697 INFO exited: httpd (exit status 0; not expected)
leantime       | 2022-11-07 08:02:36,697 INFO gave up: httpd entered FATAL state, too many start retries too quickly
```

**Comment by marcelfolaron** [comment]
Is this still an issue?

**Comment by pbarnum** [comment]
Hey @marcelfolaron, it looks like you closed this issue as soon as you asked if it was still happening! Yes, it indeed is. Just today I had to tear down the stack and bring it back up to get it working again. I added a custom health check for the service but it's not fault proof unfortunately.

**Comment by marcelfolaron** [comment]
Thanks, reopening it and will take another look

**Comment by marcelfolaron** [comment]
I just added a few config changes to the supervisor config. 
I haven't been successful reproducing this issue so I am going a little blind.

**Comment by pbarnum** [comment]
Sorry for the late response but I think that is fine. I'll help as much as I can, though I am converting my server to run off Kubernetes so this might become less of an issue for me in the future.

Unfortunately I don't see much else in the logs other than what I originally posted. The service continues to run "normally" yet all requests fail. I also noticed that the `httpd` daemon cycles a few times before permanently giving up within a few seconds (6 seconds according to my logs). One way to test this is to see what happens if you manually kill `httpd` within the container (perhaps multiple times in short succession) and see what happens.

Either way, I think if there is nothing that can be done through the existing code base, you could instead add instructions for others to set up their own health checks. Below is the one I used, though I'm not sure if it is the best moving forward.
`docker-compose.yml`
```yml
    healthcheck:
      test: ['CMD', '/health.sh']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
```
`health.sh`
```sh
code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:80)
# I didn't bother to try and work around the 303 status code
if [ "${code}" != "303" ]; then
    exit 1;
fi
```

**Comment by marcelfolaron** [comment]
Thank you!

**Comment by MFYDev** [comment]
I am keeping meeting this problem now on the latest docker image, can anyone help?
