### ISSUE TITLE
Local file upload/image issues

### ISSUE THREAD

**Issue by marcelfolaron** [Leantime/leantime#112]
This is a tracking issue for the two issues regarding logo and profile picture uploads (#106 & #109 ).
Images are not displayed correctly in certain situations.  Still trying to determine why.

Please verify and submit:
- Permissions on the local folder
- PHP Version
- Leantime Version
- Any notices/warning/php errors when opening the image via right click (should be a path like download.php?...)
- Server
- Operating system

@quangbahoa and @GhaziTriki please let me know if you can find any additional info on the issue.

**Comment by quangbahoa** [comment]
- Dir permissions  755. Upload worked. I'm currenly running WP.
- PHP 7.4
- LT 2.0.8
- No error notices return.
- LEMP Stack by RunCloud
- Ubuntu 18.04LTS on AMZ Lightsail

**Comment by marcelfolaron** [comment]
Thanks, when you open the download.php?... file do you get a 404 back or just a blank screen?

**Comment by quangbahoa** [comment]
> Thanks, when you open the download.php?... file do you get a 404 back or just a blank screen?

download.php show a small square ^^!

**Comment by marcelfolaron** [comment]
Okay, I believe it has to do with the fpassthru() function and how it sends the file to the client. Can you try to replace line 82 and 83 in your download.php 

```
  fpassthru($fd);
  fclose($fd);
```

with

```
  while (!feof($fd)) {
     $buffer = fread($fd, 2048);
     echo $buffer;
   }
   fclose($fd);
```

**Comment by marcelfolaron** [comment]
I reverted back to the fread. This should be fixed now
