### ISSUE TITLE
[BUG] - Login asks for email address - our LDAP uses 'username'.

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1130]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Login assumes email addresses are being used.  It's hard to call this a 'bug' but it's certainly not a 'feature' either :-)

**To Reproduce**
Go to the login page and view the login field placeholder text "Enter email address"

**Expected behavior**
Enter email address or username

**Leantime Version**
2.2.9

**Server**
Nginx

**PHP / MySQL Version**
8.1 / 5.7

**Additional context**
We are LDAP only and are using the username as the login.  So our first employee using Leantime today saying she was unable to login.  I was able to login with her account just fine so was confused why she couldn't.  After visiting with her she showed me that she was typing in the email address as indicated.  When she changed it to the firstname.lastname username format we use, she logged right in.

This will be a problem for any company that uses LDAP and the 'username' format for logins.

![image](https://user-images.githubusercontent.com/121611/201238519-e2de6f91-e20c-401d-9855-3577b2d03a73.png)

**Comment by marcelfolaron** [comment]
Just so I understand the problem right: we’ll need to replace the text in
the input field from “Enter email address” to “Enter Username” if ldap is
used. I guess a secondary option is to say email or username.

**Comment by compumatter** [comment]
Yes that's it.  Though a lot of LDAP setups will use the email address as the login.  It's a configuration choice for LDAP admins.  So I suspect the best choice will be "email or username" or similar.  In that way you're covered either way.  It just turns up a failure in cases where LDAP admins use 'username' and their employees are being told to enter an email address when they get there.
