### ISSUE TITLE
[BUG] Images Won't Upload with Discussion Comments

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1140]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
When someone adds a discussion comment and uploads an image, the comment gets made but the image fails as a 404 and never becomes visible.

**To Reproduce**
1. Login to Leantime
2. Respond to a discussion 
3. Upload an image from your computer
4. Click Save to store the comment and the image.
5. 
**Expected behavior**
The image should be visible within the discussion trail as it was uploaded.

**Leantime Version**
2.2.11

**Server**
NGINX

**PHP / MySQL Version**
8.1 / 5.7

**Additional context**
I have created a video for you to make the problem very obvious:

- https://www.youtube.com/watch?v=0V1bWuO506k

**Comment by TareqK** [comment]
Same issue here, on all image uploads(including PFP)
