### ISSUE TITLE
[Feature] Expanded Subtask Functionality - Too limited to utilize

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1143]
**Is your feature request related to a problem? Please describe.**
Yes. It's a problem.  When I attempt to use the Subtask feature (which is often) I find I cannot enter enough information to make the feature usable.  It is only a single field and tasks require more detail than that.

**Describe the solution you'd like**
At a minimum, the UI that pops up for adding a subtask should have
* A subtask title
* The subtask wysywig where unlimited detail of the task could be added
Upon saving, the clickable Titles for each subtask could represent the visible rows of subtasks. When clicked on their entire subtask detail would be revealed.

In a more perfect world, there would be the ability to add discussions related to the subtask itself.

In an even more perfect world the subtask GUI would be an iterative version of the parent task ie; columns, draggable to its progress point (**though I recognize this is a large undertaking and not being requested**)

**Additional context**
I have take some time to create a video for you to make my problem and the reason for this.  

- https://www.youtube.com/watch?v=46ZzrgrwOAo

**Comment by sgissi** [comment]
Disclamer: I'm just an user, not related to the actual project developement. I have managed a few projects with Leantime and usually, if I need too much detail in a subtask, it was because my breakdown was too high-level. I ended up making these actual tasks. But I agree that a more complete subtask (e.g. with attachments, discussion, etc.) would be beneficial.

**Comment by compumatter** [comment]
@sgissi of course a balance between subtasks and must always be struck.  That said, a single text field does not constitute a subtask.  More like a sub-thought :-)  The real power will come in two solutions.   Certainly a more complete sub-task.  At least a GUI and ideally attachments and discussion.  Absolutely we agree.   That said, an additional robust solution is the sub-project.  In this way if it IS still a sub-task but too big to be considered as either a task or sub-task but a needed piece of the grand puzzle, a sub-project will allow much larger and more complex projects to be embraced.    I am speaking on behalf of company / corporate use here and not individuals.  Individuals can get by without that.

**Comment by gloriafolaron** [comment]
Updating this as on roadmap as some variation of this is in plan.
