### ISSUE TITLE
[BUG] current project timesheets shortcut on the left toolbar vanished

### ISSUE THREAD

**Issue by hnegadi** [Leantime/leantime#1153]
This more e regression than a bug, apologies in advance to submit this not as a feature request... But this feature has been present from the ground up and it just vanished upon the new GUI design.

It's a real pain to have put filters on daily basis to try to read where the current project is in terms of logged workforce.
We used to access this data within a single click.
We beg you to bring back this shortcut, even if we would need to change a config file in order to.

Thank you in advance.

**Comment by marcelfolaron** [comment]
Hi, 

I understand that this is frustrating. We are spending a lot of time to make sure the menu structure focuses on the execution of a project. The timesheet link in there represents more of a reporting tool and so we decided to take it out.

With that said, I changed the timesheet menu point in the headermenu to default to the currently selected project. This way you should be able to get to the same view as before from the top menu. This will go out with the next release
