### ISSUE TITLE
[BUG] The 'person-to-do' page 't-shirt size' isn't shown elsewhere.

### ISSUE THREAD

**Issue by rivimey** [Leantime/leantime#1155]
**Describe the bug**
On the personal to-do page, the T-Shirt size (S/M/L/XL etc) is shown as a select box, which is great, but it is not displayed elsewhere (such as in the Kanban board).

**Expected behavior**
The T-short size displayed beside the priority (medium, et al) in the Kanban task card. Possibly elsewhere.

**Leantime Version**
2.2.11

**Server**
Apache

**PHP / MySQL Version**
php 8.1, Mariadb 10.8

**Comment by marcelfolaron** [comment]
The effort label is shown in the table view. Please update to the latest version
