### ISSUE TITLE
A role suggestion

### ISSUE THREAD

**Issue by evanlabs** [Leantime/leantime#121]
When using leantime, we want to restrict the permissions of the "manager" role to the scope of the specified client. Or you can add a "leader" role with only a specified client scope?
The current "manager" role does not allow us to better limit the scope of management.

Thank you very much, leantime is great.

**Comment by marcelfolaron** [comment]
Thanks for reaching out.
Is the thought that this leader/adjusted manager could create and manage all projects within the scope of the assigned clients? Are there any other restrictions/permissions you need?

**Comment by evanlabs** [comment]
Yes, this makes each team leader more secure.
It is recommended to retain the manager role for compatibility with current users.

**Comment by evanlabs** [comment]
Here are the use cases:
Case 1: Assuming the user created is a leader role, only the projects under the client are allowed to be created or managed.
Case 2: If there is no leader role, you can specify the team leader when assigning project members. The member role can be any role, and the team leader member can have all management rights of the project.
I think case 2 is more flexible.

**Comment by evanlabs** [comment]
![leantime_leader](https://user-images.githubusercontent.com/739115/75685728-02ec0380-5cd6-11ea-8435-5b1d473562c0.png)

**Comment by evanlabs** [comment]
Client leader role and project team leader have project setting permissions,
Project team leader can specify multiple users with developer role.

The above are just ideas for project management permissions.

**Comment by marcelfolaron** [comment]
Thank you, that graphic is very helpful! 
So in that chart it looks like the project lead would have access to 
1. Add team members to a project
2. Change the project settings
3. Manage everything else regarding that project (delete things, create things etc)

I'd be happy to add that role I just want to make sure I fully understand the use case: 

Would they be able to create new projects within a client?
Would they be able to  delete projects?

**Comment by evanlabs** [comment]
Yes, I think so too.

The project leader does not allow the project to be created in the client and cannot delete the project.

**Comment by evanlabs** [comment]
The client leader has management rights for all client projects.
The project leader only has the project management permissions granted,

The client leader has higher authority than the project leader, and can create and delete projects for the client and manage multiple clients.

**Comment by marcelfolaron** [comment]
Thank you, that helps.
I am reworking some of the permission code so I should be able to include
those new roles. I like the granularity and I think it makes sense for
larger organizations.

**Comment by evanlabs** [comment]
Awesome, very looking forward.

**Comment by marcelfolaron** [comment]
Included in 2.1-beta
