### ISSUE TITLE
Issues with new install of 2.0.11

### ISSUE THREAD

**Issue by rlederhilger** [Leantime/leantime#122]
I'm trying to make a change in: /setting/editCompanySettings to the company logo and am seeing the following in my error logs:

[Thu Feb 27 00:31:18.539705 2020] [php7:warn] [pid 18951] [client xxxxxxxxxxxxxxx] PHP Warning:  move_uploaded_file(/var/www/html/leantime/public/userfiles/df4c1b963539ea1ad24ca8e3abf0bc4a.png): failed to open stream: Permission denied in /var/www/html/leantime/src/core/class.fileupload.php on line 249, referer: http://xxxxxxxxxxxxxxx.com/setting/editCompanySettings

[Thu Feb 27 00:31:18.539756 2020] [php7:warn] [pid 18951] [client xxxxxxxxxxxxxxx] PHP Warning:  move_uploaded_file(): Unable to move '/tmp/php6vNQUd' to '/var/www/html/leantime/public/userfiles/df4c1b963539ea1ad24ca8e3abf0bc4a.png' in /var/www/html/leantime/src/core/class.fileupload.php on line 249, referer: http://xxxxxxxxxxxxxxx.com/setting/editCompanySettings

**Comment by marcelfolaron** [comment]
Hi, thanks for reaching out. This seems to be a folder permission problem. I gather from the file path that you are on Linux. Are you running Apache? The userfiles/ folder needs to be owned by the Apache user (default on Ubuntu is www-data). So executing the command `chown -R www-data:www-data /var/www/html/leantime/public/userfiles ` should do the trick

**Comment by rlederhilger** [comment]
> Hi, thanks for reaching out. This seems to be a folder permission problem. I gather from the file path that you are on Linux. Are you running Apache? The userfiles/ folder needs to be owned by the Apache user (default on Ubuntu is www-data). So executing the command `chown -R www-data:www-data /var/www/html/leantime/public/userfiles ` should do the trick

I updated the permissions, but am still getting the same errors.  Here are the permissions on /var/www/html/leantime/public/userfiles: 
 
drwxr-xr-x. 2 apache apache 4.0K Feb 24 06:57 userfiles

**Comment by marcelfolaron** [comment]
Couple of thoughts, first lets make sure the entire directory structure has the correct permissions and owners. Seems apache is running as apache user?

```
chown -R apache:apache /var/www/html/leantime/
```

then setting the permissions for all folders:

```
find /var/www/html/leantime -type d -exec chmod 755 {} +
```

If that doesn't work, the next place I would look is SELinux. You can try to disable it temporarily and see if that fixes the issue

```
sudo setenforce 0
```

If that is fixing the issue you can add the userfiles folder to SELinux using:

```
sudo chcon -t httpd_sys_rw_content_t /var/www/html/leantime/public/userfiles -R
sudo chcon -t httpd_sys_rw_content_t /var/www/html/leantime/userfiles -R
```

turn SELinux back on

```
sudo setenforce 1
```

More detailed instructions on SELinux can be found here:
https://www.serverlab.ca/tutorials/linux/web-servers-linux/configuring-selinux-policies-for-apache-web-servers/

**Comment by rlederhilger** [comment]
The issue was SELinux!  I should have thought of that :(

Thank you! All is resolved :)

**Comment by marcelfolaron** [comment]
I am glad that worked. Thanks for your patience. Let me know if you have
any questions or feedback on Leantime!
