### ISSUE TITLE
[BUG] Strip HTML tags in exported CSV file from todos table

### ISSUE THREAD

**Issue by lakshmanan-mk** [Leantime/leantime#1220]
**Describe the bug**
whenever i exported the data from the todo table view to csv. The exported csv file is having data in HTML tag format like, the title column data comes between span tag, some other data comes with div element, input HTML tags

**To Reproduce**
1. Go to 'To-Dos.'
2. Click on 'kanban view to table view'
3.  Click on 'Export Button'
4.  Check the downloaded document

**Expected behavior**
I want exported data with plain text in CSV file

**Leantime Version**
2.2.10. 

**Server**
xampp

**PHP / MySQL Version**
PHP  8.1.2 and Mysql 15.1

**My Output From CSV File**
Check the data from the one of the column Planned Hours from excel sheet
<input type="text" value="0" name="planHours" class="small-input" onchange="leantime.ticketsController.updatePlannedHours(this, '20'); jQuery(this).parent().attr('data-order',jQuery(this).val());">

**Comment by marcelfolaron** [comment]
This should have been fixed in one of the previous versions. Please update to the latest and let me know if this is still an issue.

**Comment by kav2k** [comment]
Still an issue in latest 2.3.6.

Exports the last unnamed column corresponding to triple-dot menu (as HTML dump of the menu)
