### ISSUE TITLE
[bug] no longer working in firefox

### ISSUE THREAD

**Issue by bluebrad** [Leantime/leantime#1227]
I can get to the login in chrome but not firefox now on version 2.3.2 updated from 2.2.11
![image](https://user-images.githubusercontent.com/6026548/210044329-7f40cf0b-8206-43fd-9852-628f1bf5a40e.png)
![image](https://user-images.githubusercontent.com/6026548/210044340-0aa5e241-109c-4e75-b8ad-793dd0f890f4.png)

I tried clearing cookies and a full browser refresh

Fatal error: Cannot declare class leantime\domain\controllers\header, because the name is already in use in /home/bbtask/public_html/src/domain/pageparts/controllers/class.header.php on line 11

**Comment by ballinger** [comment]
same issue here for firefox and chrome. iwas logged in and edited a bit of stuff after the update to 2.3 inside firefox. all was good, when i got back it was blank... automatic logout issue or something? checked the site through firefrox android after reading this post and i can log in...

**Comment by marcelfolaron** [comment]
Any erros in the console or in logs/error.log?

**Comment by ballinger** [comment]
not a single entry in the log. thats what i see in the browsers console

`Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://raw.githubusercontent.com/Leantime/leantime/master/public/images/Screenshots/Ideas.png [Ideas.png](https://raw.githubusercontent.com/Leantime/leantime/master/public/images/Screenshots/Ideas.png)
Unknown property ‘-moz-border-radius’.  Declaration dropped. [codemirror.css:244:22](chrome://devtools/content/shared/sourceeditor/codemirror/lib/codemirror.css)
Elements matching selector: .CodeMirror pre.CodeMirror-line, .CodeMirror pre.CodeMirror-line-like
NodeList []
DataCloneError: Promise object could not be cloned.`

**Comment by marcelfolaron** [comment]
Seems the issue is related to an empty theme selection in the cookie. 
I have a fix ready. Clearing out all cookies should work though.

**Comment by ballinger** [comment]
clearing out cookies is not working for me on three different desktop browsers. still can login on android tough..

**Comment by Vozodo** [comment]
I have the same problem. I have updated from 2.2.11 to 2.3.2 and when I open the URL, only a white page opens. The log/ says:
PHP Fatal error: Cannot declare class leantime\domain\controllers\header, because the name is already in use in /leantime/src/domain/pageparts/controllers/class.header.php on line 11

Even with different browsers + cookie clear it doesn't work.

**Comment by marcelfolaron** [comment]
Should be fixed with 2.3.3

**Comment by ballinger** [comment]
working, thanx!

**Comment by marcelfolaron** [comment]
Thanks for confirming @ballinger 
@Vozodo please update to 2.3.3

**Comment by Vozodo** [comment]
It works now! Thanks for the fast update!

**Comment by bluebrad** [comment]
FIXED!
