### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by NickNck** [Leantime/leantime#123]
Hi I've just recently downloaded the new version of leantime and im hosting it in the wwwroot folder of IIS on windows server. I've made sure that apache and sql services are running. I have also configured my configuration.php file with the database name and credentials. But when i open the website via the public folder in the "localhost/leantime/public" link, it automatically changes to "localhost/install" and i get an error saying "HTTP Error 404.0 - Not Found
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." Please advise on what to do.

Thanks

**Comment by marcelfolaron** [comment]
Hi, we haven't done a lot of testing on IIS but one thing that I notice is that you will need to point your domain (localhost) to the public folder directly. We currently don't support subfolder installations (eg localhost/leantime or domain.com/leantime).

You can redirect a domain to point to a different folder using the directions here: https://weblogs.asp.net/owscott/iis-url-rewrite-hosting-multiple-domains-under-one-site

In your case you would have to point localhost to /leantime/public

We are working on subfolder support and should have something ready soon

**Comment by NickNck** [comment]
Hi thanks for the reply. Will try the steps and let you know the results. Thanks a lot

**Comment by NickNck** [comment]
Hi, i have applied what you suggested and pointing the domain directly to the public and i am still getting the same error. Even though when i try to navigate to the installation script i get the following error "Fatal error: Uncaught Error: Class 'leantime\core\config' not found in C:\inetpub\wwwroot\leantime\src\install.php:3 Stack trace: #0 {main} thrown in C:\inetpub\wwwroot\leantime\src\install.php on line 3."

**Comment by marcelfolaron** [comment]
Thanks for working on that! Two things:
First make sure you renamed the configuration.sample.php to
configuration.php

Second: IIS doesn't support htaccess files which handle the redirect. Two
options here:
A. You could install: http://www.helicontech.com/ape/
Which enables htaccess support
B. You could add a web.config to public/ with translated rules.

This is the output from an online htaccess to web.config converter
(untested).

```
<rule name="rule 1I" stopProcessing="true">
<match url=".*"  />
<action type="Rewrite" url="/https://%{HTTP:Host}%{REQUEST_URI}"  />
</rule>
<rule name="rule 2I">
<match url="^resetPassword$"  />
<action type="Rewrite" url="//index.php?resetPassword=true"  />
</rule>
<rule name="rule 3I">
<match url="^resetPassword/([^/\.]+)/?$"  />
<action type="Rewrite" url="//index.php?resetPassword=true&amp;hash={R:1}"
/>
</rule>
<rule name="rule 4I">
<match url="^install$"  />
<action type="Rewrite" url="//index.php?install=true"  />
</rule>
<rule name="rule 5I">
<match url="^install/([^/\.]+)/?$"  />
<action type="Rewrite" url="//index.php?install=true"  />
</rule>
<rule name="rule 6I">
<match url="^update"  />
<action type="Rewrite" url="//index.php?update=true"  />
</rule>
<rule name="rule 7I">
<match url="^update/([^/\.]+)/?$"  />
<action type="Rewrite" url="//index.php?update=true"  />
</rule>
<rule name="rule 8I">
<match url="^/?$"  />
<action type="Rewrite" url="//index.php?act=dashboard.show"  />
</rule>
<rule name="rule 9I">
<match url="^([^/\.]+)/([^/\.]+)/?$"  />
<action type="Rewrite" url="//index.php?act={R:1}.{R:2}"
appendQueryString="true" />
</rule>
<rule name="rule 10I">
<match url="^([^/\.]+)/([^/\.]+)/([^/\.]+)/?$"  />
<action type="Rewrite" url="//index.php?act={R:1}.{R:2}&amp;id={R:3}"
appendQueryString="true" />
</rule>
```

I'd love to get IIS working and  update our documentation.

**Comment by NickNck** [comment]
No problem at all, i will try the following resolutions and let you know. Also, i have made sure the configuration.php file is renamed since before and also i installed the dependencies thinking that could be the issue, but to no resolve. I will install what you have proposed.

Thanks for the quick reply!

**Comment by NickNck** [comment]
I've installed helicon ape and created the web.config file but now i get a different error:

HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.

Config Source:
    1: <rule name="rule 1I" stopProcessing="true">
    2: <match url=".*"  />

**Comment by marcelfolaron** [comment]
So I believe you don't need to do both. Either use the plugin or the
web.config.

I'd try removing the web.config first.

**Comment by NickNck** [comment]
Removed it, whats funny is that when i host on iis i get the error (find attached) when i go to the src/install.php. But if i try hosting it using XAMP with apache and mysql running i get the error "Fatal error: Uncaught Error: Class 'leantime\core\config' not found in C:\xampp\htdocs\leantime\src\install.php:3 Stack trace: #0 {main} thrown in C:\xampp\htdocs\leantime\src\install.php on line 3". But when using XAMP, and go to the public folder i get redirected to the XAMP dashboard automatically.

**Comment by marcelfolaron** [comment]
Oh, so you shouldn't go to src/install.php directly.

To install you should be able to go to:
<<Domain>>/install

If that doesn't work try opening

<<Domain>>/index.php?install=true

If the second link opens up the install page we know that it is an
.htaccess problem.

If that doesn't open anything (404) the domain is not pointing to the
correct directory. I have it running in xampp on my windows machine. You'll
have to make sure that your vhost config is pointing to /path to
httpdocs/leantime/public

Something like:

```

<VirtualHost *:80>
    DocumentRoot "/domainpath/leantime/public"
    ServerName www.servername.com
    # Other directives here
</VirtualHost>

```

**Comment by NickNck** [comment]
Good news, slowly getting somewhere. Your suggestion works and the installation page pops up although the page is incomplete as in missing images etc.

**Comment by NickNck** [comment]
Hi quick update, leantime is fully functional now using WAMPSERVER. However, i can only access the site locally using the domain name i used to map the public folder, but i cannot access the site using the domain name on another computer on the same network. I've searched the net for a few solutions such as editing vhost.config file to require all granted but i still canot access it remotely on another computer.

**Comment by marcelfolaron** [comment]
Were you able to figure out the domain issue? Seems to me that this is a networking/windows problem. Can you confirm and close the issue if that is the case?

**Comment by NickNck** [comment]
Yes managed to.
