### ISSUE TITLE
[BUG] drop down menu not changing status

### ISSUE THREAD

**Issue by bluebrad** [Leantime/leantime#1235]
![image](https://user-images.githubusercontent.com/6026548/210097319-3d484d6b-e29e-4650-93f3-3ea47c050a11.png)
![image](https://user-images.githubusercontent.com/6026548/210097723-2ddfc02e-0549-4504-8685-c1e83c37499d.png)
![image](https://user-images.githubusercontent.com/6026548/210098690-b7388248-c4eb-4a26-bc9d-4c849b71a537.png)

Still unable to use the drop down to change the status any ware! the only way I can change the status is when editing the task/item. 
When i select an item sometimes it adds "..." but nothing changes

**Comment by marcelfolaron** [comment]
That is odd. Any errors in your error log or in the inspector?

**Comment by bluebrad** [comment]
can we connect directly? brad at bluebrad dot com

**Comment by bluebrad** [comment]
> That is odd. Any errors in your error log or in the inspector?

can we connect directly? brad at bluebrad dot com

**Comment by bluebrad** [comment]
[Fri Dec 30 10:02:41.943506 2022] [authz_core:error] [pid 8717:tid 140718572189440] [client *****:59755] AH01630: client denied by server configuration: /home/****/public_html/api, referer: https://tasks.***.***/tickets/showKanban

**Comment by bluebrad** [comment]
I change the htaccess and now its working. something is connecting outside 

RewriteEngine On
RewriteRule ^(.*)$ public/$1 [L]

and added 
![image](https://user-images.githubusercontent.com/6026548/210100336-e818caf2-113d-49f9-bfae-401d4a0b2be3.png)

**Comment by bluebrad** [comment]
the drop downs are now working?
