### ISSUE TITLE
[BUG] Edit user is not working

### ISSUE THREAD

**Issue by lakshmanan-mk** [Leantime/leantime#1236]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
I installed the latest update 2.3.2. Everything fine for me but the edit user is not working. when I try to update user data, its refreshes the page when I submit, nothing was updated.

**To Reproduce**
1. Go to 'User Management.'
2. Click on 'Any User'
3. Update any profile information or project assignment

**Expected behavior**
Edit user page need to update the user data

**Leantime Version**
2.3.2

**Server**
Apache

**PHP**
PHP 8.1.2

**Comment by lakshmanan-mk** [comment]
**Found the solution for this issue** 
 Form Token is missing. So add it as hidden input

1. Open this file
\src\domain\users\templates\editUser.tpl.php

2. Add this code to the form
` <input type="hidden" name="<?=$_SESSION['formTokenName']?>" value="<?=$_SESSION['formTokenValue']?>" />`

**Comment by marcelfolaron** [comment]
Fixed in 2.3.4
