### ISSUE TITLE
[BUG] German Translation Incomplete

### ISSUE THREAD

**Issue by datWeazel** [Leantime/leantime#1239]
**Describe the bug**
German Translations are incomplete and some variations of the german translation are missing strings altogether.

Screenshots:
[https://imgur.com/a/nWiU745](https://imgur.com/a/nWiU745)

**Leantime Version**
Version 2.3.3

**Server**
**PHP / MySQL Version**
((Using Docker Image))

**Comment by marcelfolaron** [comment]
Translations are being managed via https://crowdin.com/project/leantime
