### ISSUE TITLE
[BUG] Dark theme custom colors not working

### ISSUE THREAD

**Issue by datWeazel** [Leantime/leantime#1240]
**Describe the bug**
Setting either Primary Color or Secondary Color in Company Settings doesn't change anything when using dark theme. Light theme users will see the custom colors.

[https://i.imgur.com/XFZGpcp.png](https://i.imgur.com/XFZGpcp.png)

**Leantime Version**
Version 2.3.3

**Server**
**PHP / MySQL Version**
((Using Docker Image))

**Comment by marcelfolaron** [comment]
Fixed in 2.3.4
