### ISSUE TITLE
[BUG] configuration.php color changes have no effect

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1243]
I know there is an ability to control colors within Company Settings > Admin

However, there is also these configs in configuration.php
    public $defaultTheme = 'default';                     //Default theme
    public $primarycolor = '#1b75bb';                     //Primary Theme color
    public $secondarycolor = '#81B1A8';                   //Secondary Theme Color

Since they are there I am guessing they are supposed to override any UI level changes.
Perhaps they are just no longer used?
Perhaps there is a session stuck so the change is not propogating?

1. Edit the configuration.php file
2. Change any of the above values and nothing changes on the site.  Just for a test I used
    public $defaultTheme = 'dark';                     //Default theme
    public $primarycolor = '#000000';                     //Primary Theme color
    public $secondarycolor = '#FF0000';                   //Secondary Theme **Color**

**Leantime Version**
Which Leantime version are you using
2.3.3

**Server**
NGINX

**PHP / MySQL Version**
5.7 / 8.1

**Additional context**

If this is not intended to be an override of the UI values, is there a CLI method to alter these primary / secondary colors.  I am installing it via Ansible and would like that to be set upon first open.

**Comment by marcelfolaron** [comment]
The config variables are the first level the UI overrides the config. 
Let me double check but that is how it's supposed to work.

**Comment by compumatter** [comment]
Hello Marcel.  The curiosity there is the UI comes with those values filled in during the first install.  So that would seem to make the values in configuration.php unavailable.  I ended up using a mysql query during install to overwrite the values of companysettings.primarycolor and ...secondarycolor so that solved my need.  However you may want to pull those from configuration.php if they no longer have a purpose.

**Comment by marcelfolaron** [comment]
Closing this for now as we are moving to .env files and it is expected that the ui values override the config values
