### ISSUE TITLE
[BUG] uploading logo has no effect

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1244]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**

I have tried using the UI to upload a logo.  I have tried using the dimensions 220px x 40px.  I have tried png, jpg and also gave an svg a try.

The file does upload and if I look at the properties of the image displayed in the console I can see it went to the userfiles folder.
![image](https://user-images.githubusercontent.com/121611/210298490-2f260874-cfaf-409e-b67d-de65372d3374.png)

In each case the logo did not change from the default provided.  I tried different browsers, clearing cache and no effect was shown.

Method Used:
Company Settings > Select File > Cropped image

**Expected behavior**
Expected the logo to appear. 

**Leantime Version**
2.3.3

**Server**
NGINX

**PHP / MySQL Version**
5.7 / 8.1

**Additional context**
If I manually insert my own login in public/images/logo.svg 
in place of the leantime default logo, it does display as expected. 

I noticed the database has a zp_settings table and companysettings.logoPath column.
Uploading new logo images DO change the value of that column and you can see here it matches what was uploaded 
![image](https://user-images.githubusercontent.com/121611/210298444-f1bdd908-0f75-4752-bdcc-5891450a1849.png)

So it appears the userfiles logo is just not being called to display.

**Comment by scv1503** [comment]
Same situation

**Comment by marcelfolaron** [comment]
Fixed in 2.3.4

**Comment by marcelfolaron** [comment]
Correction, Issue not fully resolved yet.
