### ISSUE TITLE
Timesheet type issue

### ISSUE THREAD

**Issue by NickNck** [Leantime/leantime#125]
Good day,
Ive noticed an issue when saving a timesheet and choosing the type option which includes "General (Billable), project management etc". If i choose an option such as project management or anything else it always gets saved as General (Billable).

**Comment by alexsynth** [comment]
Hi I am also geting same issue with timesheet type. It only displays general billable after saving

**Comment by marcelfolaron** [comment]
Thanks, I'll take a look and will send out a fix as soon as possible.

**Comment by NickNck** [comment]
Thanks

**Comment by NickNck** [comment]
Just noticed it would also be useful if we could edit timesheet details such as projects, To-Dos, etc for previously saved timesheet values

**Comment by NickNck** [comment]
Hi i found the issue of why it only posts General (Billable) when a timesheet is saved. The issue lies within the showMy.tpl.php file on line 329. How can we set this line of code to display the chosen type value instead of this fixed value?

**Comment by marcelfolaron** [comment]
Hi, I found the issue. 
It is a combination of issues in the controller and repo. I will cut a release today that will include the fix

**Comment by NickNck** [comment]
Thanks a lot. Love the quick response and support from your team!

**Comment by marcelfolaron** [comment]
Thank you! Happy to help!

**Comment by marcelfolaron** [comment]
Should be fixed now

**Comment by NickNck** [comment]
Thanks, will take a look
