### ISSUE TITLE
[FEATURE] Add Public Facing Surveys and Forms

### ISSUE THREAD

**Issue by TareqK** [Leantime/leantime#1250]
**Is your feature request related to a problem? Please describe.**

When doing product research or working on PMF, one of the best tools available to product owners and teams is the use of client surveys to help them hone in on the solutions. At the moment, there are a lot of survey tools available; some closed source, some open soruce.

Leantime already has implemented qualitative insights using ethnographic interviews, observations, and focus groups. However, we dont have any sort of quantitative insights that we can refer to to create data-driven decisions. While the Designing thinking framework implemented is extremely useful for emphasizing and ideation, validation of those ideas is still something that is done outside of leantime.

Its a greatly missed opportunity, and having  quantitative tools to validate ideas alongside the  qualitative tools to find them would cement leantime as a best-in-class PMF targeting and implementation solution

**Describe the solution you'd like**

At the moment, details are thin, however, I imagine that there are a few parts to this

1. A Form Builder, that is used to build the fields, set form visibility(public,private) and the corresponding timeframes of the form
2. A Form Sending mechanism, perhaps by a share link or a mass email to a mailing list
3. A Place to answer the form
4. A Place to see the data of the form, such as distributions, ratios, recurring answers, demographics(if demographics are somehow implemented), and grouping and filtering. 
5. A Reflection of the form results, and a way to reference them on a board of some kind - this could be its own board, but my initial preference/lizard brain thinking is saying this belongs on the observe-insights board. 

Forms should have the following fields, but these may be expanded upon

1. Short  Text(email, ad-hoc, minimum and maximum length ranges)
2. Long Text
3. Numeric(with range validation)
4. Single Select
5. Multi Select
6. Likert scale(basically single select)
7. Range Scale(basically numeric)
8. True/False
9. File Upload

Each of these items may be optional or mandatory. In the case of the selects, options would be added during form creation. An important enhancement that may be added to single selects is an "other" option that allows for ad-hoc text - but this is not a must.

For each of these we would need the following statistics

1. Short Text -> we may be able to perform keyword extraction from these and to produce distributions of key word. This is flimsy, but nice to have, But Not Needed
2. Long Text -> same as short Text, But Not Needed
3. Numeric -> mean, mode, quartiles, median, distribution(potentially by bucket size)
4. Single Select -> distribution
5. Multi select -> distribution
6. Likert Scale -> distribution
7. Range Scale -> mean, mode, quartiles, median, distribution(potentially by bucket size)
8. True/False -> distribution
9. No Statistics

Additionally, it should  be possible to download the raw data of the form in a CSV format with all the relevant attached files, in case further analysis is to be carried out in an external system.

Lastly, It should be possible to add meta-data fields not for analysis, but for fitlering(or using form fields for filtering by values or value ranges). However, an export button would allow us to defer this to a later time.

**Comment by gloriafolaron** [comment]
Trying some new labels -- this is an interesting idea. Needs Review for mapping out and then we should chat on if this makes sense as a plugin or core? And forums preference first, I'd guess?

**Comment by marcelfolaron** [comment]
As of 3.2.0 we are supporting Zapier integrations. This would allow a flow like this. The alpha app is available here https://zapier.com/developer/public-invite/207240/cac6ec7a911bd5fa7924f38230d58d2f/
