### ISSUE TITLE
[BUG] CSS on the to-do page glitched

### ISSUE THREAD

**Issue by bluebrad** [Leantime/leantime#1261]
![image](https://user-images.githubusercontent.com/6026548/211098769-313b322c-a746-4dbc-87b6-6070816d1182.png)
when i load the page it show correctly but when it finishes loading its like it unloads. 
![image](https://user-images.githubusercontent.com/6026548/211099043-55f616f1-3f28-4581-aa91-94f357d0790a.png)

**Comment by marcelfolaron** [comment]
Can you make sure to clear your cache. This looks like an old css file.

**Comment by bluebrad** [comment]
yes, I did and tried other computers and browsers with the same result.
also a fresh install is doing the same.
looks like there is a bad js code loading an old file once the pages is
loaded and looking for cookies offsite?
see the error code that was in the original post

**Comment by g05357005** [comment]
Seems problems is on .dataTable td.dropdown-cell 

After remove its height setting, display is good now.

**Comment by SerdaOzun** [comment]
This bug affects the "Milestone"  -> table view as well. So seems to be tables in general

**Comment by marcelfolaron** [comment]
What browser is this happening on?

**Comment by bluebrad** [comment]
both firefox and chrome
something with the js

**Comment by marcelfolaron** [comment]
Got it, I’ll test some more. Right now I can’t reproduce it but I’ll check
if there was something wrong with the release package.

**Comment by bluebrad** [comment]
would you like to directly connect with me? and i can provide server
access?
brad at bluebrad dot com

**Comment by rivimey** [comment]
I have also encountered this problem after updating from 2.2.11 to 2.3.4. I ended up applying the following changes (this is from the firefox 'change' tab):

```
diff -ru /tmp/leantime/public/css/components/tables.css ./css/components/tables.css
--- /tmp/leantime/public/css/components/tables.css      2023-01-04 18:22:50.000000000 +0000
+++ ./css/components/tables.css 2023-01-09 20:00:21.812001901 +0000
@@ -462,3 +462,33 @@
     top:35px;
 }

+
+/* tables.css | https://project.ivimey.org/css/components/tables.css */
+
+.dataTable td.dropdown-cell .dropdown > a {
+  /* border-radius: 0px !important; */
+  /* padding: 8px 10px 0px 10px !important; */
+  /* line-height: 17px; */
+  border-radius: 5px !important;
+  padding: 0px 8px 0px 8px !important;
+  line-height: 20px;
+}
+
+.dataTable td.dropdown-cell {
+  /* padding: 0px; */
+  /* height: 17px; */
+  padding: 0px 3px;
+  height: 20px;
+}
+
+.dataTable td.dropdown-cell .dropdown > a .text {
+  /* float: left; */
+}
+
+/* style.default.css | https://project.ivimey.org/css/components/style.default.css */
+
+html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, font, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td {
+  /* line-height: 21px; */
+  line-height: 18px;
+}
+
```

**Comment by rivimey** [comment]
The use of floats is also causing a problem where the down-arrow slips off the button when the column collapses:

![Screenshot_20230109_223619](https://user-images.githubusercontent.com/1536678/211422058-6bfd83ce-1b1a-4538-9696-27848a648e54.png)

[this SS also shows the effect of a couple of other changes so that the --{color}--text-color: variables are used to set an appropriate text color for the new background]

**Comment by bluebrad** [comment]
not only firefox its also on chrome but chrome it looks better and on
firefox it is all glitched out
[image: image.png]
and on firefox i get this
[image: image.png]

**Comment by marcelfolaron** [comment]
Thank you for the support. @Brad it would be great if we could connect to
debug. Can you email me at marcel [at] leantime.io

**Comment by rivimey** [comment]
was my report no good?

**Comment by marcelfolaron** [comment]
Hi Ruth,

Thank you for your report and suggestions. The plan for the recent design
changes was to allow dropdowns to use the entire cell and reduce some of
the paddings. We noticed a lot of wrapped dropdown text and odd behaviour
which is why we opted for that design choice.

I will take a look at the font color as well to make sure the contrast is
high enough.

**Comment by bluebrad** [comment]
No. sorry miss under stood
i was asking if you would like for me to setup a test Port on my server to
use to test. other than what you just did.
this way you have another test platform open and ready to use.
