### ISSUE TITLE
[BUG] Users do not receive the invitation email.

### ISSUE THREAD

**Issue by albjunior** [Leantime/leantime#1266]
I created a project under "One Project Wonder" and when adding users, none of them receive the invite by email.

I expected invited users to receive the email to create their username and password.

Leantime Version: Version 2.3.4

**Comment by SerdaOzun** [comment]
Noticed this as well yesterday, but didn't get to writing a bug ticket

**Comment by marcelfolaron** [comment]
Do you have email set up via smtp or via mail() any errors in logs/error.logs ?

**Comment by marcelfolaron** [comment]
Oh, thank you! Let me check this right away.

**Comment by albjunior** [comment]
Ok, thank you! 

Do you need my company name to find my page on leantime.io?

**Comment by albjunior** [comment]
ok!
zedica@globo.com

**Comment by albjunior** [comment]
The email you asked me to send the subdomain and email information to, came with asterisks (***@***.***).

Sorry, I don't know if I understood correctly.

**Comment by marcelfolaron** [comment]
Well that is not helpful... Please send it to marcel at leantime.io

**Comment by albjunior** [comment]
email sent.

Thanks for your help.

**Comment by albjunior** [comment]
Hi Marcel,

After the adjustments you made, the functionality returned to normal.

Thank you very much!
