### ISSUE TITLE
Docker - Upgrade fail - missing zp_plugins table on DB

### ISSUE THREAD

**Issue by pablopoo** [Leantime/leantime#1268]
Hi, 
After an update from 2.2.11 to 2.3.4 I got the following error, on a docker container.

`127.0.0.1 -  09/Jan/2023:20:40:31 +0000 "GET /index.php" 500
NOTICE: PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'leantime.zp_plugins' doesn't exist in /var/www/html/src/domain/plugins/repositories/class.plugins.php:51

Stack trace:
#0 /var/www/html/src/domain/plugins/repositories/class.plugins.php(51): PDOStatement->execute()
#1 /var/www/html/src/domain/plugins/services/class.plugins.php(44): leantime\domain\repositories\plugins->getAllPlugins(true)
#2 /var/www/html/src/core/class.events.php(124): leantime\domain\services\plugins->getEnabledPlugins()
#3 /var/www/html/src/core/class.application.php(64): leantime\core\events::discover_listeners()
#4 /var/www/html/public/index.php(26): leantime\core\application->start()

}
  thrown in /var/www/html/src/domain/plugins/repositories/class.plugins.php on line 51
127.0.0.1 -  09/Jan/2023:20:40:33 +0000 "GET /index.php" 500
NOTICE: PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'leantime.zp_plugins' doesn't exist in /var/www/html/src/domain/plugins/repositories/class.plugins.php:51

Stack trace:
#0 /var/www/html/src/domain/plugins/repositories/class.plugins.php(51): PDOStatement->execute()
#1 /var/www/html/src/domain/plugins/services/class.plugins.php(44): leantime\domain\repositories\plugins->getAllPlugins(true)
#2 /var/www/html/src/core/class.events.php(124): leantime\domain\services\plugins->getEnabledPlugins()
#3 /var/www/html/src/core/class.application.php(64): leantime\core\events::discover_listeners()
#4 /var/www/html/public/index.php(26): leantime\core\application->start()

}
  thrown in /var/www/html/src/domain/plugins/repositories/class.plugins.php on line 51`

Thanks!

**Comment by pablopoo** [comment]
Hi,
found that after I updated the docker container, the db update script is not executed.
My mistake was that I persisted the whole config folder on a docker volume, instead of the configuration file only. Maybe will be better to ma the code version independent of the config files.

Thanks
Pablo

**Comment by marcelfolaron** [comment]
Oh I see, thanks for the insight. I agree the version should come from a
different place. I’ll make a note of that. I assume you were able to
resolve the issue?
