### ISSUE TITLE
Manager role cannot edit every editBoxLabel

### ISSUE THREAD

**Issue by evanlabs** [Leantime/leantime#127]
Manager role cannot edit every editBoxLabel, and the error page content location is strange

E.g. this link
https://myself.domain.name/setting/editBoxLabel&module=ticketlabels&label=NEW

**Comment by evanlabs** [comment]
![leantime_issue_001](https://user-images.githubusercontent.com/739115/75626909-71fa2700-5c06-11ea-8ba8-b9ea2b690e96.png)

**Comment by marcelfolaron** [comment]
Thanks for reporting. I found the issue and will send a fix out today.
