### ISSUE TITLE
[BUG] ONCE MAIN MENU IS HIDDEN THER IS NO WAY TO SHOW AGAIN.

### ISSUE THREAD

**Issue by paccmx** [Leantime/leantime#1276]
THE THREE LINES IN THE TOP LEFT HAND CORNER, ONCE CLICK HIDE THE SIDE MENU
![image](https://user-images.githubusercontent.com/107881696/211918382-fd4dc474-e63c-4d79-850a-9814cd470531.png)

AFTER THE MENU IS HIDDEN, THE LINES DISAPEAR AND THERE IS NO WAY TO MAKE THE MENUE REAPEAR, ADN YOU HAVE TO LOG OUT FOR IT TO APPEAR.
![image](https://user-images.githubusercontent.com/107881696/211918577-620cd8f8-0d03-4e40-96f3-12eb1cc6cf3c.png)

**Comment by hnegadi** [comment]
What version are you using ? We don't have that issue with 2.3.3

**Comment by paccmx** [comment]
2.3.4

**Comment by paccmx** [comment]
Apears to be a issue with microsoft edge

**Comment by marcelfolaron** [comment]
Thanks for the additional info. I will test in edge .

**Comment by hnegadi** [comment]
We confirm that this doesn't happen to us on firefox / chrome in 2.3.4
