### ISSUE TITLE
[BUG] Error 404 on attempt to add a sprint in table view

### ISSUE THREAD

**Issue by hnegadi** [Leantime/leantime#1287]
We have a 404 error displayed instead of the create sprint window ( not full http 404 I mean, please se attached screenshot ) when we try to create a sprint from the todos table view. The but does not happen in kanban view, we're still able to create sprints from it.
![image](https://user-images.githubusercontent.com/501818/212502241-221f7166-f248-4b8a-8465-bccb12ff7b93.png)

**Comment by marcelfolaron** [comment]
Thanks. Can confirm, just pushed a fix to master
