### ISSUE TITLE
[BUG] Unable to instert media

### ISSUE THREAD

**Issue by hnegadi** [Leantime/leantime#1288]
Each time we try to upload media in any edit widget that offers this option we end up with this
![image](https://user-images.githubusercontent.com/501818/212502568-66d7e164-2d60-4b08-873c-ff8894a1babf.png)

**Comment by marcelfolaron** [comment]
What type of media are you trying to insert? Is it local upload or external media?

**Comment by hnegadi** [comment]
This happens while uploading local mp4 files ( reasonable size, usually 480p, less than 50MB )

**Comment by hnegadi** [comment]
FYI, Embedding youtube videos works

**Comment by marcelfolaron** [comment]
The editor uses the html5 <video> tag to embed uploaded videos. MP4 in particular allows a few codecs that chrome does not support anymore. See this discussion for further information on supported codecs https://stackoverflow.com/questions/25131906/mp4-file-not-playing-in-chrome
