### ISSUE TITLE
[FEATURE] SUB TASKS DEPENDENT TO PRINCIPAL TASK

### ISSUE THREAD

**Issue by paccmx** [Leantime/leantime#1300]
SIMULAR TO THE WAY MILESTONES ARE DEPENDENT TO OTHER MILESTONES, THIS WOULD BE GREAT TO DO IN TASKS.  AS THERE ARE SEVERAL TASKS THAT DEPEND ON THE COMPLETION OF SUB TASKS IN ORDER TO BE COMPLETED.  INCOPERATING THEM INTO THE TASK TABLE, MAKE IT EASYIER TO ASIGN AND VIEW THE TASK COMPLETION PROCESS.

![image](https://user-images.githubusercontent.com/107881696/212774968-38c0e50c-8e15-4795-9d04-807a45d0756f.png)

**Comment by gloriafolaron** [comment]
We're going to be evaluating the role of subtasks -- I'm not sure if it's going to look just like this but we're looking at improvements. Marking this on roadmap.
