### ISSUE TITLE
[BUG] Css bug in sprints menu ( chrome only, works on firefox )

### ISSUE THREAD

**Issue by hnegadi** [Leantime/leantime#1302]
V2.3.5
Sprints menu displays like this in dark mode using chrome 
![image](https://user-images.githubusercontent.com/501818/212793094-1786e558-deab-4fc9-b312-33c5c1f56d90.png)
Display is fine in Firefox
![image](https://user-images.githubusercontent.com/501818/212793223-8185bf70-3562-4961-bb1a-5cbd4e7c02de.png)

**Comment by marcelfolaron** [comment]
This is fixed now as the sprint menu was moved to the header
