### ISSUE TITLE
[BUG] Error upon creating new todo or modifying existing one

### ISSUE THREAD

**Issue by hnegadi** [Leantime/leantime#1303]
The following happens upon creating new todo or modifying existing one:
![image](https://user-images.githubusercontent.com/501818/212794194-0bb78d7a-77be-4a7a-8ffc-3341aebab7f1.png)
However, the task is being created or modified properly at the end

**Comment by ayon115** [comment]
Facing the same problem. To do gets updated though. Using version 2.3.5

**Comment by marcelfolaron** [comment]
Any errors in logs/error.log ?

**Comment by ayon115** [comment]
Hello @marcelfolaron, I cleared the logfile in logs/error.log and re-created the issue. No log was found there. 
But I found the following in /var/log/nginx in the file leantime.error.log: 
`2023/01/19 04:51:58 [error] 2897114#2897114: *8711 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class "DOMDocument" not found in /var/www/html/leantime/app/domain/notifications/services/class.notifications.php:50
Stack trace:
#0 /var/www/html/leantime/app/domain/projects/services/class.projects.php(243): leantime\domain\services\notifications->processMentions()
#1 /var/www/html/leantime/app/domain/tickets/services/class.tickets.php(634): leantime\domain\services\projects->notifyProjectUsers()
#2 /var/www/html/leantime/app/domain/tickets/controllers/class.showTicket.php(191): leantime\domain\services\tickets->updateTicket()
#3 /var/www/html/leantime/app/core/class.controller.php(61): leantime\domain\controllers\showTicket->post()
#4 /var/www/html/leantime/app/core/class.controller.php(33): leantime\core\controller->executeActions()
#5 /var/www/html/leantime/app/core/class.frontcontroller.php(173): leantime\core\controller->__construct()
#6 /var/www/html/leantime/app/core/class.frontcontroller.php(95): leantime\core\frontcontroller::executeAction(" while reading response header from upstream, client: 45.120.114.172, server: pms.dhrubokinfotech.com, request: "POST /tickets/showTicket/218 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "pms.dhrubokinfotech.com", referrer: "https://pms.dhrubokinfotech.com/tickets/showKanban"
2023/01/19 04:51:58 [error] 2897114#2897114: *8711 open() "/var/www/html/leantime/public/js/libs/jquery.nyroModal/img/ajaxLoader.gif" failed (2: No such file or directory), client: 45.120.114.172, server: pms.dhrubokinfotech.com, request: "GET /js/libs/jquery.nyroModal/img/ajaxLoader.gif HTTP/2.0", host: "pms.dhrubokinfotech.com", referrer: "https://pms.dhrubokinfotech.com/css/components/nyroModal.css"`

**Comment by cburns56860** [comment]
I had the same issue and it was because i was missing the xml extension for php if that helps.

**Comment by ayon115** [comment]
I tried that, did not work for me unfortunately.

**Comment by marcelfolaron** [comment]
Hey, you are missing the DOM extension. It should come with XML but might be commented out.Check in your PHP.ini for 
extension=dom.so
or the disable-dom flag
https://stackoverflow.com/questions/44045478/how-do-i-enable-the-dom-extension-in-the-php-ini

**Comment by hnegadi** [comment]
We installed php-xml and edited /etc/php/8.2/apache2/php.ini
[image: image.png]
We are still having the issue.

**Comment by marcelfolaron** [comment]
Did you restart the server? We’re you able to set the $debug variable to 1
and see if there are any additional errors?

**Comment by hnegadi** [comment]
We did restart the server but the way we set the debug flag led to an error 500

**Comment by ayon115** [comment]
Update: Our php version is 8.1, installing php8.1-xml package fixed the issue for us.

**Comment by hnegadi** [comment]
We just did so, and we are now the issue looks like this:
![image](https://user-images.githubusercontent.com/501818/213981689-16842d56-233d-4ad6-b11e-f18c8dc794a5.png)

`Fatal error: Uncaught Error: Class "DOMDocument" not found in /var/www/leantime_2.3.5/vendor/league/html-to-markdown/src/HtmlConverter.php:113 Stack trace: #0 /var/www/leantime_2.3.5/vendor/league/html-to-markdown/src/HtmlConverter.php(91): League\HTMLToMarkdown\HtmlConverter->createDOMDocument() #1 /var/www/leantime_2.3.5/app/domain/notifications/services/class.messengers.php(228): League\HTMLToMarkdown\HtmlConverter->convert() #2 /var/www/leantime_2.3.5/app/domain/notifications/services/class.messengers.php(50): leantime\domain\services\notifications\messengers->discordWebhook() #3 /var/www/leantime_2.3.5/app/domain/projects/services/class.projects.php(193): leantime\domain\services\notifications\messengers->sendNotificationToMessengers() #4 /var/www/leantime_2.3.5/app/domain/tickets/services/class.tickets.php(634): leantime\domain\services\projects->notifyProjectUsers() #5 /var/www/leantime_2.3.5/app/domain/tickets/controllers/class.showTicket.php(191): leantime\domain\services\tickets->updateTicket() #6 /var/www/leantime_2.3.5/app/core/class.controller.php(61): leantime\domain\controllers\showTicket->post() #7 /var/www/leantime_2.3.5/app/core/class.controller.php(33): leantime\core\controller->executeActions() #8 /var/www/leantime_2.3.5/app/core/class.frontcontroller.php(173): leantime\core\controller->__construct() #9 /var/www/leantime_2.3.5/app/core/class.frontcontroller.php(95): leantime\core\frontcontroller::executeAction() #10 /var/www/leantime_2.3.5/app/core/class.application.php(116): leantime\core\frontcontroller::dispatch() #11 /var/www/leantime_2.3.5/public/index.php(26): leantime\core\application->start() #12 {main} thrown in /var/www/leantime_2.3.5/vendor/league/html-to-markdown/src/HtmlConverter.php on line 113`

**Comment by hnegadi** [comment]
Looks like it's related to our discord webhooks, just removing them now

**Comment by hnegadi** [comment]
Removing discord webhooks leads to another popup that says:
`Fatal error: Uncaught Error: Class "DOMDocument" not found in /var/www/leantime_2.3.5/app/domain/notifications/services/class.notifications.php:50 Stack trace: #0 /var/www/leantime_2.3.5/app/domain/projects/services/class.projects.php(243): leantime\domain\services\notifications->processMentions() #1 /var/www/leantime_2.3.5/app/domain/tickets/services/class.tickets.php(634): leantime\domain\services\projects->notifyProjectUsers() #2 /var/www/leantime_2.3.5/app/domain/tickets/controllers/class.showTicket.php(191): leantime\domain\services\tickets->updateTicket() #3 /var/www/leantime_2.3.5/app/core/class.controller.php(61): leantime\domain\controllers\showTicket->post() #4 /var/www/leantime_2.3.5/app/core/class.controller.php(33): leantime\core\controller->executeActions() #5 /var/www/leantime_2.3.5/app/core/class.frontcontroller.php(173): leantime\core\controller->__construct() #6 /var/www/leantime_2.3.5/app/core/class.frontcontroller.php(95): leantime\core\frontcontroller::executeAction() #7 /var/www/leantime_2.3.5/app/core/class.application.php(116): leantime\core\frontcontroller::dispatch() #8 /var/www/leantime_2.3.5/public/index.php(26): leantime\core\application->start() #9 {main} thrown in /var/www/leantime_2.3.5/app/domain/notifications/services/class.notifications.php on line 50`

**Comment by hnegadi** [comment]
We have php 8.1 running with php8.1-xml package installed and we're still
having the same issue with 2.3.6
Please read below the debug message:

*Fatal error*: Uncaught Error: Class "DOMDocument" not found in
/var/www/leantime_2.3.6/app/domain/notifications/services/class.notifications.php:50
Stack trace: #0
/var/www/leantime_2.3.6/app/domain/projects/services/class.projects.php(242):
leantime\domain\services\notifications->processMentions() #1
/var/www/leantime_2.3.6/app/domain/tickets/services/class.tickets.php(555):
leantime\domain\services\projects->notifyProjectUsers() #2
/var/www/leantime_2.3.6/app/domain/tickets/controllers/class.newTicket.php(80):
leantime\domain\services\tickets->addTicket() #3
/var/www/leantime_2.3.6/app/core/class.controller.php(61):
leantime\domain\controllers\newTicket->post() #4
/var/www/leantime_2.3.6/app/core/class.controller.php(33):
leantime\core\controller->executeActions() #5
/var/www/leantime_2.3.6/app/core/class.frontcontroller.php(173):
leantime\core\controller->__construct() #6
/var/www/leantime_2.3.6/app/core/class.frontcontroller.php(95):
leantime\core\frontcontroller::executeAction() #7
/var/www/leantime_2.3.6/app/core/class.application.php(116):
leantime\core\frontcontroller::dispatch() #8
/var/www/leantime_2.3.6/public/index.php(26):
leantime\core\application->start() #9 {main} thrown in
*/var/www/leantime_2.3.6/app/domain/notifications/services/class.notifications.php*
on
line *50*


Thank you.

**Comment by marcelfolaron** [comment]
The XML extension is still not properly installed.
DomDocument is part of the XML extension. You may be missing the mbstring
extension too

sudo apt-get install php-mbstring


Install it php-xml via:

*PHP 8.2*

   - Ubuntu: apt-get install php8.2-xml
   - CentOS 8 [with php:remi-8.2 enabled]: dnf install php-xml

*PHP 8.1*

   - Ubuntu: apt-get install php8.1-xml
   - CentOS 8 [with php:remi-8.1 enabled]: dnf install php-xml

*PHP 8.0*

   - Ubuntu: apt-get install php8.0-xml
   - CentOS 8 [with php:remi-8.0 enabled]: dnf install php-xml


After the install make sure to restart the server.

**Comment by hnegadi** [comment]
Hello,

Please find below the log of a few command lines:


*php -v*
PHP 8.1.14 (cli) (built: Jan 13 2023 10:42:52) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.14, Copyright (c), by Zend Technologies


*apt install php-xml*
Reading package lists... Done
Building dependency tree
Reading state information... Done
php-xml is already the newest version (2:8.2+93+ubuntu18.04.1+deb.sury.org
+2).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.


*apt install php-mbstring -y*
Reading package lists... Done
Building dependency tree
Reading state information... Done
php-mbstring is already the newest version (2:8.2+93+ubuntu18.04.1+
deb.sury.org+2).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.


*cat /etc/php/8.1/apache2/php.ini | grep dom.so*
extension=dom.so

We will try to switch over to default php (8.2.1 ) and let you know

-H.

**Comment by hnegadi** [comment]
I think I found the reason why we are having trouble

Apache actually runs php8.0
phpinfo:
[image: image.png] <http://www.php.net/>PHP Version 8.0.27
System Linux prodzuki 4.15.0-202-generic #213-Ubuntu SMP Thu Jan 5 19:19:12
UTC 2023 x86_64
Build Date Jan 13 2023 10:42:30
Build System Linux
Server API FPM/FastCGI
Virtual Directory Support disabled
Configuration File (php.ini) Path /etc/php/8.0/fpm
Loaded Configuration File /etc/php/8.0/fpm/php.ini
Scan this dir for additional .ini files /etc/php/8.0/fpm/conf.d
Additional .ini files parsed /etc/php/8.0/fpm/conf.d/10-mysqlnd.ini,
/etc/php/8.0/fpm/conf.d/10-opcache.ini, /etc/php/8.0/fpm/conf.d/10-pdo.ini,
/etc/php/8.0/fpm/conf.d/20-calendar.ini,
/etc/php/8.0/fpm/conf.d/20-ctype.ini, /etc/php/8.0/fpm/conf.d/20-exif.ini,
/etc/php/8.0/fpm/conf.d/20-ffi.ini,
/etc/php/8.0/fpm/conf.d/20-fileinfo.ini,
/etc/php/8.0/fpm/conf.d/20-ftp.ini, /etc/php/8.0/fpm/conf.d/20-gettext.ini,
/etc/php/8.0/fpm/conf.d/20-iconv.ini,
/etc/php/8.0/fpm/conf.d/20-mysqli.ini,
/etc/php/8.0/fpm/conf.d/20-pdo_mysql.ini,
/etc/php/8.0/fpm/conf.d/20-phar.ini, /etc/php/8.0/fpm/conf.d/20-posix.ini,
/etc/php/8.0/fpm/conf.d/20-readline.ini,
/etc/php/8.0/fpm/conf.d/20-shmop.ini, /etc/php/8.0/fpm/conf.d/20-snmp.ini,
/etc/php/8.0/fpm/conf.d/20-sockets.ini,
/etc/php/8.0/fpm/conf.d/20-sysvmsg.ini,
/etc/php/8.0/fpm/conf.d/20-sysvsem.ini,
/etc/php/8.0/fpm/conf.d/20-sysvshm.ini,
/etc/php/8.0/fpm/conf.d/20-tokenizer.ini
PHP API 20200930
PHP Extension 20200930
Zend Extension 420200930
Zend Extension Build API420200930,NTS
PHP Extension Build API20200930,NTS
Debug Build no
Thread Safety disabled
Zend Signal Handling enabled
Zend Memory Manager enabled
Zend Multibyte Support disabled
IPv6 Support enabled
DTrace Support available, disabled
Registered PHP Streams https, ftps, compress.zlib, php, file, glob, data,
http, ftp, phar
Registered Stream Socket Transports tcp, udp, unix, udg, ssl, tls, tlsv1.0,
tlsv1.1, tlsv1.2, tlsv1.3
Registered Stream Filters zlib.*, string.rot13, string.toupper,
string.tolower, convert.*, consumed, dechunk, convert.iconv.*

However, when we do:
*a2dismod php8.0*

*a2enmod php8.1*
or

*a2enmod php8.2*
we have the following messages:



*Considering dependency mpm_prefork for php8.1:Considering conflict
mpm_event for mpm_prefork:Considering conflict mpm_worker for
mpm_prefork:Module mpm_prefork already enabled*
and apache fails to restart

Any hint ?

The issue is obviously on our end, thanks in advance for any help.

-H.

**Comment by hnegadi** [comment]
Switching all to php8.0 using
*sudo update-alternatives --config php*
installing *php8.0-xml *alongside enabling *extension=dom.so *in
*/etc/php/8.0/apache2/php.ini*
/etc/php/8.0/apache2/php.ini Fixed the issue on our end.
Not sure if it's recommended to use php8.0 though, still curious how to
properly make it work with 8.2
Keep you posted.

Thank you,

-H.
