### ISSUE TITLE
[BUG] Error 500 upon updating project settings

### ISSUE THREAD

**Issue by hnegadi** [Leantime/leantime#1307]
As far as I remember, we already posted this issue but we can't find it anymore in the list.
It rings a bell that I saw it staged but still have the bug in v2.3.5
Upon project settings save after edit we get an error 500 , however the project settings are properly updated when we come back to the root URL.
May there's some logs I could look into so we figure out if it's due to the way leantime is installed on our end ?

**Comment by marcelfolaron** [comment]
I couldn’t reproduce that issue. Do you see any errors in logs/error.log ?

**Comment by hnegadi** [comment]
[Wed Jan 18 02:22:56.872335 2023] [proxy_fcgi:error] [pid 8670] [client 192.168.1.254:64788] AH01071: Got error 'PHP message: PHP Warning:  Undefined property: leantime\\core\\config::$useLdap in /var/www/leantime_2.3.5/app/core/class.environment.php on line 87', referer: https://liveyard.tech:5547/projects/showProject/42

**Comment by hnegadi** [comment]
From what I read in the log, we use a relative symbolic link in /var/www/leantime > /var/www/leantime_2.3.5
I feel that this might be causing the issue

**Comment by hnegadi** [comment]
Tried to remove the symlink
Tried also run locally but still having the issue.

**Comment by marcelfolaron** [comment]
I tried several times to reproduce the issue but still can't. The error above wouldn't throw a 500. 
Can you set the $debug flag to 1 in your config file and see if there are any other errors?

**Comment by hnegadi** [comment]
Should config.php look like this ?

class config
{
  public $debug = 1

**Comment by marcelfolaron** [comment]
With a ; at the end.

**Comment by hnegadi** [comment]
Sorry for this newbie mistake, just fixed it, logs will come soon. Thank you.

**Comment by hnegadi** [comment]
We no longer have the bug since we did what's described in the issue #1303
thread ( last emails, xml dom related )

Thank you,

-H.
