### ISSUE TITLE
[BUG] can't delete discussion comment

### ISSUE THREAD

**Issue by hnegadi** [Leantime/leantime#1309]
when we click delete 
![image](https://user-images.githubusercontent.com/501818/213059228-88f3e59d-27b6-4225-a924-79d864eecf1d.png)
The editing task widget behaves like it's refreshing but the comment we tried to delete is still here

[Wed Jan 18 02:30:45.258375 2023] [proxy_fcgi:error] [pid 14051] [client 192.168.1.254:65000] AH01071: Got error 'PHP message: PHP Warning:  Undefined property: leantime\\core\\config::$useLdap in /var/www/leantime_2.3.5/app/core/class.environment.php on line 87', referer: https://liveyard.tech:5547/tickets/showKanban

**Comment by marcelfolaron** [comment]
Is that a specific user?
