### ISSUE TITLE
Download issue on leantime.io website

### ISSUE THREAD

**Issue by NickNck** [Leantime/leantime#131]
Hi it seems the zip file on the download page of leantime.io is corrupt

**Comment by marcelfolaron** [comment]
Any particular error you see? Can you try again?

**Comment by NickNck** [comment]
When i extract with winrar it says: 

 ! C:\Users\yanick.kumar\Downloads\Leantime-V2.0.12.zip: The archive is corrupt

**Comment by NickNck** [comment]
I tried a couple of times to, still the same corrupt error

**Comment by marcelfolaron** [comment]
Odd. I just re-zipped and uploaded the file again. Let me know if that
works.

Sincerely,
Marcel

**Comment by NickNck** [comment]
Realy weird, now it says "The file is either in unknown format or damaged"

**Comment by NickNck** [comment]
It seems to have extracted successfully using 7-zip, but the error continues with WinRar. Ill let you know if the extracted files run correctly when hosting.

**Comment by NickNck** [comment]
The files work correctly as does the features you've implemented so thank you very much. It would probably be wise to inform users to extract using 7-zip just in case

**Comment by marcelfolaron** [comment]
This seems strange as we are using the standard windows zip function. I'll do some more research and let you know what I can find.

**Comment by NickNck** [comment]
No problem. I noticed though that when i used 7-zip, an alert came up saying " unexpected end of data", but it didnt affect the extract process. Hope this helps

**Comment by ramsonline** [comment]
i just tried downloading+unzipping both files (latest + stable). No Error here Win10 + 7Zip...
Maybe a md5sum or sha256sum should be provided for the stable release so that users can verify the file after Downloading.

**Comment by marcelfolaron** [comment]
Thanks for verifying. I'll close this issue. We'll add the md5sum in future stable version releases
