### ISSUE TITLE
Update an existing Leantime Installation

### ISSUE THREAD

**Issue by ayon115** [Leantime/leantime#1310]
Is any documentation or user guide available to update an existing installation of Leantime to its latest version?

**Comment by Elaktrato** [comment]
Within your leantime installation there should be a updateLeantime.sh. You could try running that script.

**Comment by marcelfolaron** [comment]
As @Elaktrato mentioned updateLeantime.sh is probably the easiest way but you can also just download the zip file from the release page and then replace the files in your folder
