### ISSUE TITLE
[FEATURE] ToDo name instead of ID in Kanban

### ISSUE THREAD

**Issue by hnegadi** [Leantime/leantime#1314]
In kanban view todos are displayed this way ( Tak ID as the main highlighted title instead of task name as shown below
![image](https://user-images.githubusercontent.com/501818/213308726-61ce7dba-67b2-43b6-a82e-a05e6446d980.png)
Task name as main highlight would make it way more readable, like in the table view

**Comment by marcelfolaron** [comment]
The default action color is blue which should make it visible enough. It seems your main action color is set to grey?
