### ISSUE TITLE
LDAP options clean-up

### ISSUE THREAD

**Issue by sgissi** [Leantime/leantime#1319]
**Describe the bug**
The LDAP settings need cleanup as current settings have no effect and can mislead users. I'll be happy to provide a clean-up patch.

**Leantime Version**
2.3.5 / master

---

**ldapUserDomain**
Becomes userDomain at [LDAP class](https://github.com/Leantime/leantime/blob/master/app/domain/ldap/services/class.ldap.php#L65). It was used at [Auth class](https://github.com/Leantime/leantime/blob/master/app/domain/auth/services/class.auth.php#L208) but commented now. Not used anywhere else.

**bindUser / bindPassword**
Defined at both [configuration.sample](https://github.com/Leantime/leantime/blob/master/config/configuration.sample.php#L70-L71) and [defaultConfiguration](https://github.com/Leantime/leantime/blob/master/app/core/class.defaultConfiguration.php#L69-L70). It seems tied to the old LDAP implementation. It is not currently present on LDAP class. All current LDAP binds use user-provided credentials.

**baseDn**
Defined but not used anywhere. Probably used in the old LDAP implementation. All LDAP searches are bound by the ldapDN setting instead.

**Comment by marcelfolaron** [comment]
Hi, thanks. You are right, some clean up is required. 
Happy to review the patch if you have time. I won't be able to get to this until later this week

**Comment by sgissi** [comment]
Thanks Marcel. I opened #1329 to clean it up.

The [docs](https://github.com/Leantime/docs/blob/master/installation/configuration.md#ldap-configuration-beta) says LDAP is in Beta. Let me know when you consider it stable and I'll be happy to update the documentation to match the current LDAP configuration.
