### ISSUE TITLE
[Feature] New right: Client / product manager

### ISSUE THREAD

**Issue by jmassiaux77** [Leantime/leantime#1328]
New right: client / product manager (allow to manage projects and users linked to the client to which the manager is also associated)
This right must not allow to read / write on other clients / products projects.

**Comment by gloriafolaron** [comment]
@marcelfolaron For the sake of discussion, this is something we need to look at with the other requests for differentiated user roles.

**Comment by marcelfolaron** [comment]
This was implemented a while ago. Closing issue now :)
