### ISSUE TITLE
Feature Request: Printable Budget Hour Reports

### ISSUE THREAD

**Issue by alexsynth** [Leantime/leantime#133]
Hi, it would be very useful if we could get a feature that generates printable reports based on Total budget hour, actual hours and the difference between budget and actual hours for each project respectively.

As well as generate printable reports on timesheets on employees.

An example of the first point:

Project Name          Total budget hours      Actual Hours     Budget vs Actual Hours
Test project                      200                           150                             50

Total                                  200                           150                            50

**Comment by marcelfolaron** [comment]
Thank you for the request. We are working on more reports and this comes in at the right time.

**Comment by marcelfolaron** [comment]
As of 3.2.0 we are supporting Zapier integrations. This would allow a flow like this. The alpha app is available here https://zapier.com/developer/public-invite/207240/cac6ec7a911bd5fa7924f38230d58d2f/
