### ISSUE TITLE
[BUG] Gantt Diagramm centered to a date last year

### ISSUE THREAD

**Issue by sbamamoto** [Leantime/leantime#1340]
After upgrading to 2.3.6, I have an issue with the Gantt Diagram . The year 2021 is shown, but my project has milestones only in 2022. In version 2.3.4 the Gantt Diagram was always centric to the actual date.

I upgraded from 2.3.4 to 2.3.6 without any problems.

If I use the cursor keys to navigate in the Gantt Diagram everything is there, but when I change the view and return to the Gantt Diagram I always put scroll one year to the right, to see the actual tasks.

**Comment by marcelfolaron** [comment]
Thank you for submitting. I'll take a look
