### ISSUE TITLE
[BUG] after upgrade - 502 bad gateway on dashboard page

### ISSUE THREAD

**Issue by thewriteway** [Leantime/leantime#1341]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
opening http://x.x.x.x/dashboard/home produces "502 bad gateway error"

**To Reproduce**
1) upgrade install new zip package in www directory over existing installation
2) open dashboard page.

**Expected behavior**
dashboard page opens and renders properly

**Leantime Version**
2.3.6

**Server**
nginx

**PHP / MySQL Version**
PHP 8.1.14 and mariadb-server 10.5.18

**Additional context**
running leantime on "Debian GNU/Linux 11 (bullseye)" Arm 64 bit edition
h/w: Raspberry Pi 4

**Comment by thewriteway** [comment]
#6 /var/www/leantime/vendor/guzzleh" while reading response header from upstream, client: x.x.x.x, server: x.x, request: "PATCH /api/sessions HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "x.x.x.x", referrer: "http://x.x.x.x/auth/login"
2023/01/24 13:37:39 [error] 755#755: *1 FastCGI sent in stderr: "PHP message: Intervention\Image\Exception\NotSupportedException: GD Library extension not available with this PHP installation. in /var/www/leantime/vendor/intervention/image/src/Intervention/Image/Gd/Driver.php:19
Stack trace:
#0 /var/www/leantime/vendor/intervention/image/src/Intervention/Image/ImageManager.php(112): Intervention\Image\Gd\Driver->__construct()
#1 /var/www/leantime/vendor/intervention/image/src/Intervention/Image/ImageManager.php(68): Intervention\Image\ImageManager->createDriver()
#2 /var/www/leantime/vendor/lasserafn/php-initial-avatar-generator/src/InitialAvatar.php(593): Intervention\Image\ImageManager->canvas()
#3 /var/www/leantime/vendor/lasserafn/php-initial-avatar-generator/src/InitialAvatar.php(359): LasseRafn\InitialAvatarGenerator\InitialAvatar->makeAvatar()
#4 /var/www/leantime/app/domain/users/repositories/class.users.php(573): LasseRafn\InitialAvatarGenerator\InitialAvatar->generate()
#5 /var/www/leantime/app/domain/users/services/class.users.php(29): leantime\domai...PHP message: PHP Fatal error:  Cannot declare class leantime\domain\controllers\header, because the name is already in use in /var/www/leantime/app/domain/pageparts/controllers/class.header.php on line 0" while reading response header from upstream, client: x.x.x.x, server: x.x.x.x., request: "GET /dashboard/home HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "x.x.x.x", referrer: "http://x.x.x.x/auth/login"

**Comment by marcelfolaron** [comment]
Please install the php gd library extension

**Comment by thewriteway** [comment]
yes, fixed by adding the -gd library.

in case anyone else once to know the components needed, I used these: php8.1 php8.1-fpm php8.1-mysql php8.1-xml php8.1-gd

**Comment by thewriteway** [comment]
If you encounter an additional page error "500" it's due to mbstring being missing which you can check with debug in sys.config

to fix add the following additional php component: php8.2-mbstring

so with the latest PHP installed the prereq install cmd is now:
sudo apt install php8.2 php8.2-fpm php8.2-mysql php8.2-xml php8.2-gd php8.2-mbstring
