### ISSUE TITLE
Project Management Notifications - No way to clear the red notifications

### ISSUE THREAD

**Issue by Auren-Frost** [Leantime/leantime#1343]
I can only click on the notification to make it open the task that was edited/updated by someone else. No option to delete, mark as read, or clear all anywhere in the menu, even at the bottom of the list. 

![Screenshot 2023-01-24 233300](https://user-images.githubusercontent.com/120057912/214444442-b138edd6-ede6-48ac-9c1b-ef2c6ad17a04.png)

**Comment by marcelfolaron** [comment]
The notification is marked read when you click it. I guess we could add
another mechanism to mark read

**Comment by Auren-Frost** [comment]
That would be great. Sometimes, you get all the information you need just
by seeing someone edited it, but don't always want to view them.
