### ISSUE TITLE
[BUG] Leantime moves To-Dos from one project to another when working on another project's to-do when the login is not synced

### ISSUE THREAD

**Issue by Auren-Frost** [Leantime/leantime#1344]
**Describe the bug**
When my login has timed out, the pop up to log back in only shows up when I try to save something. Moving tasks on the kanban board is fine and typing in boxes is fine, but you lose everything the moment you try to save something. 

Due to the above bug, another one caused by this is having multiple projects. I was on Project 1 last time I was fully logged in and switched to Project 2 to edit a task. After saving, it prompted me to log back in which lost the new data I entered, **however** what it did do was take the task from Project 2 and plop it into Project 1. Unfortunately, since there is no way to transfer tasks between projects, this was an unfortunate bug.

**To Reproduce**
1. Be in a project idly until you might be timed out
2. Swap to a different project and go to To-Dos
3. Edit the To-Do of your choice and select save. You will be prompted to log in.
4. See that the task from the other project now lives in the original one but none of the recorded data is saved inside.

**Expected behavior**
I know this is likely just not a feature implemented yet, but it would resolve a lot of my troubles to have a feature like many other webpages where it warns the user at a minute until timeout if they want to continue or quit. Then, when the minute is up, it automatically logs out.

**Leantime Version**
Leantime 2.3.3

Server
NGINX

PHP / MySQL Version
PHP 8.1 / Mysql 5.7

**Additional context**
If need be, I can attempt to make a video capturing this, but waiting until it times out is a bit tricky as there's no way to really tell without letting it sit for a long time then testing.

Not sure if this is something that can be easily fixed, but it would be very helpful.

**Comment by marcelfolaron** [comment]
Thanks for the submission. There are a couple things in here, so we'll need
to split this bug apart.

As of 2.3.6 it is possible to move tasks between projects. So I strongly
recommend to update to the latest version

I think there is another interesting point in here, moving tasks on a
kanban board should show an error message or log you out if not logged in
anymore. It seems it is failing silently which I need to fix.

Sincerely,
Marcel

**Comment by compumatter** [comment]
Hello Marcel.  Auren is a CompuMatter employee.  I will upgrade us to 2.3.6 tomorrow :-)
