### ISSUE TITLE
[BUG] ICS export URL works only if user is signed in.

### ISSUE THREAD

**Issue by LightTemplar** [Leantime/leantime#1345]
**Describe the bug**
It's about this feature: https://github.com/Leantime/leantime/issues/975
I wanted to use export of ICS on permanent base, adding the URL to an organizer app. For this I need, that the generated URL works not only in my browser session. For now the generated URL gives ICS with ToDos only if call it in browser, where I've already signed in. If this does my organizer app, it gets an empty ICS. Also do I if I try the URL after signing out.

**To Reproduce**
1. If you don't have ToDos, add some with due date
2. go to your personal calendar.
3. Click on "Export" button.
4. Get the ICS Export URL. 
5. Try it in the same browser session and look into downloaded file.
6. Try first to sign out or in incognito mode. Look into downloaded file. 
7. Compare them.
8. Second file won't have your ToDos.. It will have an ICS structure, but without any of your ToDos.

**Expected behavior**
I want, that ICS Export URL works regardless of browser session. 

**Leantime Version**
2.3.6

**Server**
Hetzner Hosting, can't tell exact configuration.

**PHP / MySQL Version**
PHP 8.1,  MariaDB 10.5 (from Hetzner docs)

**Additional context**
I've tested it also with events - they are exported anyways. Only ToDos need user to be signed in.

**Comment by marcelfolaron** [comment]
Thanks for submitting. This is indeed a bug. It should just show the calendar. I will check
