### ISSUE TITLE
[BUG] Task table date sorting not working properly in d/m/y format

### ISSUE THREAD

**Issue by jmassiaux77** [Leantime/leantime#1346]
In task table view, the js sorting for date column don't work properly for d/m/y date format.

It order by day then by month.
The correct ordering method must be by month, then by day.

> lintime version : 2.3.9
> tested on Safari :  16.3 (18614.4.6.1.5) and chrome 109.0.5414.87

Regards

<img width="292" alt="Capture d’écran 2023-01-25 à 15 41 29" src="https://user-images.githubusercontent.com/123368774/214595064-106dbc32-6caf-4847-89ca-23e32c6e3176.png">

**Comment by jmassiaux77** [comment]
UP. This is very annoying on big projects.

**Comment by marcelfolaron** [comment]
Fixed in 2.3.11
