### ISSUE TITLE
[FEATURE] Project dashboard > Milestone list > Each milestone name link to task list filtered for this milestone

### ISSUE THREAD

**Issue by jmassiaux77** [Leantime/leantime#1349]
On project dashboard > Milestone list > Each milestone name could link to task list filtered for this milestone (instead of milestone edit modal) ?

Regards,
Jerome.

**Comment by marcelfolaron** [comment]
This was changed in 2.3.6. (Link now goes to task list)
Please let me know if that is not the case.

**Comment by jmassiaux77** [comment]
Ok, I'll check ASAP.

Thanks a lot for you work.
I'm using it for an entire class for training in management and business administration.

**Comment by marcelfolaron** [comment]
Oh that's awesome, would you mind reaching out to gloria [at] Leantime.io 
We are currently doing a bit more research on Leantime's usage in education and training. Would love to get your feedback.
