### ISSUE TITLE
[FEATURE] PDF export in canvas need to open in new TAB/Window

### ISSUE THREAD

**Issue by jmassiaux77** [Leantime/leantime#1352]
leantime 2.3.5

PDF export in canvas need to open in new TAB/Window (it's now not natural to use the navigator back button).

Also, PDF title maybe can be bigger ?

Regards,
Jérôme.

**Comment by marcelfolaron** [comment]
The PDF export was removed in favor of a optimized print view that allows you to print as pdf by default
