### ISSUE TITLE
[FEATURE] Alter the behavior of closing modals

### ISSUE THREAD

**Issue by davidleechen** [Leantime/leantime#1353]
**Is your feature request related to a problem? Please describe.**
Using modals to CRUD every type of "work item" is cool for not needing to navigate people around to different pages. There's a big caveat here in that most frontend frameworks allow click to close on the backdrop. This becomes a big headache because there is no confirmation when clicking on the backdrop and the modal closes, _losing all work_ done.

**Describe the solution you'd like**
There are a few solutions that could be appropriate, I don't know all of the types of usages for the software so I will give a few.
1. Start tracking dirty state on items so you can selectively block click to close on the backdrop of the modal. For a clean model state the default behavior could be click to close. For dirty model state, a confirmation dialog could be shown. This is a much bigger ask since I'm not familiar with what data binding happens in Leantime and it's usually a requisite to making this style of tracking work correctly. Either that or a lot of really messy jQuery.

**Additional context**
There were some other UX solutions that I deemed to be non-viable such as blocking click to close completely. There are a few ways to exit modals as it stands now, the Save & Close button, clicking on the backdrop, clicking the X close button, and hitting the escape key. The only one of these that should automatically close the modal without confirmation when changes have been made to a model is the Save & Close button. X can be clicked or tapped inadvertently resulting in data loss. Hitting escape can be done inadvertently resulting in data loss. Clicking the backdrop can be done inadvertently resulting in data loss. To cover all these modal-close scenarios, I believe dirty state handling is the solution.

This will probably apply to sections in a tabbed interface such as Discussion/comments, Time Tracking, etc. as well as modifications made to dropdowns like Assigned to, the Milestone selector, etc.

**Comment by marcelfolaron** [comment]
Hi, thanks for your detailed write up. 
We did disable click on backdrop as of 2.3.6 but the X and Esc click are still there. I like your idea of determining a "dirty" state to show a confirmation box.

**Comment by marcelfolaron** [comment]
As a stop gap solution I removed exiting via background click. You can still exit via X and Esc
