### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by juanyepesm** [Leantime/leantime#1369]
when i finish a task the percentage is still 0 in the gantt view, why?
![Tareas](https://user-images.githubusercontent.com/76126076/216083150-febe164c-e814-4f4a-b9e5-8ca6d3f55524.png)
![Gantt view](https://user-images.githubusercontent.com/76126076/216083151-a606dda4-146b-4d66-99d9-2fc2d6735650.png)

**Comment by marcelfolaron** [comment]
Oh I see now. It’s the task itself.
Thanks. Will find a fix for that.
