### ISSUE TITLE
[FEATURE] ldap_connect passed arguments are deprecated

### ISSUE THREAD

**Issue by b90g** [Leantime/leantime#1379]
**Is your feature request related to a problem? Please describe.**[
As in discussion in this PR https://github.com/Leantime/leantime/pull/1329#issuecomment-1416600613 the passed arguments are insufficient to connect to LDAP securely.

**Describe the solution you'd like**
- [ ] pass the full LDAP URI eg: ldaps://ldap.example.com:636
- [ ] pass a custom certificate for self signed certificates (eg Univention Corporate Servers OpenLDAP implementation) OR give option to ignore "invalid" certificates.

**Additional context**
https://www.php.net/manual/en/function.ldap-connect.php

**Comment by croftj01** [comment]
I need to use LDAPS and port 636 otherwise I can't use this software unfortunately...
