### ISSUE TITLE
[FEATURE] Add option for all users (any role in assigned project) to see files attached to project in the "Project Settings" section

### ISSUE THREAD

**Issue by romzeon** [Leantime/leantime#1384]
Hey, is it possible for all users (any role) to see files attached to project in the "Project Settings" section? I've found that only the role "Company Manager" have that permission. 
It would be nice to have such "general project files" will be visible in Project Dashboard for all users assigned to a project.
Thank you!

**Comment by gloriafolaron** [comment]
Thanks for the suggestion! We've definitely had a few requests for more adjustable role permissions and it's something we want to implement. I'm tagging this as On Roadmap with the caveat that we're still working through some of the complexities.

**Comment by marcelfolaron** [comment]
Files is now part of the main menu section
