### ISSUE TITLE
[BUG] Critical - LDAP Values removed in 2.3.6 config.php file

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1390]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
During the upgrade to version 2.3.6 I discovered required LDAP variables were absent in the config.php file

Here is my LDAP section of config.php in my current version 2.3.3

```
/*ldap default settings (can be changed in company settings) */
public $useLdap = true;
public $ldapType = 'OL'; // Currently Supported: OL - OpenLdap, AD - Active Directory
public $ldapHost = 'localhost';
public $ldapPort = 389;  //Default Port
public $baseDn = ''; //Base DN, example: DC=example,DC=com
public $ldapDn = '';  //Location of users, example: CN=users,DC=example,DC=com
public $ldapUserDomain = '';  //Domain after ldap, example @example.com
public $bindUser = '';
public $bindPassword = ''; 
```
In config.sample.php of the latest version 2.3.6 (just downloaded) it shows only these:
```
/* ldap default settings (can be changed in company settings) */
public $useLdap = false;                              //Set to true if you want to use LDAP
public $ldapType = 'OL';                              //Select the correct directory type. Currently Supported: OL - OpenLdap, AD - Active Directory
public $ldapHost = '';                                //FQDN
public $ldapPort = 389;                               //Default Port
public $ldapDn = ''; 
```
**LDAP will certainly fail to login without the variables**
```
public $baseDn = ''; //Base DN, example: DC=example,DC=com
public $ldapUserDomain = '';  //Domain after ldap, example @example.com
public $bindUser = '';
public $bindPassword = '';
```
**Leantime Version**
2.3.6

**Server**
NGINX

**PHP / MySQL Version**
8.1 / MariaDB 10

**Additional context**
I have added those variables / values manually by copying them in from my version 2.3.3 and was able to login.

**Comment by compumatter** [comment]
Strangely I am able to login even with the LDAP Administrators username and password missing.

I will ultimately have to test this with a fresh / new installation to know if there is an issue here.    Sorry for the premature post.

**Comment by marcelfolaron** [comment]
We changed the behavior a while ago since there was no reason to have an admin account do the ldab bind+search when we have to do the bind with the username+pw anyways. For that reason we removed it.

**Comment by compumatter** [comment]
Marcel,Thanks for the follow up. It leaves me wondering though since every ldap software I use requires it.  It may not matter but instinctually I'd recommend you look into they why / why not of this. Perhaps it's a two factor auth type of a thing to insure if someone knows a user credential they cannot create a hack app on that alone.  Perhaps it's insurance the outside world cannot brute force it with only the user creds.I suspect this is a security opening.Sincerely,JayJay LeporeCompuMatterOffice: 360 299 2428Cell: 360 202 ***@***.*** you are satisfied with your service, please consider providing us a social media review at https://compumatter.com/reviews...If you are not, please let me know so I can make it betterOn Feb 11, 2023, at 1:01 PM, Marcel Folaron ***@***.***> wrote:﻿
We changed the behavior a while ago since there was no reason to have an admin account do the ldab bind+search when we have to do the bind with the username+pw anyways. For that reason we removed it.
