### ISSUE TITLE
[BUG] Dashboard Redirects to 500 Error after LDAP login

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1391]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Immediately after logging (as an LDAP user) in I receive this image

![image](https://user-images.githubusercontent.com/121611/217386348-1c1122c3-43d4-446a-a951-3b15b8343491.png)
 
It also happens if I click the home button in the top right icon bar.

**Leantime Version**
2.3.6

**Server**
NGINX

**PHP / MySQL Version**
8.1 / MariaDB 10+

I have created a video for you:
* https://www.youtube.com/watch?v=-ktb0-J34Iw

**Comment by marcelfolaron** [comment]
Hi,

Do you see any errors in the logs/error.log file? I suspect this is a
missing extension.

**Comment by compumatter** [comment]
Marcel,

Thanks for the trail on the error log.  It shows this error upon login:

`PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
                    ORDER BY
                                            zp_tickets.date ASC
                                        LIMIT 1' at line 7 in /SM_DATA/web_projects/public_html/app/domain/tickets/repositories/class.tickets.php:950
Stack trace:
#0 /SM_DATA/web_projects/public_html/app/domain/tickets/repositories/class.tickets.php(950): PDOStatement->execute()
#1 /SM_DATA/web_projects/public_html/app/domain/projects/services/class.projects.php(69): leantime\domain\repositories\tickets->getNumberOfClosedTickets()
#2 /SM_DATA/web_projects/public_html/app/domain/dashboard/controllers/class.home.php(84): leantime\domain\services\projects->getProjectProgress()
#3 /SM_DATA/web_projects/public_html/app/core/class.controller.php(61): leantime\domain\controllers\home->get()
#4 /SM_DATA/web_projects/public_html/app/core/class.controller.php(33): leantime\core\controller->executeActions()
#5 /SM_DATA/web_projects/public_html/app/core/class.frontcontroller.php(173): leantime\core\controller->__construct()
#6 /SM_DATA/web_projects/public_html/app/core/class.frontcontroller.php(95): leantime\core\frontcontroller::executeAction()
#7 /SM_DATA/web_projects/public_html/app/core/class.application.php(116): leantime\core\frontcontroller::dispatch()
#8 /SM_DATA/web_projects/public_html/public/index.php(26): leantime\core\application->start()
#9 {main}
`

**Comment by marcelfolaron** [comment]
This is very interesting. I have not seen this before. Apparently it fails to build the query for the done tickets. I am wondering why. I assume this project has custom columns? Could you screenshot the project settings screen with the columns (or even better would be the entry in the zp_settings database with the key "projectsettings.XX.ticketlabels" where XX is the project id. It should be some serialized string

**Comment by marcelfolaron** [comment]
Just following up. So far I wasn't able to reproduce the issue with a variety of custom statuses, can you share your kanban status set up with me?

**Comment by compumatter** [comment]
Marcel,

sorry about the lack of feedback.  I've been on vacation but back on Wed.  Wil follow up the day I return 

thanks for reaching back on this issue !

**Comment by marcelfolaron** [comment]
I think I found the issue. It should be fixed in 2.3.11.

**Comment by compumatter** [comment]
Nice.  Good news.  Well done.
