### ISSUE TITLE
[BUG] Profile icon shows up as broken image link

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1392]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Profile icon now shows a broken image link

**To Reproduce**
If no image is supplied, it shows a broken image instead of the default initials of First / Last name.

**Expected behavior**
Two capital letters if no image available

**Leantime Version**
2.3.6

**Server**
NGINX

**PHP / MySQL Version**
8.1 / 8

**Additional context**
I have created a video for you to demonstrate the issue
* https://www.youtube.com/watch?v=LNhqTUmNB-c

**Comment by marcelfolaron** [comment]
Any errors for this in the error logs? Can you confirm that you have gd installed and enabled?
