### ISSUE TITLE
[BUG] Internal Server 500 error after changing the subtask of a todo

### ISSUE THREAD

**Issue by Loui5** [Leantime/leantime#1396]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Using the hosted version, domain is lgtest.leantime.io and was playing around trying to fumble my way around. Created a subtask of a todo and then back and changed the name and may have also created another subtask with no name.

**To Reproduce**
I cannot reproduce as I cannot access my instance, lgtest.leantime.io

**Expected behavior**
Able to change the subtask name.

**Leantime Version**
Which Leantime version are you using
Hosted version

**Server**
Apache, nginx, IIS etc
Hosted version

**PHP / MySQL Version**
Please list the PHP and Mysql version you are using
Hosted version

**Additional context**

**Comment by marcelfolaron** [comment]
Thanks for submitting the bug. We had short server issue about an hour ago
which caused several requests to fail.
Everything should be operational again.

Please let me know if you are still running into issues.

Sincerely,
Marcel

**Comment by marcelfolaron** [comment]
Great to hear.
No bricked instances on my watch :) also we have backups.
