### ISSUE TITLE
Error when deleting project discussion comments

### ISSUE THREAD

**Issue by aschrijver** [Leantime/leantime#140]
Clicking Delete on a Comment in Project Discussions tab first gives a PHP error. When then going 'back' in the browser it says 'Document Expired' and on a subsequent try cicking Delete gives 404 Page Not Found. Document expired does not occur in all cases, and sometimes pressing 'back' leads to the user being logged out (i.e. you see the Login screen). In all this the comment was not deleted.

This is the URL:
`https://leantime.example.org/projects/showProject/4/&delComment=3`

Tested in Firefox, both on Android and Ubuntu, LeanTime 2.0.12.

**Comment by marcelfolaron** [comment]
Thanks for reaching out. Found the issue and will submit a fix.
