### ISSUE TITLE
[BUG]/[FEATURE] Gantt vue bugs and improvment

### ISSUE THREAD

**Issue by jmassiaux77** [Leantime/leantime#1415]
leantime 2.3.9

Since 2.3.9, Gantt vue have been improved but some bugs are remaining and other stuff can be improved :

[BUG]
- [ ] Task ordering for each milestone seems to work partialy now (not totaly) but subtask seems to not been ordered for each task.  --> for this issue, I'll send you an email with a dev account on my server.
- [ ] label.subtask string isn't translatable

[improvment]
- [ ] Choosing between this vues : only milestones ; milestones and task ; milestones, task and subtasks
- [ ] Chossing to only show not finished task or all states (or choosing one of possible states ?)
- [ ] Filtering only one milestone
- [ ] Possibility to showing links/arrows, or not (when there are a lot of milestones, task and subtasks, the gantt vue become very crappy)
- [ ] Task and subtask could take same color than linked milestone ?

Regards,
Jérôme.

<img width="1726" alt="Capture d’écran 2023-02-12 à 14 43 26" src="https://user-images.githubusercontent.com/123368774/218314653-6c0259be-e354-445f-9561-24fba5701b41.png">

**Comment by gloriafolaron** [comment]
@marcelfolaron for visibility. Tagging as needs review.

**Comment by marcelfolaron** [comment]
Many improvements were made to the Gantt chart. Please review in 2.4
