### ISSUE TITLE
[BUG] PHP 8.2 Deprecated: Creation of dynamic property

### ISSUE THREAD

**Issue by jmassiaux77** [Leantime/leantime#1417]
leantime 2.3.9

With PHP 8.2, there are issues for each dynamic property :

"Deprecated: Creation of dynamic property leantime\core\environment::$xxxxxx" on "/app/core/class.environment.php on line yy"

With
- xxxxxx : $dotenv, $yaml, $sitename and so on
- yy : lines 23, 26,32, 33 and so on

Jerome.

**Comment by marcelfolaron** [comment]
Thank you. We are still working on full 8.2 support including fixing deprecated items. In the meantime I would sugges to turn off errors for deprecatations.

**Comment by marcelfolaron** [comment]
This was fixed
