### ISSUE TITLE
Fatal error on production install

### ISSUE THREAD

**Issue by nickian** [Leantime/leantime#1420]
Using PHP 8.0 and nginx.

Created .env in the config folder and filled in database credentials. Going to /install gives this error:

```
2023/02/13 01:40:40 [error] 3343#3343: *2375 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Dotenv\Exception\InvalidFileException: Failed to parse dotenv file. Encountered a missing closing quote at ['{]. in /var/www/html/vendor/vlucas/phpdotenv/src/Parser/Parser.php:30
Stack trace:
#0 /var/www/html/vendor/graham-campbell/result-type/src/Error.php(118): Dotenv\Parser\Parser::Dotenv\Parser\{closure}()
#1 /var/www/html/vendor/vlucas/phpdotenv/src/Parser/Parser.php(31): GrahamCampbell\ResultType\Error->mapError()
#2 /var/www/html/vendor/vlucas/phpdotenv/src/Dotenv.php(222): Dotenv\Parser\Parser->parse()
#3 /var/www/html/vendor/vlucas/phpdotenv/src/Dotenv.php(237): Dotenv\Dotenv->load()
#4 /var/www/html/app/core/class.environment.php(24): Dotenv\Dotenv->safeLoad()
#5 /var/" while reading response header from upstream, client: 192.168.50.243, server: mydomain.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.0-fpm.sock:", host: "mydomain.com"
```

**Comment by TareqK** [comment]
`` Encountered a missing closing quote at ['{]. in /var/www/html/vendor/vlucas/phpdotenv/src/Parser/Parser.php:30`` - can you double check for me your env file?

**Comment by eschricker** [comment]
I have the same error. I deleted the .env file and now use the configuration.php again. That works for me!

**Comment by m8than** [comment]
Gotta use configuration.php instead. Got the same issue with that.

**Comment by eschricker** [comment]
Did you remove/rename the .env-file?

**Comment by marcelfolaron** [comment]
It's most likely related to an issue with your ldap configuration. A space in between the = can have that effect. The .env format is an alternative for now. We are planning to move towards it over the long term but in the meantime we'll keep both configuration.php and .env

**Comment by nickian** [comment]
Yes, removing the .env fixed it, thanks. The README.md install instructions are not clear.

**Comment by eschricker** [comment]
> It's most likely related to an issue with your ldap configuration. A space in between the = can have that effect. The .env format is an alternative for now. We are planning to move towards it over the long term but in the meantime we'll keep both configuration.php and .env

@marcelfolaron 
I used the sample configuration and did not change any of the ldap settings. If it is related to the ldap-specific setting, then the sample.env should be updated. Additionally, the .env.sample file is referenced in the documentation (Installation (Production)): `Rename config/.env.sample to config/.env`. However, this file does not exist. There is only the file `sample.env`. Either the file should be renamed or the documentation should be updated.

**Comment by marcelfolaron** [comment]
Yeah the file should be renamed, I thought it was the 2nd step in the list
but I‘ll have to double check. I’ll also check the sample file and make
sure it works. Thanks for the feedback!
