### ISSUE TITLE
[BUG] Generating/editing api keys does not work when the application is not installed in the root directory of the server

### ISSUE THREAD

**Issue by diderich** [Leantime/leantime#1422]
Generating/editing api keys does not work when the application is not installed in the root directory of the server, i.e., if the URL is `www.example.com/leantime`.

The issue is with the following links in `app/domain/setting/templates/editCompanySettings.tpl.php`:

```html
<a href="<?=BASE_URL?>/setting/editCompanySettings/#/api/newApiKey" class="btn btn-primary">Generate API Key</a>
...
<a href="<?=BASE_URL?>/setting/editCompanySettings/#/api/apiKey/<?=$apiKey["id"] ?>">
```

**Comment by marcelfolaron** [comment]
Thank you! Missed the subfolder test here. Will get a fix out as soon as possible
