### ISSUE TITLE
[BUG] No project-specific links

### ISSUE THREAD

**Issue by davidleechen** [Leantime/leantime#1424]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
In a multi-project installation, it's impossible to link to a specific project's _xxx_, where _xxx_ could be:
1. Todo kanban or table view
2. Roadmap view
3. Any goal canvases
4. Any idea canvases
5. Any wiki article

**To Reproduce**
1. Have 2 projects
2. On project 1, go to Ideas
3. Click the dropdown and select 1 idea canvas to get a URL that has an ID in it like `/ideas/showBoards/12` (/ideas/showBoards is not helpful at all, this is a second bug IMO)
4. Copy the link
5. Change to project 2
6. Paste the link in the address bar and navigate there
7. Be shown the "create an ideas canvas" page because project 2 doesn't have one.

**Expected behavior**
I would expect URLs to be project specific and to always take you to the same place regardless of the currently active project. The route probably needs to contain the project ID, something like `/ideas/1/12` where 1 is the project ID and 12 is the idea canvas ID. This is kind of MVC backwards though and is missing a piece, I would really expect it to be `/projects/1/ideas/12`. Alternatively if the project ID that has a relation to the idea canvas ID is not the current one, then switch the currently active project.

**Leantime Version**
2.3.5

**Server**
Apache

**PHP / MySQL Version**
Whatever is in the container for 2.3.5

**Additional context**
There's an additional issue where modals don't change the navigation URL making it impossible to link to things like To Dos. If this is a separate bug or feature request let me know.

**Comment by marcelfolaron** [comment]
I think this is related to #1428 and is caused by the same underlying issue.

**Comment by komali2** [comment]
I've just deployed this tool a week back and so far loving it, but this is my primary confusion with it. I would love to be able to copy links to specific tickets to paste in Slack or whatever, or link to a project's general wiki, or a project's dashboard. 

Our usecase may be overloading what Leantime is intended for (we're basically replacing notion with it) but I think Leantime is a capable tool. 

I'm happy to help contribute to getting good routing set up, I'm curious first if the Leantime... "company" or whatever is already tracking this and looking at implementing. Don't want to duplicate effort.

**Comment by gloriafolaron** [comment]
@komali2 thanks for offering to help on this! @marcelfolaron said it's a fairly complicated implementation. It's on the radar, though, and has come up a few times so will end up on the roadmap. We've got some more mapping to do around it as a function, though, as there's some future use cases we want to be mindful of. 

In the future, if you do find there are things you'd like to contribute -- we'd be happy to have you. If you haven't already, do join our discord channel. Help/info on contributing can be quicker there and we have a few others there that spend some time regularly in the code.

**Comment by gloriafolaron** [comment]
@marcelfolaron Was this updated? We spoke about it.

**Comment by marcelfolaron** [comment]
Almost all screens have their individual link now in 2.4-beta
