### ISSUE TITLE
[BUG] Navigation menu doesn't automatically close on mobile

### ISSUE THREAD

**Issue by davidleechen** [Leantime/leantime#1426]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
When navigating Leantime on a mobile phone via the main hamburger menu, the nav menu does not close itself when a new page loads. _Additionally_ you can't close the nav menu on mobile when page = Goals, at all.

**To Reproduce**
1. Get on a phone and go to Leantime
2. Tap the hamburger menu to slide out the nav items
3. Tap on a page you aren't currently on
4. The browser navigates to that page
5. The menu is still open and requires manual closing to see the page.

**Expected behavior**
I expect after navigating via the main menu to end up on the page I'm looking for, not the page below the menu. This is a very common UX paradigm everywhere on the internet.

**Leantime Version**
2.3.5

**Server**
Apache in container on Kubernetes

**PHP / MySQL Version**
Whatever is inside the container

**Additional context**

**Comment by marcelfolaron** [comment]
Agree, there are a couple further improvements slated for the mobile version. Hope to get this in with the next release.
