### ISSUE TITLE
[BUG] Missing tooltips on upper right hand icons

### ISSUE THREAD

**Issue by davidleechen** [Leantime/leantime#1427]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
When mousing over the icons in the upper right hand corner, there are no tooltips or indications of what something is. The home icon is probably OK. fa-briefcase, fa-clock-o, fa-calendar, and the "apps dropdown" however...who knows. You can't tell unless you click on it. 

**To Reproduce**
1. Login to Leantime on a desktop
2. Mouseover the upper right hand icons
3. See nothing

**Expected behavior**
The anchor tags for those items need titles, tooltips should be displayed on mouseover in the desktop viewports.

**Leantime Version**
2.3.5

**Server**
Apache

**PHP / MySQL Version**
Whatever is in the 2.3.5 container

**Additional context**

**Comment by marcelfolaron** [comment]
Agreed. I'll add a tooltip library that can be used across the system
