### ISSUE TITLE
[BUG] Changing a project takes you back to the dashboard

### ISSUE THREAD

**Issue by davidleechen** [Leantime/leantime#1428]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Changing from one project to another from the main nav menu always brings you back to the dashboard

**To Reproduce**
1. Have at least 2 projects
2. Go to project 1
3. Browse to the Ideas board
4. Open the nav menu
5. Change to project 2
6. You're on the dashboard and not project 2's Ideas board

**Expected behavior**
I would expect changing projects to change the project but leave you on the page you were on, like project 1 ideas => project 2 ideas.

**Leantime Version**
2.3.5

**Comment by marcelfolaron** [comment]
Thanks for the submission. I can confirm that this is a bug. Will work on a fix
