### ISSUE TITLE
[BUG] Wiki article Copy Url does not work

### ISSUE THREAD

**Issue by davidleechen** [Leantime/leantime#1429]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Clicking the `Copy Url` button (should it be `URL` since it is an acronym?) does not work.

**To Reproduce**
1. Go to Docs
2. Click the `Copy Url` button
3. The page navigates
4. Nothing happens

**Expected behavior**
I expect there to be no page navigation, and the URL for _the specific wiki article on the specific wiki on the specific project_ to be in the clipboard / paste-buffer.

**Leantime Version**
2.3.5

** Other **
Chrome 109.0.5414.121 (Official Build) (64-bit) (cohort: M109_Control) 
Windows 10 21H2 19044.2486

**Comment by marcelfolaron** [comment]
Thanks for submitting. This was fixed in 2.3.6 (or .7) we are currently on 2.3.11 can you update and see if that fixes the issue?

**Comment by davidleechen** [comment]
If you fixed it eventually I'm good, I'm following a slower update cadence since I am deployed via helm chart.
