### ISSUE TITLE
[FEATURE] 2FA Setup: OTP/QR value as text

### ISSUE THREAD

**Issue by systemedz** [Leantime/leantime#1432]
When setting up 2FA in Leantime, currently you are shown the QR code. Sometimes, you need to be able to set it up, without using a camera, e.g. Password Manager on the computer. In that situation, usually you can show the value of the QR code on the screen, and then simply copy/paste it into the Password Manager. But I am not able to do that in Leantime.

Currently my workaround is to open the Developer Console, and look in the HTML where there is a hidden field containing that value (secret).

It would be great if you could simply show the value underneath the QR code. Maybe a "Show value as clear text"-link that would show it, so it is not immediately visible on the screen per default.

![2FA setup](https://user-images.githubusercontent.com/37810041/218967817-2756572c-1bb0-4065-830e-13f2174fc897.png)

**Comment by marcelfolaron** [comment]
Thank you for pointing that out. You are right the code should be displayed.
