### ISSUE TITLE
[FEATURE] To-Do templates

### ISSUE THREAD

**Issue by addvanced** [Leantime/leantime#1433]
As discussed on Discord, it would be nice if it was possible to create a "template" for each of the To-Do "types".
So, if someone creates a bug, the description textarea should be preset with a "Bugfix" template, to ensure that the one creating the To-Do adds the necessary information.

Basically similar to how it works here on GitHub if you create a new Issue.

It would be nice with some "out-of-the-box" templates, already made, but of course it should be possible to change these templates.

Templates should be on a client-level at least, but could also be on a project-level.

**Comment by acul009** [comment]
If Done right, this could also male implementing repeating tasks easier.

#1322 

Even without any additional repeating feature, this would make creating tasks externally easier.

**Comment by gloriafolaron** [comment]
We still have some things in the backlog that we're working out but commenting to say this hasn't been forgotten. 

Thanks for putting it here!

**Comment by marcelfolaron** [comment]
Added templates to the editor including 3 todo templates
