### ISSUE TITLE
Feedback for Project Roadmap 2020

### ISSUE THREAD

**Issue by aschrijver** [Leantime/leantime#145]
(Continued in separate issue, from #139)

I am using LeanTime mainly as a self-hosted, personal lean project environment (some other users only occasionally). I want this server-based, so I can access from multiple devices (mobile: Android, iPad, laptop: Ubuntu), always with Firefox. I am very privacy-focused and FOSS-oriented. I highly value Humane Tech (I am admin of [HTC](https://community.humanetech.com)) and I judge companies in that light (privacy policies, trackers, dark patterns, etc.).

In all my tools I have a strong preference to use (github-flavored) Markdown. Additional support for (UML) diagrams is a big plus (think [Mermaid](https://mermaid-js.github.io/mermaid/#/) or [PlantUML](https://plantuml.com/)).

In LeanTime I'd like to define Epics and User Stories (will use ToDo's for them). There can be relationships between them (will use hyperlinks). Like in github I will have top-level issues with a checklist of sub-issues.

Missing for me is a place where I can have Gitbook-like long-form documentation (in Markdown). I need to have different Categories and a ToC per category with at least 2 levels of nesting (main / sub).

Integrations-wise I'm a big fan of alternative software (alternative to monopolists, centralization), like e.g. Matrix/Riot vs. Slack.

**Edit**: I am no fan of the current HTML editor, with wysiwyg as-you-type, and e.g. all newlines auto-create a paragraph spacing in the text.

**Comment by aschrijver** [comment]
For the Login it would be nice to be able to type a username instead of the email (shorter to type), and have a Remember Me option, so I don't have to log in so often.

**Comment by aschrijver** [comment]
When you first installed LeanTime there is already an example project with some ToDo's. It is not necessary, and imho not desirable, to have 2 ToDo's be present (do research, create milestones) in a new project by default. This is only extra work to delete them.

**Comment by aschrijver** [comment]
In the navigation there could be fewer clicks. E.g. when I delete a ToDo and after confirming, I stay on the Delete page where it says 'Ticket deleted'. There is no 'back' button (so I have to use browser's 'back' button), but also the previous page could be auto-loaded with a (green) status message saying 'Ticket deleted'.

**Comment by marcelfolaron** [comment]
Thank you for your detailed feedback! These are great ideas and we'll try to add them to our roadmap!

**Comment by aschrijver** [comment]
Nice. Would be great if you published your roadmap somewhere (e.g. gh wiki + readme link?) to encourage continued feedback for it.

**Comment by rafaelkrause** [comment]
Hi,

First of all, thanks in advance to great work around LeanTime. Its simple to use and direct. We started to use as our project manager tool.

As @aschrijver  say, will be nice if the mensagens, confirmation and errors are top banners or PopUp Dialogs. 
Same for ToDo. Can be just a PopUp Dialog. So you can always stay on same page. 
It will improve a lot the time for managing ToDos.
