### ISSUE TITLE
Preview rendered HTML in description vs Editable [FEATURE]

### ISSUE THREAD

**Issue by nickian** [Leantime/leantime#1456]
The description for a todo item just shows a TinyMCE text area that is editable. Couldn't this show what has been saved vs always pulling up edit mode? Or can you include an icon on the toolbar for "previewing" the HTML so that shows rendered instead of a WYSIWYG text area? The main reason for this is links. If you insert any links into the description, you can't easily click on them because you're always in editor mode.

**Comment by gloriafolaron** [comment]
Ah, this is a good call out. Will add it to the list. Thanks for posting it.
