### ISSUE TITLE
[BUG] WYSIWYG Editor - Placeholder text issue

### ISSUE THREAD

**Issue by addvanced** [Leantime/leantime#1459]
**Describe the bug**
When creating a new To-Do etc. where using the WYSIWYG editor, the placeholder text is not removed on focus.
If you don't manually delete it, the text you write won't be saved.

**To Reproduce**
1. Go to To-Dos
2. Click on 'New' -> 'Add To-Do"
3. Click on the textarea and start typing without removing the placeholder text ("Enter text or type '/' for commands or '@' to mention someone")
4. Click 'Save & Close' to close the To-Do Modal
5. Re-open the newly created To-Do

**Expected behavior**
When clicking on the text area, the placeholder text should automatically be removed and the textarea should be ready for you to write the text.

**Leantime Version**
2.3.13

**Server**
NGINX

**PHP / MySQL Version**
PHP 8.1

**Additional context**
Tested on: Apple MacBook Pro M1, macOS Ventura , Browsers: Safari Version 16.1 (18614.2.3.1.1) and Google Chrome Version 110.0.5481.100

Screenshot of console error.
<img width="562" alt="leantime_error" src="https://user-images.githubusercontent.com/37810041/220747854-9a401563-e310-45cb-b6ec-84968a8a28fe.png">

**Comment by gloriafolaron** [comment]
I believe this was still doing it to me on the Idea board as well.

Thanks for posting here to give us a place to track.
