### ISSUE TITLE
[BUG] Logo missing after docker update (Unraid)

### ISSUE THREAD

**Issue by BenPicard** [Leantime/leantime#1460]
**Describe the bug**
Even if it's the right file in the database (the custom logo), if I update the docker, the custom logo doesn't display anymore. The custom logo is still displayed in the setting but, in the top corner and login page, it's the default one.

I tried to set it with an env variable but it doesn't work.

**Expected behavior**
The logo would still be there after an update.

**Leantime Version**
2.3.13

**Server**
Docker on Unraid

**PHP / MySQL Version**
PHP version: 8.1.15
Apache/2.4.54

Before update
![Screenshot 2023-02-22 at 4 20 34 PM](https://user-images.githubusercontent.com/6268293/220765731-15d96e53-4f75-4e4e-a145-1b9830775876.png)

After update
![Screenshot 2023-02-22 at 4 41 20 PM](https://user-images.githubusercontent.com/6268293/220765621-373a8c6f-3d27-4884-86eb-4166447f0d57.png)
)

Settings with the custom logo still there but not displayed
![Screenshot 2023-02-22 at 4 37 52 PM](https://user-images.githubusercontent.com/6268293/220765839-ad17e19b-d849-4c60-afca-ef4f18ea26c9.png)

The custom logo is also set in the DB but, it just don't work in the UI.
![Screenshot 2023-02-23 at 9 00 45 AM](https://user-images.githubusercontent.com/6268293/220929368-c8497993-c5ca-4bbd-8ae1-3b49e16d3935.png)

**Comment by BenPicard** [comment]
Any update @marcelfolaron ? Do you need me to do some tests or something else?

**Comment by marcelfolaron** [comment]
Not yet. I am still testing this  issue. It is unclear to me why exactly
this is happening. It should disappear once cache has been cleared. I'll
continue testing.
