### ISSUE TITLE
Delete/Deactivate Account

### ISSUE THREAD

**Issue by ArslanAmeer** [Leantime/leantime#1461]
I want to delete my LeanTime account, i have tried Settings and go through all other available option but failed to find any delete / deactivate account option.

**Comment by gloriafolaron** [comment]
I am going to assume you're looking for this for the hosted platform. 

Can you send an email and let us know which account it is and we can help with that.

Email: support@leantime.io 

@marcelfolaron tagging for visibility.

**Comment by ArslanAmeer** [comment]
hi @gloriafolaron 

Yes, my workspace is 'https://arslan.leantime.io/'
i wanted to delete my workspace and my account completely, as i am using my company's self-hosted leantime.
