### ISSUE TITLE
Who is Using Leantime? 

### ISSUE THREAD

**Issue by marcelfolaron** [Leantime/leantime#1466]
⚠️ We are adding a section on our website highlighting companies that are using Leantime. ⚠️

**Comment by TareqK** [comment]
We use leantime at equiptal(https://equiptal.io) for all our product development, discovery, and bizdev work.

**Comment by Elaktrato** [comment]
We at a small German advertising agency called Netzwerk für wirksame Werbung use it as well.
You can find our website over here (Warning German only): [https://michael-wirkner.de](url)

**Comment by Mattomatica** [comment]
The PMO I work for is testing it as a potential project management solution.

**Comment by salmonix** [comment]
A small EU business - in size - focusing on Agile (Manifesto) / Team / Project based approach.

**Comment by marcelfolaron** [comment]
Thanks. Would you mind sharing your website/logo to be added to our website?

**Comment by salmonix** [comment]
Well, not yet have website and likely won't be.
But I share the logo asap.
L.

**Comment by acul009** [comment]
Rahn IT-Systemtechnik
https://it-rahn.de

We're a small MSP in Germany. We manage our clients IT infrastructure, provide hosted services as well as custom programmed solutions.

![Logo-Full](https://user-images.githubusercontent.com/54124197/224434404-ce74fbf0-b4a4-4e80-ab11-b826cd4f2fcc.png)

**Comment by compumatter** [comment]
CompuMatter / ServerMatter 
![servermatter-logo-medium](https://user-images.githubusercontent.com/121611/228959283-d8bdf4d9-b161-4912-9e3b-a74461b68f04.png)

**Comment by AvishayRapp** [comment]
![image](https://user-images.githubusercontent.com/41360776/230147913-6648a539-0969-4d2c-aa67-921810ac0339.png)

Hello from Rapp IT Solutions!
Using Leantime with great pleasure!

**Comment by aboyington** [comment]
We at Udora Safety a Canadian supplier of security systems and safety products. We offer CCTV, alarm and netowrking installation and support services to small and medium sized businesses. We just started to use it and over the last month are extremly happy with its flexibility. Being able to rename or add ToDo columns have been the best part. We are in the proccess of switching over from Asana.

Thank you and keep up this great work

You can find our website over here [https://udorasafety.com/]

**Comment by qaniere** [comment]
ASUQTR
A student association who is building an autonoumous submarine :)
![image](https://user-images.githubusercontent.com/63805908/235805684-b15fd8a7-0171-4c3b-b87f-d0f085b6f8c8.png)

**Comment by gloriafolaron** [comment]
Hi all! 

We are beginning to partner with a UX group to help design some new features. If you would be interested in interviewing (we will be offering amazon gift cards for your time if interviewed), please let me know and I'll get your contact added to the list.

**Comment by compumatter** [comment]
Sure.  Be happy to be interviewed and glad to hear your.continuing to try and improve your product.Sincerely,JayJay LeporeCompuMatterOffice: 360 299 2428Cell: 360 202 ***@***.*** you are satisfied with your service, please consider providing us a social media review at https://compumatter.com/reviews...If you are not, please let me know so I can make it betterOn May 19, 2023, at 5:19 AM, Gloria ***@***.***> wrote:﻿
Hi all!
We are beginning to partner with a UX group to help design some new features. If you would be interested in interviewing (we will be offering amazon gift cards for your time if interviewed), please let me know and I'll get your contact added to the list.

**Comment by komali2** [comment]
508.dev LLC is a software engineering co-op incorporated in the USA with engineers in the USA, Australia, and Taiwan. 

We use Leantime as our core product and project management tool. It provides a general overview of our clients and client work, and then under each client we track projects individually, ticketing out sprints and subtasks and tracking who's working on what.

We also use the wiki feature (what you call Docs) as our knowledge base, with info such as how we log our invoices and etc.

**Comment by marcelfolaron** [comment]
> The PMO I work for is testing it as a potential project management solution.

Did they have any feedback? :)

**Comment by Devusol** [comment]
We use Leantime at DEVuSOL 
[devusol.com](url)

![devusolxtrasmall](https://github.com/Leantime/leantime/assets/40222187/c8379eb1-a662-4169-ae2f-874cd71f3c11)
