### ISSUE TITLE
Global Milestone viewer [FEATURE]

### ISSUE THREAD

**Issue by Philb27** [Leantime/leantime#1470]
We have to currently jump around projects to review the milestones and reschedule (i.e. when a user is working on more than one project) it would be good to be able to consolidate all Milestone charts/pages (maybe even select those to show) into one for a quick snapshot/review.

**Comment by gloriafolaron** [comment]
100% agree. We've been evaluating what a more program/portfolio approach looks like in the system and this is one thing we want to consider for it.

@marcelfolaron FYI
