### ISSUE TITLE
[BUG] Acrhived toDos vanished

### ISSUE THREAD

**Issue by hnegadi** [Leantime/leantime#1474]
We added an archived category for our todos in our last project but they vanished after 2.3.13 install. 
It seems that they are still in the datatabase since we can see them in the time sheets menues but there's now way to access them otherwise.

Thank you,

-H.

**Comment by marcelfolaron** [comment]
Can you access them on the table view by selecting the "archive" status in the filter?

**Comment by hnegadi** [comment]
Yes I confirm we can access them this way in table view.

**Comment by hnegadi** [comment]
just installed 2.3.14, we can reproduce the exact same issue step by
step....Might have we missed something ?
TY.

-H.
