### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jmourinho** [Leantime/leantime#1477]
Hi - Having a 500 error after upgrade. 

The log is:

`#0 /home/nginx/domains/leantime.XXXXXX.com/vendor/graham-campbell/result-type/src/Error.php(118): Dotenv\Parser\Parser::Dotenv\Parser\{closure}()
#1 /home/nginx/domains/leantime.XXXXXX.com/vendor/vlucas/phpdotenv/src/Parser/Parser.php(31): GrahamCampbell\ResultType\Error->mapError()
#2 /home/nginx/domains/leantime.XXXXXX.com/vendor/vlucas/phpdotenv/src/Dotenv.php(222): Dotenv\Parser\Parser->parse()
#3 /home/nginx/domains/leantime.XXXXXX.com/vendor/vlucas/phpdotenv/src/Dotenv.php(237): Dotenv\Dotenv->load()
#4 /home/nginx/domains/leantime.XXXXXX.com/app/core/class.environment.php(24): Dotenv\Dotenv->safeLoad()
#5 /home/nginx/domains/leantime.XXXXXX.com/app/core/class.environment.php(13): leantime\core\environment->__construct()
`

Can you help, please?

**Comment by acul009** [comment]
Can you check your log again please?
It looks like you only posted the stacktrace, but the error message is missing.

**Comment by gloriafolaron** [comment]
Following up on this -- it can be quicker to get support on things like this in our Discord chat so if it isn't quick enough here, feel free to try there too.

Link here: https://discord.com/invite/4zMzJtAq9z

**Comment by jmourinho** [comment]
Sorry for the delay, i was out of the office with no access to the server.

 Error was: `FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Dotenv\Exception\InvalidFileException: Failed to parse dotenv file. Encountered a missing closing quote at ['{]. in /home/nginx/domains/leantime.xxxxxxxxx.com/vendor/vlucas/phpdotenv/src/Parser/Parser.php:30`

Long story short: i couldn't get the env file working properly (the brackets count was ok) so i switched to the old configuration.php

After that, i got another error: `"PHP message: Intervention\Image\Exception\MissingDependencyException: PHP Fileinfo extension must be installed/enabled to use Intervention Image. `

- I was not aware, but it seems you are now using phpfileinfo extension in this recent version. It was not loaded in my php config (it seems to be disabled by default in centminmod releases as it consumes lots of resources). I recompiled my php and it solved the issue.

**Comment by marcelfolaron** [comment]
Thanks for the update. Yes we are using the fileinfo extension. For the most part we rely on php extension that you would find installed on the majority of shared hosts. A good list can be found here: https://www.namecheap.com/support/knowledgebase/article.aspx/9697/2219/php-modules-limits-and-extensions-on-shared-hosting-servers/
