### ISSUE TITLE
[FEATURE] License Upgrade to GPLv3

### ISSUE THREAD

**Issue by acul009** [Leantime/leantime#1478]
**Is your feature request related to a problem? Please describe.**
I've started work on OpenID Connect support for leantime. I would like to use this library:
https://github.com/jumbojett/OpenID-Connect-PHP
unfortunately it is licensed under the Apache License, which is incompatible with your GPLv2 License.

**Describe the solution you'd like**
If possible, an update to the GPLv3 for this project would resolve this.
As far as I can remember, we would need the consent of all significant contributors, which seems like

**Comment by acul009** [comment]
Small Update: I managed to get most of it running without any libraries.

This is probably still a good idea, so I'll leave this issue open.

**Comment by marcelfolaron** [comment]
Hey,

Thank you. Interesting you mention the license concern. I too believe that
going to gpl3 is in the best interest of the project. We have already
gathered CLAs from a majority of core contributors and I would assume a
move to gpl3 would cause too many concerns.

**Comment by marcelfolaron** [comment]
Correction (stupid auto correct): would assume a move to gpl3 would NOT
cause too many concerns.
