### ISSUE TITLE
[BUG] Marking a project as "Closed" causes 403 Error on subsequent project openings

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1481]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
When I delete a project it causes subsequent project loads to throw a 403.   

**To Reproduce**
1. Open any projects existing Todo list
2. Click the Project Settings icon in the lower left corner
3. Change Active to Closed and Save
4. Click the project menu
5. Select another project from the menu and the 403 becomes visible.  Todo list does not open.
6. All other projects when select from the menu will continue to throw 403 errors.
7. However if I click on the Todo list from the left side, things will begin operating normally again.

**Expected behavior**
The Todo grid of the new project should open, 

**Leantime Version**
2.3.13

**Server**
NGINX 

**PHP / MySQL Version**
8.1 / 10.4 Mariadb

**Additional context**
After getting a 403, if I then click on that projects Todo link things once again behave normally.

I have created a video to make the problem more obvious
* https://www.youtube.com/watch?v=0iEkWZqaCK0

**Comment by gloriafolaron** [comment]
This is also happening with edits such as changing the client. Shared with @marcelfolaron

**Comment by compumatter** [comment]
Thank you!
