### ISSUE TITLE
[BUG] Goals for one project continue to appear when switching between projects

### ISSUE THREAD

**Issue by samcgarry** [Leantime/leantime#1484]
In one project the goals that have been defined continue to appear if you change to a different project from the dropdown list even if that other project has no other goals defined.

1. Go to 'Goals' in the navigation bar.
2. Define a goal for the current project if one does not exist.
3. Create a new project.
4. Switch to the new project
5. Go to 'Goals in the navigation bar.
6. The defined goal from the original project is displayed.

I would expect the goal list to refresh and be filtered to the current project, so that no goals appear.

I am using Leantime 2.3.13 in docker.

If you sign out from the account after switching and sign in so that the project that opens is the second project, the goals list appears empty. If you then go back to the original project and switch back, the goals persist and are shown in the goals view again. Refreshing from the browser doesn't make any difference either.

**Comment by gloriafolaron** [comment]
Thanks for reporting this! This seems to be happening in other text places as well. I had it happen with the project description carrying over to all my tasks. Been discussing it with @marcelfolaron.
