### ISSUE TITLE
[BUG] Can not invite user on self hosted docker instance with nginx reverse proxy

### ISSUE THREAD

**Issue by D4ykoo** [Leantime/leantime#1487]
**Describe the bug**
Leantime does not send invitation emails when creating users. Instead an error occured, even though smtp settings are configured correctly (tested with another application, all credentials work). After having a look at the log, the error is as follows:
`[error] 1778238#1778238: *1806 upstream timed out (110: Connection timed out) while reading response header from upstream, client: <client ip>, server: leantime.myurl.com, request: "POST /users/newUser HTTP/2.0", upstream: "http://127.0.0.1:8085/users/newUser", host: "leantime.myurl.com", referrer: "https://leantime.myurl.com/users/showAll"`

**To Reproduce**
1. Click on Company Management
2. Click on User Management
3. Click on Add User
4. Fill form and create user  

**Expected behavior**
An invitation email send to the user.

**Leantime Version**
Version 2.3.13

**Server**
Leantime in docker: default configuration, i guess it is apache

**PHP / MySQL Version**
MySQL: 8.0
PHP: Version that is part of the official docker image 

**Additional context**
I run leantime in a docker container for arm64, using the docker-compose file provided by your team behind a nginx reverse proxy.
Things i changed/ added in the compose file:
* `LEAN_APP_URL: https://leantime.myurl.com`
* the serving port of my container

** NGINX configuration **
```
server {
        server_name     leantime.myurl.com;

        # logging
        access_log /var/log/nginx/leantime.access.log;
        error_log /var/log/nginx/leantime.error.log warn;

        location / {
                proxy_pass http://127.0.0.1:8085;
                proxy_set_header Upgrade           $http_upgrade;
                proxy_set_header Connection        "upgrade";
                proxy_set_header Host                $host;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host  $host;
                proxy_set_header X-Forwarded-Port  $server_port;
                }

    listen 443 ssl; # managed by Certbot
    listen [::]:433 ssl http2;
    ssl_certificate /etc/letsencrypt/live/leantime.myurl.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/leantime.myurl.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = leantime.myurl.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name     leantime.myurl.com;
    listen 80;
    return 404; # managed by Certbot


}
```

I appreciate every help!

Edit:
I got a bunch of more errors after trying to use it with the admin account, like after deleting a todo i got the error that i am not authorized to access the page.
![Screenshot 2023-03-08 140442](https://user-images.githubusercontent.com/50523358/223722150-2b851016-69ae-4690-9b84-f6797ab20deb.png)

**Comment by marcelfolaron** [comment]
From the logs up there it seems like it is timing out when trying to connect to the smtp server. Are there any additional firewall settings that might cause that?

**Comment by D4ykoo** [comment]
No, I checked iptables.
