### ISSUE TITLE
[BUG] "<i class='fa fa-download'></i> Download"

### ISSUE THREAD

**Issue by gregoryfenton** [Leantime/leantime#1488]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
The text should be italic, however it is outside the <i></i> wrapper.

**To Reproduce**
Search the files for "></i> "

**Expected behavior**
The text after </i> should be in italics, however the </i> is in the wrong location.

**Leantime Version**
v2.1.8 Turnkey Linux

**Server**
Apache2

**PHP / MySQL Version**
PHP 7.4.3.3
MySQL 10.5.15-MariaDB-0+deb11u1 Debian 11

**Additional context**
grep "></i> " * -R

**Comment by gregoryfenton** [comment]
Typical example:
src/domain/retrospectives/templates/retroDialog.tpl.php:
<i class="fas fa-times"></i> <?php echo $this->__("links.cancel") ?>

The correctly formatted line should be:
<i class="fas fa-times"> <?php echo $this->__("links.cancel") ?><i>

**Comment by marcelfolaron** [comment]
Hi Gregory,

The turnkey linux distribution is not maintained by us and it appears that
it is quite a few versions behind. We are on 2.3.13

**Comment by marcelfolaron** [comment]
That label is not supposed to be cursive. This is the standard and suggested way to include fontawesome icons. The text should specifically not be wrapped into the i element since it calls the fontawesome class. https://fontawesome.com/icons/user?s=solid&f=classic
