### ISSUE TITLE
Redis support?

### ISSUE THREAD

**Issue by ghost** [Leantime/leantime#149]
Is there by chance already that redis is supported to handle object caching instead of querying the database everytime if i have a large team.

**Comment by marcelfolaron** [comment]
Thanks for reaching out. As of right now we don't have a redis caching layer in the application, but it is something we are looking into.  How big is your team? Our queries are optimized and should run pretty quickly even with large databases.

**Comment by fire** [comment]
Please do not have redis as required, it adds another step for those who don't need acceleration.

**Comment by marcelfolaron** [comment]
We wouldn't make that required. Instead offer an option for session cache, file cache or redis cache. I am not sure if the need is there yet as I believe most of our queries run pretty fast (and if not we should optimize those first)
