### ISSUE TITLE
[BUG] Gantt Chart - Moving up and down is not saved

### ISSUE THREAD

**Issue by alpCaner** [Leantime/leantime#1492]
I move the milestones and tasks up and down, however the positions are not saved. When go and come back to the milestones page back, the positions remain the same. 

![image](https://user-images.githubusercontent.com/109098482/224541780-0a8da924-c940-4dd3-8f2e-030e6ad071b6.png)

**Comment by ryland-mueller** [comment]
@marcelfolaron seems like this issue is happening on my fresh v2.3.27 install. Very frustrating and makes the gantt view virtually unusable. Any help is very much appreciated
