### ISSUE TITLE
[FEATURE] More filtering options in Milestones 

### ISSUE THREAD

**Issue by alpCaner** [Leantime/leantime#1494]
Right now show tasks option shows all the tasks. I would love to see only One Milestone with its tasks for simplicity for example. I have more than 40 tasks. Now it is quite difficult to manage them. 

![image](https://user-images.githubusercontent.com/109098482/224543565-8f971247-0ff6-46a7-a62c-d8f1a05c6602.png)

**Comment by gloriafolaron** [comment]
This makes a lot of sense. Thanks for calling it out.

**Comment by marcelfolaron** [comment]
More filtering options were added in 2.4-beta
