### ISSUE TITLE
[BUG] Setting a time of the subtask breaks the connection and it becomes a task

### ISSUE THREAD

**Issue by alpCaner** [Leantime/leantime#1495]
![image](https://user-images.githubusercontent.com/109098482/224544398-b19094c8-297f-4134-b405-8ce8004323af.png)

I was assigning the time, however the relationship is broken. It is no longer a subtask after the change.

![image](https://user-images.githubusercontent.com/109098482/224544383-d7b117a2-d724-4676-8692-4dda8cb556b7.png)

**Comment by krillin666** [comment]
I can also reproduce this bug
