### ISSUE TITLE
[FEATURE] Add Matrx webhook integration

### ISSUE THREAD

**Issue by nanu-c** [Leantime/leantime#1500]
**Is your feature request related to a problem? Please describe.**
I would like to see a matrix integration to get notifications similar to the other notifications 

**Describe the solution you'd like**
There is a Matrix webhook bot -> https://matrix.org/docs/projects/bot/matrix-webhook and
https://github.com/nim65s/matrix-webhook

The request looks like this and the only missing field is the key. The bot doesn't accept to leave out the key.
```
curl -d '{"body":"new task from toto: [44](http://radio.localhost/map/#44)", "key": "secret"}' \
  'http://matrixwebhookbot.url/!DPrUlnwOhBEfYwsDLh:matrix.org'
```
**Additional context**
Nothing :)

**Comment by 0x416c69** [comment]
+1

**Comment by marcelfolaron** [comment]
As of 3.2.0 we are supporting Zapier integrations. The alpha app is available here https://zapier.com/developer/public-invite/207240/cac6ec7a911bd5fa7924f38230d58d2f/
