### ISSUE TITLE
[FEATURE] Integration with Nextcloud

### ISSUE THREAD

**Issue by Aephir** [Leantime/leantime#1507]
**Is your feature request related to a problem? Please describe.**
I store all files in [Nextcloud](https://nextcloud.com/). Quite a few of those, I'd like to link to "to-do"/"tasks" in Leantime. But the files can change (they are frequently edited on e.g. laptop, and automatically synced with Nextcloud), so it doesn't really work to just upload a copy to Leantime. Also, it seems a waste of storage space to do that.

**Describe the solution you'd like**
A Nextcloud integration so you can sync Leantime data (for easy backup) and link files.
1. Have the option to sync with Nextcloud for backup.
2. Have option to store larger files directly in Nextcloud, and link them directly (e.g. in the "Files" tab of to-do/task; atm I think the only way is to use external Nextcloud file link, which is of course not optimal).

**Additional context**
E.g. here could be a "choose Nextcloud file" option.
<img width="1242" alt="Screenshot 2023-03-17 at 11 18 34" src="https://user-images.githubusercontent.com/20152788/225877622-d2bbc576-8da9-40cf-8ea6-f4f70dc50c9c.png">

**Comment by gloriafolaron** [comment]
This makes a lot of sense. Tagging this for review and flagging as Help Wanted in case someone else is able to jump in on it before we can.

**Comment by marcelfolaron** [comment]
As of 3.2.0 we are supporting Zapier integrations. The alpha app is available here https://zapier.com/developer/public-invite/207240/cac6ec7a911bd5fa7924f38230d58d2f/
