### ISSUE TITLE
[FEATURE] - Rewrite how the "show tasks" in Milestones "Gantt view" behaves.

### ISSUE THREAD

**Issue by Aephir** [Leantime/leantime#1508]
**Is your feature request related to a problem? Please describe.**
It's probably not a priority, as this is not a major problem. But the way the "show tasks" toggle is implemented, there is a bit of a delay (it reloads the chart, I think? At least the URL changes).

**Describe the solution you'd like**
Having the tasks always loaded for an instant toggle (without having to load a new URL). I'm not an expert, but suspect this could be achieved fairly simply?

**Comment by marcelfolaron** [comment]
This was rewritten to be task first in 2.4
