### ISSUE TITLE
[BUG]  My Portfolio throws error and white screen

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1511]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Clicking on My Portfolio icon in the top right corner displays a white screen and log file errors.

**To Reproduce**
Click on the My Portfolio icon

**Expected behavior**
Display the My Portolio screen

**Leantime Version**
2.2.14

**Server**
NGINX

**PHP / MySQL Version**
8.1 / 10.2 MariaDb

**Additional context**
I have created a video to assist with understanding the problem:
* https://www.youtube.com/watch?v=HtBor1nu-qw

Thank you as always.

Jay

**Comment by marcelfolaron** [comment]
Do you see any errors in your logs/error.log file? I cannot reproduce this issue right now
