### ISSUE TITLE
[BUG] 403 after user role update

### ISSUE THREAD

**Issue by gloriafolaron** [Leantime/leantime#1513]
I updated a user and changed her role to Company Manager. When I clicked back to go to another project view, I got a 403 error.

V. 2.3.14.

<img width="1511" alt="Screen Shot 2023-03-23 at 10 32 17 AM" src="https://user-images.githubusercontent.com/55953099/227236431-7e29d8b8-4c83-4cb8-8f22-721acc9f2c65.png">

**Comment by marcelfolaron** [comment]
Can't repro issue
