### ISSUE TITLE
[FEATURE] Auto-complete when typing / setting tags for Todos

### ISSUE THREAD

**Issue by MarblesTheMadOne** [Leantime/leantime#1517]
When typing out a tag for a todo, check if there already is one or more tags corresponding with the users input. If yes, display them below the textbox in there little tag-bubble & let the user select them.

**Comment by marcelfolaron** [comment]
What version are you using. This is already in the system and seems to be working on my end.

**Comment by MarblesTheMadOne** [comment]
@marcelfolaron I stand corrected, thank you :3
