### ISSUE TITLE
[FEATURE] Hide archived milestones in table view

### ISSUE THREAD

**Issue by AndrewGail** [Leantime/leantime#1521]
Currently in `Project Settings ->  To-Do Status Settings` I can choose to show or hide certain milestones from the Kanban, currently just the Archived status is set this way.  My expected behaviour was for the statuses hidden on the Kanban to also be hidden in the table view.
 
Not sure what the wider expectations are, but I think a quick solution might be to hide milestones from the table view where the checkbox is unchecked in `To-Do Status Settings`.  A more complicated solution might be to change the checkbox to a dropdown with options for; Show, Hide Kanban, Hide Table, Hide All?

**Comment by marcelfolaron** [comment]
Archived tasks are now hidden by default.
