### ISSUE TITLE
[BUG] Pictures not appear in notifications

### ISSUE THREAD

**Issue by cliris** [Leantime/leantime#1526]
Hello,

Thanks for your work.
We have a little bug in notification when we upload a picture in a comment for a task :

![image](https://user-images.githubusercontent.com/119530245/228758918-56abbf19-f817-4015-b894-ffd74cbc9481.png)

To reproduce :

1. create task
2. add a comment
3. upload or paste a picture
4. post
5. ask to a colleague to check their notifications, the text is ok but you have the broken image icon ...

Leantime version : 2.3.14
OS : Debian 11
WS : Apache
PHP : 8.1.17

**Comment by marcelfolaron** [comment]
This should be fixed now in 2.4-beta
