### ISSUE TITLE
[BUG] WYSIWYG Formatting doesn't stick on Todo's or Discussions

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1530]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
When editing a Todo the formatting is quite right.   However when you save that text entry the formatting falls apart.  All line spaces are removed, bullets are no longer indented, colors of headings are lost and more.

A similar result happens in the Discussion text area entry.

**To Reproduce**
1. Open an existing Todo
2. Type a few lines of text and perhaps a heading
3. Save it.
4. The result will be different and less readable than the 'during edit' version

**Expected behavior**
WYSIWYG

**Leantime Version**
2.3.14

**Server**
NGINX

**PHP / MySQL Version**
8.1 / 10.2 mariadb

**Additional context**
I have created a video to make the problem more obvious
* https://www.youtube.com/watch?v=yXSCYWVIhaE

**Comment by marcelfolaron** [comment]
I will publish new docs but there is now an option to run a script as cronjob, either via commandline or calling the url 
domain.com/cron/run
