### ISSUE TITLE
Error message after logging in

### ISSUE THREAD

**Issue by alexsynth** [Leantime/leantime#154]
Hi Ive just recently downloaded the latest version of leantime and ive been getting an error message at the top right of the home page after logging in as shown in the image attached. 
![error](https://user-images.githubusercontent.com/61594348/76229407-93c56080-623b-11ea-8c25-1fe93f2a9f58.png)

**Comment by marcelfolaron** [comment]
Hi,

Thanks for reaching out. I am sorry for the issue. I see what is causing
the bug and will send out a fix today.
In the meantime, can you update your configuration.php to include your
domain name in the appURL variable:

public $appUrl = "https://YOURLEANTIMEURL";


That should fix the issue.

Sincerely,
Marcel

**Comment by alexsynth** [comment]
Thanks very much. Will do

**Comment by marcelfolaron** [comment]
Fixed in 2.0.14
