### ISSUE TITLE
[FEATURE] French translation update (need crowdin "already approved" review)

### ISSUE THREAD

**Issue by jmassiaux77** [Leantime/leantime#1557]
leantime 2.3.15

I have updated a lot of "already approved" french translation on crowdin (some several month ago).
I have the used "Notify proofreader" function that create a comment in crowdin but they don't have been treated.

Is it possible to make a review of all this translation updates ?

Regards,
Jérôme Massiaux ("jmassiaux" on crowdin)

**Comment by marcelfolaron** [comment]
Hey, thanks for the call out. I made you a proof reader as well for French. Hope that helps
