### ISSUE TITLE
Notice in a local install for Project Timesheets page

### ISSUE THREAD

**Issue by clementaf** [Leantime/leantime#156]
Hello,

On a fresh install Leantime 2.0.14 with this server configuration :

- Apache 2.4.33
- PHP 7.2.4
- MariaDB 10.2.14

I have this notices on the Project Timesheets page.

![2020-03-10 15_18_55-Window](https://user-images.githubusercontent.com/20518176/76322380-99768100-62e3-11ea-9945-875c23a2c53d.png)
![2020-03-10 15_25_46-Window](https://user-images.githubusercontent.com/20518176/76322381-9aa7ae00-62e3-11ea-86b5-943ac4083678.png)
![2020-03-10 15_25_55-Window](https://user-images.githubusercontent.com/20518176/76322382-9b404480-62e3-11ea-8a4c-1c8c2bec9819.png)

**Comment by marcelfolaron** [comment]
This (and your other bug) seems to me that the language file (en.ini) was not loaded properly.
Check if the file resources\language\en\en.ini exists and is accessible by the server. 
Did you try to change the language code in the config file? Unfortunately this is not supported at the moment. We are working on 2.1 which will include language support, beta release will happen this week.

**Comment by clementaf** [comment]
I have change language code in the config file with 'fr' value. So after take 'en' value, it's ok. Sorry for disturbance.
I wait for beta and i could help for trad if necessary.

**Comment by marcelfolaron** [comment]
Thanks! FR translations would be great! I will let you know.
