### ISSUE TITLE
[FEATURE] Default to Collapsed Navigation Menu

### ISSUE THREAD

**Issue by aboyington** [Leantime/leantime#1560]
Hi there, when using the side menu to navigate to a project. The client list opens as an expanded list. I have some clients with 10 or more open projects.

Is there a way to have the client list default to a Collapsed view which would give me the option to expand only the client that I am interested in?

At the very least it should save my collapsed status so that on next visit all clients are collapsed except the one I am working on.

![clients-list](https://user-images.githubusercontent.com/12466469/230821690-d39e1857-4f11-4106-b329-62de32bc7cdf.jpg)

**Comment by compumatter** [comment]
I'd like to second the idea of all menu items starting collapsed.

You can see in this menu with everything open it requires you to observe and internalize a long list of unnecessary todos on your way to the client of interest.  This will only become more of a distraction as more projects are added. 

![image](https://user-images.githubusercontent.com/121611/235027239-6a37de64-efe8-404f-a406-0877e9933f2f.png)

Conversely, this is more likely to make all clients visible at a glance and and makes the Create new Project visible which disappears in the first model.  

![image](https://user-images.githubusercontent.com/121611/235028149-cff30327-97d2-4fc9-9f20-b130f8f46976.png)

**Comment by marcelfolaron** [comment]
Fixed in 2.3.21
