### ISSUE TITLE
[FEATURE] Fullscreen view when editing and viewing ideas

### ISSUE THREAD

**Issue by rvbd** [Leantime/leantime#1562]
Hello, with the ideas module, is it possible to have a fullscreen view when when viewing and idea or editing them?
The problem that we have right now is that the description field is too small for longer ideas and on the board view, it became too long vertically and indentations are truncated. 

I think implementing fullscreen view and editing would solve this issue. Or simply just full screen editing.

I've added some screenshots to illustrate where it should be full screen.
![chrome_b4hESE1oj9](https://user-images.githubusercontent.com/1558550/231058410-d7b0ab05-5605-4cd1-a3c8-4a16cb658083.png)
![chrome_srYwgJpJNA](https://user-images.githubusercontent.com/1558550/231058418-df56c56f-96d6-4132-a6ec-cda0e1ec64c3.png)

Thanks heaps.

**Comment by marcelfolaron** [comment]
View has been increased quite a bit in 2.3.21
