### ISSUE TITLE
Unable to Login using my AD user log in

### ISSUE THREAD

**Issue by marl786** [Leantime/leantime#1569]
Hello, I have been able to get leantime up and running and I have followed the latest configuration file to LDAP with AD but still for some reason I can not log in using my AD based credentials but I can register and log in using leantime.

**Comment by nabeelmahmood22** [comment]
I am facing the same issue. Please help to resolve this

**Comment by nabeelmahmood22** [comment]
@marcelfolaron Can you please look into this?

**Comment by marl786** [comment]
@marcelfolaron Please help us out

**Comment by marl786** [comment]
This is my LDAP config (Have removed some sensitive info)
  public $useLdap = true;
  public $ldapType = 'AD'; //Select the correct directory type. Currently Supported: OL - OpenLdap, AD - Active Directo>  
  public $ldapHost = "1.1.1.1"; //FQDN
  public $ldapPort = 389; //Default Port
  public $baseDn = "DC=example,DC=ca"; //Base DN, example: DC=example,DC=com
  public $ldapDn = "CN=Service Accounts,DC=example,DC=ca"; //Location of users, example: CN=users,DC=example,DC=com
  public $ldapUserDomain = "@example.ca"; //Domain after ldap, example @example.com
  public $bindUser = "user"; //ldap user that can search directory. (Should be read only)
  public $bindPassword = "pass";

    //Default ldap keys in your directory.
    public $ldapKeys = '{
        "username":"sAMAccountName",
        "groups":"memberof",
        "email":"mail",
        "firstname":"giveName",
        "lastname":"sn"
        }';

**Comment by marcelfolaron** [comment]
First thing that I see is the group attribute: 
Unless you renamed it in AD it should probably be: memberOf (notice capital "O") 

Any messages in the logs file?

**Comment by adocampo** [comment]
I'm also having issues but with the docker image itself.
```      
#      LEAN_DEBUG: "true"
      LEAN_LDAP_USE_LDAP: "true"
      LEAN_LDAP_HOST: "192.168.10.10"
      LEAN_LDAP_BASE_DN: "dc=company,dc=lan"
      LEAN_LDAP_DN: "OU=Users,OU=IT Department,OU=organization,DC=company,DC=lan"
      LEAN_LDAP_USER_DOMAIN: "@company.com"  ## Tried also with "@company.lan", also failed
      LEAN_LDAP_KEYS: '{"username":"sAMAccountName","groups":"","email":"mail","firstname":"givenname","lastname":"sn"}'
```

logs says
```
[24-Apr-2023 12:55:09 Europe/Madrid] PHP Warning:  ldap_bind(): Unable to bind to server: Invalid credentials in /var/www/html/app/domain/ldap/services/class.ldap.php on line 115
```

Any idea what's happening?

**Comment by compumatter** [comment]
Just an FYI in case it helps anyone.  I am using LDAP with Samba 4 Linux (Active Directory Clone).  I am NOT using OpenLDAP as Samba 4 uses its own AD clone config by default.

These are my settings and they work:

`    /* ldap default settings (can be changed in company settings) */
    public $useLdap = true;
    public $ldapType = 'AD'; // Note: my LDAP works whether this is AD or OL
    public $ldapHost = 'localhost';
    public $ldapPort = 389; //Default Port
    public $ldapDn = 'cn=users,dc=office,dc=mydomain,dc=com';

   //Default ldap keys in your directory.
    public $ldapKeys = '{
    "username":"cn",
    "groups":"memberof",
    "email":"mail",
    "firstname":"givenname",
    "lastname":"sn",
    "phonenumber":"telephonenumber"
    }';
`
I realize each LDAP can have their own unique twists but I have been using LDAP with Leantime for about 5 months now and through many older versions.  I am currently using their latest 2.3.18 and it is still functioning normally.  Our staff depends on LDAP.
