### ISSUE TITLE
[BUG] PHP 8.2: Dynamic Properties are deprecated 

### ISSUE THREAD

**Issue by tedmarcin** [Leantime/leantime#1573]
Hi, on exemple , on Debian /apache  installation with PHP 8.2 ,  u can see on home screen in debug mod this lines
`Deprecated: Creation of dynamic property leantime\domain\models\tickets::$editTo is deprecated in /var/www/html/leantime/app/domain/tickets/repositories/class.tickets.php on line 921`
`Deprecated: Creation of dynamic property LasseRafn\InitialAvatarGenerator\InitialAvatar::$translato is deprecated in /var/www/html/leantime/vendor/lasserafn/php-initial-avatar-generator/src/InitialAvatar.php on line 571`
![2023-04-15 13_21_52-Window](https://user-images.githubusercontent.com/11801361/232211531-67c22944-8c35-4da2-9bfb-8e426ddad9bf.png)

i checked quickly in web, and found this info [https://php.watch/versions/8.2/dynamic-properties-deprecated](url)

Maybe helps anyone this link ..

By the way, same installation on php8.1 is without errors

**Comment by marcelfolaron** [comment]
This should be fixed now across the board
