### ISSUE TITLE
<localdomain>/install -- requested URL not found

### ISSUE THREAD

**Issue by TrommelFisch** [Leantime/leantime#158]
I'm trying to set up Leantime on a Raspberry Pi 3 Model B+. I get "The requested URL was not found on this server" when trying to navigate to "localhost/install" with chromium on the Raspberry.

I have the Desktop Version of Raspian (Buster, installed via Noobs) with MariaDB, Apache2 and PHP 7.3 (installed following the instructions on [1]). I activated mod_rewrite (as instructed on [2]) and set up an empty database (following the instructions on [3]). 
I downloaded "Leantime-V2.0.12.zip", unpacked it and copied all files contained in the "Leantime-V2.0.12" folder on the Rapsberry Pi, in "/var/www/html/leantime". Next I changed the apache document root folder (following the instructions on [4]) from "/var/www/html" to "/var/www/html/leantime/public". Then renamed "config/configuration.sample.php" to "config/configuration.php" and filled in the database credentials (username, password, host, dbname). 

Why do I get the abovementioned error message? 
(The instructions given in issue "install (production) page not found #77" didnt help solving the problem.)

[1] https://www.mva.ch/support/tech-blog/techblog-raspberry/auf-raspibian-jessie-apache-php-7-und-mariadb-wordpress-installieren/
[2] https://wiki.ubuntuusers.de/Apache/mod_rewrite/
[3] http://recipes.item.ntnu.no/setting-up-an-sql-database-on-the-raspberry-pi/
[4] https://askubuntu.com/questions/337874/change-apache-document-root-folder-to-secondary-hard-drive

**Comment by marcelfolaron** [comment]
Thanks for reaching out. What do you see when you go to `localhost` ? 
There are a couple options: Try opening `localhost/index.php?install=true`. If that shows the installation page we know the mod_rewrite module is not set up correctly (Don't try to install it, Leantime won't work correctly). 
If that doesn't open anything then
A. The document root is not set up correctly
B. Server is not running? 

Do you see any errors in your apache logs?

**Comment by TrommelFisch** [comment]
> Try opening localhost/index.php?install=true. If that shows the installation page we know the mod_rewrite module is not set up correctly (Don't try to install it, Leantime won't work correctly).
That seems to be the case. 

How do I correctly set up the mod_rewrite module? 
As far as I understood, I need to active it with "sudo a2enmod rewrite" and "sudo a2enmod actions" (done), do some changes in /etc/apache2/sites-enabled/000-default.conf and /etc/apache2/apache2.conf and set up a .htaccess file. What exactly do I need to change / add to these files to make it work?

thanks for th help :)

**Comment by marcelfolaron** [comment]
Assuming you ran the commands to activate the module 
```
sudo a2enmod rewrite 
```

The <Directory> tag in 000-default.conf should contain the line:
```
AllowOverride All
```

If it is not included or says none, you may need to change that. After you change the config files you will need to restart apache

```
sudo service apache2 restart
```

You don't have to create the .htaccess files as they are included in the leantime package.

**Comment by TrommelFisch** [comment]
I found the error in 000-default.conf - the installation page is loading!

**Comment by marcelfolaron** [comment]
I am glad it is working now. Let me know if you need anything else. FYI I highly suggest updating to 2.0.14 which includes quite a few bugfixes

**Comment by antonio-emilio** [comment]
> I found the error in 000-default.conf - the installation page is loading!

I'm facing the same problem, when typing index.php?install=true I can see the page, but that's all..
What was the error?

**Comment by TrommelFisch** [comment]
I dont remember exactly what it was, but i hab a code line (or was it just one word?) in the 000-default.conf that didnt belong. After deleting it, it worked.

15.07.2020 04:07:06 Antonio Emilio <notifications@github.com>:
