### ISSUE TITLE
Chromium based downloads of files not working

### ISSUE THREAD

**Issue by ReaperOfTheSoul** [Leantime/leantime#1580]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*
yes
**Describe the bug**
when uploading a PowerPoint file, after reopening or downloading not working, is opens the file in chrome but not as a PowerPoint file but as a txt file, not readable

**To Reproduce**
discribed see **Describe the bug**

**Expected behavior**
download of the file

**Leantime Version**
hosting by leantime 

**Server**
hosting by leantime 

**PHP / MySQL Version**
hosting by leantime 

**Additional context**
none

**Comment by ReaperOfTheSoul** [comment]
all office typed files have the same issue

**Comment by marcelfolaron** [comment]
Which version are you using? I fixed a bug like this in 2.3.16

**Comment by ReaperOfTheSoul** [comment]
It is the hosting of leantime itself, so they need to upgrade, i pay 7 dollars a user for this



Sent from my Galaxy



-------- Original message --------
From: Marcel Folaron ***@***.***>
Date: 4/18/23 23:59 (GMT+01:00)
To: Leantime/leantime ***@***.***>
Cc: ReaperOfSouls ***@***.***>, Author ***@***.***>
Subject: Re: [Leantime/leantime] Chromium based downloads of files not working (Issue #1580)


Which version are you using? I fixed a bug like this in 2.3.16

**Comment by marcelfolaron** [comment]
Thanks, let me take a look right now.

**Comment by marcelfolaron** [comment]
Please try now. We just published a bugfix.
