### ISSUE TITLE
[BUG] Theme Changes Ignored

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1589]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Theme colors that we were using before are now replaced with defaults.  My settings and UI settings are both ignored.

**To Reproduce**
1. Change your color settings in the .env file
2. Change your color settings in the UI
3. Logout, clear cache and log back end.
4. Nothing changed

**Expected behavior**
Theme colors respected

**Leantime Version**
2.3.18

**Server**
NGINX

**PHP / MySQL Version**
MariaDB 10.5

**Additional context**
I have created a video to make the problem obvious
* https://www.youtube.com/watch?v=Y-JHnDtme_4

**Comment by marcelfolaron** [comment]
Sorry about that, I will release a bug fix for this right now.

**Comment by marcelfolaron** [comment]
2.3.19 contains the fix
