### ISSUE TITLE
About date formats

### ISSUE THREAD

**Issue by evanlabs** [Leantime/leantime#159]
It is recommended to support multiple date format settings in the configuration file.
E.g. "yyyy/mm/dd" or "yyyy-mm-dd"

**Comment by marcelfolaron** [comment]
The current plan is to include the date format in the translation files for each language. 
See https://github.com/Leantime/leantime/blob/feature-i18nSupport/resources/language/en-US.ini
My assumption is that most folks would like to use the dateformat of their language. That format could still be changed within the language files.

**Comment by marcelfolaron** [comment]
Fixed in 2.1-beta
