### ISSUE TITLE
[BUG] Portfolio Page - No CSS or JS Loading

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1590]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
When you click the My Portfolio link, the page is severely broken.

**To Reproduce**
1. Click the My Portfolio icon
2. Page shows no CSS / JS and a white screen.

**Expected behavior**
Normal CSS / JS formatting / colors.

**Leantime Version**
2.3.18

**Server**
NGINX

**PHP / MySQL Version**
8.1

**Additional context**
I have created a video to make the problem more obvious.  
* https://www.youtube.com/watch?v=Po8hH-4bXZQ

I have opened an issue on this previously but was too busy to follow up.   I have since checked the log file and nothing shows up on any normal log including your built in error.log file.

There is something that shows up in the console that may be of value and is reflected in the above video.

**Comment by marcelfolaron** [comment]
I looked at the bugs in the console but can't seem to identify why they are occuring. 
First can you make sure to clear your cache? Second are there any other errors in the error.log file?

**Comment by compumatter** [comment]
Marcel,

I have cleared cache and in fact have gone a step further and tested this from a computer that is a VM in a different State that has never seen my URL.  Same result.

**Comment by marcelfolaron** [comment]
No errors in your log file?

**Comment by compumatter** [comment]
No.  Nothing.  I pointed the virtualhost file to your same log file so I could see anything no matter where it came from.  It's generates no log entries at all.   It's as though it's a cached file being presented and never queries the db at all.

**Comment by marcelfolaron** [comment]
Is this still an issue for you on the latest version?

**Comment by compumatter** [comment]
Marcel,

I did just install the latest version and the problem still exists yes.  
However this time I am getting a log :-)

PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must 
be of type Countable|array, bool given in 
/SM_DATA/web_projects/public_html/app/domain/projects/templates/showMy.tpl.php:225
Stack trace:
#0 /SM_DATA/web_projects/public_html/app/core/class.template.php(251): 
require_once()
#1 
/SM_DATA/web_projects/public_html/app/domain/projects/controllers/class.showMy.php(86): 
leantime\core\template->display()
#2 /SM_DATA/web_projects/public_html/app/core/class.controller.php(61): 
leantime\domain\controllers\showMy->get()
#3 /SM_DATA/web_projects/public_html/app/core/class.controller.php(33): 
leantime\core\controller->executeActions()
#4 
/SM_DATA/web_projects/public_html/app/core/class.frontcontroller.php(176): 
leantime\core\controller->__construct()
#5 
/SM_DATA/web_projects/public_html/app/core/class.frontcontroller.php(98): 
leantime\core\frontcontroller::executeAction()
#6 
/SM_DATA/web_projects/public_html/app/core/class.application.php(127): 
leantime\core\frontcontroller::dispatch()
#7 /SM_DATA/web_projects/public_html/public/index.php(26): 
leantime\core\application->start()
#8 {main}

The timeline view and table view are normal.  The card view looks like this.

Sincerely,

Jay
	
Jay Lepore
CompuMatter
*Office*: 360 299 2428 | *Cell*: 360 202 0434
*Email*: ***@***.***
/If you are satisfied with your service, please consider providing us a 
social media review at https://compumatter.com/reviews
...If you are not, please let me know so I can make it better/

**Comment by compumatter** [comment]
Hello Marcel,

Just wanted to make you aware that after upgrading to 2.5 release this issue still exists.

One thing I have learned is it is just my user.  My employees user accounts display completely normally.  Frankly after seeing what the page looks like it makes me want it more :-)

In the near future I will be demonstrating this program to others.  It would be great if we could isolate it prior.  Let me know if there is anything else I can send.

![image](https://github.com/Leantime/leantime/assets/121611/e7db4057-e98b-4dc6-9bca-5b8de652ce9c)

Jay

**Comment by marcelfolaron** [comment]
Thank you for following up. Do you have any other errors you have
encountered? It is so odd that it is only your user. I have not been able
to reproduce it so far.

**Comment by marcelfolaron** [comment]
Please verify whether you are still running into this in 2.4 beta
