### ISSUE TITLE
[BUG] Project Dashboard - Latest Todos - load the entire site in another dialog window

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1591]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Any Latest Todos link when clicked on launches the entire site within a popup dialog window

**To Reproduce**
1. Click on Project Dashboard
2. Click on any of the Latest Todos
4. You will see the entire website loads within a dialog window

**Expected behavior**
The todo of interest shows up.

**Leantime Version**
2.3.18

**Server**
NGINX

**PHP / MySQL Version**
8.1

**Additional context**
I have created a video to make the problem more obvious
* https://www.youtube.com/watch?v=LWZiVbsvu6w

**Comment by marcelfolaron** [comment]
Now fixed in the latest patch 2.3.20
