### ISSUE TITLE
[BUG] Project Task Parameters --> color choosing CSS broken ?

### ISSUE THREAD

**Issue by jmassiaux77** [Leantime/leantime#1595]
Leantime version 2.3.20

<img width="684" alt="Capture d’écran 2023-04-25 à 12 06 42" src="https://user-images.githubusercontent.com/123368774/234248096-79aff5f1-4782-48e3-9fb5-b498ba366638.png">

**Comment by marcelfolaron** [comment]
Did you update using the latest release package or is this via git pull?

Sincerely,
Marcel

**Comment by jmassiaux77** [comment]
Via git Pull

**Comment by marcelfolaron** [comment]
If you are pulling from tbe repo you need to run npm install
Composer install
Grunt —build-all

Otherwise the JavaScript files will not be generated.

**Comment by jmassiaux77** [comment]
Ok, it's my fault ...
This problem is solved :) 
I close it.
