### ISSUE TITLE
[BUG] Task editing --> Selectors are broken (state, priority, effort, ...)

### ISSUE THREAD

**Issue by jmassiaux77** [Leantime/leantime#1596]
Leantime 2.3.20

[2023-04-25 12:37 edit] Same problem in user/editOwn and timesheets/showMy/

<img width="764" alt="Capture d’écran 2023-04-25 à 12 26 59" src="https://user-images.githubusercontent.com/123368774/234249986-518a72b4-2c14-4ed2-9d36-b0e6db1a6dd7.png">

**Comment by marcelfolaron** [comment]
The javascript has changed significantly. Please try to clear your cache or do a hard reload (shift + reload). That should fix your issues with javascript

**Comment by jmassiaux77** [comment]
I have tried with cleared cache in Safari and Google Chrome but same problem.
Same with Microsoft Edge (never used with leantime, so, no cached js).

**Comment by jmassiaux77** [comment]
Ok, it's my fault ...
This problem is solved :) 
I close it.
