### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by sultan-dfir** [Leantime/leantime#1605]
I have an issue started this morning. I am running Centos OS
Suddenly the leantime stopped working (the browsers is not able to access) showing the following 
This site can’t be reached
X.X.X.X refused to connect.
I was able to ping the server from my computer

**Comment by marcelfolaron** [comment]
Is that a self hosted install? There weren't any updates so it is unlikely that this has something to do with Leantime

**Comment by sultan-dfir** [comment]
Thank you for your reply. You were right this issue had nothing to do with leantime.
its all working now. Thank you again
