### ISSUE TITLE
Pick today as default date in the time traking

### ISSUE THREAD

**Issue by EduFdezSoy** [Leantime/leantime#161]
When you are adding a time entry in the time traking tab inside a task, or a ticket as the url says (`tickets/showTicket/N#timesheet`) the date field is mandatory, I think this field may have the current date as default instead of being plain blank

**Comment by marcelfolaron** [comment]
Good point. Thanks for the input. I'll make sure to include that in the next release.

**Comment by marcelfolaron** [comment]
Fixed in 2.1-beta
