### ISSUE TITLE
[BUG] PL (polski) Language translate not works

### ISSUE THREAD

**Issue by tedmarcin** [Leantime/leantime#1621]
**Describe the bug**
No effect  if u  change language to PL (Polski), them is still English.

**Leantime Version**
2.3.21

**Server**
Apache, Debian 11

**PHP / MySQL Version**
php8.1 , mysql 5.7

**Comment by marcelfolaron** [comment]
Thank you. I submitted a fix on our hosted platform and updated the crowdin translations. If you are self hosted, this will go out with the next release.
