### ISSUE TITLE
[BUG] Unable to load site on OPERA browser Version:98.0.4759.15

### ISSUE THREAD

**Issue by ravikirankodmur** [Leantime/leantime#1623]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Unable to load site on OPERA browser Version:98.0.4759.15

**To Reproduce**
1. Go to https://rndsofrwaresolutions.leantime.io
2. Click on '....' - Nothing to click 
3. Scroll down to - N.A.
4. See error - 

**Expected behavior**

**Leantime Version**
Which Leantime version are you using

**Server**
Apache, nginx, IIS etc

**PHP / MySQL Version**
Please list the PHP and Mysql version you are using

**Additional context**

**Comment by ravikirankodmur** [comment]
Thanks for the quick support.
Checked in Private mode, 
Success...!

(Does the Server was down on Good Friday? The site was also not accessible...!)

**Comment by marcelfolaron** [comment]
Great, glad it worked. We did do some maintenance work on Good Friday, yes. We are building out a status page including notificatinos about our maintenance windows. We try to run these during low usage times and off hours.
