### ISSUE TITLE
[FEATURE] LDAP profile picture

### ISSUE THREAD

**Issue by qaniere** [Leantime/leantime#1627]
**Is your feature request related to a problem? Please describe.**
I need to get the same picture as my LDAP server

**Describe the solution you'd like**
A some way to get the picture associated to value "jpegPhoto"

**Comment by unex** [comment]
What do I need to set in `LEAN_LDAP_KEYS` for this to work? I tried `profileId` but still get the autogenerated avatar

**Comment by marcelfolaron** [comment]
Let me take a look at that one, it's been a while. Will get back tomorrow.
