### ISSUE TITLE
[BUG]  Blank Screen When delete a project

### ISSUE THREAD

**Issue by abhishekbeesony** [Leantime/leantime#1629]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [x] Self Hosted

**Describe the bug**
I have created project as owner and delete the same project which land to blank page.

**To Reproduce**
1. create a project
2.delete the project

**Expected behavior**

**Leantime Version**
latest version

**Server**
Apache,

**PHP / MySQL Version**
PHP8.2

**Additional context**
![image](https://user-images.githubusercontent.com/66721640/235880226-9949fbe4-4b1d-4b7a-857a-b1db176762f1.png)

**Comment by nonamenebula** [comment]
+1 same problem
