### ISSUE TITLE
[FEATURE] Sub-Project

### ISSUE THREAD

**Issue by massimiliano-dalcero** [Leantime/leantime#1634]
Hello,
I would like to propose a feature that I think could be useful to improve the logical structure of projects.

Some projects require a hierarchy capable of including hierarchical subprojects.

So I think it may be useful to provide the possibility of creating support for hierarchical sub-projects.

Greetings and thank you for your open source contribution :)

**Comment by marcelfolaron** [comment]
Our new structure allows you to create "Plans" which can have various projects. This solves the vast majority of use cases for this issue. To get plans you need to update to the latest version and get the "Plans" plugin from the app marketplace.

**Comment by massimiliano-dalcero** [comment]
Hello :)

the "plans" are not exactly what is needed. The need that other tools also have is precisely the creation of a hierarchical structure between projects :)
