### ISSUE TITLE
TASKS VIEW ERROR

### ISSUE THREAD

**Issue by paccmx** [Leantime/leantime#1645]
When viewing tasks in kaban view, filtered by milestone, and you open the task to edit, once you click save the task filter is lost, and you are looking at all taks from all milestones in the project.

**Comment by CodeShakingSheep** [comment]
I encounter the same bug but already when clicking on a ticket. Here is some more information to reproduce:

1. Select a milestone for filtering a project board. This leads to the following URL: https://domain.tld/tickets/showKanban?search=true&projectId=4&milestone=12 
2. Click on a a ticket's heading. This leads to the following URL: https://domain.tld/tickets/showKanban/#/tickets/showTicket/79 As you can see the URL parameters for filtering (e.g. milestone=12) is lost which leads to all tickets being displayed again.

Side information: Interestingly, when clicking on the comments icon, the URL parameters are preserved: https://domain.tld/tickets/showKanban?search=true&projectId=4&milestone=12#/tickets/showTicket/79

@marcelfolaron Can you provide a fix for this asap please? For tickets without comments, there is no workaround for this issue and it's kind of a deal-breaker to me as I use milestones a lot for grouping tickets. Thank you.

**Comment by marcelfolaron** [comment]
Looking into it right now.

**Comment by CodeShakingSheep** [comment]
Thank you for the lightning-fast fix :)
