### ISSUE TITLE
Mixed content behind nginx reverse proxy

### ISSUE THREAD

**Issue by EHRETic** [Leantime/leantime#1648]
Hi there,

I've exactly the same issue as described here: https://github.com/Leantime/leantime/issues/231

Some history : I had setup Leantime in a dedicated server. That server had a small NGINX instance to make it more secure with SSL certificate and port redirection. As the amount of web apps started to grow, I decided to switch to Docker based apps.

 My Docker setup consists of:
- a dedicated docker apps VLAN/subnet
- 2 DB servers (real VMs for MySQL & PostgreSQL)
- 1 docker instance VM with macvlan IPs for the containers
- 1 NGINX instance to access them from my internal network through DNS hosts names and dedicated SSL certificates
- access to https is limited to that reverse proxy only, no direct access to the containers IPs

The concept for internal app is the following:
browser --> https://leantime.domain.local --> Docker NGINX --> Leantime container

Everything works fine when I want to access **_leantime.domain.local_** only if I set up **LEAN_APP_URL** to https://leantime.domain.local

Here is the dedicated NGINS server part:

```
   server  {
        # Include HTTPS server standards
        include /etc/nginx/conf.d/server_security.conf;
        ssl_certificate "/etc/pki/nginx/leantime/certificate.pem";
        ssl_certificate_key "/etc/pki/nginx/leantime/key.key";

        # Add HSTS header (not available on local server)
        add_header Strict-Transport-Security "max-age=63072000; includeSubdomains" always;

        server_name leantime.domain.local;

        location  / {
                proxy_pass  http://192.168.X.X:80;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }
    }
```

In order to make some applications available from outside, I setup another NGINX server in DMZ and configured with the following concept in mind:

Browser --> https://leantime.domain.com --> DMZ NGINX --> https://leantime.domain.local --> Docker NGINX --> Leantime container

Here is the dedicated NGINS server part:

```
    server  {
        # Include HTTPS server standards
        include /etc/nginx/conf.d/server_security.conf;

        # Add HSTS header (not available on local server)
        add_header Strict-Transport-Security "max-age=63072000; includeSubdomains" always;

        server_name leantime.domain.com;

        location  / {
                proxy_pass https://leantime.domain.local;
                # proxy_http_version  1.1;
                proxy_cache_bypass  $http_upgrade;

                # proxy_set_header Upgrade           $http_upgrade;
                # proxy_set_header Connection        "upgrade";
                proxy_set_header Host              $proxy_host;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host  $host;
                proxy_set_header X-Forwarded-Port  $server_port;
        }
    }
```

I've tried several NGINX options and value in LEAN_APP_URL but I can't get it to work on both URLs and I don't think forwarding the DMZ NGINX directly to docker containers would solve the issue.

Maybe we can solve that with the DMZ NGINX configuration because it seems leantime.domain.local is still passed back to the browser, making CORS policy issues but it outside my knowledge. Don't also know if there is a plan to use "relative" links somehow within the app, you have to tell me.

Any clue how we can solve this? Thx in advance😊

**Comment by RoboMagus** [comment]
Same issue here using Traefik reverse proxy. Even though the `LEAN_APP_URL` is set with `https` protocol, Leantime tries to fetch data over plain old `http`.

My workaround is to enable an http-to-https redirect that forces all interactions to use https.
But I'd still like to see if there's a mitigation on the Leantime side instead of this.

**Comment by marcelfolaron** [comment]
Setting the appURL in the config should now fix any mixed content issues
