### ISSUE TITLE
Quirks mode

### ISSUE THREAD

**Issue by picarda** [Leantime/leantime#1653]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ X ] Self Hosted

**Describe the bug**
Hello, I'm getting a white page with Firefox with this message in the console:
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”

**To Reproduce**
1. Go to 'https://projets.a1sportdev.com/install'
2. See error

**Expected behavior**
Should see here the welcome page..

**Leantime Version**
2.3.23

**Server**
Apache

**PHP / MySQL Version**
8.1.18 /  MariaDB 15.1

**Comment by marcelfolaron** [comment]
So it appears quirks mode gets activated when there is no Doctype definition. 
Now that would only be the case if there is a 500 error or similar in the system. Can you check logs/error.log for any errors? 
It could also be a server configuration issue, so please also check apache/nginx error logs
