### ISSUE TITLE
[FEATURE] Team Calendar

### ISSUE THREAD

**Issue by aboyington** [Leantime/leantime#1654]
Asana has a shared calendar that all team members can access, view and edit. I belive that this would also be a welcome addition to leantime. 

Currently I can see my own calendar but it would be more beneficial to have a shared calendar to see a high level view of what all team members are working on or what scheduled tasks have been assigned to them, especially when we might be working on mutilple projects at the same time.

**Comment by TareqK** [comment]
I'd also second this, with an added CalDav sync capability for authorized users to integrate with mail clients and phone reminders
