### ISSUE TITLE
[BUG] All projects view is not filtering projects depending on access rights

### ISSUE THREAD

**Issue by cholletk** [Leantime/leantime#1655]
**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
When accessing to the "all projects" view, there is no filter on which project is displayed. A limited user (with only access to one project for example) could list all projects of this installation

**To Reproduce**
1. Login as a limited user
2. Go to 'Company Management'
3. Click on 'All projects'
4. You can see all projects of the company (even if you can't access to them)

**Expected behavior**
This view should only display projects with access grants for the current user

**Leantime Version**
2.3.23

**Server**
Apache

**PHP / MySQL Version**
PHP 8.2
Mariadb 10.5.16 

**Additional context**
Fresh install (no upgrade on it)

**Comment by marcelfolaron** [comment]
Hi, 
The menu point "All Projects" is an administrative menu point and not visible to everyone: 

Admins and up are allowed (and supposed to) see all projects whether they are assigned to them or not. 
Company managers are supposed to see the projects that are assigned to their dedicated client.
Editors and below are not supposed to see the menu point at all. 

Can you confirm that this is the case?

**Comment by cholletk** [comment]
Hi,
I double check and not able to reproduce this behavior. I was not performing logout + login after role change ... .
Sorry for this
