### ISSUE TITLE
Blank home screen after deleting project

### ISSUE THREAD

**Issue by billslim** [Leantime/leantime#1657]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
Self-Hosted

**Describe the bug**
  thrown in /var/www/html/leantime/app/domain/menu/controllers/class.menu.php on line 54
[19-May-2023 12:01:07 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: array_column(): Argument #1 ($array) must be of type array, bool given in /var/www/html/leantime/app/domain/menu/controllers/class.menu.php:54
Stack trace:
#0 /var/www/html/leantime/app/domain/menu/controllers/class.menu.php(54): array_column()
#1 /var/www/html/leantime/app/core/class.controller.php(63): leantime\domain\controllers\menu->run()
#2 /var/www/html/leantime/app/core/class.controller.php(33): leantime\core\controller->executeActions()
#3 /var/www/html/leantime/app/core/class.frontcontroller.php(176): leantime\core\controller->__construct()
#4 /var/www/html/leantime/app/core/class.frontcontroller.php(237): leantime\core\frontcontroller::executeAction()
#5 /var/www/html/leantime/public/theme/default/layout/app.php(23): leantime\core\frontcontroller::includeAction()
#6 /var/www/html/leantime/app/core/class.template.php(232): require('...')
#7 /var/www/html/leantime/app/domain/dashboard/controllers/class.home.php(114): leantime\core\template->display()
#8 /var/www/html/leantime/app/core/class.controller.php(61): leantime\domain\controllers\home->get()
#9 /var/www/html/leantime/app/core/class.controller.php(33): leantime\core\controller->executeActions()
#10 /var/www/html/leantime/app/core/class.frontcontroller.php(176): leantime\core\controller->__construct()
#11 /var/www/html/leantime/app/core/class.frontcontroller.php(98): leantime\core\frontcontroller::executeAction()
#12 /var/www/html/leantime/app/core/class.application.php(127): leantime\core\frontcontroller::dispatch()
#13 /var/www/html/leantime/public/index.php(26): leantime\core\application->start()
#14 {main}

**To Reproduce**
1. Delete onboarding project after installation

**Expected behavior**
Expected to return to a homepage to start a new project.

**Leantime Version**
2.3.21

**Server**
Apache, Ubuntu 22.04 Server

**PHP / MySQL Version**
PHP 8.1 / mariadb 10.1

**Additional context**
N/A

**Comment by marcelfolaron** [comment]
This issue was resolved in 2.3.23. Please update to the latest version and see if that solves the problem
