### ISSUE TITLE
More preset/provided color buttons for tasks and milestones AND/OR hue select tool

### ISSUE THREAD

**Issue by SociotechnicalAerospace** [Leantime/leantime#1664]
**Is your feature request related to a problem? Please describe.**
You have limited color options for tasks (no orange, limited selection) and even less color options for milestones. 

**Describe the solution you'd like**
The user profile/project profile has hex code color select options to create new hues for the project/website. This customization tool would be useful for you to incorporate into other parts of the software so users to be able to customize colors for tasks and milestones (and likely other features that other users use that I don't have experience with to note). 

**Additional context**
Google calendar and onenote and other products have preset color options like the ones you provide (midtones, not fully saturated but do not appear grey, hues across the color spectrum but not the full range), but that approach, even though google and microsoft have more options for presets than leantime, is still limiting in terms of customization for people who work with products and projects that have specific hues or color symbolism incorporated into the physical product or off-leantime planning and development. 

Obviously more color options are not necessary in general as the platform functions fine, but they would improve user experience for weirdos like me who are emotionally/cognitively attached to color theory to the point where it dictates which software I choose to use. Color helps me organize my thoughts, and I rely on it every day to manage my productivity, so I appreciate it when tools use it in a way that I find freeing and intuitive. It also can help with light sensitivity to some extent, but probably not at the level it would matter for your software unless you create the option for custom background colors and text (I didn't see this, so I'm assuming it's not a feature, but the view/reader of the website that is designed for Dyslexia may benefit from user-tunable color and font options (bold, scale) in addition to the font designed for easier legibility that you are currently using with that mode).

<img width="331" alt="Screenshot 2023-05-27 192647" src="https://github.com/Leantime/leantime/assets/134817068/caedf252-f98f-47f1-965f-1f8e77be743e">
<img width="277" alt="Screenshot 2023-05-27 192833" src="https://github.com/Leantime/leantime/assets/134817068/6811f40f-448a-49e8-8c67-cc795cd7ecc3">

**Comment by marcelfolaron** [comment]
I added more default colors that are save to use with that said the input field allows you to input any hexcode for colors.
