### ISSUE TITLE
[BUG] API method getOpenUserTicketsByProject doesn't return any results

### ISSUE THREAD

**Issue by nbhochland** [Leantime/leantime#1665]
**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
The method getOpenUserTicketsByProject is not returning any results. I am feeding it a valid userId and a valid projectId with open tickets, but the result is empty :

`{
    "jsonrpc": "2.0",
    "message": "Request was successful",
    "result": [],
    "id": "1"
}`

**To Reproduce**
POST to url/api/jsonrpc the following body with a valid api key in headers, replacing userId and projectId with valid values

`{
    "method": "leantime.rpc.tickets.getOpenUserTicketsByProject",
    "jsonrpc": "2.0",
    "id": "1",
    "params": {
        "userId":"7",
        "projectId":"4"
        }
}`

**Expected behavior**
I'm expecting a list of non-archived/non-blocked tickets assigned to the specified user from the specified project

**Leantime Version**
2.3.23

**Server**
debian 11
apache 2.4

**PHP / MySQL Version**
PHP 8.1
mariaDB 10.5.19

**Additional context**
using postman to do the tests. Other ticket methods are returning my tickets so I'm suposing this is a bug

**Comment by marcelfolaron** [comment]
Can you confirm that the user has access to the project? Or that the project is opened up to all users in the system.

**Comment by nbhochland** [comment]
Yes, user is owner of the project and there are open tickets

**Comment by marcelfolaron** [comment]
This method is also used on the home dashboard of a user. So far I have not been able to reproduce it. 
Do you see results on the dashboard/home screen?

**Comment by marcelfolaron** [comment]
Will close for now. We just released 2.4 beta which improved a lot of the API endpoints. Feel free to re-open if this is still an issue
