### ISSUE TITLE
Changing SMTP settings after initial config doesn't work

### ISSUE THREAD

**Issue by elimae17** [Leantime/leantime#1668]
Hi,

I have installed Leantime on our webspace. It works really great however I have problems with making changes to the configuration file now after the initial installation. 

When first configured the configuration file, I left the SMTP settings unchanged. Now, I would like to enable SMTP but if I turn it on with `public $useSMTP = true` (or `LEAN_EMAIL_USE_SMTP = true` ) I get a completely blank page. So nothing of the software works anymore. I tried it both with the configuration.php as well with an .env file, but neither one of them works. The installation breaks entirely.

I hope someone can help me with this issue!

Thanks
Elias

**Comment by marcelfolaron** [comment]
Can you check logs/error.log for any errors?

**Comment by elimae17** [comment]
Hi Marcel,

I checked the file and these are the errors from yesterday:

```
[01-Jun-2023 12:06:54 America/Los_Angeles] PDOException: SQLSTATE[28000] [1045] Access denied for user 'xxxx'@'localhost' (using password: NO) in /mydomain.com/app/core/class.db.php:74
Stack trace:
#0 /mydomain.com/app/core/class.db.php(74): PDO->__construct()
#1 /mydomain.com/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /mydomain.com/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /mydomain.com/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /mydomain.com/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /mydomain.com/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /mydomain.com/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct()
#7 /mydomain.com/app/core/class.application.php(46): leantime\domain\services\auth::getInstance()
#8 /mydomain.com/public/index.php(24): leantime\core\application->__construct()
#9 {main}
```

**Comment by marcelfolaron** [comment]
It appears it lost connection to the database. Which would be unrelated to SMTP. Did you change the db config as well?

**Comment by elimae17** [comment]
No I didn't change anything with the database... 

Other things I noticed are (which might be helpful):
- When I change the smtp setting back to false it works again
- The error log doesn't log any new errors when I'm changing the `$useSMTP` value back and forth
- When I am changing the title - `public $sitename` or `LEAN_SITENAME` - the installation does not break as it does with the SMTP settings, however the title of the page does not change at all. It stays with the site name I have given upon initial installation.

**Comment by marcelfolaron** [comment]
Please try using 2.4.4
We haven't seen any other smtp issues lately. Closing for now
