### ISSUE TITLE
Assign a task to more than one user

### ISSUE THREAD

**Issue by EduFdezSoy** [Leantime/leantime#167]
(This one is the last for today, I promise)

Change the task "Assigned to" selectable list to some sort of checkbox list, to allow us to assign a task to more than one user at a time (more like trello do)

--- 
This is not the right space to say it but whatever: I'll try to slide the spanish translations into our next Sprint since I read you are searching for some help with that

**Comment by gonztirado** [comment]
I think it will be an awesome feature too... ;) 

And yes! we did finally these Spanish translations 💪

**Comment by marcelfolaron** [comment]
Hey,

Our philosophy has always been that one person should own one task and if another person is working on it as well or a similar task they should own a copy of that. It makes accountability within the team a lot easier and avoids situations where it is not clear who is responsible for finishing a task. 

With that said, I can see how we might want to have collaborators on a task or watchers. In those cases one person would own the task while the others are listed as collaborators. 

Would that cover your use case?

**Comment by EduFdezSoy** [comment]
sounds good to me, how about assigning those collaborators to subtasks? what do you think?

**Comment by marcelfolaron** [comment]
That would be a lot easier, subtasks are basically the same as tasks internally. There has been another discussion to show subtasks on the kanban board as well. What do you think?

**Comment by EduFdezSoy** [comment]
dont know about that, showing them can be good but it may flood the board too
@gonztirado what do you think?

**Comment by gonztirado** [comment]
I think adding subtasks with other assignation is a good solution. The main TO-DO will be assigned to the guy who is responsible for the task, but we can add subtasks with different assignations. I think it fits all our needs, if you think it has an easier implementation, go for it! 👌 

About adding the subtask in the main kanban, definitely yes! It will be the best way to make a follow-up. But maybe it will be optional, with a "show subtasks" filter option in the kanban. Also, these subtasks must have a reference for the parent task.  

I hope we are not requesting so much. Again, thanks for your awesome project and for sharing with the community! 😄

**Comment by marcelfolaron** [comment]
We are tracking the subtask addition to the kanban board in #190 closing this issue

**Comment by eldraco** [comment]
This is still not possible, and I have the impression that it was lost in the subtasks.

**Comment by eldraco** [comment]
Sorry, I mean that this request to add more users to the same task was lost as an Issue when it was 'moved' to the Issue https://github.com/Leantime/leantime/issues/190, which it used to be related, but not anymore.

I would like this feature to be added still.
