### ISSUE TITLE
Add Custom Fields in project Settings

### ISSUE THREAD

**Issue by VINISHVV** [Leantime/leantime#1674]
Please add custom fields creation facility in leantime like other project management tool.

![image](https://github.com/Leantime/leantime/assets/65057910/9c9c5582-9d32-4da4-bf31-8ca6958d62af)

**Comment by gloriafolaron** [comment]
Could you share what sort of custom fields you are looking to create?

**Comment by helioguardabaxo** [comment]
Hi, @gloriafolaron !
I guess @VINISHVV suggest some thing like this:
https://www.redmine.org/projects/redmine/wiki/RedmineCustomFields

New fields with validation or regex would be very useful.

**Comment by gfviegas** [comment]
Seconding this with a solid example:

For backlog priorization: ICE, RICE, WSJF, etc. It would be awesome to have a custom "formula" field like clickup does which would allow to compute scores and use it to sorting the To Dos.

I reckon backlog priorization as a vital part of agile teams and without a custom field we would have to track it in a spreadsheet or something, which would be a shame since leantime is such an awesome platform :)

**Comment by gloriafolaron** [comment]
Thanks for the example! We definitely see the use cases here and plan on this coming out as a fast follow to our plugin marketplace release.

**Comment by luis-guimaraes-exoawk** [comment]
any news?

**Comment by gloriafolaron** [comment]
As mentioned on Discord (be sure to join -- things get updated more quickly there - https://discord.gg/mWvqKdYR):

Plugin marketplace is near finished. We’ll be launching it with high level strategy management, program plan management, whiteboard and hopefully AI. The very next one we’re looking at will be custom fields — this will likely include task types but we are still mapping that out.

Ideally, in the next 2-3 months unless it gets sponsored sooner or we get funding to bring on another engineer 🙂

We are happy to do sponsored features if someone is looking for it sooner or as part of our enterprise licensing. This helps keeps us running, growing, and gets features like this one out sooner.

**Comment by shafqatevo** [comment]
Hi @gloriafolaron, thanks to Leantime for this great software!

Curious what's the current ETA of Task Types and custom fields in tasks?

**Comment by gloriafolaron** [comment]
Good question! 

Custom fields is in development as a plugin right now. Expecting it to be done and out by mid month. 

@marcelfolaron fyi

**Comment by shafqatevo** [comment]
Thanks @gloriafolaron!

**Comment by marcelfolaron** [comment]
Custom Fields are now available as plugin!
