### ISSUE TITLE
gtunt default not working in the latest update

### ISSUE THREAD

**Issue by GhaziTriki** [Leantime/leantime#168]
Done, but with warnings.
root@devops:/var/www/leantime# grunt
Warning: Task "default" not found. Use --force to continue.

**Comment by GhaziTriki** [comment]
The new task name is `Build-All`.

**Comment by marcelfolaron** [comment]
Sorry, I haven't had a chance to update the readme yet. I'll cut a new release tonight and will update the readme as well.
