### ISSUE TITLE
v2.3 updated and no longer can get into instance

### ISSUE THREAD

**Issue by XTREEMMAK** [Leantime/leantime#1689]
Hi all,

Pulled the latest docker image for v2.3 and then asked me to upgrade database. Told it yes and it was successful. Now, after logging in, I'm able to see my old data, but as soon as I do anything, I'm met with:

> Service Unavailable
>The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
>
>Apache/2.4.56 (Unix) Server at plan.kjnet.us Port 80

Looking at the docker returns:
>2023-06-12 21:45:14,730 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config >file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
>2023-06-12 21:45:14,732 INFO supervisord started with pid 7
>2023-06-12 21:45:15,734 INFO spawned: 'php-fpm' with pid 8
>2023-06-12 21:45:15,736 INFO spawned: 'httpd' with pid 9
>[12-Jun-2023 21:45:15] NOTICE: fpm is running, pid 8
>[12-Jun-2023 21:45:15] NOTICE: ready to handle connections
>2023-06-12 21:45:16,760 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
>2023-06-12 21:45:16,760 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
>127.0.0.1 -  12/Jun/2023:21:45:17 +0000 "GET /index.php" 200
>127.0.0.1 -  12/Jun/2023:21:45:17 +0000 "GET /index.php" 200
>127.0.0.1 -  12/Jun/2023:21:45:17 +0000 "GET /index.php" 200
>127.0.0.1 -  12/Jun/2023:21:45:17 +0000 "GET /index.php" 200
>127.0.0.1 -  12/Jun/2023:21:45:17 +0000 "GET /index.php" 200
>127.0.0.1 -  12/Jun/2023:21:45:17 +0000 "GET /index.php" 200
>127.0.0.1 -  12/Jun/2023:21:45:17 +0000 "GET /index.php" 200
>127.0.0.1 -  12/Jun/2023:21:45:17 +0000 "GET /index.php" 200
>127.0.0.1 -  12/Jun/2023:21:45:17 +0000 "GET /index.php" 200
>127.0.0.1 -  12/Jun/2023:21:45:17 +0000 "GET /index.php" 200
>127.0.0.1 -  12/Jun/2023:21:45:17 +0000 "GET /index.php" 200
>127.0.0.1 -  12/Jun/2023:21:45:17 +0000 "GET /index.php" 200
>127.0.0.1 -  12/Jun/2023:21:45:17 +0000 "GET /index.php" 200
>127.0.0.1 -  12/Jun/2023:21:45:17 +0000 "GET /index.php" 200
>[12-Jun-2023 21:45:45] WARNING: [pool www] child 36 exited on signal 11 (SIGSEGV) after 29.438205 seconds from start
>[12-Jun-2023 21:45:45] NOTICE: [pool www] child 38 started

Again using docker and docker compose. How can I fix this?

**Comment by marcelfolaron** [comment]
Any errors in logs/error.log on the docker container?

**Comment by XTREEMMAK** [comment]
So, all I could find is error log entry for Apache:

[Mon Jun 12 21:43:48.285783 2023] [so:warn] [pid 10] AH01574: module proxy_module is already loaded, skipping
[Mon Jun 12 21:43:48.285839 2023] [so:warn] [pid 10] AH01574: module proxy_fcgi_module is already loaded, skipping
[Mon Jun 12 21:43:48.286561 2023] [lbmethod_heartbeat:notice] [pid 10] AH02282: No slotmem from mod_heartmonitor
[Mon Jun 12 21:43:48.287775 2023] [mpm_prefork:notice] [pid 10] AH00163: Apache/2.4.56 (Unix) configured -- resuming normal operations
[Mon Jun 12 21:43:48.287800 2023] [core:notice] [pid 10] AH00094: Command line: 'httpd -D FOREGROUND'
[Mon Jun 12 21:44:09.636915 2023] [proxy_fcgi:error] [pid 11] [client 192.168.224.1:53382] AH01067: Failed to read FastCGI header, referer: https://plan.kjnet.us/dashboard/home
[Mon Jun 12 21:44:09.636968 2023] [proxy_fcgi:error] [pid 11] (104)Connection reset by peer: [client 192.168.224.1:53382] AH01075: Error dispatching request to : , referer: https://plan.kjnet.us/dashboard/home
[Mon Jun 12 21:44:14.905402 2023] [proxy_fcgi:error] [pid 12] [client 192.168.224.1:43368] AH01067: Failed to read FastCGI header
[Mon Jun 12 21:44:14.905447 2023] [proxy_fcgi:error] [pid 12] (104)Connection reset by peer: [client 192.168.224.1:43368] AH01075: Error dispatching request to : 
[Mon Jun 12 21:45:12.356871 2023] [proxy_fcgi:error] [pid 18] [client 192.168.224.1:47610] AH01067: Failed to read FastCGI header
[Mon Jun 12 21:45:12.356933 2023] [proxy_fcgi:error] [pid 18] (104)Connection reset by peer: [client 192.168.224.1:47610] AH01075: Error dispatching request to : 
[Mon Jun 12 21:45:15.752199 2023] [so:warn] [pid 9] AH01574: module proxy_module is already loaded, skipping
[Mon Jun 12 21:45:15.752243 2023] [so:warn] [pid 9] AH01574: module proxy_fcgi_module is already loaded, skipping
[Mon Jun 12 21:45:15.752920 2023] [lbmethod_heartbeat:notice] [pid 9] AH02282: No slotmem from mod_heartmonitor
[Mon Jun 12 21:45:15.752947 2023] [core:warn] [pid 9] AH00098: pid file /run/apache2/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Mon Jun 12 21:45:15.754258 2023] [mpm_prefork:notice] [pid 9] AH00163: Apache/2.4.56 (Unix) configured -- resuming normal operations
[Mon Jun 12 21:45:15.754283 2023] [core:notice] [pid 9] AH00094: Command line: 'httpd -D FOREGROUND'
[Mon Jun 12 21:45:45.196793 2023] [proxy_fcgi:error] [pid 13] [client 192.168.224.1:44022] AH01067: Failed to read FastCGI header
[Mon Jun 12 21:45:45.196859 2023] [proxy_fcgi:error] [pid 13] (104)Connection reset by peer: [client 192.168.224.1:44022] AH01075: Error dispatching request to : 
[Mon Jun 12 21:57:37.068583 2023] [proxy_fcgi:error] [pid 11] [client 192.168.224.1:58094] AH01067: Failed to read FastCGI header
[Mon Jun 12 21:57:37.068648 2023] [proxy_fcgi:error] [pid 11] (104)Connection reset by peer: [client 192.168.224.1:58094] AH01075: Error dispatching request to :

**Comment by v-marinkov** [comment]
I have exactly the same problem. Updated from 2.3.23 to 2.3.25 and I can log in but clicking on any section in the left side bar crashes the server like above. After restarting the docker container, the clicked section (e.g. To-Dos) loads but changing to another (say Ideas) crashes it again.

**Comment by marcelfolaron** [comment]
Thanks all, @v-marinkov do you have any errors in your error.log file? 
I was looking into the issue and so far it appears to be a memory corruption problem which leads me to believe that there is an issue with the docker image itself (as opposed to the leantime code), but I am still verifying. Any errors or hints would be greatly appreciated as I was not able to reproduce the issue yet.

**Comment by v-marinkov** [comment]
@marcelfolaron exactly the same as above. So not much help, I'm afraid

**Comment by previmeteo** [comment]
if it can help you
<img width="918" alt="Capture d’écran 2023-06-13 à 15 18 09" src="https://github.com/Leantime/leantime/assets/5520605/12ab6708-f77b-434d-bbfb-3ce69702b2c9">

**Comment by arpichord** [comment]
Same issue here, docker compose.

The instance works for maybe... 5-10 seconds, then every attempt to load a page equates to a new log of the following WARNING and NOTICE:

`leantime        | [13-Jun-2023 13:58:28] WARNING: [pool www] child 36 exited on signal 11 (SIGSEGV - core dumped) after 23.527556 seconds from start
leantime        | [13-Jun-2023 13:58:28] NOTICE: [pool www] child 40 started
leantime        | [13-Jun-2023 13:59:05] WARNING: [pool www] child 37 exited on signal 11 (SIGSEGV - core dumped) after 60.980392 seconds from start
leantime        | [13-Jun-2023 13:59:05] NOTICE: [pool www] child 41 started
leantime        | [13-Jun-2023 13:59:07] WARNING: [pool www] child 40 exited on signal 11 (SIGSEGV - core dumped) after 39.219756 seconds from start
leantime        | [13-Jun-2023 13:59:07] NOTICE: [pool www] child 42 started
`

and a 503 service error.

![image](https://github.com/Leantime/leantime/assets/118236494/61ec8e66-056b-478f-b1fa-3df272650c20)

**Comment by zoell** [comment]
Same here with docker 2.3.25

**Comment by gloriafolaron** [comment]
We are having this same issue and continuing it on a thread on Discord as active troubleshooting. Please consider joining for faster updates and to help with any error logs that may help us troubleshoot.

https://discord.gg/XH28cGWw

The thread is under the I Need Help channel on a thread titled Docker Upgrade.

**Comment by marcelfolaron** [comment]
I just pushed a new docker image that seemed to have fixed it. Please check "latest"

**Comment by marcelfolaron** [comment]
Having to rebuild the images again. Stay tuned.
