### ISSUE TITLE
Missing menu selection functionality available in previous releases

### ISSUE THREAD

**Issue by diderich** [Leantime/leantime#1694]
Why has the possibility been removed to select a specific menu associated with a given project in commit #1678 ?

**Comment by marcelfolaron** [comment]
Hi Claude, 
Let's sync up on discord on this particular feature as I know you are using it. 

The menu selection dropdown was confusing for people and not used by the vast majority of users. However we introduced the concept of project types and your specific use case would be best added as a new project type via plugins. I can give you a skeleton of what that would look like.

**Comment by diderich** [comment]
There is an option `LEAN_ENABLE_MENU_TYPE = true|false` in the configuration file `.env` to enable/disable the functionality. So there should be no issue with confusion as/if the the option is `false` by default.

I don't think this is a use case for a plugin as it in part of multiple domains and templates.

**Comment by marcelfolaron** [comment]
The point is that the functionality of the custom menu option is now tied to project types. So it is a more flexible option. The "full menu" option just needs to be added as a project type. I'll provide an example soon.

**Comment by diderich** [comment]
Any news on the "promised example" front?
