### ISSUE TITLE
[FEATURE] Kanban swimlanes

### ISSUE THREAD

**Issue by RoboMagus** [Leantime/leantime#1707]
**Is your feature request related to a problem? Please describe.**
I use Leantime self-hosted. The UI and layout is nice to work with, but a feature that is really lacking is swimlanes.

**Describe the solution you'd like**
[Swimlanes for kanban](https://kanbanize.com/kanban-resources/kanban-software/kanban-swimlanes), Ideally collapsible. This could be a nice way to show all sprints in the Kanban view. Active sprint on top, planned sprints below that, and the backlog with all unplanned issues at the very bottom.

**Additional context**
-

**Comment by marcelfolaron** [comment]
We now have Kanban Swimlanes as of 2.4-beta
