### ISSUE TITLE
Deprecated: Automatic conversion of false to array is deprecated in /var/www/leantime/app/domain/menu/repositories/class.menu.php on line 204

### ISSUE THREAD

**Issue by PonlorkBeang** [Leantime/leantime#1709]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ ] Self Hosted

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Leantime Version**
Which Leantime version are you using
Version 2.3.25

**Server**
Apache, nginx, IIS etc

**PHP / MySQL Version**
Please list the PHP and Mysql version you are using
PHP8.1
Mariadb 10.11.2
**Additional context**
![image](https://github.com/Leantime/leantime/assets/97224078/8ad35f19-89b6-46eb-a6d9-8b7f7ac37fa0)
![image](https://github.com/Leantime/leantime/assets/97224078/8a6f895d-3bea-48fc-90b0-3998b8b29ba1)

**Comment by Sidvp** [comment]
command "grunt Build-all" required

**Comment by PonlorkBeang** [comment]
how to command "grunt Build-all" required?

**Comment by marcelfolaron** [comment]
This should now be fixed in 2.4-beta
