### ISSUE TITLE
[BUG] Some of the text in To-Do Table View is not visible (CSS issue)

### ISSUE THREAD

**Issue by benninkcorien** [Leantime/leantime#1710]
**What set up are you using**
* [x] Self Hosted

**Describe the bug**
 To-Dos, Table view. Tried this with all available themes.
 The CSS colors load fine at first (I can see the text flash when I force a CSS reload), but then get overridden by something that makes some of the text not visible. 
 

**To Reproduce**
1. Go to To-Do
2. Click on Table View
3.  See error

**Expected behavior**
Visible text

**Leantime Version**
2.3.25

kanban.css - these (and possibly more) don't load correctly.

    body .maincontent .priority-bg-4, body .maincontent .ticketDropdown .priority-bg-4 {
        color: var(--green-text-color);
    }
    body .maincontent .priority-bg-5, body .maincontent .ticketDropdown .priority-bg-5 {
        color: var(--dark-grey-text-color);
    } 
    body .maincontent .priority-bg-1, body .maincontent .ticketDropdown .priority-bg-1 {
        color: var(--dark-red-text-color);
    }
    .chosen-results li.label-info, .maincontentinner .ticketDropdown a.label-info, .nyroModalCont .ticketDropdown a.label-info {
        color: var(--dark-blue-text-color);
    }

Image: Status "New" is not showing ,  Priority apart from High and Medium is not showing
![Screenshot 2023-06-21 123849](https://github.com/Leantime/leantime/assets/9899593/c15e79c6-3517-4ed2-96a1-34dbedad04a4)

**Comment by marcelfolaron** [comment]
What theme do you have active?

**Comment by marcelfolaron** [comment]
I was not able to reproduce this issue. Do you see any errors in the console?

**Comment by benninkcorien** [comment]
Default (light) is active, but this issue occurs with all themes.

![image](https://github.com/Leantime/leantime/assets/9899593/daeb46af-87b6-454e-8ce8-235d2fbc87a2)

Console:

**Comment by benninkcorien** [comment]
compiled-base-libs.2.3.25.min.js is in URL/leantime/public/js/filename.js ..
