### ISSUE TITLE
[BUG]Not possible to upload any image

### ISSUE THREAD

**Issue by TanaKa1990** [Leantime/leantime#1723]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
 Self Hosted

**Describe the bug**
Upload of images are possible, but choosing any picture to insert in a text block/comment is not possible.

**To Reproduce**
1. Go to Task
2. Click on 'new Comment'
3. Click on 'images icon'
4. Choose one of the uploaded image
5. After clicking 'Save', a square is visible, with a question mar in it

If I insert an image via pasting, the image is visible for a few seconds and then disappear again. 

**Expected behavior**
I expect, that the image should be inserted in the comment

**Leantime Version**
latest 2.3.25

**Server**
nginx

**PHP / MySQL Version**
php 8.2.6/MySQL 5.7

additional comment:
I have try to upload the images in different ways.
a) opening a task, go to Files and "browse" -> After clicking OK, I get the info, that the upload was completed. And when I click to the uploaded image a 404 appears.

**Comment by marcelfolaron** [comment]
Thank you for your submission. Do you see any errors in logs/error.log ?

**Comment by TanaKa1990** [comment]
Thank you for your response. 

There are no entry in the error.log  to that issue. 

There are no entries that relate to this error in the log-file. 

In the meantime, however, I have tried to narrow down the error. 

I uploaded a picture for both the project and my profile. In both cases, this worked perfectly. By the way, the logos were png images. Just like the images that cause the error when uploading to the comment field. I don't know what to do.

**Comment by TanaKa1990** [comment]
Additional info:

when I click to the already uploaded images, which are listed in the 'Files' section of the project details, the following message is shown.
As you can see, I play around and try several formats of attachments. 

![Screenshot at Jun 27 23-20-15](https://github.com/Leantime/leantime/assets/137841763/ca91e3ed-5c15-4654-962f-172e1cb90b59)

**Comment by marcelfolaron** [comment]
Can you also check if there is a file called "null" in your public/ folder?

**Comment by TanaKa1990** [comment]
No such file.
Only assets and cgi-bin folder and config.js and index.html Files.
