### ISSUE TITLE
[BUG] -- HTTP ERROR 500

### ISSUE THREAD

**Issue by ahrensma** [Leantime/leantime#1724]
Leantime selfhosted

- macOS Monterey 12.6.7
- Apache/2.4.57 (Unix)
- OpenSSL/1.1.1u 
- PHP/8.2.7
- MYSQL/8.2.7 

Details see  [phpinfo.zip](https://github.com/Leantime/leantime/files/11892369/phpinfo.zip)

Upgrade from  Version 2.3.23 Version 2.3.25

After the upgrade I get an HTTP error 500. Subpages like /tickets/roadmap and /tickets/showKanban can still be displayed, /dashboard/show and /projects/showProject/* remain empty.

The error.log says 'Column not found: 1054 Unknown column 'zp_user.jobTitle' in 'field list' in /usr/local/var/www/leantime/app/domain/projects/repositories/class.projects.php:833'.

or more detailed

[28-Jun-2023 02:09:55 America/Los_Angeles] PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'zp_user.jobTitle' in 'field list' in /usr/local/var/www/leantime/app/domain/projects/repositories/class.projects.php:833
Stack trace:
#0 /usr/local/var/www/leantime/app/domain/projects/repositories/class.projects.php(833): PDOStatement->execute()
#1 /usr/local/var/www/leantime/app/domain/projects/services/class.projects.php(795): leantime\domain\repositories\projects->getProjectUserRelation('10')
#2 /usr/local/var/www/leantime/app/domain/dashboard/controllers/class.show.php(56): leantime\domain\services\projects->getProjectUserRelation('10')
#3 /usr/local/var/www/leantime/app/core/class.controller.php(61): leantime\domain\controllers\show->get(Array)
#4 /usr/local/var/www/leantime/app/core/class.controller.php(33): leantime\core\controller->executeActions('get', Array)
#5 /usr/local/var/www/leantime/app/core/class.frontcontroller.php(176): leantime\core\controller->__construct('get', Array)
#6 /usr/local/var/www/leantime/app/core/class.frontcontroller.php(98): leantime\core\frontcontroller::executeAction('dashboard.show', Array, 200)
#7 /usr/local/var/www/leantime/app/core/class.application.php(127): leantime\core\frontcontroller::dispatch()
#8 /usr/local/var/www/leantime/public/index.php(26): leantime\core\application->start()
#9 {main}

**Comment by marcelfolaron** [comment]
Did you pull from master or update the package? It should have redirected you to /install/update to add those fields?

**Comment by ahrensma** [comment]
Yes, I start the update process, I got a long time an empty (white) page, 5min later I opened the website over 127.0.0.1.
