### ISSUE TITLE
[BUG] Todo Columns sometimes require drag and drop "in the blind"

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1727]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
Often times the "New" todos columns is quite a bit longer than the ones in progress.  When I wish to move a task up the ladder to another column the columns themselves are no longer visible so you have to drop them in columns in the blind.  

**To Reproduce**
1. Create enough Todo's in any one column that exceed it's neighbors by 3 or more tasks.
2. Drag it to a nearest neighbor column

**Expected behavior**
Some sense of what columns are being dragged into.  Perhaps some mirror of the top headings that ride at the bottom of the longest column... Perhaps some light shading different OR some column borders to indicate where they are.   Anything but blind would be good.

**Leantime Version**
2.3.25

**Server**
NGINX

**PHP / MySQL Version**
8.1 / 10.4 Mariadb

**Additional context**
I've created a short video to make the problem more obvious:
* https://www.youtube.com/watch?v=0kAxFAmXof0

**Comment by marcelfolaron** [comment]
Thanks I'll take a look at the issue.

**Comment by marcelfolaron** [comment]
This should now be fixed in 2.4-beta
