### ISSUE TITLE
Install on Ionos hosted server

### ISSUE THREAD

**Issue by witzker** [Leantime/leantime#173]
Followed the instructions
domain.com/install brings white screen
PLS Help

**Comment by marcelfolaron** [comment]
Any errors in resources/logs/error.log ?
Which version did you use?

**Comment by witzker** [comment]
THX for taking care
error log = empty
Version: Leantime-V2.0.14.zip

I have created a subdomain pointing to 
/leantime/public
created database
leantime/config/configuration.php with database datas

Hope for help

**Comment by marcelfolaron** [comment]
Do you know which PHP version is installed and if mod_rewrite is enabled on
Apache?

Can you go to: domain.com/index.php?install=true and check if the
installation page shows up?

**Comment by witzker** [comment]
PHP 7.3
mod_rewrite is enabled  ?

domain.com/index.php?install=true 
install page comes up
I put in email
continue
white page again

**Comment by marcelfolaron** [comment]
That means that htaccess is not working properly. Can you check your apache logs for any errors. 
There might be a specific ionos setting.

**Comment by witzker** [comment]
Ok but I'm really new with this which on is interresting? Pls help

![grafik](https://user-images.githubusercontent.com/4120266/77252329-6e7d1d00-6c53-11ea-9eaa-78d16bbc7a83.png)
![grafik](https://user-images.githubusercontent.com/4120266/77252340-7fc62980-6c53-11ea-91be-25c47ed62b9d.png)

**Comment by marcelfolaron** [comment]
There should be an error log somewhere. I don't see it on this screen.

**Comment by witzker** [comment]
I found this but I don't know where to put what?

![image](https://user-images.githubusercontent.com/4120266/77256386-2f0ffa00-6c6e-11ea-9d63-7b8dc4860826.png)

**Comment by marcelfolaron** [comment]
Those are the php error logs, which aren't quite what we need. 
We are looking for the apache error logs since there is a problem with your htaccess configuration. 

Are you on a dedicated server or a shared host? For dedicated servers you will need to make sure you enable htaccess manually (follow the guide under "Is the .htaccess File Being Read?": 

https://www.ionos.com/community/server-cloud-infrastructure/apache/how-to-fix-http-error-code-500-internal-server-error/

**Comment by witzker** [comment]
Shared host

I also have Nextcloud there
I put in the htaccess  of Nextcloud something rewrite ?? HTTP -> HTTPS
and it worked, so I think the htaccess support should work on Ionos

**Comment by marcelfolaron** [comment]
Try setting `$debug = 1` in configuration/settings.php and see if that
shows any error messages

**Comment by DanielDLRG** [comment]
Have you tried including  "RewriteBase / " in .htaccess-file (in public) folder just below the line RewriteEngine On ?

**Comment by witzker** [comment]
SO!!
I have now:

RewriteEngine On
RewriteBase / 

#Uncomment and update if Leantime runs in a subfolder
#RewriteBase /leantime/

RewriteCond %{HTTP:X-Forwarded-Proto} =http
RewriteRule .* https://%{HTTP:Host}%{REQUEST_URI} [L,R=permanent]

RewriteRule ^resetPassword$ index.php?resetPassword=true
RewriteRule ^resetPassword/([^/\.]+)/?$ index.php?resetPassword=true&hash=$1

RewriteRule ^install$ index.php?install=true
RewriteRule ^install/([^/\.]+)/?$ index.php?install=true

RewriteRule ^update index.php?update=true
RewriteRule ^update/([^/\.]+)/?$ index.php?update=true

RewriteRule ^/?$ index.php?act=dashboard.show
RewriteRule ^([^/\.]+)/([^/\.]+)/?$ index.php?act=$1.$2 [QSA]
RewriteRule ^([^/\.]+)/([^/\.]+)/([^/\.]+)/?$ index.php?act=$1.$2&id=$3 [QSA]

WORKING !!
Great
THX

**Comment by marcelfolaron** [comment]
Awesome, I am glad it got resolved. Thanks @DanielDLRG for the tip.
