### ISSUE TITLE
[BUG] Incorrect dates displayed in Timeline Milestones Gantt View

### ISSUE THREAD

**Issue by beddows** [Leantime/leantime#1735]
**What set up are you using**
* [X ] Cloud Hosted Version

**Describe the bug**
In the Gantt View of the Timeline Milestones, the gantt bars appear to be ~11 days behind the actual date values.

**To Reproduce**
1. Go to Timeline
2. Click on Add Milestone
3. Enter Milestone Title including Planned Start Date and Planned End Date
4. Save and see the milestone displayed ~11 days behind the planned dates (for Timeframe: month)

**Expected behavior**
The milestone timeline view to be congruent with dates entered.

**Leantime Version**
2.3.25

**Additional context**
This bug is in "Timeframe: month". The "Timeframe: week" displays the correct dates.

**Comment by marcelfolaron** [comment]
Thank you for submitting the bug. We have confirmed that there is an issue with the day calculation and "where" the today line appears. A fix has been submitted and will be released shortly.
