### ISSUE TITLE
[BUG] Keep getting logged out

### ISSUE THREAD

**Issue by beddows** [Leantime/leantime#1737]
**What set up are you using**
* [X] Cloud Hosted Version

**Describe the bug**
For the past couple of days, I've been intermittently logged out. Now it's happening more frequently. At one point, the site wouldn't accept my user name and password. So I reset my password, but I'm still being logged out.

**To Reproduce**
Any activity.

**Leantime Version**
2.3.25

**Additional context**
I'm using Safari 16.5.1 on MacOS 13.4.1

**Comment by distresscode** [comment]
I'm experiencing a similar issue, but on the self-hosted version. I will open a new ticket.

**Comment by marcelfolaron** [comment]
This should now be fixed in 2.4-beta
