### ISSUE TITLE
[BUG] Documentation points to outdated sample config

### ISSUE THREAD

**Issue by dantefromhell** [Leantime/leantime#1739]
The documentation in https://docs.leantime.io/#/installation/docker
points to https://github.com/Leantime/leantime/blob/master/config/configuration.sample.php#L124
while the top of `configuration.sample.php` states

> @deprecated 2.3.15 Please do not use this configuration file anymore

Due to the anchor on line 124 this is very easy to overlook

**Comment by jiriks74** [comment]
I no longer see that it's deprecated. The new message says:

```php
/***
 *
 * Config class
 * This class is included for backwards compatibility and to be used with subfolder installations
 *
 * @see config/sample.env
 */
```

**Comment by marcelfolaron** [comment]
Docs were recently updated
