### ISSUE TITLE
[BUG] Export in My Portfolio as CSV includes injected html code

### ISSUE THREAD

**Issue by rjjrbatarao** [Leantime/leantime#1742]
If you have problems with the installation please use our [community forum](https://community.leantime.io/)

Describe the bug

After finding a way to export tasks I looked into the csv and it includes injected html code which breaks the csv

To Reproduce

Go to 'My Portfolio'
Switch to table view
Click Export
Get csv with a lot of html code
Expected behavior
Get a clean sanitized csv

Leantime Version
2.3.25

Server
Nginx, Mariadb

PHP / MySQL Version
PHP8.0

Additional context
What you wanna know?

**Comment by marcelfolaron** [comment]
Not applicable anymore.
