### ISSUE TITLE
[BUG] Table overflowed on My Timesheets

### ISSUE THREAD

**Issue by rjjrbatarao** [Leantime/leantime#1743]
If you have problems with the installation please use our [community forum](https://community.leantime.io/)

Describe the bug

The My Timesheets when loaded shows overflowed tables extended on the page

To Reproduce

Go to 'My Timesheets'
Toggle it in week view

Expected behavior
View should be a scrollable table view of timesheets in week view

Leantime Version
2.2.8

Server
Nginx, Mariadb

PHP / MySQL Version
PHP8.0

Additional context
What you wanna know?

**Comment by marcelfolaron** [comment]
This was fixed a while ago in 3.0
