### ISSUE TITLE
Reset password not working[BUG]

### ISSUE THREAD

**Issue by megadoga** [Leantime/leantime#1748]
**What set up are you using**
* [x] Cloud Hosted Version

**Describe the bug**
I forgot the password and try to you the Reset password feature (like, months ago).
I still did not receive any email regarding "leantime" password reset.

**To Reproduce**
1. In the login page.
2. I click on "Forgot password?"
3. In the next page I put my email and click "Reset password"
4. The webpage says an email was sent to me, but there is no email in my inbox - of course, I already checked the Spam folder.

**Expected behavior**
After clicking on Reset password. I was expecting to receive an email with instructions or a link to reset my password.

**Leantime Version**
I'm using the cloud version.

**Server**
I'm not using in any server.

**PHP / MySQL Version**
...

**Additional context**
I'm trying to log from my MacBook.

**Comment by marcelfolaron** [comment]
Thanks for reaching out. Can you email me (marcel@leantime.io) your subdomain and email address so I can verify why the email was not sent?
