### ISSUE TITLE
[BUG] Upgrade to 2.3.26 does not create cache/avatars folder

### ISSUE THREAD

**Issue by devenbj** [Leantime/leantime#1759]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
Just upgraded to 2.3.26 using the shell script. Running on Ubuntu with Nginx / PHP-FPM. After upgrading, no pages would finish rendering. Console was showing multiple 500 codes. Server logs reported it did not have permissions to create the cache/avatars/...png file.

I created and permissioned the cache folder and the avatars folder. Everything is working now. Reporting this for awareness.

**To Reproduce**
1. Have a working Leantime 2.3.25 on Nginx / PHP-FPM
2. Run the updateLeantime.sh script
3. Go to site
4. Update the database with the prompt
5. Get 500 errors

To fix:
1. Create 'cache' folder at root of Leantime install folder and set owner to the web user
2. Inside cache folder create 'avatars' folder and set owner to the web user

**Expected behavior**
No errors after upgrade

**Leantime Version**
2.3.26

**Server**
Nginx

**PHP / MySQL Version**
PHP 8.2.8, MariaDB 10.11.4

**Additional context**
No additional context. Thanks!

**Comment by tech62** [comment]
Confirmed, i've the same problem after manually creating the folder , it works

**Comment by marcelfolaron** [comment]
Issue has been fixed in 2.3.27
