### ISSUE TITLE
[BUG] modal fade in targets makes it impossible to click on the target. 

### ISSUE THREAD

**Issue by yursh** [Leantime/leantime#1762]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [x] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
when switching to targets, having several targets in one board, it is not possible to click on the target as that place is occupied by the field.

**To Reproduce**
1. Go to 'targets'
2. Click on 'boards'
3. Click on 'Inspect element'  top/middle of the screen

**Additional context**
<img width="1680" alt="modals" src="https://github.com/Leantime/leantime/assets/38814372/bfb71d44-01c7-4ff4-93eb-f30e7539a162">

**Comment by marcelfolaron** [comment]
This should be fixed with the latest version 2.3.27
