### ISSUE TITLE
[BUG] it is not possible to delete Event in the calendar

### ISSUE THREAD

**Issue by yursh** [Leantime/leantime#1763]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [x] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
If you create a new event in the calendar directly from the calendar, it cannot be deleted. See screenshot

**Leantime Version**
2.3.25

**Additional context**
<img width="1680" alt="Calendar Error" src="https://github.com/Leantime/leantime/assets/38814372/cc60834a-c9e0-4ba6-a714-7226fe6e7991">

**Comment by marcelfolaron** [comment]
This should now be fixed in 2.4-beta
