### ISSUE TITLE
[BUG] Could not update milestone from calendar view. 

### ISSUE THREAD

**Issue by Devusol** [Leantime/leantime#1769]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x ] Self Hosted

**Describe the bug**
Could not update milestones from the calendar view. Hangs on loading view with the clock.

**To Reproduce**
1. Go to Timeline
2. Change to calendar view
3. Make a change on the modal and click save twice
4. Screen is stuck on the loading view with the clock.

**Expected behavior**
Updates data and closes loading screen.

**Leantime Version**
2.3.25

**Server**
Apache

**PHP / MySQL Version**
8.1

**Additional context**

**Comment by marcelfolaron** [comment]
This should now be fixed in 2.4-beta
