### ISSUE TITLE
[BUG] Dark mode milestones year view CSS. Cannot see numbers on white background.

### ISSUE THREAD

**Issue by Devusol** [Leantime/leantime#1773]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ x] Self Hosted

**Describe the bug**
The milestone year view calendar is white with white background. Hard to see.

**To Reproduce**
1. Change view to Dark mode
2. Go to the timeline
3. Change the view to calendar
4. Change the timeframe to Year
5. See the error

**Expected behavior**
update text color to a contrasting color or change the background to dark

**Leantime Version**
2.3.25

**Server**
Apache

**PHP / MySQL Version**
8.1

![Capture](https://github.com/Leantime/leantime/assets/40222187/7d3bab0c-304e-4fff-b99e-d3b164be6424)

**Comment by jiriks74** [comment]
Looks like this got fixed. Could this be closed?
![image](https://github.com/Leantime/leantime/assets/54378412/60e77491-48c2-43e4-937c-ea893a9f1bdd)
