### ISSUE TITLE
[BUG] Timesheet update causes other time calculations not rounded

### ISSUE THREAD

**Issue by Devusol** [Leantime/leantime#1776]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x ] Self Hosted

**Describe the bug**
When a timesheet update is made, other tasks for that same week total is an unrounded decimal. After saving, it rounds properly.

**To Reproduce**
1. Log time on two tasks on two different days
2. Go to the timesheet and adjust one of the times
3. Edit another time
4. See the error

**Expected behavior**
Calculations will be rounded to 2 decimals

**Leantime Version**
2.3.25

**Server**
Apache

**PHP / MySQL Version**
8.1

**Additional context**
![Screenshot 2023-07-28 094845](https://github.com/Leantime/leantime/assets/40222187/0915822d-1a89-4d48-9d74-5173d9923d5c)

**Comment by marcelfolaron** [comment]
This should now be fixed in 2.4-beta
