### ISSUE TITLE
[BUG] Redis running out of memory - restarting redis doesn't free up memory either

### ISSUE THREAD

**Issue by distresscode** [Leantime/leantime#1780]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
Self Hosted via Cloudron https://www.cloudron.io/store/io.leantime.cloudronapp.html

**Describe the bug**
Redis running out of memory. Restarting Redis does not free up used memory.

**To Reproduce**
Fresh install of Leantime on a Cloudron server. Watch Redis grow and run out of memory and crashes the app.

**Expected behavior**
Really?

**Leantime Version**
Leantime v2.3.27

**Server**
Cloudron 7.5.0 on Ubuntu 22.04 

**PHP / MySQL Version**
no clue amigo

**Additional context**
Screenshot of Redis usage of Leantime while idle (no active users)
![idle](https://github.com/Leantime/leantime/assets/2686608/33487cf7-2be7-4b2a-962d-0f52b1e645ac)

Screenshot of Redis usage after restarting Redis - barely frees up any memory!
![after-restart-redis](https://github.com/Leantime/leantime/assets/2686608/a1912ab6-2541-4bdb-9c68-34c3da5d4547)

**Comment by Hillside502** [comment]
> Leantime Version
Leantime 0.2.0

Leantime on Cloudron is v2.3.27 --- 0.2.0 is the internal Cloudron packaging version

**Comment by distresscode** [comment]
@Hillside502 Thanks for catching that!

**Comment by distresscode** [comment]
I set up another install of Leantime. Redis is exhibiting the same behavior. Fills up to 95% and runs out of memory after a while. Restarting Redis brings it down to 80% and then fills back up....

![image](https://github.com/Leantime/leantime/assets/2686608/08a9eaf4-d25b-498f-9b55-db9d643fe72e)

**Comment by gramakri** [comment]
Cloudron maintainer here. Currently, we configure cloudron redis with `maxmemory-policy allkeys-lru` . Is this a problem for leantime?

**Comment by marcelfolaron** [comment]
I’m not entirely sure to be honest.
All we’re storing on Redis is session data and the php garbage collector
should clean that up before memory is exhausted.

Does this issue persist if you’re logged out?

Do you set any other php GC configs?
I don’t see any redis issues in our other environments and memory usage
seems to fine.

**Comment by distresscode** [comment]
@marcelfolaron Yes, I'm logged out and the issue persists, even if I restart Leantime and Redis. I'm running the default settings (fresh install of Leantime). The app memory usage is fine. It's Redis memory that is filling up/crashing here.

This is where my tech skills end :( Girish @gramakri can let you know what the package is running.

**Comment by marcelfolaron** [comment]
Yeah so when your logged out there is (almost) nothing in the session
variable left. So I doubt it’s coming from Leantime data.
