### ISSUE TITLE
Time-based blind injection

### ISSUE THREAD

**Issue by M507** [Leantime/leantime#179]
A vulnerable parameter to time-based blind injection.

_Details have been removed_

**Comment by marcelfolaron** [comment]
Thank you for reaching out. We have received and verified the issue and will send out a patch within the next 24 hours.

**Comment by marcelfolaron** [comment]
Fixed in 2.0.15 and 2.1.-beta3

**Comment by M507** [comment]
Can you request a CVE notice for the vulnerability on the Security Advisories section?

**Comment by marcelfolaron** [comment]
Done

**Comment by M507** [comment]
Thank you @marcelfolaron ! @github-staff requested an update. I updated it as what I think they want. Please review it and resubmit the request again.
