### ISSUE TITLE
[FEATURE] Hours left auto-calculation

### ISSUE THREAD

**Issue by Devusol** [Leantime/leantime#1796]
**Is your feature request related to a problem? Please describe.**
During weekly planning, we assess hours assignments for the following week in the table view. When we make hours adjustments we have to manually adjust both the planned and hours left columns. 

**Describe the solution you'd like**
It would be great if the hours left column would automatically calculate when the planned hours value changes

**Comment by marcelfolaron** [comment]
Calculations are now in the table
