### ISSUE TITLE
Move a TO DO task between different projects

### ISSUE THREAD

**Issue by gonztirado** [Leantime/leantime#180]
Maybe can be a nice feature if we can move a task to a different project.

For example, we have a project with a task, but finally, this task must be assigned to another team with a different kanban board.

**Comment by dqn9t2** [comment]
I think this is good, bc some project have the same tasks, it will save alot of time for us if we dont have to remake them all.

**Comment by marcelfolaron** [comment]
Yes, we need that. I assume we'd want the option to copy and move the todo/milestone?

**Comment by dqn9t2** [comment]
Yes. Copy from project to project, it will save time. Thank you for your work!

**Comment by jakimfett** [comment]
Having the ability to move and duplicate any item, be it a research hypothesis or an idea, would be rather useful, and would indeed save time during project setup.

**Comment by gonztirado** [comment]
I agree with @jakimfett. All the elements should be transferable or copied between projects

**Comment by YQGong** [comment]
Is there any progress on this feature? This could be very useful.

**Comment by davask** [comment]
Looking forward to that feature

**Comment by compumatter** [comment]
I am in need of this feature as well.  This is another one of those core needs that come up over and over again.  You've created a project, some todo's and at some point the scope of the project changes and you need to move that Todo and its innards to another project / column.  At present it's a painful copy / paste anytime that comes up and it comes up often.

**Comment by romzis** [comment]
Hey! 
Any progress on this feature? 
Thanks for your work!

**Comment by romzis** [comment]
> Hey! Any progress on this feature? Thanks for your work!

I've found some workaround using a database.
You find a project that you need to assign to a task in zp_projects table, get the project id.
Then you can update a field projectId in zp_tickets table with a new project id what you have got in prev. step.

It works for me.
