### ISSUE TITLE
[BUG] Order of tasks and under tasks in the Gantt view

### ISSUE THREAD

**Issue by Philippe-M** [Leantime/leantime#1801]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
In the Gantt view, the tasks and subtasks are not displayed in the hierarchic order but in the order of creation.

Tasks and subtasks are organized in this way:

```
"Saisie des commandes"
	|__ "Préparation des stocks"
	|__ "expédition des commandes"
```
But they are displayed in another order.

![image](https://github.com/Leantime/leantime/assets/4558101/af297fdd-bcb1-4da2-b09d-fe7d28b4e3b2)

**Expected behavior**
Normally the Gantt should display the main task and below the subtasks.

![image](https://github.com/Leantime/leantime/assets/4558101/82fd9620-110c-4bba-9e11-b4c84621ea6c)

**Leantime Version**
2.3.27

**Server**
Apache

**PHP / MySQL Version**
Php 8.0 / mysql 5.7

**Comment by marcelfolaron** [comment]
This should now be fixed in 2.4-beta
