### ISSUE TITLE
[BUG] The Gantt view does not record task move

### ISSUE THREAD

**Issue by Philippe-M** [Leantime/leantime#1802]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
In the Gantt view, in a week's time slot for example, when I move a task from one line to another, this is not recorded after recharging the page.

**To Reproduce**
[Capture vidéo du 2023-08-07 14-50-03.webm](https://github.com/Leantime/leantime/assets/4558101/8415dd0f-04d2-40c9-a9dc-a809d81dc8fd)

**Expected behavior**
The order should be kept or if it is not possible to do this action, the displacement by clicked placed should be deactivated.

**Leantime Version**
2.3.27

**Server**
Apache

**PHP / MySQL Version**
Php 8.0 / mysql 5.7

**Additional context**
Firefox 115.0.2 on Fedora 38

**Comment by marcelfolaron** [comment]
This should now be fixed in 2.4-beta
