### ISSUE TITLE
SLOW RESPONSE FROM SERVER

### ISSUE THREAD

**Issue by paccmx** [Leantime/leantime#1803]
I am not sure if this is my service provider, I recently I have noted a delay en server response when using leantime.  So much that some time when creating a new task in Kaban view, I hit enter two times, and a duplicate task is created.  I have also noted that aste updateing a task, you return to kaban view, and is refreshed two times...  

I have no way (knowledge) to check database connection speed, but if instructed on how to do so, would.  I am using MYSQL.

![image](https://github.com/Leantime/leantime/assets/107881696/08dd9efc-4771-4b2c-a442-6dff72ddcf04)

**Comment by marcelfolaron** [comment]
Response times should have improved significantly in 2.4-beta
