### ISSUE TITLE
[BUG] Redirected to /dashboard/home is returning a blank page.

### ISSUE THREAD

**Issue by mariushosting** [Leantime/leantime#1810]
Latest **2.3.27** version issue. When you log-in you will be automatically redirected to **/dashboard/home** which leads to a blank page instead of the dashboard page.
@marcelfolaron

**Comment by Daerendor** [comment]
I second this issue

**Comment by mariushosting** [comment]
This happens on the leantime Docker version for over 1 month

**Comment by Daerendor** [comment]
See #1792 for a fix for Nginx

**Comment by marcelfolaron** [comment]
This should be fixed now
