### ISSUE TITLE
Leantime with Synology DSM 7.2

### ISSUE THREAD

**Issue by Emad-Marji** [Leantime/leantime#1816]
Hi @marcelfolaron,
It wasn't easy to install leantime with Container Manager in DSM 7.2; but finally managed :)
It seems to be working fine under the localhost, but when using the reverse proxy in Synology, I can't access the dashboard.
When accessing using the localhost, it is there, but when using my local domain via HTTPS and let's encrypt certificate, I can access everything except the dashboard!!!
Any advice? do I need to configure the domain in the .env file?

![001](https://github.com/Leantime/leantime/assets/102861171/42228b7b-a662-43e6-aa6a-07b847688a68)
![002](https://github.com/Leantime/leantime/assets/102861171/c1759353-b6bf-4383-9d4d-e7f975379634)

**Comment by marcelfolaron** [comment]
Can you check the error logs in logs/error.log in your instance?

**Comment by Emad-Marji** [comment]
Thanks @marcelfolaron, but I cannot SSH my Synology NAS.
Not sure if correct, but I have added a volume to: - ./error.log:/logs/error.log and rebuilt the container. The log file has no entries and is still 0 bytes in size.
It is very strange as I can access the dashboard using the local IP address!!!
All other pages are accessible from the public domain except the dashboard.
Please excuse my ignorance. I am still new to the docker technology :)

**Comment by Emad-Marji** [comment]
Thanks again @marcelfolaron for your support. It seems to be a Synology issue.
I have deployed the same docker-compose file under a Linux server and it works fine with no issue.
