### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by marcelfolaron** [Leantime/leantime#182]

**Comment by marcelfolaron** [comment]
Looking for contributors to our translations. Just copy en-US.ini in resources/language/ and rename to your language to get started

**Comment by marcelfolaron** [comment]
5.8% Done

**Comment by ramsonline** [comment]
Hi, i am working on this, you should see some Progress [here](https://github.com/ramsonline/leantime)

I will create a PR when i am done / have no more time for this

**Comment by marcelfolaron** [comment]
Awesome, thank you!

**Comment by ramsonline** [comment]
btw. is there a way to test this with the new Language File ? I can not see a choose language Button on the webinterface.
I am running LT in a docker container using the compose-file.

**Comment by marcelfolaron** [comment]
Hey, 
somehow just now saw the comment here. You would have to update the configuration.php file in your container. If you are building the docker image with the newest version you can actually pass in environment variables.

**Comment by Skaldar** [comment]
I saw ramsonline created a PR and is not able to continue translating.
I [forked the project](https://github.com/Skaldar/leantime) and will complete the translation
