### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by marcelfolaron** [Leantime/leantime#183]
Looking for contributors to our translations. Just copy en-US.ini in resources/language/ and rename to your language to get started

**Comment by marcelfolaron** [comment]
3.5% Done

**Comment by EduFdezSoy** [comment]
Related: #195

**Comment by gonztirado** [comment]
Hey! I have already submitted a pull request with the full translation :) 

https://github.com/Leantime/leantime/pull/195

**Comment by marcelfolaron** [comment]
Included in 2.1 Beta 5
