### ISSUE TITLE
All Dropdown menus on dashboard pages

### ISSUE THREAD

**Issue by bluebrad** [Leantime/leantime#1843]
Self Hosted  v2.3.27
no mater what dashboard im on task cards or milestone cards drop downs are not working. 

Clicking on any of the menus do nothing happens
<img src="https://i.imgur.com/gA08Pyf.png">
https://imgur.com/gA08Pyf</img>

Apache/2.4.57
PHP: 8.0.26
MySQL: 10.2.44-MariaDB

**Comment by bluebrad** [comment]
Work around: if i open the task or milestone fully i can change them on the side and save. but from the any of the dashboards the drop down menus do not work. 
I have also tried PHP 8.1 with no luck

**Comment by marcelfolaron** [comment]
This should now be fixed in 2.4-beta

**Comment by bluebrad** [comment]
still not working and now worse

**Comment by marcelfolaron** [comment]
Now worse? What is happening? Still no reaction when you click on them? Do you have any extensions installed that might cause the issue? 

So far we have not seen or heard of this issue anywhere else.

**Comment by marcelfolaron** [comment]
Any errors in the dev console?

**Comment by bluebrad** [comment]
ya the meny drops down but when i select the field nothing happens


i also try to update to the beta and just get white.
im looking at when 2.4 is out ill start over with that version.
ive been updating since 1.4
so maybe there is a bug.

if you like you can DM me to take a look at my server. there is nothing
critical there. but has snapshot options.
if you find the bug we can repost it here.
-
***@***.***
