### ISSUE TITLE
[BUG] An error Occured on all Dialog Windows

### ISSUE THREAD

**Issue by acul009** [Leantime/leantime#1847]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
Every action that would open a dialog, like clicking on a ticket or wiki article just shows "an error occured"
The Dev-Tools shows a failed CORS request. I suggest this might have something todo with my forward auth.

To additionally secure Leantime, I not only use the OIDC login, I also have a forward auth configured via authentik.
I suspect a change in how you handle these dialogs together with my forward auth causes the issue.

**To Reproduce**

**Expected behavior**
I would love to keep my second layer of security, especially since the end user basically doesn't notice it.

**Leantime Version**
Newest version of the docker image as of 2003-08-27

**Server**
Docker image with traefik as reverse proxy and authentik as auth-provider

**PHP / MySQL Version**
Docker again

**Additional context**
As described above, I'm using a forward auth rule.

**Comment by marcelfolaron** [comment]
The dialogs are just asynchronous requests and executed the same way (xhr requests) they were executed before. Do you have the appURL set? 
Also please try clearing your cache. I noticed some odd behavior when old Javascript was in the cache.
