### ISSUE TITLE
[BUG] Dropdowns and dashboard menus not working

### ISSUE THREAD

**Issue by bluebrad** [Leantime/leantime#1848]
I attempted the upgrade from version 2.3.27 to beta 2.4, but the menu bug still persists. Additionally, when I loaded the update, I encountered a 500 error initially, but after refreshing, the update popup didn't appear but the site loaded. If you're interested, I can create a clone of this and provide you with test access for further investigation.
<img src="https://imgur.com/8c15byZ.png">
https://imgur.com/8c15byZ</img>
<img src="https://imgur.com/bCmSE1Z.png">
https://imgur.com/bCmSE1Z</img>

**Comment by marcelfolaron** [comment]
Which browser are you using? This seems odd as I have not encountered that
bug before.
Please also make sure to fully clear the cache after the update I noticed
that old JS files will break certain parts.

**Comment by bluebrad** [comment]
tried it on both firefox and chrome.
i mainly trust firefox.

**Comment by gloriafolaron** [comment]
Are you still experiencing this on the newest release?

**Comment by bluebrad** [comment]
ill take a look next weekend this week im away from the computer for production.

**Comment by marcelfolaron** [comment]
I think we finally found the answer to this. For anyone else running into a similar issue: 
Redhat/Centos will disallow patch/put requests in some configurations causing a 403 on most dropdown returns

Using `<limit>` in the htaccess and specifically allowing the methods fixed the issue.

**Comment by bluebrad** [comment]
Ok 👌  please post that to the documentation. Even better would be to have
the patch as a download.
