### ISSUE TITLE
Unapprove/undo approved timesheets and invoiced 

### ISSUE THREAD

**Issue by alexsynth** [Leantime/leantime#185]
Hi, i noticed when you approve a timesheet it cannot be undone. It would be very useful to edit this approval in order to undo it in case of a mistake

**Comment by marcelfolaron** [comment]
Thanks, good point. We'll try to get that in soon.

**Comment by tieu** [comment]
Hi everyone,

Just wanted to also add that if you delete a task that was billed on the timesheet. The timesheet loses the name of the task and just shows the hours.

Would be nice to also allow us to edit the task.

Thanks,

**Comment by marcelfolaron** [comment]
Thanks for reporting!
Will take a look.

**Comment by marcelfolaron** [comment]
Quick update: Working on this in addition to some more timesheet bug fixes. This will go out this weekend.

**Comment by marcelfolaron** [comment]
Included in 2.1 Beta 5
