### ISSUE TITLE
[BUG] LDAP - Cannot Login with 2.4-beta (without custom changes)

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1850]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X ] Self Hosted

**Describe the bug**
LDAP configuration problems.  Required manual modifications not documented in sample.env file supplied.  I could not login.  Errors in log file documented below

**To Reproduce**
When using Samba-ad-dc for LDAP login and LEAN_LDAP_LDAP_TYPE = 'OL' and LEAN_LDAP_KEYS documented in sample.env for same.

**Expected behavior**
Expected to be able to login via LDAP

**Leantime Version**
2.4-beta

**Server**
NGINX

**PHP / MySQL Version**
PHP 8.1 Mariadb 10.3

**Additional context**
Am unable to login through LDAP on a new installation of 2.4-beta on a new server.

I am using the same LDAP configuration that works normally on an identical server but using Leantime Version 2.3.25 on the working model.

Using NGINX / Ubuntu 22.04

I have verified that these required packages are installed:
libapache2-mod-php8.1 php8.1-bcmath php8.1-cli php8.1-common php8.1-curl php8.1-fpm php8.1-ldap php8.1-mbstring php8.1-mysql php8.1-opcache php8.1-pgsql php8.1-readline php8.1-xml php8.1-zip php-ldap php8.1-ldap

Problem: after entering my ldap username and password and pressing submit this url is presented:
https://projects.smvirtual.biz/auth/login along with 
This page isn’t workingprojects.smvirtual.biz is currently unable to handle this request.
HTTP ERROR 500

/var/log/nginx/leantime.access.log provides:
192.168.XX.XX - - [27/Aug/2023:13:28:40 -0700] "POST /auth/login HTTP/2.0" 500 0 "https://projects.smvirtual.biz/auth/login?redirect=%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"

No errors are rendered at:  
* /var/log/nginx/error.log
* /var/log/nginx/leantime.error.log

Errors are being rendered at:
* public_html/logs/error.log

[27-Aug-2023 13:32:40 America/Los_Angeles] ErrorException: Warning: Undefined property: stdClass::$phone in /SM_DATA/web_projects/public_html/app/domain/ldap/services/class.ldap.php:187
Stack trace:
#0 /SM_DATA/web_projects/public_html/app/domain/auth/services/class.auth.php(212): leantime\domain\services\ldap->getSingleUser()
#1 /SM_DATA/web_projects/public_html/app/domain/auth/controllers/class.login.php(79): leantime\domain\services\auth->login()
#2 /SM_DATA/web_projects/public_html/app/core/class.controller.php(91): leantime\domain\controllers\login->post()
#3 /SM_DATA/web_projects/public_html/app/core/class.controller.php(53): leantime\core\controller->executeActions()
#4 [internal function]: leantime\core\controller->__construct()
#5 /SM_DATA/web_projects/public_html/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs()
#6 /SM_DATA/web_projects/public_html/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build()
#7 /SM_DATA/web_projects/public_html/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve()
#8 /SM_DATA/web_projects/public_html/app/core/class.frontcontroller.php(151): Illuminate\Container\Container->make()
#9 /SM_DATA/web_projects/public_html/app/core/class.frontcontroller.php(73): leantime\core\frontcontroller::executeAction()
#10 /SM_DATA/web_projects/public_html/app/core/class.Bootloader.php(330): leantime\core\frontcontroller::dispatch()
#11 /SM_DATA/web_projects/public_html/app/core/class.Bootloader.php(154): leantime\core\Bootloader->handleRequest()
#12 /SM_DATA/web_projects/public_html/public/index.php(11): leantime\core\Bootloader->boot()
#13 {main}

# Tests performed
If I change **phonenumber** to **phone** in my .env file it skips to $jobTitle error (so apparently succeeds) 
[27-Aug-2023 13:40:10 America/Los_Angeles] ErrorException: Warning: Undefined property: stdClass::$jobTitle in /SM_DATA/web_projects/public_html/app/domain/ldap/services/class.ldap.php:187
I have no jobTitle provided in my LDAP_KEYS nor does the example.env file provided.

jobTitle translates to 'title' in my samba configs so I tried:
LEAN_LDAP_KEYS="{
        \"username\":\"cn\",
        \"groups\":\"memberOf\",
        \"email\":\"mail\",
        \"firstname\":\"givenName\",
        \"lastname\":\"sn\",
        \"phone\":\"telephoneNumber\", # newly changed during testing
        \"title\":\"jobTitle\" # fails during testing 
}"
Fails with same error on $jobTitle 

For the heck of it I changed LEAN_LDAP_LDAP_TYPE = 'OL' to LEAN_LDAP_LDAP_TYPE = 'AD' but then failed with 
 Unable to bind to server: Invalid credentials in /SM_DATA/web_projects/public_html/app/domain/ldap/services/class.ldap.php:123
 
So I changed it back to OL 

I then directly edited the class.ldap.php file and removed this portion of the string:
**$this->ldapKeys->jobTitle, $this->ldapKeys->jobLevel, $this->ldapKeys->department**

Result:
Warning: Undefined array key "memberOf" in /SM_DATA/web_projects/public_html/app/domain/ldap/services/class.ldap.php:205

So I changed my naming convention in LEAN_LDAP_KEYS from \"groups\":\"memberOf\", to \"groups\":\"memberof\",

Result: got past the memberOf error and now:
ErrorException: Warning: Undefined property: stdClass::$jobTitle in /SM_DATA/web_projects/public_html/app/domain/ldap/services/class.ldap.php:221

Redefined LEAN_LDAP_KEYS... as  \"jobTitle\":\"title\",

Result: 
Seems to get past jobTitle now but onto jobLevel.  I have no idea what jobLevel is since it doesn't appear in my ldap configs.
Warning: Undefined property: stdClass::$jobLevel in /SM_DATA/web_projects/public_html/app/domain/ldap/services/class.ldap.php:222

Since it worked for jobTitle I just copied it for jobLevel ie;
\"jobLevel\":\"level\"

Results: seems to get past jobLevel 
Undefined property: stdClass::$department in /SM_DATA/web_projects/public_html/app/domain/ldap/services/class.ldap.php:223

Since it worked for jobTitle and jobLevel I repeated for department (previously unused)
\"department\":\"department\"

Results: was able to get past login auth 500 errors.

My new LEAN_LDAP_KEYS settings which are working are as follows: 
**Leantime->Ldap attribute mapping**
LEAN_LDAP_KEYS="{
        \"username\":\"cn\",
        \"groups\":\"memberof\",
        \"email\":\"mail\",
        \"firstname\":\"givenName\",
        \"lastname\":\"sn\",
        \"phone\":\"telephoneNumber\",
        \"jobTitle\":\"title\",
        \"jobLevel\":\"level\",
        \"department\":\"department\"
}"

**Comment by marcelfolaron** [comment]
Fixed in 2.4-beta-4
