### ISSUE TITLE
[BUG] An Error Occurred popup in fresh installation

### ISSUE THREAD

**Issue by swratten** [Leantime/leantime#1854]
**What set up are you using**
* [x] Self Hosted

**Describe the bug**

When trying to reference an image in the editor by choosing source, I am met with an error modal.

The Network call in the browser inspector shows a 404 for:
http://myip/files/showAll&modalPopUp=true

**To Reproduce**
1. Go to Create To-Do
2. Click in description
3. Click on Source button
4. "An Error Occurred"

**Leantime Version**
2.4-beta

Using the docker container, with no reverse proxy.

**Comment by marcelfolaron** [comment]
Fixed in 2.4-beta-4
