### ISSUE TITLE
[BUG] Loop when deleting a To-Do

### ISSUE THREAD

**Issue by swratten** [Leantime/leantime#1855]
**What set up are you using**
* [x] Self Hosted

**Describe the bug**
When trying to delete a To-Do, I am presented with a slightly broken modal that states: "Are you sure you would like to delete this To-Do?" after pressing Yes, I am sent back to the same screen.

Url:
http://myip/tickets/showKanban#/tickets/delTicket/17

<img src="https://i.imgur.com/Bo9D0h9.png" alt="Alt text">

**Leantime Version**
2.4-beta - fresh installation

**Server**
Docker - no reverse proxy

**Comment by DerKamii** [comment]
Please see this, I've explained briefly how to resolve this: https://github.com/Leantime/leantime/issues/1867

**Comment by jiriks74** [comment]
Please close this issue. It's already thracked on #1867 and there is a PR  #1871 that addresses this. If you want a one liner for docker that fixes this until the PR is merged look at this comment: https://github.com/Leantime/leantime/issues/1867#issuecomment-1709889230
