### ISSUE TITLE
[BUG] Delete task button/popup

### ISSUE THREAD

**Issue by davidkobielski** [Leantime/leantime#1856]
**What set up are you using**
Self Hosted

**Describe the bug**
When I try to delete a task the application shows me an ugly popup (screenshot below) with delete task button. Unfortunately when I click the button it doesn't work.

![image](https://github.com/Leantime/leantime/assets/42317458/354db443-87e1-45c1-bf18-eab32279584b)

**To Reproduce**
1. Go to 'Project'
2. Click on 'Delete task'
3. See error

**Expected behavior**
Should redirect to delete task page and delete a task

**Leantime Version**
2.4 Beta

**Server**
Idk, I use leantime with docker

**PHP / MySQL Version**
The newest version from leantime docker
I think there is MySQL 8

**Comment by Polonco** [comment]
same here. I just installed leantime for the first time using docker to test it out but I can't delete tasks and I receive the same error.

**Comment by SenkaWolf** [comment]
I'm also getting the same issue.

I'm running 2.4-beta self hosted with PHP version 8.1.

https://i.senkawolf.com/01-09-23_18.44.23.png

**Comment by DerKamii** [comment]
@SenkaWolf @Polonco @davidkobielski 
Please see this, I've explained briefly how to resolve this: https://github.com/Leantime/leantime/issues/1867

**Comment by jiriks74** [comment]
Please close this issue. It's already thracked on #1867 and there is a PR  #1871 that addresses this. If you want a one liner for docker that fixes this until the PR is merged look at this comment: https://github.com/Leantime/leantime/issues/1867#issuecomment-1709889230

**Comment by sailhobie** [comment]
Similar issue when trying to delete a project blueprint item. I am able to delete it, but the formatting looks to be the same as when trying to delete a ToDo item. 

This is after applying the docker one-liner from issue 1867, which worked for ToDos

**Comment by jiriks74** [comment]
> Similar issue when trying to delete a project blueprint item and/or a Goal Board. I am able to delete it, but the formatting looks to be the same as when trying to delete a ToDo item.
> 
> This is after applying the docker one-liner from issue 1867, which worked for ToDos

I'll try to look into it but don't bet on me as I don't really know php

**Comment by DerKamii** [comment]
> > Similar issue when trying to delete a project blueprint item and/or a Goal Board. I am able to delete it, but the formatting looks to be the same as when trying to delete a ToDo item.
> > This is after applying the docker one-liner from issue 1867, which worked for ToDos
> 
> I'll try to look into it but don't bet on me as I don't really know php

It's basically the same thing.
File: /app/domain/canvas/controllers/class.delCanvas.php
Line 62: from "$this->tpl->display" to "$this->tpl->displayPartial"

**Comment by jiriks74** [comment]
> > > Similar issue when trying to delete a project blueprint item and/or a Goal Board. I am able to delete it, but the formatting looks to be the same as when trying to delete a ToDo item.
> > > This is after applying the docker one-liner from issue 1867, which worked for ToDos
> > 
> > 
> > I'll try to look into it but don't bet on me as I don't really know php
> 
> It's basically the same thing. File: /app/domain/canvas/controllers/class.delCanvas.php Line 62: from "$this->tpl->display" to "$this->tpl->displayPartial"

Yup, I fixed it while I was on train. It's already in the pull request. I was working on adding this to my one-liner and figuring out why my container was crashing after fixing this issue. The new one-liner is available at https://github.com/Leantime/leantime/issues/1867#issuecomment-1722230365
