### ISSUE TITLE
[BUG] 2FA verify page is blank

### ISSUE THREAD

**Issue by Daerendor** [Leantime/leantime#1858]
**What set up are you using**
Self Hosted

**Describe the bug**
I cannot auth using the main admin account, because of 2FA.

**To Reproduce**
1. Go to Leantime
2. Make sure you're logged out
3. Fill the form with your login and pass
4. Click "Login"
5. It may blank here. If it does, you have a first issue. Try to reload w/ cache clear
6. If you are lucky, you can see the 2FA prompt. Fill in your 2FA OTP.
7. It will blank.

**Expected behavior**
Works as intended: auth, 2FA, redirect to dashboard.

**Leantime Version**
2.4-beta

**Server**
Nginx Reverse Proxy

**PHP / MySQL Version**
Docker default (8.1)

**Comment by r1979** [comment]
I experience the same bug.

**Comment by digitalconstantin** [comment]
I am also experiencing the same bug.

**Comment by phires** [comment]
I had to remove the 2FA token from the DB to be able to login again; having the same issue.

**Comment by digitalconstantin** [comment]
> You need to connect to your Database server, e.g. using mysql command line tools. There is a table `zp_user` with two relevant rows, `twoFAEnabled` and `twoFASecret`.
> 
> I've disabled 2FA for my user using this command: `UPDATE zp_user SET twoFAEnabled = 0, twoFASecret = '' WHERE username = '<USERNAME>';`
> 
> When omitting the WHERE-Clause you disable 2FA for ALL users - depending on if thats what you want ;)

Yep, that worked flawlessly! Thank you so much.

**Comment by charly-palencia** [comment]
Experience the same issue :( any solution so far? (other than remove the 2fa)

**Comment by michael-schramm** [comment]
I had the same issue and had to delete the corresponding entries in the database.
:-(

**Comment by marcelfolaron** [comment]
2.4-beta-2 has a fix in it
