### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 2forB** [Leantime/leantime#1863]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ x] Self Hosted

**Describe the bug**
I created a template project with all wikis and wanted to duplicate it, but unfortunately, the wikis didn't transfer. 

**To Reproduce**
1. Go to 'Project Settings'
2. Click on ' Duplicate Project'
3. Click on ' Duplicate'
4. Go to 'copied Project'
5. Click on ' Docs'

**Expected behavior**
The same Wiki's as in the original project

**Leantime Version**
v2.3.27

**Server**
Apache

**PHP / MySQL Version**
mysql:8.0v

**Additional context**

**Comment by marcelfolaron** [comment]
2.4-beta-2 has a fix in it
