### ISSUE TITLE
[BUG] Documentation not matching current repo; setup stuck on creating database.

### ISSUE THREAD

**Issue by davesierra** [Leantime/leantime#1864]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
In reference to the docs with setting up with docker: https://github.com/Leantime/docker-leantime

I cannot get it up and running. A few points running `docker compose up`:

- Complains that LEAN_PORT is empty in the [docker-compose file](https://github.com/Leantime/docker-leantime/blob/master/docker-compose.yml), this is not set in the [sample.env](https://github.com/Leantime/docker-leantime/blob/master/sample.env) file, nor is it mentioned anywhere in the docs. Suggest either adding it or just making a static default port.
- docker-compose might be docker compose (good to make a note of this somewhere in case the user is unaware)
- After running the command, it's stuck creating the database, unknown why it gets stuck. Here is a screenshot:
![Screenshot 2023-09-02 122921](https://github.com/Leantime/leantime/assets/867047/bd0f8441-1bee-4a6d-88e4-5dfc0ef3da49)

**To Reproduce**
Following the same steps as outlined here: https://docs.leantime.io/#/installation/docker

Suggest that the docker hub page just links to that installation to be consistent: https://hub.docker.com/r/leantime/leantime

**Expected behavior**
I should be able to get a minimal working product after following the setup.

**Leantime Version**
[Which Leantime version are you using](leantime:latest)

**Server**
Ubuntu 20.04

**PHP / MySQL Version**
See docker-compose

**Additional context**

**Comment by marcelfolaron** [comment]
Port was added to composer file
