### ISSUE TITLE
[BUG] Leantime logo URL is base url instead of /dist/images/logo.jpg

### ISSUE THREAD

**Issue by jiriks74** [Leantime/leantime#1866]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
Created a new install and I'm missing the logo in the top left corner. If I manually modify
`<a href="https://leantime.stefka.eu" style="background-image: url(https://leantime.example.com">&nbsp;</a>`
to
`<a href="https://leantime.stefka.eu" style="background-image: url(https://leantime.example.com/dist/images/logo.jpg">&nbsp;</a>`
it works.

**To Reproduce**
1. Setup a new instance of Leantime
2. See the missing logo

**Expected behavior**
A logo being shown

**Leantime Version**
2.4-beta (tagged as `latest` on Dockerhub)

**Server**
Docker

**PHP / MySQL Version**
Docker

**Comment by jiriks74** [comment]
Also uploading new logo doesn't work either

**Comment by jiriks74** [comment]
Ok, since recreating the container and changing the volumes from `./volumename` to `volumename` it works for whatever reason.

**Comment by marcelfolaron** [comment]
2.4-beta-2 has a fix in it

**Comment by almereyda** [comment]
I'm seeing this again on 2.4.7
