### ISSUE TITLE
[BUG] Unable to remove To-Dos due to some glitch

### ISSUE THREAD

**Issue by jiriks74** [Leantime/leantime#1867]
**What set up are you using**
* [x] Self Hosted

**Describe the bug**
I get some graphical glitch when deleting a To-Do which also prevents me from deleting the To-Do

<details>
<summary>Screenshot</summary>

![image](https://github.com/Leantime/leantime/assets/54378412/65ff465e-bfbe-45f8-b0e5-baf7cd010078)

</details>

**To Reproduce**
1. Create a new docker install
2. Create the first account
3. Create the first project
4. Skip the introduction
5. Go to To-Dos
6. Click the 3 dot menu on the default To-Do and click `Delete To-Do`
7. See the glitch

**Expected behavior**
No glitch and the To-Do removed

**Leantime Version**
2.4-beta (tagged as latest on Dockerhub)

**Server**
Docker

**PHP / MySQL Version**
MySQL:8.0

**Comment by DerKamii** [comment]
So the displaying glitch wasn't super hard to fix (I think):
in the class.delTicket.php there are 2 lines with "$this->tpl->display('tickets.delTicket');"
You need to rewrite them to "$this->tpl->displayPartial('tickets.delTicket');".

Still strying to figure out why deleting still doesn't work.

**Comment by jiriks74** [comment]
> 

Should I try to modify my container and see if it works?

**Comment by DerKamii** [comment]
I don't see any harm in it until it's fixed officially. Docker is just a wrapper around the application for "easier" setup.

**Comment by jiriks74** [comment]
> I don't see any harm in it until it's fixed officially. Docker is just a wrapper around the application for "easier" setup.

I've tried the fix and it works flawlessly.
I've created a pull request since I couldn't find one by you (you got the credit, of course ;) )

I'll just modify the information about the fix for anyone trying to fix it before it gets merged:

```bash
docker exec -it <container_id> sh -c "sed -i \"s/\$this->tpl->display('tickets.delTicket');/\$this->tpl->displayPartial('tickets.delTicket');/g\" /var/www/html/app/domain/tickets/controllers/class.delTicket.php && sed -i 's@<form method=\"post\">@<form method=\"post\" action=\"<?=BASE_URL ?>/tickets/delTicket/<?php echo \$ticket->id ?>\">@g' /var/www/html/app/domain/tickets/templates/delTicket.tpl.php"
```

**Comment by DerKamii** [comment]
Thanks! I've litterally just fixed that yesterday on the fly since it was holding me back on using the software lol.
Appreciate the PR and the mention!

**Comment by jiriks74** [comment]
> Thanks! I've litterally just fixed that yesterday on the fly since it was holding me back on using the software lol. Appreciate the PR and the mention!

Thank you! I need to use this as well and I don't really know PHP so figuring this out would take me ages.

Also, I've set up Leantime more than a year ago and I remember this problem, or a similar one, being present (the graphical glitch was the same). But I didn't really use this, as it was setup for someone else, so I didn't really pay attention to bugs.

I hope that the one liner will be of use to someone as it took some time messing around with `sed` which I don't understand and it's syntax is painful. Also, if you use docker-compose it's useful because you can then easily fix it after doing `docker-compose down` and/or `docker-compose up -d`

**Comment by jiriks74** [comment]
New one-liner:
```bash
docker exec -it <container_id> sh -c "sed -i \"s/\$this->tpl->display('tickets.delTicket');/\$this->tpl->displayPartial('tickets.delTicket');/g\" /var/www/html/app/domain/tickets/controllers/class.delTicket.php && sed -i 's@<form method=\"post\">@<form method=\"post\" action=\"<?=BASE_URL ?>/tickets/delTicket/<?php echo \$ticket->id ?>\">@g' /var/www/html/app/domain/tickets/templates/delTicket.tpl.php && sed -i \"s/\$this->tpl->display(static::CANVAS_NAME . 'canvas.delCanvas');/\$this->tpl->displayPartial(static::CANVAS_NAME . 'canvas.delCanvas');;/g\" /var/www/html/app/domain/canvas/controllers/class.delCanvas.php"
```

It fixec Canvas deletion as well.
