### ISSUE TITLE
[FEATURE] Improve code readability in dark mode

### ISSUE THREAD

**Issue by CodeShakingSheep** [Leantime/leantime#1872]
**Is your feature request related to a problem? Please describe.**
When copying lines from log files to a ticket comment the readability is really bad when using Leantime in dark mode. See screenshot
![image](https://github.com/Leantime/leantime/assets/19874562/4e3a3ab9-b4a2-4412-bd19-fb161e34734f)

**Describe the solution you'd like**
I would like the font color to be brighter in dark mode (e.g. white or light gray) so that the contrast between the dark background and the font is higher, in order to improve readability.

**Comment by marcelfolaron** [comment]
Where is this log coming from? How are you inserting it. I see there is some sort of container around it?

**Comment by CodeShakingSheep** [comment]
> Where is this log coming from? How are you inserting it. I see there is some sort of container around it?

The log just comes from HTML code. Specifically, from [here](https://paste.yunohost.org/raw/secetebaga). You can just copy any lines and paste them in a comment when using Leantime in dark mode.

**Comment by marcelfolaron** [comment]
Fixed in 2.4-beta-4
