### ISSUE TITLE
[FEATURE] Add markdown support in comments

### ISSUE THREAD

**Issue by CodeShakingSheep** [Leantime/leantime#1874]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use markdown syntax in ticket comments.

**Describe the solution you'd like**
With markdown support I would expect this to be formatted as code:
![image](https://github.com/Leantime/leantime/assets/19874562/ed02b2bf-b988-4b85-8e6f-7e08705e8e84)

**Comment by marcelfolaron** [comment]
Basic markdown support is now in 2.4.1
