### ISSUE TITLE
[BUG] companysettings.telemetry.active parameter ignored

### ISSUE THREAD

**Issue by yuggmatt** [Leantime/leantime#1876]
**What set up are you using**
* [X] Self Hosted

**Describe the bug**
Even when telemetry is deactivated in company settings, Leantime stills try to reach out for telemetry.leantime.io

**To Reproduce**
1. Deactivate telemetry in company settings
2. Log out
3. Log In
4. Browse your projects and pages. Even though the telemetry box is unchecked in company settings, the app stills tries to access telemetry.leantime.io

**Expected behavior**
When telemetry setting is disabled, Leantime should not try to access the telemetry URL whatsoever.

**Leantime Version**
Latest official docker image ([2.4-beta])

**Additional context**
I am wondering why the parameter from the DB seems to be ignored, and replaced and always replaced with a true value, see lines 222 and 223 in app/Domain/Reports/Services/Reports.php

```
            $allowTelemetry = (bool) $this->settings->getSetting("companysettings.telemetry.active");
            $allowTelemetry = true;
```

Removing the second line seems to fix it.

**Comment by yuggmatt** [comment]
Just a bit of context about why I find this annoying. I run leantime in a Docker container, besides several other containerized applications, behind a traefik reverse proxy. Leantime runs on a docker network on which it can communicate with the reverse proxy, but I do not offer IP masquerading for this network in order to prevent my container from "going out" on the internet, for security reasons. Only connections initiated through the reverse proxy can get answers from my containers. Hence, the data collection from the telemetry cannot pass through as this is initiated from the leantime container.
When telemetry is activated in leantime, the DNS requests to resolve telemetry.leantime.io time out after 5 seconds. There are two of them, and this more or less, induces a 10s lag time every time a new page is loaded, which results in a very sluggish user experience. This makes leantime unusable.

The config parameter that I set to deactivate telemetry should not be bypassed as it is the case right now (as documented in my first post).

**Comment by marcelfolaron** [comment]
Hi, thanks for pointing that out. This must have been a left over from previous testing. You are right this is not supposed to just override the setting. Fix coming in.

**Comment by tunloop** [comment]
Just an FYI to anyone finding this page.

I am currently using v3.5.12 and the company settings page in the UI has no such setting for disabling telemetry.
(Just in case others came looking and wondering where that checkbox is)
