### ISSUE TITLE
[BUG] delete item from To-Dos

### ISSUE THREAD

**Issue by tsifra** [Leantime/leantime#1877]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
When i try to delete item on to-dos list (/tickets/showKanban) i have popup dialog that brakes layout. If i push "yes, delete" button i just have page reload. No data deleted.

**To Reproduce**
1. Go to '/tickets/showKanban'
2. Click on "Getting Started with Leantime" dot-menu and chose delete option
3. See error

**Expected behavior**
Expected to be clear poup dialog without main page menu over it.

**Leantime Version**
2.4 beta

**Server**
nginx

**PHP / MySQL Version**
php 8.1

**Comment by sailhobie** [comment]
I am also experiencing this on self hosted 2.4 Beta
