### ISSUE TITLE
[BUG] Cannot Select Project Avatar

### ISSUE THREAD

**Issue by otinex** [Leantime/leantime#1878]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
Cannot Change Project Avatar as the Save button cannot be clicked
![image](https://github.com/Leantime/leantime/assets/28898876/79e0835c-6be9-4d29-b9cf-d4aa17e76807)

**To Reproduce**
1. Go to Project Settings
2. Click on Select File
3. Scroll down to the Save Button
4. Button cannot be selected or clicked

**Expected behavior**
After selecting the file for the avatar and changing the scale I should be able to click on Save and accept the new Project Avatar

**Leantime Version**
2.4-beta

**Server**
nginx

**PHP / MySQL Version**
docker

**Additional context**
seems like some CSS bug

**Comment by arminarmin** [comment]
Can confirm, faced exatly the same issue.
