### ISSUE TITLE
Syntax error in PHP file "showCanvas.tpl.php"

### ISSUE THREAD

**Issue by jul-den** [Leantime/leantime#1880]
https://github.com/Leantime/leantime/blob/ac127ca2ac53f616e67ba1843e1162310242dd4e/app/Domain/Sbcanvas/Templates/showCanvas.tpl.php#L48C70-L48C70

Next Illuminate\View\ViewException: syntax error, unexpected token "=", expecting "]" (View: leantime/app/views/templates/layouts/app.blade.php) in leantime/app/domain/sbcanvas/templates/showCanvas.tpl.php:46

Line 48:
            `<?php $varsToPass = array_merge($__data, ['statusLabels' `**=**` $stakeholderStatusLabels]) ?>`

FIX:
            `<?php $varsToPass = array_merge($__data, ['statusLabels' `**=>**` $stakeholderStatusLabels]) ?>`

**Comment by marcelfolaron** [comment]
2.4-beta-2 has a fix in it
