### ISSUE TITLE
[BUG] todo limit and change name - 2.4 beta

### ISSUE THREAD

**Issue by SZEINER** [Leantime/leantime#1886]
When we add new position for todo  the system cant add and change name for last visible todo.

**Comment by SZEINER** [comment]
![obrazek](https://github.com/Leantime/leantime/assets/77299927/beb074f8-e52f-4ff6-8b0f-80e0c1436090)

**Comment by marcelfolaron** [comment]
2.4-beta-2 has a fix in it
