### ISSUE TITLE
[BUG] invite users - problem with link

### ISSUE THREAD

**Issue by SZEINER** [Leantime/leantime#1894]
When update userr credential and change to invite for copy link, there problem with link generation.This problem is only with edit users. Version 2.4 beta2

url: https://domain.com/auth/userInvite/

![obrazek](https://github.com/Leantime/leantime/assets/77299927/317c2113-0ba3-4243-9144-503fab491cde)

**Comment by jiriks74** [comment]
This got fixed but IDK where

**Comment by encg** [comment]
Not seeing this in v2.4.1. I see the entire invite URL.

**Comment by jiriks74** [comment]
Could this be closed then?
