### ISSUE TITLE
[BUG] OIDC does not work anymore on 2.4-beta-3

### ISSUE THREAD

**Issue by fame-odoo** [Leantime/leantime#1896]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
I have set the OIDC log in correctly before 2.4-beta-3, worked perfectly wor 2.4-beta

**To Reproduce**
1. Set the OIDC correctly in the .env
2. use 2.4-beta works well
3. Switch to 2.4-beta3, cannot log in any more, it will stuck on https://leantime//oidc/login

**Expected behavior**
use the same configuration should work, and now I cannot log in anymore

**Leantime Version**
2.4-beta-3

**Server**
Nginx reverse proxy + docker

**PHP / MySQL Version**
docker mysql 8

**Additional context**

**Comment by fame-odoo** [comment]
Delete all docker volume and reinstalled everything, after logged in always get an error occurred alert, cannot use it at all. Docker compose install.

Docker 2.4-beta-3 is so broken

**Comment by fame-odoo** [comment]
Please refer to https://discord.com/channels/990001288026677318/1154612999475179580/1154939140174004254 for the details

**Comment by marcelfolaron** [comment]
Fixed in 2.4-beta-4

**Comment by fame-odoo** [comment]
@marcelfolaron 
<img width="1098" alt="image" src="https://github.com/Leantime/leantime/assets/107050396/9f5c6c09-d522-4dd6-9c0c-54a904031114">

I do not think this is fixed. I tried both ways of the installation, docker cannot event log in, always An error occured, and normal install will simply has this error

**Comment by fame-odoo** [comment]
Also, for 2.3.27, OIDC scopes can be defined as LEAN_OIDC_SCOPES = email givenname sn, but in the 2.4-beta-4, if I keep this, it will tell me unable to parse it
