### ISSUE TITLE
[BUG] Clean install 2.4-beta-3

### ISSUE THREAD

**Issue by SZEINER** [Leantime/leantime#1897]
**What set up are you using**
* [ ] Self Hosted

**Describe the bug**
When set /install have problem with SQL database. But database credentials is set.

**To Reproduce**
1. Go to install script 
2. Click on enter
3. See error: No database connection, check your database credentials in your configuration file. Checking common issues: 

**Leantime Version**
2.4-beta3

**Server**
Apache

**PHP / MySQL Version**
PHP 8.1

![obrazek](https://github.com/Leantime/leantime/assets/77299927/e32a1e21-1eaa-459e-b229-28f35773bf33)

**Comment by marcelfolaron** [comment]
This should be fixed in 2.4-beta-4
