### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chlarsen** [Leantime/leantime#1898]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
Trying to send a test email using current configuration from the command line, and I get
```
In Container.php line 891:
Target class [Leantime\Core\language] does not exist.  
In Container.php line 889:
Class "Leantime\Core\language" does not exist  
```
**To Reproduce**
1. Run FreeBSD 13.2 p3
2. PHP 8.1 in jail A with Leantime 2.4-beta3 and Nginx 1.24 as static asset server behind reverse proxy in jail B, privilege separation for PHP-FPM
3. Nginx 1.24 as reverse proxy in jail B (irrelevant for this error)
4. MariaDB 10.6 in jail C, connection works, tested using mariadb client
5. Database migration worked, using the CLI
6. Sending mail using the PHP Mailer failed. Normally, "Language" errors are related to no or an incorrect PHP version, but 8.1 ist should be.

**Expected behavior**
Mail should be sent and received.

**Leantime Version**
Leantime 2.4-beta3

**Server**
Nginx 1.24 with FastCGI for PHP-FPM, HTTP2, SSL, caching and the works as reverse proxy; Nginx 1.24 as static asset server in PHP jail

**PHP / MySQL Version**
PHP 8.1.23
MariaDB 10.6

**Additional context**
Also: The Nginx setup as described in the example files with Leantime running from https://leantime.my.domain/ just do not work. A rework and simplification may be in order, as PHP-FPM with FastCGI and Nginx is standard and usually E-A-S-Y and works with all my other applications. However, first the application server issue :-).

**Comment by marcelfolaron** [comment]
Fixed in 2.4-beta-4
