### ISSUE TITLE
[BUG] Group by in To-Dos cannot be turned off

### ISSUE THREAD

**Issue by jiriks74** [Leantime/leantime#1899]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [x] Self Hosted

**Describe the bug**
When I open To-Dos for any project the To-Dos get grouped according to their status. I don't want it as I don't want to have the To-Dos grouped twice into the same categories.
When I turn it off it still turns on after going to another page and then going to To-Dos too. This behavior cannot be changed in Project settings, Personal settings or Organization settings

**To Reproduce**
1. Go to To-Dos
2. Create one or more To-Dos
3. See the groups
4. Set `Group By` to `No Grouping`
5. Go somewhere else and then go to To-Dos again
6. See that it groups again

**Expected behavior**
To-Dos not grouping when I tell it not to

**Leantime Version**
v2.4-beta-3

**Server**
Docker

**PHP / MySQL Version**
Docker

**Comment by marcelfolaron** [comment]
Fixed in 2.4-beta-4
