### ISSUE TITLE
A task should be the same as a subtask.

### ISSUE THREAD

**Issue by fire** [Leantime/leantime#190]
A task should be the same as as subtask. A task's dependencies should not be different. Have some way to make a hierarchy of tasks.

**Comment by marcelfolaron** [comment]
So is the goal to see subtasks in the top level views (table + kanban) and allow dependencies on a Task/Story/Bug level?

**Comment by fire** [comment]
I want to remove the idea of sub anything.

There should only be tasks. Each task may have a dependency of a number of tasks or be a dependent.

**Comment by fire** [comment]
You can think of other link types.

https://www.jetbrains.com/help/youtrack/standalone/Link-Issues.html

```
Depend | Directed
Duplicate | Aggregation
Relates | Undirected
Subtask | Aggregation
```

https://confluence.atlassian.com/adminjiraserver073/configuring-issue-linking-861253998.html

```    
relates to / relates to
duplicates / is duplicated by
blocks / is blocked by
clones / is cloned by
```

**Comment by fire** [comment]
By having a dag structure, you can do stuff like pretty graphs.

![image](https://user-images.githubusercontent.com/32321/78183251-6fb10580-741c-11ea-8127-728900aaca12.png)

https://stackoverflow.com/questions/40668022/plott-a-dag-in-a-dot-layout-using-ggnet

**Comment by sangdrax8** [comment]
I believe this is basically what I was looking for as well.  I would like to be able to link tasks to others, so I can keep track of dependencies.  I don't really need a "sub-task" but I do need any task that is blocked by another, to be able to show that linkage.

**Comment by dekiesel** [comment]
It would be great if we could ad a "depends on" to tasks.

**Comment by Silvarion** [comment]
Any news about this feature? It would be highly appreciated

**Comment by axelrindle** [comment]
+1

**Comment by prakas24** [comment]
Any update on this? Can we assign a subtask to others?

**Comment by clemrdh** [comment]
Any Update on this ?
This feature would be really usefull and easy to implement !
