### ISSUE TITLE
[BUG] Current date marker in timeline view is in a wrong place

### ISSUE THREAD

**Issue by tsifra** [Leantime/leantime#1902]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
Current date marker in timeline view is in a wrong place. Today is 24 sep. but current date marker is shown near 20 oct.

**To Reproduce**
1. Go to 'Tasks' page
2. Click on 'Timeline' tab
3. Switch to 'Week' period
4. Check the view and see where current date marker with blue line is. In my case it's somewhere in the end of october instead of september (current date).

**Expected behavior**
Expect current date marker in today's zone on timeline.

**Leantime Version**
2.4-beta-3

**Server**
nginx

**PHP / MySQL Version**
php 8.1

**Comment by marcelfolaron** [comment]
Can you check if this is still an issue in 2.4-beta-4 ?

**Comment by tsifra** [comment]
Yes i can confirm, bug is still there. "Forget about this site" also does nothing to this.

**Comment by tsifra** [comment]
> Can you check if this is still an issue in 2.4-beta-4 ?

Yes i can confirm, bug is still there. "Forget about this site" also does nothing to this.
PS: hvae just updated to beta4

**Comment by tsifra** [comment]
Why did you close the issue? Do i need to recreate report?

**Comment by marcelfolaron** [comment]
No, that was by accident. So far I have not been able to reproduce the issue. I assume your server has the right date/timezone?

**Comment by tsifra** [comment]
I believe there's nothing wrong with timezone on server and on client. Problem can be seen only in "week" representation. If i choose day and month marker is exactly where expected. I've checked it in three different browsers (latest ver.): librewolf, palemoon, firefox.

One of task that starts at 25.09.2023 and end at 01.10.2023 has following attributes
<rect x="660" y="75" width="140" height="40" rx="5" ry="5" fill="#8D99A6" class="bar"><animate attributeName="width" from="0" to="140" dur="0.4s" begin="0.1s" calcMode="spline" values="0;140" keyTimes="0; 1" keySplines="0 0 .58 1"></animate></rect>

And current day circle has following
<circle cx="1101" cy="57" r="10" class="today-highlight-label-bg"></circle>
<text x="1101" y="61" class="today-highlight-label">25</text>

You can see current day marker is on the right of task.

**Comment by bram-smeets** [comment]
Pitching in to say I also have this issue in week view and a similar issue in month view.
Removed the database and went down to 2.3.27, issue persisted.
Server is set to UTC.

In week view the date marker is one month in the future, while the tasks/milestones are placed correctly.
In the month view the date marker is placed correctly but my tasks are offset by one month into the past.

**Comment by marcelfolaron** [comment]
Thank you, that information helped.

**Comment by tsifra** [comment]
It looks like in 2.4-beta-5 issue was solved. At least i can't reproduce it now

**Comment by marcelfolaron** [comment]
just released 2.4-beta-6 which should fix this
