### ISSUE TITLE
[BUG] Can not add a comment in to-do window opened from project overview

### ISSUE THREAD

**Issue by ralfsiebert65** [Leantime/leantime#1905]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
When I open a task from project overview, I can not add a comment. The inline editor does not appear.

**To Reproduce**
1. Go to project overview
2. Open a task
3. click to "add a comment"

**Expected behavior**
The inline editor should open to add a comment

**Leantime Version**
2.3.27
**Server**
Apache

**PHP / MySQL Version**
PHP 8.1
MariaDB 10.3

**Comment by marcelfolaron** [comment]
Fixed in 2.4-beta-4
