### ISSUE TITLE
[FEATURE] Allow user to disable the default log in form

### ISSUE THREAD

**Issue by MFYDev** [Leantime/leantime#1908]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I install Leantime, set OIDC log in, and log in with the user which has the same email address as admin, so that they can be linked, and in the future I can use OIDC to directly log in. However, after this the default log in form won't let me log in anymore, it becomes useless, I will suggest give user an option to disable the default log in form.

**Additional context**

**Comment by eric-hansen** [comment]
@marcelfolaron If you want this done I can take this.  I was thinking about this myself once I got OIDC set up.  IMO it should be a `.env` variable.

**Comment by marcelfolaron** [comment]
Thank you, yes I agree this would be appropriate for the env file. We have
a main config manager under core/DefaultConfig, so it needs to be added in
there as well.
