### ISSUE TITLE
[BUG] "HTTP ERROR 500" on My Timesheets /timesheets/showMy (2.4-beta-4)

### ISSUE THREAD

**Issue by steveoriol** [Leantime/leantime#1909]
**What set up are you using**
* [ ] Cloud Hosted Version
* [ x] Self Hosted

**Describe the bug**
"HTTP ERROR 500" when you click on "My Timesheets" (/timesheets/showMy)

**To Reproduce**
1. Go to 'Home' (/dashboard/home)
2. Click on "My Timesheets" (on top right icons)

**Leantime Version**
2.4-beta-4

**Server & PHP / MySQL Version**
docker compose version : https://github.com/Leantime/docker-leantime

**Comment by marcelfolaron** [comment]
just released 2.4-beta-6 which should fix this
