### ISSUE TITLE
[BUG] 2FA login fails with blank page

### ISSUE THREAD

**Issue by schories** [Leantime/leantime#1912]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x ] Self Hosted with official "leantime/leantime:latest" image, currently on DIGEST:sha256:3b377ec9540fb66b0c353222a9230efeca5aa12195e3848793931c84d1775fd5
* https://hub.docker.com/layers/leantime/leantime/latest/images/sha256-3b377ec9540fb66b0c353222a9230efeca5aa12195e3848793931c84d1775fd5?context=explore

**Describe the bug**
2FA enabled. After entering correct username and password usually the 2FA would appear. However, https://www.domain.com/twoFA/verify results in a blank page now.

**To Reproduce**
1. Go to login page
2. enter username and password of 2FA enabled user
3. Click on button to sign in - instead of 2FA a blank page appears

**Expected behavior**
2FA should work again, no blank page.

**Leantime Version**
 "leantime/leantime:latest" image, currently on DIGEST:sha256:3b377ec9540fb66b0c353222a9230efeca5aa12195e3848793931c84d1775fd5

**Server**
official "leantime/leantime:latest" image

**PHP / MySQL Version**
official "leantime/leantime:latest" image

**Comment by schories** [comment]
I've seen https://github.com/Leantime/leantime/pull/1911/commits has been integrated (PR). Once docker image is updated, I will reply with feedback. Thank you once again!

**Comment by schories** [comment]
Sadly the issue is still present with: official "leantime/leantime:latest" image DIGEST:sha256:96ff70a3a42551bfa93170055991ce3ca76354a95cce2a53cb0dbcda3e175376

**Comment by schories** [comment]
I can't find php log files, means even when in the running container. I'd like to help - but don't know how in this case?!

Thank you! :)

**Comment by marcelfolaron** [comment]
just released 2.4-beta-6 which should fix this

**Comment by schories** [comment]
Yes,  [2.4-beta-6](https://hub.docker.com/layers/leantime/leantime/2.4-beta-6/images/sha256-e2e6549ee5ce994574cc32d6741ebb880d4bd704646d19ef849b2a2b05bbfd34?context=explore) also fixes the 2FA / MFA issue.

I apologize for the late reply.

Thank you!
