### ISSUE TITLE
[BUG] When switching project while viewing boards a new board is created on second project (if it didn't exist)

### ISSUE THREAD

**Issue by jiriks74** [Leantime/leantime#1913]
**What set up are you using**
* [x] Self Hosted

**Describe the bug**
When switching from one project to another while viewing boards (eg. business model board) the board gets created if ti doesn't exist in the project you're switching to.

**To Reproduce**
1. Create 2 projects
2. Go to the first project
3. Create a new board under blueprints
4. Leave the board open and switch to the second project
5. A board, of the type you left open while on project one, got created on project 

**Expected behavior**
The view shows `Blueprints` view instead of creating a new blueprint

**Leantime Version**
 v2.4-beta-4

**Server**
Docker

**PHP / MySQL Version**
Docker

**Comment by marcelfolaron** [comment]
As a matter of fact we always create one default board when you enter one of the blueprint boards. So even within one project clicking on one of the blueprints will create one default board called "board". This is to avoid having an additional click for a a 0 state screen. Or are you saying that it actually duplicates the board?

**Comment by jiriks74** [comment]
I understand that boards get created once I click on blueprints. For me, this is expected. 
It also doesn't duplicate them but it creates board that I don't want to use if I had one open on one project and go to another.


Let's say I have project *a*. On project *a* I'll create a board for *SWAT Analysis*.
Then I'll create project *b*. On project *b I don't want/need to use *SWAT Analysis* so I don't create it.

Then I go to project *a*'s *SWAT Analysis* board and I add something (or just look - opening the board is what's relevant).
Then I want to do something on project *b* so I select it in the top left menu and bam - a board for *SWAT Analysis* got created on project *b* (because I didn't go out of the *SWAT Analysis* board on project *a* before switching to project *b*).

As I don't want to have *SWAT Analysis* on project *b* I now have to go and delete it.

**Comment by marcelfolaron** [comment]
Ah, I understand. Thanks for clarifying.

**Comment by marcelfolaron** [comment]
Behavior was updated.
