### ISSUE TITLE
![BUG]! Beta images are tagged as latest on Dockerhub

### ISSUE THREAD

**Issue by jiriks74** [Leantime/leantime#1919]
I think that since it's a beta release people shouldn't be updated to it without their knowledge when they update their containers.

I think that using `latest` for stable releases and `beta` for beta releases would be better.

**Comment by jiriks74** [comment]
This caused #1921 when trying to recreate the container. It could prevent people with systems in production from receiving a bad update like the one in #1921

**Comment by marcelfolaron** [comment]
Latest is now 2.4 stable.

**Comment by jiriks74** [comment]
> Latest is now 2.4 stable.

Have you considered vmhaving a beta channel as well? People then could choose stable (`latest`) or thr latest beta (`beta`). This way people won't have to search the tags to figure out what the latest beta tag is if they want to use it.
