### ISSUE TITLE
![BUG]! 2.4-beta-5 image has no connection to the database

### ISSUE THREAD

**Issue by jiriks74** [Leantime/leantime#1921]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [x] Self Hosted

**Describe the bug**
When updating from `2.4-beta-4` docker image to `2.4-beta-4` I get `No database connection, check your database credentials in your configuration file.`

The credentials are correct since changing the used image from `latest` to `2.4-beta-4` solves the issue.

**To Reproduce**
1. Update to/use v2.4-beta-5
2. Connect to the server
3. See the error

**Expected behavior**
Leantime loading up successfully.

**Leantime Version**
v2.4-beta-5

**Server**
Docker

**PHP / MySQL Version**
Docker

**Comment by jiriks74** [comment]
I think that this is a critical bug that needs to be fixed asap as it's tagged as latest on Dockerhub. Upgrading/installing will cause problems for users.

**Comment by jiriks74** [comment]
Related to 147d79f

**Comment by marcelfolaron** [comment]
Thanks. I am taking a look

**Comment by jiriks74** [comment]
Ok, looks like it wasn't https://github.com/Leantime/leantime/commit/147d79ff91a2f9ba969b3b150df1bbdabda6e405

I'm currently modifying my server install so that I can easily revert commits and find the broken one

**Comment by marcelfolaron** [comment]
I reverted latest back to 2.4-beta-4. Image is building and will be done in 30 min 
Investigating the config issue.

**Comment by jiriks74** [comment]
Looks like an issue with [Environment.php](https://github.com/Leantime/leantime/commit/147d79ff91a2f9ba969b3b150df1bbdabda6e405#diff-805d24b84e1bbb8adaa149706a6f08b5032e44aca8e0dd8147c2235db87918b4L120) There were massive deletions without adding variables back.

To get the line I highlighted you'll have to manually load the difff as it's too large.

**Comment by marcelfolaron** [comment]
No, the deletions were on purpose. We have a defaultConfig that is the "master" of our config variables. The double definition in the environment class was actually causing issues.

**Comment by marcelfolaron** [comment]
I checked and it seems the config vars make it to the Db class but for some reason PDO can't connect to mysql

**Comment by marcelfolaron** [comment]
I found where it's failing, but not why... 
All configs make it in except the mysql host. The Db class gets localhost when it should by mysql_leantime

**Comment by jiriks74** [comment]
I looked into loading the variables from environment but that seem ok
https://github.com/Leantime/leantime/blob/2e7cfd12ae8779e999ba648e5e7929345f3a15ab/app/Core/Environment.php#L112

**Comment by vitor-alves** [comment]
I'm having the same issue. Sticking with leantime/leantime:2.4-beta-4 for now

**Comment by jiriks74** [comment]
I haven't found anything sadly.
I'll go and have some sleep, it's 4:15am here. I'll look at it in the morning/afternoon if it isn't fixed by then.

**Comment by marcelfolaron** [comment]
Thanks for your help

**Comment by schories** [comment]
DIGEST:sha256:96ff70a3a42551bfa93170055991ce3ca76354a95cce2a53cb0dbcda3e175376 fixed the issue for me..

(It was introduced with DIGEST:sha256:5ecd12771567c9606b5bf880e3e076b5466907ea3af5cf9fa575e5779b703ab3 for me.)

**Comment by jiriks74** [comment]
@schories please add a Space before thé commit hashes si that Github can convert them to links

**Comment by jiriks74** [comment]
(misclick on my phone)

**Comment by jiriks74** [comment]
@schories 
> DIGEST:sha256: 96ff70a3a42551bfa93170055991ce3ca76354a95cce2a53cb0dbcda3e175376 fixed the issue for me..
> 
> (It was introduced with DIGEST:sha256: 5ecd12771567c9606b5bf880e3e076b5466907ea3af5cf9fa575e5779b703ab3 for me.)

I can't checkout those commit hashes. Are they valid?
![image](https://github.com/Leantime/leantime/assets/54378412/8b049d86-4c96-4c51-8e7c-35cada1af1da)

**Comment by schories** [comment]
They are from https://hub.docker.com/r/leantime/leantime/tags. I added the links to arch-specific digest-sha256 in my original post.

Please let me know if there are better links/hashes - I will use them instead then.

**Comment by jiriks74** [comment]
It would be helpful if we could find the git commit responsible for the issue so that we can fix it in the codebase.

**Comment by schories** [comment]
I understand now, thank you! I'll look into it and get back asap.

**Comment by schories** [comment]
This would be my pick:

Commit:

https://github.com/Leantime/leantime/commit/147d79ff91a2f9ba969b3b150df1bbdabda6e405

most likely in app/Core/Db.php

https://github.com/Leantime/leantime/commit/147d79ff91a2f9ba969b3b150df1bbdabda6e405#diff-978212dd4e7ca780c01732aa1fa10e7f87e1de2218c10313da14ed46418043f3

**Comment by jiriks74** [comment]
I think so too but the problem is not easy to spot at all. As marcelfolaron said:

> I found where it's failing, but not why...
> All configs make it in except the mysql host. The Db class gets localhost when it should by mysql_leantime

**Comment by schories** [comment]
You both are correct, as always. 

I promise to have a deeper look tonight - with a much more gifted and smarter friend. 

Crying out loud to @MartinMa .. ^^

**Comment by marcelfolaron** [comment]
I am fairly certain I found it. Background: Leantime can handle 3 types of configuration files (configuration.php, yaml and .env). The order of priority is (low to high) `configuration.php -> yaml -> .env`
The latter "should" overwrite previously set variables. However in this case we got some checks wrong and if a value was set in the previous config the following config checks were not overwriting the values. 

In this particular instance `$dbHost` is set to `"localhost"` in the `configuration.php` file but the docker compose file defines the mysql container to be `mysql_leantime` through the environment file. This was not overwritten. 

I have a fix in: https://github.com/Leantime/leantime/pull/1923/files 

We have tests that build and check the docker image but unfortunately they were all using "localhost" as the db, so they didn't catch this issue.

**Comment by jiriks74** [comment]
@marcelfolaron 
Could we now rebuild `v2.4-beta-5` as it's now fixed? Or make `v2.4-beta-6` to include the new fixes?

**Comment by marcelfolaron** [comment]
just released 2.4-beta-6 which should fix this

**Comment by schories** [comment]
Yes,  [2.4-beta-6](https://hub.docker.com/layers/leantime/leantime/2.4-beta-6/images/sha256-e2e6549ee5ce994574cc32d6741ebb880d4bd704646d19ef849b2a2b05bbfd34?context=explore) causes no MySQL DB issues.

I apologize for the late reply.

Thank you!
