### ISSUE TITLE
[BUG] can't save todo in list representation

### ISSUE THREAD

**Issue by tsifra** [Leantime/leantime#1925]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
Can't 'save' or 'save & close' todo during edit in list representation.

**To Reproduce**
1. Go to '.make - to-dos' menu
2. Click on 'list' representation
3. Click on any item in list to open edit form
4. Click in 'save' or 'save & close' on 'details' tab.

**Expected behavior**
Expected page to be reloaded or message with save result popup. If you check network log in browser you'll see that no data was submitted. Both buttons don't trigger any action.

**Leantime Version**
v2.4-beta-5

**Server**
nginx

**PHP / MySQL Version**
php 8.1

**Additional context**

**Comment by marcelfolaron** [comment]
just released 2.4-beta-6 which should fix this
