### ISSUE TITLE
[BUG] To-Dos count not updating (it stays 0 no matter how many To-Dos are in that section)

### ISSUE THREAD

**Issue by jiriks74** [Leantime/leantime#1927]
**What set up are you using**
* [x] Self Hosted

**Describe the bug**
![image](https://github.com/Leantime/leantime/assets/54378412/6fb2ec80-6d6a-42c7-b278-e221b0395b3a)

**To Reproduce**
1. To-Dos
2. See your To-Dos or create new ones
3. See the count in the sections (`New`, `Blocked`, ...)
4. It stays at `0` no matter how many To-Dos are in that section

**Expected behavior**
The number being affected by the number of To-Dos in that section

**Leantime Version**
v2.4-beta-4

**Server**
Docker

**PHP / MySQL Version**
Docker

**Additional context**
All the To-Dos are in a Sprint

**Comment by marcelfolaron** [comment]
just released 2.4-beta-6 which should fix this
