### ISSUE TITLE
[BUG](To-Dos) The timeline view is shifted to the left and does not represent the selected dates

### ISSUE THREAD

**Issue by jiriks74** [Leantime/leantime#1928]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [x] Self Hosted

**Describe the bug**
The To-Dos (and Milestones) are shifted to the left. I have To-Dos for the next month that show up as due to half of September which already passed.

<details>
<summary>Kanban view (here you can see the due dates</summary>

![image](https://github.com/Leantime/leantime/assets/54378412/c64e69d4-95be-4d26-9258-ad3bcbfa9724)

</details>

<details>
<summary>Timeline view</summary>

![image](https://github.com/Leantime/leantime/assets/54378412/5979d171-6092-4c75-b199-b3a16b644320)

</details>

**To Reproduce**
1. Go to To-Dos
2. Make sure you're in _Kanban_ view
3. Create a To-Do with a due date
4. Go to _Timeline_ view
5. See that the end of the To-Do is not correct

**Expected behavior**
Correct dates being used for To-Dos in Timeline view

**Leantime Version**
v2.4-beta-4

**Server**
Docker

**PHP / MySQL Version**
Docker

**Additional context**
All To-Dos are in a Sprint

**Comment by marcelfolaron** [comment]
I did fix that one in 2.4-beta-5. Lets check with the next release.

**Comment by jiriks74** [comment]
> I did fix that one in 2.4-beta-5. Lets check with the next release.

Will do as soon as the Docker image is available.

Closing as a duplicate of #1902
