### ISSUE TITLE
[BUG] UI items not translated

### ISSUE THREAD

**Issue by Razique** [Leantime/leantime#1939]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
Upon upgrading to 2.3.27 version, some fields are not translated

**To Reproduce**
1. Upgrade to 2.3.27 version
2. Refresh screen
3. Some menu items are not translated (see screenshot)

**Expected behavior**
Application entries should be translated

**Leantime Version**
2.3.27

**Server**
Nginx

**PHP / MySQL Version**
PHP 8.2 FPM

<img width="477" alt="Screenshot 2023-10-01 at 12 35 33" src="https://github.com/Leantime/leantime/assets/1027278/3ebee5fd-070e-4f67-8dad-2a40eb5fab6c">
<img width="971" alt="Screenshot 2023-10-01 at 12 35 17" src="https://github.com/Leantime/leantime/assets/1027278/bf513d23-61c9-4906-b9c3-02422a078639">
<img width="213" alt="Screenshot 2023-10-01 at 12 34 56" src="https://github.com/Leantime/leantime/assets/1027278/ad1e4da1-da1c-40fb-88f6-536208c00249">

**Comment by gloriafolaron** [comment]
Hi! 

Could you update to 2.4-stable and see if you're still having the same issues? 

If you are, would you verify what theme you're using?

**Comment by Razique** [comment]
Hi @gloriafolaron,
I have updated to the 2.4 stable, and I confirm that this fixed the issue.
However, there are still some entries that didn't get translated. This is on the profile settings, after switching to dark theme --, the theme name reads `theme.name`

<img width="417" alt="Screenshot 2023-10-10 at 16 31 17" src="https://github.com/Leantime/leantime/assets/1027278/2160b476-1533-4dea-b131-539ad0b219a9">

**Comment by gloriafolaron** [comment]
Thanks for calling that out.

@marcelfolaron see here for next round of fixes.

**Comment by marcelfolaron** [comment]
Fixed in 3.0.0
