### ISSUE TITLE
[BUG] mobile (responsive) layout broken in to-dos

### ISSUE THREAD

**Issue by tsifra** [Leantime/leantime#1940]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
When to-dos main page is opened on mobile phone layout is broken

**To Reproduce**
1. Go to 'To-dos menu'
2. See error. Topmost part of page with profile button has larger width than other page elements.

**Expected behavior**
Expected to see clean responsive layout without h-scroll in browser

**Leantime Version**
2.4-beta6

**Server**
nginx

**PHP / MySQL Version**
php 8.1

**Comment by gloriafolaron** [comment]
Hi!

We are now on 2.4-stable.

Can you verify if this is still an issue?
