### ISSUE TITLE
[FEATURE] task priority view by color, not text

### ISSUE THREAD

**Issue by tsifra** [Leantime/leantime#1942]
**Is your feature request related to a problem? Please describe.**
When you look at kanban view there is priority tag marked with color and containing priority text in it. That doesn't allow to take a quick look at task priority because tag can be situated in random place in rectangle because of milestone text.

**Describe the solution you'd like**
Priority text can be removed to make visual recognition based on colors. In my opinion odoo erp / project module have almost good workflow and representation of kanban cards.

**Comment by marcelfolaron** [comment]
The border on the right side of the card is actually representing the priority color. Is that what you are looking for?

**Comment by tsifra** [comment]
It's hard to explain without screenshots. I'm talking about max. fixing of kanban card's elements layout. Now there are three elements in one line that are floating: milestone, priority and effort. I think that if priority will be color circle near "assigned to" or on the left down angle with same popup menu for changing it. It will increase readability of the page. I didn't recognized color of vertical line in the left of the card until this moment. It's cool.
PS: Just sharing ideas. Please close if your vision is different.

**Comment by gloriafolaron** [comment]
Just curious -- are you mostly working off the kanban views instead of the "home" views on top? These may be easier to visualize and I'd be curious on your thoughts.

Appreciate the discussion too because we're always looking for ways to make things more clear and intuitive.
