### ISSUE TITLE
[BUG] Fix Codesniffer violations

### ISSUE THREAD

**Issue by marcelfolaron** [Leantime/leantime#1944]
We are getting fairly close to being fully PSR-12 compliant and have complete documentation. 
There are currently 1700 code sniffer violation, most of them being missing variable comments and some missing types. 
Good issue to get large exposure to the Leantime codebase and contribute to our documentation efforts

**Comment by colomeramonica** [comment]
Hey, can you assign that one to me! I'd love to help

**Comment by marcelfolaron** [comment]
Sure thing

**Comment by RahatAhmed171** [comment]
Hi, is this issue still open? would like to contribute

**Comment by marcelfolaron** [comment]
We are now using Laravel Pint for codestyling
