### ISSUE TITLE
[FEATURE] date-time formats

### ISSUE THREAD

**Issue by tsifra** [Leantime/leantime#1945]
**Is your feature request related to a problem? Please describe.**
The problem is that date and time formats are related to selected locale in settings. For example some english terms are sometimes better to use than localized national translation. In the same time using non 24h format and m/d/y sequence is not good

**Describe the solution you'd like**
 It would be better if ISO yyyy-mm-dd or dd-mm-yyyy will be used or there will be option to choose date-time formats separately from language

**Comment by marcelfolaron** [comment]
I agree, this should be a user setting alongside with timezones. We have folks working in different timezones and that should be reflected.

**Comment by eric-hansen** [comment]
Would you mind if I take a shot at this @marcelfolaron ?

**Comment by marcelfolaron** [comment]
Oh I just realized that we are actually using date_default_timezone_set() in the appSettings file. So this will make it a lot easier since you can change that at any time.

**Comment by eric-hansen** [comment]
@marcelfolaron since this will require a DB change to support storing the user's preferred TZ and date-time format, what is the process for DB migrations/DDLs?

**Comment by marcelfolaron** [comment]
Hi,

A db change won't be needed for this. Settings like that are stored in the settings table. You can follow the examples for the theme or language setting of a given user in the esitOwn controller.

**Comment by eric-hansen** [comment]
@marcelfolaron thanks for that!  I was thinking things were structured differently (that's what I get for coding at 2 AM hah).

I'm not familiar with Crowdin so for new strings what do I need to do?  As I'll have to add in some UI text to this.

**Comment by marcelfolaron** [comment]
No problem. For new content strings just add them to the en-US.ini language file (in the repository, not in crowdin). 
Crowdin will automatically pick up the changes and push the new key to all the other translation files.

**Comment by eric-hansen** [comment]
I've got most of this done, and updated the Language.php file to use the new settings if they exist or fallback to the original format.  However, a couple of things:

* As part of this effort does it make sense to let the user choose a TZ that's different than the default/set in the config?
* While I trust the business logic, I'm always a fan of having tests in place, but I can't really understand how PHP tests are handled currently (there's no phpunit.xml file and `./vendor/bin/phpunit` says no tests ran as well as if I pass in the `tests` dir).

If PHP unit testing isn't a thing currently then I can add that in with some tests for my changes if you like.  I know there's also #1949

**Comment by marcelfolaron** [comment]
Yes, we should let users pick a timezone. It’s fairly easy in php to change
the timezone on the fly.

We currently only have integration tests but are in dire need to write more
unit tests.
The tool we are using is codeception which is built on top of phpunit.
You’re welcome to give it a try but it’s also okay to wait for now until we
have a few example tests in place.

**Comment by marcelfolaron** [comment]
See further comments on: https://github.com/Leantime/leantime/issues/1945

**Comment by marcelfolaron** [comment]
<img width="369" alt="image" src="https://github.com/Leantime/leantime/assets/47038998/2d86f92f-b340-4c2e-9bb3-65473fa8f10c">

<img width="369" alt="image" src="https://github.com/Leantime/leantime/assets/47038998/3d1c03ce-8300-4e66-8591-4d1ca65f3c3b">

**Comment by eric-hansen** [comment]
I was able to resolve the first issue.  Mostly got the 2nd part done but need to finish up some testing.
