### ISSUE TITLE
[BUG] Jibberish inside of Your To-Dos Title on main Page

### ISSUE THREAD

**Issue by otinex** [Leantime/leantime#1951]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
On the first Page where the ToDos are shown there is a string inside the bracket that doesn't change and doesn't make sense.
![image](https://github.com/Leantime/leantime/assets/28898876/8c189a3c-3793-4c2e-8701-07cdffea27f1)

**To Reproduce**
1. Go to Main Pare
2. Scroll down to 'Your To-Dos'
3. See error

**Expected behavior**
Either remove the brackets or show something useful.

**Leantime Version**
2.4-beta8

**Server**
nginx

**PHP / MySQL Version**
Please list the PHP and Mysql version you are using

**Additional context**

**Comment by marcelfolaron** [comment]
Which language file is being used here (en-US is standard, are you using en-GB)? The string has changed a few versions ago

**Comment by marcelfolaron** [comment]
Should be fixed in 2.4.1 now
