### ISSUE TITLE
[FEATURE] Milestone view "only" in Timeline

### ISSUE THREAD

**Issue by EHRETic** [Leantime/leantime#1952]
**Is your feature request related to a problem? Please describe.**
I hope I'm not mistaken but I think since 2.4 series, the possibility to display milestones only is not possible anymore in the new Timeline view (was previously a Milestones section) and I'm missing it.

**Describe the solution you'd like**
I think an extra "Milestones" type filter would be the perfect solution to give that possibility (exist already for tasks):

![image](https://github.com/Leantime/leantime/assets/28634810/eafe64a4-5e48-4921-8538-ac9016b3c256)

I didn't find the possibility by plying with filters but correct me if I'm wrong 😉
Thanks in advance

**Comment by marcelfolaron** [comment]
This is now in the latest 2.4 stable release.

**Comment by EHRETic** [comment]
> This is now in the latest 2.4 stable release.

Thank you very much @marcelfolaron 😉👌
