### ISSUE TITLE
[BUG] Once clicking on any navbar menu item, the corresponding menu isn't showing on hover.

### ISSUE THREAD

**Issue by vivekpathakgit** [Leantime/leantime#1954]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version

**Expected behavior**
Regardless of multiple clicks on menu items, the menu should be shown on mouse hover.

**Leantime Version**
The deployed version.

**Help**
If anyone can help me find the navbar file (or the homepage file) in the directory, I can try my best to resolve this issue

**Additional context**
![bug](https://github.com/Leantime/leantime/assets/93838914/16a1b5bd-60b0-48b5-a24b-67058ee91f7b)

**Comment by marcelfolaron** [comment]
Fixed
