### ISSUE TITLE
Projects burndown charts doesn't work

### ISSUE THREAD

**Issue by gonztirado** [Leantime/leantime#196]
It seems like the burndown charts don't work properly. Also, we can't change this chart between Sprint, for example, to compare the chart with the previous sprint one

**Comment by marcelfolaron** [comment]
Thanks for reporting. We found the issue and will work on a fix this week.

**Comment by marcelfolaron** [comment]
FYI we verified the issue and have a fix ready. The burndown charts and reports are indeed incorrect.

**Comment by gonztirado** [comment]
Thanks, Marcel! I've tried to understand how this chart works but, certainly the behavior it was very strange

**Comment by marcelfolaron** [comment]
Fixed for future burndown charts in 2.1 beta 6
