### ISSUE TITLE
[BUG] UpdateLeantime.sh script doesn't work

### ISSUE THREAD

**Issue by NaBuLSiO** [Leantime/leantime#1964]
**What set up are you using**

* [x] Self Hosted

**Describe the bug**
UpdateLeantime.sh script has couple of issues.
* First it fails to do the database backup step.
* Second it fails to unzip the downloaded file saying that the download file is not a zip file. So maybe there is an issue with the download file URL.
After downloading the file manually and unzipping it then copying the files to the www/html file 
two more issues have showed up:
1. Old configuration file didn't work because of the namespace was changed [here](https://github.com/Leantime/leantime/blob/8ed1e1c0c5ad4bf1cf7de5cfcca698d9cedc7063/app/Core/Environment.php#L3)
2. A permission issue for the ./cache/view directory where the permission for the folder needs to be changed .
 
**To Reproduce**
1. Go to the directory where Leantime is installed
2. Run updateLeantime.sh 

**Expected behavior**
updateLeantime.sh script should work as excepted without the need of the change to the php file or do any permission commands.

**Leantime Version**
I was on 2.3.* and tried to update to 2.4 latest version at the time of the creation of this issue.

**Server**
Apache, nginx

cc: @TareqK

**Comment by TareqK** [comment]
https://discord.com/channels/990001288026677318/1156490503362199642


Please read this thread and make sure you have followed these steps
