### ISSUE TITLE
[BUG] LDAP Login not possible after upgrade to 2.4

### ISSUE THREAD

**Issue by Stiles96** [Leantime/leantime#1965]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ X ] Self Hosted

**Describe the bug**
Error Log:
[09-Oct-2023 16:32:44 Europe/Berlin] PHP Fatal error:  Uncaught Error: Non-static method Leantime\Domain\Ldap\Services\Ldap::bind() cannot be called statically in /var/www/leantime/app/Domain/Auth/Services/Auth.php:226
Stack trace:
#0 /var/www/leantime/app/Domain/Auth/Controllers/Login.php(81): Leantime\Domain\Auth\Services\Auth->login()
#1 /var/www/leantime/app/Core/Controller.php(98): Leantime\Domain\Auth\Controllers\Login->post()
#2 /var/www/leantime/app/Core/Controller.php(59): Leantime\Core\Controller->executeActions()
#3 [internal function]: Leantime\Core\Controller->__construct()
#4 /var/www/leantime/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs()
#5 /var/www/leantime/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build()
#6 /var/www/leantime/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve()
#7 /var/www/leantime/app/Core/Frontcontroller.php(120): Illuminate\Container\Container->make()
#8 /var/www/leantime/app/Core/Frontcontroller.php(74): Leantime\Core\Frontcontroller::executeAction()
#9 /var/www/leantime/app/Core/Bootloader.php(370): Leantime\Core\Frontcontroller::dispatch()
#10 /var/www/leantime/app/Core/Bootloader.php(165): Leantime\Core\Bootloader->handleRequest()
#11 /var/www/leantime/public/index.php(14): Leantime\Core\Bootloader->boot()
#12 {main}
  thrown in /var/www/leantime/app/Domain/Auth/Services/Auth.php on line 226

Redirect to: /auth/login, whitescreen

At my first try I was logged in by a cookie and the system works. I cleared my cache and no login is possible.

**To Reproduce**
1. Try to login with a ldap user

**Expected behavior**

**Leantime Version**
2.4

**Server**
Apache

**PHP / MySQL Version**
PHP 8.1

**Additional context**
LDAP Config:

    public $useLdap = true;            //Set to true if you want to use LDAP
    public $ldapType = 'AD';                     //Select the correct directory type. Currently Supported: OL - OpenLdap, AD - Active Directory
    public $ldapHost = 'Zuhause.local';                                //FQDN
    public $ldapPort = 389;                               //Default Port
    public $ldapDomain = 'Zuhause.local';
    public $ldapUserDomain = 'he-it.eu';
    public $baseDn = 'DC=Zuhause,DC=local';
    public $ldapDn = 'OU=User Accounts,DC=Zuhause,DC=local';      //Location of users, example: CN=users,DC=example,DC=com
    public $bindUser = 'SVC-LDAP'; //ldap user that can search directory. (Should be read only)
    public $bindPassword = '{{ ldapAgentPassword }}';
    //Default ldap keys in your directory.
    public $ldapKeys = '{
        "username":"sAMAccountName",
        "groups":"memberof",
        "email":"mail",
        "firstname":"givenname",
        "lastname":"sn",
        "phonenumber":"telephoneNumber",
        "jobTitle":"title",
        "jobLevel":"",
        "department":"department"
    }';

**Comment by gloriafolaron** [comment]
What version are you updating from?

There are some threads discussing LDAP updates around some of the breaks on
our discord server that may be helpful as well.

**Comment by Stiles96** [comment]
2.3.27

**Comment by marcelfolaron** [comment]
Should be fixed in 2.4.1 now
