### ISSUE TITLE
[BUG] url bug

### ISSUE THREAD

**Issue by andy9468** [Leantime/leantime#1967]
## 1. Describe the bug

First, create a milestone. Secondly, click on to-Dos and then click on Timeline to view the milestone. On this page, select the newly added milestone and pop up a floating window, where you can click to view the todo tasks. Finally, it was found that the tasks below this milestone could not be accessed.

http://ip:8081/tickets/showKanban&milestone=12

## 2.suggestion:

http://ip:8081/tickets/showKanban&milestone=12

The char & in that url should be changed to char ?.

**Comment by marcelfolaron** [comment]
Should be fixed in 2.4.1 now
