### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ShadowPeo** [Leantime/leantime#1971]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X ] Self Hosted

**Describe the bug**
No LDAP Bind variables in configuration.php or Docker sample.env.

Specificially options for the following variables seem to be missing

ldapDomain
ldapUserDomain
baseDn
bindUser

**To Reproduce**
Look at configuation.php and sample.env for docker

**Expected behavior**
Variables/Docker ENV Vars to be provided so we know what they are and if they are still valid

**Leantime Version**
2.4 Docker

**Server**
Docker

**PHP / MySQL Version**
Docker

**Additional context**

**Comment by marcelfolaron** [comment]
All variables from the config can be used in the env files as well. The sample env was updated.
