### ISSUE TITLE
[BUG] Milestone can not be removed from a goal

### ISSUE THREAD

**Issue by ybizeul** [Leantime/leantime#1974]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
Milestone can not be removed from a goal

**To Reproduce**
1. Create a new milestone
2. Create a new goal
3. In the goal, lick Attach Milestone
4. Attach a milestone
5. Try to remove by clicking "Remove"

**Expected behavior**
The milestone should be removed from the goal

**Leantime Version**
2.4

**Server**
Official container

**PHP / MySQL Version**
Official container

**Additional context**
Container running on Docker Desktop macOS on M1 platform.

**Comment by Stiles96** [comment]
Workaraound: Save the goal and the goal looses the reference to the milestone

**Comment by gloriafolaron** [comment]
This was fixed in 2.4.2 but would recommend to wait to update until 2.4.3 due to some bugs that came up on the blueprints.

**Comment by marcelfolaron** [comment]
Fixed in 2.4.4
