### ISSUE TITLE
[BUG] OpenIDConnect: typo in the client id and secret key environment variables

### ISSUE THREAD

**Issue by aHugues** [Leantime/leantime#1976]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**

When configuring Leantime as an OpenIDConnect client using environment variables instead of `configuration.php`, there is a typo on two environment variables used to configure it

```
## OpenID Connect
# required
# LEAN_OIDC_ENABLE = false
# LEAN_OIDC_CLIEND_ID =
# LEAN_OIDC_CLIEND_SECRET =
```

Here we have `LEAN_OIDC_CLIEND_ID` instead of `LEAN_OIDC_CLIENT_ID` and `LEAN_OIDC_CLIEND_SECRET` instead of `LEAN_OIDC_CLIENT_SECRET`

We can also see on [Environment.php](https://github.com/Leantime/leantime/blob/master/app/Core/Environment.php#L67C1-L68C57)

```php
        'oidcClientId' => 'LEAN_OIDC_CLIEND_ID',
        'oidcClientSecret' => 'LEAN_OIDC_CLIEND_SECRET',
```

The options have the correct name in their php version, but not their environment variables, which can lead to confusion.

**To Reproduce**
1. Copy content from [sample.env](https://github.com/Leantime/docker-leantime/blob/master/sample.env)
2. Scroll to the `OpenID Connect` section
3. See the different variable names

**Expected behavior**
Environment variables should correspond to their PHP counterparts

**Leantime Version**
Leantime 2.4 (docker)

**Server**
NA

**PHP / MySQL Version**
NA

**Additional context**
Since the typo might have not been spotted by just copy/pasting the environment file, then simply fixing the values could introduce a breaking change due to the name change,

**Comment by marcelfolaron** [comment]
Fixed in 2.4.5
