### ISSUE TITLE
[BUG] Google Docs Embedding fails in Wikis

### ISSUE THREAD

**Issue by harrellbm** [Leantime/leantime#1977]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [x] Cloud Hosted Version
* [ ] Self Hosted

**Describe the bug**
Google docs embedding fails within the wikis

**To Reproduce**
1. Go to docs and create a new article.
2. Click on embed and provide a google docs share link. 
3. The embedding works until you go to hit save
5. See error
![image](https://github.com/Leantime/leantime/assets/55707292/4c177f5d-4949-4f2c-8e47-d6976955cf82)
Which is slightly different from past errors pictured below:
![image](https://github.com/Leantime/leantime/assets/55707292/2405094c-fc52-45fa-8c83-cb44d915d43a)

**Expected behavior**
To save the embedded doc within the wiki

**Leantime Version**
2.4 Cloud

**Server**
N/a

**PHP / MySQL Version**
N/a

**Additional context**
Past embedded docs are still visible it seems to only be the saving process that is erroring out.

**Comment by harrellbm** [comment]
As of 2.4.2 this bug has

**Comment by harrellbm** [comment]
Ops sorry this bug has improved with 2.4.2 but is still present
![image](https://github.com/Leantime/leantime/assets/55707292/286a7485-34c3-4786-8a15-a4139e669d00)

**Comment by marcelfolaron** [comment]
This was tested extensively and seems to be working.
