### ISSUE TITLE
[BUG] Menu Style inconsistency on narrow window

### ISSUE THREAD

**Issue by harrellbm** [Leantime/leantime#1978]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [x] Cloud Hosted Version

**Describe the bug**
A small styling issue with how the menu is displayed on a narrow screen.

**To Reproduce**
1. Shrink screen window to at least 50% width
2. Open Menu
3. See error:
![image](https://github.com/Leantime/leantime/assets/55707292/78a427b8-cbc8-4874-a7e0-865762e08afa)

**Expected behavior**
Consistent styling on smaller window.

**Leantime Version**
2.4 Cloud

**Server**
N/a

**PHP / MySQL Version**
N/a

**Additional context**
Restoring to full screen solves inconsistency without a reload.

**Comment by marcelfolaron** [comment]
Fixed in 2.4.4
