### ISSUE TITLE
[BUG] Importing Blueprint doesn't work

### ISSUE THREAD

**Issue by ybizeul** [Leantime/leantime#1979]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
I needed to split a project in two, since I don't see a way to move blueprints from a project to another, I exported it and wanted to import it in the new project

**To Reproduce**
1. Create a project and create a SWOT Analysis
2. Export the blueprint to a local file
3. Create another project
4. Go to Blueprints
5. Click on SWOT Analysis
6. From the 3 dots icon choose Import
7. Choose the file previously exported
8. Click import

**Expected behavior**
Board should be imported, but instead of that, Leantime is showing a blank page to "http://localhost:8081/swotcanvas/showCanvas"

**Leantime Version**
2.4

**Server**
Official docker container

**PHP / MySQL Version**
Official docker container

**Additional context**
none

**Comment by marcelfolaron** [comment]
Fixed in 2.4.4
