### ISSUE TITLE
[BUG] For user management section, I can't perform any Edit/delete action for any users

### ISSUE THREAD

**Issue by charly-palencia** [Leantime/leantime#1980]
For user management section, I can't perform any Edit/delete action for any users after the version  beta 2.4.0-7

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
Every time I tried to edit or delete an user, it raises the error "Form Token , please try again". I'm not sure if this is a CRFS token error form the laravel form, but it doesn't allow me to do any action in this admin page but create a user.

**To Reproduce**
1. Go to User management section as super admin
2. Click on any delete icon action for an user
3. Accept confirmation
4. See error message of the top right.
5. (Same with the edit action)

**Expected behavior**
It should delete or save the user's changes

**Leantime Version**
2.4.1 latest

**Server**
docker

**PHP / MySQL Version**
docker compose version

**Additional context**
![image](https://github.com/Leantime/leantime/assets/645526/1cbcf33c-3518-47bc-a703-ecc847096e99)

**Comment by eric-hansen** [comment]
is the URL you're accessing the install with different than what's configured?

i.e.: if the app is configured to be ran on http://localhost but you're accessing it through http://leantime.domain.com then that'll cause this issue.
