### ISSUE TITLE
[FEATURE] Idea service API

### ISSUE THREAD

**Issue by liquidz3r0** [Leantime/leantime#1987]
**Is your feature request related to a problem? Please describe.**
There is currently no API available to post or interact with the Idea boards

**Describe the solution you'd like**
Having a API implemented for this functionality

**Additional context**
None

**Comment by gloriafolaron** [comment]
Adding this to hacktoberest:

This needs a wrapper method in the idea service.

**Comment by marcelfolaron** [comment]
3.2.0 added various endpoints for the idea api
