### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by phancaovu** [Leantime/leantime#1989]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ ] Self Hosted

**Describe the bug**
Leantime OPENID is not working, it is a problem with callback URL. In spite of the Authentik app notification success.

http://localhost:8081/oidc/callback?state=2287956a32513583b73f12d48a328910&session_state=0fd0d421-a0bf-43d9-9ad0-b22b090a5d5d&code=8085ef54-fd1b-4c0c-8024-6d8cae88bdd3.0fd0d421-a0bf-43d9-9ad0-b22b090a5d5d.e4956e15-4107-4726-9baa-e8ea0edff697

**To Reproduce**

**Expected behavior**

**Leantime Version**
Which Leantime version are you using

**Server**
Apache, nginx, IIS etc

**PHP / MySQL Version**
Please list the PHP and Mysql version you are using

**Additional context**

**Comment by gloriafolaron** [comment]
Hey, are you able to answer the other questions for us?

What version you're on?
Whats your server set up?

**Comment by phancaovu** [comment]
> Hey, are you able to answer the other questions for us?
> 
> What version you're on? Whats your server set up?

I use version 2.4 beta 
server setup apache  
using Authentik authen
