### ISSUE TITLE
USER FILES

### ISSUE THREAD

**Issue by paccmx** [Leantime/leantime#1992]
I have an issue with user files.

When I upgrade i get a 500 error, if I do not delete all the folders from my install.  This causes an issue as my user files are in there somewhere.  I have not found them yet...

I would recomend that the document and user files be stored in the database vs file system, one for security, and two for ease of backup.

**Comment by marcelfolaron** [comment]
Userfiles are stored in the userfiles/ folder which is outside of the publicly available file path. Storing files in the db is actually quite slow and hard on the db. So if you need to delete folders due to changes just delete everything except the userfiles and config folder.
