### ISSUE TITLE
[BUG] Can't close pop-ups and start timers

### ISSUE THREAD

**Issue by v-marinkov** [Leantime/leantime#1995]
I updated to 2.4.2 from 2.3.27 using Docker and I noticed I can't close pop-ups. Firefox throws: `Uncaught DOMException: The operation is insecure.` while Chrome `Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'https://tickets/showKanban' cannot be created in a document with origin 'mydomain.com'`

Starting a timer throws 404 in the console:  `Response Status Error Code 404 from https://mydomain.com//hx/timesheets/stopwatch/start-timer/`

I am running it behind nginx with SSL. I had to add `LEAN_APP_URL: 'https://mydomain.com'` to get rid of some cross-origin errors after the update but perhaps that's not enough. What else do I need to do to have it function properly?

Thanks

**Comment by gloriafolaron** [comment]
Hi! 

Did you also use these instructions?

https://github.com/Leantime/leantime/releases/tag/v2.4-beta-2

**Comment by v-marinkov** [comment]
@gloriafolaron which instructions do you mean exactly? The top of the `configuration.php` file must have automatically updated to the instructions there. I only have 2 plugins - "Motivational quotes" and "csvimport", but disabling them changes nothing.

**Comment by v-marinkov** [comment]
I removed "Motivational quotes" but trying to remove "csvimport" causes an error 500:
```
[17-Oct-2023 12:30:55 Europe/London] PHP Fatal error:  Declaration of Leantime\Plugins\CsvImport\Services\CsvImport::connect(): void must be compatible with Leantime\Domain\Connector\Services\ProviderIntegration::connect(): mixed in /var/www/html/app/Plugins/CsvImport/Services/CsvImport.php on line 47
```
Could this be related and how can I manually remove this plugin?

**Comment by gloriafolaron** [comment]
If the header was already added to the config file there, then likely not. We haven't seen this issue with the plugins -- I'm on product side so unfortunately, resources is where my skill set runs out. 

Giving Marcel a quick download on your issues, though: 
Can you confirm that you're on a reverse proxy (based on what you described)? 

If yes, aside from the cross origin errors, we are unable to account for the variety of configurations that can occur in a reverse proxy setting and it may be something outside of our system control. For these setups, however, we recommend using our priority support plans as we can then set some time and a call to walk through it and try to locate the challenges. We do have one time support options as well that are not currently listed. You can send us an email at support@leantime.io if you're interested in that.  https://leantime.io/priority-support/
