### ISSUE TITLE
[BUG] Milestone shows as not completed in goals

### ISSUE THREAD

**Issue by Stiles96** [Leantime/leantime#1997]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
I have a milestone finished to 100%. 1 Task was removed and as also marked as finished. Everywhere I see the milestone has 100% but not in the goal. Re-Link the milestone doesn't help.

**To Reproduce**
1. Make a goal and a milestone
2. Add some tasks, set 1 to removed and finished the other tasks
3. The milestone will be shown as completed
4. The milestone in the goal isn't completed

**Expected behavior**
Show the milestone in the goal also as finished.

**Leantime Version**
2.4.1

**Server**
Apache2

**PHP / MySQL Version**
8.1

**Comment by gloriafolaron** [comment]
Thanks for sharing this. Could you share a screenshot on the milestone on the goal (limiting whatever personal info)? I just want to make sure I'm understanding.

**Comment by Stiles96** [comment]
![image](https://github.com/Leantime/leantime/assets/51234422/8f350f99-9416-4370-9c62-802f339408a8)

![image](https://github.com/Leantime/leantime/assets/51234422/33953625-e647-4656-be97-c68f0dc3eb47)

![image](https://github.com/Leantime/leantime/assets/51234422/aad183aa-2193-41cd-9875-c1087385850a)

![image](https://github.com/Leantime/leantime/assets/51234422/11c961e4-382d-4463-8e5a-6bcec4f15b1d)

**Comment by gloriafolaron** [comment]
Thanks, that was really helpful!

In this case, I'm seeing a bug on the table setting given that you are reporting abgelehnt as a done state and it not carrying over to the Milestone Goals calculation. 

If you mark the Abgelehnt task to Archived, do you still see the % miscalculation?

**Comment by Stiles96** [comment]
If I mark the task as archived, I get the 100% in the goal.

**Comment by marcelfolaron** [comment]
Fixed in 2.4.4
