### ISSUE TITLE
Set permission for client.

### ISSUE THREAD

**Issue by dqn9t2** [Leantime/leantime#200]
Can i set permission for my client, what he can change, or can not. because i have many type of client, some time i just want him to see the overview of the project... 
Thanks for your work.

**Comment by marcelfolaron** [comment]
Hi, thanks for reaching out.
Granular permissions like that (attribute based) are currently not possible. It is on the roadmap for 2020 (most likely Q3).

**Comment by marcelfolaron** [comment]
We added a new role system which should cover most use cases
