### ISSUE TITLE
[FEATURE] Always visible horizontal scrollbar for Timelines

### ISSUE THREAD

**Issue by v-marinkov** [Leantime/leantime#2002]
The timeline view can sometimes be very long vertically as well as horizontally. I don't always have a mouse with a horizontal scroll wheel and now I have to scroll all the way to the bottom to be able to scroll horizontally if I want to explore a given task or milestone. It would be very useful to always see the horizontal scrollbar like you see the vertical. On Windows we can middle click and scroll horizontally that way, but that doesn't hold for Linux or MacOS.

Could the horizontal scrollbar on the Timeline view be made to stick to the bottom of the browser viewport?

**Comment by marcelfolaron** [comment]
Fixed in 2.4.4
