### ISSUE TITLE
[BUG] Sub-tasks don't show their name on Project Overview page

### ISSUE THREAD

**Issue by v-marinkov** [Leantime/leantime#2003]
Running 2.4.3 on Docker

On project Overview sub-tasks are not showing their name, but only the parent's name. In the example below the top one with the yellow bar is a sub task with a name "test sub-task" but only the parent's (lower one) name is showing:

![image](https://github.com/Leantime/leantime/assets/7135724/74772c51-e284-4f41-b0d8-8165ea1ef9f3)

**Comment by marcelfolaron** [comment]
Fixed in 2.4.4
