### ISSUE TITLE
[BUG]  syntax error, unexpected '|' 

### ISSUE THREAD

**Issue by ithakaa** [Leantime/leantime#2006]
I am trying to install a fresh copy of Leantime but am getting the below error.

`[Thu Oct 19 02:53:56.517697 2023] [php7:error] [pid 875] [client 192.168.0.2:51042] PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/html/leantime/app/Core/Bootloader.php on line 42`

Ubuntu 22.04

**Comment by ithakaa** [comment]
I am running 8.1

```
root@leantime:~# php -v
PHP 8.1.24 (cli) (built: Oct  6 2023 09:46:19) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.24, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.24, Copyright (c), by Zend Technologies
```

**Comment by marcelfolaron** [comment]
Can you create a php file on your server and add

```
<?php
phpinfo()
```
to get the exact version number that is currently running.
