### ISSUE TITLE
[BUG] Design optimisation in the kanban board overview

### ISSUE THREAD

**Issue by TheMatzy** [Leantime/leantime#2007]
in the kanban board view, the full width of the task status is not used. as a result, the overview with the tickets is also somewhat squashed. 
In the past, when there were too many task statuses, a scroll bar was simply displayed to the right. I like this view as it is, but I find the wide, white, unused border a bit wasted :)

![image](https://github.com/Leantime/leantime/assets/41703752/430fa2c3-483e-4e8b-9b5b-6eed83eb7879)

**Comment by marcelfolaron** [comment]
Oh Odd. The calculation uses 100% / number if columns. Wonder if there is a crazy rounding error. I'll check with your number of columns

**Comment by TheMatzy** [comment]
Fixed in the new Leantime Version :)
