### ISSUE TITLE
[BUG] Stuck on Update Database for latest docker version during update

### ISSUE THREAD

**Issue by komali2** [Leantime/leantime#2008]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**

I updated our leantime deployment using the docker compose steps:

```
docker-compose pull
docker-compose up -d
```

There were no errors.

On navigating to our deployment's frontend, I'm brought to the `install/update` URL. I click "update now," but am brought to a "form submission over insecure connection" page in my browser. I "send anyway," and am brought back to the `install/update` page. 

The logs in docker look like:

```
leantime       | 127.0.0.1 -  19/Oct/2023:05:49:16 +0000 "GET /index.php" 200
mysql_leantime | 2023-10-19 05:46:42+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.34-1.el8 started.
mysql_leantime | 2023-10-19 05:46:42+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_leantime | 2023-10-19 05:46:42+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.34-1.el8 started.
mysql_leantime | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
mysql_leantime | 2023-10-19T05:46:43.682050Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
mysql_leantime | 2023-10-19T05:46:43.687311Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.34) starting as process 1
mysql_leantime | 2023-10-19T05:46:43.690203Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
mysql_leantime | 2023-10-19T05:46:43.690225Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8mb3_unicode_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
mysql_leantime | 2023-10-19T05:46:43.718783Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
mysql_leantime | 2023-10-19T05:46:44.391134Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysql_leantime | 2023-10-19T05:46:45.184149Z 4 [System] [MY-013381] [Server] Server upgrade from '80033' to '80034' started.
mysql_leantime | 2023-10-19T05:46:56.399771Z 4 [System] [MY-013381] [Server] Server upgrade from '80033' to '80034' completed.
mysql_leantime | 2023-10-19T05:46:56.690849Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql_leantime | 2023-10-19T05:46:56.691201Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
mysql_leantime | 2023-10-19T05:46:56.696136Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql_leantime | 2023-10-19T05:46:56.736182Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.34'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
mysql_leantime | 2023-10-19T05:46:56.736917Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
leantime       | 127.0.0.1 -  19/Oct/2023:05:53:14 +0000 "GET /index.php" 200
```

**To Reproduce**
(see above)

**Expected behavior**
Database update concludes and I can access our leantime frontend as normal.

**Leantime Version**

On `docker images`, it lists as `leantime/leantime` with tag `LATEST` created 36 hours ago at time of posting. I can no longer see the version on the frontend, but I assume it's `2.4.4` based on the docker tags

**Server**
We proxy through nginx `nginx/1.14.0 (Ubuntu)`

`Docker version 20.10.21` 

**PHP / MySQL Version**
Within docker so I'm not sure.

**Additional context**

**Comment by komali2** [comment]
The mysql container seems to be restarting infrequently. I find the log block above from `mysql_leantime` running every few minutes.

**Comment by komali2** [comment]
From within the `leantime` container I did `find . error.log` and after a bunch of output got 

```
find: error.log: No such file or directory
```

**Comment by marcelfolaron** [comment]
Yes within the leantime directory. Should be within /var/www/html/

**Comment by komali2** [comment]
No, within the `/var/www/html/logs` directory there is no `error.log` file, nor any other files.

**Comment by marcelfolaron** [comment]
Can you access the database? I'd like to know the value of db-version
within the zp_settings table

**Comment by marcelfolaron** [comment]
Okay, there are 5 db scripts that came after that. Something must have gone
wrong with the update of the db.
Can you go to your configuration file
/var/www/html/config/configuration.php and set $debug to 1

Then try to run the installer/updater again.
Then head back to  /var/www/html/logs/error.log and see if there is
anything in there.

Alternatively you can rebuild the docker image using the LEAN_DEBUG
environment variable.

**Comment by komali2** [comment]
I tried under `class Config` to set:

```
public $debug = 1;                                    //Debug flag
```

Then reloaded the webpage, clicked "Update Now!", and then checked `var/www/html/logs`, however unfortunately there's no `error.log` file or any other file there. 

I really appreciate your help btw

**Comment by komali2** [comment]
There are log files under `var/www/logs`, checking now

**Comment by marcelfolaron** [comment]
Yeah, that seems unrelated. I am surprised there are no errors in the log file. 
Can you take a look at the database and see if the table zp_canvas has a "description" column? If not we may have to manually update the db. If it does, the db might have updated without udpating the version in the settings table which would be a simple fix.

**Comment by komali2** [comment]
It looks like there's no description column.

```
mysql> describe zp_canvas;
+-----------+--------------+------+-----+---------+----------------+
| Field     | Type         | Null | Key | Default | Extra          |
+-----------+--------------+------+-----+---------+----------------+
| id        | int          | NO   | PRI | NULL    | auto_increment |
| title     | varchar(255) | YES  |     | NULL    |                |
| author    | int          | YES  |     | NULL    |                |
| created   | datetime     | YES  |     | NULL    |                |
| projectId | int          | YES  | MUL | NULL    |                |
| type      | varchar(45)  | YES  |     | NULL    |                |
+-----------+--------------+------+-----+---------+----------------+
6 rows in set (0.07 sec)
```

Should I add one?

**Comment by komali2** [comment]
If that's the only change needed, I can add the column without issue. I can also later on take a peek at the git history to see what other database changes may have occurred, but if you know any off the top of your head that have occurred in the last ~3 months, that would be awesome :P Don't go looking for it though, if you'll have to do that I can just do it myself, don't want you spending all this time on one guy

**Comment by marcelfolaron** [comment]
Hey, sorry for the delay. There are a couple queries you would need to execute. They are all in https://github.com/Leantime/leantime/blob/master/app/Domain/Install/Repositories/Install.php

Given that your db says you are currently on 2.1.16 you would need to execute the queries in methods:

update_sql_20117();
update_sql_20118();
update_sql_ 20120();
update_sql_20121();
update_sql_20122();

And then just update your version number to 2.1.22

**Comment by komali2** [comment]
Ok, I've done so, and then ran `INSERT INTO zp_settings (`key`, `value`) VALUES ('db-version', '2.1.22') ON DUPLICATE KEY UPDATE `value` = '2.1.22';`, and now login screen is visible. However, I'm getting unsecure form submission errors after inputting login information, so unfortunately I think we chased a rabbit hole here lol. I mean, at least my DB is updated at this point, but the original issue was probably more related to whatever mixed content HTTPS issues I was having :(
