### ISSUE TITLE
OPENID not working [BUG]

### ISSUE THREAD

**Issue by phancaovu** [Leantime/leantime#2009]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ ] Self Hosted

**Describe the bug**
I use version 2.4 beta
server setup apache
using Authentik authen

Leantime OPENID is not working, it is a problem with callback URL. In spite of the Authentik app notification success.

http://localhost:8081/oidc/callback?state=2287956a32513583b73f12d48a328910&session_state=0fd0d421-a0bf-43d9-9ad0-b22b090a5d5d&code=8085ef54-fd1b-4c0c-8024-6d8cae88bdd3.0fd0d421-a0bf-43d9-9ad0-b22b090a5d5d.e4956e15-4107-4726-9baa-e8ea0edff697

**To Reproduce**

**Expected behavior**

**Leantime Version**
Which Leantime version are you using

**Server**
Apache, nginx, IIS etc

**PHP / MySQL Version**
Please list the PHP and Mysql version you are using

**Additional context**

**Comment by eric-hansen** [comment]
What does your OpenID config in Leantime look like (masking any sensitive details)?

It took me a hot minute to get it working w/ Microsoft OIDC.

**Comment by marcelfolaron** [comment]
We'll need more information, where is it failing? Any errors in your logs/error.log ?

**Comment by aHugues** [comment]
Hi, it's lacking a bit in information, but looks a lot with an issue I've had with using Leantine with OIDC SSO. 

In my case the following happens: 
1. click on "connect using oidc"
2. get correctly redirected to the oidc provider
3. logins and authorize the app
4. get a "unsupported key format" message 

According to the [get_public_key](https://github.com/Leantime/leantime/blob/master/app/Domain/Oidc/Services/Oidc.php#L359) method, only two formats for the jwks endpoint are supported: 

- a map of strings (strings being the public keys)
- a map of object with the public key itself stored in the value `x5c`

However, many OIDC providers store the public keys as a map of objets, the public key being in the value `n`, which is explicitely marked as not supported in leantime. 

But that means I could not get it working with
- nextcloud
- gitea
- dex

Please also note [here](https://github.com/Leantime/leantime/blob/master/app/Domain/Oidc/Services/Oidc.php#L315) that only `RS256` is supported (that should be taken into consideration for the oidc provider config)

**Comment by phancaovu** [comment]
> We'll need more information, where is it failing? Any errors in your logs/error.log ?
> What does your OpenID config in Leantime look like (masking any sensitive details)?
> 
> It took me a hot minute to get it working w/ Microsoft OIDC.


in authentic app 
![image](https://github.com/Leantime/leantime/assets/66910370/f8975052-8ac4-4d4e-936e-da49bcd65a0a)

in .env file config 

LEAN_OIDC_ENABLE =true
LEAN_OIDC_CLIEND_ID =Tq7UOF9pMVQyE5PBXJ59HZtrGgMTN9TVwOUc8qNm
LEAN_OIDC_CLIEND_SECRET =tv2MRmWrzTLY6hEWcn26...

#AUTHENTIK
LEAN_OIDC_PROVIDER_URL =http://localhost:9000/application/o/leantimeit/
LEAN_OIDC_JWKS_URL_OVERRIDE =https://localhost/application/o/lean/jwks/
LEAN_OIDC_AUTH_URL_OVERRIDE =http://localhost:9000/application/o/authorize/
LEAN_OIDC_TOKEN_URL_OVERRIDE =http://localhost:9000/application/o/token/
LEAN_OIDC_USERINFO_URL_OVERRIDE =http://localhost:9000/application/o/userinfo/

**Comment by phancaovu** [comment]
> > We'll need more information, where is it failing? Any errors in your logs/error.log ?
> > What does your OpenID config in Leantime look like (masking any sensitive details)?
> > It took me a hot minute to get it working w/ Microsoft OIDC.
> 
> in authentic app ![image](https://user-images.githubusercontent.com/66910370/276847933-f8975052-8ac4-4d4e-936e-da49bcd65a0a.png)
> 
> in .env file config
> 
> LEAN_OIDC_ENABLE =true LEAN_OIDC_CLIEND_ID =Tq7UOF9pMVQyE5PBXJ59HZtrGgMTN9TVwOUc8qNm LEAN_OIDC_CLIEND_SECRET =tv2MRmWrzTLY6hEWcn26...
> 
> #AUTHENTIK LEAN_OIDC_PROVIDER_URL =http://localhost:9000/application/o/leantimeit/ LEAN_OIDC_JWKS_URL_OVERRIDE =https://localhost/application/o/lean/jwks/ LEAN_OIDC_AUTH_URL_OVERRIDE =http://localhost:9000/application/o/authorize/ LEAN_OIDC_TOKEN_URL_OVERRIDE =http://localhost:9000/application/o/token/ LEAN_OIDC_USERINFO_URL_OVERRIDE =http://localhost:9000/application/o/userinfo/



> We'll need more information, where is it failing? Any errors in your logs/error.log ?

**Comment by phancaovu** [comment]
????

**Comment by eric-hansen** [comment]
> ????

As requested, please provide the error(s) you are receiving.

If this is related to the issue that @aHugues mentioned then I can see if I can add support for this based on the provided list of apps.

But if the error is not related to this, then it may require a different course of action.

**Comment by marcelfolaron** [comment]
Please check in 2.4.5 again. A  few OIDC fixes made it in

**Comment by almereyda** [comment]
A similar issue about the way signing keys are handled in the OIDC implementation of Leantime just surfaced again:

- https://github.com/Leantime/leantime/issues/2088

**Comment by MIPMHannes** [comment]
> Please check in 2.4.5 again. A few OIDC fixes made it in

This issue stays the same even with 2.4.8. 
Instead of Authentik I use apereo cas. My IDP notifys me that SSO was succesfull but leantime does not let me login.

**Comment by cableman** [comment]
I have the same issue when trying to use OIDC with MS B2C connetions as https://github.com/Leantime/leantime/issues/2009#issuecomment-1772182782 have as it is not have the `x5c` field.

Also hits the `oidc.error.providerMismatch` which I am not sure why is needed :-) We normally use https://oauth2-client.thephpleague.com/ with our one "extension" - https://github.com/itk-dev/openid-connect

Also our connection string already has an `?` in the URL: 

`LEAN_OIDC_PROVIDER_URL = https://xxxx.b2clogin.com/xxxx.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_AAK_SIGNIN_OIDC_LEANTIMEITKDEVELOPMENT'`

This part is easily fixed in `buildLoginUrl()`, but not sure about the other parts the login process.

**Comment by jejbq** [comment]
If you have a redirection loop (in Authentik or your OIDC), try LEAN_OIDC_CREATE_USER : 'true' in Docker .env (not documented except #2313)
