### ISSUE TITLE
[BUG] Long project titles overflow

### ISSUE THREAD

**Issue by v-marinkov** [Leantime/leantime#2021]
Long project titles overflow on mouse hover.
![image](https://github.com/Leantime/leantime/assets/7135724/864eda1d-31a4-4f5c-969a-8fd2114e1358)

They should either be:
- on multiple lines by default
- automatically start horizontal scroll of the project name on hover
- have a little tooltip with the full name appear on hover

**Comment by marcelfolaron** [comment]
Fixed in 2.4.5
