### ISSUE TITLE
User Permission and levels

### ISSUE THREAD

**Issue by bluebrad** [Leantime/leantime#2023]
Still have the problem with user access. 
i set a user to company manager they should be able to edit current projects. but admins can make new ones. 
Editors should not see closed projects or at lease not be able to re open them. 
commenters should only have access to the projects on the menu panel and not see all projects 

![202310230824-1698074682](https://github.com/Leantime/leantime/assets/6026548/0d007270-a6a1-4e9a-bacb-1de02d348ebb)

![202310230824-1698074687](https://github.com/Leantime/leantime/assets/6026548/5f756f36-30bf-4ee7-93c5-497345f38661)

**Comment by marcelfolaron** [comment]
Actually, the company manager is allowed/supposed to be able to create new projects for the "client" they are assigned to. I will double check the other roles

**Comment by as1029** [comment]
Should a 'Editor' be able to see timesheets system wide? certainly the drop downs suggest they should

**Comment by bluebrad** [comment]
The user permissions should be a table
also you should be able to make your own user groups

[image: image.png]

Having a table where we can manage permissions under the system settings
for the users/groups
under the users it would only be the project managers and company / client
that would need to add and remove users from their currently viewed
project.
Also allow us to create teams/departments/user groups so we can set
permissions for that group. people managing there tasks should only see
there tasks
