### ISSUE TITLE
DS_store files left behind creating bugs

### ISSUE THREAD

**Issue by bluebrad** [Leantime/leantime#2024]
need to clean up the zips from mac os. 
it leaves behind .DS_store files all over the place. 
even creates a bug when you load menus

![202310230824-1698074647](https://github.com/Leantime/leantime/assets/6026548/b8a28a4a-cf97-4ea4-90e4-2c315f70d78b)
![202310230832-1698075148](https://github.com/Leantime/leantime/assets/6026548/4f72ffc4-d144-4d65-99f5-760b0863a53b)

**Comment by marcelfolaron** [comment]
It appears that these are actually left over from an old installation. The DS_Store files should not be in the package anymore as I am not building the release package from my mac anymore. You can safely remove them

**Comment by bluebrad** [comment]
Yes, i have removed them. was just letting everyone know.
keep in mind its also good practice to add an index.html to all empty
directories. and/ or .htaccess redirecting the directory from outside eyes.
The index.html should have the Meta redirect unless its from 127.0.0.1 this
way it allows system access but not remote access.
