### ISSUE TITLE
Editing timesheets invoiced & MGR approval

### ISSUE THREAD

**Issue by alexsynth** [Leantime/leantime#203]
Hi i've noticed theres an issue when editing the invoiced or mgr approval of timesheets. When you uncheck either of the box and save, it does not uncheck the box. You will have to sign out, login again and uncheck the box and it is now that you see that you can tick the box again

**Comment by marcelfolaron** [comment]
Hey, I was trying to reproduce but couldn't quite follow. 
Which version are you using? Which browser is that happening on?

**Comment by alexsynth** [comment]
I am using the latest beta version available. I use google chrome.

**Comment by marcelfolaron** [comment]
Thanks, I am still trying to reproduce that issue.
So I assume you are doing that through the main timesheets menunpoint on the right?

After opening one entry to edit the invoiced state and saving it, it shows up as checked again for you?

**Comment by alexsynth** [comment]
Correct! For it to get unchecked after saving it sometimes i have to re-login again and edit it again for it to appear unchecked. Now i've also found out it gets unchecked if you try to edit it again without loging in again. So the issue fluctuates.

**Comment by alexsynth** [comment]
If it helps, this is the version of chrome im using:

Version 80.0.3987.149 (Official Build) (64-bit)

Ill try to see if the issue persists in other browsers

**Comment by alexsynth** [comment]
Just to be clear when i say it appears "checked" you can still see the date under the invoiced heading and in the Edit window you still see the date as well as the tick in the box.

**Comment by marcelfolaron** [comment]
Ah I see, yes the dates are not cleared. That is a bug!

**Comment by alexsynth** [comment]
Thanks for notifying :)

**Comment by marcelfolaron** [comment]
Fixed in Beta 6
