### ISSUE TITLE
[BUG] OIDC - Newly created account - "editor" role not found

### ISSUE THREAD

**Issue by danielmichalichyn** [Leantime/leantime#2031]
Hello, 

When a user is automatically created using OIDC, and no role is configured on the auth/idToken, the default role causes the application to crash, upon further analysis, i've noticed that the "editor" role now have a value of "20" inside the DB, that is correct? If this is the expected behaviour i'm glad to open a PR for this fix.

https://github.com/Leantime/leantime/blob/6494f65bc53a38d776692af17a49d742c509b663/app/Domain/Oidc/Services/Oidc.php#L220C42-L221C1

![image](https://github.com/Leantime/leantime/assets/52325588/d1a80641-6dd4-40c9-8916-a6da6f519217)

**Comment by marcelfolaron** [comment]
Should be fixed in 2.4.5 You can now set the default role in the config. Please check the sample.env for the new variable name
