### ISSUE TITLE
[BUG] ERROR 500 after 2.4.2 update from 2.4.1

### ISSUE THREAD

**Issue by cliris** [Leantime/leantime#2034]
Hi,

Some pbs after the update from 2.4.1 to 2.4.2 but solved, i post here for helping only

1. In /config/configuration.php replace the old
`namespace leantime\core;`
by the new
`namespace Leantime\Config;`

2. Check the rights of file & folders, in my case I had some with root and www-data permissions :/
in leantime folder
`chown -R www-data *`
`chgrp -R ww-data *`

3. Do an update database
`./bin/leantime db:update`

4. Restart Apache
`sudo service apache2 restart`

This have fixed my problems

**What set up are you using**
* [x] Self Hosted

**Describe the bug**
Error 500 after 2.4.2 update from a 2.4.1 installation

**Server**
Apache

**PHP / MySQL Version**
PHP 8.1
MariaDB 10.5

**Additional context**
Debian 11

**Comment by marcelfolaron** [comment]
Any errors in logs/error.log?

**Comment by gloriafolaron** [comment]
To confirm, you posted this to share how you fixed it? 

Appreciate you doing that! We're on 2.4.4. now -- let us know if you have any similar issues when updating again.

**Comment by marcelfolaron** [comment]
Update to 2.4.4 and report back. Will close this for now
