### ISSUE TITLE
[BUG] DiscordHook - wrong ping people/channel format

### ISSUE THREAD

**Issue by Deerpfy** [Leantime/leantime#2035]
**What set up are you using**
* [x] Self Hosted

**Describe the bug**
If we would like to tag a person via discord format <@ID>, the embed message will look like this: 

```
PROJECTNAME
New comment in Task [XX] - TASKNAME
USER added a new comment to the Task 'TASKNAME':

“&lt;@306440035832561666&gt;”
```
It should look like this:

```
PROJECTNAME
New comment in task [XX] - TASKNAME
USER added a new comment to the task "TASKNAME":

"@Deerpfy"
```

**To Reproduce**
1. On the discord, right-click on the user.
2. Copy the USER ID
3. Go into a Leantime project
4. Open any task
5. Expand the comments section and type <@USERID> | It must be the USER ID of the discord, not Leantime!

Discord tagging works in 2 ways:
1. We know the nickname on the server, where we can put @NICKNAME and the person will be tagged
2. If we don't know the nickname, whereby for external purposes we use the USERID on discord, where the tagging works as follows <@ID>
With the **@** sign used to ping people and **&** to indicate channels.

**Expected behavior**
Embed Message should looks like this, if we would like to ping person with Task comments:
```
PROJECTNAME
New comment in task [XX] - TASKNAME
USER added a new comment to the task "TASKNAME":

"@Deerpfy"
```

**Leantime Version**
2.4.4

**Server**
apache 2.4

**PHP / MySQL Version**
PHP: 8.1
MySQL: MariaDB 10.7

**Additional context**
Any formatting editor for custom styling would help, via discordhook.
Image about the BAD embed message:
![image](https://github.com/Leantime/leantime/assets/47902435/40dabee8-a082-4fb9-b9bb-b0bcbe4f1ca7)

**Comment by marcelfolaron** [comment]
Thanks, we are still trying to figure out how to best escape the content to work for discord. I'll take another look
