### ISSUE TITLE
[BUG] "Getting started" links are broken

### ISSUE THREAD

**Issue by noamraph** [Leantime/leantime#2036]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [x] Cloud Hosted Version
* [ ] Self Hosted

**Describe the bug**
The "take me there" link under "describe your project" is broken. It links to https://noam.leantime.io/projects/showProject3 instead of https://noam.leantime.io/projects/showProject/3
![image](https://github.com/Leantime/leantime/assets/1553464/73941ae4-c541-4e29-b4c6-758ba3f3d8fa)

**To Reproduce**
I just logged in to a newly created workspace.

**Expected behavior**
The link should be to https://noam.leantime.io/projects/showProject/3

**Leantime Version**
v2.4.4
(It was very hard to find, the robot obscured it)

**Server**
Apache, nginx, IIS etc

**PHP / MySQL Version**
Please list the PHP and Mysql version you are using

**Additional context**

**Comment by gloriafolaron** [comment]
Ah, snap. Thanks for catching this! Marcel will take a look and get that corrected here as soon as possible.
