### ISSUE TITLE
[BUG] Regularly logged out for no reason

### ISSUE THREAD

**Issue by ybizeul** [Leantime/leantime#2044]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
During refresh when performing actions, leantime goes back to login page regularly
expiration is set to 28800 which should be 8 hours

**To Reproduce**
Basic deployment with helm chart, the database has been imported from a docker install though.

**Expected behavior**
There should not be redirect to login unless the expiration has been reached.

**Leantime Version**
v2.4.4

**Server**
Helm chart

**PHP / MySQL Version**
Helm chart

**Comment by marcelfolaron** [comment]
Are you by chance using Safari?
We have a few reports that Safari keeps logging out users.

**Comment by ybizeul** [comment]
I'm using Safari indeed ! Let me know if there is any output from safari console that might be useful

**Comment by marcelfolaron** [comment]
I am actually not quite sure why it’s happening. This seems to be a safari
problem only. There are some articles that having the developer console
open causes this issue but I wasn’t able to confirm that.
https://www.reddit.com/r/Safari/s/ZVterwDFGW

If you have any output that would be great. More than likely though safari
is deleting the session cookie for some odd reasons.
I am still doing research on settings to see if there is anything I can do
from the Leantime side.

**Comment by marcelfolaron** [comment]
Also found this
https://developer.apple.com/forums/thread/728137

**Comment by marcelfolaron** [comment]
It seems to be related to the cookie we are sending and safari not handling
it right. The bug was supposed to be fixed but that is not clear.
https://bugs.webkit.org/show_bug.cgi?id=255524

I’ll check for alternative solutions to the samesite attribute if possible

**Comment by marcelfolaron** [comment]
Nvm still active
https://bugs.webkit.org/show_bug.cgi?id=257845

**Comment by ybizeul** [comment]
Very interesting. For the records, I'm using Version 17.0 (19616.1.27.211.1)
I can live with that for now, it doesn't happen that often, hopefully you'll be able to find a workaround or Safari will get a fix.

I wonder if it would be related to my setup with Kubernetes as well (#2043)

Thanks !

**Comment by marcelfolaron** [comment]
Related: #2033

**Comment by marcelfolaron** [comment]
Closing this for now since there is not much we can do on our end

**Comment by ybizeul** [comment]
Well I'm glad 99.99% of the web has a solution for this at least ! I'd be glad to retry Leantime when it's usable in my context, but with the issue closed I can't even monitor future progress.
Thanks for looking into this anyways.
