### ISSUE TITLE
[BUG] small offset of text at first login to leantime

### ISSUE THREAD

**Issue by Stormfinger** [Leantime/leantime#2045]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Self Hosted

**Describe the bug**
hi i created account for my use and after seting up password and at first login i see that smal portion of text is not visible... im running latest firefox on mx-linux i have 24" monitor 

**To Reproduce**
create accoutn
login
See error at first page

**Expected behavior**
text should be fully visible

**Leantime Version**
Version 2.3.11

**Server**
nginx

**PHP / MySQL Version**

**Additional context**
![LeanTime](https://github.com/Leantime/leantime/assets/84122683/e467422c-c9b7-4714-aea2-94973e0e5f2b)

**Comment by gloriafolaron** [comment]
Thanks for reporting this. Could you try updating to the latest version (2.4.4) to see if this is still an issue?

**Comment by marcelfolaron** [comment]
Closing this for now as this is an old version
