### ISSUE TITLE
[BUG] Skip For Now Window - won't go away (Fatal - cannot use 2.4.7)

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#2067]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ X ] Self Hosted

**Describe the bug**
After a successful upgrade to 2.4.7 and after first successful login (LDAP), I get the following screen:
![image](https://github.com/Leantime/leantime/assets/121611/659e8ac2-3e27-466d-82ee-f27f992bcb21)
Whether I click "Skip for now", or provide a project name and click Next it fails with this log file error:
`[critical] Uncaught Error: Leantime\Domain\Projects\Services\Projects::isUserAssignedToProject(): Argument #2 ($projectId) must be of type int, string given, called in /SM_DATA/web_projects/public_html/app/Domain/Projects/Services/Projects.php on line 693
`

**To Reproduce**
1. Freshly Install 2.4.7 (same problem on upgrade or fresh install)
2. Login with a user that has no current projects created (mine is an LDAP user but may not be relevant)
3. You will be presented with a requirement to create a project or skip
4. Both will be unsuccessful and result in a log file error and return to the same screen or given an on screen "An error occured"
![image](https://github.com/Leantime/leantime/assets/121611/e7648cf7-f720-4ad7-b610-ed65bb673bc6)

**Expected behavior**
To allow skipping or creating of the first project

**Leantime Version**
2.4.7

**Server**
NGINX

**PHP / MySQL Version**
8.1 / Maria DB 10.4

**Additional context**
I am seeing this in the Linux log files:  
* Projects.php - $projectId - must be of type int, string given 

To make the problem more obvious, I have created a youtube video for you.
* https://www.youtube.com/watch?v=oiAm7GrSawc

Parts of this issue are very similar to an issue previously closed here:  https://github.com/Leantime/leantime/issues/1851 as I was getting an error screen there though for a slightly different reason but also related to no current projects.

I am suspecting this is unique to LDAP logins because otherwise you would have had to experience this problem by now.  At the very least I need a way to stop the nag screen about creating first projects so I can use the software.  Otherwise we are stuck.   We have experienced a similar problem with some earlier 2.4.x but were able to create a project to get past it.   The skip for now button should be our safe haven but throws the error and redirects us back again.

Thank you.

Sincerely,

Jay
CompuMatter / ServerMatter

**Comment by marcelfolaron** [comment]
Thank you for the report. I see the issue and will get a fix out.

**Comment by compumatter** [comment]
Great news. We're looking forward to trying out the later stuff

**Comment by compumatter** [comment]
Thank you Marcel.  Will check it out and give you feedback.
