### ISSUE TITLE
User rules issue

### ISSUE THREAD

**Issue by same7-abdel3aziz** [Leantime/leantime#207]
I can't add more rule with different permissions,

Examples:
1- I need to create a rule for someone who shouldn't edit/delete tasks.
2- Also if I need to add different rule with different permissions such as (designer, tester, UI, ..etc)

Thanks in advanced

**Comment by marcelfolaron** [comment]
Hi,
Thanks for reaching out. There is currently not a way to add rules via the UI. There are code changes you could make to allow restrictions but these are quite involved.

We are working on a new attribute based permission system and will release that later this year.
