### ISSUE TITLE
[BUG] updateLeantime.sh fails from 2.3.25 to 2.4.7 (includes my resolution experience)

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#2071]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ X ] Self Hosted

**Describe the bug**
When trying to use the automated bash script to upgrade from the command line, it fails at the point of backing up the database file.

**To Reproduce**
1. From command prompt at the Leantime base directory type:  . updateLeantime.sh

**Expected behavior**
I would expect it to pull existing credentials and other intel from the .env file and proceed through the finish line.

**Leantime Version**
2.3.25

**Server**
NGINX

**PHP / MySQL Version**
8.1 / 10.4

**Additional context**
To make my experience more clear I have created a video for you:
* https://www.youtube.com/watch?v=pBH9-Ff1fJU

**Comment by gloriafolaron** [comment]
Discussing with Marcel, it's unclear if the update script would have been impacted by some of the breaking changes that occurred in going from 2.3 to 2.4.

Can you verify that you updated the config and files mentioned in these:

https://github.com/Leantime/leantime/releases/tag/v2.4-beta

And

https://github.com/Leantime/leantime/releases/tag/v2.4-beta-2

And if so, any errors in the logs?  

Apologies if they're shown in the video as I'm not able to view it at the moment.

**Comment by compumatter** [comment]
I got your reply over here https://discord.com/channels/990001288026677318/1156490503362199642/1171215649570299997 
As for verifying configs are updated.  I have not been able to find the nginx location rule ie;

"If you are using nginx please use our updated nginx config (take note of the new location / {}"

Can you provide a link to that so I may have a look and see if it is different?

**Comment by marcelfolaron** [comment]
We are now using the leantime cli to update leantime: `php bin\leantime system:update` 
Closing this for now
