### ISSUE TITLE
[BUG] EDITOR Issue On User Confidential Info

### ISSUE THREAD

**Issue by as1029** [Leantime/leantime#2075]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X ] Self Hosted

**Describe the bug**
I have set up a test system with a few users, a few companies and a few projects.
One of the users is an 'EDITOR' and is a member of one team working on one project at one company.
If I log in as this user then when I try to edit company profile (should not even get the option?) - then as this user I select 
Company Management > All Projects 
      the result is a 403 Page not authorised - fair enough just not pretty

The ISSUE  is is this user select 
Company Management > All TimeSheets
the result is the time sheet view but the search is not restricted to the company and projects to which the user belongs/should have access to 
ALL companies AND ALL Projects And ALL Users appear in the various drop downs !

This is a problem if using in a multi client multi project environment

**To Reproduce**
See description

**Expected behavior**
1. NO 403 Page not authorised
2. User Should only have access to own time sheets? - management should see all for a company etc.

**Leantime Version**
Which Leantime version are you using : v2.4.2

**Server**
Apache2

**PHP / MySQL Version** (should not be relevant to above bug?)
PHP 8.1
Mysql -> Maria V - not sure

**Additional context**

**Comment by as1029** [comment]
Maria 11.1.2-MariaDB-1:11.1.2+maria~ubu2204 mariadb.org binary distribution

**Comment by marcelfolaron** [comment]
Thank you for pointing that out. That seems to be a bug indeed. The user should not even have access to the menu. I will take a look and check whats going on there.
