### ISSUE TITLE
Bug in class.loginInfo.php when setting $appUrl="https://..."

### ISSUE THREAD

**Issue by lamping7** [Leantime/leantime#208]
**Error**: `Notice: Undefined offset: 1 in /var/www/html/src/domain/general/controllers/class.loginInfo.php on line 45`
Version: 2.0.15
https://github.com/Leantime/leantime/blob/75aa49101e17e48f5dbb3217e7249ac70dcf7d45/src/domain/general/controllers/class.loginInfo.php#L45

Something goofy is going on in line 44, causing the error on line 45.

I'm specifying `$appUrl` as "https://leantime.me.someddns.com" in the config, using a `sed` replace in the docker containers `start.sh`, which I'm sending as an environment variable in the `docker run` command.

I'm not sure if the BASE_URL is wonky with an extra slash or something. I haven't debugged yet or tried the newer Beta.

**Edit**: Update: It appears that the `$url` in line 44 is without the `s` in `https://`. So, the `explode` doesn't "filter" out the `BASE_URL` as intended.

**Edit 2**: The problem is in resolving the protocol in `settings.php`:
https://github.com/Leantime/leantime/blob/75aa49101e17e48f5dbb3217e7249ac70dcf7d45/config/settings.php#L59

In my case, I'm using the docker container, with this on port 80 (as setup and not easily configurable), mapping to the host at a different port. Then I have a nginx reverse proxy for the subdomain. Anyways, the values of what is going on with the line above are `$_SERVER['HTTPS'] = NULL` and `$_SERVER['SERVER_PORT'] = 80`.

So, the value of `$protocol` is "http://", resulting in the incorrect return value from `getBaseURL()` and thus `getFullURL()`.

**Edit 3 / Workaround:** The easiest fix here is on the Docker end. Just use Port 443 so https is detected correctly. To do this, I had to edit `app.conf` over at https://github.com/Leantime/docker-leantime/blob/master/config/app.conf
1. Add the line: `Listen 443`
2. Change the Vhost port: `<VirtualHost *:443>`
3. Build the image. This wasn't a huge deal, as I already need to do this for the `$appUrl` substitution, adding this to `start.sh`: `sed -i 's#$appUrl = ""#$appUrl="'"${LEAN_APPURL}"'"#g' config/configuration.php` (Notice I used a different delimiter for `sed`. Obviously `https://` screws up the normal choice of using a slash. It caused me a minor hiccup. So, I wanted to point that out.)

I would consider this more of a workaround than a solution. It seems like a clunky way to manage https. If the app isn't to be fixed on how it detects https in `settings.php`, maybe make a easy way to configure the port with an env variable and process it in `start.sh`, like what seems to be the intent for `$appUrl` (see https://github.com/Leantime/docker-leantime/issues/8).

Also, feel free to edit the title to include the deeper problem and not the initial problem, which is more of symptom.

**Comment by marcelfolaron** [comment]
Hi, thank you for the report and the fixes/suggestions. You are right that use case is not well handled at the moment. I agree setting the protocol via config is probably the cleaner option. I'll add that to the next release.

**Comment by lamping7** [comment]
Are you thinking of following the approach here --> https://github.com/Leantime/leantime/pull/201 and adding an env config where a user can specify https?

**Comment by marcelfolaron** [comment]
Thank you for the PR, just merged it! I can see now how the handling of the CURRENT_URL definition created the issue!
