### ISSUE TITLE
[BUG] LDAP Profile Data Not Pulling In - 2.4.7

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#2080]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ X ] Self Hosted

**Describe the bug**
After login, LDAP users are missing important profile data (First Name and Phone Number) within their profile environments.  Last Name does pull in properly.

**To Reproduce**
1. Login as an LDAP user.  
2. Click the circular profile icon in the top right corner
3. You will see the Profile information is only partially populated

**Expected behavior**
We expect to see the First Name and Phone Number

**Leantime Version**
2.4.7

**Server**
NGINX

**PHP / MySQL Version**
8.1 / 10.4

**Additional context**
I have created a video to make the problem more clear to you:
* https://www.youtube.com/watch?v=cOC6kUQsbLg

**Comment by marcelfolaron** [comment]
Fixed in 3.1.0-beta
