### ISSUE TITLE
[BUG] Kanban view with groups, group spacing is set based on longest group -> excess whitespace

### ISSUE THREAD

**Issue by fmoledina** [Leantime/leantime#2082]
**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
When using groups in Kanban view, group spacing (i.e. space between the top of one group to the next) for all groups appears to be set based on the longest group. This results in smaller groups having lots of whitespace between them. Also, groups appear to dynamically increase in size as required to accommodate moving tasks between them, but they do not shrink. Ideally, group spacing can be variable based on the size of the group, and groups can dynamically grow and shrink in the Kanban view when adding/removing/moving tasks in groups.

**To Reproduce**
1. Create a project with 10 tasks, and 3 milestones. Assign the same status to each milestone.
2. Add 2 tasks to Milestone 1, 2 tasks to Milestone 2, and the rest to Milestone 3
3. View in Kanban mode, group by Milestone.
4. Observe excess whitespace.
5. In Milestone 3, distribute the tasks across other statuses.
6. Refresh the page
7. Observe reduced whitespace due to adjusted group spacing.

**Expected behavior**
The expected behavior is for group spacing to scale with the length of the status with the most tasks per group, likely with constant spacing between the last visible task and the top of the next group. The further expectation is that groups would automatically grow and shrink as necessary without refreshing as tasks are moved around between statuses and groups.

**Leantime Version**
Leantime v2.4.7

**Server**
Docker image: [leantime/leantime:2.4.7](https://hub.docker.com/layers/leantime/leantime/2.4.7/images/sha256-f4327024cbd0ba0b2caba729eeac3d447fcfc442641685e1a56e4b772db48fe9?context=explore)
Hosted behind Traefik. Docker image: [traefik:v2.10](https://hub.docker.com/layers/library/traefik/v2.10/images/sha256-9701f2c228e65fbaced54478b24f3953502192d396823ebdb2aa9b9e37b0e647?context=explore)

**PHP / MySQL Version**
PHP: built-in to Leantime Docker image
MySQL Docker image: [mysql:8.0](https://hub.docker.com/layers/library/mysql/8.0/images/sha256-fb3bd1a95fb7031940038d16b178be03c92f26e186bbeb69943b8a852746d392?context=explore)

**Additional context**
This bug behavior is also observed in the following scenarios:
* Grouping via priority
* Without the Traefik reverse proxy

**Photos**
![FireShot Capture 004 - Leantime - leantime-testing](https://github.com/Leantime/leantime/assets/17585204/9020bda6-525a-4226-894c-32f939bc1090)
![FireShot Capture 005 - Leantime - leantime-testing](https://github.com/Leantime/leantime/assets/17585204/baaa7972-063d-4c22-9e8a-5934c28b89ac)

**Comment by fmoledina** [comment]
As an update to anyone else experiencing this issue, I can confirm that it persists in 3.0.0-beta.

![3 0 0-beta-1](https://github.com/Leantime/leantime/assets/17585204/d7bd7efe-3a81-449f-a04a-91551a3373cf)
![3 0 0-beta-2](https://github.com/Leantime/leantime/assets/17585204/4e564441-6df1-4bd8-87b1-c90d56824322)

**Comment by marcelfolaron** [comment]
Fixed in 3.0.3
