### ISSUE TITLE
[BUG] Dark theme: text in dropdown boxes too dark

### ISSUE THREAD

**Issue by fmoledina** [Leantime/leantime#2086]
**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
When in Dark mode, text color for items in dropdowns is too dark.

**To Reproduce**
1. Change theme to _Dark_ in _Look & Feel_ settings.
2. View selections in any dropdown box in the interface.
3. Observe dark text for elements other than the one that the mouse hovers on.

**Expected behavior**
The text should be a lighter color to be more readable.

**Leantime Version**
Leantime v2.4.7

**Server**
Docker image: [leantime/leantime:2.4.7](https://hub.docker.com/layers/leantime/leantime/2.4.7/images/sha256-f4327024cbd0ba0b2caba729eeac3d447fcfc442641685e1a56e4b772db48fe9?context=explore)
Hosted behind Traefik. Docker image: [traefik:v2.10](https://hub.docker.com/layers/library/traefik/v2.10/images/sha256-9701f2c228e65fbaced54478b24f3953502192d396823ebdb2aa9b9e37b0e647?context=explore)

**PHP / MySQL Version**
PHP: built-in to Leantime Docker image
MySQL Docker image: [mysql:8.0](https://hub.docker.com/layers/library/mysql/8.0/images/sha256-fb3bd1a95fb7031940038d16b178be03c92f26e186bbeb69943b8a852746d392?context=explore)

**Additional context**
None

**Photos**
![Screenshot 2023-11-13 162053](https://github.com/Leantime/leantime/assets/17585204/e6d2ab61-59e9-4328-9dd9-844cdf807b45)

**Comment by gloriafolaron** [comment]
Thanks for sharing this! We're doing some redesign of dark mode and will make sure this gets caught in that.

**Comment by marcelfolaron** [comment]
Fixed in 3.0.0
