### ISSUE TITLE
[BUG] OIDC w/ GitLab: The format for the public signing key is not yet supported

### ISSUE THREAD

**Issue by almereyda** [Leantime/leantime#2088]
**What set up are you using**

Self Hosted

**Describe the bug**

When logging in with GitLab, an error is thrown:

> The format for the public signing key is not yet supported, check if your provider supports other jwks endpoints.

![Screenshot 2023-11-14 at 00-53-45 Allmende Lean](https://github.com/Leantime/leantime/assets/1645308/dfb674ef-85e2-43e1-9993-f47e36562302)

**To Reproduce**

1. Configure OIDC with GitLab
2. Click on "OIDC Login"
3. See error

**Expected behavior**

It is possible to login.

**Leantime Version**

2.4.7

**Server**

Docker

**PHP / MySQL Version**

Docker image / 8.2

**Additional context**

GitLab uses the `RS256` signing algorithm.

For reference:

- https://gitlab.com/.well-known/openid-configuration
- https://gitlab.com/oauth/discovery/keys

**Comment by almereyda** [comment]
The last time when this was seen, @aHugues made good observations in https://github.com/Leantime/leantime/issues/2009#issuecomment-1772182782.

**Comment by marcelfolaron** [comment]
This should be solved with: https://github.com/Leantime/leantime/pull/2747

**Comment by almereyda** [comment]
Very nice, thanks.
