### ISSUE TITLE
[BUG] When switching the language using the language option, the UI interface does not get translated as expected

### ISSUE THREAD

**Issue by luoguohua** [Leantime/leantime#2095]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ √] Self Hosted

**Describe the bug**
The UI interface cannot be switched to the corresponding language

**To Reproduce**

![image](https://github.com/Leantime/leantime/assets/29771475/3bbebc2e-50be-4a1b-9130-bbccfb17430a)

**Expected behavior**
Switch the UI interface to the corresponding language

**Leantime Version**
image: leantime/leantime:latest

**Comment by HillbertChan** [comment]
same question

**Comment by marcelfolaron** [comment]
Is that for all languages or just one particular one? Which language?

**Comment by Linkwenhao** [comment]
> Is that for all languages or just one particular one? Which language?是适用于所有语言还是仅适用于一种特定语言？哪种语言？

For me, the issue occurs with all languages. I am unable to switch languages successfully, regardless of which one I try.

**Comment by luoguohua** [comment]
> Is that for all languages or just one particular one? Which language?

Yes, this issue exists in all languages.

**Comment by marcelfolaron** [comment]
Fixed in 3.0.0
