### ISSUE TITLE
[BUG] Minor UI bug in landing page

### ISSUE THREAD

**Issue by darren-teo** [Leantime/leantime#2106]
**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
PHP print format displayed with **To-Dos This Week** on landing page after login.

**To Reproduce**
1. Login to Leantime.
2. Scroll down to **Your To-Dos**.
3. PHP print format, (%1$s), can be seen beside **To-Dos This Week** title.
![image](https://github.com/Leantime/leantime/assets/32067070/793bf19e-5f1d-4b45-9e5d-12c1fc774591)

**Expected behavior**
No PHP print format shown or the appropriate value shown instead of the print format.

**Leantime Version**
2.4.7

**Server**
Docker based installation

**PHP / MySQL Version**
MYSQL 8.1.0

**Comment by jontorrado** [comment]
Hi Darren,

I can't reproduce this bug. This is shown in my installation, also 2.4.7:

![bug](https://github.com/Leantime/leantime/assets/6916591/972990f2-873b-42ac-b7fe-57bc97f2307e)

I've also tried to find that string (%1$s) and this is a string only shown on My Timesheets, but it's correctly replaced after "dispatchTplFilter". Could you please give us more info?

**Comment by darren-teo** [comment]
Thank you @jontorrado. May I know specifically what further info you need?

**Comment by jontorrado** [comment]
Hi Darren,

No need, just found out that you are using en-GB instead of en-US and there are some translation errors, as seen in https://github.com/Leantime/leantime/issues/2101
