### ISSUE TITLE
[BUG] Upgrade from 2.4.5 to 2.4.7

### ISSUE THREAD

**Issue by bluebrad** [Leantime/leantime#2108]
when i try to migrate from 2.4.5 to 2.4.7 im getting this 500 error 
i am on CWP apachie 

HTTP 500 Internal Server Error
Plugin csvimport conflicts with domain
Exception
in[ /home/bbts/public_html/app/Core/Template.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)(line 194)

                    ]);
                $pluginPaths = collect(glob(APP_ROOT . '/app/Plugins/*'))
                    ->mapWithKeys(function ($path) use ($domainPaths) {
                        if ($domainPaths->has($basename = strtolower(basename($path)))) {
                            throw new Exception("Plugin $basename conflicts with domain");
                        }
                        return [$basename => "$path/Templates"];
                    });
                $_SESSION['template_paths'] = $domainPaths

in[ /home/bbts/public_html/vendor/illuminate/collections/Collection.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)-> Leantime\Core\{closure} (line 819)
Collection->mapWithKeys() in[ /home/bbts/public_html/app/Core/Template.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)(line 197)
in[ /home/bbts/public_html/vendor/illuminate/container/BoundMethod.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)-> setupBlade (line 36)
in[ /home/bbts/public_html/vendor/illuminate/container/Util.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm):: Illuminate\Container\{closure} (line 41)
in[ /home/bbts/public_html/vendor/illuminate/container/BoundMethod.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm):: unwrapIfClosure (line 93)
in[ /home/bbts/public_html/vendor/illuminate/container/BoundMethod.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm):: callBoundMethod (line 37)
in[ /home/bbts/public_html/vendor/illuminate/container/Container.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm):: call (line 661)
Container->call() in[ /home/bbts/public_html/app/Core/Template.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)(line 156)
Template->__construct()
in[ /home/bbts/public_html/vendor/illuminate/container/Container.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)-> newInstanceArgs (line 929)
in[ /home/bbts/public_html/vendor/illuminate/container/Container.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)-> build (line 770)
in[ /home/bbts/public_html/vendor/illuminate/container/Container.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)-> resolve (line 706)
in[ /home/bbts/public_html/vendor/illuminate/container/Container.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)-> make (line 1043)
in[ /home/bbts/public_html/vendor/illuminate/container/Container.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)-> resolveClass (line 959)
in[ /home/bbts/public_html/vendor/illuminate/container/Container.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)-> resolveDependencies (line 920)
in[ /home/bbts/public_html/vendor/illuminate/container/Container.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)-> build (line 770)
in[ /home/bbts/public_html/vendor/illuminate/container/Container.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)-> resolve (line 706)
Container->make() in[ /home/bbts/public_html/app/Core/Frontcontroller.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)(line 120)
Frontcontroller::executeAction() in[ /home/bbts/public_html/app/Core/Frontcontroller.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)(line 74)
Frontcontroller::dispatch() in[ /home/bbts/public_html/app/Core/Bootloader.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)(line 368)
Bootloader->handleRequest() in[ /home/bbts/public_html/app/Core/Bootloader.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)(line 165)
Bootloader->boot() in[ /home/bbts/public_html/public/index.php ](file:///X:/Desktop/Plugin%20csvimport%20conflicts%20with%20domain%20(500%20Internal%20Server%20Error).htm)(line 14)

**Comment by marcelfolaron** [comment]
Please make sure to run a clean update or remove the csvInport folder from
plugins. This was moved to core

**Comment by bluebrad** [comment]
TY
ill try that this weekend and respond with the test results .

**Comment by marcelfolaron** [comment]
Did that work?

**Comment by bluebrad** [comment]
just completed it .
yes it worked.
but the css is still bugged on the time tracking for the task card.
[image: image.png]

**Comment by marcelfolaron** [comment]
Is this still an issue or were you able to resolve?

**Comment by bluebrad** [comment]
still on 2.4.5 could not get a stable install to 2.4.7 i gave up do to its
all working but the one section in the task card.

**Comment by marcelfolaron** [comment]
Understood. I am working on 3.0 which will come with a lot of improvements. Beta is going out soon and I can let you know once we are stable.
