### ISSUE TITLE
Remove codesniffer

### ISSUE THREAD

**Issue by marcelfolaron** [Leantime/leantime#2128]
See https://github.com/squizlabs/PHP_CodeSniffer/issues/3932

Project is abandoned. We are using php standards already. Need to go all in.

**Comment by jrfnl** [comment]
Thank you for your support and your enthousiasm embracing the take-over of the PHP_CodeSniffer package.

In contrast to earlier information, arrangements are now being made to allow the package to continue under its original name on Packagist. The commit (in the new repo) to rename the package [has been reverted](https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/135).

Sorry for the confusion and thank you for understanding. I hope you'll enjoy the 3.8.0 release, which I expect to release this Friday.

**Comment by marcelfolaron** [comment]
Thank you @jrfnl . Appreciate the update and all the work you are doing!
