### ISSUE TITLE
Fatal Error with Slack Integration

### ISSUE THREAD

**Issue by jp-san-gabriel** [Leantime/leantime#213]
Hi, I get this error everytime I add a todo.  This started happening after I added a slack webhook to my project.  This error appears for that particular project only:

`Fatal error: Uncaught Error: Call to undefined function leantime\domain\services\curl_init() in /var/www/html/src/domain/projects/services/class.projects.php:177 Stack trace: #0 /var/www/html/src/domain/tickets/controllers/class.showKanban.php(82): leantime\domain\services\projects->notifyProjectUsers('JEAN PAUL added...', 'A new To-Do was...', '4', Array) #1 /var/www/html/src/core/class.frontcontroller.php(168): leantime\domain\controllers\showKanban->run() #2 /var/www/html/src/core/class.frontcontroller.php(107): leantime\core\FrontController->executeAction('tickets.showKan...') #3 /var/www/html/src/core/class.application.php(71): leantime\core\FrontController->run() #4 /var/www/html/public/index.php(31): leantime\core\application->start() #5 {main} thrown in /var/www/html/src/domain/projects/services/class.projects.php on line 177`

**Comment by marcelfolaron** [comment]
Hi,

Seems like the curl extension is not installed.

On Ubuntu just execute

`sudo apt-get install php-curl`

Let me know if that works.

Sincerely,
Marcel

**Comment by jp-san-gabriel** [comment]
Yes, that fixed the issue.  Thanks!
