### ISSUE TITLE
[BUG] OIDC regression on upgrade 2.4.7 -> 2.4.8

### ISSUE THREAD

**Issue by RagingCub** [Leantime/leantime#2139]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [x] Self Hosted

**Describe the bug**
When upgrading to version `2.4.8`, (or tag `latest` for the docker image as of December 11th 2023) the OIDC login doesn't work with json response:
```
{
  "error": "invalid_client",
  "error_description": "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). The requested OAuth 2.0 Client does not exist."
}
```

The issue isn't present on version `2.4.7`

**To Reproduce**
1. Go to main page
2. Click on 'OIDC Login'

**Expected behavior**
Should login without problems

**Leantime Version**
`2.4.8`

**Server**
Using docker image leantime/leantime

**Additional context**
When this kind of regression happens on minor or patch releases, is it safe to rollback to the previous working version?

**Comment by EHRETic** [comment]
Hi there,

I was struggling implementing Oauth with Authentik in my environnement and I found your issue.
I tried to revert from 2.4.8 to 2.4.7 and it worked straight away.

What I noticed is the URL generated after clicking on OIDC login button is missing the client ID:
![image](https://github.com/Leantime/leantime/assets/28634810/d33fcc91-1e59-4235-a144-48dc34183a1b)

But adding it manually in URL still fails afterwards (might be missing somewhere else in the code).

@marcelfolaron can you check if there is something missing in code generating the URL? It looks like the client_id is not passed  somewhere.

Hopefully, it is an easy fix 😉

**Comment by marcelfolaron** [comment]
Hey all,

Please make sure to update the config. There was a typo in the client_id variable name (it was called clienD_id). That was changed in the latest version

**Comment by RagingCub** [comment]
> Hey all,
> 
> Please make sure to update the config. There was a typo in the client_id variable name (it was called clienD_id). That was changed in the latest version

That solved it thanks!

**Comment by EHRETic** [comment]
> Hey all,
> 
> Please make sure to update the config. There was a typo in the client_id variable name (it was called clienD_id). That was changed in the latest version

Thanks a lot Marcel, it work for me too.

I can not believe I looked at my typo 100 times and didn't see it! 😁
(but the typo was in the doc... that's my excuse!)

**Comment by yunylz** [comment]
> Hi there,
> 
> I was struggling implementing Oauth with Authentik in my environnement and I found your issue. I tried to revert from 2.4.8 to 2.4.7 and it worked straight away.
> 
> What I noticed is the URL generated after clicking on OIDC login button is missing the client ID: ![image](https://private-user-images.githubusercontent.com/28634810/293939201-d33fcc91-1e59-4235-a144-48dc34183a1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzQwNjAsIm5iZiI6MTcxMzc3Mzc2MCwicGF0aCI6Ii8yODYzNDgxMC8yOTM5MzkyMDEtZDMzZmNjOTEtMWU1OS00MjM1LWExNDQtNDhkYzM0MTgzYTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA4MTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyM2E3ODFhNDYxYWM3NWQ0ZDEyM2QyMGM3MmVlYTUwOTgxODUwMmM0YWZkZGFhYTk5M2EyMmY1MGIzNmEzYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.flaozfgyom8a4TIrFtlRL5PXrrO7mdtkkNj0Udw9fSk)
> 
> But adding it manually in URL still fails afterwards (might be missing somewhere else in the code).
> 
> @marcelfolaron can you check if there is something missing in code generating the URL? It looks like the client_id is not passed somewhere.
> 
> Hopefully, it is an easy fix 😉

this issue still occurs in leantime:latest with docker compose. i'm using authentik and i get the same error
<img width="601" alt="Screenshot 2024-04-22 11 16 44" src="https://github.com/Leantime/leantime/assets/32681723/45495e9a-6f12-4699-9f9c-d9c2752f3d36">
