### ISSUE TITLE
Sweep: Refactor bind function in LDAP.php to concatenate username with ldap_domain when AD ist used

### ISSUE THREAD

**Issue by arminarmin** [Leantime/leantime#2140]
### Details

Hi,
first please change the usenrame to username in line 140.
on line 144 the function only uses the username for the bind. In some cases it needs to concatenate the username with the ldap-domain like you can see in line 149 but even if it uses AD to authenticate. 
My preffered way would be to try the bind with username and password and if it fails then try the bind with username concatenated with the ldap-domain.

Regards,
Armin

**Comment by marcelfolaron** [comment]
If you set the config ldapType to AD it should do exactly as you suggested. https://docs.leantime.io/#/installation/configuration?id=ldap-configuration Let me know if that doesn't work

**Comment by marcelfolaron** [comment]
Will close this issue for now. If you are still running into it please reopen
