### ISSUE TITLE
[BUG] starting timer errors with 404

### ISSUE THREAD

**Issue by nebulade** [Leantime/leantime#2146]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted (on Cloudron)

**Describe the bug**
When attempting to start a timer for timetracking, the browser issues a `PATCH /hx/timesheets/stopwatch/start-timer/` which results in a 404 response.

Coming from https://github.com/Leantime/leantime/blob/master/app/Domain/Tickets/Templates/partials/timerLink.blade.php#L14 and assuming it should hit the REST handler at https://github.com/Leantime/leantime/blob/master/app/Domain/Timesheets/Hxcontrollers/Stopwatch.php#L78

For a start I don't quite know the frameworks involved here, so my assumption might be wrong.

The app is running on apache and otherwise routes are fine.

I have set `LEAN_DEBUG = 1` but there is nothing in the error logs or otherwise to be seen in the app, maybe I have missed some other env variable to add more debug output? Is there any good place to start debugging this further?

**Leantime Version**
v2.4.8

**Server**
Apache

**PHP / MySQL Version**
PHP 8.1.2
MySQL 8

**Comment by marcelfolaron** [comment]
Hi all, 

We have seen this a couple times now and it has been difficult to reproduce.
 
One Option we know of is that the PATCH method might be disabled on some server environments. 
Please check if your server allows GET, POST, DELETE & PATCH methods. 

Please let me know if you find any other errors or issues that could help debug this.

**Comment by nebulade** [comment]
Unfortunately `PATCH` does work as far as I can tell. The apache config is quite basic in our case https://git.cloudron.io/cloudron/leantime-app/-/blob/main/apache/leantime.conf?ref_type=heads

**Comment by poetaster** [comment]
I also get patch errors on apache (mod php8.2)
```
XHRPATCH
https://domain.name/hx/projects/checklist/update-subtask/
[HTTP/2 404  65ms]
```

**Comment by xJakalx** [comment]
Hey guys think i figured this one out, I was able to reporoduce this by uninstalling php-fpm module, then apache config doesnt know how to nadle the PATCH request to the system appropriatly. The PHP-FPM Requirement is definatly a need here. for those experienceing the same thing please confirm you have php-fpm installed and the apache host files are proxing accross it. 

I was able to test with php7.4 php8.0 php8.1 and php8.2 and confirmed this was the case :)

Happy coding all :)

**Comment by poetaster** [comment]
Ok, I can confirm that this is a monolith apache. I'll switch to fpm. Thanks!

**Comment by xJakalx** [comment]
> Ok, I can confirm that this is a monolith apache. I'll switch to fpm. Thanks!

No problem :)
