### ISSUE TITLE
[BUG] Getting this on fresh install

### ISSUE THREAD

**Issue by Yacine-Eljazairi** [Leantime/leantime#2149]
Getting this on fresh install:

![image](https://github.com/Leantime/leantime/assets/133384188/9a45cfc0-cee2-4be8-8039-6720ff6b8247)

WTF?

**Comment by marcelfolaron** [comment]
What version are you using? Are you installing via docker or is this a regular install? Any errors in your error log?

**Comment by x99percent** [comment]
Seeing the same error on 2.4.8 and 3.0.0.  No errors in the container log.

**Comment by marcelfolaron** [comment]
This is now fixed in 3.0.5
