### ISSUE TITLE
The requested URL /install was not found on this server.

### ISSUE THREAD

**Issue by phillipm2001** [Leantime/leantime#215]
Hi,

I am trying to install Leantime under localhost. I have placed the leantime directory in the www directory. When I point to localhost/leantime/install I get a page headed Drive Impact, which invites me to install login credentials. After I do this, the get Not Found, The requested URL /install was not found on this server. Any help would be appreciated.
![leantime](https://user-images.githubusercontent.com/20366121/79816382-751fc100-83c6-11ea-98d5-9b14df601940.JPG)

**Comment by marcelfolaron** [comment]
Hi, 

Seems like there are a couple of things going on:

1. Did you use a release package or clone from master? If you cloned from master you will need to build the dependencies

For PHP
```composer install```

For the javascript packages
```npm install```

and then to build the files
```
./node_modules/grunt/bin/grunt Build-All
```

The latest release packages contain all of these files already. 

2. Seems like you are going with a subfolder installation? Please make sure to uncomment line 4 in public/.htaccess/

```
#RewriteBase /leantime/
```

Once all of that is done you should be able to run the installation without a problem

**Comment by phillipm2001** [comment]
I am a bit of a novice so I think I would struggle with NPM and building files although I am willing to try.

In the past I have installed WordPress on localhost, configured the Mysql database and have had no issues. I thought I could do the same with Leantime.

With Leantime, I downloaded the files, installed them in a directory, installed a Mysql database (I am running WAMP) changed the configuration files with the Mysql details but that is as far as I could go. 

All the .htaccess file says is: 

RewriteEngine On
RewriteRule ^(.*)$ public/$1 [L]

Thanks for your prompt reply.

**Comment by phillipm2001** [comment]
Forgot to answer your question: This is where I got the release package from **Installation (Production)**

**Comment by marcelfolaron** [comment]
No problem, the goal is to make Leantime as easy to install as possible.

First let's make sure you downloaded the right package. I suggest
downloading the 2.1 beta zip file from our website.  It contains everything
you need. https://leantime.io/download/

Unzip everything into your local directory.

Then navigate to leantime/public/ and open the .htaccess file
This is the file that will contain the commented rewrite rule.

Then make sure your configuration.php is still filled out. In there make
sure to set appURL to http://localhost/leantime

After that you should be able to open localhost/leantime/install and see
the (nicely formatted) installation page

**Comment by phillipm2001** [comment]
Hi Marcel,

It works. Thank you. What I did: 

I deleted the files that I had downloaded before. I went to the page you indicated and downloaded the latest _stable_ release. Last time, I downloaded the latest release, rather than the latest stable release.

I renamed the config file and entered the database credentials. This time I entered the appURL to http://localhost/leantime, as you suggested. I didn't do that before. 

Thanks for your help. I appreciate it.

**Comment by marcelfolaron** [comment]
Great, glad it worked. Let me know if you have any other questions!

PS: We have a new community forum. Sign up to get the latest news and ask
questions about Leantime and project management.
Https://community.leantime.io <https://community.leantime.io/>
