### ISSUE TITLE
[BUG] End date before start date possible

### ISSUE THREAD

**Issue by wunschadresse** [Leantime/leantime#2151]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [x] Cloud Hosted Version
* [ ] Self Hosted

**Describe the bug**
Apparently it is possible to save an end date that is before the start date.
This leads to issues, e.g. in the timeline view.

**To Reproduce**
see above

**Expected behavior**
An error should be issued, if end date < start date

![grafik](https://github.com/Leantime/leantime/assets/38276651/4227c583-22d3-40b1-b0d7-dcba973b4add)
![grafik](https://github.com/Leantime/leantime/assets/38276651/a6eef143-ceaa-4856-b99a-2f6c70b8f537)

**Comment by marcelfolaron** [comment]
Fixed in 3.0.0
