### ISSUE TITLE
[BUG]start work for time tracking inan task does'nt work

### ISSUE THREAD

**Issue by gerardgn** [Leantime/leantime#2154]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [X ] Self Hosted in a docker

**Describe the bug**
When  I open a task and I go to the Time tracking view. In the 3 dots menu, the 'Start work' doesn't start the timer.

**To Reproduce**
1. Go to a task
2. Click on the Time tracking view
3. click on the 3 dots menu
4. Click on 'Start work'
5. The timer does'nt start

**Expected behavior**
I expect the timer start with the type of tacking choosen in the Type list. When I want to stop the timer, the 3 dots menu display 'Stop work at...' like it does when I start a task in the Kanban view

**Leantime Version**
2.4.7
**Server**
Apache

**PHP / MySQL Version**
PHP: 8.1.25
Mysql : 8

**Comment by niloc-ray** [comment]
Im also having the same issue, the request get 404 not found error and PATCH requests do work.

**Comment by poetaster** [comment]
Ditto here.
```
XHRPATCH
https://lean.veritably.ai/hx/timesheets/stopwatch/start-timer/
[HTTP/2 404  64ms]

```


Leantime Version
2.4.8
Server
Apache2.4

PHP / Maria Version
PHP: 8.2 (mod-php8.2)
MariaDB : 10.5

**Comment by poetaster** [comment]
I also created a test page in a subdir ( public/test) with a bare bones htmx form handling example. PATCH is no problem:

```
2a01:4f9:3a:2414::6 - - [12/Jan/2024:13:25:54 +0100] "GET /favicon.ico HTTP/1.1" 404 886 "https://lean.veritably.ai/test/fp.php" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0"
2a01:4f9:3a:2414::6 - - [12/Jan/2024:13:26:20 +0100] "PATCH /test/fpost.php HTTP/1.1" 200 493 "https://lean.veritably.ai/test/fp.php" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0"
```

**Comment by marcelfolaron** [comment]
Thanks for the logs, this is super helpful.

I just realized that XmlHttpRequests are handled differently in Apache than
regular HttpRequests.

The failing request is done via XHR while your test was a regular
httpRequest.

I’ll have to do more research to figure out where this needs to be fixed
(Leantime vs Apache).

If anyone knows about the intricacies of these 2 request types please let
me know :)

**Comment by marcelfolaron** [comment]
Do you all see any cors issues with that 404?

**Comment by poetaster** [comment]
I don't have any security errors: The error on timer start is the same one as on setting project attributes :
from the dev console
```
XHRPATCH
https://lean.veritably.ai/hx/projects/checklist/update-subtask/
[HTTP/2 404  60ms]
```
followed by
```
Response Status Error Code 404 from https://lean.veritably.ai/hx/projects/checklist/update-subtask/ htmx.min.js:1:25780
```

Same as start timer:
```XHRPATCH
https://lean.veritably.ai/hx/timesheets/stopwatch/start-timer/
[HTTP/2 404  62ms]
```
```
Response Status Error Code 404 from https://lean.veritably.ai/hx/timesheets/stopwatch/start-timer/ htmx.min.js:1:25780
```

**Comment by poetaster** [comment]
In my tests in a subdirectory of leantime I'm using [https://unpkg.com/htmx.org@1.9.3](view-source:https://unpkg.com/htmx.org@1.9.3) and a simple:

```

    <form
        hx-patch="fpost.php"
        hx-target="this"
        hx-swap="innerHTML"
    >
```

And I grab PATCH with:
```
parse_str(file_get_contents('php://input'), $_PATCH);
```

**Comment by poetaster** [comment]
I'm not sure how this is supposed to work. I'f I'm not off, you're using jsonrpc. It does not support patch:
Domain/Api/Controllers/Jsonrpc.php:
```
146 is function patch() which always causes and error since only POST/GET are supported.
```

That's having looked where the getMethod used for parsing is located. Maybe there is another one?

**Comment by poetaster** [comment]
Ok, last bit of input, I changed:

Domain/Timesheets/Hxcontrollers/Stopwatch.php

to allow post and

Tickets/Templates/partials/timerLink.blade.php

to use hx-post.

No difference.

**Comment by marcelfolaron** [comment]
Thank you, that is interesting. That would have been my silver bullet. It’s
odd that it’s working here and on our Saas production server.

**Comment by poetaster** [comment]
> It’s odd that it’s working here and on our Saas production server.

Can you share a bit about the setup? nginx? is the config like the example.conf you supply? 

I've done the extra websockets connection stuff in ha-proxy (there are a lot of different apps behind this proxy cluster), but that does not seem relevan.

**Comment by marcelfolaron** [comment]
Yeah, our SaaS environment is using nginx on AWS. Nothing particularly special there except our account management. 
Locally I work with a mamp apache environment on mac. So far I have not been able to replicate the issue which is a little difficult in terms of debugging :) 

My local htaccess is the one in master so:

```
Options +FollowSymLinks
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]
```

and config in mamp is 
<img width="569" alt="image" src="https://github.com/Leantime/leantime/assets/47038998/00a4c735-6350-46cf-b2d1-e28b59858b7e">

**Comment by poetaster** [comment]
Ah, ok. Interesting. There is nothing in the nginx config that suggests anything. I'll keep digging a bit. Might take a couple of days.

**Comment by broskees** [comment]
404 being the response here and not 500 is very surprising to me. Could you turn the LEAN_DEBUG .env variable to true and try again? I would like to see the full stack trace if there is one.

**Comment by poetaster** [comment]
> @poetaster 404 being the response here and not 500 is very surprising to me. Could you set `LEAN_DEBUG=true` in your .env file and try again? I would like to see the full stack trace if there is one.

I'm using the configuration.php file not the env file. In the config file I have
```
public $debug = 1;
