### ISSUE TITLE
Fallback to english when a string is missing

### ISSUE THREAD

**Issue by EduFdezSoy** [Leantime/leantime#216]
when a translation is missing it shows the key now  
![image](https://user-images.githubusercontent.com/2505358/79846597-ed828400-83be-11ea-810e-6f43341df316.png)

**Comment by marcelfolaron** [comment]
Good point, we should fall back to english.

**Comment by gonztirado** [comment]
Also, we can complete the Spanish translations. Are you choose a platform for doing this translation. lokalise.com is free for open source projects. I think I comment crowdin.com previously, but I have been used Lokalise for another project with better results  :)
