### ISSUE TITLE
BUG - time graph in task timesheet

### ISSUE THREAD

**Issue by EduFdezSoy** [Leantime/leantime#217]
Look at this 

![image](https://user-images.githubusercontent.com/2505358/80083898-6cf68b80-8556-11ea-893d-4ed45fae7016.png)

**Comment by EduFdezSoy** [comment]
Version 2.1 - Beta 6

**Comment by marcelfolaron** [comment]
Hey, thanks for the report. Will take a look. I assume you are referring to the plan hours graph going up...

**Comment by EduFdezSoy** [comment]
yes, looks like something is wrong

**Comment by EduFdezSoy** [comment]
v2.1.1 
still going up
![image](https://user-images.githubusercontent.com/2505358/81393123-11b0c580-9120-11ea-944e-b3b6bd0d6580.png)

**Comment by EduFdezSoy** [comment]
@marcelfolaron

**Comment by marcelfolaron** [comment]
Can you try clearing your browser cache and try again? This was a
javascript error but should be fixed.

**Comment by EduFdezSoy** [comment]
still the same @marcelfolaron
