### ISSUE TITLE
[BUG] Updating Status in Tableview Does Not Trigger Webhook

### ISSUE THREAD

**Issue by typkrft** [Leantime/leantime#2171]
**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
When moving between statuses in the kanban view a webhook for, in my case, discord is triggered. When updating a status in the table view a webhook is not triggered. 

**To Reproduce**
1. Create Discord Integration
2. Go to Table View of Project
3. Create a task 
4. Webhook Fires
5. Change Status Webhook does not fire
6. Go to Kanban and Change Column
7. Webhook Fires

**Expected behavior**
We work almost exclusively from the table view. This would be a nice feature, assuming it isn't a bug.

**Leantime Version**
sha256:1b69a5208579aacc11b2937e1328281c2df2b3dfc037bdf58ef7f13cef6c8fa9

**Server**
Traefik

**PHP / MySQL Version**
PHP is whatever is in the current docker container and mysql is docker tag 8

**Comment by marcelfolaron** [comment]
This should be fixed as of 3.0.4
