### ISSUE TITLE
Time fields not being saved when creating new To-Do

### ISSUE THREAD

**Issue by alejodan** [Leantime/leantime#2172]
I am using version v2.4.8 of Leantime, which was installed on my local server using Docker containers. 

When I create a new To-Do and enter the start, end, and due dates and times, the time fields do not get saved. I have tried entering the times in various formats, but the result is always the same. The date fields are saved correctly, but the time fields are blank when I save the To-Do. 

This is causing problems with scheduling and tracking my tasks. Please let me know if there is a workaround or fix for this issue.

**Comment by TheMatzy** [comment]
Same issue here at Leantime v3.0.2

**Comment by Nom4** [comment]
Same here with latest v3.0.2.
Thanks

**Comment by marcelfolaron** [comment]
Fixed in 3.0.3

**Comment by Nom4** [comment]
Thanks, that works fine !
