### ISSUE TITLE
installation impossible

### ISSUE THREAD

**Issue by mingus52** [Leantime/leantime#218]
Hi,

I'm trying to install leantime on a lxc container with the last beta.
I've dowmloaded the *.zip file.

The apache server is running correctly and i've activated the "rewrite mod"

The default 000-default.conf have for Document Root this value "DocumentRoot /var/www/leantime/public
"

but when i'm am tring to access to:

http://leantime.domain.xxx i've this error:

`appUrl) && $config->appUrl != ""){ define('BASE_URL', $config->appUrl); define('CURRENT_URL', $config->appUrl.$settings->getRequestURI()); } else{ define('BASE_URL', $settings->getBaseURL()); define('CURRENT_URL', $settings->getFullURL()); } $login = leantime\core\login::getInstance(leantime\core\session::getSID()); ob_start(); $loginContent = ''; if($login->logged_in()!==true){ $loginContent = ob_get_clean(); ob_start(); } //Bootstrap application $application = new leantime\core\application( new leantime\core\config(), $settings, $login, leantime\core\frontcontroller::getInstance(ROOT), new leantime\core\language(), new leantime\domain\services\projects(), new leantime\domain\repositories\setting()); $application->start(); if(ob_get_length() > 0) { ob_end_flush(); }`

Do you have an idea ?

**Comment by mingus52** [comment]
Oops, i forgot to install php7.2

**Comment by mingus52** [comment]
I've still a problem the url http://leantime.domain.tld/install is not found

I don't understand why i've this error

**Comment by mingus52** [comment]
UPDATE:

I've this error on http://leantime.domain.tld
`Fatal error: Uncaught Error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /var/www/leantime/src/core/class.db.php:86 Stack trace: #0 /var/www/leantime/src/core/class.db.php(104): leantime\core\db->__construct() #1 /var/www/leantime/src/core/class.login.php(131): leantime\core\db::getInstance() #2 /var/www/leantime/public/index.php(19): leantime\core\login->__construct('b344cecd03c7fe8...') #3 {main} thrown in /var/www/leantime/src/core/class.db.php on line 86`

I still don't have procedeed the installation with http://leantime.domain.tld/install because the page is not found

**Comment by marcelfolaron** [comment]
Hey,

That last error means you don't have the mysql module enabled in PHP.

**Comment by mingus52** [comment]
Yes i forgot do add in 000-default.conf
`<Directory /var/www/leantime/public>
            AllowOverride All
</Directory>
`
But i still have de first error.

Thanks you for your reply

**Comment by mingus52** [comment]
Okay it's php7.3-mysql, it was not installed.

**Comment by marcelfolaron** [comment]
Did you install the mysql module? It should be working once that is done.

**Comment by mingus52** [comment]
yes indeed, that's work now :)

**Comment by marcelfolaron** [comment]
Great, glad it's resolved.
