### ISSUE TITLE
[BUG] FatalError : Compile Error in Mailer.php

### ISSUE THREAD

**Issue by hashfunktion** [Leantime/leantime#2195]
**What set up are you using**
* [x ] Self Hosted

**Describe the bug**
If it comes to an action where an email should be send, the error occurs.

**To Reproduce**
1. Create a new Project
2. On Save the error happens

or try to add someone new to a Project.

```
FatalError
Symfony\Component\ErrorHandler\Error\FatalError:
Compile Error: A function with return type must return a value (did you mean "return null;" instead of "return;"?)

  at /var/www/html/app/Core/Mailer.php:266

```

**Expected behavior**
I can create new Projekts (in best case the Mail is sent)

**Leantime Version**
3.0.0-beta

**Server**
Docker-Image with mysql

BR
Hashfunktion

**Comment by as1029** [comment]
Hi
I changed the return value to null ?? this got rid of the compile error you note


   return  null; //$filteredValue; // andy


on line 266
