### ISSUE TITLE
[BUG] V3.0.0-beta dark theme causes readability issues

### ISSUE THREAD

**Issue by BossMBGaming** [Leantime/leantime#2208]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted (Docker)

**Describe the bug**
The Description Text Box, has a background color which is causing readability issues if dark mode is enabled.

**To Reproduce**
1. Go to 'any place that has a description box' i.e. an individual to-do (pictured below) or project creation page.
2. Click on description box in the case of an individual to-do event.
3. See error.

![image](https://github.com/Leantime/leantime/assets/49920384/bc85c180-6581-49e6-9023-07520d8f8d97)

**Expected behavior**

**Leantime Version**
I am using v3.0.0-beta

**Server**
Docker Host - Ubuntu 22.04.3

**PHP / MySQL Version**
PHP - 8.1.27
MySQL - 8.0

**Additional context**
background color of tinymce input for description box is causing readability/accessibility issues.

If I find any other issues using dark mode or other theme issues I will add comments to this issue

**Comment by marcelfolaron** [comment]
Fixed in 3.0.0
