### ISSUE TITLE
[BUG] V3.0.0-beta  Default theme causes visibility issues

### ISSUE THREAD

**Issue by willybcode** [Leantime/leantime#2209]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
The select drop-downs for (Status, Milestone,To-Do size) are not fully visible due to the containers of surrounding cards

**To Reproduce**
1. Go to the any project dashboard
2. Click on the option to select a status for an individual To-Do
3. See error

**Expected behavior**
Expected to clearly see the full list of options

**Leantime Version**
I am using v3.0.0-beta

**Server**
Apache - Pop-os 22.04

**PHP / MySQL Version**
PHP - 8.1.27
MySQL - 8.0

**Additional context**
This is purely a UI bug.  This is on the default theme (i've just installed leantime, no customization was made yet). Issue appears on both light and dark theme
![leantimedark](https://github.com/Leantime/leantime/assets/132558146/f8497bdc-55e1-450d-8939-0108930d5736)
![leantimelight](https://github.com/Leantime/leantime/assets/132558146/8a6a90aa-0b7a-4fbd-b1d2-96e73698bdce)

**Comment by marcelfolaron** [comment]
Fixed in 3.0.0
