### ISSUE TITLE
[BUG] Some labels are not resolved correctly

### ISSUE THREAD

**Issue by CodeShakingSheep** [Leantime/leantime#2212]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
Some labels are not being resolved correctly (language setting: English). See screenshot for relevant labels:

- menu.myprojects (also tooltip: popover.myprojects)
- links.timeline
- links.calendar

![image](https://github.com/Leantime/leantime/assets/19874562/a38bfa32-86fa-4473-a80d-6edab2011f97)

Edit: Caught more labels in the menu:

- menu.overview
- menu.files

![image](https://github.com/Leantime/leantime/assets/19874562/d0fab427-4aee-4110-b176-96efbb718426)

**To Reproduce**
Just updated LeanTime to version 2.4.8 . Then open dashboard.

**Expected behavior**
Labels should be resolved correctly.

**Leantime Version**
2.4.8

**Server**
nginx

**PHP / MySQL Version**
PHP 8.2

**Additional context**
None.

**Comment by Codebreaker101** [comment]
`text.you_have_not_favorited_any_projects` as well

**Comment by marcelfolaron** [comment]
Fixed in 3.0.0
