### ISSUE TITLE
Plugins with v3

### ISSUE THREAD

**Issue by nebulade** [Leantime/leantime#2221]
I am preparing the Cloudron package for v3 and our tests found an issue with the plugins. In v2 the Plugins folder in the app folder was local to this repository, while it is now a link to a private repo at https://github.com/Leantime/plugins/tree/fb23f76357ff1b8405722add67682fddfd4fb1cc

My Question here is, if those plugins are indeed required or if we can just start the app with an empty `Plugins` folder? Previously it only contained one plugin, the `MotivationalQuotes`, which is now gone and causes the app to behave erratical after update.

Any hints on how to overcome this situation or some info what to expect would be greatly appreciated.

**Comment by marcelfolaron** [comment]
Hey, 
Yeah with 3.0 we are introducing a plugin marketplace so the default installation starts out with an empty Plugins folder. 
For updates this shouldn't impact the contents of the Plugins folder. However on re-builds you'll need to make sure that folder keeps the data. So it might make sense to mount it if you're using docker. We'll update our docs to say that as well.

**Comment by nebulade** [comment]
Thanks for the clarification!

**Comment by nebulade** [comment]
Reopening this, as clearing out the plugins folder still didn't fix the app when updated. I have encountered some inconsistencies with plugins on a fresh v3 vs an updated leantime instance.

The `zp_plugins` table on an instance which was upgraded from v2 -> v3 looks as follows:
```
mysql> describe zp_plugins;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int          | NO   | PRI | NULL    | auto_increment |
| name        | varchar(45)  | YES  |     | NULL    |                |
| enabled     | tinyint      | YES  |     | NULL    |                |
| description | varchar(255) | YES  |     | NULL    |                |
| version     | varchar(45)  | YES  |     | NULL    |                |
| installdate | datetime     | YES  |     | NULL    |                |
| foldername  | varchar(45)  | YES  |     | NULL    |                |
| homepage    | varchar(255) | YES  |     | NULL    |                |
| authors     | varchar(255) | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
9 rows in set (0.00 sec)
```
This is after a successful migration run:
```
bin/leantime db:migrate 

[OK] Database Successfully Migrated
```

now on a fresh installation its looks as follows:
```
mysql> describe zp_plugins;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int          | NO   | PRI | NULL    | auto_increment |
| name        | varchar(45)  | YES  |     | NULL    |                |
| enabled     | tinyint      | YES  |     | NULL    |                |
| description | varchar(255) | YES  |     | NULL    |                |
| version     | varchar(45)  | YES  |     | NULL    |                |
| installdate | datetime     | YES  |     | NULL    |                |
| foldername  | varchar(45)  | YES  |     | NULL    |                |
| homepage    | varchar(255) | YES  |     | NULL    |                |
| authors     | varchar(255) | YES  |     | NULL    |                |
| license     | text         | YES  |     | NULL    |                |
| format      | varchar(45)  | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
11 rows in set (0.01 sec)
```
`license` and `format` fields are extra here.

I am wondering if there is a migration script missing in the v3 release or if I missed some potentially required manual steps here.

**Comment by marcelfolaron** [comment]
Ah, thanks for bringing that up. I had another user face the update issue. The update script should have created the missing columns. Let me take a look at what's going on there.

**Comment by marcelfolaron** [comment]
Which version did you update from?

**Comment by nebulade** [comment]
This is from 2.4.8 → 3.0.0

Tried also 2.4.8 ⇾ 3.0.2 now, which appears to have a fix for this with https://github.com/Leantime/leantime/pull/2226/commits/dc168205bb111bd2f005de1b3e2ac64bb00318ce and I can confirm the table is properly migrated there.

Unfortunately this apparently wasn't the only issue, so I will dig further. To give some context. No errors are shown anywhere, however after the update (**not** in a fresh v3 instance) the app looks like this:

![image](https://github.com/Leantime/leantime/assets/646768/0f5cc51a-d1d8-4c39-bd54-738fbdcb75af)

Just as if some css would be broken. Cache is busted and no assets are failing to load, so something is still off.

**Comment by marcelfolaron** [comment]
Yeah this def looks like a css caching bug. Are you pulling the zip file or are you pulling directly from master?

**Comment by nebulade** [comment]
We are pulling the release tarball: https://git.cloudron.io/cloudron/leantime-app/-/blob/main/Dockerfile?ref_type=heads#L7

Taking a second look there and confirming its not a client side caching issue, maybe our `start.sh` needs some extra cache busting command.

**Comment by marcelfolaron** [comment]
On another note: I saw in one of the cloudron forum posts that there may have been a session memory issue. More than likely it is related to the session garbage collection definition in your dockerfile. I am not quite well versed on best practices there so I won't be able to be of much help but thought I'd share :)

**Comment by nebulade** [comment]
We were able to publish a package update to v3 now with cache clearing and session timeout. Thanks for all the help!

**Comment by marcelfolaron** [comment]
Thanks for the update!
