### ISSUE TITLE
[BUG] Graphical Bug in Project Overview Dashboard

### ISSUE THREAD

**Issue by MIPMHannes** [Leantime/leantime#2222]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**

**To Reproduce**
1. Go to 'Project Selection Menu'
2. Click on 'your Project -> Project Overview'
3. Look at the Project Checklist
![image](https://github.com/Leantime/leantime/assets/98889138/e1e4d3b6-2e7a-430f-b949-b1c87b556055)

Same Problem is with 'edit project' button on the same widget. It says 'label.edit_project'
**Expected behavior**
I belive that text.step_*1* is not what it is supposed to say. I think it needs to be just  'Step *1*' 
**Leantime Version**
Which Leantime version are you using
3.0.0
**Server**
Docker Container, Apache (I think)

**Comment by cbrand-ludlums** [comment]
In addition to this, the fly outs for the checklists display under the Latest To-Dos section making them inaccessible.
![image](https://github.com/Leantime/leantime/assets/45399214/0c0f58dc-3bfa-4ca5-b87e-fdb8295d3b6d)
Running in docker, leantime version 3.0.0.

**Comment by BeateLerch** [comment]
I see the same issues, running directly on apache, having deleted the cache.

**Comment by BeateLerch** [comment]
@Hannes, add to your language.php those lines, matching your language of course:

text.step_1 = "Schritt 1"
text.step_2 = "Schritt 2"
text.step_3 = "Schritt 3"
text.step_4 = "Schritt 4"
label.edit_project = "Projekt bearbeiten"

**Comment by marcelfolaron** [comment]
This should be fixed as of 3.0.4
