### ISSUE TITLE
[BUG] If project is deleted, the associated tasks remain as ghost tasks

### ISSUE THREAD

**Issue by TheMatzy** [Leantime/leantime#2227]
**What set up are you using**

* [ x ] Self Hosted

**Describe the bug**
If I delete a project, I can still see the tasks on my start page (My Work). Even projects with tasks that have been deleted for months. 

**To Reproduce**
1. Delete a project with tasks in it
2. Project has been deleted and is no longer visible
3. On the start page (My Work) under My ToDos. If you select Group by -> Project, you suddenly see old deleted projects. Marked as // (20)
![grafik](https://github.com/Leantime/leantime/assets/41703752/871b0179-319a-4505-a07a-bcc32eecd9cc)
4. There you can now see tasks that should actually be deleted. You see that in the database too.
5. But get an error, when you open the ghost task
![grafik](https://github.com/Leantime/leantime/assets/41703752/7145f71c-fedc-4c07-830f-9660df13b7c0)

**Current workaround**
Delete all tickets manually before deleting the project. Otherwise they remain in the database as ghost tasks 👻  and are just not assigned to a project

**Expected behavior**
When a project is deleted, the associated task should also be deleted. For a clean database.

**Leantime Version**
3.0.2

**Server**
Leantime V3.0.2 with the official Docker Image

**Comment by marcelfolaron** [comment]
Fixed in 3.0.3
