### ISSUE TITLE
[BUG] Cron jobs not working

### ISSUE THREAD

**Issue by willcodetech** [Leantime/leantime#2228]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X ] Self Hosted

**Describe the bug**
Cron jobs not available.
According to the documentation (https://docs.leantime.io/#/development/commandline?id=cron-jobs), it is possible to use cron jobs via the browser and also via the command line.
When trying to access via browser, "/cron/run" nothing happens.

If you try to run it via the command line, it generates the error " There are no commands defined in the "cron" namespace."
![image](https://github.com/Leantime/leantime/assets/48792160/83a4702b-e739-49b1-aedb-c677cde1887b)

It seems to me that because of this, email notifications are not sent.

Other commands via terminal work, such as testing sending an email
![image](https://github.com/Leantime/leantime/assets/48792160/3394c57b-36db-4b01-b7c2-29e04c7d86ef)

**To Reproduce**
1 - Via terminal, go to the bin folder
2 - Run the command ./leantime cron:run
3 - See error

**Expected behavior**
Command runs without errors

**Leantime Version**
v3.0.2

**Server**
cPanel with nginx

**PHP / MySQL Version**
PHP 8.1
MySQL 8.0.33-cll-lve

**Additional context**
Just updated from v2.4.7 to v3.0.2

**Comment by mott2060** [comment]
Hey @willcodetech ,
did you find a solution for this issue? I´m having the exact same problem. Access via browser doesn´t work and via command line I´m getting the same error message.

**Comment by willcodetech** [comment]
> Hey @willcodetech , did you find a solution for this issue? I´m having the exact same problem. Access via browser doesn´t work and via command line I´m getting the same error message.

Hello @mott2060  !
I still haven't been able to solve it, but I installed the latest version v3.0.6 and I'm also having the same problem =/

**Comment by mott2060** [comment]
Thanks for your feedback @willcodetech .
@marcelfolaron , do you maybe have any advice for us?

**Comment by seguce92** [comment]
I have the same problem with version 3.0.6. Reviewing the previous versions I reached #v2.4.8, a version in which cron:run does work, reviewing I was able to show that the command does not exist
app/Command/RunCronCommand.php

![image](https://github.com/Leantime/leantime/assets/87082387/00cb6d3a-e000-47b1-90ff-928a6fa4056e)

**Comment by marcelfolaron** [comment]
CLI and cron jobs were fixed in 3.3.0

**Comment by refadon** [comment]
Jobs are now executed through Laravel’s scheduler:

Long-running worker (recommended if you can keep a process alive ie. by supervised)
php /path/to/leantime/bin/leantime schedule:work

One-off run (use this from crontab every 5–15 min)
php /path/to/leantime/bin/leantime schedule:run
