### ISSUE TITLE
[BUG] Leantime not working with domain but working fine with ip address

### ISSUE THREAD

**Issue by weir1** [Leantime/leantime#2229]
Using selfhosted

when I visit ip:port its works great but by using cloudflare tunnel or nginx its breaking

**Expected behavior**
as its working great with ip & port , I want it to work like that with leantime.mydomain.com

latest 3.0.2

using docker compose currently after trying from last night

I played with manual installation too

**Comment by willcodetech** [comment]
What do you mean by "break"?
Do you have a screenshot or error log to make it easier to analyze the problem?

I have leantime running on my hosting with cPanel and Nginx and I have no problems. I don't use docker, direct installation.

**Comment by TheBilltrain** [comment]
I am having similar issues when connecting over https via a nginx proxy. Works fine from http ip:port. Installed via docker.

This looks to be the issue;

Even though the initial HTML page is loaded over a secure HTTPS connection, some resources like images, stylesheets or scripts are being accessed over an insecure HTTP connection. Usage of insecure resources is restricted to strengthen the security of your entire site. To resolve this issue, load all resources over a secure HTTPS connection. 

18 resources 

| Name                                     | Restriction Status     |
|------------------------------------------|------------------------|
| main.3.0.2.min.css                       | blocked                |
| app.3.0.2.min.css                        | blocked                |
| i18n?v=3.0.2                             | blocked                |
| compiled-htmx.3.0.2.min.js               | blocked                |
| compiled-frameworks.3.0.2.min.js         | blocked                |
| compiled-framework-plugins.3.0.2.min.js  | blocked                |
| compiled-global-component.3.0.2.min.js   | blocked                |
| compiled-calendar-component.3.0.2.min.js | blocked                |
| compiled-table-component.3.0.2.min.js    | blocked                |
| compiled-editor-component.3.0.2.min.js   | blocked                |
| compiled-gantt-component.3.0.2.min.js    | blocked                |
| compiled-chart-component.3.0.2.min.js    | blocked                |
| compiled-app.3.0.2.min.js                | blocked                |
| logo.svg                                 | automatically upgraded |
| logo-powered-by-leantime.png             | automatically upgraded |
| compiled-footer.3.0.2.min.js             | blocked                |
| login                                    | Warned                 |
| favicon.png                              | blocked                |

**Comment by marcelfolaron** [comment]
Make sure to set the app_url environment variable when you are behind a
proxy

**Comment by TheBilltrain** [comment]
@marcelfolaron Adding in a docker env variable of 'LEAN_APP_URL=https://leantime.domain.com' sorted the issues I was seeing. Thanks.

**Comment by TheBilltrain** [comment]
Hi @weir1,
Can you check the following, and see if this solves your issue;
https://github.com/Leantime/leantime?tab=readme-ov-file#docker-installation-notes
