### ISSUE TITLE
[BUG] Slow frontend if proxy in place

### ISSUE THREAD

**Issue by macidev** [Leantime/leantime#2234]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x ] Self Hosted

**Describe the bug**
Leantime get's really slow if you have a proxy running. This is caused by the function getFeed() and hasNews() from app/Domain/Notificatoins/Services/News.php. 
If there's no connection without a proxy, both run in a timeout and therefor slowing every request down. 
Commenting major parts out and just write an return (false) in the function, solves the problematic. 

**To Reproduce**
Steps to reproduce the behaviour:
1. get Leantime running only behind a proxy and php won't be able to connect to the Leantime website. 

**Expected behavior**
Not slowing down the application because of a time-out for the current version. Maybe once a day or once a week. Alternative would be if Leantime would support connections through a proxy. 

**Leantime Version**
3.0.0 - 3.0.2

**Server**
Apache, PHP 8.1, MySQL version unknown, behind proxy

**Comment by hnegadi** [comment]
We have no proxy running but we are running leantime 3.0.2 on a VM.
We just doubled the processors allocation and RAM, It has now 6 logical processors allocated along side with 8192 MB of RAM but it doesn't seem to make a difference.
My Work Page can take up to 7 seconds to refresh and it refreshes eacht time we open a todo and close it.
Server Apache, PHP 8.2, MySQL not behind proxy.

**Comment by puzzle9** [comment]
As long as the network accessing `https://leantime.io` is not good, it will appear

**Comment by marcelfolaron** [comment]
This should have been closed. We made the call async a while ago solving this issue
