### ISSUE TITLE
[FEATURE] Plugin Marketplace Requests

### ISSUE THREAD

**Issue by marcelfolaron** [Leantime/leantime#2236]
Hi All,

With Leantime 3.0 we released our plugin marketplace. To prioritize our roadmap better we want to hear from you which plugins you are interested in. 

Background: The open source project is incredibly feature rich and compared to our competitors we offer most advanced features as part of core. To keep the project alive we do have to find a way to sustain our development efforts. 
Our core believes have always been to serve as many users as possible while keeping the system system. With that said there are a lot of industries that require specialized features that may not be relevant to all. That is why we believe a plugin marketplace offers the best opportunity to build specialized features through a commercial offering and keep the core free. 

Let us know your thoughts! 
Thanks!

**Comment by macidev** [comment]
Hi, awesome, that this is possible. I already asked my co-workers if we need the whiteboard  plugin. 

Maybe offer an option like "Sponsor this feature". If any corp or customer needs a special feature, offer a sponsored development. Not with a pricetag predifined, but the possibility.

**Comment by marcelfolaron** [comment]
Thanks for the feedback!

**Comment by cholletk** [comment]
Hi,
We start some discussions on our end last week to have the ability to plan work of our team on each project. Today it is possible to plan each todos but in our way to work, people are "allocated" on project day by day where they are working on multiple todos.
