### ISSUE TITLE
[BUG] "Skip and don't show this page again" doesn't work on any page

### ISSUE THREAD

**Issue by Nils7698** [Leantime/leantime#2242]
**What set up are you using**
* [ ] Cloud Hosted Version
* [ x] Self Hosted

**Describe the bug**
Everytime a user logs into Leantime he is greeted with the pop up window which describes the current pages functionality etc. This happens on every page. When pressing the "Skip and don't show this page again" Button, I get a "400 Bad Request" error. for example:

__________________________
Request:
XHRPATCH
"mydomain"/api/users
[HTTP/1.1 400 Bad Request 21ms]
	
settings	"mytimesheets"
patchModalSettings	"1"
__________________________
Response:
XHRPATCH
"mydomain"/api/users
[HTTP/1.1 400 Bad Request 33ms]

	
status	"failure"
error	"Required params not included in request"
__________________________

**To Reproduce**
1. Login
2. go to any page

**Expected behavior**
When I use the "Skip and don't show this page again" button the popup window shouldn't appear anymore in the future.

**Leantime Version**
v3.0.2

**PHP / MySQL Version**
PHP 8.1.27 | MySQL 8.0

I installed Leantime with the official docker-compose.

Thanks in advance.

**Comment by marcelfolaron** [comment]
Fixed in 3.0.3
