### ISSUE TITLE
[BUG] Install Issue "Failed to open stream

### ISSUE THREAD

**Issue by maniyar1** [Leantime/leantime#2244]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
Installation not working, Nginx throws a 404 and an error in the log.

**To Reproduce**
Here is the [python script I used to install](https://gist.github.com/maniyar1/de77b3ba9fe87b06256893a5d90aa292) (I was working on it live so it's a bit dirty). This is a non-prod environment, not actual user/pass.

After this I moved configuration sample to `configuration.php` and the env to `.env`. Then I added my DB settings, here is env:
```bash
# This is a sample configuration file with all possible configuration options.
# If you don't want to maintain a file like this you can pass in all variables via Server Variables
 
## Minimum Configuration, these are required for installation
 
LEAN_APP_URL = ''                                  # Base URL, only needed for subfolder installation
LEAN_APP_DIR = '/leantime'                                  # Base of application without trailing slash (used for cookies), e.g, /leantime
 
LEAN_DEBUG = 0                                     # Debug flag
 
# Database
LEAN_DB_HOST = 'localhost'                         # Database host
LEAN_DB_USER = 'leantime2'                                  # Database username
LEAN_DB_PASSWORD = 'leantime2'                              # Database password
LEAN_DB_DATABASE = 'leantime2'                              # Database name
LEAN_DB_PORT = '3306'                              # Database port
```

**Expected behavior**
Install page to show up and give HTTP OK.

**Leantime Version**
Tested with both 3.0.1 and 3.0.2.

**Server**
Nginx

**PHP / MySQL Version**
PHP 8.2.7

**Additional context**
This is the nginx error log:
```2024/01/26 05:12:40 [error] 18608#18608: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(/var/www/leantime/cache/installation/c6/92/c692273deb2772da307ffe37041fef77bf4baa97): Failed to open stream: No such file or directory in /var/www/leantime/vendor/illuminate/filesystem/Filesystem.php on line 190; PHP message: PHP Warning:  file_put_contents(/var/www/leantime/cache/installation/5b/ac/5bac1d3aee24b76ccad2a413c6a76d4780014219): Failed to open stream: No such file or directory in /var/www/leantime/vendor/illuminate/filesystem/Filesystem.php on line 190" while reading response header from upstream, client: 192.168.50.17, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "192.168.50.56"```

Also, when going to the ip address, it does reroute to /install. It just 404s though.

Thank you for any help!

**Comment by marcelfolaron** [comment]
Thanks for the updated

**Comment by KevinBrogan** [comment]
what was the fix @maniyar1 ?
I am also getting Failed to open stream, while using the sample nginx file.

/var/www/leantime/cache/ exists, but /var/www/leantime/cache/installation/ does not

**Comment by marcelfolaron** [comment]
Please make sure that your nginx/apache user has the correct permissions to
write to the cache folder.
