### ISSUE TITLE
[BUG] Subtasks opens not in current Kanban view

### ISSUE THREAD

**Issue by TheMatzy** [Leantime/leantime#2250]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ x ] Self Hosted

**Describe the bug**
When viewing the Kanban Board and accessing a ticket, it contains multiple subtasks. If I select these subtasks, they appear in the "My Work" section instead of the current project. Conversely, if the subtasks are displayed on the Kanban Board and I open them from there, they remain within the Kanban Board view.

https://github.com/Leantime/leantime/assets/41703752/3cd17ade-2023-49d3-9482-c43c34a9825d

**To Reproduce**
1. Go to your Project
2. Go to ToDos
3. Open the Kanban view
4. Create a Task "My little Farm"
5. In this Task create a Subtask
6. Open the Subtask in the main Task.
7. It opens the Subtask in the "My Work" view

**Expected behavior**
Open the Subtask in the current Kanban Board view not in my "My Work" view

**Leantime Version**
Leantime 3.0.3

**Server**
Apache

**PHP / MySQL Version**
Leantime 3.0.3 - MySQL 8.0

**Additional context**

**Comment by marcelfolaron** [comment]
Fixed in 3.0.6
