### ISSUE TITLE
[BUG] Comments on a Wiki page cause an error

### ISSUE THREAD

**Issue by v-marinkov** [Leantime/leantime#2252]
On v3.0.3 running on Docker, posting a comment on a Wiki page causes a 500 Internal Server Error. The comment does get posted though. This page appears:

![image](https://github.com/Leantime/leantime/assets/7135724/cfc2f4eb-65fc-48f5-b759-035fa38128e1)

**Comment by marcelfolaron** [comment]
Fixed in 3.0.6
