### ISSUE TITLE
[BUG] CSS class error on Projects dropdown

### ISSUE THREAD

**Issue by v-marinkov** [Leantime/leantime#2256]
The class for the heading of the Projects dropdown is wrong and thus the left margin doesn't like on "My Work" and "Company"

![image](https://github.com/Leantime/leantime/assets/7135724/1365690d-3d33-4c99-a2cf-7404ffe76e1f)

![image](https://github.com/Leantime/leantime/assets/7135724/dbed1f7d-3c97-411e-ad3b-c9ae3c9fbd14)

![image](https://github.com/Leantime/leantime/assets/7135724/48cd312b-9ab5-4734-a045-8626cd1c79a9)

For comparison, here is "My Work":

![image](https://github.com/Leantime/leantime/assets/7135724/a099e26a-b3be-4ead-9990-9b2fbd11d362)

**Comment by marcelfolaron** [comment]
This is now fixed in 3.0.5
