### ISSUE TITLE
[BUG] Buttons layout shift in the Projects dropdown

### ISSUE THREAD

**Issue by v-marinkov** [Leantime/leantime#2257]
On v3.0.3 running on Docker, toggling the grouping by client in the Projects dropdown shifts these two buttons from the bottom to the top.
![image](https://github.com/Leantime/leantime/assets/7135724/445a3109-6ad0-4504-8069-ce51d90cc475)

A page refresh fixes it, but the jumping is quite stark and should be avoided.

**Comment by marcelfolaron** [comment]
This is now fixed in 3.0.5
