### ISSUE TITLE
[BUG] 500 Error when clicking favorite in Project Hub

### ISSUE THREAD

**Issue by Elaktrato** [Leantime/leantime#2259]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [x] Cloud Hosted Version
* [ ] Self Hosted

**Describe the bug**
Whenever I am in the project hub and either add or remove a project from my favorites I get a 500 error message and have to reload the page. The changes are made however.

**To Reproduce**
1. Go to 'Project Hub'
2. Click on 'Favorite Star on any Project'
3. See error

**Expected behavior**
The project should simply be moved to or removed from favorites without an error message.

**Leantime Version**
3.0.3

**Comment by marcelfolaron** [comment]
This is now fixed in 3.0.5
