### ISSUE TITLE
[FEATURE] Reintroduce Export of all Timesheets

### ISSUE THREAD

**Issue by Elaktrato** [Leantime/leantime#2260]
**Is your feature request related to a problem? Please describe.**
In previous versions of Leantime we had the ability to export the timesheets on *All Timesheets* with the applied filters etc.
Since Leantime v3 it seems to have been removed. Our issue with this is that we rely on being able to export these timesheets for our invoices at the end of every month.

**Describe the solution you'd like**
Reintroduce the export feature for the timesheets. Before, it seems to have been done based on the HTML present in the frontend (some HTML Tags tended to end up inside the Excel Sheets). Albeit not the best solution I'd prefer being able to export something than nothing at all.

Thank you for your help!

**Comment by marcelfolaron** [comment]
This is now fixed in 3.0.5
