### ISSUE TITLE
[BUG] Project Details have to be saved twice

### ISSUE THREAD

**Issue by Elaktrato** [Leantime/leantime#2261]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [x] Cloud Hosted Version
* [ ] Self Hosted

**Describe the bug**
On any project whenever we want to edit an existing project's description, due date or title, the changes we made aren't saved the first time we press the save button. Only after the page has reloaded after pressing save once, we can reenter all the changes we want to make , press save and actually have it be saved.

**To Reproduce**
1. Go to an existing project
2. Attempt to change the project's description, due date or title
3. Scroll down to the Save Button
4. Click Save and let the page reload
6. See that the changes have been reverted
7. Reenter the changes you wanted to make
8. Click save
9. Have the changes be saved

**Expected behavior**
Any changes should be saved the first time you press the save button.

**Leantime Version**
3.0.3

**Comment by marcelfolaron** [comment]
This is now fixed in 3.0.5
