### ISSUE TITLE
Sweep: Make things clickable through the confetti when creating a new project or add ability to remove it.

### ISSUE THREAD

**Issue by Elaktrato** [Leantime/leantime#2262]
### Details

As the title says, it's quite bothersome to have to wait until the confetti is completely gone whenever you create a new project.

**Comment by pdunne** [comment]
in line 415 of [app/Core/Template.php](https://github.com/Leantime/leantime/blob/392f910c886edfbe9768492f829942543449a7b1/app/Core/Template.php#L415)
change

`        $_SESSION['confettiInYourFace'] = true;`

to

`        $_SESSION['confettiInYourFace'] = false;`

**Comment by Elaktrato** [comment]
Unfortunately I am using the cloud-hosted version and cannot edit the files. 

So simply being able to click through the confetti or turn it off for yourself in the settings would be great.

**Comment by pdunne** [comment]
Sorry, I'm a user too, running my own docker instance so I can't help further.

**Comment by marcelfolaron** [comment]
Confetti was updated and reduced significantly to avoid the blocking issue. version 3.20.
