### ISSUE TITLE
[BUG] Can't close 'Create a new Goal Board' in a new project without creating at least 1 goal

### ISSUE THREAD

**Issue by Mr4013** [Leantime/leantime#2272]
**What set up are you using**
* [ x] Cloud Hosted Version

**Describe the bug**
When you create a new project, if you click in the 'Goals' option, you can't close the 'Create a new Goal Board' window without creating at least one goal.

If you close this window, immediately appears a new one.

**To Reproduce**
1. Go to 'Create a project' and give it a name
2. Click on 'Goals'

**Expected behavior**
Be able to close the 'Create a new Goal Board' window and continue working inside the app.

**Leantime Version**
v3.0.3

**Comment by marcelfolaron** [comment]
This is now fixed in 3.0.5
