### ISSUE TITLE
[BUG] Many 500 errors after update from 2.4.8 to 3.03

### ISSUE THREAD

**Issue by previmeteo** [Leantime/leantime#2273]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x ] Self Hosted (docker)

**Describe the bug**
can't go to /ideas/showBoards, /strategy/showBoards or /retroscanvas/showCanvas without a 500 error (no console error)
can't go to /tickets/showAll or /tickets/showList or /wiki/show from an existing project without a 500 error 
can't create au new projet, new task... (Error message in console : SyntaxError: Unexpected token '<'  AppendChild showKanban:1:879)

**To Reproduce**

**Expected behavior**

**Leantime Version**
Which Leantime version are you using
after update from 2.4.8 to 3.03

**Server**
Apache, nginx, IIS etc
docker container

**PHP / MySQL Version**
Please list the PHP and Mysql version you are using
docker container

**Additional context**

**Comment by marcelfolaron** [comment]
Any errors in logs/error.log?

**Comment by previmeteo** [comment]
[02-Feb-2024 15:53:23 Europe/Paris] Error: Call to a member function __() on int in /var/www/html/app/Domain/Wiki/Templates/show.tpl.php:66
Stack trace:
#0 /var/www/html/vendor/illuminate/filesystem/Filesystem.php(109): require()
#1 /var/www/html/vendor/illuminate/filesystem/Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#2 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/var/www/html/a...', Array)
#3 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(38): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/a...', Array)
#4 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\PhpEngine->get('/var/www/html/a...', Array)
#5 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#6 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#7 /var/www/html/cache/views/46f11d8ba1fba7c35011fc90cf06cc342fabf900.php(46): Illuminate\View\View->render()
#8 /var/www/html/vendor/illuminate/filesystem/Filesystem.php(109): require('/var/www/html/c...')
#9 /var/www/html/vendor/illuminate/filesystem/Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#10 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/var/www/html/c...', Array)
#11 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/c...', Array)
#12 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/a...', Array)
#13 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#14 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#15 /var/www/html/app/Core/Template.php(504): Illuminate\View\View->render()
#16 /var/www/html/app/Domain/Wiki/Controllers/Show.php(194): Leantime\Core\Template->display('wiki.show')
#17 /var/www/html/app/Core/Controller.php(82): Leantime\Domain\Wiki\Controllers\Show->get(Array)
#18 /var/www/html/app/Core/Controller.php(49): Leantime\Core\Controller->executeActions('GET', Array)
#19 [internal function]: Leantime\Core\Controller->__construct(Object(Leantime\Core\IncomingRequest), Object(Leantime\Core\Template), Object(Leantime\Core\Language))
#20 /var/www/html/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs(Array)
#21 /var/www/html/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build('Leantime\\Domain...')
#22 /var/www/html/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve('Leantime\\Domain...', Array)
#23 /var/www/html/app/Core/Frontcontroller.php(130): Illuminate\Container\Container->make('Leantime\\Domain...')
#24 /var/www/html/app/Core/Frontcontroller.php(75): Leantime\Core\Frontcontroller::executeAction('wiki.show', Array)
#25 /var/www/html/app/Core/HttpKernel.php(62): Leantime\Core\Frontcontroller::dispatch()
#26 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#27 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#28 /var/www/html/app/Core/HttpKernel.php(62): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#30 /var/www/html/app/Core/Middleware/CurrentProject.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#31 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\CurrentProject->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#32 /var/www/html/app/Core/Middleware/Localization.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#33 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Localization->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#34 /var/www/html/app/Core/Middleware/Auth.php(88): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#35 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Auth->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#36 /var/www/html/app/Core/Middleware/Updated.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#37 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Updated->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#38 /var/www/html/app/Core/Middleware/Installed.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#39 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Installed->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#40 /var/www/html/app/Core/Middleware/InitialHeaders.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#41 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\InitialHeaders->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#42 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#43 /var/www/html/app/Core/HttpKernel.php(63): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#44 /var/www/html/app/Core/Bootloader.php(300): Leantime\Core\HttpKernel->handle(Object(Leantime\Core\IncomingRequest))
#45 /var/www/html/app/Core/Bootloader.php(170): Leantime\Core\Bootloader->handleRequest()
#46 /var/www/html/public/index.php(18): Leantime\Core\Bootloader->boot()
#47 {main}

Next Illuminate\View\ViewException: Call to a member function __() on int (View: /var/www/html/app/Views/Templates/layouts/app.blade.php) in /var/www/html/app/Domain/Wiki/Templates/show.tpl.php:66
Stack trace:
#0 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Error), 0)
#1 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/c...', Array)
#2 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/a...', Array)
#3 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#4 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#5 /var/www/html/app/Core/Template.php(504): Illuminate\View\View->render()
#6 /var/www/html/app/Domain/Wiki/Controllers/Show.php(194): Leantime\Core\Template->display('wiki.show')
#7 /var/www/html/app/Core/Controller.php(82): Leantime\Domain\Wiki\Controllers\Show->get(Array)
#8 /var/www/html/app/Core/Controller.php(49): Leantime\Core\Controller->executeActions('GET', Array)
#9 [internal function]: Leantime\Core\Controller->__construct(Object(Leantime\Core\IncomingRequest), Object(Leantime\Core\Template), Object(Leantime\Core\Language))
#10 /var/www/html/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs(Array)
#11 /var/www/html/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build('Leantime\\Domain...')
#12 /var/www/html/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve('Leantime\\Domain...', Array)
#13 /var/www/html/app/Core/Frontcontroller.php(130): Illuminate\Container\Container->make('Leantime\\Domain...')
#14 /var/www/html/app/Core/Frontcontroller.php(75): Leantime\Core\Frontcontroller::executeAction('wiki.show', Array)
#15 /var/www/html/app/Core/HttpKernel.php(62): Leantime\Core\Frontcontroller::dispatch()
#16 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#17 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#18 /var/www/html/app/Core/HttpKernel.php(62): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#20 /var/www/html/app/Core/Middleware/CurrentProject.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#21 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\CurrentProject->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#22 /var/www/html/app/Core/Middleware/Localization.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#23 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Localization->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#24 /var/www/html/app/Core/Middleware/Auth.php(88): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#25 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Auth->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#26 /var/www/html/app/Core/Middleware/Updated.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#27 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Updated->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#28 /var/www/html/app/Core/Middleware/Installed.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#29 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Installed->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#30 /var/www/html/app/Core/Middleware/InitialHeaders.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#31 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\InitialHeaders->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#32 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#33 /var/www/html/app/Core/HttpKernel.php(63): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /var/www/html/app/Core/Bootloader.php(300): Leantime\Core\HttpKernel->handle(Object(Leantime\Core\IncomingRequest))
#35 /var/www/html/app/Core/Bootloader.php(170): Leantime\Core\Bootloader->handleRequest()
#36 /var/www/html/public/index.php(18): Leantime\Core\Bootloader->boot()
#37 {main}
[02-Feb-2024 16:28:35 Europe/Paris] Error: Call to a member function get() on int in /var/www/html/app/Domain/Ideas/Templates/showBoards.tpl.php:29
Stack trace:
#0 /var/www/html/vendor/illuminate/filesystem/Filesystem.php(109): require()
#1 /var/www/html/vendor/illuminate/filesystem/Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#2 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/var/www/html/a...', Array)
#3 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(38): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/a...', Array)
#4 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\PhpEngine->get('/var/www/html/a...', Array)
#5 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#6 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#7 /var/www/html/cache/views/46f11d8ba1fba7c35011fc90cf06cc342fabf900.php(46): Illuminate\View\View->render()
#8 /var/www/html/vendor/illuminate/filesystem/Filesystem.php(109): require('/var/www/html/c...')
#9 /var/www/html/vendor/illuminate/filesystem/Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#10 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/var/www/html/c...', Array)
#11 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/c...', Array)
#12 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/a...', Array)
#13 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#14 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#15 /var/www/html/app/Core/Template.php(504): Illuminate\View\View->render()
#16 /var/www/html/app/Domain/Ideas/Controllers/ShowBoards.php(128): Leantime\Core\Template->display('ideas.showBoard...')
#17 /var/www/html/app/Core/Controller.php(84): Leantime\Domain\Ideas\Controllers\ShowBoards->run()
#18 /var/www/html/app/Core/Controller.php(49): Leantime\Core\Controller->executeActions('GET', Array)
#19 [internal function]: Leantime\Core\Controller->__construct(Object(Leantime\Core\IncomingRequest), Object(Leantime\Core\Template), Object(Leantime\Core\Language))
#20 /var/www/html/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs(Array)
#21 /var/www/html/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build('Leantime\\Domain...')
#22 /var/www/html/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve('Leantime\\Domain...', Array)
#23 /var/www/html/app/Core/Frontcontroller.php(130): Illuminate\Container\Container->make('Leantime\\Domain...')
#24 /var/www/html/app/Core/Frontcontroller.php(75): Leantime\Core\Frontcontroller::executeAction('ideas.showBoard...', Array)
#25 /var/www/html/app/Core/HttpKernel.php(62): Leantime\Core\Frontcontroller::dispatch()
#26 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#27 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#28 /var/www/html/app/Core/HttpKernel.php(62): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#30 /var/www/html/app/Core/Middleware/CurrentProject.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#31 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\CurrentProject->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#32 /var/www/html/app/Core/Middleware/Localization.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#33 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Localization->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#34 /var/www/html/app/Core/Middleware/Auth.php(88): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#35 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Auth->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#36 /var/www/html/app/Core/Middleware/Updated.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#37 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Updated->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#38 /var/www/html/app/Core/Middleware/Installed.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#39 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Installed->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#40 /var/www/html/app/Core/Middleware/InitialHeaders.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#41 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\InitialHeaders->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#42 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#43 /var/www/html/app/Core/HttpKernel.php(63): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#44 /var/www/html/app/Core/Bootloader.php(300): Leantime\Core\HttpKernel->handle(Object(Leantime\Core\IncomingRequest))
#45 /var/www/html/app/Core/Bootloader.php(170): Leantime\Core\Bootloader->handleRequest()
#46 /var/www/html/public/index.php(18): Leantime\Core\Bootloader->boot()
#47 {main}

Next Illuminate\View\ViewException: Call to a member function get() on int (View: /var/www/html/app/Views/Templates/layouts/app.blade.php) in /var/www/html/app/Domain/Ideas/Templates/showBoards.tpl.php:29
Stack trace:
#0 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Error), 0)
#1 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/c...', Array)
#2 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/a...', Array)
#3 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#4 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#5 /var/www/html/app/Core/Template.php(504): Illuminate\View\View->render()
#6 /var/www/html/app/Domain/Ideas/Controllers/ShowBoards.php(128): Leantime\Core\Template->display('ideas.showBoard...')
#7 /var/www/html/app/Core/Controller.php(84): Leantime\Domain\Ideas\Controllers\ShowBoards->run()
#8 /var/www/html/app/Core/Controller.php(49): Leantime\Core\Controller->executeActions('GET', Array)
#9 [internal function]: Leantime\Core\Controller->__construct(Object(Leantime\Core\IncomingRequest), Object(Leantime\Core\Template), Object(Leantime\Core\Language))
#10 /var/www/html/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs(Array)
#11 /var/www/html/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build('Leantime\\Domain...')
#12 /var/www/html/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve('Leantime\\Domain...', Array)
#13 /var/www/html/app/Core/Frontcontroller.php(130): Illuminate\Container\Container->make('Leantime\\Domain...')
#14 /var/www/html/app/Core/Frontcontroller.php(75): Leantime\Core\Frontcontroller::executeAction('ideas.showBoard...', Array)
#15 /var/www/html/app/Core/HttpKernel.php(62): Leantime\Core\Frontcontroller::dispatch()
#16 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#17 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#18 /var/www/html/app/Core/HttpKernel.php(62): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#20 /var/www/html/app/Core/Middleware/CurrentProject.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#21 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\CurrentProject->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#22 /var/www/html/app/Core/Middleware/Localization.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#23 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Localization->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#24 /var/www/html/app/Core/Middleware/Auth.php(88): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#25 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Auth->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#26 /var/www/html/app/Core/Middleware/Updated.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#27 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Updated->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#28 /var/www/html/app/Core/Middleware/Installed.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#29 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Installed->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#30 /var/www/html/app/Core/Middleware/InitialHeaders.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#31 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\InitialHeaders->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#32 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#33 /var/www/html/app/Core/HttpKernel.php(63): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /var/www/html/app/Core/Bootloader.php(300): Leantime\Core\HttpKernel->handle(Object(Leantime\Core\IncomingRequest))
#35 /var/www/html/app/Core/Bootloader.php(170): Leantime\Core\Bootloader->handleRequest()
#36 /var/www/html/public/index.php(18): Leantime\Core\Bootloader->boot()
#37 {main}

**Comment by marcelfolaron** [comment]
Oh, which language do you currently use?

**Comment by previmeteo** [comment]
Docker image

Le 2 févr. 2024 à 20:02, Marcel Folaron ***@***.***> a écrit :

﻿


Oh, which language do you currently use?

**Comment by previmeteo** [comment]
My foreign language is french and with last release, it seems to be corrected
