### ISSUE TITLE
[BUG] 2-Factor authentication results in 404 error, dashboard button returns to login

### ISSUE THREAD

**Issue by twessman** [Leantime/leantime#2279]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Self Hosted - official docker version

**Describe the bug**
Turned on 2 factor time based authentication, but now it returns a 404 page when i correctly give the 6 digit code. Pressing the DASHBOARD button on the page returns to main page and login happened fine.

Also should probably mark that field as a "not-rembered" item to avoid big lists of 6 digit code collecting there.

**Expected behavior**
Automatic redirect to main page I would assume.

**Leantime Version**
Saw in 3.03 and just now in 3.04 after upgrading

**Server**
Whatever is in official docker image.

**PHP / MySQL Version**
Whatever is in official docker image.

**Additional context**

https://github.com/Leantime/leantime/assets/47958282/10891cf6-f01b-49a2-a3a4-9e474cf3a4a9

**Comment by marcelfolaron** [comment]
This should be fixed in 3.0.5
