### ISSUE TITLE
Feature Request: Calendar Subscription

### ISSUE THREAD

**Issue by Marcquito** [Leantime/leantime#228]
Hi there! I have one main calendar for work that pulls in a ton of information from a few sources so I can get an idea of the day/week/month at a glance. Is there a way to add the leantime calendar subscription to my existing calendar (that I'm not seeing?) or is this in the works? It would be super useful! 

Thanks for everything!!!

**Comment by marcelfolaron** [comment]
Thanks. We currently don't have an oval export. I think it would be great to sync calendars. We'll add that to our backlog!

**Comment by Marcquito** [comment]
Thanks Marcel!

**Comment by marcelfolaron** [comment]
We finally have ical export in our latest release!
