### ISSUE TITLE
[BUG] Emails do not seem to notify people upon tagging, assigning, etc

### ISSUE THREAD

**Issue by twessman** [Leantime/leantime#2280]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Self Hosted  official docker image

**Describe the bug**
I do not seem to be able to get any email notifications regarding issues being assigned, tagged, etc. Setting to 5 minutes, 12 hours or anything does not work.

**To Reproduce**
Tag a user or assign them, and it does not ever seem to email them. Other emails work fine like PW resets, etc so the mail system is functioning.

**Expected behavior**
An email letting the user know they were tagged or something was assigned after the specified period of no action/view.

**Leantime Version**
3.03->3,04
In the previous 2.x I was seeing email notifications. Seems like this was lost/broken in the 3.x transition maybe?

**Server**
Official docker image

**PHP / MySQL Version**
Official docker image

**Additional context**
2.x seemed to email just fine as I would expect. This is a pretty critical issue as it really prevents teams from working together I think... (at least if this is not just me)  Posted a question on this in discord and did not see anything so filed here to avoid getting lost.

**Comment by marcelfolaron** [comment]
Do you have the cron job running that sends out the emails?

**Comment by BeateLerch** [comment]
I have experienced the same. In Docker as well as n a native installation - e-Mailing is broken after updating from 2.x to 3.x. Since updating is more or less just replacing files in a directory i cannot see how that would disable a cron job. On the other hand, there is no cron job in version 2.x, right? Perhaps this is missing in the update routine?

**Comment by twessman** [comment]
Yes, it was up and running. This was a fresh install using the official docker image.

A more interesting artifact here I just noticed earlier in the week - going into the email settings per user and unchecking, then rechecking the "email notification" checkbox seems to trigger it to begin working. toggling the setting then back seemed to kick it moving again.

**Comment by marcelfolaron** [comment]
Should be fixed in 3.1.2 now
