### ISSUE TITLE
[BUG] Installation on Plesk - nginx directives bug in the docs

### ISSUE THREAD

**Issue by iskraecommerce** [Leantime/leantime#2285]
I have tried to install Leantime on Plesk Linux - AlmaLinux 9, all fully up2date. 

I followed this guide: https://github.com/Leantime/docs/blob/master/installation/configuration.md

The nginx directives have a bug I believe - they only work without the "{"

But then it still does not work to install leantime (too many redirects). Maybe because the additional sentence under the directives is not complete: 

This and by desabling the

Disabling what? :-) 

Thank you in advance! 

Regards
Lukas

**Comment by gnanet** [comment]
have a look into the raw markdown, and you will find the initial lines (witout the three \` signs)
https://github.com/Leantime/docs/blob/master/installation/configuration.md?plain=1

but yes, there was possibly a distration while writing the ending part
