### ISSUE TITLE
[BUG] After Upgrade to 3.0.3 - Cannot Add New Todo From Inside Project

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#2286]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ X ] Self Hosted

**Describe the bug**
When attempting to add a new "To-Do" we get "An error occurred" and a white screen with a red border

**To Reproduce**
1. Find an existing project
2. Click the Todos icon on the left side
3. Click New - Add Todo
4. Save or Save / Close

**Expected behavior**
The Todo is saved

**Leantime Version**
3.0.3

**Server**
NGINX

**PHP / MySQL Version**
8.1 / MariaDB 10.4

**Additional context**
Of interest is this error does not seem to happen when I adding a todo from the main dashboard but happens every time when inside a project and clicking the west side menu's Todo icon.

![image](https://github.com/Leantime/leantime/assets/121611/9b2a4ea2-027e-4d0b-8c4a-7aa1ea493dcb)

**Comment by marcelfolaron** [comment]
Any errors in the log file (logs/error.logs)

**Comment by marcelfolaron** [comment]
Thanks. I think I have a fix for this already but just to confirm: Does this user have any projects assigned?

**Comment by marcelfolaron** [comment]
This should be fixed in 3.0.5

**Comment by compumatter** [comment]
Yes.  It is my user I am finding this on.  This last upgrade made it to the production server.  So do you think if I run the upgrade to 3.0.5 we should be good?  I can do this.

**Comment by marcelfolaron** [comment]
Yes, I believe that 3.0.5 will fix this issue.

**Comment by compumatter** [comment]
Hello Marcel,

So far so good :-) problem seems resolved for sure.
