### ISSUE TITLE
[BUG] LDAP - firstName and telephoneNumber not pulling into Leantime after login

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#2289]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ X ] Self Hosted

**Describe the bug**
LDAP has been setup in the .env file.  I have verified that the LDAP firstName and telephoneNumber on the server do have text values.  Upon logging into Leantime it pulls in the last name (sn) and email (mail) however it does not pull in the first name (firstName) or phone number (telephoneNumber).

**To Reproduce**
1. Fill out the .env file as is proper for LDAP
2. Login
3. Go to Profiles
4. See missing fields

**Expected behavior**
I expect to see the first name and phone number values

**Leantime Version**
3.0.5 (but this has been a problem for many versions)

**Server**
NGINX

**PHP / MySQL Version**
8.1 / MariaDB 10.4

**Additional context**
I have created a video to make the problem more clear.  It provides important insights:
* https://www.youtube.com/watch?v=FBAiAK1hsqE

**Comment by compumatter** [comment]
Just an FYI - I actually just noticed that I opened another issue on this back in November https://github.com/Leantime/leantime/issues/2080 though I suspect this most recent video is more detailed.  The other video mentions this going back to version 2.3.x so you may want to close one of these issues out.

**Comment by marcelfolaron** [comment]
Fixed in 3.1.0-beta
