### ISSUE TITLE
Install on Windows Server

### ISSUE THREAD

**Issue by hoebd** [Leantime/leantime#229]
Hi, I am trying to install Leantime on Windows Server. I have added a Webpage in IIS that Points to C:\Leantime\public Directory. Then I have installed PHP Version 7.4.1, MySQL and added an empty database "LeantimeDB". The config file has been renamed and filled with the following data: 

/* Database */
        public $dbHost="localhost:3306"; //Database host
	public $dbUser="testuser"; //Database username
	public $dbPassword="********"; //Database password
	public $dbDatabase="LeantimeDB"; //Database Name

After that I wanted to install Leantime, but when I try to open the install URL "http://localhost:8080/install" I get a HTTP-Fehler 404.0 - Not Found

When I try to call "http://localhost:8080/" or "http://localhost:8080/index.php?install=true" then it says "No database connection, check your database credentials in your configuration file."

Could you please give me a hint, what the problem is or which steps I forgot to do?

**Comment by marcelfolaron** [comment]
Hey, 
So the biggest factor is probably mod_rewrite. That is a requirement for the redirects. I know IIS has a few extensions to enable that, like: https://www.iis.net/downloads/microsoft/url-rewrite

The no database connection message is curious though. Do you see any error in resources/logs/error.log?

**Comment by marcelfolaron** [comment]
Were you able to fix your issue?

**Comment by marcelfolaron** [comment]
Will close this for now. If you are still having issues feel free to reopen or reach out on [https://community.leantime.io/](https://community.leantime.io/)
