### ISSUE TITLE
[BUG] Many 500 errors are back

### ISSUE THREAD

**Issue by previmeteo** [Leantime/leantime#2300]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x ] Self Hosted

**Describe the bug**
lot of 500 errors are back
(create a task, ideas dashbord for a project, blueprint,...)
 
<img width="1435" alt="Capture d’écran 2024-02-09 à 16 37 30" src="https://github.com/Leantime/leantime/assets/5520605/bf5249d0-ef71-415c-bb1d-27ead75288e2">

**To Reproduce**
1. Go to '.a project'
2. Click on 'add a task'
4. See error 500

**Expected behavior**

**Leantime Version**
Which Leantime version are you using
3.0.6

**Server**
Apache, nginx, IIS etc
Docker version

**PHP / MySQL Version**
Please list the PHP and Mysql version you are using

**Additional context**

even in french or english language

**Comment by marcelfolaron** [comment]
Are there any errors in your logs/error.log file?

Sincerely,
Marcel

**Comment by previmeteo** [comment]
`Next Illuminate\View\ViewException: Call to a member function __() on int (View: /var/www/html/app/Views/Templates/layouts/app.blade.php) in /var/www/html/app/Domain/Strategy/Templates/showBoards.tpl.php:128
Stack trace:
#0 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Error), 0)
#1 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/c...', Array)
#2 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/a...', Array)
#3 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#4 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#5 /var/www/html/app/Core/Template.php(507): Illuminate\View\View->render()
#6 /var/www/html/app/Domain/Strategy/Controllers/ShowBoards.php(168): Leantime\Core\Template->display('strategy.showBo...')
#7 /var/www/html/app/Core/Controller.php(84): Leantime\Domain\Strategy\Controllers\ShowBoards->run()
#8 /var/www/html/app/Core/Controller.php(49): Leantime\Core\Controller->executeActions('GET', Array)
#9 [internal function]: Leantime\Core\Controller->__construct(Object(Leantime\Core\IncomingRequest), Object(Leantime\Core\Template), Object(Leantime\Core\Language))
#10 /var/www/html/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs(Array)
#11 /var/www/html/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build('Leantime\\Domain...')
#12 /var/www/html/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve('Leantime\\Domain...', Array)
#13 /var/www/html/app/Core/Frontcontroller.php(130): Illuminate\Container\Container->make('Leantime\\Domain...')
#14 /var/www/html/app/Core/Frontcontroller.php(75): Leantime\Core\Frontcontroller::executeAction('strategy.showBo...', Array)
#15 /var/www/html/app/Core/HttpKernel.php(63): Leantime\Core\Frontcontroller::dispatch()
#16 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#17 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#18 /var/www/html/app/Core/HttpKernel.php(63): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#20 /var/www/html/app/Core/Middleware/CurrentProject.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#21 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\CurrentProject->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#22 /var/www/html/app/Core/Middleware/Localization.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#23 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Localization->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#24 /var/www/html/app/Core/Middleware/Auth.php(88): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#25 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Auth->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#26 /var/www/html/app/Core/Middleware/Updated.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#27 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Updated->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#28 /var/www/html/app/Core/Middleware/Installed.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#29 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Installed->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#30 /var/www/html/app/Core/Middleware/InitialHeaders.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#31 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\InitialHeaders->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#32 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#33 /var/www/html/app/Core/HttpKernel.php(64): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /var/www/html/app/Core/Bootloader.php(300): Leantime\Core\HttpKernel->handle(Object(Leantime\Core\IncomingRequest))
#35 /var/www/html/app/Core/Bootloader.php(170): Leantime\Core\Bootloader->handleRequest()
#36 /var/www/html/public/index.php(18): Leantime\Core\Bootloader->boot()
#37 {main}`

**Comment by previmeteo** [comment]
Still no idea for a fix ?

**Comment by previmeteo** [comment]
Cleaning cache solved it (does not work if using only private session
