### ISSUE TITLE
[BUG] Theming - Changing Values Has No Effect On Colors

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#2311]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ X ] Self Hosted

**Describe the bug**
I have a need.  I wish to modify colors / logo so they are more in keeping with our server / wide theming strategy of earth tones.  I also need to the company logo at the top.

I see these values in the .env file:

```
LEAN_LOGO_PATH = '/dist/images/logo.svg'           # Default logo path, can be changed later
LEAN_PRINT_LOGO_URL = '/dist/images/logo.png'      # Default logo URL use for printing (must be jpg or png format)
LEAN_DEFAULT_THEME = 'default'                     # Default theme
LEAN_PRIMARY_COLOR = '#1b75bb'                     # Primary Theme color
LEAN_SECONDARY_COLOR = '#81B1A8'                   # Secondary Theme Color
LEAN_KEEP_THEME = true

```
But changing them has no effect on anything.

I cannot find documentation on these values either.  I have a real need to make color changes after the recent upgrade but can't figure out how to make it happen.

**To Reproduce**
1. Edit the .env file
2. Change any of the theme color settings
3. Load Leantime in the browser
4. No changes

**Expected behavior**
I expected to see the color changes as indicated in the .env file.

**Leantime Version**
3.0.5

**Server**
NGINX, MariaDB 10.4

**PHP / MySQL Version**
8.1

**Additional context**
It is very important that as the heading says:
## Look & Feel, these settings are available in the UI and can be overwritten there.
as I wish to be able to prevent individuals from changing the company defined theme and this appears to be made for that purpose.

I have created a video to make obvious what the user experience is on my end:
* https://www.youtube.com/watch?v=ENLJWikrR0g

I think this situation has existed for a while as I have notes that to alter colors in the past I have had to UPDATE zp_settings SET value = '#2E2D1E' WHERE zp_settings.key = 'companysettings.primarycolor'; and UPDATE zp_settings SET value = '#526B55' WHERE zp_settings.key = 'companysettings.secondarycolor';" to get the job done.

Thanks for looking at it as always.

Jay / ServerMatter

**Comment by marcelfolaron** [comment]
This should be fixed in 3.1.3
