### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BeateLerch** [Leantime/leantime#2312]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
in Firefox, the login screen appears again after each click. Edge does not show this behaviour.

**To Reproduce**
1. open leantime URL in Firefox
2. authenticate
3. click some menu item

**Expected behavior**
the menu item should open without authenticating again

**Leantime Version**
2.x, but the same issue was seen in 3.x

**Server**
Apache

**Comment by macidev** [comment]
Did you clear the cache or deleted the cookies in Firefox?

**Comment by BeateLerch** [comment]
Since this was the behaviour from the very first time i opened even the installatin page, i did not think of it. But it seems to have fixed the issue. thanks!
