### ISSUE TITLE
[FEATURE] Create user on first OIDC login

### ISSUE THREAD

**Issue by Minionflo** [Leantime/leantime#2313]
**Describe the solution you'd like**
A option to autocreate a user on the first OIDC login

**Comment by pablopoo** [comment]
On docker is LEAN_OIDC_CREATE_USER: 'true'

**Comment by jejbq** [comment]
Without LEAN_OIDC_CREATE_USER : 'true' Authentik is in a redirection loop

**Comment by pablopoo** [comment]
Same issue here. Running 3.1.1 ok. 
Tested 3.1.4 and got a redirect loop with OIDC login. 
Noticed that with 3.1.4 my session id keeps changing. With 3.1.1 stay the same, must be by the changes on [app/Core/Session.php](https://github.com/Leantime/leantime/commit/8ab7cff1eb4996a71084bc67e13c7731a9c44ae2#diff-98a084f1b8958233a2a6e9cbfb8a6cad4f3d0b9218ad80128b574a381321db6c)

Could be that the session ID is regenerated before processing the SSO postback redirect? so the app lost the context and don't know what to do with the IdP response?
