### ISSUE TITLE
Feature Request: LDAP Authentication + SSO

### ISSUE THREAD

**Issue by tiredofit** [Leantime/leantime#232]
First of all, what a nice project with well thought out design and featuresets.

I'd like to make a suggestion to the Authentication / User Management section, and that would be to have the capabilities to integrate LDAP lookup and sync capabilities to the tool. There is potential here to be able to skip the manual user additions aspect, and be able to sync various fields and groups to allow for Auto Population of the user profile fields, auto assign to "Clients" and define permissions.

With that in place, another win would be for organizations to allow the flexibility to login via some sort of single sign on. The easiest would be to utilize HTTP REMOTE_USER style headers, which would allow for those who weren't logging in to still utilize the frontend login screen. Alternatively there are other options like SAML, and OIDC which are harder to configure and put in place, yet add significant value for those who have to jump from application to application and have to constantly login to a service. 

I'll be watching your project closely!

**Comment by emallinger** [comment]
Hello,
In case it's useful, I'd like to suggest using ll:ng (lemon ldap ng) as your test reference SSO to implement this new feature, as it's : free open source software and with a high quality in implementing AAA norms and standards.
Community is great and active.
https://github.com/LemonLDAPNG
https://lemonldap-ng.org/welcome/

Regards,

**Comment by sunrez** [comment]
Another vote for LDAP support!  This is an outstanding application and having LDAP support makes it very easy to extend this to a larger organization.

There is already a Laravel LDAP module ( https://github.com/Adldap2/Adldap2-laravel package).

**Comment by dominguesg** [comment]
Another vote for LDAP support! Thank you for this outstanding tool!

**Comment by thiagolamosa** [comment]
One more vote for LDAP authentication support!

**Comment by sunrez** [comment]
Leantime Developers:

Any feedback on whether or not this feature is on your roadmap?

**Comment by Hawkinzzz** [comment]
would be awesome if there was LDAP integration!

**Comment by marcelfolaron** [comment]
Hey All,

It is definitely on the roadmap. I can't give an exact timeline but the plan is to release a alpha build with basic ldap functionality and test it in the wild. Determining the minimum viable feature set has been a little difficult. 
Feel free to comment here which features you expect.

**Comment by b90g** [comment]
> Feel free to comment here which features you expect.

LDAP Group Sync would be superb.

**Comment by marcelfolaron** [comment]
Group Sync is an interesting topic.

Here are my thoughts as of right now:

- Settings screen gets ldap settings
- Under users you choose to sync users from your ldap directory
- Users can login using their ldap credentials
- Admins can set a flag to create new users on first login
- New users get a default role (developer/team member), can be set via settings
- Admins can still create users using the old way (clients for example)

With that roles would still be managed within Leantime. Seems that is how Jira works as well. Does that work for everyone?

**Comment by dehive-dev** [comment]
> * Under users you choose to sync users from your ldap directory

Sounds great. Would be nice to have support for multiple LDAP backends (like Jira and OpenProject) so you can include users from multiple directories.
I think user-sync would be great but for a start wouldn't be needed.

**Comment by RalfSoft** [comment]
I would really appreciate it. This makes the user management in my larger company a little bit easier.

**Comment by mfsid** [comment]
I really like centralized management of users.

**Comment by amit510** [comment]
SAML or LDAP please.

**Comment by prakas24** [comment]
SAML please

**Comment by himself1985** [comment]
SSO please!!!!!!1111 thx

**Comment by kazyka** [comment]
Any status on this @marcelfolaron

**Comment by marcelfolaron** [comment]
We have ldap and OIDC.
SAML is most likely coming later this year as a plug-in.
