### ISSUE TITLE
[BUG] Calendar - Adding Event Without Time Fails

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#2320]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ X ] Self Hosted

**Describe the bug**
When adding a calendar even with no "time" inserted it say Event created successfully.  However the event was not created.  The event dialog window reloads as well.  It appears what should be happening is some error to insert time OR check out "all day event" but the error is not visible and it pretends to save the event.

**To Reproduce**
1. Create an event
2. Do not fill in the time or check the all day event box
3. Save your event
4.  You will see the event dialog window reloads and pretends to save the event.

**Expected behavior**
No errors. 

**Leantime Version**
3.0.5

**Server**
NGINX 

**PHP / MySQL Version**
8.1 / MariaDB 10.4

**Additional context**
I have created a video so you can see what the end user is experiencing:
* https://youtu.be/RMa26OoxmTc
* (I also mention in the video that my exported ics file was not importing or validating.  It was not validating because I was able to save an event with only a start time but no end time. This failed ics validation and would not import. So similar root cause)

This is a copy of the log at the point of failure:

Adding Event Listener to request_terminated
[12-Feb-2024 17:49:53 America/Los_Angeles] PHP Fatal error:  Declaration of Leantime\Core\ConsoleKernel::queue(string $command, array $parameters = []) must be compatible with Illuminate\Contracts\Console\Kernel::queue($command, array $parameters = []) in /SM_DATA/web_projects/public_html/app/Core/ConsoleKernel.php on line 241

**Comment by compumatter** [comment]
This may be of some value.  When a new event is opened in Nextcloud it defaults to making the start / end dates "today" and checks the [x] all day event.  When you 'uncheck' the all day checkbox it shows the 'time slots' and prefills them with a 10:00AM begin and 11:00AM end.  Though those times are random, it begs to be changed to the correct time.   Time fields cannot be empty.  If the all day is unchecked, both times must be filled in.  Conversely if 'all day' is checked it hides the time fields and deletes their data so you start anew upon unchecking 'all day'
![image](https://github.com/Leantime/leantime/assets/121611/c6ac9eb6-a12c-4d42-8819-2d21263be0c0)
![image](https://github.com/Leantime/leantime/assets/121611/1a8d2c39-199c-4a51-b364-4283b3da5b8e)

**Comment by marcelfolaron** [comment]
This should be fixed as of 3.1.2 and up. Please re-open if you are still running into this issue
