### ISSUE TITLE
[BUG] Moving Todos (from Edit mode) To Different Project Fails

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#2321]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ X ] Self Hosted

**Describe the bug**
When I attempt to move a todo to different project by editing the todo, selecting a different project and saving - it fails to carry it out and provides no errors.

**To Reproduce**
1. Create a todo and save exit it
2. Edit that todo
3. Click the Project menu and change to a different project
4. Save and Close (or just Save)
5. Says "To-Do was saved successfully"
6. To-Do is not moved

**Expected behavior**
Expected the To-Do to be moved to the other project so that it does not have to be manually recreated.

**Leantime Version**
3.0.5

**Server**
NGINX

**PHP / MySQL Version**
8.1 / MariaDB 10.4

**Additional context**
I have created a video so that you can see what's happening from the users view
* https://www.youtube.com/watch?v=iLHrgSZLFpY

**Comment by compumatter** [comment]
I have just noticed that I am able to move the ToDo using the 3 dot menu and selecting Move To-Do so at least there is a way to get it done for now.
![image](https://github.com/Leantime/leantime/assets/121611/d569dbda-9c5d-4770-9fbe-7ab4ab94cfce)

**Comment by marcelfolaron** [comment]
Should be fixed in 3.1.3
