### ISSUE TITLE
[BUG] Timesheet: time registrations on wrong date

### ISSUE THREAD

**Issue by lilosti** [Leantime/leantime#2322]
**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
Adding a task and putting in 2 hours on monday on my timesheets, saving I see my registration on sunday in the same week.

**To Reproduce**
1. Go to 'Timesheets'
2. Select at task to register time on, register 2 hours on monday
3. Press save
4. See your 2 hours have not been saved on monday (but on sunday)

Try registering time on any day and have fun guessing what will happen...

**Expected behavior**
Time registered on monday is expected to stay on monday

**Leantime Version**
3.0.6

**Server**
Apache, nginx, IIS etc

**PHP / MySQL Version**
Please list the PHP and Mysql version you are using

**Additional context**

**Comment by marcelfolaron** [comment]
Fixed in 3.1.0-beta
