### ISSUE TITLE
[FEATURE] Remove "Not Available in this plan" any time a new project is added

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#2323]
**Is your feature request related to a problem? Please describe.**
When I click on add a new project I am now seeing 2 features that a client does not have.  "Set Direction" and "Map your Steps"  

I recognize the intention is to have the viewer recognize this feature may be of value and possibly purchase it.  To that end, I am a staunch supporter in seeing this project maintaining its future through sustainability.  It's the only way Leantime will be there in the future.

However, because this is "Not available"... is displayed perpetually ie; every time a new project is created, my perception as a user finds this to be the functional equivalent of what is commonly referred to as a "nag screen" ie; a popup with an intention to up sell.  

I am not sure if these plans are online hosting only plans and not available to the self-hosted.  If that is the case at the very least they should not be showing up in the self-hosted environment.  If these plans are in fact available to the self-hosted community, perhaps they should appear in a market-place environment where they can be purchased as they peruse all marketplace offerings.

**Describe the solution you'd like**
When I add a new project I should go straight to creating a new project.

**Additional context**
![image](https://github.com/Leantime/leantime/assets/121611/cf29bd41-422c-41f3-9717-465c1f515fe9)

Thanks again for this product.  I hope we can work together to accomplish both of our goals.

Jay

**Comment by gloriafolaron** [comment]
Jay,

We'll get a more thorough reply here but I want to drop this while I have a second -- The goal is not to "nag sell" here; the plugin marketplace is available as an access point in the system as well. At most, we want to create awareness and offer easy access to investigate.

We're in the process of updating onboarding flows right now and will make sure to take a look at this section as well. I appreciate you pointing it out -- it's helpful in calling awareness to it.

**Comment by compumatter** [comment]
Thank you Gloria.  Thanks for the reply!

I recognize the need to create awareness.  It's just this happens every time a new project is created.  As a user I would have of course realized these features were not available to me after the first few times of seeing it.  I feel having a link called "marketplace" or Leantime apps, visible within the software dashboard provides that awareness in a logical way.  I had certainly seen that straight away.

**Comment by gloriafolaron** [comment]
Updating here but also to add that I've sent you an email as well. We've since updated our Support Leantime plugin to now remove these links. 

More details can be found here: [](https://leantime.io/ultimate-small-team-bundle-and-ad-free-sponsorship-plugin/)
