### ISSUE TITLE
[FEATURE] Air-Gapped System Options

### ISSUE THREAD

**Issue by icewolf69** [Leantime/leantime#2324]
**Is your feature request related to a problem? Please describe.**
It seems that Leantime 3 leans a bit more into plugins, feeds, integrations, etc.  Which I absolutely understand to remain competitive and also to generate potential revenue. The issue that we have with the new version of Leantime, is that the features that reach out to the internet to populate either slow performance or hinder navigation of the application.  For example, the feature under the lightning bolt menu, which I believe is the Leantime news/updates/feed menu, seems to pop up automatically on every page displaying a "500" error.  I cannot seem to minimize/remove this pop up.  Picture attached.

**Describe the solution you'd like**
I am requesting a configuration option available through the GUI, configuration files, or environmental variables, that disables features that need to reach out to the internet to function. 

**Additional context**
[Steps to produce]
Disconnect the docker container from the internet
Start the leantime application and database containers
login to leantime, news menu pops up automatically.

Screenshot attached.
![leantime_3](https://github.com/Leantime/leantime/assets/21128941/7230519a-7e50-4094-bfc9-fd2bb8ddb539)

**Comment by marcelfolaron** [comment]
Thanks for bringing this to my attention. This should indeed not happen and
just silently fail. I will take a look at this.

**Comment by marcelfolaron** [comment]
Fixed in 3.1.0-beta
