### ISSUE TITLE
Docker does not work

### ISSUE THREAD

**Issue by sitthykun** [Leantime/leantime#233]
The statement that I copy and paste does not work by showing error as
docker: Error response from daemon: network leantime-net not found

Here the command.
$ docker run -d -p 80:80 --network leantime-net -e DB_HOST=mysql_leantime -e MYSQL_USER=admin -e MYSQL_PASSWORD=321.qwerty -e MYSQL_DATABASE=leantime --name leantime leantime/leantime:latest

Others docker file work properly, could you help me to list any solution.
I have no idea now. thanks

**Comment by marcelfolaron** [comment]
You'll have to create the leantime-net first. You can follow the full set up instructions for docker here: https://github.com/Leantime/docker-leantime this included network, mysql and the leantime docker instance

**Comment by marcelfolaron** [comment]
Were you able to resolve the issue?

**Comment by marcelfolaron** [comment]
I will close this issue for now. If you are still having trouble please feel free to open the issue again or reach out on [https://community.leantime.io/](https://community.leantime.io/)

**Comment by sitthykun** [comment]
It's fine now. 
yes, I got confused for that doc. :)
Thank you so much
