### ISSUE TITLE
[BUG] Remove outdated duplicate files to avoid file collission on case-insensitive filesystem

### ISSUE THREAD

**Issue by martinyde** [Leantime/leantime#2330]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
When cloning this repository into a case-insensitive filesystem there are a few file collisions, mainly in the public/assets/images/Screenshots folder.
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'public/assets/images/Screenshots/Blueprints.png'
  'public/assets/images/Screenshots/blueprints.png'
  'public/assets/images/Screenshots/Calendar.png'
  'public/assets/images/Screenshots/calendar.png'
  'public/assets/images/Screenshots/Docs.png'
  'public/assets/images/Screenshots/docs.png'
  'public/assets/images/Screenshots/Goals.png'
  'public/assets/images/Screenshots/goals.png'
  'public/assets/images/Screenshots/ProjectDashboard.png'
  'public/assets/images/Screenshots/projectDashboard.png'
  'public/assets/lottie/leo/Pirate.json'
  'public/assets/lottie/leo/pirate.json'
  ```

**To Reproduce**
1. Clone the repository into a case-insensitive filesystem

**Expected behavior**
The repo clones without file collision.

**Leantime Version**
v3.0.6

**Comment by marcelfolaron** [comment]
Fixed in 3.1.0-beta
