### ISSUE TITLE
[BUG] Theme is reset when logging out

### ISSUE THREAD

**Issue by gamedevkirk** [Leantime/leantime#2335]
**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
After logging out, the selected theme is reset and not restored upon logging in again.
Navigating to "Themes" and clicking "Save" restores the previous theme settings. Based on this, It seems they're being saved but not reloaded properly when logging back in.

**To Reproduce**
1. Login
2. Navigate to "Themes"
3. Switch to dark mode
4. Save
5. Log out
6. Login
7. Theme has been reverted

**Expected behavior**
The theme from the previous session should be maintained

**Leantime Version**
v3.0.6

**Server**
Nginx

**PHP / MySQL Version**
PHP 8.1.2-1ubuntu2.14
mysql  Ver 15.1 Distrib 10.6.16-MariaDB, for debian-linux-gnu (x86_64)

**Additional context**
LEAN_KEEP_THEME is set to true, but this does not seem to function either. The login page always defaults back to light theme.

**Comment by marcelfolaron** [comment]
Fixed in 3.1.0-beta
