### ISSUE TITLE
Description box doesn't show up

### ISSUE THREAD

**Issue by GPGrieco** [Leantime/leantime#235]
When creating a new project or a new idea the page loads with the title and description box, and then the description box immediately disappears and there is no way to input a description. I have tried this in both Firefox and Chrome. I have the same issue with different projects. This is on a fresh install of Ubuntu Server.

Leantime Version 2.1.0
Ubuntu Server Version 20.04 with system fully updated
Apache version: 2.4.41
PHP Version 7.4.3
MySql Version 8.0.19-0ubuntu5

**Comment by marcelfolaron** [comment]
This is odd. Do you see any Javascript errors in the developer console (F12 in chrome)?

**Comment by GPGrieco** [comment]
Here is the errors that show up in the developer console.

`JQMIGRATE: Migrate is installed, version 1.4.1
plugin.js:16 Text color plugin is now built in to the core editor, please remove it from your editor configuration
(anonymous) @ jquery.nyroModal.custom.js:938
skin.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
content.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
2content.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
skin.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
content.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for http://192.168.0.5/leantime/css/bootstrap-grid.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by marcelfolaron** [comment]
Seems you are running Leantime in a subfolder? Did you set the appURL?

**Comment by GPGrieco** [comment]
Yes I did. I couldn't get the app to load at all before I set that so I am pretty sure that is done correctly. Here is what it is set to:
` public $appUrl = "http://192.168.0.5/leantime";`

**Comment by marcelfolaron** [comment]
I see, I think I know what the problem is. There were a few places where we
missed to set appURL before the library path. Let me double check. I've
been chasing a few of those today. Will cut a release later tonight.
