### ISSUE TITLE
[FEATURE] Console commands to install (and uninstall etc.) plugins

### ISSUE THREAD

**Issue by rimi-itk** [Leantime/leantime#2363]
**Is your feature request related to a problem? Please describe.**
During (plugin) development and deployment, a console command for installing and enabling a plugin would come in handy.

**Describe the solution you'd like**
I'd like to be able to install, enable, disable and remove (uninstall) a plugin using the `bin/leantime` command.

**Comment by marcelfolaron** [comment]
Fixed in 3.1.0-beta
