### ISSUE TITLE
[BUG] Error 500 on new user with OIDC login

### ISSUE THREAD

**Issue by pablopoo** [Leantime/leantime#2366]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X ] Self Hosted

**Describe the bug**
When a new user log-in for the first time using a OIDC connector, the user get an error 500 on home page.
Error log:
[error_log_lt.log](https://github.com/Leantime/leantime/files/14463131/error_log_lt.log)

**To Reproduce**
1. Login-in with a new account using OIDC, using an email that do not exist on user DB.
2. The user is created successfully.
3. An error 500 is displayed on that user account.
4. Using an admin account, assign the user to a project. 
5. The user now can use the platform. 

**Expected behavior**
If the user have no projects, show a button to request access.

**Leantime Version**
3.0.7

**Server**
Docker version.

**PHP / MySQL Version**
Docker version

**Additional context**
.-

**Comment by marcelfolaron** [comment]
Fixed in 3.1.0-beta
