### ISSUE TITLE
[BUG] Error 500 on 3.0.7

### ISSUE THREAD

**Issue by hnegadi** [Leantime/leantime#2368]
Hello.

We posted an issue on github but I'm not sure it's the appropriate place.
We are having an error 500 issue with our leantime ubuntu 20.04 virtual machine running PHP 8.2.15 (cli) (built: Jan 20 2024 14:16:39) (NTS) Zend Engine v4.2.15, Copyright (c) Zend Technologies
with Zend OPcache v8.2.15, Copyright (c), by Zend Technologies

Please find bellow /var/www/leantime_3.0.7/logs/error.log contents

[01-Mar-2024 21:09:26 UTC] PHP Fatal error:  Uncaught Error: Undefined constant PDO::MYSQL_ATTR_INIT_COMMAND in /var/www/leantime_3.0.7/app/Core/Db.php:67
Stack trace:
#0 [internal function]: Leantime\Core\Db->__construct()
#1 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs()
#2 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(292): Illuminate\Container\Container->build()
#3 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(885): Illuminate\Container\Container->Illuminate\Container\{closure}()
#4 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build()
#5 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve()
#6 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(1043): Illuminate\Container\Container->make()
#7 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(959): Illuminate\Container\Container->resolveClass()
#8 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(920): Illuminate\Container\Container->resolveDependencies()
#9 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build()
#10 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve()
#11 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(1043): Illuminate\Container\Container->make()
#12 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(959): Illuminate\Container\Container->resolveClass()
#13 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(920): Illuminate\Container\Container->resolveDependencies()
#14 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(292): Illuminate\Container\Container->build()
#15 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(885): Illuminate\Container\Container->Illuminate\Container\{closure}()
#16 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build()
#17 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve()
#18 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(1043): Illuminate\Container\Container->make()
#19 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(959): Illuminate\Container\Container->resolveClass()
#20 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(920): Illuminate\Container\Container->resolveDependencies()
#21 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build()
#22 /var/www/leantime_3.0.7/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve()
#23 /var/www/leantime_3.0.7/app/Core/HttpKernel.php(77): Illuminate\Container\Container->make()
#24 /var/www/leantime_3.0.7/app/Core/Bootloader.php(303): Leantime\Core\HttpKernel->handle()
#25 /var/www/leantime_3.0.7/app/Core/Bootloader.php(173): Leantime\Core\Bootloader->handleRequest()
#26 /var/www/leantime_3.0.7/public/index.php(18): Leantime\Core\Bootloader->boot()
#27 {main}
  thrown in /var/www/leantime_3.0.7/app/Core/Db.php on line 67S

Thank you in advance and sorry for bothering if the issue is on our end.

-H.

**Comment by hnegadi** [comment]
It seems that forcing VM to run php 8.1 got it to work, we are closing the issue but we are curious to see which versions of php are actually supported.

**Comment by marcelfolaron** [comment]
8.1+ is supported. The above issue is actually related to the mysql pdo
extension. It was probably not installed on 8.2
