### ISSUE TITLE
[BUG] Finishing create user profile from link results i ERROR 500

### ISSUE THREAD

**Issue by lilosti** [Leantime/leantime#2379]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X ] Self Hosted

**Describe the bug**
When trying to finish user creation we are shown an error 500.

**To Reproduce**
1. Create a new user - send email to finish user creation
2. Click on link in email
3. Fill out forms and questions
4. After filling out last page See error

https://app.screencast.com/Gm3TdMvIsPEf9

**Expected behavior**
New user is created and can sign in

**Leantime Version**
3.+

**Server**
Apache, nginx, IIS etc

**PHP / MySQL Version**
Please list the PHP and Mysql version you are using

**Additional context**

**Comment by marcelfolaron** [comment]
Fixed in 3.1.0-beta
