### ISSUE TITLE
To-Dos page error

### ISSUE THREAD

**Issue by js325** [Leantime/leantime#238]
I am just trialing this software to check suitability and all seems to be working except when i click on the To-Do menu on the left, I get a blank page. I have it installed in a "projects" sub-domain and the to-dos link is trying to open http://domainname/projects/projects/tickets/showKanban.
If i manually remove one of the /projects in the above link, the page displays.

**Comment by King-GO** [comment]
Yes, I also encounter this situation. 
It was installed in sub-folder follow by instruction
```
Uncomment line 4 in public/.htaccess and change to
**RewriteBase /Leantime/**
Set public $appURL in config\configuration.php to the http://xxx.com/Leantime
```
windows 7, XAMPP

**Comment by marcelfolaron** [comment]
Thanks for reporting. Did you set the appURL in the configuration file?

I'll double check the routes in case of a subfolder installation again.

**Comment by frode81** [comment]
Have the same problem, and yes it was also installed withe instructions as King-GO comments.
And have set the appURL in config file.

Seems like there is something with the api also : i have installed in https://domain.com/leantime/
But the api url`s are like this https://domain.com/api/users?profileImage=currentUser, works if i correct the url to https://domain.com/leantime/api/users?profileImage=currentUser

**Comment by marcelfolaron** [comment]
Thanks all. I will take a look at that today.

**Comment by js325** [comment]
Thanks Marcel,
Just to add, when I first click on to-do's after logging in, I get the correct page http://url/projects/tickets/showKanban. 
If I hover/click over the to-do link menu after that, I get the link http://url/projects/projects/tickets/showKanban - my installation sub-directory is projects but as you can see, there is a repeated subdomain in the link.

**Comment by marcelfolaron** [comment]
Thanks for the details. I found the issue and submitted a fix to master.

https://github.com/Leantime/leantime/pull/241

The method that detects the path after appURL had a bug.

I would like to run a few more tests before I cut the release tomorrow.

**Comment by js325** [comment]
Great stuff! 
Thanks again

**Comment by King-GO** [comment]
upgrade to version 2.1.1 this bug is still there

> In research menu,
> Who are the Customers > add new **An error occured**

**Comment by marcelfolaron** [comment]
Is that only happening in that one link for you?

**Comment by King-GO** [comment]
YES

**Comment by marcelfolaron** [comment]
Ahh, I am sorry. I just found it. I was testing on the full lean canvas page and missed the simple.
PR is out https://github.com/Leantime/leantime/pull/248

In the meantime you can still create a customer segment on the Full Leancanvas. This will also appear on the simple canvas.

**Comment by King-GO** [comment]
One more Error 404
Project Settings > Project Details > Team Members >
Choose the users that will have access to this project. Add more users here
then
**Object not found!**

**Comment by thehellrider** [comment]
I have a similar problem. I installed last version 2.4.1 in a shared host in Ionos under a subdirectory named 'projects' and changed the configuration file to "public $appUrl = "https://www.mydomain.com/projects/public" 
and the public folder .htaccess to 
RewriteBase /projects/public/ 

This allowed me to run everything seeems working fine but the ToDos missing link is pointing to :
https://www.mydomain.com/projects/public/projects/public/tickets/showKanban

the correct link that shows the ToDos page must be:
https://www.mydomain.com/projects/public/tickets/showKanban

Also when you try to save a new task the page redirects to a 404 page :
https://www.mydomain.com/tickets/newTicket
when it must be I suppose:
https://www.mydomain.com/projects/public/tickets/newTicket

It's something about the routes I guess. Thanks for your help and congrats for this top quality project manager.

**Comment by spokobg** [comment]
@thehellrider,
I have the same configuration ->  "public $appUrl = "https://www.mydomain.com/leantime/public"
and the public folder .htaccess to
RewriteBase /leantime/public/
and had the same 404 errors as you.
I managed to fix it by changing line 14 in index.php from:
 define('CURRENT_URL', $config->appUrl.$settings->getRequestURI($config->appUrl));
to:
    define('CURRENT_URL', $settings->getRequestURI($config->appUrl));
All seems to be working fine now.

**Comment by dee1337** [comment]
The issue appears again in the current version. @spokobg's solution still works as fix.

**Comment by TimexPeachtree** [comment]
Yes had same issue with IIS 10 on Windows @spokobg solution works with latest 2.2.7
