### ISSUE TITLE
[BUG] wrong project when your not part of Team

### ISSUE THREAD

**Issue by Anna-itk** [Leantime/leantime#2388]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
Even if I'm not part of the team I can see all the projects and also create new To do. But when I see the To do create modal (and I'm not part of the team for that project) it shows me a different project (that I'm part of) in the project dropdown. This is very confusing

**To Reproduce**
1. Go to a project where your not a part of the team
2. Click on To do's
3. Click on 'New' and choose 'Add To do'
4. See that in the project dropdown it's not the current project that is showed but a different project

**Expected behavior**
As admin and owner I would expect that I could see projects where I'm not part of the Team but not be able to create a new to do. For roles with less rights I would expect not to see the project at all.

**Leantime Version**
Leantime version 3.0.7

**Comment by marcelfolaron** [comment]
Fixed in 3.1.0-beta
