### ISSUE TITLE
[BUG] Link to settings are shown when a plugin is not enabled.

### ISSUE THREAD

**Issue by rimi-itk** [Leantime/leantime#2389]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ ] Self Hosted

**Describe the bug**
The plugin list shows the “Settings” link for all installed plugins. Only plugins that are *enabled* should have the Settings link.
![Screen Shot 2024-03-11 at 11 35 22](https://github.com/Leantime/leantime/assets/11267554/6cb24c23-f208-4cfc-8e79-4b20e3e9adf0)

**To Reproduce**
1. Go to `/plugins/myapps`
2. Install a plugin with settings.
3. Click “Settings” 
4. Notice “Page not found”

**Expected behavior**
Only enabled plugins should have the “Settings” link.

**Leantime Version**
https://github.com/Leantime/leantime/releases/tag/v3.0.7

**Comment by marcelfolaron** [comment]
Fixed in 3.1.0-beta
