### ISSUE TITLE
Integration to GIT (Github, Gitea, Bitbucket et al)?

### ISSUE THREAD

**Issue by baradhili** [Leantime/leantime#239]
It would be nice to have an integration to GIT.

As a MVP just a place to put a URL to the repo would be a start, but it would be also nice to be able to link branches to tasks/cards etc..

**Comment by marcelfolaron** [comment]
Thanks for the request. Would you want to add that link to the project level or To-Do level?

**Comment by baradhili** [comment]
Thanks.. I would add it to the project level I think.

**Comment by baradhili** [comment]
having a sniff around Gitea which I use normally.. the API looks quite straight forward.. https://try.gitea.io/api/swagger  I might dig through the leantime code and work out where integrations should sit and give it a go..

**Comment by marcelfolaron** [comment]
Let me know if you have any questions. Happy to do a code walk through

**Comment by kimberely27** [comment]
Any updates? :) This would be awesome!

**Comment by leogaggl** [comment]
Is this being looked at currently? This would be a huge boost for us being able to use Leantime with software projects.

From a practical perspective, I would see the logical mapping like this:

- Leantime ToDo --> GIT Issue
- Leantime Milestone --> GIT Release

This seems a natural flow between the 2 systems from my p.o.v.

Happy to be involved in testing / assistance.

**Comment by samueldelamotte** [comment]
BUMP!

Our current project management solution revolves heavily around Leantime for all of our software development projects and it would streamline our workflows if Leantime integrated with GIT.

I am also able to help out with testing if needed!!!

**Comment by leogaggl** [comment]
Actually - add GitLab as another GIT implementation.

Happy to assist with GitLab (preferred) and GitHub testing and bugfixing.

**Comment by FeryET** [comment]
Hello. Is there any update on this feature? Thanks!

**Comment by marcelfolaron** [comment]
As of 3.2.0 we are supporting Zapier integrations. The alpha app is available here https://zapier.com/developer/public-invite/207240/cac6ec7a911bd5fa7924f38230d58d2f/
