### ISSUE TITLE
Update import CSV URL

### ISSUE THREAD

**Issue by vid-pas** [Leantime/leantime#2401]
**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
On the csv import page the documentation link is broken 

**To Reproduce**
1. Go to http://localhost:57143/connector/integration?provider=csv_importer#/csvImport/upload
2. Click on '[Check our documentaiton](https://support.leantime.io/support/solutions/articles/154000063304-importing-data-via-csv)'
3. See error 'Uh-Oh. This page knows nothing.'

**Expected behavior**
Land on the CSV import help page; currently here: https://support.leantime.io/importing-data-via-csv

**Leantime Version**
Which Leantime version are you using
Latest master:
`a13b28c (grafted) Merge pull request #2399 from Leantime/snyk-upgrade-5ac0841a0aa8a08a67be95308cc04a84 Marcel Folaron Tue Mar 12 10:45:24 2024`

**Server**
Docker

**Comment by vid-pas** [comment]
Put in a PR for this

**Comment by marcelfolaron** [comment]
Fixed in 3.2.0
