### ISSUE TITLE
[BUG] Warning: syntax error, unexpected '(' in app/Language/en-US.ini on line 582

### ISSUE THREAD

**Issue by rimi-itk** [Leantime/leantime#2413]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**

https://github.com/Leantime/leantime/commit/c0e86ffbf432cd9aaeec152f113b3007fbc28b34 introduces a newline character after line 581 `app/Language/en-US.ini` (in the `text.full_lean_canvas_helper_content` key):

https://github.com/Leantime/leantime/blob/c0e86ffbf432cd9aaeec152f113b3007fbc28b34/app/Language/en-US.ini#L581-L582

This leads to a parser warning

> Warning: syntax error, unexpected '(' in app/Language/en-US.ini on line 582 

and the value for the key `text.full_lean_canvas_helper_content` is `null`.

**To Reproduce**
1. Update Leantime to https://github.com/Leantime/leantime/commit/c0e86ffbf432cd9aaeec152f113b3007fbc28b34
2. Enable debugging by setting `LEAN_DEBUG = 1` in `config/.env`
3. Load any Leantime page
4. See warning

**Expected behavior**
The ini file should net generate anyw warnings.

**Leantime Version**
https://github.com/Leantime/leantime/commit/c0e86ffbf432cd9aaeec152f113b3007fbc28b34

**PHP / MySQL Version**
`PHP 8.1.27 (cli) (built: Dec 21 2023 20:19:54) (NTS)`

**Comment by marcelfolaron** [comment]
Fixed in 3.1.0-beta
