### ISSUE TITLE
Page loading is very very slow.

### ISSUE THREAD

**Issue by monkeyotg** [Leantime/leantime#2419]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
These pages load very, very slowly, see the attached screenshots.
![Snipaste_2024-03-17_23-08-28](https://github.com/Leantime/leantime/assets/8792193/6e2a5ef3-7c31-47d4-845c-6000c87aa95c)
![Snipaste_2024-03-17_23-09-50](https://github.com/Leantime/leantime/assets/8792193/445336e7-49e7-424d-a29c-fa5a060d4343)
![Snipaste_2024-03-17_23-11-21](https://github.com/Leantime/leantime/assets/8792193/45348529-4660-4d56-812b-bf0874258aab)
![Snipaste_2024-03-17_23-12-38](https://github.com/Leantime/leantime/assets/8792193/cc1d3600-ae8b-496c-b41d-b85e61bb883f)
![Snipaste_2024-03-17_23-14-23](https://github.com/Leantime/leantime/assets/8792193/32bcb916-bef1-46cd-a8ca-8fd8b81f342a)
![Snipaste_2024-03-17_23-15-42](https://github.com/Leantime/leantime/assets/8792193/653db3e8-15bf-4cb3-a2b4-0251fc9b6bbc)

**To Reproduce**
1. just open the page in the browser (tested with different browsers: Chrome, Brave, Edge, Firefox, no difference)

**Expected behavior**

**Leantime Version**
latest

**Server**
Docker Desktop on Windows Server 2022
No indication that CPU and memory are maxed out.
Intel N100 + Docker: 3bg RAM

**PHP / MySQL Version**
mysql:8.0

**Additional context**
I've noticed this problem the first time launched Leantime. And after issues are added. It gets more terrible.

**Comment by marcelfolaron** [comment]
Hard to say what the issue is here. I can't reproduce this on our development environments or in our production systems. We do run everything on Linux though. I am not sure how exactly windows handles docker and which image you are using right now .

**Comment by monkeyotg** [comment]
I know what caused it now:
I added customized DNS configuration in Docker

```
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "dns": [
    "9.9.9.9",
    "8.8.8.8",
    "8.8.4.4"
  ],
  "experimental": true
```

without making this change, leantime can not resolve domain in the container, without DNS means no SMTP...

**Comment by marcelfolaron** [comment]
Thanks for the update.

**Comment by marcelfolaron** [comment]
We have not encountered this issue anywhere else. It seems to be connected
to your local set up. Did you set up a special network for the Leantime
container?
