### ISSUE TITLE
Error in hour duration for a Milestone

### ISSUE THREAD

**Issue by cesalo** [Leantime/leantime#243]
**Describe the bug**
Created 3 Milestones and then tasks for each one of them as shown below.
Task 1 (40h) -> Milestone 1
Task 2 (20h) -> Milestone 2
Task 3 (20h) -> Milestone 2
Task 4 (30h) -> Milestone 3

According with this the total per Milestone are as follows:

Milestone 1 -> 40h
Milestone 2 -> 40h
Milestone 3 -> 30h

![Screenshot from 2020-05-02 14-22-29](https://user-images.githubusercontent.com/16859916/80872527-767fa200-8c80-11ea-9200-9e1c164f2b61.png)

If I go to the Milestones page and choose "Table View" the totals of hours are fine except for Milestone 1. This one shows double the hours:

![Screenshot from 2020-05-02 14-24-16](https://user-images.githubusercontent.com/16859916/80872556-a3cc5000-8c80-11ea-905c-cb128e9004b5.png)

**To Reproduce**

Create the milestones and tasks as described above.

**Expected behavior**
Milestone 1 to have 40h total.

**Leantime Version**
Just installed 2.1 using docker yesterday.

**Server**
Used instructions here: https://github.com/Leantime/docker-leantime

**PHP / MySQL Version**
Used instructions here: https://github.com/Leantime/docker-leantime

**Additional context**
I also noticed additionally that all tasks are assigned to the Sprint: backlog even though I'm not using sprints at all.

![Screenshot from 2020-05-02 14-22-29](https://user-images.githubusercontent.com/16859916/80872656-41278400-8c81-11ea-9432-2771b540aa55.png)

Not sure if this is by design or a BUG. I could open another issue in github if needed.

**Comment by cesalo** [comment]
There seems to be an issue with how the time logged is calculated for tasks based on timesheet entries:
For example this task has just 23.2h logged:

![Screenshot from 2020-05-02 15-32-50](https://user-images.githubusercontent.com/16859916/80882965-ded38100-8c8a-11ea-885e-cec6fd4a2139.png)

but in the task view is shows double:

![Screenshot from 2020-05-02 15-32-32-mod](https://user-images.githubusercontent.com/16859916/80883097-e8f57f80-8c8a-11ea-96eb-bfdde03e8484.png)

Not sure if this is related but may be.

**Comment by marcelfolaron** [comment]
Thanks for reporting. I will take a look at it.

**Comment by marcelfolaron** [comment]
I see the bug and have a fix ready. Will submit here soon and it should go out with a release tonight
