### ISSUE TITLE
[BUG] Issue with File Opening/Downloading in Leantime Application

### ISSUE THREAD

**Issue by Frubilarc** [Leantime/leantime#2439]
Hello,

I hope you're having a great day. I'm reaching out to you regarding the following matter.

On Thursday, 14/03, users of our Leantime tool, which is hosted on our Cloudron platform, reported encountering issues with opening/downloading files from the application.

We kindly request your assistance in resolving this matter promptly to ensure uninterrupted user productivity.

I tried again from another browser and the issue persists.

![image](https://github.com/Leantime/leantime/assets/129025326/a4614fa3-4086-4269-b79b-48085009be0f)

I will send you the step-by-step process I follow to download the documents and the error message I receive.

I log into Leantime and navigate to the projects:

![image](https://github.com/Leantime/leantime/assets/129025326/7f33f272-3279-47c4-847b-d2f5a165729c)

Then I select an activity:

![image](https://github.com/Leantime/leantime/assets/129025326/8c91f1bc-08e2-4618-a9a2-8d6909f8838b)

I try to download any of these files associated with the activity:

![image](https://github.com/Leantime/leantime/assets/129025326/e703fce1-c325-4f54-9b8d-89f878991f03)

But when I attempt to download:

![image](https://github.com/Leantime/leantime/assets/129025326/091d1d07-4b5a-4b9a-8335-76b186ff7876)

I encounter the following error:

![image](https://github.com/Leantime/leantime/assets/129025326/90efdda0-a13b-4337-ba0a-c33656d0545f)

I have already tried with another browser and the problem persists.

**Comment by gramakri** [comment]
This should be resolved by https://github.com/Leantime/leantime/pull/2431
