### ISSUE TITLE
[BUG] Responsive Kanban layout To-Dos

### ISSUE THREAD

**Issue by SZEINER** [Leantime/leantime#2447]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Self Hosted

When multiple "Columns" are added to the To-Dos the entire section is subsequently dropped. Tested on 11 "columns". If the whole content is zoomed out in the browser it will balance out. The automatic expansion process does not work.

**Zoom 100%**
![obrazek](https://github.com/Leantime/leantime/assets/77299927/05d1595a-e506-4f0a-a40b-5da3791dde92)

**Zoom Out 60%**
![obrazek](https://github.com/Leantime/leantime/assets/77299927/389c652d-2b1a-4d96-9769-4cbf628443e7)

**Leantime Version**
3.0.7

**Server**
Apache

**PHP / MySQL Version**
PHP 8.2 / MySQL 10.7.3-MariaDB

**Comment by marcelfolaron** [comment]
Sorry for the delay, but this should be fixed as of 3.1.x
