### ISSUE TITLE
[BUG] Upgrade docker leantime 3.0.7 to 3.1.1 doesn't work

### ISSUE THREAD

**Issue by reece146** [Leantime/leantime#2454]
**What set up are you using**
* [ ] Cloud Hosted Version
* [ X ] Self Hosted

**Describe the bug**

Trying to upgrade from leantime/leantime:3.0.7 to leantime/leantime:3.1.1.

Container loads fine according to docker but when I navigate to the web site nothing appears. Viewing source is a page with nothing but the number 1 on the page.

**PHP / MySQL Version**
Please list the PHP and Mysql version you are using

MariaDB 10.8.2

**Additional context**

To be clear, if I roll back the container to 3.0.7 it seems to work fine.

No error logs in /var/www/html/logs

Ideas?

**Comment by ndgayan** [comment]
Below are the parts of the error log.

leantime  | NOTICE: PHP message: PHP Warning:  file_put_contents(/var/www/html/cache/installation/c6/92/c692273deb2772da307ffe37041fef77bf4baa97): Failed to open stream: No such file or directory in /var/www/html/vendor/illuminate/filesystem/Filesystem.php on line 190

leantime  | NOTICE: PHP message: PHP Warning:  file_put_contents(/var/www/html/cache/installation/5b/ac/5bac1d3aee24b76ccad2a413c6a76d4780014219): Failed to open stream: No such file or directory in /var/www/html/vendor/illuminate/filesystem/Filesystem.php on line 190

leantime  | NOTICE: PHP message: PHP Warning:  file_put_contents(/var/www/html/cache/09d49f92-b7e4-4952-9ea2-c847f00adfe0/85/84/85841abddb12dc3591a5990c6527df65a5e63c87): Failed to open stream: No such file or directory in /var/www/html/vendor/illuminate/filesystem/Filesystem.php on line 190

leantime  | NOTICE: PHP message: PHP Warning:  file_put_contents(/var/www/html/cache/views/abcad8e5a22bd29aaabbc2b51e223bacc196be9c.php): Failed to open stream: Permission denied in /var/www/html/vendor/illuminate/filesystem/Filesystem.php on line 190
leantime  | NOTICE: PHP message: Illuminate\Contracts\Filesystem\FileNotFoundException: File does not exist at path /var/www/html/cache/views/abcad8e5a22bd29aaabbc2b51e223bacc196be9c.php. in /var/www/html/vendor/illuminate/filesystem/Filesystem.php:113

**Comment by EHRETic** [comment]
Hi,

Same issue there, logon page won't load up (ERROR 500) but rollback to 3.0.7 works fine.

Some logs:
`127.0.0.1 -  03/Apr/2024:08:15:46 +0000 "GET /index.php" 500
NOTICE: PHP message: PHP Fatal error:  Uncaught Illuminate\Contracts\Filesystem\FileNotFoundException: File does not exist at path /var/www/html/cache/views/edf299eb4370dce66f71099b13d581c6da5749e0.php. in /var/www/html/vendor/illuminate/filesystem/Filesystem.php:113
Stack trace:
#0 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/var/www/html/c...', Array)
#1 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/c...', Array)
#2 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/a...', Array)
#3 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#4 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#5 /var/www/html/app/Core/Template.php(509): Illuminate\View\View->render()
#6 /var/www/html/app/Core/HttpKernel.php(77): Leantime\Core\Template->display('errors.error500', 'global::layouts...')
#7 /var/www/html/app/Core/Bootloader.php(303): Leantime\Core\HttpKernel->handle(Object(Leantime\Core\IncomingRequest))
#8 /var/www/html/app/Core/Bootloader.php(173): Leantime\Core\Bootloader->handleRequest()
#9 /var/www/html/public/index.php(18): Leantime\Core\Bootloader->boot()
#10 {main}
Next Illuminate\View\ViewException: File`

**Comment by andyberry** [comment]
Same symptom (blank login screen):
snips from log:

NOTICE: PHP message: PHP Warning:  file_put_contents(/var/www/html/cache/views/edf299eb4370dce66f71099b13d581c6da5749e0.php): Failed to open stream: Permission denied in /var/www/html/vendor/illuminate/filesystem/Filesystem.php on line 190
NOTICE: PHP message: PHP Fatal error:  Uncaught Illuminate\Contracts\Filesystem\FileNotFoundException: File does not exist at path /var/www/html/cache/views/edf299eb4370dce66f71099b13d581c6da5749e0.php. in /var/www/html/vendor/illuminate/filesystem/Filesystem.php:113
Stack trace:
#0 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/var/www/html/c...', Array)
#1 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/c...', Array)
#2 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/a...', Array)
#3 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#4 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#5 /var/www/html/app/Core/Template.php(509): Illuminate\View\View->render()
#6 /var/www/html/app/Core/HttpKernel.php(77): Leantime\Core\Template->display('errors.error500', 'global::layouts...')
#7 /var/www/html/app/Core/Bootloader.php(303): Leantime\Core\HttpKernel->handle(Object(Leantime\Core\IncomingRequest))
#8 /var/www/html/app/Core/Bootloader.php(173): Leantime\Core\Bootloader->handleRequest()
#9 /var/www/html/public/index.php(18): Leantime\Core\Bootloader->boot()
#10 {main}
Next Illuminate\View\ViewException: File does not exist at path /var/www/html/cache/views/edf299eb4370dce66f71099b13d581c6da5749e0.php. (View: /var/www/html/app/Views/Templates/layouts/error.blade.php) in /var/www/html/vendor/illuminate/filesystem/Filesystem.php:113
Stack trace:
#0 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Illuminate\Contracts\Filesystem\FileNotFoundException), 0)
#1 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/c...', Array)
#2 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/a...', Array)
#3 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#4 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#5 /var/www/html/app/Core/Template.php(509): Illuminate\View\View->render()
#6 /var/www/html/app/Core/HttpKernel.php(77): Leantime\Core\Template->display('errors.error500', 'global::layouts...')
#7 /var/www/html/app/Core/Bootloader.php(303): Leantime\Core\HttpKernel->handle(Object(Leantime\Core\IncomingRequest))
#8 /var/www/html/app/Core/Bootloader.php(173): Leantime\Core\Bootloader->handleRequest()
#9 /var/www/html/public/index.php(18): Leantime\Core\Bootloader->boot()
#10 {main}
  thrown in /var/www/html/vendor/illuminate/filesystem/Filesystem.php on line 113

**Comment by mariushosting** [comment]
@marcelfolaron same issue here. The new version completely broken the selfhosted image.

**Comment by gecexgokyuzu** [comment]
Same issue also here, illuminate plugin seems to have changed or missing

**Comment by rqi14** [comment]
Same issue

**Comment by austinatose** [comment]
same issue here

**Comment by previmeteo** [comment]
chown www-data:www-data -R /var/www/html/cache solved the problem on docker install

**Comment by reece146** [comment]
Confirmed - this fixed it on my end. Casual clicking around appears everything works.

**Comment by marcelfolaron** [comment]
Hi All,

I went ahead and updated the permissions as part of the Dockerfile and that should fix the issue. Both latest and :3.1.1 were recreated with the new settings.

**Comment by EHRETic** [comment]
Hi,

I confirm, it works fine with 3.1.1

Thanks @marcelfolaron ! 👌
