### ISSUE TITLE
[BUG] Company Manager can see the 'Company' link at the header

### ISSUE THREAD

**Issue by darren-teo** [Leantime/leantime#2456]
**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
User with the Company Manager role is able to see the "Company" link at the header. However, upon clicking the link, the user will be  presented with a 403 error. A Company Manager should not be able to edit company settings, hence should not see that link.

**To Reproduce**
1. Log in with as a user with Company Manager role.
2. Click on 'Company' in the header.
3. The user sees a 403 error page.

**Expected behavior**
The 'Company' link in the header should not visible to a Company Manager.

**Leantime Version**
3.1.1 (docker image)

**MySQL Version**
Latest 8.3.0 version

**Comment by marcelfolaron** [comment]
Fixed in 3.1.2

**Comment by mjut** [comment]
I am running into the same issue – in 3.2.1.
