### ISSUE TITLE
[BUG] Tutorials showing on every login and theming reverts back to default

### ISSUE THREAD

**Issue by Tattersson** [Leantime/leantime#2457]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [x] Cloud Hosted Version
* [X ] Self Hosted

**Describe the bug**
Tutorials are shown after every login. After every login these tutorials/tours are shown on all pages. No matter if I've just logged in and logged out. I think this might not be bug, but rather a permission error on our on-prem service. 
![image](https://github.com/Leantime/leantime/assets/54801689/7c1a1b66-f86f-4781-9d99-f6933dacf830)

**To Reproduce**

1. Login to the portal
2. Select project
3. Select To-Do
4. Close and don't show screen -tutorial
5. Log out 
6. Start from step 1 again.

**Expected behavior**
Once I hit **Close and don't show this screen again** these tours wouldn't show again. 

**Leantime Version**
3.0.2

**Server**
Apache

**PHP / MySQL Version**
_I'm afraid that at this point I don't have this information_

**Additional context**

**Comment by marcelfolaron** [comment]
Should be fixed in 3.1.3
