### ISSUE TITLE
[BUG] Calendar view  in Milestones show time in UTC

### ISSUE THREAD

**Issue by darren-teo** [Leantime/leantime#2459]
**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
The calendar view under Milestones does not display tasks' date/time by timezone. It is showing the time based on UTC time. On a separate note, the calendar view accessed from Dashboard doesn't have this issue.

**To Reproduce**
1. Go to a selected Project.
2. Click on Milestones, click on the Calendar tab.
3. Tasks shown are in UTC time.

**Expected behavior**
Tasks shown in selected project > Milestones > Calendar view are in the user selected timezone.

**Leantime Version**
3.1.1 docker

**MySQL Version**
Latest 8.3.0

**Comment by marcelfolaron** [comment]
Fixed in 3.1.2
