### ISSUE TITLE
[BUG] Incorrect z-index oder for sidebard scroll and assigned to pop-up

### ISSUE THREAD

**Issue by charly-palencia** [Leantime/leantime#2462]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
When the assigned is open and there's a scroll from the left sidebar, it appears over the assigned to modal.

**To Reproduce**
1. Go to any TODO project using a screen with less or equal than 900 (1400x900)
2. The left sidebar should show a scrollbar
3. get one ticket in the first column and click the assign icon 
4. Pop up be shown 

**Expected behavior**
the assigned to modal should be z-index greater than scroll for sidebar

**Leantime Version**
3.1.1

**Server**
Docker, Portrainer, Traefik

**PHP / MySQL Version**
Docker

**Additional context**
![Screenshot from 2024-04-13 14-34-07](https://github.com/Leantime/leantime/assets/645526/6287148b-20bf-447c-be63-86b9f207988d)

**Comment by marcelfolaron** [comment]
Can you check again with the latest version? We made several CSS changes over the last few releases which addressed a variety of similar issues.
