### ISSUE TITLE
[BUG] i18n language not loaded before login.

### ISSUE THREAD

**Issue by pablopoo** [Leantime/leantime#2470]
**What set up are you using**
* [ ] Cloud Hosted Version
* [ X] Self Hosted

**Describe the bug**
When the main language is set to any other than English, the site text labels show placeholders.

**To Reproduce**
1. Set main language to LEAN_LANGUAGE: 'es' or any other language different than English
2. label placeholders are show
![image](https://github.com/Leantime/leantime/assets/13492043/91371c50-f0a9-4706-a8e7-98a90d8f51e4)

**Expected behavior**
1.-If there is no translation for a label, it must fall back to English on that label. 

**Leantime Version**
Docker tag 3.1.1

**Additional context**
Seems the translation functionality is executed after the user is authenticated.

**Comment by marcelfolaron** [comment]
Hey,

The language config requires language + country code. So it needs to be es-ES. 
The list of available languages can be viewed here https://github.com/Leantime/leantime/blob/master/app/Language/languagelist.ini
