### ISSUE TITLE
[BUG] Error when re-inviting a deleted member

### ISSUE THREAD

**Issue by Elbry** [Leantime/leantime#2472]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*
I reached the discord server, and was guided to create a GitHub issue.

**What set up are you using**
* [ ] Cloud Hosted Version
* [ ✅ ] Self Hosted (v.3.1.1)

**Describe the bug**
While inviting other users, I had to delete some of them and invite them again.
The reinvited ones only get to see an error page with error code 500 and cannot configure their profile and get in.
Also an error code below has been printed.
`Exception: Error trying to set a project in /var/www/html/app/Domain/Projects/Services/Projects.php:632`

**To Reproduce**
1. Invite new user by their email address.
2. Delete them in member configuration.
3. Invite again with the same email address.
4. Have the reinvited member try to get in leantime.

**Expected behavior**
Reinvited users also should be able to get access back to the leantime project as before.

**Leantime Version**
v3.1.1

**Server**
docker images (leantime/leantime:latest)

**PHP / MySQL Version**
PHP: 8.1.27 (internally in docker images)
MySQL: 8.0.36

**Additional context**

**Comment by marcelfolaron** [comment]
Should be fixed in 3.1.3
