### ISSUE TITLE
[BUG] Custom themes are not saved

### ISSUE THREAD

**Issue by Waldehyd** [Leantime/leantime#2473]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x ] Self Hosted

**Describe the bug**
When creating a custom theme, it can be selected and applied, but after clearing cache/cookies or using different browser, it gets reset to the old theme until applying again.

**To Reproduce**
1. Create custom theme by duplicating the default theme folder
2. Change name to "custom" and both colors (in my case solid black) in theme.ini
3. Set default theme to "custom" in .env
4. Change colors in .css files

**Expected behavior**
The themed should be persistent and default for all users.

**Leantime Version**
3.1.1

**Server**
Apache on shared hosting on Uberspace

**PHP / MySQL Version**
8.1
10.6

**Comment by Waldehyd** [comment]
For 2. I dont see the custom theme defined in LEAN_DEFAULT_THEME. I see the default theme. The custom theme is selected as default in the theme dropdown though, but i still need to hit apply again.

For 3. Thats not the case, it's the default theme.

**Comment by marcelfolaron** [comment]
Thanks. I think I found the issue. Will release a fix soon.

**Comment by marcelfolaron** [comment]
Should be fixed in 3.1.3
