### ISSUE TITLE
Sweep: Add Project API doesn't return project_id

### ISSUE THREAD

**Issue by Samekichi** [Leantime/leantime#2474]
### Bug:
- The `addProject()` function in `\app\Domain\Projects\Services\Projects.php` does not return the `project_id` (i.e., return value of `..\Repositories\Projects.php.addProject()`). 

### Suggestion: 
- Add a `return` keyword before the last line `$this->projectRepository->addProject($values);`?

**Comment by marcelfolaron** [comment]
Fixed in 3.1.2
