### ISSUE TITLE
Add customizable webhook support

### ISSUE THREAD

**Issue by skluthe** [Leantime/leantime#249]
Adding a general/customizable webhook would be beneficial for users with custom notification setups. In particular I want to use it with gotify to get push notifications sent to mobile devices.

**Comment by ebecaf** [comment]
I would really lilke to see this.

A custom web-hook would be great, as I don't always want ALL notifications to go to Slack/ Zulip (see #466)

Instead it would be nice to filter web-hook content and add context if needed (again see #466)

Thank you.

**Comment by ebecaf** [comment]
@skluthe 
I've found a way to do this, in the Slack or Mattermost URL box, add your incoming webhook URL instead. You can then get the data in Zapier or Mattermost and filter out what you do or don't want. You may need to use some regex e.g. `/[<,>]/g` to remove the < and > that is used in the webhook text to ensure an accurate link.

**Comment by marcelfolaron** [comment]
While not strictly aligned with this task we added a Zapier app which is now live and will solve most use cases for this.
