### ISSUE TITLE
[BUG]  undefined method Leantime\Core\ApiRequest::getAPIKeyUser()

### ISSUE THREAD

**Issue by PekkaJalonen** [Leantime/leantime#2495]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
Running a simple API request to gives error: 
PHP message: Error: Call to undefined method Leantime\Core\ApiRequest::getAPIKeyUser() in /var/www/html/app/Core/Middleware/RequestRateLimiter.php:58

**To Reproduce**
1. Make API call example POST api/jsonrpc with body:
{
"method": "leantime.rpc.sprints.getAllSprints",
"jsonrpc": "2.0",
"id": 3512291,
"params": {"projectId":8}
}

**Expected behavior**
Return data

**Leantime Version**
3.1.3

**Server**
Docker

**PHP / MySQL Version**
MySQL: 8.1

**Additional context**

**Comment by marcelfolaron** [comment]
This should be fixed as of 3.1.4.
