### ISSUE TITLE
Kaban ToDo Add New Panels

### ISSUE THREAD

**Issue by rafaelkrause** [Leantime/leantime#250]
Is it possible to add more panels to Kaban or Label it? If not will be a nice feature.

For Example:
We can create panels for Sales Follow Up.

New   |  Working | Sent | Wait Confirmation | Approved | Delivered | Done

br
Rafael

**Comment by marcelfolaron** [comment]
You can rename the columns already, just click on the little edit icon on each header label. It is not possible to add new columns at this point.

**Comment by ashkantaravati** [comment]
After lots of research about the perfect solution, I finally set Leantime up last night but suddenly realized I can't add a column and that's seriously crucial to my need. Is it going to be made possible anytime soon?

**Comment by Sonicelo** [comment]
I would love this feature as well. As I understand it should allow to add/remove the labels right?

**Comment by Corborax** [comment]
Adding and substracting panels is really needed. There has to be more flexibility if teams need it.

**Comment by bragonznx** [comment]
+1 for this feature
