### ISSUE TITLE
[BUG]Slow load times without internet connection

### ISSUE THREAD

**Issue by xraitin** [Leantime/leantime#2507]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
Pages are taking 15-30 seconds to load when your serwer don't have internet connection. 

**To Reproduce**
1. Disable internet on serwer
2. Try to load main page or To-do's - it loads slowly
3. Enable internet
4. Leantime run fast

**Expected behavior**
To use leantime without internet connection.

**Leantime Version**
3.1.4, it behave like that from versions 3.X

**Server**
Ubuntu 22.04, Offical docker-compose.yml file with apache as reverse proxy

**PHP / MySQL Version**
Shipped with containers

**Additional context**
Site is trying to connect to 34.221.222.116 - ec2-34-221-222-116.us-west-2.compute.amazonaws.com.

**Comment by marcelfolaron** [comment]
This should be fixed as of 3.3
