### ISSUE TITLE
[BUG] Notification error 500 on clean install

### ISSUE THREAD

**Issue by remygrandin** [Leantime/leantime#2509]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
Without PHPUnit installed, a large error 500 block half the screen

**To Reproduce**
1. Install on a clean ubuntu server 22.04
2. connect to leantime
3. A large error 500 in the top right corner block usage of underneath componenets

**Expected behavior**
No error

**Leantime Version**
3.1.4

**Server**
nginx

**Additional context**
Logs show php stack trace of : 

Error: Call to undefined function PHPUnit\Framework\throwException() in /opt/leantime/app/Domain/Notifications/Services/News.php:103

When installing phpunit via apt and restarting nginx, the error disapear.

phpunit should probably be listed in the required dependency of the repo readme install section

**Comment by marcelfolaron** [comment]
Fixed in 3.3
