### ISSUE TITLE
[BUG] type task is saved as both upper and lower case

### ISSUE THREAD

**Issue by sinejespersen** [Leantime/leantime#2513]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**

It seems, the task type is saved as uppercase: 

https://github.com/Leantime/leantime/blob/b8252d3b66cfa1121b96875b248e233c72efb672/app/Domain/Tickets/Services/Tickets.php#L1088

https://github.com/Leantime/leantime/blob/b8252d3b66cfa1121b96875b248e233c72efb672/app/Domain/Tickets/Services/Tickets.php#L1196

And other entries are saved as lowercased, e.g. project and milestone as seen in the example below

https://github.com/Leantime/leantime/blob/b8252d3b66cfa1121b96875b248e233c72efb672/app/Domain/Tickets/Services/Tickets.php#L1432

I am not sure if this is intentional, but I'll create a pr to save task as lowercase to streamline the codebase. 

**To Reproduce**
 
See files linked above.

**Expected behavior**

I would expect for the type to be lowercased as it is with the other types.

**Leantime Version**
3.1.4

**Server**
N/A

**PHP / MySQL Version**
N/A

**Additional context**
N/A

**Comment by pvi-github** [comment]
@sinejespersen @marcelfolaron if the above fix did solve the problem why is this issue still marked open ?
