### ISSUE TITLE
/dashboard/home stuck loading notifications

### ISSUE THREAD

**Issue by exiamu** [Leantime/leantime#2516]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
When using Leantime from IP:PORT without using Nginxpm it loads my notifications on my /dashboard/home after logging in. Once I set up Nginxpm and use https://leantime.domain.com and log in. The notifications and everything on my /dashboard/home just is stuck loading and the GET command looks to be trying to grab things from IP:PORT instead of the leantime.domain.com

**To Reproduce**
1. Dont set up nginxpm 
2. Run from IP:PORT and get no issue
3. set up nginxpm
4. run https://leantime.domain.com and get issue

**Expected behavior**
Load the notifications on /dashboard/home

**Leantime Version**
3.1.4

**Server**
Ubuntu server, nginx, cloudflare

**Comment by exiamu** [comment]
I have pinpointed this down to the "/widgets/welcome/get" and the "/widgets/welcome/todos" pulling a BASE URL of my IP:PORT and not my leantime.domain.com like all the other things. My /dashboard/home is pulling the BASEURL properly but not the widgets side. The coding inside of Widgets > Services > widgets.php shows the coding has under WidgetsURL -- BASEURL . "/widgets/welcome/get" so i dont know why this is not converting to leantime.domain.com proplery like the other stuff.

**Comment by bgreyesjr** [comment]
try dashboard settings -> reset dashboard
