### ISSUE TITLE
[BUG] Unable to log in with OIDC. Redirects back to login page.

### ISSUE THREAD

**Issue by Sgt-Ogre** [Leantime/leantime#2519]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ x ] Self Hosted

**Describe the bug**
When attempting to log in with OIDC user after initial setup i get redirected to the login screen after IDP login. The user gets created but i am unable to log in with that user.

**To Reproduce**
1. Setup OIDC configuration
2. Log in using the OIDC Login button
3. After login you will be redirected to login page
4. User gets created and can be seen on the admin side.

**Expected behavior**
User is forwarded to dashboard

**Leantime Version**
Latest Docker image pulled last night

**Server**
NGINX reverse Proxy

**PHP / MySQL Version**
mysql docker 8.0

**Additional context**
Using authentik as the IDP

**Comment by samuk** [comment]
I'm also having a similar issue getting Keycloak OIDC to work

**Comment by sy-gpe** [comment]
Hello !

I think I've found out why this is happening. The SID cookie is now set with the SameSite restriction as `Strict`, which prevents the web browser from sending it when you're hitting the callback URL.

According to my tests, changing this restriction to `Lax` seems to fix the issue.

You can change [this line](https://github.com/Leantime/leantime/blob/d54fdf9d187ebfef703e7d2c81a0c1e29df109b8/app/Core/Session.php#L112) on Leantime v3.1.4 to patch this issue : 

```php
->withSameSite('Lax')
```

@marcelfolaron Does [your PR](https://github.com/Leantime/leantime/pull/2530) would also fix this issue ? Or should I create a new one ?

Best regards

**Comment by marcelfolaron** [comment]
Hey, yes the latest PR changes this back to Lax
