### ISSUE TITLE
[FEATURE] Better way to assign a time to tasks

### ISSUE THREAD

**Issue by despens** [Leantime/leantime#252]
**Is your feature request related to a problem? Please describe.**

It is very easy to assign tasks to milestones and plan for the time the milestone should be worked on. Independent of that, every tasks has a separate time that needs to be manually assigned. There is no guidance available when having to pick these times, such as the end time of the milestone automatically becoming the end time, and edits need to be made without information about other tasks and milestones being visible.

This makes it cumbersome to add such dates to tasks, which often leaves these fields undefined. The dashboard then typically shows that there's nothing to do today, even when milestone delivery dates are coming soon.

**Describe the solution you'd like**

I would like to zoom into a milestone in the gantt view and graphically move tasks around inside the milestone.

**Additional context**

The gantt view is really nice overall!

**Comment by marcelfolaron** [comment]
In 2.3.4
