### ISSUE TITLE
[BUG] Changing IP address invalidates session

### ISSUE THREAD

**Issue by gamedevkirk** [Leantime/leantime#2522]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
I'm being logged out any time my VPN shuffles my IP address, it seems to invalidate the session.
Disabling my VPN keeps the session intact, but enabling it immediately logs me out.

**To Reproduce**
1. Login to Leantime
2. Enable VPN (or force an IP change through other means)
3. Try and interact with Leantime
4. Redirected to login

**Expected behavior**
Changing IP addresses should leave the session intact.

**Leantime Version**
3.1.4

**Server**
Nginx

**PHP / MySQL Version**
PHP 8.1.2-1ubuntu2.17 (cli) (built: May  1 2024 10:10:07) (NTS)
mysql  Ver 15.1 Distrib 10.6.16-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by marcelfolaron** [comment]
3.2 introduced a new session manager which should fix this.
