### ISSUE TITLE
[BUG] Issue with Tags in To-Do - Error 500

### ISSUE THREAD

**Issue by RubeHicksCube** [Leantime/leantime#2525]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
Fresh install from Turnkey, everything else works fine but after creating a task I get Error 500. Only happens when a tag is assigned.

Re-installed twice, different machines. tried adding the email in the configuration.php file with no change. From the home page I can adjust the tags - with a tag I get error 500 - without a tag everything works.

**To Reproduce**
1. Go to 'To-Do'
2. Click on 'Tags'
3. Create Tag and close wizard
4. See error 500

**Expected behavior**
A To-Do task created without the error

**Leantime Version**
v3.1.2

**Server**
Turnkey on ProxMox - Debian 12

**PHP / MySQL Version**
PHP 8.2.18

**Comment by marcelfolaron** [comment]
This cannot be reproduced in 3.2.1
