### ISSUE TITLE
[BUG] subtasks can't be less than an hour, they appear to round to the nearest full hour

### ISSUE THREAD

**Issue by improvethings** [Leantime/leantime#253]
"We recommend subtasks be less than 4 hours long."

I tried to enter a subtask of 15 minutes using '0.25', and it now says planned hours of 0 once I saved it. 

For hours remaining on another subtask I tried '0.5' and it still says 1 hour remaining after saving.

**Comment by marcelfolaron** [comment]
Thanks for reporting. We'll take a look at that and should have a fix out by the weekend
