### ISSUE TITLE
[BUG] UI Bug: Alerts not scrollable

### ISSUE THREAD

**Issue by 3lm4r** [Leantime/leantime#2531]
**What set up are you using**
* [X] Cloud Hosted Version: Demo Account
* [ ] Self Hosted

**Describe the bug**
If u are opening a new demo account, skipping all the help and finally get to the dashboard, you have a lot of release information and other stuff in your personal alerts. Click in Menubar on the alert icon and you can't scroll through ure alerts but only on the dashboard. This way u can't see all your alerts.

**To Reproduce**
Not necicary ... see above.

**Expected behavior**
I want to scroll the alerts not the dashboard.

**Leantime Version**
I don't know wich version your demo server are reliable on.

**Server**
not relevant

**PHP / MySQL Version**
not relevant

**Additional context**
not relevant

**Comment by 3lm4r** [comment]
Additional information:

Chrome
Version 125.0.6422.142 (Official Build) (64-Bit)

**Comment by gloriafolaron** [comment]
I was able to recreate this pretty easily -- thanks for the details! You should definitely be able to isolate that scroll. 

We'll take a look at it.

Thanks!

**Comment by 3lm4r** [comment]
Thank you for the fast reaction. I'm happy if I could help and that you're interested in my feedback. In my opinion, you are making and planning a great product. I'll stay tuned.

Greetings ... 3lm4r ^^

**Comment by gloriafolaron** [comment]
We can't get better without the feedback and I think it's sometimes these finer details that add up to bigger experiences -- so any time, we're happy to have it. 

That said, I know it takes time out of your day and work to drop the feedback... and when you've gone out of your way to do that, it's even more meaningful on our end. 

Appreciate it!
