### ISSUE TITLE
[BUG] Can't scroll through all of my projects

### ISSUE THREAD

**Issue by improvethings** [Leantime/leantime#254]
I'm using Firefox 75 MacOS High Sierra on a MacBook pro. 

I have multiple clients, and multiple projects for each client. When I click on a project now on the left side menu, and the client list appears with each project under each client, it's so long I can't scroll after it gets to the bottom of the screen. 
For example, I can no longer see the "Add new project" option, as it's below the visible screen.

**Comment by marcelfolaron** [comment]
Thanks for reporting. You can collapse the list by clicking on the client name. Is that not working for you?

**Comment by gloriafolaron** [comment]
@improvethings I'm currently reviewing bugs that have not been closed and I realize this is outdated but wanted to follow up in case it's still an issue. Are you still having problems with this with the updated versions?
