### ISSUE TITLE
[BUG]No database connection

### ISSUE THREAD

**Issue by Wykkkk** [Leantime/leantime#2540]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*
i am sure mysql connect is true,i can connect in local and mysql cenots can ping 192.168.8.210 unobstructed
but when i use docker run
`docker run -d --restart unless-stopped -p 8076:80 \
-e LEAN_DB_HOST=192.168.8.210 \
-e LEAN_DB_PORT=3306 \
-e LEAN_DB_USER=root \
-e LEAN_DB_PASSWORD=1qazxsw2 \
-e LEAN_DB_DATABASE=leantime \
--name wyk_leantime leantime/leantime:latest`

or

`docker run -d --restart unless-stopped -p 8076:80 \
-e LEAN_DB_HOST=192.168.8.210:3306 \
-e LEAN_DB_USER=root \
-e LEAN_DB_PASSWORD=1qazxsw2 \
-e LEAN_DB_DATABASE=leantime \
--name wyk_leantime leantime/leantime:latest`

i use install prompt `No database connection, check your database credentials in your configuration file`
Is it because my MySQL library is empty?my leantime  is empty

**Comment by Wykkkk** [comment]
I have tried using MySQL 5.7 \ 8.0 before，but still unable to connect

**Comment by puzzle9** [comment]
https://github.com/Leantime/leantime/blob/master/app/Core/Db/Db.php#L75

change file show more error

**Comment by UAnton** [comment]
I have the same error. Try reinstalling many times but every time get an error!

**Comment by marcelfolaron** [comment]
Please check that the db is in the same network. Unfortunately we can't support custom docker set ups. So unless this problem shows up with our docker-compose file we can't dive deeper. You may be able to find additional help in our discord channel.
