### ISSUE TITLE
Subtask: Not able to make description on newly created

### ISSUE THREAD

**Issue by Anna-itk** [Leantime/leantime#2544]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
Not possible to edit description on newly created subtasks and also description from main task is being copied to subtask automatically (this might be a feature?)  

**To Reproduce**
1. Go to 'Project' create new To do
2. Make subtask on the newly created To do
3. Open subtask try to edit the description (not possible)
4. Click 'Save and close'
5. Open subtask again and see that the description has been copied fra the main To do
6. See error

**Expected behavior**
I expect to be able to edit the description of a newly created subtask - I don't want the descriprion of the main task to be copied to the subtask (but if this is a feature I accept it)

**Leantime Version**
V.3.1.4

**Comment by pvi-github** [comment]
Hello @Anna-itk : you can click "save" instead of "save and close" : that will save you time.

**Comment by marcelfolaron** [comment]
Should be fixed in 3.3 now
