### ISSUE TITLE
[BUG] User - "Not assigned to Client" doesn't work

### ISSUE THREAD

**Issue by lamping7** [Leantime/leantime#255]
**Describe the bug**
I was creating users for my team members. I selected "company manager" as the role and left it "not assigned to client". After saving, looking at the overview of users, in the table, it is showing a seemingly random client's name. I created another one and accidentally forgot to change the role, defaulted to "client" and the same "not assigned to client." In the table, this showed up as expected as blank in the "Client" section of the table. I found that interesting. So, I tried setting the first user to "Client" role to see of it would clear and adhere to the "not assigned to client." It didn't/stayed the same. 

Edit: I just added another user as a "company manager" and it worked correctly. Also, I have two clients. So, maybe once I got beyond two users, it is allowing those additional users, beyond the number of clients, to be "not assigned."

**To Reproduce**
See above.

**Expected behavior**
Allow a user to not be assigned to a client in any role.

**Leantime Version**
2.1.1

**Comment by marcelfolaron** [comment]
I'll have to review that flow. Generally speaking you should be able to leave that field empty for all users except(!) the clientManager role who needs that field to be able to manage the client. I should make it required in that case.

**Comment by marcelfolaron** [comment]
I found the issue. There was a problem in the show all user sql query. I have a fix ready and will cut a release tonight.
