### ISSUE TITLE
[BUG] Calendar Event Drag Not working

### ISSUE THREAD

**Issue by clemrdh** [Leantime/leantime#2551]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
in the calendar page (/calendar/showMyCalendar), when moving an event from Time slot to another, the new position is not persistent (ie. the change doesn't get saved).

For some unknown reason, the **api request** made when the drag is finished (endpoint : api/tickets), **contains an empty value**, wich I suspect is resulting in the 500 error return from the endpoint.

_Here is the "PATCH" request I can read from the Inspector in firefox:_ 
id=179&editFrom=2024-06-15T04%3A30%3A00-07%3A00&editTo=

_In the  Console, a few warnings but no errors :_ 
Cette page utilise la propriété non standard « zoom ». Envisagez d’utiliser calc() dans les valeurs des propriétés pertinentes ou utilisez « transform » avec « transform-origin: 0 0 ». [showMyCalendar]()
Certains cookies utilisent incorrectement l’attribut recommandé « SameSite » 20
La mise en page a été forcée avant le chargement complet de la page. Si les feuilles de style ne sont pas encore chargées, cela peut provoquer un flash de contenu non stylisé. [compiled-frameworks.3.1.4.min.js:1:83612]()
L’attribut « src » de l’élément <script> est vide. [showMyCalendar:46:20]()
L’attribut « src » de l’élément <script> est vide. [showMyCalendar:47:20]()
​

**To Reproduce**
1. Go to Calendar Page
2. Click on any event and drag it somewhere else
3. Reload the page
4. Event is still in the original position

**Expected behavior**
Event should be moved persistently

**Leantime Version**
v3.1.4

**Server**
Apache

**PHP / MySQL Version**
PHP 8 

Thanks 🙏

**Comment by gloriafolaron** [comment]
Any chance you checked this in other browsers? No problem if not, we can look as well. I ask as we frequently have issues in Firefox as a whole and so I'm curious.

Thanks for reporting, though.

**Comment by clemrdh** [comment]
Just checked in chrome and the same thing happens :/

**Comment by marcelfolaron** [comment]
Fixed in 3.2.1
