### ISSUE TITLE
[BUG] Warning: Undefined array key "modified" on projectSelector.blade.php

### ISSUE THREAD

**Issue by afdhal395** [Leantime/leantime#2565]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
This error appeared when I tried to Create New Project after deleting the first (tutorial/walkthrough/sample) project.

**To Reproduce**
1. Go to Project Hub.
2. Delete the first created project during first welcome screen.
3. Click on Create New Project that will take users to http://<domain.com>/projects/newProject.
4. The error appeared. 

**Expected behavior**
A wizard for creating new project should appeared.

**Leantime Version**
3.1.4

**Server**
Apache, nginx, IIS etc

**PHP / MySQL Version**
Please list the PHP and Mysql version you are using

**Additional context**

![image](https://github.com/Leantime/leantime/assets/42729942/a98cf7e8-5d45-4344-bf0c-fb8fc236a832)

**Comment by marcelfolaron** [comment]
Fixed in 3.2.0
