### ISSUE TITLE
[BUG] newUser action can't redirect to the success page.

### ISSUE THREAD

**Issue by kuangmeng** [Leantime/leantime#2567]
**What set up are you using**
* [ ] Cloud Hosted Version
* [✅] Self Hosted

**Describe the bug**
When I add a new user to a client, it can't redirect to the success page but returns to the following page.

![image](https://github.com/Leantime/leantime/assets/9164162/c6293687-9739-46cc-b53f-92c24b656770)

**To Reproduce**
1. Go to 'client details' page;
2. Click on 'add new user' button;
3. Then click on 'invite user' button.

**Leantime Version**
2.4.4 but with the newest `app/Domain/Users/Controllers/NewUser.php` file

**Server**
Docker

**Comment by marcelfolaron** [comment]
This does not seem to be an issue on 3.2 
You also can't just replace the NewUser controller and assume it will work. There is a lot more to the entire stack than just the controller. Replacing individual files will not ensure functionality
