### ISSUE TITLE
[BUG] ToDo Discussions: When a user replies within discussion, the gravatar is overwritten.

### ISSUE THREAD

**Issue by Marcquito** [Leantime/leantime#257]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Within the discussion area of any ToDo item, if there is a discussion taking place and a user decides to use the "reply" feature to create a thread, the profile picture of the user using the reply feature will be overwritten by the user of the parent post they are replying to. I'll be attaching a screenshot of this so it's super clear. 

**To Reproduce**
1. User A will post a message within the discussion of a ToDo. 
2. User B will go to the message within the ToDo, click "reply" and post a reply message.
3. Once User B submits their message, their profile picture will be the image belonging to User A.

**Expected behavior**
Once a user replies, their reply and profile picture should be their own.

**Leantime Version**
2.1.1

**Server**
Apache

**PHP / MySQL Version**
PHP 7.3, MariaDB 10.2
![thread-reply-inherits-avatar](https://user-images.githubusercontent.com/5797508/81432341-bc30e480-9130-11ea-8db3-bacec94e40dd.jpeg)

**Additional context**

**Comment by marcelfolaron** [comment]
Thanks for reporting. Will get a fix out with the 2.1.2 cut this weekend

**Comment by rpacheco2019** [comment]
Hi!, i can confirm this bug. Leantime Ver. 2.1.1. Thanks for your effort 👍
