### ISSUE TITLE
[BUG] Modals showing blank preventing Milestone Creation and all other modal related activities

### ISSUE THREAD

**Issue by silenceinit** [Leantime/leantime#2571]
Modals return blank, im using the latest version, on docker container with docker compose. Tried rolling back to an older release, 2 months old version, still the same issue

![mile](https://github.com/Leantime/leantime/assets/174639889/aaa2b6d5-9702-46d0-a960-34871b10361a)

**Comment by gloriafolaron** [comment]
Hey!

That's weird.

Are you seeing an errors in your logs? Can you tell me which step you are
trying to take that creates the modal? (adding a milestone, to do, is it
help modal, etc).

**Comment by silenceinit** [comment]
There no errors in the logs, i just tried with docker v26, it works fine.. Its either the v27 has issues, for instance i have a lamp server that when i install some apps with v27 they dont complete initializing, but with v26 they do. Or something happened to my server that interfered with the container, but then i have removed and redeployed the container and the problem didnt go away.. Two more tests, one, im removing everything but the database, and re installing, including all volumes and files, the second is im starting from scratch. Also this is a fresh install, from a new AWS, so i can risk it, ill get back to you once i solve this atleast. In the meantime i suggest looking into docker v27 issue.. Another example is proxmox lxc dont work well with docker v.27 either, there are issues pulling resources in some cases, and many more probably,

![lean logs](https://github.com/Leantime/leantime/assets/174639889/e7640129-3d0d-45fe-8a4f-53539cbc2e3d)

**Comment by silenceinit** [comment]
It somehow fixed itself.. I did two things, re install, did not fix, then i enabled third party cookies on chrome, last i checked it did not work, i did some docker prune, and lastly i deleted the directory i was installing leantime with and just before starting from scratch i told myself i could check again, then suprising enough the modals are back on.. not sure which solution solved this but i did unknowingly. Maybe it was a cache thing

**Comment by silenceinit** [comment]
FIXED: turns out it was a https url issue.. i was deploying without the url addition in the .env file. After i added it everything worked fine.
