### ISSUE TITLE
[BUG] Date input with calandar does not work outside default settings

### ISSUE THREAD

**Issue by benausro** [Leantime/leantime#2580]
**What set up are you using**
* [ x] Cloud Hosted Version
* [ ] Self Hosted

**Describe the bug**
I have set the langage to German and changed date format to a one that is more common here. When selecting a date from the calendar that pops up when entering a date in a task, saving gives a server error 500.

**To Reproduce**
1. Switch langage to German
1. Go to a random task
2. Click on the due date field, select a date. It will show something like "Juli 12, 2024"
3. Save.
4. See error.

**Leantime Version**
Cloud

**Additional context**
PHP expects F d, Y. If you enter July 12, 2024 manually, everything works.

**Comment by RKLBusinessDevelopment** [comment]
This problem happens in the self-hosted version too. I was about to open an issue, but found yours.
