### ISSUE TITLE
[BUG] logo disappears after refresh page

### ISSUE THREAD

**Issue by leonidas-o** [Leantime/leantime#2585]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
When accessing the login page, the custom logo is shown. On refreshing the page or clicking on the logo, which opens a new tab the logo disappears. When using the browsers inspector to check the img src, it changed to `https://my-leantime.domain.com/dist/images/logo.svg`.

**To Reproduce**
1. Go to the login page
2. Refresh the page/ or click on the logo
4. After refresh, see logo disappeared

**Expected behavior**
The same custom logo will be used.

**Leantime Version**
docker leantime 3.1.4

**Comment by marcelfolaron** [comment]
Can you check if this is still an issue in 3.2.0? I can't reproduce that.

**Comment by leonidas-o** [comment]
Just updated and it's still the same behaviour. 
Opened a new private window:
- the logo on Mac OS Safari is still skewed and disappears on page refresh
- the logo on Firefox is NOT skewed, but disappears on page refresh, too

```bash
leantime/leantime  latest                 b6e3caf92d50  5 days ago    463 MB
# also checked/ inspected the image and saw a few entries `LEAN_VERSION=3.2.0`
```

**Comment by marcelfolaron** [comment]
I double checked the behavior in 3.2.1 and this cannot be reproduced anymore.

**Comment by leonidas-o** [comment]
@marcelfolaron No, exactly the same behaviour. Tested on Mac and even on iOS. Please re-open the issue.

macOS Sonoma 14.6.1
Safari Version 17.6 (19618.3.11.11.5)
Firefox 130.0.1

and iOS 17.61 (Safarai)

Opened a new private window:

the logo on Mac OS Safari is still skewed and disappears on page refresh
the logo on Firefox is NOT skewed, but disappears on page refresh


also checked/ inspected the image and saw a few entries `LEAN_VERSION=3.2.1`
```
leantime/leantime  latest                 cab8c280b816  10 hours ago  536 MB
```
