### ISSUE TITLE
[BUG] Timeregistration without Project

### ISSUE THREAD

**Issue by Anna-itk** [Leantime/leantime#2586]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
If I use My timesheets week view but forget to select Project I will get an empty registration with just //   

**To Reproduce**
1. Go to 'My time sheets week view'
2. Click on 'fill out an hour without selecting project or To do'
3. Press 'save'

**Expected behavior**
Not being able to regsiter time without choosing project

**Leantime Version**
[v.3.1.4]

**Comment by marcelfolaron** [comment]
Updated in 3.2.1
