### ISSUE TITLE
[BUG] Deleting To do with worklogs

### ISSUE THREAD

**Issue by Anna-itk** [Leantime/leantime#2587]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
If you delete a To do with worklogs you will have worklogs without any To dos

**To Reproduce**
1. Go to 'Project To do's Kanban view'
2. Click on '...' and delete To do
3. Go to 'My timesheet' and find worklogs of deleted To do
4. See error (now they are no longer connected to a To do

**Expected behavior**
I would like a notifcation if I'm about to delete a To do with worklogs

**Leantime Version**
v.3.1.4

**Comment by marcelfolaron** [comment]
Would you expect the worklogs to be deleted as well or should we prevent deleting the task?

**Comment by Anna-itk** [comment]
I would prefer prevent deleting the task (so I would have to manually delete the worklogs first to delete the task)

**Comment by marcelfolaron** [comment]
I added a new check in 3.2.1
