### ISSUE TITLE
To-Dos Filter search doesn't work

### ISSUE THREAD

**Issue by cesalo** [Leantime/leantime#259]
**Describe the bug**
Going to the To-Dos view, click in Filters and then try to use "Search Term" doesn't do anything.

**To Reproduce**
1. Go to To-Dos view
2. Click on Filters
3. Write something in the "Search Term" and click "Search"
4. It goes back to the initial view listing all the To-Dos.

![Screenshot from 2020-05-08 19-16-32](https://user-images.githubusercontent.com/16859916/81456508-860b5900-9160-11ea-8455-7b9f062d2fd6.png)

Click Search:

![Screenshot from 2020-05-08 19-16-45](https://user-images.githubusercontent.com/16859916/81456499-7ee44b00-9160-11ea-8b5d-d1009f1385fd.png)

**Expected behavior**
After click in search it should show the To-Dos that have the search string in the Title or Milestone, etc.

**Leantime Version**
2.1.1

**Server**
Docker Version

**Comment by marcelfolaron** [comment]
Thanks for reporting, will take a look and get a fix out with the release cut this weekend
