### ISSUE TITLE
[BUG] Empty Client ID in Message to IdP

### ISSUE THREAD

**Issue by ryand11** [Leantime/leantime#2596]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [X ] Self Hosted

**Describe the bug**
While Authenticating via OpenID, client_id is appearing as NULL / Blank

**To Reproduce**
1. Go to Login Page
2. Click on OIDC login
3. You will be redirected to your auth provider
4. See error in URL:  https://auth.example.com/application/o/authorize/?**client_id=**&redirect_uri=xyz

**Expected behavior**
Client ID is passed to SSO provider

**Leantime Version**
v3.1.4

**Server**
Docker

**Comment by ryand11** [comment]
Update: This still persists in 3.2.0

**Comment by marcelfolaron** [comment]
Can you check that your .env config has the correct spelling for the OIDC_CLIENT_ID?
In some previous versions the environment sample file had a typo where "client" was spelled with a "d" at the end.

**Comment by ryand11** [comment]
> Can you check that your .env config has the correct spelling for the OIDC_CLIENT_ID?
> In some previous versions the environment sample file had a typo where "client" was spelled with a "d" at the end. 

Well, thats mildly infuriating 😅. Feel free to close this
