### ISSUE TITLE
[BUG] Adding time in the timesheet deletes existing rows

### ISSUE THREAD

**Issue by lilosti** [Leantime/leantime#2597]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**

**To Reproduce**
1. Go to timesheet weekview
2. Add a row with registrations for 4 days in a week (1 hour each day) for projekt X Todo Y
3. Add a new registration to projekt X row Y for 1 hour
4. Press save
5. See that the first registration you made is overwritten => you just lost the existing registrations

**Expected behavior**
2 choices:
1. you cannot choose a todo there is already a registration on in weekview
2. if you choose a todo that aldready has a registration the registration should be added. deleting registrations is never correct behavior.

**Leantime Version**
Which Leantime version are you using new

**Server**
Apache, nginx, IIS etc

**PHP / MySQL Version**
Please list the PHP and Mysql version you are using

**Additional context**

**Comment by marcelfolaron** [comment]
Thanks for the submission. The value gets updated as you have called out. So it's less of an overwrite as it is an update of the existing number of hours to the new value. 

Now I agree that there is a UX issue here in that we should now allow creating 2 rows of the same ticket in one week. I think easiest solution here would be to remove the todo from the selection for that week. Would that solve the issue?

**Comment by marcelfolaron** [comment]
Thank you for your patience. This is fixed in 3.2.1 now
