### ISSUE TITLE
[BUG] add new  Customer Segments "save and close" button does not work as expected on website 

### ISSUE THREAD

**Issue by LaurenC2022** [Leantime/leantime#2606]
**What set up are you using**
* [X ] Cloud Hosted Version

**Describe the bug**
 when adding new  Customer Segments "save and close" button does not work as expected on website. Data is saved, but window does not close as expected. 

**To Reproduce**
1. Go to add "Project Value Board // Board"
2. Click on "add new" under "Customer Segments"
3. include "Description" and "What assumptions do you have about this customer segment?"
4. Scroll down and click on "Save & Close"
5. Content is saved, but the window for adding new customer segment doesn't close 

**Expected behavior**
Save and then close 

**Leantime Version**
www.leantime.io
 v3.1.4 (website)

**Server**
Unknown

**PHP / MySQL Version**
Unknown

**Additional context**
none

**Comment by marcelfolaron** [comment]
Fixed in 3.2.0
