### ISSUE TITLE
[BUG] Plugin csvimport conflicts with domain - dashboard missing 

### ISSUE THREAD

**Issue by bialybudyn** [Leantime/leantime#2607]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X ] Self Hosted

**Describe the bug**
After log in I have several 500 internal error and dashboard completely disappear. 

**docker logs:** 
[13-Aug-2024 18:48:34] NOTICE: ready to handle connections
2024-08-13 18:48:35,222 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-08-13 18:48:35,222 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
127.0.0.1 -  13/Aug/2024:18:48:36 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:48:47 +0000 "GET /index.php" 302
127.0.0.1 -  13/Aug/2024:18:48:48 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:48:48 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:48:50 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:48:53 +0000 "POST /index.php" 303
127.0.0.1 -  13/Aug/2024:18:48:53 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:48:53 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:48:53 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:48:53 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:48:53 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:48:54 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:48:59 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:48:55 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:12 +0000 "GET /index.php" 302
127.0.0.1 -  13/Aug/2024:18:49:12 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:12 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:13 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:17 +0000 "POST /index.php" 303
127.0.0.1 -  13/Aug/2024:18:49:17 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:17 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:17 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:17 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:17 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:17 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:18 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:24 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:25 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:26 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:26 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:26 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:26 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:26 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:29 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:35 +0000 "GET /index.php" 200
127.0.0.1 -  13/Aug/2024:18:49:36 +0000 "PATCH /index.php" 200

**/var/www/html/logs/error.log:**

[13-Aug-2024 18:49:12 UTC] Plugin csvimport conflicts with domain                                                                                                                           │
│[13-Aug-2024 20:50:07 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:07 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:07 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:07 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:07 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:07 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:07 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:07 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:07 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:10 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:10 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:10 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:10 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:10 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:10 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:10 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:10 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:10 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:12 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:12 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:12 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:12 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:12 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:12 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:12 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:12 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 20:50:12 Europe/Warsaw] PHP Warning:  Undefined property: Leantime\Domain\Plugins\Models\MarketplacePlugin::$version in /var/www/html/cache/views/dc3487e4961ad0872902b53cd4883│
│[13-Aug-2024 19:00:14 UTC] Plugin csvimport conflicts with domain      

**To Reproduce**
1. 'Log in'

**Expected behavior**
I want to see dashboard again :) 

**Leantime Version**
I've try latest docker image, 3.1.4, 3.1.3 and 3.1.2

![leantime_error](https://github.com/user-attachments/assets/276af2bb-1ca9-41be-b1d3-bfc28ffcdb0a)

**Comment by marcelfolaron** [comment]
Did you recently update from an older version? 
Is the plugin folder mounted by any chance? the csvImport was added to core and the plugin is thus not needed anymore. Can you take a look and remove csvImport from the plugin directory in app/Plugins?

**Comment by marcelfolaron** [comment]
Once the csvImport plugin is removed this should work. Closing for now.
