### ISSUE TITLE
[FEATURE] Add export capability 

### ISSUE THREAD

**Issue by raman325** [Leantime/leantime#261]
**Is your feature request related to a problem? Please describe.**
I've been playing with this tool and the UI is great, but in order to facilitate adoption, it would be great if all objects (milestones, research, ideas, etc.) were exportable. Instead of trying to figure out what file formats make sense, it would be great to be able to build a JSON export of the item in question. At my company we use a ton of tools that handle some of the functionality in LeanTime but I find it easier to use LeanTime for certain types of tasks, and it would be great to be able to work in LeanTime for the UI and then export it and translate it into APIs for other products. This would make it easier for people that are using a different solution to transition, because users could use LeanTime for the UI while still populating incumbent tools in the transition period. Either JSON or CSV (or ideally both) would be sufficient.

**Comment by marcelfolaron** [comment]
Thanks for the report. It is already possible to export milestones, to-dos and timesheets as CSV. Next are ideas and research boards. I'll see if we can offer a Json format as well.

**Comment by raman325** [comment]
Thanks @marcelfolaron - to be quite honest I gave leantime a quick tour and must've just happened to focus on some of the areas that weren't covered. I may have been a bit trigger happy in submitting this, but I'm glad to hear you guys already have this under consideration and that you'd consider JSON as an export format. Cheers!

**Comment by mazhit-t** [comment]
Hello!
I would like to clarify whether there is such a function as exporting tasks as a report in excel format?

**Comment by marcelfolaron** [comment]
Right now the only export option is CSV from
the todo table view.

You can open the csv with excel and manage the todos.

**Comment by mazhit-t** [comment]
When exporting in CSV format, I unload the code and not the report, which is why I asked if there is an excel format

**Comment by marcelfolaron** [comment]
As of 3.2.0 we are supporting Zapier integrations. This would allow a flow like this. The alpha app is available here https://zapier.com/developer/public-invite/207240/cac6ec7a911bd5fa7924f38230d58d2f/
