### ISSUE TITLE
[BUG] Error when deleting the default Wiki

### ISSUE THREAD

**Issue by MnAppsNet** [Leantime/leantime#2615]
**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
When I delete the default Wiki page under Project -> DATA ROOM -> Docs, I get into a situation that I can no longer use the project Docs and I get the following error:
![image](https://github.com/user-attachments/assets/ab3dba62-58d5-44e0-adbc-0e31c226a123)

**To Reproduce**
1. Go to any of your projects
2. Click on Docs under DATA ROOM
3. Delete all yout wikis

**Expected behavior**
When all wikis are deleted, the user should still be able to create a new wiki from the begenning or it should be impossible to delete the last wiki

**Leantime Version**
v3.1.4

**Server**
Running on a docker container on an LXC proxmox container

**PHP / MySQL Version**
MySQL version 8.0 and the latest leantime docker image (leantime/leantime:latest)

**Comment by marcelfolaron** [comment]
Fixed in 3.2.1
