### ISSUE TITLE
[BUG] 500 code error in exported calendar URL

### ISSUE THREAD

**Issue by filipesaraiva** [Leantime/leantime#2644]
**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
I am using Leantime 3.2.0 self-hosted. I tried calendar URL export function. I import that URL in Google Calendar but nothing was presented. So I tried open the URL directly in browser and in wget, both show me the http 500 error.

**To Reproduce**
1. Export some calendar URL. The calendar must have some to-do event;
2. Import the URL in some calendar application (like Google Calendar);
3. The to-do event is not presented;
4. Try the URL in the browser or wget and error 500 is presented.

**Expected behavior**
The URL works and the calendar to-do are presented in calendar applications.

**Leantime Version**
3.2.0

**Server**
Apache

**PHP / MySQL Version**
php8.2

**Additional context**
The URL generated is like https://URL/calendar/ical/code

If necessary I can share an example URL generated by my instance.

**Comment by marcelfolaron** [comment]
Any errors in the error logs?

**Comment by marcelfolaron** [comment]
iCal management was refactored and many bugs fixed. This should resolve this issue
