### ISSUE TITLE
[BUG] Company Colors are not set

### ISSUE THREAD

**Issue by pleibling** [Leantime/leantime#2652]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
I change the Company in .env (docker compose installation, include env-file):
LEAN_DEFAULT_THEME = 'default'                     # Default theme
LEAN_PRIMARY_COLOR = '#850406'                     # Primary Theme color
LEAN_SECONDARY_COLOR = '#e10f12'                   # Secondary Theme Color
LEAN_KEEP_THEME = true                             # Keep theme and language from previous user for login screen

Change it in DB too (leantime > zp_settings > companysettings.primarycolor and companysettings.secondarycolor)

**To Reproduce**
Login (everything is in blue Leantime color), go to theme and click on companycolor - everything is in my red color,  when i click save, it change back to the blue leantime color.

**Expected behavior**
The style is not in selected color, after save it switch back to default leantime color.

**Leantime Version**
3.2.0 (leantime/leantime:latest) - from Docker Hub

**Server**
Docker container, Caddy as reverseproxy and MariaDB as Database.

**PHP / MySQL Version**
From Docker Container self, MariaDB is latest (Docker Container).

**Additional context**

**Comment by pleibling** [comment]
Change LEAN_KEEP_THEME set to false and restart the container doesn't help.

**Comment by marcelfolaron** [comment]
This should be fixed in 3.2.1 
Keep in mind that users can still set their own color scheme under theme. The default colors set in the config will be the "starting" colors and show up as "company colors" under Theme.

**Comment by pleibling** [comment]
Perfect, works well :).
