### ISSUE TITLE
Attempt to create a new Focus Area leads to 500 error

### ISSUE THREAD

**Issue by warhar** [Leantime/leantime#2656]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
I've installed leantime/strategyPro (v1.2.0) and leantime/pgmPro (v1.2.0) to myself hosted instance. Upon attempting to create a new Focus area or setup a goals inside one of the existing defaults, I'm met with a 500 error
**To Reproduce**
1. Go to  'Focus Area'
2. Click on  'Existing Area and click on drop down arrow next to the default area'
3. Scroll down to 'Create Focus Area'
4. See 'error code 500' 

**Expected behavior**
The that permit the creation of a new Focus Area

**Leantime Version**
Latest Docker Compose

**Server**
Apache, nginx, IIS etc

**PHP / MySQL Version**
Please list the PHP and Mysql version you are using

**Additional context**
![Screenshot 2024-09-11 at 12 30 59 PM](https://github.com/user-attachments/assets/d96b642e-415f-46b5-b896-2b0309aa9cdb)

**Comment by marcelfolaron** [comment]
A new version of the plugin was released in tandem with 3.2.1 
This should fix the remaining issues
