### ISSUE TITLE
[BUG] Support Leantime (remove premium links)

### ISSUE THREAD

**Issue by DMTGMBH** [Leantime/leantime#2666]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
"Notes" is not removed

**To Reproduce**
1. Enter licence key and install plugin
2. Click on "Sidebar"
3. See menu item "Notes"

**Expected behavior**
After activation all uninstalled premium links should disappear

**Leantime Version**
3.2.0

**Server**
Apache,

**PHP / MySQL Version**
PHP 8.3.latest and Mysql 8.0

**Comment by marcelfolaron** [comment]
A new version of the plugin was released in tandem with 3.2.1 
This should fix the remaining issues
