### ISSUE TITLE
[BUG] CAN'T INSTALL LEANTIME WITH DOCKER AND WITHOUT DOCKER

### ISSUE THREAD

**Issue by danmb315** [Leantime/leantime#2675]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**

Hi,
I want to install leantime for my work, but i found me with a issue, i tried with docker and without docker.
But both have the same problem in the last version.

I can pull the container/config apache2, php, etc. But when i entry to the url http://<lenantime>/install all looks good, i try to create my user but when i press "install" i don't get any message, no error, no sucess, no anything. just the page get reload.

I  tried with a older leantime version like 3.1.4 and it's fuction, but this versions have to much bugs that get resolve with the last versión 3.2.0

**Leantime Version**
3.20
**Server**
Apache

**PHP / MySQL Version**
8.1

**Comment by marcelfolaron** [comment]
Any errors in logs/leantime.log? 
Leantime requires php 8.1 but the docker image was updated, so not sure where the 8.1 comes from?

**Comment by danmb315** [comment]
@marcelfolaron 
I dont know how i can see the logs with docker because i'm new with it and i already deleate the machine with self host but is something like this "production.CRITICAL: PDOException: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'zp_calendar' already exists in"
I tried with php 8.1 and the lastest version , both have the same problem

**Comment by marcelfolaron** [comment]
Did you use our docker compose file or did you create your own set up? We can only support set ups that use our docker-compose file. There are so many configuration options inside and outside of docker that it's difficult to debug each individual environment. 

The error message above indicates that you are trying to install into an already existing database. Make sure to clear the db before reinstalling.

**Comment by danmb315** [comment]
@marcelfolaron 
I know what say that message. But is a new database it is empty, and i tried with both. The docker-compose with default settings, i don't change anything, literally i download the compose and use it. And i tried with a setup too

**Comment by danmb315** [comment]
> Did you use our docker compose file or did you create your own set up? We can only support set ups that use our docker-compose file. There are so many configuration options inside and outside of docker that it's difficult to debug each individual environment.
> 
> The error message above indicates that you are trying to install into an already existing database. Make sure to clear the db before reinstalling.


[docker-compose.txt](https://github.com/user-attachments/files/17076082/docker-compose.txt)
[env.txt](https://github.com/user-attachments/files/17076083/env.txt)
i tried with this compose

**Comment by marcelfolaron** [comment]
3.3.0 was just released which addresses a lot of the install and login issues.
