### ISSUE TITLE
[BUG] Command system:update cleanup fails

### ISSUE THREAD

**Issue by thurti** [Leantime/leantime#2690]
The command `php bin/leantime system:update` fails to remove the `cache/leantime` directory because `rmdir` requires the directory to be empty.

https://github.com/Leantime/leantime/blob/d6815d5346b34baff8e48069c3c8984c76fb1f11/app/Command/UpdateLeantime.php#L109

**Comment by marcelfolaron** [comment]
This is fixed in 3.3
