### ISSUE TITLE
[Bug]: Assignee from the task is no longer fixed to the project team

### ISSUE THREAD

**Issue by lilosti** [Leantime/leantime#2707]
### What is your set up?

Self Hosted Docker

### Version

3.2.1

### Describe the issue

When editing a task (or changing assignee from the project "To'dos") and changing assignee on the task the list of users are not restricted to the team selected on the project.

### Reproduction steps

1. Open "To-do" overview on a project
2. Press the assignee buble
3. See that all users in the system exists in the dropdown

1. Edit a todo
2.  Change assignee
3.  See that the list contains users not in the project team

...

**Comment by rqi14** [comment]
I have the same issue. Even more, everyone receives notifications from the projects which they are not part of.

**Comment by mjut** [comment]
Same issue over here as well:
- assignees need to be restricted to team members
- notifications from other (private and not assigned to) projects shouldn’t be visible

I wouldnt be bothered, but my team-members are confused ;) and I think, the more people using Leantime, the more of an issue it gets.

**Comment by rqi14** [comment]
Notifications from other projects are sent via email. In the newer version, everyone has the same avatar
