### ISSUE TITLE
[BUG] add more user here > Object not found! 

### ISSUE THREAD

**Issue by King-GO** [Leantime/leantime#271]
**Describe the bug**
Object not found!

**To Reproduce**
1. Go to 'Project Settings'
2. Click on ' add more user here under Team members tab'
3. See Error 404

**Leantime Version**
2.1.2

**Server**
XAMPP

**PHP / MySQL Version**
php 7.3.12
mysqli 10.4
--

**Comment by marcelfolaron** [comment]
Do you run Leantime in a subfolder?

**Comment by King-GO** [comment]
yes, company.com/leantime

已從 Outlook Mobile<https://aka.ms/blhgte> 傳送

________________________________

**Comment by Gregory92** [comment]
I also had this issue. I went through all the links in the application, and this specific link (add more users here) is the only one that I found that did not pick up the the subfolder name/location form the .htaccess file, or at least that is what and where I am assuming its supposed to do.
