### ISSUE TITLE
[BUG] Edit ToDO from Agenda save to Wrong Projct

### ISSUE THREAD

**Issue by rafaelkrause** [Leantime/leantime#272]
Hi,

When I edit a To-Do from Calendar,  it saves to current project, not the original.

**To Reproduce**

1. Open a project, other than To-Do owner;
2. Open Calendar;
3. Click on To-Do (to Edit);
4. When on To-Do Edition, Click Save and Close;

Now the To-Do are saved on the current Selected Project, not the original one.

**System**
OS: Debian
Server: Apache2
PHP:  7.2.24
MySql: 14.14
**LeanTime:  2.1.1**

**Comment by marcelfolaron** [comment]
Thank you for filing the bug. I see the issue and will push a fix with the next release cut.
