### ISSUE TITLE
Leantime bad gateway 502 - using reverse proxy letsencrypt nginx companion

### ISSUE THREAD

**Issue by jasek5** [Leantime/leantime#273]
Hello !
Firstly - thank you for this docker image. Awesome project!!! (I was searching exactly something like this - simple, nice ad with options of minor customizations -- just perfect)

I encoutered an error bad gateway 502 - i tried to deploy this project on my server (leatime/leantime) - the problem is that the leantime is working only via local ip,but not working using my domain...

I am not docker specialist.
Is there anyone who could help/tell me what is wrong ? (I am using owncloud, gitea sucessfully with this docker-letsencrypt-nginx-proxy-companion)

The commands of all related containers are in screenshot.

proxy container: [docker-letsencrypt-nginx-proxy-companion](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion)
nginx container: [nginx-proxy by jwilder](https://github.com/nginx-proxy/nginx-proxy)
db: [mariadb](https://hub.docker.com/r/linuxserver/mariadb)

PS: it did not work before - it never worked with leantime (using domain).
![issue](https://user-images.githubusercontent.com/12669491/82342211-a4d7de00-99f1-11ea-8a9b-c305664e98e6.png)

If you need more info - could you please post me a command ? I will provide an output.

**Comment by jasek5** [comment]
VIRTUAL_PORT must be 80

**Comment by marcelfolaron** [comment]
Thanks for the update! I am glad it got resolved
