### ISSUE TITLE
[Bug]: Unable to load new install 

### ISSUE THREAD

**Issue by stonesrose** [Leantime/leantime#2734]
### What is your set up?

Self Hosted Server

### Version

3.2.1

### Describe the issue

Error 500

`[2024-10-09 17:09:16] production.ERROR: Undefined array key "host" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"host\" at /var/www/leantime/app/Core/Providers/Session.php:52)
[stacktrace]`

### Reproduction steps

1. New Self hosted install
2. Example nginx with updated servername
[leantime.conf.txt](https://github.com/user-attachments/files/17315809/leantime.conf.txt)
[dot_env.txt](https://github.com/user-attachments/files/17315812/dot_env.txt)
...

**Comment by agrozyme** [comment]
mybe the php version in docker image is wrong.
I can install version 3.1.4, but can not install 3.2.0+.
I try install version 3.1.4 and use 3.2.1 to run DB update.
it show the error:

```
/var/www/html # ./bin/leantime db:update
ErrorException: foreach() argument must be of type array|object, null given in /var/www/html/vendor/illuminate/collections/Arr.php:255
Stack trace:
#0 /var/www/html/app/Core/Exceptions/HandleExceptions.php(255): Leantime\Core\Exceptions\HandleExceptions->handleError(2, 'foreach() argum...', '/var/www/html/v...', 255)
#1 /var/www/html/vendor/illuminate/collections/Arr.php(255): Leantime\Core\Exceptions\HandleExceptions->Leantime\Core\Exceptions\{closure}(2, 'foreach() argum...', '/var/www/html/v...', 255)
#2 /var/www/html/app/Core/Console/ConsoleKernel.php(154): Illuminate\Support\Arr::flatten(NULL)
#3 /var/www/html/app/Core/Console/ConsoleKernel.php(36): Leantime\Core\Console\ConsoleKernel->commands()
#4 /var/www/html/app/Core/Console/ConsoleKernel.php(233): Leantime\Core\Console\ConsoleKernel->bootstrap()
#5 /var/www/html/app/Core/Bootstrap/Bootloader.php(161): Leantime\Core\Console\ConsoleKernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/app/Core/Bootstrap/Bootloader.php(129): Leantime\Core\Bootstrap\Bootloader->handleRequest()
#7 /var/www/html/bin/leantime(14): Leantime\Core\Bootstrap\Bootloader->boot()
#8 {main}

```

**Comment by stonesrose** [comment]
Im not running in Docker. Though I can check my php version.
