### ISSUE TITLE
Research Board Status Dropdown menu Improperly sets Status

### ISSUE THREAD

**Issue by Gregory92** [Leantime/leantime#274]
**Describe the bug**
Just started using the software, created a new research board and started filling out the "Who are the customers" column. Filled out the entire item and set the status of the of item to "Validated - Correct". But when the item is saved and closed, I am seeing "Validated - Wrong" on the board view or Vice-Versa. However, the status of "Not Validated" works correctly.

**To Reproduce**
1. Go to 'Research'
2. Click on 'Create New Board and add a card to a column'
3. Set status on card to either "Validated - Correct" or "Validated - Wrong"
4. See the opposite status on the Board view.

**Expected behavior**
Setting the status of the item in the creation step should match the status present on the board view. 

**Leantime Version**
2.1.2

**Server**
Apache 2.4

**PHP / MySQL Version**
PHP 7.2/MySQL 5.7.30

**Additional context**
Not sure if it matters at all, but leantime is installed on a Ubuntu 18.04 LTS VM inside a subfolder. The .htaccess file has been updated to reflect this situation. I could not find anywhere in the documentation on what schema the data base should use, so I made it utf8_mb4_bin. Whether or not that got changed during the install I do not know. Let me know If you need anything else.

**Comment by Gregory92** [comment]
Just checked that database, and the table zp_canvas_items table is showing **success** which correlates to Validated - Correct in class.leancanvas.php ("success" => "status.validated_true")

So, what the board is displaying on the webpage is correct, the item is displaying "Validated - Correct" on the board. However, when you click on that item and go to edit it, the dropdown menu is populated with "Validated - Wrong", which is not what is displayed on the board view or stored in the database. 

-ps 
My database Collation is showing up as utf8mb4_bin, but all tables in this database are showing utf8mb4_unicode_ci if that helps at all.

**Comment by marcelfolaron** [comment]
Thanks for the detailed bug report. We will cut a new release this weekend and will include a bugfix for that.

**Comment by Gregory92** [comment]
Thanks marcelfolaron!

> 
> 
> Thanks for the detailed bug report. We will cut a new release this weekend and will include a bugfix for that.
