### ISSUE TITLE
[Bug]: Inconsistent Application of LEAN_APP_URL Variable Causes Missing CSS/JS Resources

### ISSUE THREAD

**Issue by TheMatzy** [Leantime/leantime#2787]
### What is your set up?

Self Hosted Docker

### Version

3.3.0

### Describe the issue

I updated my Docker container to version 3.3.0, but now I’m experiencing an issue where CSS and JavaScript are not loading correctly.

It seems the LEAN_APP_URL variable from the .env file is not being applied consistently. For testing, I set the LEAN_APP_URL variable to quark.domain.de. While this seems to work for light.css (as shown in point 2 of the attached image), the other CSS and JavaScript resources are not properly referencing quark.domain.de. This inconsistency is causing the styling issues.
 
<img width="1021" alt="image" src="https://github.com/user-attachments/assets/1c8dfaa6-f0d3-4944-980e-2e7b9591ca9e">

### Reproduction steps

Change the .env Env variable LEAN_APP_URL to any other domain, and it don't work.
<img width="1098" alt="image" src="https://github.com/user-attachments/assets/8cfcde2a-8dbf-4c50-aadf-6d9bdcbebb47">
<img width="331" alt="image" src="https://github.com/user-attachments/assets/4164c716-681d-4ef0-a51a-b664b86cc6ba">
<img width="1021" alt="image" src="https://github.com/user-attachments/assets/1c8dfaa6-f0d3-4944-980e-2e7b9591ca9e">

**Comment by marcelfolaron** [comment]
When you set the lean_app_url did you include http/https? The protocol is
required with that variable.

Marcel Folaron - Co-Founder

phone. 206-371-1325

email. ***@***.***

web. https://leantime.io

**Comment by TheMatzy** [comment]
Hi, yes of course I have set that. See the screenshots I have attached. It really is a bug. The same problem occurs in a fresh installation.

**Comment by PterX** [comment]
I have same issue

**Comment by lpier** [comment]
I'm experiencing the same issue

**Comment by marcelfolaron** [comment]
Fix is ready and will be released shortly. https://github.com/Leantime/leantime/pull/2792

**Comment by marcelfolaron** [comment]
Fixed in 3.3.1
