### ISSUE TITLE
[Bug]: All API calls have stopped working

### ISSUE THREAD

**Issue by jeppekroghitk** [Leantime/leantime#2807]
### What is your set up?

Self Hosted Docker

### Version

3.3.1

### Describe the issue

After some digging, it seems that all parameters are lost somewhere around the executeAction method in Frontcontroller.php.

### Reproduction steps

1. Call api endpoint with following body
{
    "method": "leantime.rpc.Tickets.Tickets.getAll",
    "jsonrpc": "2.0",
    "id": 1,
    "params": {
    }
}
2. Receive error saying that method is required
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "Invalid params",
        "data": "Must include method"
    },
    "id": null
}

**Comment by rqi14** [comment]
I have issues connecting to the APIs as well. The error I got is "Invalid API endpoint"

**Comment by jeppekroghitk** [comment]
> I have issues connecting to the APIs as well. The error I got is "Invalid API endpoint"

@rqi14 what endpoint are you trying to call?

https://docs.leantime.io/#/api/README

**Comment by rqi14** [comment]
> > I have issues connecting to the APIs as well. The error I got is "Invalid API endpoint"
> 
> @rqi14 what endpoint are you trying to call?
> 
> https://docs.leantime.io/#/api/README

My code is as below
```
import requests
from datetime import datetime 
import yaml
url = r"https://leantime.*******.com/api/jsonrpc"
headers = {
    "accept": "application/json",
    "x-api-key": "lt_*********************",
}
post_data = {
    "method": "leantime.rpc.Projects.getAllProjects",
    "jsonrpc": "2.0",
    "id": "airflow" + str(datetime.now().timestamp()),
    "params": {
    }
}
response = requests.post(url,json=post_data, headers=headers)

print("Status Code:", response.status_code)
formatted_yaml = yaml.dump(response.json(), sort_keys=False)
print("Response Body:")
print(formatted_yaml)
```

The result get is:

```
Status Code: 404
Response Body:
error: Invalid API endpoint
```

**Comment by jeppekroghitk** [comment]
@rqi14 
As per https://docs.leantime.io/#/api/classes/Leantime/Domain/Projects/Services/Projects?id=leantimerpcprojectsprojectsgetallprojects

leantime.rpc.Projects.getAllProjects 
should be
leantime.rpc.Projects.Projects.getAllProjects

That will fix your 404 :)

**Comment by marcelfolaron** [comment]
Hey, I found the issue in the authentication middleware and have a fix ready. Additionally I created a new set of unit tests and acceptance tests to make sure the API access is always tested:
https://github.com/Leantime/leantime/pull/2811 

I could use some help writing tests for some of our most used API methods to check the method name works and the method signature, parameters are working correctly.

**Comment by rqi14** [comment]
> @rqi14 As per https://docs.leantime.io/#/api/classes/Leantime/Domain/Projects/Services/Projects?id=leantimerpcprojectsprojectsgetallprojects
> 
> leantime.rpc.Projects.getAllProjects should be leantime.rpc.Projects.Projects.getAllProjects
> 
> That will fix your 404 :)

I tried it and still got the same error

**Comment by marcelfolaron** [comment]
@rqi14 If you are on 3.3.1 you will need to wait until my PR is merged.

**Comment by rqi14** [comment]
> @rqi14 If you are on 3.3.1 you will need to wait until my PR is merged.

I confirm on 3.3.2 the problem has been fixed. Thank you very much!

**Comment by jeppekroghitk** [comment]
@marcelfolaron Great, thank you!
