### ISSUE TITLE
[Bug]: import csv 

### ISSUE THREAD

**Issue by Double-Click-ERP** [Leantime/leantime#2817]
### What is your set up?

Self Hosted Server

### Version

3.3.2

### Describe the issue

Sprint and Milestone doesn't imported

### Reproduction steps

1.Create csv with Sprint & Milestone included in the data
2.Import csv
3.Sprint & Milestone are appear in the Review page put not imported after Confirm

**Comment by marcelfolaron** [comment]
I just checked again and while it may not seem obvious sprints will not be automatically created. So you would have to create the sprints first and then add the sprint id into the spreadsheet.

**Comment by Double-Click-ERP** [comment]
Sprint/Milestone already created before import .
So the trick is to seat the Sprint/Milestone as ID not as Name , however i can use the Project as Name not as ID in import file .

I think if all fields the same in use will make it easy to use , as Name or as ID
