### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by goldhase** [Leantime/leantime#282]
After deleting a projekt, I get the message that I´m not assigned to any other projekts although I am.
I have to create a new one to be able to switch to other projekts.

**Leantime Version**
2.1.4

**Comment by goldhase** [comment]
I can´t even change any settings.
I have administrator permission.

**Comment by marcelfolaron** [comment]
Thanks for reporting. I will look into that.
In the meantime can you try to logout and login again to see if that
resolved the issue?

**Comment by goldhase** [comment]
Yes I have already tried this.
In the moment when this message appears I´m not able to do anything in leantime except open external weblinks and logout.
