### ISSUE TITLE
[FEATURE] Sprint List sort by alphabet

### ISSUE THREAD

**Issue by goldhase** [Leantime/leantime#286]
It would be fantastic if it would be possible to sort the Sprint list by alphabet or arrange them by drag an drop as I find it best. When you have more than 10 sprints, an unsorted list becomes confusing.
I'm even happy if it just sorts everything automatically alphabetically.

**Comment by marcelfolaron** [comment]
Would you mind sharing more about your sprint naming? The current sorting is meant to show the most recent sprints first, assuming that old sprints are done and won't be accessed a lot.

**Comment by goldhase** [comment]
in big projects we have a lot of sprints and work on them simultaneously - it would be easier to search if they are sorted by alphabet (an additional function would be great)
