### ISSUE TITLE
Master Dashboard & Few Minor Issues (To-Do Modals)

### ISSUE THREAD

**Issue by shaiquddin** [Leantime/leantime#287]
As a business owner or project manager, I'd like to see a master dashboard comprising of summary of all active projects, time logs and recent activities upon logging in. That would help me to get a quick overview of progress.

There are a few issues that I've identified:

1. Changing status of a project to 'closed' doesn't hide it from the sidebar.
2. If a client has only 1 project assigned to it, then upon project close, client dropdown must also hide. 
3. Editing a to-do on the kanban board should be easier. Instead of redirecting to a new screen, why not open a lightbox or a popup modal so we don't have to switch screens.
4. Deleting a to-do on the kanban board should not redirect the user to a new screen to confirm delete. It should be a popup or something very intuitive.

**Comment by marcelfolaron** [comment]
Hi, Thanks for the report. 
Which version are you currently using? We introduced a new Portfolio view in 2.1.3. Let me know if you have any feedback around that view. 

On 2 & 3: I fully agree. I'll keep this issue open to track the work towards this.

**Comment by shaiquddin** [comment]
I updated today to the latest version. Liked the portfolio view but it still needs some improvements. Overall good. Looking forward to the 2 & 3

**Comment by xekon** [comment]
In Kanboard there is a plugin called BigBoard. It allows you to select multiple projects and see all cards simultaneously related to those projects. Over the last few days I have installed leantime, wekan, leantime, and already had kanboard installed.

So far I have not seen a master dashboard like the one in Kanboard, I am exploring alternative kanboard projects, even though kanboard has the bigboard plugin, it has its own set of unique issues and development of kanboard has not been fast enough (we have used it nearly 2 years)

here is a picture of the bigboard plugin I am referring to, you can see its currently showing a view that includes 3 different projects:

![bigboard](https://user-images.githubusercontent.com/106644/144164210-8248d07f-aa40-4109-bc2f-7238a318746f.png)
