### ISSUE TITLE
[FEATURE] Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by nikolasj5** [Leantime/leantime#289]
Already worked on it and currently using it. Any comments are welcome!

**Comment by antonio-emilio** [comment]
I'm kinda lost how can I use it. Can I install it using docker?

**Comment by jboilesen** [comment]
Olá @antonio-emilio,

Você pode [instalar usando o docker](https://github.com/Leantime/docker-leantime) ou através de um servidor (LAMP ou WAMP) com Apache - ou Nginx -, com PHP e um banco de dados MySQL [conforme as instruções de instalação](https://github.com/Leantime/leantime).

**Comment by antonio-emilio** [comment]
> Olá @antonio-emilio,
> 
> Você pode [instalar usando o docker](https://github.com/Leantime/docker-leantime) ou através de um servidor (LAMP ou WAMP) com Apache - ou Nginx -, com PHP e um banco de dados MySQL [conforme as instruções de instalação](https://github.com/Leantime/leantime).

Eu já possuia uma instalação via docker, mas como ele pega a última release, e não o última versão do github, não havia essa tradução. Ai ao invés de fazer o pull da ultima release, coloquei da última versão do trunk. 
Instalei, mas mesmo assim, no menu não aparece a opção de português...

**Comment by jboilesen** [comment]
As línguas do leantime ficam na pasta [leantime / resources / languages](https://github.com/Leantime/leantime/tree/master/resources/language).

Verifique se o arquivo pt-BR.ini existe e se há a seguinte linha no arquivo languagelist.ini:

`pt-BR = "Português Brasileiro"`

Tendo estes é para a tradução funcionar. Na dúvida, reinicie o serviço do PHP.

**Comment by antonio-emilio** [comment]
Ontem eu perdi umas duas horas tentando resolver isso e com essa ajuda sua eu consegui resolver! Muito obrigado cara :)

**Comment by LeviLucena** [comment]
> Olá@antonio-emilio,
> 
> Você pode [instalar usando o docker](https://github.com/Leantime/docker-leantime) ou através de um servidor (LAMP ou WAMP) com Apache - ou Nginx -, com PHP e um banco de dados MySQL [conforme instruções de instalação](https://github.com/Leantime/leantime) .

Estou tentanto instalar usando o Xampp, me sinto confuso.

**Comment by jboilesen** [comment]
@LeviLucena quais são as dúvidas? Poderia trazer mais detalhes?

O ambiente que está montando é Windows ou Linux?
