### ISSUE TITLE
[BUG] When using Slack notifications, the ToDo link opens the details within the most recently viewed project even if the ToDo is associated with a different project.

### ISSUE THREAD

**Issue by Marcquito** [Leantime/leantime#292]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Let me try to paint the picture as clear as possible...
Let's say that the last time I was using Leantime, I was working with "Project-C". I close Leantime and a few moments later, I see a Slack notification come through that someone posted a new ToDo item within "Project-A". I open the notification in Slack and click the link to open Leantime to view the item. When Leantime opens to show the ToDo details... it will be showing the details within "Project-C" since this was the last project I actually had opened. This causes some problems if you don't notice right away if you are viewing discussions, time sheets, etc. 

Of course, navigating to the correct project and finding the fresh ToDo solves the problem, but I've noticed some people on my team not noticing right away and causing some confusion. 

**To Reproduce**
1. Go to a project (Project A) that is connected to Slack and post a new ToDo item. For now, ignore the Slack notification that comes through.
2. Before exiting Leantime, visit a _different_ project (Project B).
3. Now open Slack, visit the ToDo notification, and click the link to open the details.
4. You will now see how the ToDo posted in Project A is being viewed within Project B. 

**Expected behavior**
I expect the link to open the ToDo item details within it's parent project, not the project I last visited.

**Leantime Version**
2.1.4

**Server**
Apache

**PHP / MySQL Version**
7.3

**Additional context**
No other details, thanks!

**Comment by marcelfolaron** [comment]
Thanks for reporting. I see the bug and will get a fix out. We are planning a new release this weekend, so this should go out soon

**Comment by andrewagrahamhodges** [comment]
Hello, I found an additional issue with this particular topic. If you change the state of a task in Project A while it is displayed within Project B as described above. The Task actually changes from Project A to Project B. 

I can reproduce this easily on version 2.1.14. With this method it is easy to move tasks from one project to another and loose visibility of the task.

**Comment by marcelfolaron** [comment]
This should be fixed with 2.1.6
