### ISSUE TITLE
[FEATURE] Make one sprint to hold multiple stories and/or tasks from multiple projects

### ISSUE THREAD

**Issue by Aquive** [Leantime/leantime#294]
We want to make one sprint for projects from several different clients. The problem now is when there are 4 clients with each 10 hours of work to fill a week with 40 hours you must make 4 different sprints with each 10 hours. Better (for us) would be to combine those in 1 sprint (just like in Jira).

The solution would be to make a sprint and choose own filters which backlog tasks and stories show up for that sprint.

**Comment by marcelfolaron** [comment]
The way Leantime is set up right now it is highly unlikely this will ever be implemented. We are thinking about a dependency relationship between projects but I don’t think it would quite be the same feature as described here. Closing this for now until further notice
