### ISSUE TITLE
[BUG] Autocomplete showing upon Datapicker

### ISSUE THREAD

**Issue by nikolasj5** [Leantime/leantime#295]
**Describe the bug**
In a date field which previously had been filled, the autocomplete suggestions are shown upon the calendar (Datapicker) blocking its visualization.

**To Reproduce**
1. Go to 'Edit Task'
2. Click on 'Working on it from until' date field
3. See error

**Expected behavior**
Autocomplete should not show when there's a datepicker field.

**Leantime Version**
2.1.4

**Server**
nginx

**PHP / MySQL Version**
PHP 7.3
psql (PostgreSQL) 12.1 (Debian 12.1-1.pgdg100+1)

**Additional context**
Google Chrome Version 83.0.4103.97

**Comment by nikolasj5** [comment]
I still have to test, but a solution seems to be:

```
$('.datepicker').on('click', function(e) {
   e.preventDefault();
   $(this).attr("autocomplete", "off");  
});
```

**Comment by it-mkl** [comment]
I added autocomplete="off" into the relevant fields in the submodule template, and that works.
