### ISSUE TITLE
Garbled characters in csv file

### ISSUE THREAD

**Issue by n-mit** [Leantime/leantime#297]
Hello.
I am downloading the master from the branch of Github and operating the installation (development) on my own PC.

If you output the data input in Japanese as csv, the characters will be garbled.
Although the characters are garbled in Excel, they can be displayed in Sakura Editor without any problems.

I'm not very knowledgeable so I would appreciate any help if I could.

![rapture_20200624154249](https://user-images.githubusercontent.com/65585619/85509694-65746100-b631-11ea-9587-90bb8a2fb588.jpg)

**Comment by marcelfolaron** [comment]
Hi, 
Excel allows you to choose the character encoding. Make sure you set it to utf-8 when opening the file.  https://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically

**Comment by n-mit** [comment]
Thank you for your quick answer.

Is it possible to add some code to prevent garbled characters when opening Excel directly after outputting csv?
