### ISSUE TITLE
[BUG] KanBan/To-Do Page Sometimes 404 Not Found

### ISSUE THREAD

**Issue by groovybluedog** [Leantime/leantime#298]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
After having created a new project, intermittently, when I go to the To Do list, I will get a random 404.

In the URL bar I notice that there seems to be a double of the directories:
/projects/leantime**/projects/leantime**/tickets/showAll

Yesterday this only occured when I was on the Kanban view of ToDo, I go to Table view, and then come back from ToDo. 

Sometimes I will get continous 404's when I visit the To-Do menu item, but other times I can go back to the default Leantime Onboarding and To-Dos can work again. But I just did that change, and clicked To-Dos, and I get the same 404.

I will only get this with the To-Dos menu. The upload of files was successful, I can't see any errors in the server logs, and this occured yesterday too on an entirely different Firefox session with firefox set to clear all data including the cache. My base URL in the config is also set correctly. 

Just to be sure I did a fresh install, went to the To-Dos, went to another menu item, and on going back to To-Do, I hit the same 404 error. I noticed the URL had two slashes in which I confirmed was because I left the trailing slash in the appurl of the configuration file, however the URL is still incorrect with two lots of the directory:

projects/leantime//projects/leantime/tickets/showKanban

Even correcting the slash still has the wrong URL. It should only be /projects/leantime/tickets/showKanban

**To Reproduce**
1) Make project
2) Go to To-Dos menu
3) Use view options to change the view, and then go back
4) Try the To-Dos menu again if you haven't got the 404 yet

**Expected behavior**
Not to get the 404

**Leantime Version**
Latest release 2.1.4

**Server**
Apache Version | 2.4.43

**PHP / MySQL Version**
PHP Version | 7.4.7
MySQL Version | 5.7.30

**Additional context**
None

**Comment by marcelfolaron** [comment]
Thanks, I see there are a few links that have no been updated yet. I will take a look

**Comment by kimberely27** [comment]
Not sure if that is the right approach but I fixed it by editing public/index.php Line 14
`    define('CURRENT_URL', $config->appUrl.$settings->getRequestURI($config->appUrl));`
to
`    define('CURRENT_URL', $settings->getRequestURI($config->appUrl));`

**Comment by BenjaminKeating1986** [comment]
> 
> 
> Not sure if that is the right approach but I fixed it by editing public/index.php Line 14
> ` define('CURRENT_URL', $config->appUrl.$settings->getRequestURI($config->appUrl));`
> to
> ` define('CURRENT_URL', $settings->getRequestURI($config->appUrl));`

This fixed my problem thank you

**Comment by chris-dealerwebs** [comment]
I've noticed this on a recently installed copy in a sub directory, it appears to happen every time the filters are used in the to do section. 

The above fix didn't work.

**Comment by broesie** [comment]
Any updates about this, months after the original post. I just downloaded 2.1.4 and still got the same problem, to do's is leading to a wrong url...
