### ISSUE TITLE
[FEATURE] Drag & Drop image upload functionality /  multiple image upload

### ISSUE THREAD

**Issue by santibm** [Leantime/leantime#300]
It would be great to be able to drag a bunch of images when editing a to-do, if it's too hard, then the ability of adding more than one image at a time would also be a great time saver

**Comment by marcelfolaron** [comment]
Thanks. That is a great idea. I'll take a look. We are currently using tinymce as the editor but were wondering if ckeditor might be a better choice.

**Comment by santibm** [comment]
Hi Marcel, Im working on it, almost got it, I'm implementing dropzone.js I'll post a pr and you can check if you like it! thanks

**Comment by santibm** [comment]
hi @marcelfolaron, how could I share with you what I've done so far? Is almost working there just an issue that maybe you can give me a hand with
