### ISSUE TITLE
[BUG] Login goes to incorrect URL

### ISSUE THREAD

**Issue by lamping7** [Leantime/leantime#304]
**Describe the bug**
I have this setup with the official docker image behind nginx. Nginx is serving this up at `http://myhost.myuniversity.edu/projects` which is what I have `LEAN_APP_URL` and the corresponding `appUrl` set to. When trying to login, the `requestUrl` is `'/'`, taking you to `myhost.myuniversity.edu` when you click the "Login" button, which is a 404 for obvious reasons. You can then change the address in the bar to the correct URL (`http://myhost.myuniversity.edu/projects`) and you're logged-in and get to the dashboard. All other functions seem to work as expected after this.

**To Reproduce**
 - Self-explanatory

**Expected behavior**
 - Self-explanatory

**Leantime Version**
2.1.4

**Server**
nginx

**PHP / MySQL Version**
docker image with mariadb 10.4.13

**Additional context**
I have a fix in a coming PR.

**Comment by marcelfolaron** [comment]
Left a comment on the PR. Did you test redirects from emails?

**Comment by lamping7** [comment]
This is still a problem.

**Comment by marcelfolaron** [comment]
I think this is resolved now. Will close. Let me know if you are still running into issues
