### ISSUE TITLE
View only role for Milestone/To-do/Patches

### ISSUE THREAD

**Issue by jackylamhk** [Leantime/leantime#309]
Create a "view only" role where all the info is echo-ed instead of letting the user edit, and the user will not have permission to edit, like a view only file.
Currently my temporary workaround is to make the "add" or "edit" buttons only show when permission is > developer.

Also requesting to show/hide certain modules such as "Research" from customer. Currently uses same workaround but still accessible via direct URL.

**Comment by marcelfolaron** [comment]
Thank you for the request. We are indeed looking into a more flexible role management system. Work should progress in q3
