### ISSUE TITLE
[BUG] Another sub-folder path related incorrect URL

### ISSUE THREAD

**Issue by lamping7** [Leantime/leantime#314]
https://github.com/Leantime/leantime/blob/a72ad3e9bcbe2b1068aa88403905a83b536b5d1e/src/domain/clients/templates/showClient.tpl.php#L140

https://github.com/Leantime/leantime/blob/49a121e4252b75145b761d982305fbf2aa9bf870/resources/language/en-US.ini#L482

Just like #304, this doesn't work with sub-folder paths as your base URL. This is just one example.

**Comment by marcelfolaron** [comment]
Thanks, I'll run another test with your fix today and see if that works
