### ISSUE TITLE
[BUG] minors errors in en-EN.ini

### ISSUE THREAD

**Issue by clementaf** [Leantime/leantime#316]
Hello,

I have create french translation from en-EN.ini.

I think that file have minors errors,  I don't have see correction in the master branch at this day.

line 780 for the key __email_notifications.project_update_message__, replace _the to-do_ by _the project_

line 810 to 815 dupplicate key __email_notifications.milestone_update_subject__ and __email_notifications.milestone_update_message__.

line 857 for the key __tour.once_youre_done_adding_milestones_go_todos__, em is not closed to the end.

I can create pull request if you want.

**Comment by marcelfolaron** [comment]
Thanks for submitting, good catch!
