### ISSUE TITLE
 Company Settings cannot change anything reverts to original

### ISSUE THREAD

**Issue by bikker** [Leantime/leantime#318]
EDIT: Solved by reinstalling , might be some permissions issue, you can close this ! thank you

*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
We cannot change anything  in  Company Settings, on saving it reverts to original

**To Reproduce**
1. Go to 'company settings
2. change any settings like color or logo or company name
3. reverts to original on saving

**Expected behavior**
To change the settings

**Leantime Version**
2.1.4

**Server**
Apache

**PHP / MySQL Version**
PHP 7.3  ,  MYSQL 5.7.31

**Comment by marcelfolaron** [comment]
I am glad it got resolved. Thanks for closing
