### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sogln** [Leantime/leantime#322]
The Editor doesn't work correct in the code function.
If you want to work with <code> p. e. in the description editor "label.description", no code is not displayed!

1. Go to 'description editor of an idea'
2. Click on 'Format <> Code'
3. no code is not displayed

**Expected behavior**
html code should be displayed

**Leantime Version**
2.4.1

**Server**
Apache 2.3.4.1-5+deb10u3

**PHP / MySQL Version**
PHP 7.4 and Mysql 5.0

**Additional context**

**Comment by marcelfolaron** [comment]
This will not show you the actual html code but format the text to be "code" which changes the font and size so it looks like code form an editor
