### ISSUE TITLE
 notification.database_exists

### ISSUE THREAD

**Issue by kamranbhutto** [Leantime/leantime#327]
![Screenshot_14](https://user-images.githubusercontent.com/3133422/92353975-d8528b80-f0fa-11ea-81f9-0257580a1be9.png)
![Screenshot_13](https://user-images.githubusercontent.com/3133422/92353893-b0632800-f0fa-11ea-82c8-1ce5397941bd.png)
**Describe the solution you'd like**

notification.database_exists

**Additional context**

**Comment by marcelfolaron** [comment]
Did you have a failed install before? This message appears when the database selected is not empty.

**Comment by sarsi2k** [comment]
Same problem! First i did install on local and when i got nginx to work i got this!

**Comment by Drew5316** [comment]
![Screen Shot 2020-12-01 at 8 20 34 PM](https://user-images.githubusercontent.com/7198774/100819903-b5422a00-3412-11eb-8bc1-eae0eedb08e5.png)
Same issue. How to resolve?
