### ISSUE TITLE
[BUG] Layout issue on iPad / tablet of login page

### ISSUE THREAD

**Issue by diderich** [Leantime/leantime#328]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Login page layout is inconsistent between tablet and desktop.

![image](https://user-images.githubusercontent.com/10230144/92724525-0dfdab80-f36b-11ea-8eda-eb1b7e2bbcd8.jpeg)

**To Reproduce**
1. Go to login page on tablet, e.g., iPad Pro

**Expected behavior**
Login page looks the same independent of the device, i.e., being responsive.

**Leantime Version**
2.4

**Server**
Apache 2.4

**PHP / MySQL Version**
php 7.3

**Additional context**

**Comment by Marcquito** [comment]
I found this bug earlier as well! Not a big deal since we never log in using a tablet, but it's there.

**Comment by tiredofit** [comment]
Can confirm it is happening with Safari 13, not Chrome, IE, Firefox.

**Comment by AlexanderTamo** [comment]
Seems the CSS is wonky across the application when using Safari 13.
<img width="1556" alt="image" src="https://user-images.githubusercontent.com/5807320/93937438-a6d1e680-fcdc-11ea-8726-85395a0f322d.png">
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/5807320/93937491-bfda9780-fcdc-11ea-9f84-cc2e818df5fe.png">

**Comment by marcelfolaron** [comment]
Thanks all. Will take a look at Safari and in particular ipad. Is that the latest ipad? Trying to find the correct resolution

**Comment by diderich** [comment]
Just retried it with iOS 14.0 and now it works / is displayed as expected.
