### ISSUE TITLE
[FEATURE] add option to disable SMTP authentication

### ISSUE THREAD

**Issue by kharkatar** [Leantime/leantime#332]
**Is your feature request related to a problem? Please describe.**
We are using SMTP relay without authentication, by default the mailer class force the authentication.

**Describe the solution you'd like**
add a new env like LEAN_EMAIL_SMTP_AUTH to permit to disable authentication with SMTP.

**Comment by marcelfolaron** [comment]
Thanks. I agree that we should add that variable. In the meantime you can jump into https://github.com/Leantime/leantime/blob/master/src/core/class.mailer.php and set line 80 to false.

**Comment by ruhnet** [comment]
I just submitted a pull request that addresses this (and also another SMTP feature option).
