### ISSUE TITLE
Deleting/locking installation path after installation?

### ISSUE THREAD

**Issue by slushpuppy** [Leantime/leantime#335]
I may be incorrect, but does it appear that regular users can still run the installation script to give themselves admin inspite of the installation having been performed already?

**Comment by sgissi** [comment]
I just tried and, while the page does load, trying to install gives an error that database already exists. Did you manage to run the installation script?

**Comment by carsteneu** [comment]
I tried, it did not run - but anyway - it should not work at all...  so everyone will try to do and it does not feel very save at all.

**Comment by marcelfolaron** [comment]
That seems to be a bug. The script should check if Leantime is installed and forward to the login page.

**Comment by marcelfolaron** [comment]
Are you on the latest version?

**Comment by carsteneu** [comment]
yes, fetched from upstream master...

**Comment by marcelfolaron** [comment]
Yeah agree, it should not show the install screen at all

**Comment by JedMeister** [comment]
It may not be the best way of doing it but one easy way to disable it (assuming you're using Apache to serve) is to comment out the relevant lines from the `.htaccess` file. I.e. in `leantime/public/.htaccess`:

```
#RewriteRule ^install$ index.php?install=true
#RewriteRule ^install/([^/\.]+)/?$ index.php?install=true
```

**Comment by r0l1** [comment]
Any updates on this issue?

**Comment by marcelfolaron** [comment]
I'll take another look at this bug this week

**Comment by nagro** [comment]
Any updates ?

**Comment by marcelfolaron** [comment]
I'll push a new release this weekend which will contain a fix
