### ISSUE TITLE
[FEATURE] Calendar filter view to show open vs done todo's

### ISSUE THREAD

**Issue by tiredofit** [Leantime/leantime#340]
**Is your feature request related to a problem? Please describe.**
I'd really like to use the Calendar function in detail, however it is showing too much data.

**Describe the solution you'd like**
Have a view to limit "Done" tasks from the calendar as they are adding stress in my weekly planning thinking I have more things to do than I actually do.

Additionally an alternative would be to have completed To-Do's display in a different colour if they were all to show on the page, but having that sort of flexibility would cover many use cases.

**Comment by carsteneu** [comment]
I think done items should not be in the calender... done is done in my opinion.

**Comment by carsteneu** [comment]
In src/domain/calendar/repositories/class.calendar.php Line 58 
instead of 
```
WHERE (tickets.editorId = :userId OR tickets.userId = :userId) AND tickets.type <> 'Milestone' AND tickets.type <> 'Subtask'";
```
do this
```
WHERE (tickets.editorId = :userId OR tickets.userId = :userId) AND tickets.type <> 'Milestone' AND tickets.type <> 'Subtask' AND tickets.status <> '0'";
```

**Comment by tiredofit** [comment]
Thanks, that works as a quick fix!
So much potential with this application, appreciate your quick response.
