### ISSUE TITLE
[FEATURE] wysiwyg editor in task discussion

### ISSUE THREAD

**Issue by mkrnac** [Leantime/leantime#341]
**Is your feature request related to a problem? Please describe.**
One thing what this toll is lacking is a way to track work. This can be handled by Discussion, but there is missing an editor to format it. For example when you want to add some code snippets or command line history. 
Another possibility could be to implement work log tab, but now wysiwyg editor in Discussion should be sufficient. 

**Describe the solution you'd like**
Add wysiwyg editor to Task Discussion

**Comment by carsteneu** [comment]
Hi - maybe markdown would be sufficient? Like here on github... what do you think?

**Comment by loslolos** [comment]
One thing which is also pretty much crucial is ability to insert an image. I'm not sure if this can be done by markdown editor, if so, I think markdown is OK then.

**Comment by carsteneu** [comment]
That would be easyier with the tinymce editor... an alternative would be to attach an image... this could be also ok i think - what is your opinion?

**Comment by loslolos** [comment]
For the work logging purposes I would definitely recommend to have an inline images. So it seems tinymce is the best choice. But maybe for those who needs/wants markdown, make it switchable, or configurable in preferences?

**Comment by carsteneu** [comment]
ok - so - time is limited :-) - i would also prefer tinymce ...

**Comment by marcelfolaron** [comment]
Hi thanks. You can already copy past images into the editor. We do need to add it to the discussions. 
I have done some research on the existing markdown editors and nothings quite seems to do everything we need. As such I am inclined to stick with tinymce for now. The other option is CKEditor which is similarly powerful. It does have better markdown support as well.

**Comment by marcelfolaron** [comment]
Adding the editor to the comments should be a pretty easy tasks since there is only one file that contains the html.

**Comment by carsteneu** [comment]
Hi - yes  -copy paste works - but it does not save the image... but thats only a short test...

**Comment by tiredofit** [comment]
I recommend that it is be an HTML editor like TinyMCE, Quill, Jodit. Markdown is great, but when thinking about the use case of clients accessing the systems and wanting to submit discussions, I think having something as close to a WYSIWYG editor would be easier to onboard them to using the system.

**Comment by carsteneu** [comment]
I made a patch - you can download the file and replace it if you want. or apply the patch

**Comment by loslolos** [comment]
I've applied the patch and this functionality works like charm. Thank you a lot for this.
But I have one other comment regarding discussion. For better readability could be comments sorted in reverse order? So newest item on bottom together with editor (if you have subcomments, they are also below the main comment). If you don't think this could be handled in this thread, I can open another feature request.

**Comment by tiredofit** [comment]
Might be best for a different feature request IMO - Some people may like the current way that it is sorted. Of course having flexibility on defaults the optimal way.

Thanks @carsteneu for everything you do.

**Comment by Sonicelo** [comment]
Could this be extended to the Comments as well (like in Ideas?)
