### ISSUE TITLE
[FEATURE] Archive Project

### ISSUE THREAD

**Issue by tiredofit** [Leantime/leantime#353]
**Is your feature request related to a problem? Please describe.**
We have dozens of projects assigned, and some have completed yet still appear in our view. We do not want to delete the projects, but make reference to them at a later date.

**Describe the solution you'd like**
Ability to "Archive" a project which would mute all notifications, and remove it from a list of available projects in my dashboard. I do not know any design details on how to access the archived projects and bring it back to Active but I think that feature would be useful as well.

**Comment by carsteneu** [comment]
Archived Projects could be listet in the adminstration view of all projects und could be opened from there and reactivated if neccessary.
If you link to an item it could be still visable, but only with the correct link i think...

just my 2 cent...

**Comment by marcelfolaron** [comment]
Hi,
You can set the project to "Closed" on the project settings screen. This
will have the effect your described.

**Comment by tiredofit** [comment]
Does one need to be an instance administrator for this to occur, or can you be a different user role.

**Comment by marcelfolaron** [comment]
"Managers" can do that as well.

**Comment by tiredofit** [comment]
Thanks for your prompt reply! Will pass this onto the team and see how they make out. Closing for now.
