### ISSUE TITLE
[FEATURE] send notifications to MS Teams

### ISSUE THREAD

**Issue by businesslogic360** [Leantime/leantime#354]
Is it on the time line to add support to send notifications to MS Teams?

**Comment by marcelfolaron** [comment]
Not right now, but I can look into the API and let you know. It might be very simple.

**Comment by marcelfolaron** [comment]
Seems this should be pretty straight forward and quite similar to what Slack and Mattermost do
https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using

**Comment by amit510** [comment]
Having teams tightly integrated with leantime, would be very beneficial.

**Comment by phulstaert** [comment]
Recent documentation
Doc: https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook

Node.js example: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/incoming-webhook/nodejs
C# example: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/incoming-webhook/csharp

**Comment by guillemsuetta** [comment]
Is this still "In Progress"?

**Comment by marcelfolaron** [comment]
As of 3.2.0 we are supporting Zapier integrations. This would allow a flow like this. The alpha app is available here https://zapier.com/developer/public-invite/207240/cac6ec7a911bd5fa7924f38230d58d2f/
