### ISSUE TITLE
[BUG] Blank page when trying to enable 2FA

### ISSUE THREAD

**Issue by paulocoghi** [Leantime/leantime#356]
**Describe the bug**
After installation, when I access my profile and choose the "Manage two-factor authentication" option, that points to **`/twoFA/edit`** , I get a blank page.

The error log file remains blank.

I believe that this maybe related to my PHP 7.4 FPM that has only the `php7.4-mysql` package installed, and Leantime may require additional ones.

**To Reproduce**
1. Install Leantime normally
2. Log in with the first user created
3. Go to the profile, on **`/users/editOwn/`**
4. Click on "Manage two-factor authentication"
5. The page turns blank

**Expected behavior**
Be able to access the 2FA management feature

**Leantime Version**
2.1.4, downloaded through GitHub Releases

**Server**
Ubuntu 20.04
Nginx 1.19.6

**PHP / MySQL Version**
PHP 7.4.3 FPM
MariaDB 10.5.8

**Additional context**
My PHP 7.4 FPM installation has only the `php7.4-mysql` package installed and this may be the problem (other PHP packages may be required, but are missing).

**Comment by tiredofit** [comment]
Check your PHP Logs and you'll get better insight. However, you can try to enable `curl, xmlwriter, simplexml, and tokenizer` to get past your hurdle.


`

**Comment by paulocoghi** [comment]
Thanks for the suggestions, Dave @tiredofit ! I installed `php7.4-curl`, `php7.4-xml` and the other libraries were already installed on `php7.4-common` that was installed since the beginning.

After installing them, I restarted PHP FPM but still, same thing. Blank page with no errors on console.

Also, no errors are printed on the error_log or php log.

**Comment by gandhipurav** [comment]
Having the same issue. Seems like the functionality has been broken. I am using the turnkey stuff, so assuming that everything that is needed is already installed.

**Comment by marcelfolaron** [comment]
Any errors in resources/logs?

**Comment by paulocoghi** [comment]
> Any errors in resources/logs?

Gotcha. Yes, there is an error:

```shell
[29-Dec-2020 02:45:42 America/Los_Angeles] PHP Fatal error:  Uncaught Error: Call to undefined function Endroid\QrCode\Writer\imagecreatetruecolor() in /home/myuser/leantime/vendor/endroid/qr-code/src/Writer/PngWriter.php:67
Stack trace:
#0 /home/myuser/leantime/vendor/endroid/qr-code/src/Writer/PngWriter.php(57): Endroid\QrCode\Writer\PngWriter->createBaseImage()
#1 /home/myuser/leantime/vendor/endroid/qr-code/src/Writer/PngWriter.php(26): Endroid\QrCode\Writer\PngWriter->createImage()
#2 /home/myuser/leantime/vendor/endroid/qr-code/src/QrCode.php(381): Endroid\QrCode\Writer\PngWriter->writeString()
#3 /home/myuser/leantime/src/domain/twoFA/controllers/class.edit.php(104): Endroid\QrCode\QrCode->writeString()
#4 /home/myuser/leantime/vendor/robthree/twofactorauth/lib/TwoFactorAuth.php(131): leantime\domain\controllers\TwoFAQRCode->getQRCodeImage()
#5 /home/myuser/leantime/src/domain/twoFA/controllers/class.edit.php(82): RobThree\Auth\TwoFactorAuth->getQRCodeImageAsDataUri()
#6 /home/myuser/leantime/src/core/class.frontcontroller.php(168): leantime\domain\controllers\edit->run in /home/myuser/leantime/vendor/endroid/qr-code/src/Writer/PngWriter.php on line 67
```

**Comment by paulocoghi** [comment]
I was trying to login, to check if installing `php7.4-imagick` would solve the issue, but I forgot my password and, when trying to recover the password, Leantime says that it can't find the user (but it exists and I checked the database). :man_facepalming: 

It's not generating the recovery ID on the database, since it can't find the user _(I checked more than twice that the email is the exact same email on the database)_.

**Comment by paulocoghi** [comment]
I will probably start everything from scratch but, if the maintainers want, I can open another issue about the password recovery bug.

**Comment by marcelfolaron** [comment]
Yes, imagemagick wasnt installed. So this should fix the issue for this bug. Please do create a separate issue for the forgot password function. I am closing this one for now
