### ISSUE TITLE
Blank "To-Dos" page after second visit [BUG]

### ISSUE THREAD

**Issue by huguesderiau** [Leantime/leantime#361]
the path to "To-Dos" becomes incorrect after it has been visited once

**To Reproduce**
1. Click on "To-Dos" from the left navigation: on the first time the page loads ok (url is /leantime/tickets/showKanban)
2. Navigate to any other page via the left menu and then try to go back to "To-Dos": the page is blank (pointing to URL becomes /leantime/leantime/tickets/showKanban)

Issue also happens when adding a new To-Do or deleting an existing "To-Do"from the "To-dos" page from the column:
1. Click on "Add To-Do", give a name and save: URL becomes /leantime/**leantime**/tickets/showKanban
1. Click on "Delete To-Do" using the ••• contextual menu after confirming delete YES, same behavior

More similar issues can be seen when using leantime/tickets/showKanban
- after deleting a sprint, same double base directory in URL
- after clicking on "NEW -> add to-do" from the top left, after saving the URL this time is missing the base directory (instead of pointing to "leantime/tickets/newTicket" it points to "tickets/newTicket" 

Thank you for looking into this.

Leantime Version: 2.1.14

Server: Apache/2.4.46
PHP 7.4.9 / MySQL 5.7.30

**Additional context**
using MAMP, no SSL, my base URL is http://localhost:8888/leantime/

**Comment by marcelfolaron** [comment]
Do you see any messages in resources/logs

**Comment by huguesderiau** [comment]
No, nothing is written in the error log, I only get a 404 in the console

I applied the solution suggested in a response from bug #298 and it works.

in public/index.php
line 14
I replaced 
define('CURRENT_URL', $config->appUrl.$settings->getRequestURI($config->appUrl));
by
define('CURRENT_URL', $settings->getRequestURI($config->appUrl));

**Comment by marcelfolaron** [comment]
Hey, I am currently investigating this issue. The solution above will work for anyone using the subfolder installation, however it does not work if a subfolder is not used. There is an issue in the class.tickets.php that I am not fully understanding yet.

**Comment by rstemmer** [comment]
Sorry, I still have the bank-page issue with version 2.1.7.

Steps to reproduce (I replaced my domain by _localhost_):
 - In the left menu, click on "To-Dos" (https://localhost/leantime/tickets/showKanban gets loaded)
 - The click on "Milestones" in the left menu (https://localhost/leantime/tickets/roadmap gets loaded)
 - Click again on "To-Dos" -> blank page (https://localhost/leantime/leantime/tickets/showKanban fails to load)

Note the second "/leantime" when trying to go to the To-Dos a second time.

**Comment by thwaller** [comment]
I also have this issue, and it applies to changing from the Kanban View and the Table View ( showKanban / showAll ).

**Comment by TareqK** [comment]
I have a similar issue. I think Its related to the url. When selecting Sprints in kanban view, the URL It is using is 

``https://<domain>/tickets?act=show.Kanban`` instead of ``https://<domain>/tickets/showKanban``. This leads to an issue where if you select the sprint, it doesnt add the ``act=show.kanban`` to the URL, thus taking you to somewhere that doesnt actually exist.

The solution is to either add a redirect, or to simply add the show.kanban as hidden input
