### ISSUE TITLE
[FEATURE] Sort Milestones on Dashboard by Deadline

### ISSUE THREAD

**Issue by steinhmor** [Leantime/leantime#365]
**Is your feature request related to a problem? Please describe.**
I don't understand the sorting of the Milestones on the project-dashboard - it seems neither to be alphabeticly nor by deadline.

**Describe the solution you'd like**
I would love to see a dropdown-menu which allows me to sort the milestones by deadline, date added and status. Or at least it would be great to have them sorted by the nearest deadline.

**Comment by marcelfolaron** [comment]
Thanks, the sorting was alphabetical by headline. I just committed a change into a dev branch to sort by date. This will go out on this week
