### ISSUE TITLE
[FEATURE] Next Release

### ISSUE THREAD

**Issue by PascalBru** [Leantime/leantime#368]
Are there any plans to make a new release with the bugfixes in the next time?
The last one was a long time ago.

**Comment by PascalBru** [comment]
It would be good that the latest commits 6ab1ecd28839a9891c2caaf5b0969aaa90c882b6 and 750dff4a7ceb112f4de9936a3bccad51138cfe01 are also included.

**Comment by marcelfolaron** [comment]
I'll work on a release this week and hope to get one out by Friday.

**Comment by PascalBru** [comment]
Thats sounds great
