### ISSUE TITLE
Create Unit Tests

### ISSUE THREAD

**Issue by ghost** [Leantime/leantime#37]
We need unit tests for the whole system.

In particular for:

DB class
Frontcontroller
Template Engine
i18n
Email class
File access class

**Comment by yisraeldov** [comment]
This is scary.  Why no tests.

**Comment by marcelfolaron** [comment]
This issue was closed as part of a sweep. Reopening it to work on unit tests

**Comment by jakimfett** [comment]
Leantime would be eligible for [BrowserStack's free testing for open source projects](https://www.browserstack.com/open-source), although their system seems fairly centred on Selenium as the test framework.

What's on the table for unit testing, at the moment?

**Comment by marcelfolaron** [comment]
Closing this for now. Started writing unit tests
