### ISSUE TITLE
OAuth2 and OpenID Connect [FEATURE]

### ISSUE THREAD

**Issue by Ezyweb-uk** [Leantime/leantime#371]
Would be great if the API could include OAuth2 for login authorization and OpenID Connect for login authentication.

**Comment by marcelfolaron** [comment]
Would love that. It will take me a while as I am not quite familiar with the implementation details of OpenId in PHP

**Comment by jsmaco** [comment]
This would be a quite welcomed feature!

**Comment by acul009** [comment]
Just a heads up: I'm currently working on this, using Authentik as my reference implementation.
I'll send a Pull-Request once I've got a prototype working.

**Comment by timmwille** [comment]
somewhat linked issue is #1478 (not directly)

thank you @acul009 and @marcelfolaron this will be a great addition to promote this to smaller Organisations that usually do not use Ldap to connect to their SSO ...

**Comment by marcelfolaron** [comment]
Basic OpenID is now available

**Comment by timmwille** [comment]
thank you @marcelfolaron

**Comment by andreasdueren** [comment]
At the chance of sounding stupid but I really couldn't find anything in the documentation or the repository: Whats the Login callback Url for OpenID?

**Comment by acul009** [comment]
The callback url is /oidc/callback

**Comment by andreasdueren** [comment]
> The callback url is /oidc/callback

Perfect, thank you! Now it shows me `The received provider https://open-id-provider.tdl/openid does not match the local setting https://open-id-provider.tdl/.well-known/openid-configuration` after login. Any ideas on how to troubleshoot this?

**Comment by jdaviescoates** [comment]
Did you manage to get this working @andreasdueren ?

**Comment by jdaviescoates** [comment]
Thanks for the clarification @acul009 :slightly_smiling_face:

**Comment by q20** [comment]
> > The callback url is /oidc/callback
> 
> Perfect, thank you! Now it shows me `The received provider https://open-id-provider.tdl/openid does not match the local setting https://open-id-provider.tdl/.well-known/openid-configuration` after login. Any ideas on how to troubleshoot this?

Was also hoping to get this ironed out. Fresh install, testing this platform out. All my other OIDC services authenticate correctly with Pocket ID.
Any ideas?
