### ISSUE TITLE
[BUG] Refactor psettings

### ISSUE THREAD

**Issue by marcelfolaron** [Leantime/leantime#375]
Psettings  for comments added a new field in the project table. 
Instead we should use the zp_Settings table to store settings like that.

**Comment by marcelfolaron** [comment]
To get a setting you can use:
`
$this->settingsRepo->getSetting("projectsettings.".$projectId.".YOURSETTINGSKEY");`

to save one:

` $this->settingsRepo->saveSetting("projectsettings.".$projectId.".YOURSETTINGSKEY", $settingVar);`

**Comment by gelomon** [comment]
Hi @marcelfolaron will there be an upgrade instruction if you are coming from 2.1.4? I have tried upgrading the image to 2.1.6 and encountered this zp_settings error. Thank you

**Comment by marcelfolaron** [comment]
The bug was fixed in 2.1.6.
Are you still seeing an error about the psettings?

**Comment by gelomon** [comment]
@marcelfolaron I upgraded the image of leantime to use the latest (2.1.6). The instance is up but when I login, an error 500 shows up on my browser and the log contains the following:

`PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'zp_projects.psettings' in 'field list' in /var/www/html/src/domain/projects/repositories/class.projects.php:357`

this is related to this one right?
