### ISSUE TITLE
[BUG] Deleting all sprints breaks TODOs

### ISSUE THREAD

**Issue by r0l1** [Leantime/leantime#378]
**Describe the bug**
Deleting all sprints in a projects causes all TODOs to disappear. This is quite dangerous.

**To Reproduce**
1. Create TODOs
2. Create a sprint
3. Delete all sprints
4. TODOs and Tasks disappear. The only solution is to delete the complete project to fix this.

**Leantime Version**
2.1.4

**Server**
Apache (Docker version)

**Comment by marcelfolaron** [comment]
Thanks. This is a really good point. Let me get a fix in this week

**Comment by r0l1** [comment]
Thank you for looking into this. Great project imho! I'll definitely support this project with a donation.

**Comment by duzilla** [comment]
Hi Guys,

Just a solution that worked out, not sure it was the right thing to do but solved my problem by editing src/domain/general/templates/menu.tpl.php

from
<a href="<?=$this->get('ticketMenuLink');?>"><?=$this->__("menu.todos") ?></a>
to
<a href="<?=BASE_URL ?>/tickets/showKanban"><?=$this->__("menu.todos") ?></a>

**Comment by duzilla** [comment]
Hi Guys,

Just a thought I would share a solution that worked for me, not sure if its the right way to go about it, just edited `'src/domain/general/templates/menu.tpl.php`' file line 65

from
`'<a href="<?=$this->get('ticketMenuLink');?>"><?=$this->__("menu.todos") ?></a>'`
to
`'<a href="<?=BASE_URL ?>/tickets/showKanban"><?=$this->__("menu.todos") ?></a>'`
