### ISSUE TITLE
[BUG] Project Overview: wrong linkes

### ISSUE THREAD

**Issue by r0l1** [Leantime/leantime#385]
**Describe the bug**
Clicking on a project in the project overview links to the wrong project. The current selected project does not change.

**To Reproduce**
1. Go to 'All Projects'
2. Click on a project which is not currently the active one
3. The project selection in the left sidebar does not change

**Leantime Version**
2.1.4

**Server**
Docker Installation.

**Comment by marcelfolaron** [comment]
Can't reproduce in 2.1.6.
Please update and try again. Thank you

**Comment by r0l1** [comment]
Could you please tag the 2.1.6 docker release? I don't want to go to latest, due to stability reasons.

**Comment by marcelfolaron** [comment]
Please check with the latest 2.1.7 tag

**Comment by r0l1** [comment]
Thanks! This is fixed in 2.1.7 :)
