### ISSUE TITLE
[BUG] Deleted Task still visible in calendar

### ISSUE THREAD

**Issue by r0l1** [Leantime/leantime#386]
**Describe the bug**
Deleted TODOs are still visible in the calendar. Clicking on them links to a 404 page.

**To Reproduce**
1. Create TODO and set the due date.
2. Go to 'My Calendar'
3. Verify that the TODO is visible
4. Delete the TODO
5. Recheck the calendar 

**Leantime Version**
2.1.4

**Server**
Docker Installation

**Comment by marcelfolaron** [comment]
I wasn't able to reproduce this issue with 2.1.6
Is it possible this is a local cache?

**Comment by r0l1** [comment]
I cleared the cache and also tested against another browser (chromium). Let me test against the latest release.

**Comment by r0l1** [comment]
Seams to be fixed in 2.1.7. However I still have an invalid entry in my calendar overview. Could be an old database entry caused by a bug in the the older version... I'll close this for now.
