### ISSUE TITLE
[FEATURE] Email password reset link instead of plain text passwords to new users

### ISSUE THREAD

**Issue by M-Miller-42** [Leantime/leantime#387]
I think the current account creation process is more complicated than it needs to be and could be safer. Right now I have to ask everyone in my team for their mail address and fill out the user creation form. This includes creating a password for them. Then I have to ask them to login reset their password themselves. The worst part is that I have no guarantee, that they actually reset it. They might keep the password that leantime sent them in plaintext. I don't want to see leantime on [plaintextoffenders.com](https://plaintextoffenders.com/), so I am suggesting this fix:

Don't make the password field required in the create user form. If its empty, create an account with a randomly created password, that is never sent to anyone. Then email only this link to new users: https://leantimeURL.com/resetPassword
The new user then requests the PW reset and chooses a new password of their choice.

This has the following advantages:
 - no more plain text PWs in emails
 - users have to choose their own PW
 - only the email field has to be filled out in order to create new users
 
Looks like this fix only requires a small change [here](https://github.com/Leantime/leantime/blob/24f46cc2b46c8d440410096e47922e9715f4da9c/src/domain/users/controllers/class.newUser.php#L65).
Thank you for reading

**Comment by marcelfolaron** [comment]
I think this is a great idea! 
Let me get this into this week's release.

**Comment by grehund** [comment]
Is there any update on the progress of this?

**Comment by marcelfolaron** [comment]
This is now complete and in 2.3.3.
