### ISSUE TITLE
[BUG] Some Dates are set to 2020 instead of 2021 and are not changeable in Dashboard

### ISSUE THREAD

**Issue by steinhmor** [Leantime/leantime#388]
I noticed a strange behaviour of Leantime. It seems like some duedates are automaticly changed from 2021 to 2020. I'm sure that I set the correct date but I often notice that there are tasks that have a date in 2020 (the rest of the date is correct, just the year is wrong...).
When I try to change the date at the dashboard by clicking on it and entering the correct year with my keyboard I get the notification (after I pressed "enter") that the change was excepted. But when I reload the page nothing has changed. I can only change the date by clicking on the tast, editing the date and save it.

**Expected behavior**
Dates should be saved correctly and should be changable from the dashboard.

**Leantime Version**
2.1.7

**Comment by steinhmor** [comment]
OK, now it is prooven for me :-) It happend again...
I changed the date for some tasks in the dashboard-view. The pop-up-calendar showd me the correct year (2021) - I remeber this because "today" was highlightet. I selected a date aprox. 2 weeks later and the task was saved. after a while I reloaded the dashboard-page and noticed the bug.

**Comment by marcelfolaron** [comment]
Ha, found it. MomentJs is doing something odd here. Changing the YY in the language file to YYYY fixes it. 
Create a PR that fixes the issue. Very bizarre

**Comment by steinhmor** [comment]
Great! I realy like the feature to reschedul tasks from the dashboard easily. Thanks for the quick fix 😃

**Comment by steinhmor** [comment]
BTW: in the german lang-setting the date-picker shows Sunday as the first day of the week but in the settings of the lang-file it is set to Monday. Maybe this is also a bug in the date-picker?

**Comment by j26w** [comment]
This is happening for me too. Took me ages to figure out why my to-dos were not showing on the calendar, and finally realized they were set to 2020. Even if I manually type in "2021" in the Dashboard date quick-change, it will revert to 2020. I have to go into the task details and change the due date in there.

> Ha, found it. MomentJs is doing something odd here. Changing the YY in the language file for momentJSdate to YYYY fixes it.
> Create a PR that fixes the issue. Very bizarre

Thanks for the heads up. I've made this change and all is working now.
