### ISSUE TITLE
[BUG] Error 500 after login (fresh install) : PHP 8

### ISSUE THREAD

**Issue by NickkoG** [Leantime/leantime#391]
**Describe the bug**
After a fresh install by FTP, following the installation guide, I try to login and get an error 500, no error on my hosting log but I see an error in the /ressources/logs/error.log file.

**To Reproduce**
1. Go to "hostname"
2. type your credential and click on the login button
3. See error

**Expected behavior**
I expect to be logged in.

**Leantime Version**
2.1.7

**Server**
OVH shared hosting, performance 1

**PHP / MySQL Version**
PHP 8

**Additional context**
Same behavior in Edge (lastest chromium version) and Vivaldi (lastest version)
Error log : 
```
[15-Feb-2021 07:14:53 America/Los_Angeles] PHP Notice:  spl_autoload_register(): Argument #2 ($do_throw) has been ignored, spl_autoload_register() will always throw in [HIDDEN]/src/core/class.autoload.php on line 10
[15-Feb-2021 07:14:53 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: PDOStatement::setFetchMode(): Argument #2 must be a valid class in [HIDDEN]/src/domain/reports/repositories/class.reports.php:169
Stack trace:
#0 /home/usabilit/projets/src/domain/reports/repositories/class.reports.php(169): PDOStatement->setFetchMode(8, 'leantime\\domain...')
#1 /home/usabilit/projets/src/domain/reports/services/class.reports.php(33): leantime\domain\repositories\reports->checkLastReportEntries('3')
#2 /home/usabilit/projets/src/domain/dashboard/controllers/class.show.php(35): leantime\domain\services\reports->dailyIngestion()
#3 /home/usabilit/projets/src/core/class.frontcontroller.php(148): leantime\domain\controllers\show->__construct()
#4 /home/usabilit/projets/src/core/class.frontcontroller.php(107): leantime\core\frontcontroller->executeAction('dashboard.show')
#5 /home/usabilit/projets/src/core/class.application.php(91): leantime\core\frontcontroller->run()
#6 /home/usabilit/projets/public/index.php(41): leantime\core\application->start()
#7 {main}
  thrown in /home/usabilit/projets/src/domain/reports/repositories/class.reports.php on line 169
```

**Comment by marcelfolaron** [comment]
Thanks for submitting. This is a PHP 8 related issue that we have not resolved yet. 
I am working on PHP 8 support in the next few weeks. In the meantime please use PHP 7.X

**Comment by NickkoG** [comment]
Thanks for the workaround. I will also try your fix and let you know how it works on my hosting.

**Comment by NickkoG** [comment]
I have modified classe.autolod.php but I don't see the two line to delete in my class.roadmap.php (I'm sure to edit the right file). 
And finaly that don't work. 

I rolled out to PHP 7.4

**Comment by NickkoG** [comment]
I always get an error 500, but now, the error.log file remains empty.
