### ISSUE TITLE
[BUG] moving ticket from one project to another

### ISSUE THREAD

**Issue by anyi797** [Leantime/leantime#395]
**Describe the bug**
using the url of a task of sprint planning for a project B when we are on sprint planning for a project A. the application add the task to the project A and remove it to project B

**To Reproduce**
1. Go to the sprint planning A
2. Change the URL with the task B1 of project B 
3. See all description of the task B1 appear in sprint planning A
4. Save the task
5. the task was put on backlog of project A and removed of project B

**Expected behavior**
change the URL switch sprint planning A to sprint planning B

**Leantime Version**
2.1.4

**Server**
Apache

**Comment by marcelfolaron** [comment]
Hey, that bug was fixed as of 2.1.7. Closing this.
