### ISSUE TITLE
[FEATURE] Priority

### ISSUE THREAD

**Issue by modaresimr** [Leantime/leantime#396]
Adding priority to the tasks.
It means we can see the priority of task easily in the views similar to the effort level (XS, S, M, L, XL)

**Comment by andyg2** [comment]
This commit in a recent fork and the following commit implement priority.
https://github.com/droidsolutions/leantime/commit/fed78ccef01403dcdf31d7e4233d786f5882911e

**Comment by zoell** [comment]
@marcelfolaron wondering if there are plans to merge this feature from @andyg2?

**Comment by marcelfolaron** [comment]
Hi All. Thanks @andyg2 Can you create a pull request? Happy to merge that feature

**Comment by zoell** [comment]
Thanks for this! @marcelfolaron wondering if we can expect a release with this?

**Comment by marcelfolaron** [comment]
Yes, I'll put a release out this upcoming weekend.

Sincerely,
Marcel
