### ISSUE TITLE
Going from to-do table view to kanban view generates permanent project 404 not found page

### ISSUE THREAD

**Issue by ghost** [Leantime/leantime#405]
1) Navigate to to-dos page under a project (/tickets/showKanban)
2) Click "Kanban view" and change to "Table view"
3) Click "Table view" and change back to "Kanban view" 

That kanban view never loads. The page is "not found" (/tickets/showKanban). Now every visit to the base URL and clicking on To-dos always generates a not found page. Only creating a new project will reset this cycle where I can replicate this again.

**Comment by marcelfolaron** [comment]
I assume you are in a subfolder installation?
What version of Leantime are you using. We fixed a few of those issues in the latest version

**Comment by trinhpc** [comment]
@marcelfolaron  i using 2.1.7

In Kanban view, i not shot Due. Can you help me?

**Comment by snowcatjoey** [comment]
v2.1.9
When I in a subfolder, same question.
The URL become domain/leantime/**leantime/**tickets/showKanban 

subfolder name become twice
