### ISSUE TITLE
Inserting templates in to dos

### ISSUE THREAD

**Issue by joelbong** [Leantime/leantime#407]
First off all, I appreciate the efforts done in this projects. It really fits my needs.

**Describe the bug**
I cannot use templates in to-dos or more concrertly, I have no idea where to create templates.

**To Reproduce**
1. Go to To-Dos
2. add a To-Do
3. In description we should able to insert a template
4. we get a text --> 'no templates defined'

**Expected behavior**
Either an explanation where to add templates or pre-defined templates.

**Leantime Version**
2.1.7

**Server**
Apache

**PHP / MySQL Version**
phpp 7.2

**Additional context**
I'm not sure if this should be a bug or a feature.

**Comment by patchworquill** [comment]
+1 would love to see this implemented properly. Seems like a bug, within a feature that is partially implemented.

**Comment by stevenb9** [comment]
Yes please this is exactly what im looking for
