### ISSUE TITLE
[FEATURE] Show Milestones in Portfolio in order of due date

### ISSUE THREAD

**Issue by kilianmuster** [Leantime/leantime#410]
**Is your feature request related to a problem? Please describe.**
Currently the milestones shown on the Portfolio page are shown in alphabetical order

**Describe the solution you'd like**
Since milestones are based on to-from dates, it would make much more sense to order them by date

**Additional context**
<img width="525" alt="Screen Shot 2021-03-31 at 10 39 22" src="https://user-images.githubusercontent.com/11626441/113078168-86e02a00-920d-11eb-8a1b-9de6cdc0d848.png">

**Comment by marcelfolaron** [comment]
Agreed. I will included that in the next version
