### ISSUE TITLE
Auto archive tasks

### ISSUE THREAD

**Issue by GhaziTriki** [Leantime/leantime#411]
After few months of usage the UI becomes messy with a lot of tasks done.
It would be nice to add an auto-archive task after 15 days as example.

**Comment by marcelfolaron** [comment]
I like that idea. We don't have a good scheduler in Leantime yet, so this work might take a little longer

**Comment by marcelfolaron** [comment]
As of 3.2.0 we are supporting Zapier integrations. This would allow a flow like this. The alpha app is available here https://zapier.com/developer/public-invite/207240/cac6ec7a911bd5fa7924f38230d58d2f/
