### ISSUE TITLE
Some problems with saving user passwords from /users/editUser/

### ISSUE THREAD

**Issue by yuramak** [Leantime/leantime#412]
Some problems with saving user passwords. After editing a user and saving, the password is reset to blank. Maybe we need to check for empty **password** and **password2** fields.

**Comment by marcelfolaron** [comment]
Hi,

This behavior is by design. The password is still saved in the database it
just doesn't show in the frontend. We store passwords as hash + salt so
showing them in the form wouldn't even work.

The point is that you can change the password via the form. I could add
some messaging to make that clear.

**Comment by yuramak** [comment]
Hi,
In function public function editUser(array $values, $id) 
src\domain\users\repositories\class.users.php Line 258

We see the code:
```
             $query = "UPDATE `zp_user` SET
				firstname = :firstname,
				lastname = :lastname,
				username = :username,
				phone = :phone,
				status = :status,
				role = :role,
				hours = :hours,
				wage = :wage,
				clientId = :clientId,
				**password = :password**
				
			 WHERE id = :id LIMIT 1";
```

:password my be blank, because in src\domain\users\controllers\class.editUser.php Line 58:

```
$values = array(
'firstname' => ($_POST['firstname']),
'lastname' => ($_POST['lastname']),
'user' => ($_POST['user']),
'phone' => ($_POST['phone']),
'status' => ($_POST['status']),
'role' => ($_POST['role']),
'hours' => ($_POST['hours']),
'wage' => ($_POST['wage']),
'clientId' => ($_POST['client']),
**'password' => (password_hash($_POST['password'], PASSWORD_DEFAULT)),**
);
```
The password variable in the array always changes to a new value when the user settings are updated = $_POST['password'].

If the password field is empty, then the password field in the database will eventually reset to an empty password.

**Comment by marcelfolaron** [comment]
Let me check the flow again. The password field is never submitted in the
form, so $_POST['password'] shouldn't be set at all.

Will get back to you

**Comment by yuramak** [comment]
Maybe my fixes can help you understand the problem?

        public function editUser(array $values, $id)
        {
	    $flag_no_pass = password_verify('', $values['password']);

	    if ($flag_no_pass==false)
	    {
             $query = "UPDATE `zp_user` SET
				firstname = :firstname,
				lastname = :lastname,
				username = :username,
				phone = :phone,
				status = :status,
				role = :role,
				hours = :hours,
				wage = :wage,
				clientId = :clientId,
				password = :password
				
			 WHERE id = :id LIMIT 1";

            $stmn = $this->db->database->prepare($query);
            $stmn->bindValue(':firstname', $values['firstname'], PDO::PARAM_STR);
            $stmn->bindValue(':lastname', $values['lastname'], PDO::PARAM_STR);
            $stmn->bindValue(':username', $values['user'], PDO::PARAM_STR);
            $stmn->bindValue(':phone', $values['phone'], PDO::PARAM_STR);
            $stmn->bindValue(':status', $values['status'], PDO::PARAM_STR);
            $stmn->bindValue(':role', $values['role'], PDO::PARAM_STR);
            $stmn->bindValue(':hours', $values['hours'], PDO::PARAM_STR);
            $stmn->bindValue(':wage', $values['wage'], PDO::PARAM_STR);
            $stmn->bindValue(':clientId', $values['clientId'], PDO::PARAM_STR);
            $stmn->bindValue(':id', $id, PDO::PARAM_STR);
            $stmn->bindValue(':password', $values['password'], PDO::PARAM_STR);

            $stmn->execute();
            $stmn->closeCursor();
           }
	   else
           {
            $query = "UPDATE `zp_user` SET
				firstname = :firstname,
				lastname = :lastname,
				username = :username,
				phone = :phone,
				status = :status,
				role = :role,
				hours = :hours,
				wage = :wage,
				clientId = :clientId
				
			 WHERE id = :id LIMIT 1";

            $stmn = $this->db->database->prepare($query);
            $stmn->bindValue(':firstname', $values['firstname'], PDO::PARAM_STR);
            $stmn->bindValue(':lastname', $values['lastname'], PDO::PARAM_STR);
            $stmn->bindValue(':username', $values['user'], PDO::PARAM_STR);
            $stmn->bindValue(':phone', $values['phone'], PDO::PARAM_STR);
            $stmn->bindValue(':status', $values['status'], PDO::PARAM_STR);
            $stmn->bindValue(':role', $values['role'], PDO::PARAM_STR);
            $stmn->bindValue(':hours', $values['hours'], PDO::PARAM_STR);
            $stmn->bindValue(':wage', $values['wage'], PDO::PARAM_STR);
            $stmn->bindValue(':clientId', $values['clientId'], PDO::PARAM_STR);
            $stmn->bindValue(':id', $id, PDO::PARAM_STR);
//			$stmn->bindValue(':password', $values['password'], PDO::PARAM_STR);

            $stmn->execute();
            $stmn->closeCursor();

	   }
        }

**Comment by CdiegoBB** [comment]
I made the same thing to ask if the password it's empty please don't save it, but don't enter into the method EditUser even i readed in the code that the constructor call it, any help?

> Maybe my fixes can help you understand the problem?
> 
> ```
>     public function editUser(array $values, $id)
>     {
>     $flag_no_pass = password_verify('', $values['password']);
> 
>     if ($flag_no_pass==false)
>     {
>          $query = "UPDATE `zp_user` SET
> 			firstname = :firstname,
> 			lastname = :lastname,
> 			username = :username,
> 			phone = :phone,
> 			status = :status,
> 			role = :role,
> 			hours = :hours,
> 			wage = :wage,
> 			clientId = :clientId,
> 			password = :password
> 			
> 		 WHERE id = :id LIMIT 1";
> 
>         $stmn = $this->db->database->prepare($query);
>         $stmn->bindValue(':firstname', $values['firstname'], PDO::PARAM_STR);
>         $stmn->bindValue(':lastname', $values['lastname'], PDO::PARAM_STR);
>         $stmn->bindValue(':username', $values['user'], PDO::PARAM_STR);
>         $stmn->bindValue(':phone', $values['phone'], PDO::PARAM_STR);
>         $stmn->bindValue(':status', $values['status'], PDO::PARAM_STR);
>         $stmn->bindValue(':role', $values['role'], PDO::PARAM_STR);
>         $stmn->bindValue(':hours', $values['hours'], PDO::PARAM_STR);
>         $stmn->bindValue(':wage', $values['wage'], PDO::PARAM_STR);
>         $stmn->bindValue(':clientId', $values['clientId'], PDO::PARAM_STR);
>         $stmn->bindValue(':id', $id, PDO::PARAM_STR);
>         $stmn->bindValue(':password', $values['password'], PDO::PARAM_STR);
> 
>         $stmn->execute();
>         $stmn->closeCursor();
>        }
>    else
>        {
>         $query = "UPDATE `zp_user` SET
> 			firstname = :firstname,
> 			lastname = :lastname,
> 			username = :username,
> 			phone = :phone,
> 			status = :status,
> 			role = :role,
> 			hours = :hours,
> 			wage = :wage,
> 			clientId = :clientId
> 			
> 		 WHERE id = :id LIMIT 1";
> 
>         $stmn = $this->db->database->prepare($query);
>         $stmn->bindValue(':firstname', $values['firstname'], PDO::PARAM_STR);
>         $stmn->bindValue(':lastname', $values['lastname'], PDO::PARAM_STR);
>         $stmn->bindValue(':username', $values['user'], PDO::PARAM_STR);
>         $stmn->bindValue(':phone', $values['phone'], PDO::PARAM_STR);
>         $stmn->bindValue(':status', $values['status'], PDO::PARAM_STR);
>         $stmn->bindValue(':role', $values['role'], PDO::PARAM_STR);
>         $stmn->bindValue(':hours', $values['hours'], PDO::PARAM_STR);
>         $stmn->bindValue(':wage', $values['wage'], PDO::PARAM_STR);
>         $stmn->bindValue(':clientId', $values['clientId'], PDO::PARAM_STR);
>         $stmn->bindValue(':id', $id, PDO::PARAM_STR);
> ```
> 
> // $stmn->bindValue(':password', $values['password'], PDO::PARAM_STR);
> 
> ```
>         $stmn->execute();
>         $stmn->closeCursor();
> 
>    }
>     }
> ```

**Comment by yuramak** [comment]
> I made the same thing to ask if the password it's empty please don't save it, but don't enter into the method EditUser even i readed in the code that the constructor call it, any help?
> 
> > Maybe my fixes can help you understand the problem?
> > ```

Hmm. I checked my code - it works. Perhaps you didn't make the change correctly?
Can you copy your changes here?

**Comment by CdiegoBB** [comment]
@yuramak  I paste your code I know that will work but i don't know why in the server use the php code before my change? i need to run a command or something to deploy my changes?

**Comment by CdiegoBB** [comment]
@yuramak  i see an error in your code when the class controller/editUser call repository/users the first class send the value password with hash value then even it's empty this will have a value in User.php because it's encrypted, then i put in Edituser.php a validation if the pass it's empty set Array with '' if not then hash the value I will paste the code hier :

`							$password = empty($_POST['password']) ? '' : password_hash($_POST['password'], PASSWORD_DEFAULT);

							$values = array(

								'firstname' => ($_POST['firstname']),

								'lastname' => ($_POST['lastname']),

								'user' => ($_POST['user']),

								'phone' => ($_POST['phone']),

								'status' => ($_POST['status']),

								'role' => ($_POST['role']),

								'hours' => ($_POST['hours']),

								'wage' => ($_POST['wage']),

								'clientId' => ($_POST['client']),

								'password' => ($password),

							);`

after line 56

**Comment by yuramak** [comment]
Please show your editUser function code in full. I don't really understand what you ended up changing and where. In my code or in the original code?

**Comment by CdiegoBB** [comment]
EditUsers go into the folders users/controller and Users go into users/repository

[EditUser.txt](https://github.com/Leantime/leantime/files/6939513/EditUser.txt)
[Users.txt](https://github.com/Leantime/leantime/files/6939516/Users.txt)
