### ISSUE TITLE
[BUG] Undesirable password change when changing user parameters

### ISSUE THREAD

**Issue by aarchijs** [Leantime/leantime#416]
**Describe the bug**
Editing user parameters like name, role, status, client in ['administration>user management>(user name)'] results in password change even if that is not the intention. Workaround is to type the password in the password fields when saving these parameters.

**To Reproduce**
1. Go to 'administration>user management>(user name)'
2. Change any parameter for user and leave password field blank
3. Press save
4. Edited user does not have password anymore 

**Expected behavior**
Password should not be changed

**Leantime Version**
v2.1.7

**Server**
Apache

**PHP / MySQL Version**
PHP 7.4 and Mysql 8.0.23

**Comment by aarchijs** [comment]
My guess it is the same issue as #412
Password change should not happen if that is not the goal.

**Comment by skye0402** [comment]
Thanks, I was wondering why I couldn't login anymore. Blank password enabled me to get back in and to set a password again.
