### ISSUE TITLE
[FEATURE] Link to specific items for a specific project

### ISSUE THREAD

**Issue by zoell** [Leantime/leantime#418]
I realized that sometimes I want to link to a specific project's todos or milestone etc but it seems it is not possible.

When I browse to an URL like this, it should show the todos of that specific project without the need to change project manualy:
https://leantimehost/project/project_name_or_id_or_whaterver/tickets/showAll 

Additionally this should also work for milestone, timesheets, etc:
https://leantimehost/project/project_name_or_id_or_whaterver/tickets/roadmap
https://leantimehost/project/project_name_or_id_or_whaterver/retrospectives/showBoards
etc

Would this be possible to achieve?

**Comment by marcelfolaron** [comment]
Leantime does that already. It is not displayed in the link but it will switch projects based on the todo id (or project id) 
So sending a link like: tickets/showTicket/16 will switch to the correct project
Please let me know if that doesn't work

**Comment by zoell** [comment]
Hi @marcelfolaron, but my question was not that if I can link to a specific ticket. (which is working but it actually won't switch to the project).

My question was to be able to link to a specific project's ticket list, roadmap, etc.

My version is 2.1.4

**Comment by marcelfolaron** [comment]
This was added a bit ago. Search queries are now available via url and there is a copy url link on the project dashboard
