### ISSUE TITLE
[BUG] Non Unicode font

### ISSUE THREAD

**Issue by w1naenator** [Leantime/leantime#422]
Please use full range Unicode font.
![image](https://user-images.githubusercontent.com/2381733/115712002-e8169b80-a37c-11eb-89f5-b3741c053e0a.png)

Data from Chrome DevTools: 
RobotoLight, "Helvetica Neue", Helvetica, sans-serif
![image](https://user-images.githubusercontent.com/2381733/115713598-ddf59c80-a37e-11eb-91e3-a13aade086d0.png)

**Comment by marcelfolaron** [comment]
Hey, can you past some of the not supported unicode characters here so I can test better?

**Comment by w1naenator** [comment]
Latvian language uses also Āčēģīķļņšūž together with ASCII table.

**Comment by marcelfolaron** [comment]
Which version are you using?
This is what I see changing the project name:

[image: image.png]

**Comment by w1naenator** [comment]
I using version 2.1.7. Problem appears only titles. There unsupported
unicode characters replaced with another font characters. Please check
image.
