### ISSUE TITLE
[BUG] calendar events not save in right date

### ISSUE THREAD

**Issue by krubenrc** [Leantime/leantime#425]
Hello, i detect a bug, i have the last version installed (2.1.7).

When you add a new event to the calendar, with spanish language (although I think it gives error in others as well)
the date saved change the format, and change the month place for the day place.

Example:

I select 10/05/2021 with format d/m/Y

![image](https://user-images.githubusercontent.com/33639842/117441532-cd742300-af35-11eb-999a-56ee6623c041.png)

When it saved in database, this date saved as: Y-d-m
![image](https://user-images.githubusercontent.com/33639842/117441544-d36a0400-af35-11eb-89b3-2e29e26318f8.png)

But in the interface web, it is represented as: Y-m-d, and the date appears in a wrong place.

(Septiembre = September)
And in the calendar, show the event in the month 10, when 10 was the day.
![image](https://user-images.githubusercontent.com/33639842/117441807-378cc800-af36-11eb-9c79-066ae80b5511.png)

I can resolv this, change strtime for  \DateTime::createFromFormat in class.editEvent.php and class.addEvent.php

Example:
this:
$dateFrom = date('Y-m-d H:i:01', strtotime($_POST['dateFrom']." ".$_POST['timeFrom']));

for:
$dateFrom = date('Y-m-d H:i:01', \DateTime::createFromFormat('d/m/Y h:i A', $_POST['dateFrom']." ".$_POST['timeFrom'])->getTimestamp());

And it will can be better, if the format will get from language files, because, 'd/m/Y h:i A' is in the language file.

**Comment by marcelfolaron** [comment]
Good catch. I found the bug in addEvent. 
Fix will be included in the next release.
