### ISSUE TITLE
[BUG] Time tracking information is lost (when user gets logged out)

### ISSUE THREAD

**Issue by freder** [Leantime/leantime#426]
**Describe the bug**
when doing time tracking, it can happen that the user gets logged out, in which case the time information is lost.

**To Reproduce**
1. log in 
2. start time tracking
3. work for a couple of hours
4. come back to stop time tracking
5. observe that you got logged out
6. log in again (+ observe that there is no running timer anymore)

**Expected behavior**
- whatever the current inactivity timeout for logging out users is: it's way too short. make it longer.
- or find a way to persist information about a running a timer between sessions.

**Leantime Version**
- 2.1.7
- https://github.com/Leantime/docker-leantime

**Comment by marcelfolaron** [comment]
The time logging is preserved in the db meaning there shouldn't be a reason why the timer stopped. 
Do you see any errors in resources/error.logs? 

I tried multiple times and can't reproduce this issue.

**Comment by gloriafolaron** [comment]
@freder  I'm organizing our current open bug reports and I just wanted to follow up on whether this is still an issue for you as we were unable to reproduce it at that time.
