### ISSUE TITLE
Can’t upload files

### ISSUE THREAD

**Issue by trinhpc** [Leantime/leantime#428]
I install Leantime 2.1.7 with LAMP

PHP 7.3
Mariadb 10.3

I set permissons

chown apache:apache /var/www/userfiles/
chown apache:apache /var/www/html/userfiles/
chmod 777 on both folder

Now, I can't upload files

**Comment by trinhpc** [comment]
@marcelfolaron can you help me ?

**Comment by trinhpc** [comment]
![ảnh](https://user-images.githubusercontent.com/85401057/120921158-93d93800-c6ec-11eb-995e-a286c32fc0ef.png)

But i can't up load files

![ảnh](https://user-images.githubusercontent.com/85401057/120921203-c7b45d80-c6ec-11eb-9372-8526a3641fab.png)

And can't change password

**Comment by trinhpc** [comment]
I upload file susessful

But i can't config smtp

**Comment by marcelfolaron** [comment]
Use smtp should be set to 1 instead of "yes".
