### ISSUE TITLE
[FEATURE] Add tags as filters in the To-Dos view

### ISSUE THREAD

**Issue by Razique** [Leantime/leantime#431]
First of all, thanks for such an excellent project :) 
I feel like tags, albeit really useful for categorizing stories and tasks, don't currently have any value given that they cannot be used as filters.
I suggest adding one of the following in the To-Dos View:
- A new "Tags" column, which would allow sorting by tag
- A new "Tags" as filter option when clicking "Filters" (in the "Type" dropdown)
- A new Group By -> Tags option

Moreover, the application currently does not list existing tags when assigning them in the new to-do page. It would be nice to list existing tags so that it is possible to quickly reuse existing one instead of typing them.

**Comment by labarilem** [comment]
Saw a similar feature request here: https://github.com/Leantime/leantime/issues/399.

I'm also interested in this feature. Another option might be:
- When clicking on a tag, the boards automatically applies a filter by that tag to the To-Dos

@marcelfolaron would you be interested in a PR for this?
