### ISSUE TITLE
[BUG] Install Page 404 Not Found

### ISSUE THREAD

**Issue by ghost** [Leantime/leantime#436]
**Describe the bug**
I did a fresh install of LeanTime on my Ubuntu 20.04 VM and pointed the apache webroot to _/public_ and also ensured that the **apache rewrite module** was enabled.  I still get the 404 error when hitting http://serverip/install

**To Reproduce**

1. Set Document Root
/etc/apache2/sites-enabled/000-default.conf - Line 12: DocumentRoot _/var/www/html/public_

2. sudo a2enmod rewrite

3. sudo systemctl restart apache2

4. Navigate to http://serverip/install

5. See error

**Expected behavior**
Go through the setup/install process

**Leantime Version**
2.1.7 (latest)

**Server**
Apache

**PHP / MySQL Version**
MariaDB - latest
PHP - 7.4

**Comment by b90g** [comment]
do you have tried

```
<Directory /var/www/>
        AllowOverride All
</Directory>
```

?

**Comment by DMTGMBH** [comment]
Got the same problem and in my case it was caused by a special character in the database password  > check your php error log to clearify that the error is not caused by modifications of your configuration.php

**Comment by edwardsj9090** [comment]
Team,

Thank you for the suggestions.  I apologize for the late response.  I will give these a try and let you know.

**Comment by diviatrix** [comment]
Still exist all the time. Cant install.

**Comment by thewriteway** [comment]
Did you add the following code to your nginx config:
location / {
rewrite ^/?$ /index.php?act=dashboard.show;
rewrite ^/([^/\.]+)/?$ /index.php?act=$1;
rewrite ^/([^/\.]+)/([^/\.]+)/?$ /index.php?act=$1.$2;
rewrite ^/([^/\.]+)/([^/\.]+)/([^/\.]+)/?$ /index.php?act=$1.$2&id=$3;
}
