### ISSUE TITLE
Trello Json Import 

### ISSUE THREAD

**Issue by Bigben83** [Leantime/leantime#442]
Hello
I am just wondering if there is any plan to include a Trello Json import into Leantime. 
I couldn't see any roadmap to see if there was something planned.

It would be great if we could import Trello Boards into Leantime via the Json export that you can easily get from Trello.

**Comment by marcelfolaron** [comment]
Thanks, I have been wanting to create an importer for a while. 
How would you like to see the import work? I assume one would want to match leantime columns with the trello columns?
One trello board = 1 project in leantime?

**Comment by Bigben83** [comment]
Hi Marcel,
Yes this sounds perfect :thumbsup:

**Comment by marcelfolaron** [comment]
As of 3.2.0 we are supporting Zapier integrations. This would allow a flow like this. The alpha app is available here https://zapier.com/developer/public-invite/207240/cac6ec7a911bd5fa7924f38230d58d2f/
