### ISSUE TITLE
[BUG]: Can not login (always a redirect to the base url)

### ISSUE THREAD

**Issue by stevleibelt** [Leantime/leantime#451]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
I am using [uberspace](https://manual.uberspace.de/en/web-documentroot.html) as a hoster.
Because of that, I have to set the `RewriteBase` in the delivered `public/.htaccess` to `RewriteBase /`.
Calling `https://foo.bar.ru/install` was working fine. I get the `notification.database_exists`.
But whenever I want to login with my user, I am redirected to `https://foo.bar.ru`.

**To Reproduce**
1. Follow your installation instruction
2. Open the index page
3. Try to login with the user created in the installation routine
4. See that you only get redirected to the index page without any error

**Expected behavior**
Either get a notice "username and password are wrong" or get redirected to the logged in page.

**Leantime Version**
[v2.1.8](https://github.com/Leantime/leantime/tree/v2.1.8)

**Server**
Apache

**PHP / MySQL Version**
PHP 7.4.22 (cli) (built: Jul 27 2021 18:08:31) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.22, Copyright (c), by Zend Technologies

mysql  Ver 15.1 Distrib 10.3.26-MariaDB, for Linux (x86_64) using readline 5.1

**Additional context**
Maybe [uberspace](https://manual.uberspace.de/en/web-documentroot.html) is behaving differently.
My apache error or php error logs are free from any error.
Is there a way to run leantime in debug mode?

**Configuration**

Following the lines I've changed in the `configuration.php`.
Done by `diff configuration.php configuration.sample.php` and removed the sensible parts.

```
7c7
<   public $sitename = "foobar project management powered by leantime"; //Name of your site, can be changed later
---
>   public $sitename = "Leantime"; //Name of your site, can be changed later
11c11
<   public $appUrl = "https://foo.bar.ru"; //Base URL, trailing slash not needed
---
>   public $appUrl = ""; //Base URL, trailing slash not needed
15,17c15,17
<   public $dbUser="user"; //Database username
<   public $dbPassword="password"; //Database password
<   public $dbDatabase="database_leantime"; //Database name
---
>   public $dbUser=""; //Database username
>   public $dbPassword=""; //Database password
>   public $dbDatabase=""; //Database name
38,39c38,39
<   public $email = "leantime@foo.bar.ru"; //Return email address
<   public $useSMTP = true; //Use SMTP? If set to false, the default php mail() function will be used
---
>   public $email = ""; //Return email address
>   public $useSMTP = false; //Use SMTP? If set to false, the default php mail() function will be used
45c45
<   public $smtpPort = "465"; //Port (usually one of 25, 465, 587, 2526)
---
>   public $smtpPort = ""; //Port (usually one of 25, 465, 587, 2526)
```

I was able to debug it to `core\login::getUserByLogin` and `password_verify($password, $user['password'])` returns a `true`.
Inside the same method mentioned above, also the `$returnValues` are filled with expected values.
Also `setcookie ...`returns a `true`. The value of `sid` in my cookie stays the same.

**Comment by marcelfolaron** [comment]
Seems there are multiple things going on here:

Are you trying to run leantime in a subfolder installation?
If you can't change the document root you will have to run leantime in
foo.bar.ru/leantime
https://docs.leantime.io/#/installation/quick-installation?id=subfolder-installation
Looking at the docs though it seems you shouldn't have any trouble setting
the document root: https://manual.uberspace.de/en/web-documentroot.html

notifications.database_exists indicates that the database has been
installed. Did you go through the installation process and set a password?
Which tables are in your database?

**Comment by stevleibelt** [comment]
Hello @marcelfolaron and thanks for your quick reply.

> Did you go through the installation process and set a password?
yes

> Which tables are in your database?

```
MariaDB [foobar_leantime]> show tables;
+-----------------------------+
| Tables_in_foobar_leantime |
+-----------------------------+
| zp_account                  |
| zp_action_tabs              |
| zp_audit                    |
| zp_calendar                 |
| zp_canvas                   |
| zp_canvas_items             |
| zp_clients                  |
| zp_comment                  |
| zp_dashboard_widgets        |
| zp_file                     |
| zp_gcallinks                |
| zp_lead                     |
| zp_message                  |
| zp_modulerights             |
| zp_note                     |
| zp_projects                 |
| zp_punch_clock              |
| zp_read                     |
| zp_relationuserproject      |
| zp_roles                    |
| zp_settings                 |
| zp_sprints                  |
| zp_stats                    |
| zp_submodulerights          |
| zp_tickethistory            |
| zp_tickets                  |
| zp_timesheets               |
| zp_user                     |
| zp_wiki                     |
| zp_wiki_articles            |
| zp_wiki_categories          |
| zp_wiki_comments            |
+-----------------------------+
```

**Comment by stevleibelt** [comment]
@marcelfolaron 

> If you can't change the document root you will have to run leantime in
foo.bar.ru/leantime

I can change it, all other subdomain projects are running fine when I add the `RewriteBase /` in the `public/.htaccess`.

I was able to debug it to the following point.
`src\core\class.login.php::344`. This line `if(isset($_SESSION['userdata']) === true) ` is evaluated as `false.
The whole `$_SESSION` is empty :-/.

**Comment by marcelfolaron** [comment]
Do you see any errors in resources/error.logs?
I assume sessions are enabled on your host?

can you check that the user your created during the install flow is in
zp_user

Sincerely,
Marcel

**Comment by stevleibelt** [comment]
> Do you see any errors in resources/error.logs?

Sadly no :-(.

> can you check that the user your created during the install flow is in zp_user

Yes, I've validated it. From inside the login class, the password is verified as valid.

> I assume sessions are enabled on your host?

As far as I know yes, at least projects like roundcube and nextcloud are running fine on the same host but different subdomain.

**Comment by stevleibelt** [comment]
The `redirectUrl` is `/`. Is this expected?

**Comment by marcelfolaron** [comment]
Try setting the appUrl in your config file.

**Comment by stevleibelt** [comment]
> Try setting the appUrl in your config file.

The appUrl is already set.

**Comment by stevleibelt** [comment]
Any option where I can enable some debugging setting?

**Comment by GaraQuor** [comment]
Same problem here. Some update ?

**Comment by PieterWaegeman** [comment]
I have the exact issue, on version 2.1.8 (clean install). The issue was also tested on a version 2.1.4 installation (clean) but it could not be reproduced there. I'll be using version 2.1.4 for a while until this bug is resolved.

**Comment by stevleibelt** [comment]
Thank you for the hint @PieterWaegeman, I will give  [2.1.4.](https://github.com/Leantime/leantime/tree/v2.1.4) a try,

**Comment by PieterWaegeman** [comment]
Oh, that seems weird.

My steps were:
- I dropped the tables in the database
- Loaded a new Docker container with v2.1.4, and the needed parameters (DB info, appUrl)
- Went to the /install URL to provision the database

This seems to work in my case for this version, but not for the latest release.

**Comment by PieterWaegeman** [comment]
I recreated the Docker container from v2.1.4 to v2.1.6 today. I did the DB upgrade the software instructed me to do and I got this issue again.

**Comment by stevleibelt** [comment]
I see, I am deploying it on a CentOS machine without podman or the older brother docker.
Thanks for your response.

**Comment by mbollmann** [comment]
I'm having exactly the same issue, also on an Uberspace host.

I did some good old print debugging–or rather `error_log()` debugging–and found the following:
+ the login works just fine: `leantime\core\login->login()` is called and succeeds; but
+ the content of the `$_SESSION` variable doesn't seem to persist, as it's empty when `leantime\core\login->logged_in()` is called;
+ therefore the code immediately logs me out again [on this line](https://github.com/Leantime/leantime/blob/c38085c52c41b60780134d5c3bffea1d9eb4ce0a/src/core/class.login.php#L358).

That's as far as I could get. @marcelfolaron do you have any ideas what the problem here could be? Anything in my PHP configuration maybe? It's been a while since I developed in PHP so I'm not quite sure what could go wrong here.

**Comment by mbollmann** [comment]
Found the cause!

Uberspace sets `session.use_strict_mode=1` on their servers, while default PHP configuration is `session.use_strict_mode=0`. Forcing the setting back to `0` makes Leantime work.

(For Uberspace users: `echo "session.use_strict_mode=0" > ~/etc/.php.d/mycustom.ini ; uberspace tools restart php`)

**Comment by stevleibelt** [comment]
@mbollmann thank you, now I am totally thrilled to give it a try at home :-).

**Comment by EHRETic** [comment]
Hello there 😉

I've the same bug as described, but solution doesn't seems to work for me.

Some details:
- Leantime 2.1.8
- Fresh and dedicated install on AlmaLinux 8 (all patched)
- MariaDB, PHP 8.0x, NGINX ( "production" style, no docker.)
- no sub-folder config
- session.strict_mode to PHP default so 0 (confirmed by PHP info)

Maybe good to know : Install didn't pop out an error, but didn't give any installation ending info either. On login mask. if I enter a wrong password, I get the wrong password error and nothing happens if I enter the right one. It "confirms" the same behavior.

Any hint/help to help me going forward? I'ts my first install and I can't wait to use it (home lab)! 😄

**Comment by EHRETic** [comment]
> Hello there 😉
> 
> I've the same bug as described, but solution doesn't seems to work for me.
> 
> Some details:
> 
> * Leantime 2.1.8
> * Fresh and dedicated install on AlmaLinux 8 (all patched)
> * MariaDB, PHP 8.0x, NGINX ( "production" style, no docker.)
> * no sub-folder config
> * session.strict_mode to PHP default so 0 (confirmed by PHP info)
> 
> Maybe good to know : Install didn't pop out an error, but didn't give any installation ending info either. On login mask. if I enter a wrong password, I get the wrong password error and nothing happens if I enter the right one. It "confirms" the same behavior.
> 
> Any hint/help to help me going forward? I'ts my first install and I can't wait to use it (home lab)! 😄

I've tried with Leantime 2.1.5 and 2.1.0 too: same result... any hint I can follow? Thx 😉

**Comment by EHRETic** [comment]
Well, I activated my troubleshooting mode on and I found out 2 main issues:
- I used PHP 8 in the first place, only PHP 7.X seems to work: saw one post in the community forum that gave me the hint and I tried.
- I had permission issue within php folder, user was still apache but I use nginx... I saw an permission error in the log

![image](https://user-images.githubusercontent.com/28634810/136019946-8cceb4d6-6a21-43f8-8823-575c5c5b8256.png)

I did try reverting a snapshot to do the permissions fix on my PHP 8 installation but it gave an ERROR 500 page when I tried to login so this confirmed me PHP 8 doesn't seems to be supported. If this is the case it should be highlighted in the documentation IMHO 😉

If this info can help anybody, I'll be happy.

**Comment by EHRETic** [comment]
> * I had permission issue within php folder, user was still apache but I use nginx... I saw a permission error in the logs.

This permission issue came back after an update (I use auto update). 
Does somebody knows if we can fix it "forever"? 😉

**Comment by marcelfolaron** [comment]
Hi all,

I am in the process of fixing some PHP8 issues, as of right now I suggest
to use PHP7. The next release will include full pop 8 support

The permission issue you mentioned doesn't seem to be related to Leantime
though. The installer doesn't touch those folders.

**Comment by marcelfolaron** [comment]
Ah got it. Yeah it seems weird that the permissions don't align. You can
change the user apache is running under in the apache configuration.
Httpdconf I believe

**Comment by silent-tan** [comment]
i use orb to run `docker compose up -d`, always redirect to login page : (
