### ISSUE TITLE
To whomever suffering installing leantime on IIS 

### ISSUE THREAD

**Issue by Abdelfatahh** [Leantime/leantime#453]
Hey all! 

I've been struggling installing leanTime on IIS because once I installed it and pointed the root directory to /public I got redirected to /install and I got a 404 page.

I checked the issues here and I saw @marcelfolaron response to someone suggesting to navigate to two different URLs: 
A. http://serverip/
B. https://serverip/index.php?install=true

I tried the first one and it directed me to a 404 page and the second one redirected me to the installation page! 
and Marcel's response was stating that there's still a problem in the mod_rewrite permissions. 

So I started working around this case and I installed [URL rewrite](https://www.iis.net/downloads/microsoft/url-rewrite) for IIS.
Then restarted IIS and opened the site in sites tab, IIS -> URL Rewrite.

Once you open URL Rewrite, head to Actions tab on the right side. and click on `Import Rules`  then click on the 3 dots that refers to file upload and upload the .htaccess file that exists in public folder. 

Now when you navigate to /install there will be no problems and it will work with literally not a single problem!

**Comment by marcelfolaron** [comment]
Thank you. I will add that to the documentation!
