### ISSUE TITLE
[BUG] HTTP Error 500 when trying to edit a user

### ISSUE THREAD

**Issue by gianlucaromito** [Leantime/leantime#457]
**Describe the bug**
Installed the docker version of leantime. Accessing via reverse proxy. Added the correct LEAN_APP_URL env var.
When trying to edit a user I get This page isn’t working <URL> is currently unable to handle this request.
HTTP ERROR 500

**To Reproduce**
Go to the user management page.
Click on a user.
I get error 500

**Expected behavior**
Open the selected user editing page

**Leantime Version**
2.1.8

**Server**
docker behind nginx proxy manager

**PHP / MySQL Version**
docker version

**Additional context**
In the docker log file nothing is shown about the error.

Thanks to take a look!
Ciao Gianluca

**Comment by DMTGMBH** [comment]
Change line 68 in src/domain/users/controllers/class.editUser.php
from: 'password' = ($row['password']),
to: 'password' => ($row['password']),

This will solve the problem.
Best regards
Jürgen

**Comment by hartigdan** [comment]
fix #454

**Comment by g33k-g1rl** [comment]
This fixed the issue for me as well. :)
