### ISSUE TITLE
[BUG] Todo with PHP comment breaks system

### ISSUE THREAD

**Issue by olenoerby** [Leantime/leantime#462]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Creating a Todo with a comment field including a PHP multi-line comment template breaks the Kanban view styling catastrophically.

**To Reproduce**
1. Open Kanban view to ensure proper function
2. Create a new Todo in any category
3. Insert any title
4. Insert into the comment field the following text, no matter the formatting:
```
/** 
 * PHP 7.4
 * LICENSE: This source file is subject to version 3.01 of the PHP license
 * that is available through the world-wide-web at the following URI:
 * http://www.php.net/license/3_01.txt.  If you did not receive a copy of
 * the PHP License and are unable to obtain it through the web, please
 * send a note to license@php.net so we can mail you a copy immediately.
 * 
 * @category Web
 * @package  Project
 * @author   Ole Nørby <mail@redacted.com>
 * @license  http://www.php.net/license/3_01.txt  PHP License 3.01
 * @version  GIT: https://github.com/redacted/project
 * @link     https://project.com
 */
```

**Expected behavior**
A Todo is to show in the Kanban view

**Leantime Version**
Docker version 2.1.8

**Server**
docker pull leantime/leantime:2.1.8

**PHP / MySQL Version**
Mariadb 5.7.35 - MySQL Community Server (GPL)

**Additional context**
Prior to creation:
![image](https://user-images.githubusercontent.com/6160947/134118783-ef25b2af-afbb-4b9c-9f54-250e226c9356.png)

Attempt:
![image](https://user-images.githubusercontent.com/6160947/134118633-4e90bada-5f56-498e-bcc1-2563272e04c6.png)

Result:
![image](https://user-images.githubusercontent.com/6160947/134118548-a5869e49-350e-4d8a-ac74-7ff16804bd76.png)

**Comment by olenoerby** [comment]
When the PHP comment is removed, the problem disappears.
Problem is: It shouldn't appear at all, since the comment line should be pure text.
It seems the comment field is broken by the comment, escaping the field.
This is potentially very bad.

**Comment by SephGER** [comment]
I had the same problem with a formatted table in the Comment. All following tasks were put in this table and the categories after "Blocked" were missing.
