### ISSUE TITLE
[BUG] Notifications sent to Slack says 'To Do' when it's a Project.

### ISSUE THREAD

**Issue by ebecaf** [Leantime/leantime#463]
When a project name or description is updated, the notification that is sent to Slack/ Zulip/ Mattermost says 
[User Name] updated the To-Do '[Project Name]'[Link]

There is also no space between the apostrophe after the project name and the URL, because of the apostrophe, the Link works on Zulip, but there should still be a space (see additional info below)

**To Reproduce**
1. setup Zulip details in project and save
3. change some details on the Project settings

**Expected behavior**
[User Name] updated the Project Details of '[Project Name]' [Link]

**Leantime Version**
2.1.8 (docker leantime/leantime:2.1.8)

**Server**
nignx

**PHP / MySQL Version**
MySQL 5.7.35
PHP 7.2.34

**Additional context**
Another bug is that when a Milestone is updated there is no space between the notification and URL, so the URL **does not come through as a link**.
e.g. 
[User Name] "updated a milestonehttps://example.com"
instead of
[User Name] "updated a milestone: https://example.com"

I realise this is low priority, but as it's not 'code' per-se, rather a grammar change, it would be nice if it could make it into the next update. Meanwhile I'll download the code and see if I can find out where to make the relevant changes.

**Comment by ebecaf** [comment]
RE the Milestone text issue, I think it's here, because the same text seems to be used for Zulip as the email notifications, there is no space added in Zulip because it's not needed in the email, but it is in the notification for the URL to work.
https://github.com/Leantime/leantime/blob/c38085c52c41b60780134d5c3bffea1d9eb4ce0a/resources/language/en-GB.ini#L821

Possibly a similar issue with the space when updating project details, but I guess that needs to be added in the code when concatenating the notification message and the URL.
Alternatively, a space here would fix it:
https://github.com/Leantime/leantime/blob/c38085c52c41b60780134d5c3bffea1d9eb4ce0a/resources/language/en-GB.ini#L766

Though that still leaves the issue of 'To-Do' when it's the Project Details being changed.

**Comment by ebecaf** [comment]
_For now I have updated my language file but obviously that is not a permanent solution._

**Comment by ebecaf** [comment]
Is there any possibility someone is going to fix this? It's quite bad that when a project gets updated I get a notification that says a to-do us updated!

**Comment by marcelfolaron** [comment]
Sorry about the issue. I have now fixed it and it will go out with the next release.
