### ISSUE TITLE
Issue in Installation

### ISSUE THREAD

**Issue by abhijeetgotkhindi** [Leantime/leantime#464]
Hey,
   I am not able to install  I have followed the below steps 

- Download latest release package
- Create an empty MySQL database
- Upload entire directory to your server
- Point your domain to the public/ directory
- Rename config/configuration.sample.php to config/configuration.php
- Fill in your database credentials (username, password, host, dbname) in config/configuration.php
- Navigate to <yourdomain.com>/install
- Follow instructions to install database and set up first user account

but still it is showing me below error.

![image](https://user-images.githubusercontent.com/26604525/134468128-4467a3de-7e59-4778-8199-62403f4bb161.png)

Thanks in advance

**Comment by serega404** [comment]
I have the same problem

**Comment by rzelnik** [comment]
I have similar issues with the installation process. I noticed that the application contains hardcoded fixed paths from the public folder to the private/hidden one. Some examples:

public/index.php
```
include_once '../config/configuration.php';
include_once '../config/settings.php';
include_once '../src/core/class.autoload.php';
```
public/download.php
```
include_once '../config/settings.php';
include_once '../src/core/class.autoload.php';
include_once '../config/configuration.php';
```
This is not always the case, especially on shared hostings, where the configuration could be different.

**Comment by DFF-fred** [comment]
> Try downloading the release package instead of the source code as mentioned [in the docs](https://docs.leantime.io/#/installation/quick-installation). The [releases](https://github.com/Leantime/leantime/releases) will contain the `/vendor` directory

That was exactly that! Thank you very much :-)
