### ISSUE TITLE
[FEATURE] Disable push notifiactions for Update/ New ToDos or Milestones

### ISSUE THREAD

**Issue by ebecaf** [Leantime/leantime#466]
In small and medium businesses or particularly in small teams, it is not always necessary to update the team when a To-Do or Milestone has been created or updated, or when a Project itself has been updated (although currently Project update notifications come through as a ToDo see #463)

**Describe the solution you'd like**
I would like the ability to disable Push Notifications (for Zulip/Slack - though I specifically use Zulip) for different types of actions.
For example:

- Disable push for new ToDos
- Disable push for ToDo updates
- Disable push for New Milestones
- Disable push for Project updates
- Add more detail to the message when ToDos are moved i.e. 'In Progess' or 'Waiting for Approval'

Thank you

**Additional context**
I would also like to change these settings on a per-project basis. Which I appreciate would be a lot more work.

**Comment by marcelfolaron** [comment]
We streamlined the notification feature, which will summarize most of these
