### ISSUE TITLE
[BUG] Issue creating items

### ISSUE THREAD

**Issue by iancarmichael** [Leantime/leantime#470]
Appear to be errors when creating some items e.g. Milestones
1) Navigate to /tickets/roadmap
2) Click on "Add Milestone" button

I expected to be able to complete details for a new milestone but the page refreshes with only the URL changing (to /tickets/roadmap&showMilestoneModal=)

I cannot create ideas, research etc either although I can create users.

Leantime Version 2.1.8 (downloaded)

Tried with both Apache 2.4 and latest Nginx

PHP 7.2.24 and Mysql 8.0.26

I have applied change for issue #457 

Browser (using both Firefox and Edge) show problems as follows:
Uncaught ReferenceError: jQuery is not defined
    <anonymous> http://****/tickets/editMilestone:76
editMilestone:76:9

and 

GEThttp://****/api/i18n
[HTTP/1.1 500 Internal Server Error 82ms]

Internal Server Error
Referrer Policystrict-origin-when-cross-origin

**Comment by phulstaert** [comment]
I have the same issue on a brand new install (clean Alpine VM with docker-compose).

**Comment by phulstaert** [comment]
ok, found it... stupid actually...
you havfe to put an email adress in /config/configuration.php, even when you do no use mailing.
Otherwise, you will get a err 500 on every creation of an item.
Maybe skip mailing if no mail address is set instead of an error?

**Comment by shimmyshine** [comment]
> ok, found it... stupid actually... you have to put an email adress in /config/configuration.php, even when you do no use mailing. Otherwise, you will get a err 500 on every creation of an item. Maybe skip mailing if no mail address is set instead of an error?

Thank you!

Won't lie, dug around for about 2 days looking for this answer.  I think the suite is awesome and has a ton of potential, but if I didn't, that's enough to make me nope right along to the next best available option lol

**Comment by marcelfolaron** [comment]
Thank you for the feedback. Totally understand. Working hard to get the
next release out :)
