### ISSUE TITLE
[BUG] Edit User page broken in v2.1.8

### ISSUE THREAD

**Issue by McDiggy69** [Leantime/leantime#471]
The Edit User page is broken in version 2.1.18.  The php error log reports:

 PHP Parse error:  syntax error, unexpected '=', expecting ')' in /.../src/domain/users/controllers/class.editUser.php on line 68

**Comment by marcelfolaron** [comment]
Confirmed. Will fix this in the next release this weekend

**Comment by TheWizl** [comment]
I´ve got v2.1.8. How do I update?

Best regards

Magnus
