### ISSUE TITLE
[BUG] sumRemaining uses parseInt and therefore rounds always down

### ISSUE THREAD

**Issue by ngblume** [Leantime/leantime#472]
**Describe the bug**
When using floating values for i.e. remainingHours, the sum in the ticket table view, using grouping by milestone, rounds down all floating values, causing the sum to be (way) too low.
![image](https://user-images.githubusercontent.com/3869392/135692798-7421fd94-c268-40ee-8d22-4bae51d3e090.png)

**To Reproduce**
1. Assign a ticket a fraction of an hour as remaining
2. Group tickets by milestone and check sum

**Expected behavior**
Add values as floats to get correct sum

**Leantime Version**
2.1.7 (docker via docker-compose)

**Server**
docker via docker-compose

**PHP / MySQL Version**
5.7 (docker via docker-compose)

**Additional context**
I'm pretty certain, that the incorrect source code can be found here:
https://github.com/Leantime/leantime/blob/013c785b125c6724ce567a5fd335793ab65e34e4/src/domain/tickets/js/ticketsController.js#L1171
I should be "return parseFloat(a) + parseFloat(b["@data-order"]);" if I understand the source code correctly.
A quick change didn't yield a chance, so there might be some more studff to change, maybe the db query...

**Comment by ngblume** [comment]
Code location is correct..

Who would like this to work in old versions, please change the compiled-app.js-file under "public/js"...
Just search for "parseInt" and replace with parseFloat, whereever necessary, i.e. remainingHours or plannedHours, etc.

**Comment by ngblume** [comment]
I forked the repo, made the changes under "src" and created the pull-request:
https://github.com/Leantime/leantime/pull/473

Would be nice to get some feedback and if the fix works, the issue can be closed.

**Comment by marcelfolaron** [comment]
Thank you for the fix!
