### ISSUE TITLE
[BUG] files not deleted from filesystem

### ISSUE THREAD

**Issue by McDiggy69** [Leantime/leantime#475]
I'm running Leantime v2.1.8.

I have discovered two instances so far where files are not being deleted from the filesystem.

First, when a to-do or an entire project is deleted, associated files on the filesystem are not deleted.

Second, when a new company logo is uploaded, the old logo is not deleted from the filesystem.

I'm assuming these are bugs.  If that behavior is by design, I'm curious to know why.

**Comment by marcelfolaron** [comment]
You are correct. These are bugs that need to be resolved
