### ISSUE TITLE
[BUG] Some problems in French calendar translation

### ISSUE THREAD

**Issue by EHRETic** [Leantime/leantime#477]
**Describe the bug**
French calendar miss July (Juillet in French), so every months after July are shifted. When I click on the 1st of September, the 1st of August is put in the date (same for start and end dates), etc. 

**Expected behavior**
Well, that date is the same as the one I click 😜

**Screenshots**
January
![image](https://user-images.githubusercontent.com/28634810/136089106-cb6bc7d0-9e7b-42a3-bfc4-31e9aa59db6f.png)

September
![image](https://user-images.githubusercontent.com/28634810/136088285-c921034d-b553-4415-8ddf-9da9a9b1a15c.png)

December
![image](https://user-images.githubusercontent.com/28634810/136088630-7d49b68a-1e99-4fc4-8a31-4633eb72baaf.png)

Also, October has a typo, it should be "Octobre":

![image](https://user-images.githubusercontent.com/28634810/136089306-0a9f41f4-83a5-4ce3-9e15-9084fe117ab8.png)

My 5 cents... glad I can help, it is a great software! 😉

**Versions**
Leantime 2.1.8 (Don't know if it was the case in a previous version), NGINX 1.21.3, PHP 7.4

**Comment by Beexx** [comment]
It seems to be fixed in already merged pull request [#458](https://github.com/Leantime/leantime/pull/458)
