### ISSUE TITLE
[Feature] Change/ hide "Drive Impact" text

### ISSUE THREAD

**Issue by ebecaf** [Leantime/leantime#491]
Please add a text box in the settings to allow us to change (or remove altogether) the "Drive Impact" text from the login screen.

Sure, I can hide it with some CSS, or delete it in the language files, but it obviously comes back after an update.

**Comment by PinkieIcePie** [comment]
Hi, I've already created a way to do this on my version, give me a day or two to get back on my PC and I'll post the changes I made :)

**Comment by marcelfolaron** [comment]
There is now a filter than can be used through a plugin to change the content.
