### ISSUE TITLE
[BUG] After a few days, any logo I upload gets a 404

### ISSUE THREAD

**Issue by ebecaf** [Leantime/leantime#492]
I have tried several different logos including one the exact size 260x60 asked for, twice the size, high DPI, png and jpeg and combinations thereof.

All that happens is that after a few days (unsure of exact time) the 'broken image icon' shows up on the login page and there is no icon at the top of the main menu. When using developer tools, the link to the image is still there, but it just goes to a 404...

The URL looks like this https://example.com/userfiles/3a87037d0b8f24b506e3b80b1.png so it's still linked there, but the image files seem to get deleted.

I'm using Leantime 2.1.8 on Docker (Ubuntu 20.04)

**Comment by marcelfolaron** [comment]
Is this still an issue? I wasn't able to reproduce the bug
