### ISSUE TITLE
[BUG] Datepicker doesn't have same first day of week as calendar

### ISSUE THREAD

**Issue by ncot-tech** [Leantime/leantime#496]
I have my language set to en-GB and in en-GB.ini `language.firstDayOfWeek = "1"` is set to make Monday be the first day of the week. This works fine in the main calendar, but in the popup date picker Sunday is still the first day of the week. The datepicker should be in the same format.

**Comment by Beexx** [comment]
Hello,

I second that... 

I've tried to modify the code at several places, but it does not seem to work. For instance, in : 
src/domain/calendar/js/calendarController.js

I've added : 
` 
.datepicker( ...
firstDay: leantime.i18n.__("language.firstDayOfWeek"),
`

And in my language file, I do have : 
`language.firstDayOfWeek = "1"`

But it does not seem to work. The first day displayed in the first column is still Sunday : 

![image](https://user-images.githubusercontent.com/50069390/147659765-a089ecdf-e0b8-4646-9d07-c963107ac941.png)

Any clue how to fix this ?
