### ISSUE TITLE
[BUG] Access to this resource on the server is denied!

### ISSUE THREAD

**Issue by vix95** [Leantime/leantime#497]
Hi, I found a bug when I create a subtask for To-Do.
Step by step:
1. Create To-Do
2. Edit To-Do
3. Create Subtask and type **Create new table** in the headline.
![image](https://user-images.githubusercontent.com/38139321/139941386-09a9ee7f-5b73-4ffe-b5a6-fe72ec888969.png)
4. Save
![image](https://user-images.githubusercontent.com/38139321/139941075-c6d9cd33-eec6-4a92-85f9-c59c1f3a1f19.png)

I think that the problem is related to **'table'** word.

**Comment by marcelfolaron** [comment]
Thanks will take a look

**Comment by marcelfolaron** [comment]
Reviewing this again. I believe this has to do with your servers mod_security firewall (or similar). 
Leantime allows that entry (and filters it correctly). Please re-open if the issue persists.
