### ISSUE TITLE
[BUG] Can't manage my own or other users (I am an admin)

### ISSUE THREAD

**Issue by ebecaf** [Leantime/leantime#499]
When I go to `https://example.com/users/showAll/` and click any of the users to go to `https://example.com/users/editUser/2/` (for example), I get `HTTP ERROR 500`

I see this in the console:

>`crbug/1173575, non-JS module files deprecated. (anonymous) @ (index):7290`

Which does not appear on other pages.

**Comment by marcelfolaron** [comment]
Yeah this is a known issue. I linked the pull request with the fix. 
I just need to finish up some clean up before I can create another release. Thank you for your patience
