### ISSUE TITLE
[FEATURE] See all milestones calendar of multi projects in a same view

### ISSUE THREAD

**Issue by previmeteo** [Leantime/leantime#501]
**Is your feature request related to a problem? Please describe.**
We would like to have a visual representation of all our project's milestones to help the planification of the team
**Describe the solution you'd like**
Same view as the single project one but with all the projetcs
**Additional context**
none

**Comment by matheus-rossi** [comment]
That's a great idea. We have exactly the same difficulties here.
I'm creating a unified Gantt chart, in another tool to keep the eye on all projects in the same "view".

**Comment by Whos0who** [comment]
Is this feature has been added?

**Comment by clemrdh** [comment]
Interested as well.
Same for multi-projects kanban.
Kind of an unified view for milestones and kanban would be very great.

**Comment by marcelfolaron** [comment]
Now available under Portfolio
