### ISSUE TITLE
[BUG] Kanban Column name cache

### ISSUE THREAD

**Issue by SephGER** [Leantime/leantime#508]
**Describe the bug**
After renaming a Kanban Column, the column keeps this name in all projects until logged out.

**To Reproduce**
1. Go to "Tasks"
2. Rename the Kanban-Column
3. Change the project
4. Go to "Tasks"
5. Column has the same name as in the other project
6. Log out and log in
7. Go to "Tasks"
8. Kanban-Column has the right name for the project
9. Change to first project
10. Go to "Tasks"
11. Kanban-Column has the same name as in the other project

**Expected behavior**
Each Project should have its own Kanban-Column names and the names should change if the project is changed.

**Leantime Version**
2.1.8

**Server**
Docker-Compose

**PHP / MySQL Version**
mysql:5.7, leantime:latest

**Additional context**
The names in the DB seem to be the right ones but the server seems to only cache the names for the first project and display this cache on every other project

**Comment by JulioSM98** [comment]
Solution Temporal: In www/html/src/domain/tickets/repositories/class.tickets.php line 128
![image](https://user-images.githubusercontent.com/29544449/142426343-c04fdf81-f6bd-4cb5-9711-239a62396ed6.png)
Add "!" in if

**Comment by marcelfolaron** [comment]
Thanks @JulioSM98. Almost, we could just add the unset into `projectService->changeCurrentSessionProject()` method.
There are a couple places where changeCurrentSessionProject is being called. 
Can you create a PR for that?

**Comment by SephGER** [comment]
Created https://github.com/Leantime/leantime/pull/579
