### ISSUE TITLE
can't see  /dashboard/show

### ISSUE THREAD

**Issue by bluemix** [Leantime/leantime#51]
Hello,
when I started to login to leantime, I get this error:
```
Not Found
The requested URL /dashboard/show was not found on this server.
Apache/2.4.12 (Ubuntu) Server at 192.168.221.66 Port 80
```
and thanks in advance.

**Comment by marcelfolaron** [comment]
There are a few possible solutions. First I would check if mod_rewrite is installed and enabled. 
Secondly, the site needs to be in the root of your web accessible vhost configuration. eg. DOMAIN.com/ it won't work if it is in DOMAIN.com/subfolder/

**Comment by bluemix** [comment]
Hello,
yes, I set it on the root of the site.
I hope you see the first check.
thanks for your reply.

**Comment by imsuwj** [comment]
@bluemix Hello,I faced with the same problem.Please enable the mod_rewrite. Edit the `/etc/httpd/conf/httpd.conf`,uncomment the `LoadModule rewrite_module modules/mod_rewrite.so` and  change ` AllowOverride None` to `AllowOverride All` .
```
 <Directory /var/www/html>
...
    AllowOverride All
...
 </Directory>

```

**Comment by marcelfolaron** [comment]
Thank you @imsuwj. @bluemix  let me know if that worked. I'll ad that to a trouble shoot page

**Comment by marcelfolaron** [comment]
I think this is working now. Closing the issue
