### ISSUE TITLE
[BUG] Hyphen in e-mails are not accepted

### ISSUE THREAD

**Issue by sogln** [Leantime/leantime#522]
*Login issue*

**Describe the bug**
If the login name contains a hyphen "a.xx@t-online.de", the login attempt is rejected with the error message "Username or password incorrect!".

**To Reproduce**
1. Go to 'Login'
2. Insert 'a.xx@t-online.de'
3. Insert a password like 'Jessi200'
3. Click 'Login'
4. See error !Username or password incorrect!'

**Expected behavior**
All the credentials as shown above have been previously entered in the user data.

**Leantime Version**
2.1.7

**Server**
Apache

**PHP / MySQL Version**
PHP-Version: 7.2.33
Datenbank-Client Version: libmysql - mysqlnd 5.0.12-dev - 20150407

**Additional context**
---

**Comment by marcelfolaron** [comment]
Doesn't seem to be a problem in 2.1.9 anymore.

**Comment by sogln** [comment]
Hallo Marcel,

thanks a lot for completion of #522.

I have one question.

If I overwrite my directories and files of version 1.2.7 with the directories and files of version 1.2.9 
as mantioned to update:
Make sure to take a backup of your database and files done
Replace all files in your directory with the updated version done
configuration.php  /* Database */  actualized
If there were any database changes, the system will redirect your to <yourdomain.com>/update
When I start the program now, I get a white screen. Do you have any hingst to me, whats going wrong?

Best regards

Christian

**Comment by sogln** [comment]
Sorry Marcel,

of course the versions 2.1.7 and 2.1.9 are meant!

Best regards

Christian

**Comment by marcelfolaron** [comment]
Hi,

First step would be to make sure the email address field is set in the
config file. (Can be any value). That is a bug that was introduced in
2.1.9. I have a fix prepared.

If that doesn’t work please check the contents of resources/error.log

**Comment by sogln** [comment]
Hi Marcel,

content of error.log
[08-Jul-2022 02:48:24 America/Los_Angeles] PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/chblbqxq/www.lean.chb.cc/vendor/symfony/polyfill-php80/bootstrap.php on line 29
Best regards

Christian

> Am 08.07.2022 um 15:56 schrieb Marcel Folaron ***@***.***>:
> 
> 
> Hi,
> 
> First step would be to make sure the email address field is set in the
> config file. (Can be any value). That is a bug that was introduced in
> 2.1.9. I have a fix prepared.
> 
> If that doesn’t work please check the contents of resources/error.log
> 
> 
>

**Comment by marcelfolaron** [comment]
Oh that is strange. This is an error in the vendor directory which are
external packages we rely on.
Where did you download the files from? Could it be that you used the
source.zip instead of the release?
 Make sure you use a release version (not the zip file called source but
the ones called Leantime-v…

Or download it from our website. First guess is to just try again maybe
something went wrong with the upload.

**Comment by sogln** [comment]
Hi,
I have download now the zip from:


The same white screen, but no comment in the error.log

I have testet it with email adress and without in the configuration.php

Best regards

Christian


> Am 08.07.2022 um 17:57 schrieb Marcel Folaron ***@***.***>:
> 
> 
> Oh that is strange. This is an error in the vendor directory which are
> external packages we rely on.
> Where did you download the files from? Could it be that you used the
> source.zip instead of the release?
> Make sure you use a release version (not the zip file called source but
> the ones called Leantime-v…
> 
> Or download it from our website. First guess is to just try again maybe
> something went wrong with the upload.
> 
> 
>

**Comment by sogln** [comment]
Hi
 
testet via firefox and safari

Best regards

Christian

> Am 08.07.2022 um 19:43 schrieb Christian Bernert ***@***.***>:
> 
> Hi,
> I have download now the zip from:
> <PastedGraphic-1.png>
> 
> The same white screen, but no comment in the error.log
> 
> I have testet it with email adress and without in the configuration.php
> 
> Best regards
> 
> Christian
> 
> 
>> Am 08.07.2022 um 17:57 schrieb Marcel Folaron ***@***.*** ***@***.***>>:
>> 
>> 
>> Oh that is strange. This is an error in the vendor directory which are
>> external packages we rely on.
>> Where did you download the files from? Could it be that you used the
>> source.zip instead of the release?
>> Make sure you use a release version (not the zip file called source but
>> the ones called Leantime-v…
>> 
>> Or download it from our website. First guess is to just try again maybe
>> something went wrong with the upload.
>> 
>> 
>>
