### ISSUE TITLE
Hyphen in logins are not accepted!

### ISSUE THREAD

**Issue by marcelfolaron** [Leantime/leantime#546]
### Discussed in https://github.com/Leantime/leantime/discussions/521

<div type='discussions-op-text'>

<sup>Originally posted by **sogln** December  4, 2021</sup>
Bug:
a.xxx@t-online.de 
The hyphen "-" is not accepted for the login!

Regards
Christian</div>

**Comment by sogln** [comment]
Ok. Is there a possibility to use another login user name instead of the e-mail? Where can I enter it?
