### ISSUE TITLE
[BUG] Session timeout every 30min or so

### ISSUE THREAD

**Issue by HijackHornet** [Leantime/leantime#557]
**Describe the bug**
I get disconnected from the site every half an hour or so, event though the sessionn timeout is set to 8h
`public $sessionExpiration = 28800; //How many seconds after inactivity should we logout?  28800seconds = 8hours`

**To Reproduce**
1. Have a page open and go grab a coffee
2. Come back
3. You're now disconnected but it doesnt show it. So if you try stopping a timer, it will stop it, showing the login page over the notification, but it wont actually register the change in DB. 

**Leantime Version**
2.1.8

**Server**
Apache2

**PHP / MySQL Version**
PHP 7.4
MariaDB10

**Additional context**
Firefox, no adblock on the domain

**Comment by nickian** [comment]
I'm noticing the same behavior. The app does not seem to respect the session expiration setting in the configuration.

**Comment by HijackHornet** [comment]
The most disturbing part was that it showed the entire "login" page into the notification block. I dont have a screenshot unfortunatly as i didnt keep using it afterward.

**Comment by marcelfolaron** [comment]
I have a hard time reproducing this. I stay logged in and the cookie seems to be fine. 
Can you take a look and check if the cookie expiration date/time is correct? I noticed that only Firefox users encountered that problem, so I am wondering if there is a php setting or so that needs to be set.

**Comment by martin-korf** [comment]
You can try change the session.gc_maxlifetime in the php.ini . It seems that this solved it for me

; After this number of seconds, stored data will be seen as 'garbage' and
; cleaned up by the garbage collection process.
; http://php.net/session.gc-maxlifetime
session.gc_maxlifetime = 86400

**Comment by marcelfolaron** [comment]
Thank you for the pointer. I didn’t realize the default was set to 1440
which is 24 min.

I’ll add that to the list of ini_sets we are executing. Keep in mind the
docs though:


   -

   Note: If different scripts have different values of
   session.gc_maxlifetime but share the same place for storing the session
   data then the script with the minimum value will be cleaning the data. In
   this case, use this directive together with session.save_path.
