### ISSUE TITLE
[BUG] updated logo distorted

### ISSUE THREAD

**Issue by mashuptwice** [Leantime/leantime#567]
When updating the Logo via company settings on the webinterface, the image gets displayed as distorted garbage.

1. Install Leantime
2. go to Company Settings
3. upload logo
4. logo gets displayed distorted on every occurrence on the webpage

**Expected behavior**
The logo should resemble the uploaded image.

**Leantime Version**
V2.1.8

**Server**
Apache/2.4.51 (Debian 11)

**PHP / MySQL Version**
PHP 7.4.25 (cli) (built: Oct 23 2021 21:53:50) ( NTS )
mysql  Ver 15.1 Distrib 10.5.12-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Additional context**
Distorted may be the wrong term as there is no resemblance with the original image. 
The attached images are taken with the default logo copied from "public/images/logo.png" and uploaded via described method.
The behavior occurs only with ~~firefox~~, librewolf, ~~chromium and probably every other browser.~~
Clearing the browser cache as well as repairing the webroots permissions haven't made any difference. 
As I don't know where the uploaded image gets saved to, I can't even check if they get uploaded at all.

![Screenshot_20220111_230724](https://user-images.githubusercontent.com/54219098/149030879-3cd80458-229a-4079-b560-685591bf5c7d.png)
![Screenshot_20220111_231004](https://user-images.githubusercontent.com/54219098/149030923-64dd4826-f68c-49b5-9b67-7b7aa21ffc1e.png)
![Screenshot_20220111_230939](https://user-images.githubusercontent.com/54219098/149030953-05dd43ca-ca8b-472c-a876-c418091ba52d.png)

If there is any method on how to set the logo manually via config files or mysql, please let me know.

**Comment by mashuptwice** [comment]
The same also happens if I try to change a user profile picture.
It seems like only a few hundred bytes get uploaded of the pictures:

```
drwxr-xr-x 2 www-data www-data  4096 11. Jan 23:25 .
drwxr-xr-x 8 www-data www-data  4096 11. Jan 22:23 ..
-rwxr-xr-x 1 www-data www-data 13671 11. Jan 22:58 11d7c8fc261ef17000bc490d8252eb12.png
-rwxr-xr-x 1 www-data www-data   474 11. Jan 23:00 15abd2a799aa0274af21ff4bce94cc87.png
-rwxr-xr-x 1 www-data www-data   308 11. Jan 23:05 63b772950072af4958a29ba508c51084.png
-rw-r--r-- 1 www-data www-data  1367 11. Jan 23:25 6fa51e9b6725cc9ffcdd6c1b92cab881.png
-rwxr-xr-x 1 www-data www-data   328 11. Jan 23:01 e71e4c765f34bf2876b6708d12a9c949.png
```

**Comment by marcelfolaron** [comment]
This is bizarre. Please check the uploaded files in user data/ and public/userdata

We have a ja library that manages the image resizing. If your pictures are distorted on the server it's probably that.
Can you check if you see any errors in the browser console (F12 in Chrome) when you edit and upload the picture?

**Comment by mashuptwice** [comment]
I got it resolved. Seems like the option "privacy.resistFingerprinting" in firefox results in this behaviour. 

I've checked the images in the servers directories and they are distorted when downloaded and viewed locally as well. This means there is something going wrong in the upload process. 

I still don't understand why the canvas fingerprinting prevention results in an uploaded image to be distorted. From my limited understanding it should only affect images which are downloaded from the server?

**Comment by marcelfolaron** [comment]
Interesting. Seems there is an open Firefox bug on this as well: https://bugzilla.mozilla.org/show_bug.cgi?id=1676028
There is some discussion around reading canvas. The way our upload works is to resize the image in the browser and then upload. 
That saves server resources. We can keep the bug open to see if there is a workaround or fix

**Comment by marcelfolaron** [comment]
So it seems Firefox blocks the canvas API alltogether. Did you see a prompt about canvas (https://www.ghacks.net/2017/10/28/firefox-58-warns-you-if-sites-use-canvas-image-data/)? 
We are using canvas for a few of the features. So while I don't want users to force turning privacy.resistFingerprinting off, we would probably have to encourage whitelisting the leantime instance.

**Comment by mashuptwice** [comment]
There is no prompt, also no icon in the URL bar like the one shown here:
![canvas_setting](https://user-images.githubusercontent.com/54219098/150722908-e1ecc7d4-066d-48f2-b388-1bdd17c16d8f.png)
I can confirm the icon is being shown on other websites with canvas, just not on leantime.

**Comment by mashuptwice** [comment]
I've edited the question. The problem seems to be related to a non-default html canvas default policy. in my setups. I've noticed that on most websites that require canvas for functionality, there will be an explicit popup. Is there any way to check if the browser has canvas capability?

**Comment by marcelfolaron** [comment]
I’ll double check. Thanks for the additional context
