### ISSUE TITLE
Docker image for leantime

### ISSUE THREAD

**Issue by yifeikong** [Leantime/leantime#57]
Could you please provide an official docker image for leantime? it would be great for new users to try out.

**Comment by marcelfolaron** [comment]
Official Docker Image can now be found at https://hub.docker.com/r/leantime/leantime

**Comment by yifeikong** [comment]
That's wonderful work!

Could you please also add `Dcokerfile` to this GitHub repository? 

Thanks.

**Comment by marcelfolaron** [comment]
I assume that would be for a development environment? I'll work on that.

**Comment by marcelfolaron** [comment]
Available in the docker repo https://github.com/Leantime/docker-leantime
