### ISSUE TITLE
Layout problems when running from master

### ISSUE THREAD

**Issue by danshearer** [Leantime/leantime#576]
Thanks for Leantime!

I find the August 2020 stable release to be very usable. However I notice lots of useful-fixes in "git log". So I cloned the project and followed the development install instructions.

See attached screenshot. There are parts missing on the left hand side; text spread far down the page of the screen; overwriting on the right hand side.

This happens with multiple browsers. Is this known behaviour with current master? I couldn't see any issue reporting it.

Thanks,

Dan
![l2](https://user-images.githubusercontent.com/3944577/149647373-adbf33d9-1f33-4984-8dd7-3d93c45b9197.png)

**Comment by marcelfolaron** [comment]
That doesn't seem right. Did you run npm install and the grunt tasks?

**Comment by danshearer** [comment]
>  Did you run npm install and the grunt tasks?

It looks like not all the grunt tasks finished their uglify jobs. After I ran:

```
./node_modules/grunt/bin/grunt Build-All --verbose
```

in another tree, I noticed more files in ```public/js/```

Fixed, thanks!

Dan

**Comment by marcelfolaron** [comment]
Perfect. Glad that worked. Let me know if you need anything else
