### ISSUE TITLE
[BUG] Subtasks disapear from main task

### ISSUE THREAD

**Issue by davask** [Leantime/leantime#584]
**Describe the bug**
When I define a task assigned to user X and I define multiple subtasks in that main task they appear as expected.
However, if user X assign the main task to another user Y, User Y sees the main task and subtasks as expected BUT user X do not see the main task however he sees the subtasks as independants tasks like if they were main tasks too.
As long as this "main/sub" tasks are not modified by user X then original subtasks still appears as subtasks for user Y BUT if user X modify those "main/sub" tasks then they become independants task and disapears from the original main task.

**To Reproduce**
Follow explainationabove

**Expected behavior**
If subtasks are attached to a main tasks, then they must follow the main task when task are reassigned to another user

**Leantime Version**
2.1.8

**Server**
Apache 2.4

**PHP / MySQL Version**
PHP 7.3.33 & MariaDB 10.3.31

**Comment by marcelfolaron** [comment]
Old bug. This was fixed in 2.1.9
