### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by marcelfolaron** [Leantime/leantime#59]
Add support for internationalization.

**Comment by marcelfolaron** [comment]
Core support enabled in develop branch. Now working through all the modules to find and replace content.

**Comment by luxlogica** [comment]
Does that include support for date formats? Being able to select a standard (non-US) date format is crucial for most international users.

**Comment by marcelfolaron** [comment]
Yes that includes date formats. The format will be stored in the language file. See this file for reference: https://github.com/Leantime/leantime/blob/feature-i18nSupport/resources/language/en.ini

**Comment by marcelfolaron** [comment]
Quick update on this. Most modules have been prepared to be translated. 
We will release a beta this weekend. We are in need of volunteers to translate. If you would like to contribute, please let me know. Thank you!

**Comment by marcelfolaron** [comment]
Support included in 2.1-beta

**Comment by lukepolak** [comment]
@marcelfolaron So, I'd like to do polish translation - so I just basicly make pl-PL.ini and add it to langualist.ini to test it? Or are there any more steps?

**Comment by marcelfolaron** [comment]
Yes, that and set "pl-PL" as language in your config file.

Thanks for working on the translation, let me know if you have any
questions.

**Comment by softmade-timobruentjen** [comment]
I´ve loaded the beta version but still not able to change language. Have set the configuration to "de-DE" but no effect, am i doing somethin wrong?

**Comment by marcelfolaron** [comment]
No worries, yeah we are still working on all of the German translations. We have community members contributing.
