### ISSUE TITLE
404 not found error when localhost/install run 

### ISSUE THREAD

**Issue by dreamworksTest** [Leantime/leantime#617]
after followed General Steps run the localhost/leantime then it only changed the url to localhost/install and showing 404 not found error.

**Comment by alaksandarjesus** [comment]
After installing in localhost, update in config/settings.php
![image](https://user-images.githubusercontent.com/4712552/157404579-cde2226c-ff9c-4bd6-8bb9-0fb9956b820f.png)
`public function getBaseURL () {

        $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443) ? "https://" : "http://";
        $domainName = $_SERVER['HTTP_HOST'].'';
        return $protocol.$domainName.'/{folder_name}';

	}`

**Comment by hifron** [comment]
In public/.htaccess file there are lines which could be altered without https: 

```
RewriteCond %{HTTP:X-Forwarded-Proto} =http
RewriteRule .* http://%{HTTP:Host}%{REQUEST_URI} [L,R=permanent]
```

**Comment by Shaun-Fong** [comment]
Check out [Nginx.conf](https://github.com/Leantime/leantime/blob/master/nginx.conf) template.
