### ISSUE TITLE
Nginx support

### ISSUE THREAD

**Issue by marcelfolaron** [Leantime/leantime#62]
Tthe htaccess redirects don't work with nginx and converting them causes issues. Investigate and solve nginx configuration.

**Comment by GhaziTriki** [comment]
Hello @marcelfolaron 

We started using leantime at RIADVICE and put a comlete nginx configuration that is working. Are you interested into a pull request?

**Comment by marcelfolaron** [comment]
Hi @GhaziTriki,

Yes, that would be awesome! Thank you!

**Comment by GhaziTriki** [comment]
Give me few minutes. It should not be hard. I also have a lot of ideas to improve your product maintainability :)

**Comment by marcelfolaron** [comment]
Awesome, thank you so much! Happy to chat about all your ideas! I am working on code clean up as well to prepare for i18n.
