### ISSUE TITLE
url issue

### ISSUE THREAD

**Issue by dreamworksTest** [Leantime/leantime#620]
i installed leantime followed the doc after that only login page works fine . but after login it showing blank page on http://localhost/leantimenew/public/ here if i change the url statically to localhost/leantimenew/public/index.php?act=dashboard.show then it redirects me to on dashboard page for the all pages redirection is not working without ?act= .............. how can i solve this issue?

**Comment by marcelfolaron** [comment]
Is this issue still relevant? Will close for now.
