### ISSUE TITLE
Remove password from initial email

### ISSUE THREAD

**Issue by Stormfinger** [Leantime/leantime#621]
We have set up Leantime and all well but i as user received mail from Leantime sistem and it contained password as text. Which is realy not good. 

When user is created it would be better for him to proceed the same as he would forgot his password. so even in initial mail one can be redirected to main page with instructions in mail ..."if you dont know password please reset it" 

![https_project_inconviniance](https://user-images.githubusercontent.com/84122683/153259870-7229fa3f-77c1-43b5-986c-973c8d1bdf61.jpg)

**Comment by barsk** [comment]
I second this. This is unsafe.

**Comment by axelrindle** [comment]
What about a login-like page that allows the user himself to set an initial password?

**Comment by marcelfolaron** [comment]
Now implemented in 2.3.3
