### ISSUE TITLE
[BUG] Looping login page

### ISSUE THREAD

**Issue by rivaldy98** [Leantime/leantime#693]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
A clear and concise description of what the bug is looping login page if I am login to the apps

**To Reproduce**
1. Go to 'https://foo.bar'
2. Insert username & password 
3. Click on "Login"

**Expected behavior**
Login to the apps

**Leantime Version**
Which Leantime version are you using 2.1.8

**Server**
Docker Env

**PHP / MySQL Version**
PHP 7.2
MariaDB 10.1

**Additional context**
Always looping to appUrl if I tried login the apps

**Comment by jmt-lab** [comment]
I'm having this same issue, in my case I have tried to deploy on ECS/Fargate in AWS and using an ALB to do the SSL Termination. Looking at the network logs and comparing against running the docker container locally it looks like there is a patch. No errors in the error logs either.

**Comment by marcelfolaron** [comment]
Are you using Apache?
Can you try to comment out line 6 + 7 in public/.htaccess ?

I just recently discovered that we check for x-forward twice (once in
htaccess and then again in the php app. This might be causing the loops.

**Comment by jmt-lab** [comment]
^ That fixed it for me, is there a way we can get a new docker image released that either has that commented out, or has some flag or -e flag to turn it off?

**Comment by marcelfolaron** [comment]
Ah, that explains a lot. I’ll create a new release tomorrow with a couple
fixes.
