### ISSUE TITLE
Small text bug in new install

### ISSUE THREAD

**Issue by scythetleppo** [Leantime/leantime#696]
Just trying this product out. Self installed, went through tour, have not changed anything.
Clicked "Project Settings" on the default project. This pops up. Notice the variables has not been replaced. v=2.1.9

![image](https://user-images.githubusercontent.com/99230615/165931085-9a15aac3-d801-45ac-a46b-887c2948ac8c.png)

**Comment by marcelfolaron** [comment]
Thank you for reporting this. Hope Leantime is working for you!
