### ISSUE TITLE
Cannot add more than 1 Idea board

### ISSUE THREAD

**Issue by wurrtelbrumft** [Leantime/leantime#699]
I click on the link to create a new idea board, type in the name and click on create... it gives the message that it was successful but no new board is showing up.

**Comment by marcelfolaron** [comment]
Any errors in resources/logs/error.log ?

**Comment by wurrtelbrumft** [comment]
> [02-May-2022 12:21:34 America/Los_Angeles] PHP Fatal error:  Uncaught PHPMailer\PHPMailer\Exception: Invalid address:  (From):  in /www/htdocs/mydomain/vendor/phpmailer/phpmailer/src/PHPMailer.php:1300
> Stack trace:
> #0 /www/htdocs/mydomain/src/core/class.mailer.php(162): PHPMailer\PHPMailer\PHPMailer->setFrom('', 'Name (Leantim...')
> #1 /www/htdocs/mydomain/src/domain/ideas/controllers/class.advancedBoards.php(68): leantime\core\mailer->sendMail(Array, 'Name')
> #2 /www/htdocs/mydomain/src/core/class.frontcontroller.php(168): leantime\domain\controllers\advancedBoards->run()
> #3 /www/htdocs/mydomain/src/core/class.frontcontroller.php(107): leantime\core\frontcontroller->executeAction('ideas.advancedB...')
> #4 /www/htdocs/mydomain/src/core/class.application.php(88): leantime\core\frontcontroller->run()
> #5 /www/htdocs/mydomain/public/index.php(43): leantime\core\application->start()
> #6 {main}
>   thrown in /www/htdocs/mydomain/vendor/phpmailer/phpmailer/src/PHPMailer.php on line 1300

I added an emailadress + smtp infos and now the board I create replaces the existing one (I can still not create more than one board)
