### ISSUE TITLE
Submitting changes (new to-dos, projects, users) returns HTTP ERROR 500

### ISSUE THREAD

**Issue by caseyv86** [Leantime/leantime#700]
Hello. Fairly novice here...but I set up leantime in a docker on Unraid running nginx proxy manager. I can log in just fine, however every time I try to create something (new to-do/project/user) the page errors out with "HTTP ERROR 500 leantime.mydomain.com can't currently handle this request." Once I modify the URL back to HTTPS, everything loads fine, and my change is saved. I can only assume some setting is defaulting to the unsecure protocol, but I am not sure where to look. 

Appreciate any guidance/ideas!

**Comment by marcelfolaron** [comment]
Welcome to Leantime. There is currently a known issue with this 500 error.
Please make sure the variable "email" is set in your config file (can be
any email).
Once that is set the error should disappear.

**Comment by caseyv86** [comment]
Thank you for the quick reply! I realize now I posted this under the wrong repo (since I'm using docker). Sorry for what I am sure is a basic question...but how to do I access the config file? With the docker in Unraid, I don't have the typical appdata folder like most containers. I attempted to add a variable to the Unraid container but that didn't work.

**Comment by marcelfolaron** [comment]
Ah I See. You would have to pass it in as env variable similar to the MySQL
data. In this case it‘d be:

LEAN_EMAIL_RETURN

**Comment by caseyv86** [comment]
That did it. Thank you again!
