### ISSUE TITLE
[BUG] Idea Wall reports an error if milestone is added to an idea

### ISSUE THREAD

**Issue by Corborax** [Leantime/leantime#701]
**Describe the bug**
I added a milestone to an idea on the idea wall. When saving, the pop-up gets red border and a message is diplayed, that an error occured. After closing the window, the milestone appears underneath the idea and in the Milestones Section in the timeline.

**To Reproduce**
1. Go to Ideas
2. Create new Idea Wall
3. Add Idea 
4. Open Idea and Assign an existing Milestone OR create a new milestone (no difference)
5. See Error "An error occured"

**Expected behavior**
I expect the window to close without an error message.

**Leantime Version**
2.1.9

**Server**
Apache

**PHP / MySQL Version**
PHP 7.4
MySQL 8

**Comment by marcelfolaron** [comment]
Do you see any errors in resources/error.log ?
I can't reproduce this issue on my end
