### ISSUE TITLE
Menu link issue for subfolder

### ISSUE THREAD

**Issue by linkgtaylor** [Leantime/leantime#705]
I installed to a subfolder called 'main'. Upon navigating to some of the menu tabs I realize that the 'To-Dos' menu began resolving to an incorrect link. It actually doubled the subfolder reference in the link. Please fix.

![image](https://user-images.githubusercontent.com/6674071/167181305-10d2054f-ad8d-4c96-bd57-5797fd353891.png)

**Comment by marcelfolaron** [comment]
Did you set the appURL in the config file?

**Comment by linkgtaylor** [comment]
Yes I did.

public $appUrl = "/main";

**Comment by marcelfolaron** [comment]
Can you set the url to the fqdn?
HTTPS://yourdomain.com/main”

That should fix it.

**Comment by linkgtaylor** [comment]
Thanks. That worked
