### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pareshpandit** [Leantime/leantime#709]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
The addition pages "Add Client" / "Add Project" / "Add User" do not return to their respective management pages (eg. User Management), or to "Add New", upon succesful addition of the object. They go to a blank page. One has to hit back, or refresh. 

(Also, there is no Add Another option on the Add pages - Maybe there can be a success message, along with an add another option?)

**To Reproduce**
1. Go to 'Your Profile Menu at Top RHS corner (as Admin)'
2. Click on 'User Management'
3. Scroll down to '+ Add User'
4. After you hit Save, see how the creation is handled, to discover the bug.

**Expected behavior**
What is expected is a Suceess Message such as "User Created" or even before that, a information confirmation screen.

**Leantime Version**
v 2.1.9

**Server**
nginx [from package - over shared hosting with Hostinger] 

**PHP / MySQL Version**
PHP : 7.4 
MySQL : 10.5
MySQL DB : 7

**Additional context**
The same thing happens when adding any object may it be a User, Client or Project.

**Comment by adamyfai** [comment]
Also occurring on the latest docker image leantime/leantime:2.1.9

Image versions:
PHP: 7.2.34
MySQL: 15.1
MySQL DB: 5.7

**Comment by marcelfolaron** [comment]
Please make sure to set the $email variable in the config file.

**Comment by adamyfai** [comment]
Thank you.
Added 
 - LEAN_EMAIL_RETURN=myemail@company.com

to my docker-compose.yml and the issue was resolved

**Comment by pareshpandit** [comment]
Got it, works buttery-smooth now - so basically, it wasn't finding the address to send email intimation to.
Thank you. :)

**Comment by marcelfolaron** [comment]
Lol, yeah.
The library we are using wasn’t throwin an exception before the latest
update. I’m working on a fix to prevent the 500 from happening.
