### ISSUE TITLE
[BUG] Columns on To-Do's page shifted to bottom

### ISSUE THREAD

**Issue by tilstoni** [Leantime/leantime#717]
**Describe the bug**
Two of the columns on the To-Do's page have shifted to the bottom. Their width is also significantly reduced, so one is unable to read the content of the two columns.
Numbers of numbered lists on all tasks are partly on the outside of the task box in Kanban view. This might have nothing to do with the issue but since this seems to be a formatting issue, I thought it might be worth to mention.

![Leantime-Tasks-Issue](https://user-images.githubusercontent.com/32870423/169805331-27139e53-a498-4469-a2a5-97ab75b070d1.PNG)

**To Reproduce**
Unfortunately my colleagues do not recall, which exact task/change broke the view. Recreating it by copying task names and descriptions yielded no result. So far this issue only arises in one project.

**Expected behavior**
The five columns should appear side by side to each other.

**Leantime Version**
2.1.9

**Server**
Official Docker Image. Ubuntu 20.04.2 LTS on Host.

**PHP / MySQL Version**
as provided in most recent Docker Image v2.1.9

**Comment by Treuman** [comment]
found a bug, it appears when all the specified conditions match:
1. When you color the task description in any color (or use the built-in text editor)
2. If in the description of the task, in the line of characters, there are more than a preview of the task (in kanban form), it was possible to find out empirically - 52 characters (without spaces).
3. If there are more than three lines in the task description

**Comment by marcelfolaron** [comment]
Oh, wow. I’ll do some digging, but if you do find the ticket (content) that
caused it, please let me know.
