### ISSUE TITLE
Milestone page shows empty after adding a new milestone

### ISSUE THREAD

**Issue by GhaziTriki** [Leantime/leantime#72]
I see an empty page after adding a new milestone. I am using nginx.

![image](https://user-images.githubusercontent.com/4991088/70471327-36e7cc00-1acd-11ea-941b-2e3bfd0c38ea.png)

**Comment by marcelfolaron** [comment]
Do you have steps to reproduce the issue? Where did you create the milestone (on the milestone page or from the To-Do page)? Did you see any javascript issues? I don't think this is a nginx problem since it routed correctly. It seems the javascript didn't fire.

**Comment by GhaziTriki** [comment]
json extension was disabled.
