### ISSUE TITLE
[BUG] User permission can't setting by SQL Table

### ISSUE THREAD

**Issue by snowcatjoey** [Leantime/leantime#726]
**Describe the bug**
In table 'zp_modulerights'.'roleIds' doesn't match permissions

**To Reproduce**
1. I want to let Developer Group can Add Project, and Manager Group can't edit users.
2. In table, the value of 'projects/class.newProject.php' 'roleIds' already set  2,4,5.
                                  & 'users/class.showAll.php' 'roleIds' only set  2.
3. Developers and Managers still not match the roles. 

**Leantime Version**
2.1.9

**Server**
Apache

**PHP / MySQL Version**
PHP 7.4.26 and Mysql 8.0.29

I really love leantime~  and hope the function will working! thx~ ٩(◦`꒳´◦)۶

**Comment by marcelfolaron** [comment]
A new role system has been implemented
