### ISSUE TITLE
Help - Change the Default time format

### ISSUE THREAD

**Issue by pggsadmin** [Leantime/leantime#732]
Hi,

Recently i started using this application and seems its very nice and thanks to all the team behind this project.

I am having some issue with time format showing in the export option. Is there any settings to change the default time format from MM-DD-YYYY to DD-MM-YYYY

**Comment by phulstaert** [comment]
The MM-DD-YYYY is the American standard, where DD-MM-YYYY is mostly used in Europe (and other parts of the world).

Systems usually use the YYYY-MM-DD format, with is the default format for the date type in XML messages, is a part of the Timestamp format and is the default in ISO 8601 and RFC 3339.

This should be the new default.

Next to this, it might be a nice feature to be able to choose another format and save this in the user profile.

**Comment by marcelfolaron** [comment]
Thanks for pointing that out. That seems to be a bug. We store the date
format in the language files and that should be passed into the export.
Will check what’s going on there

**Comment by VINISHVV** [comment]
@marcelfolaron - Thanks
Modifying language file works fine.

**Comment by pggsadmin** [comment]
Thanks its works.
