### ISSUE TITLE
[BUG] Creating Tasks clears the Page

### ISSUE THREAD

**Issue by MisterNox** [Leantime/leantime#733]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
If I create a new task in the to-dos section I get the formular to fill in all the details (it moves me from .../tickets/showAll to .../tickets/newTicket). When I now click save or save & close the page clears itself after the POST-message and I stay at .../tickets/newTicket and not get redirect back to ../tickets/showAll. And I think this is the problem as the other add possiblities (e.g. at research) use modals in order to show the formulars. By the way, the to-do is created.

**To Reproduce**
1. Go to 'To-Dos'
2. Click on 'New' and then on 'Add To-Do'
3. fill in the details required to create a to-do
4. See error (cleared screen)

I am curious if this is only my problem or wether you can reproduce it.

**Expected behavior**
A redirection to the URL .../tickets/showAll with a success message.

**Leantime Version**
2.1.9

**Additional context**
I use the official docker-compose.yml from https://github.com/Leantime/docker-leantime

**Comment by javaindian** [comment]
> 

Thanks. It worked for me. My issue was leantime always threw an Error 500 whenever i created a new discussion/to-do or project. This qsolved all the problem i faced so far. Still exploring this awesome product.
