### ISSUE TITLE
DEFAULT VIEW IN TASKS [FEATURE]

### ISSUE THREAD

**Issue by paccmx** [Leantime/leantime#740]
**Is your feature request related to a problem? Please describe.**
It is frustrating to always have to change my task layout to table, then sort by milestone...  

**Describe the solution you'd like**
It would be great if there were a way to make this my default view.

**Additional context**
The same issue could apply to the milestone view.

**Comment by marcelfolaron** [comment]
Please chekc if this is still an issue. The table layout is stored in local storage and should stay in tact
