### ISSUE TITLE
[BUG] File could not be uploaded

### ISSUE THREAD

**Issue by a1dot0** [Leantime/leantime#742]
**To Reproduce**
1. Go to 'Project Settings -> Files'
2. Click on 'Select file'
3. Select file and click 'Upload'
4. See error "File could not be uploaded"

**Leantime Version**
2.1.9

**Server**
Apache2

**PHP / MySQL Version**
PHP 7.4
MariaDB 10.5.15

**Comment by marcelfolaron** [comment]
There could be a couple issues why this might be happening.
Do you see any errors in resources/error.log ?

Did you set the fileupload path in the config file?

Are you using S3?

**Comment by a1dot0** [comment]
error.log is empty

I use default path:
   ```
 /* Fileupload */
    public $userFilePath= "userfiles/"; 

    public $dbBackupPath= "backupdb/"; 
```

No, I don't use S3.

**Comment by marcelfolaron** [comment]
I assume you are using linux? What is the owner of the userfiles folder? It
should be set to the apache/nginx user executing the script and the folder
needs to be writable.

**Comment by a1dot0** [comment]
Sorry, my fault. I edit post_max_size and upload_max_filesize in php.ini (increased from 2M to 200M) and all work fine.

**Comment by a1dot0** [comment]
Close

**Comment by marcelfolaron** [comment]
Thanks. Glad it worked out.
This is good feedback though: We should change the error message to reflect
what is going on.
