### ISSUE TITLE
[BUG] idea size doesnt fit to screen

### ISSUE THREAD

**Issue by Stormfinger** [Leantime/leantime#746]
**Describe the bug**
I have open idea page and it doesnt fit the screen. took me some time to scroll down to start new idea

**To Reproduce**
1. Go to Project -> got to idea

**Expected behavior**
Button for idea should be visible and on screen for smaller sized monitors

**Leantime Version**
2.1.7

**Comment by marcelfolaron** [comment]
Thanks for submitting. Can you post a screenshot? I am having a difficult
time fully understanding the issue.

Thanks
