### ISSUE TITLE
[BUG] Timesheet show no Save Button

### ISSUE THREAD

**Issue by KBITSERVICES** [Leantime/leantime#748]
**Describe the bug**
On the Timesheet Page if i edit an Entry there is no Save Button or anything showing up.

**To Reproduce**
1. Go to Timesheet
2. Click on Edit
3. Scroll down to End

**Expected behavior**
I need a Save Button to Save the Change

**Leantime Version**
2.1.9

**Server**
nginx

**PHP / MySQL Version**
PHP 7.3, MySQL 5.7

![Screenshot 2022-06-29 114303](https://user-images.githubusercontent.com/62514189/176405945-f708176a-f997-4b41-96cf-b6fa111dbca7.png)

**Comment by marcelfolaron** [comment]
Not sure what is going on here, but I have a hard time reproducing this. Can you post the html code for that modal?

**Comment by marcelfolaron** [comment]
Correction: Found the issue. Fix is submitted and will go out with the next release
