### ISSUE TITLE
[FEATURE] Allow Embeding Videos in ToDos

### ISSUE THREAD

**Issue by TareqK** [Leantime/leantime#749]
**Is your feature request related to a problem? Please describe.**
Sometimes, when reporting bugs, our QA engineers attach videos of them recreating the scenario.

**Describe the solution you'd like**

 It would be if we can embed videos and not just images when editing Todos using the editor

**Additional context**

https://www.tiny.cloud/docs/plugins/opensource/media/

tinyMCE (which i think is the editor we are using) seems to support this with a OSS plugin

**Comment by marcelfolaron** [comment]
Forgot to close this one. Possible as of 2.2.0
