### ISSUE TITLE
Sometimes jQuery fails to load

### ISSUE THREAD

**Issue by GhaziTriki** [Leantime/leantime#75]
ReferenceError: jQuery is not definedjquery-ui-1.9.2.min.js:6:2
    <anonyme> jQuery

**Comment by marcelfolaron** [comment]
Hey, 
do you have any steps to reproduce this issue?

**Comment by marcelfolaron** [comment]
Will close this for now. Let me know if you still run into this issue.

**Comment by jumblies** [comment]
I get this running behind traefik.  

'''ReferenceError: jQuery is not definedleantime.dokuwiki.lamkerad.com:380:4
    <anonymous> https://leantime.dokuwiki.lamkerad.com/:380'''

**Comment by marcelfolaron** [comment]
Did you set appURL and did you include the protocol (https://)?

**Comment by jumblies** [comment]
Wow.  Thanks for the speedy response to a closed issue.  Completely unexpected.  I have the env var set 
```
         LEAN_APP_URL: 'leantime.TLD.com'
```
I thought I tried 
```
         LEAN_APP_URL: 'https://leantime.TLD.com'
```
at one point and it wouldn't start.  But after reading your comment, it does work.  

Superb response!   Thank you so much.

**Comment by marcelfolaron** [comment]
Glad I could help. I'll make sure to update the docs to include a note
about https://
