### ISSUE TITLE
[BUG] DB Password handling in configuration.php

### ISSUE THREAD

**Issue by EmTeeAge** [Leantime/leantime#750]
Hello,

I've run into this weird issue while installing Leantime but eventually figured it out, however I believe it is not desired behavior, since some people could make the same mistake and I would like to save them a couple of hours of troubleshooting.

Brief explanation:
Using a database password that includes the "$" character in configuration.php results in application error. 

**Steps to reproduce:**
I use password managers to generate my passwords, the one that I got for the installation of Leantime was following:
`PK44#b37Djb#@KDNt$m2$z!V2Je%$Z%%`

I entered this password to _/var/www/leantime/config/configuration.php_ file to the following configuration block:

```
/* Database */
    public $dbHost="localhost"; //Database host
    public $dbUser="leantime_admin"; //Database username
    public $dbPassword="PK44#b37Djb#@KDNt$m2$z!V2Je%$%Z%%"; //Database password
    public $dbDatabase="leantime"; //Database name
```

and created an empty DB and user with the same password.

Unfortunately, after setup, I got a blank page in the browser and error code 500. The favicon appeared in the browser, but the page itself was sending HTTP 500 code.

After changing the password to this:

```
/* Database */
    public $dbHost="localhost"; //Database host
    public $dbUser="leantime_admin"; //Database username
    public $dbPassword="PlVul#euq8DY*K*J#X@2hk0zAhN!Lc3l"; //Database password
    public $dbDatabase="leantime"; //Database name
```

It started working. Vim highlighting actually helped me a lot. Here's a screenshot of the block with the first password
![image](https://user-images.githubusercontent.com/67438185/177021459-3d7661fd-fb55-4545-8d03-a53e216e2d83.png)

and here's with the second password:
![image](https://user-images.githubusercontent.com/67438185/177021473-fed9a4a2-36ec-41e3-b17b-2836c891d2e5.png)

Turns out having a "$" character (haven't found any other) in the password somehow breaks the config. I would assume having the password enclosed in " " would prevent this issue, as all characters within those quotes should be treated the same.

Could you please confirm if this is supposed to happen or not? If it is okay, it should be mentioned somewhere in the docs, so that people know not to use dollar signs in their passwords.

Thank you.

**Comment by EmTeeAge** [comment]
Turns out the issue is even more specific. If $ is followed by a character or number, the application works fine. However, if $ is followed by a letter, it breaks.
e.g.
These passwords would work:
```
uig684fu$%-5fds
8oj4ll$*r5-3a
```

These would not:
```
p45nb$loiu987*4
fdh%$lp-554dfa
```

**Comment by EmTeeAge** [comment]
The same issue applies to other configuration fields in the same file, e.g sessionpassword.

**Comment by qualitycoder** [comment]
Since this is PHP, you could still use the `$` character in your password. Just change the double quotes to single quotes and it should work just fine. The issue is PHP is trying to parse the variables in the double-quoted string.

**Comment by marcelfolaron** [comment]
That is accurate. The content needs to be wrapped an single quotes.

**Comment by EmTeeAge** [comment]
Thank you for the comments guys, I though it had something to do with single quotes vs. double quotes. If that is the case, why not use single quotes in the entire configuration file by default?

**Comment by marcelfolaron** [comment]
You are right, I’ll make sure to update that in
the sample config.
