### ISSUE TITLE
[FEATURE] - To-Do Status - Delete and Add

### ISSUE THREAD

**Issue by funkywaddle** [Leantime/leantime#761]
**Is your feature request related to a problem? Please describe.**
I might be missing it, but currently, I don't see any way to add/remove statuses for To-Do's. I can modify the status name, but adding additional columns or removing columns seems to be missing.

**Describe the solution you'd like**
I would like the ability to add/remove To-Do statuses, not just edit the name. 
(In Kanban view, this would be the columns. In table view, this would be the status)

**Comment by marcelfolaron** [comment]
Hi, 
2.2.0 has two spots to get to the column manager:

1. Go to project settings and select the “To-Do Status Settings” tab
2. On the kanban board click the three dot menu on any of the headlines and select “Add/Remove Columns”

Please let me know if that doesn’t work.

**Comment by funkywaddle** [comment]
I'll have to update to get 2.2.0. 
I only installed it a couple days ago, and I have 2.1.9.
I'll respond here after updating.

**Comment by funkywaddle** [comment]
functionality works great.

The only thing I noticed (and this is extremely minimal) is the alignment of the "Show on Kanban Board" and "Delete" (trash bin) icon for the newly added status.

After refresh, they align perfectly. But right after the "Add Status" link is clicked, everything lines up except for those two elements (see here: [https://projects.qualitycoder.net/images/to-do-status-settings.png](https://projects.qualitycoder.net/images/to-do-status-settings.png))
