### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bragonznx** [Leantime/leantime#763]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Just fater an upgrade from 2.1.9 to 2.2
I've got an erreur : 
[11-Jul-2022 06:37:59 America/Los_Angeles] PHP Parse error:  syntax error, unexpected '|', expecting ';' or '{' in /var/www/leantime-v2.2.0/src/domain/reports/services/class.reports.php on line 121

**To Reproduce**
Upgrade from 2.1.9 to 2.2.0

**Expected behavior**

**Leantime Version**
From 2.1.9 to 2.2.0

**Server**
nginx

**PHP / MySQL Version**
PHP 7.4.28
10.5.15-MariaDB

**Comment by marcelfolaron** [comment]
Thanks for the report. Leantime 2.2 requires PHP 8.0+
From you configuration it seems you are running php 7.4

Please update the PHP Version to resolve this issue.
