### ISSUE TITLE
[BUG] Logging on the mobile device logs me out from computer and vice versa

### ISSUE THREAD

**Issue by AbraxasDMG** [Leantime/leantime#765]
Locally hosted on Apache. Version 2.2.0.

I log in via desktop browser. Everything works ok on the desktop.
I log in via mobile phone. Everything works ok on the mobile phone but I am logged out from the desktop (whatever I click on the desktop I get redirected to login page).
I then log in via desktop again. Everything ok on the desktop but I am logged out from the mobile....

**Comment by marcelfolaron** [comment]
Thanks for filing. This is expected behavior at this point. We only allow one active session per user. 
I'll change this to a feature request as I believe we should allow multiple active sessions.

**Comment by ftrueck** [comment]
It is not only affecting mobile/browser combination. It is also when you want to have multiple tabs in one browser. Currently this is not possible as current project (page) are session global which means you can not have opened 2 projects at once. This would improve usability greatly if this would work. For a project manager it is also handy: one window shows the time sheets and the other the projects.

**Comment by marcelfolaron** [comment]
Fixed in the latest version
