### ISSUE TITLE
[BUG] No profile icon/menu visible in portrait mode on Samsung Galaxy S21 

### ISSUE THREAD

**Issue by AbraxasDMG** [Leantime/leantime#766]
Locally hosted on Apache. Version 2.2.0.

On my phone, in portrait mode (1080 x 2400 pixels) I can't see the profile icon/menu (so I can't access any of the items there, including logging out).
In landscape mode I see the icon but the menu cannot roll past the Administration subsection of the menu, which, effectively, makes it impossible to log out of the app on mobile, unless you active temporarily "desktop mode" in the mobile browser.

**Comment by marcelfolaron** [comment]
Thanks for reporting. Will take a look
