### ISSUE TITLE
[FEATURE] Import of To-Dos from csv or xls would be helpful while migrating from a manual excel sheets.

### ISSUE THREAD

**Issue by javaindian** [Leantime/leantime#767]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by marcelfolaron** [comment]
Thanks. Would you mind sharing some more details, or anwering questions:

1. What do you want to import? To-Dos? Projects? Ideas? Timesheets? Lean Canvas? 
2. If you import todos over multiple projects, how would you want to map that in the CSV? Project Name or is project id okay?
3. Do you need to map milestones? Or subtasks? Eg any type of hierarchical relationship between To-Dos? 
4. How would you want to map users? All to one user? Map by email address? Map by name? 

There are probably more questions :D but this could get me started.

**Comment by javaindian** [comment]
Sorry for the delayed response @marcelfolaron. Initially, I would like to go with import of ToDos of a single project with Project Name being primary key.

**Comment by TareqK** [comment]
@javaindian  For what its worth, when we did this(from jira to leantime), all we did was import the CSV into MYSQL directly by renaming the headers, setting the ticket statuses and types using the Ids in the db, and adding a projectId column. 

But I 2nd the need for an Import

**Comment by gloriafolaron** [comment]
@TareqK @marcelfolaron is this the same thing in the threads yesterday in discord -- for CSV imports of tasks for repeating?

**Comment by marcelfolaron** [comment]
CSV Import was introduced a few versions ago. Closing this issue

**Comment by rockygiglio** [comment]
> CSV Import was introduced a few versions ago. Closing this issue

where is the import function? I am on 3.7.3 and don't see it anywhere? Sorry if I am being dense

**Comment by rockygiglio** [comment]
> > CSV Import was introduced a few versions ago. Closing this issue
> 
> where is the import function? I am on 3.7.3 and don't see it anywhere? Sorry if I am being dense

found it! Go to Company on the top menu, then to Integrations under Administration on the left, and it shows up there.
