### ISSUE TITLE
[FEATURE] Moving task from One project to another

### ISSUE THREAD

**Issue by javaindian** [Leantime/leantime#768]
I made a mistake of manually feeding tasks (in tens) to Project A instead of Project B.

I had to delete those tasks and recreate them in Project B.

Instead, if it was possible just to switch the task from Project A to Project B would have helped a lot.

**Comment by marcelfolaron** [comment]
Thanks for the feature request. Fully agree, we need to move things between projects. Not just tasks but also ideas and other items.

**Comment by javaindian** [comment]
Thanks for understanding the impact @marcelfolaron
