### ISSUE TITLE
issue with docker leantime

### ISSUE THREAD

**Issue by killmasta93** [Leantime/leantime#769]
Hi
Currently installed leantime on docker, the issue is that everytime i try to update something i keep getting http error 500.
but after i refresh the page and it works again 

![image](https://user-images.githubusercontent.com/13953629/177019205-c9931b01-b0a3-415f-b971-e06c0818ae9b.png)

i tried editing the app URL to http://192.168.7.147:8087 but keeps showing the error 

i checked the logs and i found this

![image](https://user-images.githubusercontent.com/13953629/177019254-d0c24419-39d6-4721-8302-4881df569b4f.png)

Thank you

**Comment by phulstaert** [comment]
Hi @killmasta93, is this still an issue?
If yes: what version do you use? 
We used to have an issue where you got an error 500 on every action that would send an email if you did not include the LEAN_EMAIL_RETURN. (even if you did not configured the mailing system).

docker run -d -p 80:80 --network leantime-net \
-e LEAN_DB_HOST=mysql_leantime \
-e LEAN_DB_USER=admin \
-e LEAN_DB_PASSWORD=321.qwerty \
-e LEAN_DB_DATABASE=leantime \
**-e LEAN_EMAIL_RETURN=changeme@local.local \**
--name leantime leantime/leantime:latest

Could you verify this error is not the issue?

**Comment by killmasta93** [comment]
Hi @phulstaert thank you for the reply, currently i switched to openproject thank you again
