### ISSUE TITLE
install (production) page not found

### ISSUE THREAD

**Issue by adnredwan77** [Leantime/leantime#77]
I've followed these instructions:
Installation (Production)
Download latest release package
Create an empty MySQL database
Upload entire directory to your server
Point your domain to the public/ directory
Rename config/configuration.sample.php to config/configuration.php
Fill in your database credentials (username, password, host, dbname) in config/configuration.php
Navigate to <yourdomain.com>/install
Follow instructions to install database and set up first user account
*********************
But when navigate to  <mydomain>/install it returns 404 Page not found

**Comment by quangbahoa** [comment]
Are you running apache or nginx? Did you point root to /public ?

**Comment by mamour666** [comment]
hello have same problem i am running apache

**Comment by adnredwan77** [comment]
I'm using windows shared host on Plesk,
So after installing PHP composer and package dependencies it works fine.
But I don't know how to log in what's the default user credentials?

**Comment by marcelfolaron** [comment]
Hi, 
If you downloaded the release package from https://github.com/Leantime/leantime/releases (files named with version number) you shouldn't have to install composer or npm. 

Is it possible that you downloaded the source.zip? This is the developer source code that requires a composer and npm build (and then grunt executions). 

We haven't had the chance to verify an installation on Windows yet. I assume you are still using apache or nginx and not IIS?

If you see the login screen you should be able to navigate to <yourdomain>/install and install the database. This will allow you to create credentials.

**Comment by quangbahoa** [comment]
@mamour666 @adnredwan77  You must follow install instructions. That error mean you're not point root dir to /public dir. (https://help.leantime.io/article/show/97350-installing-leantime)
 For example document root `/var/www/leantime/` 
- Apache edit `DocumentRoot` to `/var/www/leantime/public`
- Nginx edit `root` to `/var/www/leantime/public`

**Comment by adnredwan77** [comment]
Hi, it works for me 
but now I can not log in and did not know what is the default credentials

**Comment by adnredwan77** [comment]
Hi, 
I've pointed the root dir to /public, also following the instruction in the link:
[https://help.leantime.io/article/show/97350-installing-leantime](https://help.leantime.io/article/show/97350-installing-leantime)
but when I navigate to <mydomain>/install I get the error 

404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.
Although I can see the log in screen when I navigate to may domain

**Comment by adnredwan77** [comment]
Hi, I've created the database from class.install.php file, I copied the create statements and run it on the database , after that copy the insert statments and run it on the database one by one
and change the parameters with suitable values,
I've inserted user in zp_user table 
and try login but it fails also

**Comment by quangbahoa** [comment]
@adnredwan77  happy new year. Can you share your site url?

**Comment by Lucifer-Clegg** [comment]
Hello,
is there now a solution?
I've got the same problem (404 - File or directory not found.)
with install on synology.

regards

**Comment by marcelfolaron** [comment]
Hey,

This is usually due to missing configurations on apache.
Same questions as above: 

1. Did you point the domain to the /public folder within Leantime?

The virtual host config should look similar to this:

```
<VirtualHost *:80>
    DocumentRoot "/domainpath/leantime/public"
    ServerName www.servername.com
    # Other directives here
</VirtualHost>
```

On Synology: How are did you set it up? Using docker or a VM? 
When using docker you'll have to make sure to change the port. Synology is using port 80 for the management console.

**Comment by Lucifer-Clegg** [comment]
Hello,
Q1: Yes, in Synology 'web-station' I set the 'virtual host' as you mention it (in my case web
/leantime/public)
Q2: Yes, according to Synology's indications 'mod_rewrite' is activated.
![webstation](https://user-images.githubusercontent.com/57875690/74592487-4251f900-5022-11ea-8f22-8633a19d1c01.jpg)
Other settings I don't see (know)

greetings

**Comment by marcelfolaron** [comment]
I see. Did you make sure "leantime" is defined in your DNS settings? 
Depending on your local set up this can be set up on your router or locally in your hosts file:

On windows navigate to: C:\Windows\System32\drivers\etc\hosts
And add the line (replace <synology ip> with the ip of your synology server , most likely something like 192.168.xx.xx)
<synology ip> leantime

You will need to open the host file as administrator using notepad (right click notepad and click "Run as administrator")

On linux the hosts file is in /etc/hosts. The process is the same (just use sudo)

I have a synology nas as well and this is how I have it set up. (Make sure you have a mysql database available as well)

**Comment by Lucifer-Clegg** [comment]
so,
- hosts file edited -> brings no change
- Mysql db is created (also before) 
- Mysql (MariaDb) is set on port 3307, I've tried meanwhile 3306 -> with no changes
...can't be that difficult

regards

**Comment by marcelfolaron** [comment]
Can you try to run "ping leantime" in a command line to see if you can reach the synology server? 
It might be a firewall setting as well

**Comment by Lucifer-Clegg** [comment]
as you say
```
Ping wird ausgeführt für leantime [192.168.x.x] mit 32 Bytes Daten:
Antwort von 192.168.x.x: Bytes=32 Zeit<1ms TTL=64
Antwort von 192.168.x.x: Bytes=32 Zeit<1ms TTL=64
Antwort von 192.168.x.x: Bytes=32 Zeit<1ms TTL=64
Antwort von 192.168.x.x: Bytes=32 Zeit<1ms TTL=64
```

**Comment by marcelfolaron** [comment]
So that's good. It is finding the server. It could be that the response in
your browser is cached from the previous request. Can you open an incognito
window and try to connect to http://leantime

**Comment by Lucifer-Clegg** [comment]
uhm... 

`No databsae connection, check your database credentials in your configuration file`
there is definitive a database and a user
DB: dbleantime
User: usrleant
and this user neds only the rights for this DB, right?
Or are some other entries intended?

**Comment by marcelfolaron** [comment]
Great, at least we are connected to the server now :) 

In the configuration file you will need to set the dbHost (which should be IP of your synology box). 
dbUser and the db name (and password of course). You are right the system only needs access to the one database.

Make sure MySQL runs under port 3306 (synology and MariaDB 10 will try to run under 3307, that is currently not supported)

**Comment by Lucifer-Clegg** [comment]
> set the dbHost (which should be IP of your synology box)

Well, as the dbHost I used to set the host, which is set in the db, there is 127.0.0.1 (the localhost)
I changed the port to 3306 and still
`No databsae connection, check your database credentials in your configuration file`

I'm starting to get a little bit annoyed... only a bit ;-)

**Comment by Lucifer-Clegg** [comment]
stop... I'm in!
seems it was still the port 3307 that has to change... probably takes a while
But my other Mysql/PHP things runs at port 3307 how get I them to run again...?

**Comment by marcelfolaron** [comment]
Totally understandable. The set up on Synology Nas is a little more complex. 

You can't use localhost (or 127.0.0.1) because the web server (via web station) doesn't actually run on within the scope of the same host (it runs as a virtual machine). The way to connect to the db is to use the ip of your synology machine 192.168.x.x

**Comment by marcelfolaron** [comment]
So I just checked again and you may be able to run leantime under a different port using 
$dbHost="<ip>:3307"

I don't think we have 3306 hard coded anywhere which means this should work. (I'll double check this weekend)

**Comment by Lucifer-Clegg** [comment]
Wow... yeah, that works. So I can my port leave it as it is
by the way... good work and what a patience.
What makes me curious is, why  the other aplications work over dyndns.
They have the same entries in Virtual Host of the DS...

**Comment by marcelfolaron** [comment]
Glad it works, happy to help.
Yeah the dyndns issue is odd. I'll give that a try on my set up as well and
see if I can spot anything.
