### ISSUE TITLE
Forces https redirect

### ISSUE THREAD

**Issue by jackgray** [Leantime/leantime#771]
I have spent a couple days now trying to get a minimum viable installation of Leantime, and I don't have certificates configured yet.

Why is it redirecting my url (projects.mydomain.com) to https? Even when I type the full path with http it forces https. I can't find anywhere in the config files any mention of port 443 or https redirects. 

I've tried just about every different docker way I can think of following this readme and leantime docs, and am starting to wonder if this current version is even passing? Running multiple services behind Traefik, and the others are all working.

**Comment by phulstaert** [comment]
Hi Jackgray, do you still need assistance regarding this issue?
