### ISSUE TITLE
websocket is not working on a Synology NAS

### ISSUE THREAD

**Issue by mariushosting** [Leantime/leantime#773]
Even if websocket is activated this not work with HTTPS on a Synology NAS.

**Comment by marcelfolaron** [comment]
Not sure how websockets come into play here. Can you elaborate more on the problem?

**Comment by mariushosting** [comment]
> Not sure how websockets come into play here. Can you elaborate more on the problem?
Related to issue #821 
https://github.com/Leantime/leantime/issues/821

This bug was present since the old version is now solved in #821

**Comment by marcelfolaron** [comment]
Thank you!
