### ISSUE TITLE
Mount volume(s) for config, userfiles, log

### ISSUE THREAD

**Issue by tet3** [Leantime/leantime#779]
Suggest closing Leantime/docker-leantime#8, where the original issue seems to be fixed. 

But you do need README and `docker-compose.yml` to reflect setting up volume(s) for files that need to be accessed outside the container or will change but should survive an image rebuild. Putting the whole of `\var\www\html` per @marcelfolaron 's last comment on 8 isn't right, because that's got `src`, `vendor` and other stuff that should definitely be fully inside the container fs. But volumes for config, userfiles (why are there both `/var/www/html/userfiles` and `/var/www/html/public/userfiles`?) and `/resources/logs` are needed. Is there anything else that changes during normal running, that couldn't be deleted and recreated on a version upgrade?

**Comment by gotjoshua** [comment]
> is there other setting

this is not really a setting, but rather a docker convention (what i call a limitation):
named volumes are pre populated from the docker image folders on the first container up.
mounted `/local_dir/`s are not.
You can monkey patch this by mounting elsewhere and manually copying the contents of the container folders into your folders.
OR you can use https://github.com/MatchbookLab/local-persist

good luck
