### ISSUE TITLE
[BUG] Error 500 after 2.20 update

### ISSUE THREAD

**Issue by EHRETic** [Leantime/leantime#783]
**Describe the bug**
Getting an ERROR 500 when I update from 2.19 to 2.20

**To Reproduce**
1. Replace all the files in leantime folder as stated in help
2. Refresh main page or try /update or /install
3. See error 500, no connectivity

**Expected behavior**
Working update 😉

**Leantime Version**
From 2.19 to 2.20

**Server**
nginx

**PHP / MySQL Version**
PHP 7.4.30-1 and MariaDB 3:10.3.32-2 

**Additional context**
Not a docker installation but dedicated VM on Almalinux 8.6 (and I can revert snapshot whenever I want to reproduce the problem)

**Comment by marcelfolaron** [comment]
Hi,

Thanks for the report.
Seems you are using PHP 7.4
We dropped support for 7.4 with 2.2.
Please update to 8.0+ That should fix the issue.

**Comment by EHRETic** [comment]
> No worries. I don’t have much experience with Almalinux but this guid makes it sound like you may want to remove 7 first before installing 8? https://www.linuxcapable.com/how-to-install-php-8-1-on-almalinux-8/

Well, after some nightmare tries again... I understood that I was already using REMI repository and PHP update could be done in one line which is:

`dnf module switch-to php:remi-8.1`

So much easier... And Leantime update with file copy worked like a charm after that.

So if it can help anybody, I'll be happy! 😉

**Comment by thewriteway** [comment]
to fix the php dependency issue on raspberry bullseye you can follow this article : https://pimylifeup.com/raspberry-pi-latest-php/
