### ISSUE TITLE
[BUG] Left panel empty

### ISSUE THREAD

**Issue by hitodev** [Leantime/leantime#787]
**Describe the bug**
Left panel suddenly empty

**To Reproduce**
Open left panel

**Expected behavior**
Should show menus

**Leantime Version**
2.2 Stable

**Server**
Apache

**PHP / MySQL Version**
8

**Additional context**
The bug appear after having added some clients.

**Comment by marcelfolaron** [comment]
Can you update to 2.2.3. I believe this should be fixed with that version
