### ISSUE TITLE
Release 2.0.4 break nginx redirection

### ISSUE THREAD

**Issue by GhaziTriki** [Leantime/leantime#79]
After updating to version 2.0.4 I get a HTTP error 404 when doing `/update`. Did the server config change for this new version?

**Comment by marcelfolaron** [comment]
Hi, yes a new rule was added. This should be the last rule change I can foresee. We'll need to see if we can refactor the htaccess/nginx redirects to avoid these hardcoded values.

```
 location = /update {

      rewrite ^(.*)$ /index.php?update=true;
  }

  location /update {

     rewrite ^/update/([^/\.]+)/?$ /index.php?update=true;
  }
```

**Comment by marcelfolaron** [comment]
Come to think of it. Really the entire installation and update flow + password reset will need to be changed and moved into src/domain/* but that means we'll need to make updates to the frontcontroller and login handler.

**Comment by marcelfolaron** [comment]
Let me know if that fixes the issue.

**Comment by GhaziTriki** [comment]
I updated the nginx config and it works.
