### ISSUE TITLE
textarea error!!!! 

### ISSUE THREAD

**Issue by quocnho** [Leantime/leantime#80]
Can not write as html entry. 
Version 2.0.3 is okie but version 2.0.4 has error
<textarea name="details" id="details" class="tinymce" rows="5" cols="50"><?php echo $project['details'] ?></textarea>
It's show: 

> `<strong>Summary</strong><br /><i>{{Describe the project in a few words}}</i><br /><br/><strong>Business Justification</strong><br /><i>{{Why are you doing this project?}}</i><br /><br/><strong>Objectives/Goals</strong><ul><li><i>{{What are your goals with this project?}}</i></li></ul><br /><br/>  `

**Comment by marcelfolaron** [comment]
I'll take a look.

**Comment by marcelfolaron** [comment]
Can you let me know how you got to that error? I can't reproduce it. This seems to be happening for you on the "Create Project Screen"? Do you see the editor at all?

**Comment by quocnho** [comment]
I have checked again and know that it is okie!
Thanks for your support

**Comment by marcelfolaron** [comment]
Thanks for the update!
