### ISSUE TITLE
Fit kaban board columns to the window width at window resize

### ISSUE THREAD

**Issue by GhaziTriki** [Leantime/leantime#82]
![image](https://user-images.githubusercontent.com/4991088/71631764-b66b4580-2c0a-11ea-972c-da2e133041c0.png)

**Comment by GhaziTriki** [comment]
After updating to 2.0.5, this issue is still visible. I am using Firefox.

**Comment by marcelfolaron** [comment]
Should be fixed now. Let me know if not
