### ISSUE TITLE
[BUG] Sub-Tasks are not saved

### ISSUE THREAD

**Issue by michael-schramm** [Leantime/leantime#820]
I created a task and now want to create a sub-task but the sub-task is not being created:

![image](https://user-images.githubusercontent.com/45664277/180949631-685bed6b-237b-4e15-bbe0-ed561ac6791f.png)

Instead a blank message window is being shown:

![image](https://user-images.githubusercontent.com/45664277/180949803-15a5083f-3781-4d6c-8548-76e5dc36615b.png)

Sometimes the blank message window does not show up. It seems the subtask has been created but when I open the task again, there is no subtask at all.

I am using Firefox.

Leantime version 

**Server**
Apache
PHP 8.1

**Comment by michael-schramm** [comment]
Leantime version 2.2.0
BTW: where can I check this? In the past version this info could be found in the footer of the app. Now it's not there anymore.

**Comment by marcelfolaron** [comment]
Thanks, I’ll take a look at that.

**Comment by b3belov** [comment]
Same issue is with uploaded files.

**Comment by npgretz** [comment]
I am also experiencing the same issue with saving subtasks. When I click save on the subtask the POST method returns status 302 and the modal for subtasks becomes the view for "showKanban" even though the URL is "showKanban#subtasks". I get a modal of the "showKanban" view overlaid on the "showKanban" view page.

I used the docker-leantime installation through docker compose:
MySQL Server 5.7.39-1.el7
Leantime V2.2.0

If you need more information or help reproducing the error, I can offer some of my time.

**Comment by marcelfolaron** [comment]
Thanks folks. I have identified the bug and will release a fix today.

**Comment by Treuman** [comment]
Also does not save files on the tasks tab.
_addition: the company logo is not displayed, although the link to the file from the s3 storage is visible through the code_
leantime v.2.2.3+apache 2+mariadb 10.6.8

**Comment by marcelfolaron** [comment]
Fixed in 2.2.4
