### ISSUE TITLE
[BUG] White Settings Menu, strange page format

### ISSUE THREAD

**Issue by mariushosting** [Leantime/leantime#821]
The menu settings is white, Can't read anything. There is strange page format.
![nowork](https://user-images.githubusercontent.com/37554361/180981324-ebfec6b2-f521-4a98-b874-357ea5f33fa5.png)

**Comment by marcelfolaron** [comment]
Is this a new install or an update? Did you use the release package or
development version off of master?

It seems that a lot of the Stylesheets are missing.
Any errors in resources/logs/error.log?

**Comment by mariushosting** [comment]
There is no errors in the log. Everything seems to be ok.

**Comment by Memurame** [comment]
It looks exactly the same to me. I also tried a fresh install. But it always looks like the photo above.

**Comment by marcelfolaron** [comment]
Thanks. I assume it is the latest version 2.2.2?
Also is this via docker or the regular version?

Any errors in the inspector?

**Comment by Memurame** [comment]
No errors in the Log.
I have the regular version.

You can see the page on https://projects-update@hirter.dev

**Comment by mariushosting** [comment]
Yes latest version 2.2.2
New fresh install version, no upgrade. There is some missing Stylesheets.

web page: https://leantime.mariushosting.synology.me

**Comment by Memurame** [comment]
Ok, the Error ist only in release Version. I stalled a new instance of development Version. It works fine.

**Comment by marcelfolaron** [comment]
Ah, I see. I didn't realize this bug was so pervasive. For a quick fix, can you make sure that config/appSettings.php has debug set to 0. That might fix it already.
Otherwise I will push a new release today with that fix.

**Comment by mariushosting** [comment]
Thank you, waiting for the new release!

**Comment by Memurame** [comment]
My debug setting was already set to 0.
Thx

**Comment by marcelfolaron** [comment]
Kk, I’ll ping you all once the new release is out.

**Comment by marcelfolaron** [comment]
Just released a new version. Please check and let me know if that fixed the issue.

**Comment by mariushosting** [comment]
> Just released a new version. Please check and let me know if that fixed the issue.

Works like a charm! Thank you!

**Comment by marcelfolaron** [comment]
What errors show up in the inspection console (F12)
