### ISSUE TITLE
Better image quality for the logo

### ISSUE THREAD

**Issue by GhaziTriki** [Leantime/leantime#83]
The current compression ratio is too high for the logo and the quality is not very good. Could we improve it please?

![image](https://user-images.githubusercontent.com/4991088/71972442-eb7c2700-320c-11ea-8c01-691be393524a.png)

**Comment by GhaziTriki** [comment]
The image quality is still not good enough. Thanks.

![image](https://user-images.githubusercontent.com/4991088/72877132-83434000-3cf8-11ea-8d15-a4359db511fb.png)

**Comment by marcelfolaron** [comment]
Hi,

Would you mind sending me the image you are using to support@leantime.io so
I can take a look?

One thing to keep in mind is that the image has to be at least 260px wide
and 60px high.

If it's smaller the tool will upscale to that size causing quality issues.
