### ISSUE TITLE
Logo not visible

### ISSUE THREAD

**Issue by Treuman** [Leantime/leantime#834]
Can't load company logo from S3 storage
error(Chrome console): Failed to load resource: the server responded with a status of 403 (Forbidden)
DevTools failed to load source map: Could not load content for https://company.org/css/components/bootstrap-grid.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Files in tasks are saved and downloaded to and from S3 storage

Leantime Version 2.2.4
Apache 2.4.37 
PHP 8.0.21
MySQL 10.6.8-MariaDB

![image](https://user-images.githubusercontent.com/39520485/182238952-cbf4c8e5-129e-4daf-add9-5a3316b64b55.png)
![image](https://user-images.githubusercontent.com/39520485/182237415-27bb30d1-fcc6-45a1-8ca7-c46b5c7f419e.png)
![image](https://user-images.githubusercontent.com/39520485/182237597-85377361-62fc-4fcf-8eca-70d31611af86.png)

**Comment by marcelfolaron** [comment]
Thanks for submitting a bug. The source map bug is not a big deal and
wouldn't cause the S3 error. I'll take a look and see whats going on, but
from the error message it sounds like S3 is not allowing access. Now I'll
check if that has something to do with how we upload the file and set
permissions or not.
In the meantime you could make that file public in your S3 bucket to
resolve that issue

**Comment by Treuman** [comment]
I tried the account in S3 using root (S3). Must have rights to all actions. As an option: when requesting a picture, the identification of keys is not transmitted?

**Comment by marcelfolaron** [comment]
Is this still an open issue?
