### ISSUE TITLE
[FEATURE] - Changes required in My Calendar.

### ISSUE THREAD

**Issue by VINISHVV** [Leantime/leantime#839]
**Is your feature request related to a problem? Please describe.**

In calendar view all the tasks with due date is showing, But its difficult to understand whether the task is completed/in progress etc..

If we can incorporate the status then this would be really helpful,

**Describe the solution you'd like**

Using different color code for each task based on its current status, for example if a task is completed then it should be shown in green colour,

If any task its pending and due date is completed then such entries shown in RED colour.

**Comment by HugoGon** [comment]
That would be great. It's important to me to have access to the completed tasks in the calendar.

This solution in #340 used to work for a while, but with a recent code change that is no longer an option.

**Comment by marcelfolaron** [comment]
Added done tasks as well as task status in 2.3.21
