### ISSUE TITLE
[BUG] Release zip is buggy

### ISSUE THREAD

**Issue by phulstaert** [Leantime/leantime#841]
The release zips are not consistent, and for the last 3 versions they do not work within Windows explorer. (only 7z or others)

2.2.0 => content is directly multiple folders and the nginx.conf files and so on (later i will call these the app files)
2.2.1 => leantime folder; within that folder you see the app files.
2.2.2, 2.2.3, 2.2.4 => do not open in Windows explorer; in 7z you see a folder leantime; in that folder you have a folder ".". In that folder you see the app files.

![Leantime zip error](https://user-images.githubusercontent.com/8971696/182601323-e6e0f371-b3c4-48b0-a046-1d3556041f87.png)
i

**Comment by marcelfolaron** [comment]
Thanks for reporting this. I started scripting the release package creation
and it seems something is not right. I’m on mac. Will do some windows
testing.

**Comment by marcelfolaron** [comment]
If you want to check it out, it’s this file:
https://github.com/Leantime/leantime/blob/master/createReleasePackage.sh

**Comment by phulstaert** [comment]
Done.
https://github.com/Leantime/leantime/pull/842

**Comment by marcelfolaron** [comment]
Thank you!

**Comment by phulstaert** [comment]
Small question; does a mac have awk? It might be nice to pull the version directly out of the config php file.

**Comment by phulstaert** [comment]
If you think it would be nice to have the version automatically:
https://github.com/Leantime/leantime/pull/843

**Comment by phulstaert** [comment]
Could you update the release zip's with working versions? I have included working versions [here](https://drive.google.com/drive/folders/14Ll5_8Gbn0O7hyjVmYBabWCZBat9nOLx?usp=sharing).
Contents of files are not touched, I only fixed them.
