### ISSUE TITLE
[BUG] jQuery initiates LOTS of PATCH requests to index.php while resizing

### ISSUE THREAD

**Issue by phulstaert** [Leantime/leantime#852]
When a user resizes a window, jQuery sends out a lot of PATCH HTTP requests. (between 8 and 12 per second per user)
Because of this, I receive lots of "server reached pm.max_children"-warnings.

**To Reproduce**
1. Open Leantime
2. Either look at the HTTP servers logs or at the development tools network tab in google chrome.
3. Resize the window
4. see a lot of requests

![image](https://user-images.githubusercontent.com/8971696/183306936-6e5fa96c-42a8-4282-a997-a9ec7ea14883.png)

**Expected behavior**
I don't know what they do, but we have to throttle this to once a second max.

**Leantime Version**
2.2.4 - Docker-compose version

**Additional context**
When a hand full of people are using the system, this could be ignored, but in bigger settings, this would slow everything down.

**Comment by marcelfolaron** [comment]
Woah, that is weird. Is that on the kanban screen? Do you know what is
being patched?

My first guess is that sortable() is being triggered on a resize() which in
turn sends a patch to update ticket status. I’ll check it out.

**Comment by phulstaert** [comment]
Every page, all the time (with and without a modal screen active)

**Comment by phulstaert** [comment]
Well... not all the time... only when resizing :-D

**Comment by phulstaert** [comment]
![image](https://user-images.githubusercontent.com/8971696/183309835-79708bfc-72d8-4ae9-a9a0-caa35b4033ef.png)

**Comment by marcelfolaron** [comment]
Found it. It's in the menu controller javascript that stores whether the
left menu is open or not.
https://github.com/Leantime/leantime/blob/0d8ec77ae78654191553f0b62ce204e1859487d8/src/domain/general/js/menuController.js#L71

I can't believe no one found that before. This has been working this way
for a very long time. (3 years based on git blame)

Good catch!

**Comment by phulstaert** [comment]
Glad I can be of help.
You really found that fast :-)

**Comment by phulstaert** [comment]
Maybe this type of solution might help?

https://stackoverflow.com/questions/5489946/how-to-wait-for-the-end-of-resize-event-and-only-then-perform-an-action

The easiest of them all is [this one](http://jsfiddle.net/mblase75/fq882/197/).
This comes down to "if you stop resizing for x ms; do something". So this is kind of an 'end resize' event.

**Comment by marcelfolaron** [comment]
huh, yeah I see it now. It sends requests to api/session . Now let me find
the culprit.

**Comment by marcelfolaron** [comment]
Well I just searched for ".resize("  :D
