### ISSUE TITLE
Warning in form fields when creating a new user

### ISSUE THREAD

**Issue by GhaziTriki** [Leantime/leantime#86]
I have leantime with PHP 7.4, in the 4 first fields I can see the following message

```
<br /><b>Notice</b>:  Trying to access array offset on value of type null in <b>/var/www/leantime/src/domain/users/templates/newUser.tpl.php</b> on line <b>92</b><br />
```

**Comment by GhaziTriki** [comment]
I also see this in projects fields

![image](https://user-images.githubusercontent.com/4991088/71988661-90f4c200-3230-11ea-955b-0e2277516c29.png)

**Comment by GhaziTriki** [comment]
I think it is general issue in templates.
I don't see the project name in emails 

![image](https://user-images.githubusercontent.com/4991088/71989256-9bfc2200-3231-11ea-920d-c91fcf7d6c23.png)

**Comment by marcelfolaron** [comment]
Thanks, I'll take a look

**Comment by GhaziTriki** [comment]
A similar issue is here https://github.com/laravel/framework/issues/30737 and here https://git.zabbix.com/projects/ZBX/repos/zabbix/commits/8ccc854fb32e7e3e20e9e455f26236fc243dac38

**Comment by marcelfolaron** [comment]
I just realized that this is a warning introduced with PHP 7.4. I know what's going on and will fix that shortly.
