### ISSUE TITLE
[BUG] - To-Do with table content corrupts kanban board status layout 

### ISSUE THREAD

**Issue by fcelis** [Leantime/leantime#873]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
When writing the description of the To-Do that includes a table after saving the To-Do the Kanban board layout is changed. 
The To-Do stays within the status assigned and all status to rights get moved inside the current status and are no longer visible.

**To Reproduce**
1. Go to your project
2. Click on on To-Dos ( make sure you are in kanban view ) 
3. Click on "New" 
4. Fill up the form 
5. In Description textarea input enter description 
6. Click on "Insert" and select table with 4 rows and 2 columns 
7. Populate the table any content 
8. Click Save & Close
9. See the error 

**Expected behavior**
The To-Do should display and all the kanban status should be visible 

**Leantime Version**
2.2.1

**Server**
NGINX 1.18.0 

**PHP / MySQL Version**
PHP 7.4.26  
MySQL 8.0.30

**Additional context**
![Screen Shot 2022-08-16 at 10 03 59 PM](https://user-images.githubusercontent.com/1025750/185018728-1c38adf2-3c64-4a26-a0ed-39367e980c21.png)

**Comment by marcelfolaron** [comment]
Hi, thanks for reaching out.
This issue was resolved in 2.2.3 I believe.
Can you update to 2.2.4 and let me know if the issue persists? (Php8 is
required)
