### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by siccl** [Leantime/leantime#883]
some files have a residual documentation / code

https://github.com/Leantime/leantime/blob/master/src/domain/users/repositories/class.users.php
public function  sendAnonymousTelemetry()**: bool|PromiseInterface**

https://github.com/Leantime/leantime/blob/master/src/domain/users/repositories/class.users.php
public function getLastLogin() **:string|null**

**To Reproduce**
Install from zero
review logs o enable debug
PHP Parse error:  syntax error, unexpected '|', expecting ';' or '{'

**Leantime Version**
2.2.4

**Server**
nginx, php-fpm, ubuntu

**PHP / MySQL Version**
7.4.3-4ubuntu2.12 amd64 / Mariadb 10.6.7-2ubuntu1.1 amd64

I remove this from the code and application work fine and beautiful

**Comment by marcelfolaron** [comment]
That is not a bug. 
The multiple return types is something PHP8 introduced and we want to use moving forward. Leantime need PHP8 as of 2.2.1. Support for 7.4 has ended. https://platform.sh/blog/2020/php-80-feature-focus-type-improvements
