### ISSUE TITLE
[BUG] Project Discussion posts don't get saved

### ISSUE THREAD

**Issue by Georacer** [Leantime/leantime#893]
Hello everyone! Thanks for open sourcing this project, I'm trying it out. I have the following bug:

**Describe the bug**
I cannot make a post in the Project Discussion. To-Do discussion do work.

I am on a Docker-Compose installation.

**To Reproduce**
1. Go to 'Project Settings'
2. Click on 'Discussion'
3. Type a new post and click 'Save'
4. At first nothing happens
5. Click 'Save' again
6. A clock appears but never disappears
7. Clicking anywhere outside resets the screen and cancels the post
![image](https://user-images.githubusercontent.com/3149996/185764846-1161a329-3e93-4caa-b82e-74d46cb27c2e.png)

**Expected behavior**
I was expecting posts to go through, show-up and persist.

**Leantime Version**
I cloned the Docker Compose project from this commit: https://github.com/Leantime/docker-leantime/commit/556e56393dd33b728514ef237563e430b6fe680e

**Additional context**
I modified the database service in `docker-compose.yml` with
``    user: "${UID}:${GID}"``
to gain access to the generated files and sync them with Dropbox.

Thanks in advance!

**Comment by marcelfolaron** [comment]
Hi,
thanks for submitting that. I just found that bug yesterday as well. I have a fix in master and it will be out with the next release.

**Comment by Georacer** [comment]
Nice! Do the stable Docker images get updated regularly? Or do I have to switch my docker compose file to a "latest version"?

**Comment by marcelfolaron** [comment]
They get updated with a new release.
Ill create a new release package today which will update docker.
