### ISSUE TITLE
MySQL SSL connection required

### ISSUE THREAD

**Issue by leogaggl** [Leantime/leantime#899]
I have been trying to find any information on how to change the SSLMode of the database connection using a docker image to connect to a database server that is configured with SSLMODE=required.

I can connect to the database from the docker container and credentials using the --ssl flag in the MySQL CLI.

There does not seem to be any way to use either ENV variables (there is no DB_SSL_MODE) or the configuration.php to set this correctly.

Am I missing anything here?

**Comment by marcelfolaron** [comment]
Thanks for bringing that up. Right now there is no way that I could think
of (short of going into the docker instance and changing the db call)

it seems we could just add a string for additional parameters that would
allow you to add sslmode. I am not sure where you’d put the certificate
though.

**Comment by leogaggl** [comment]
Hi @marcelfolaron 

The certificates should probably just go into the default Laravel /resources/certificates folder (which currently does not exist) I assume. That is if they are needed. For LetsEncrypt and other popular CA's it would probably not be needed.

The main issue is you can not set the parameters and SSL options in the configuration.php and there is no database.php used in Leantime.

This is a database.php config example for Laravel using SSL connection to MySQL

       'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
            'sslmode' => 'require',
            'options'   => array(
                PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
                PDO::MYSQL_ATTR_SSL_KEY => '/certs/client-key.pem',
                PDO::MYSQL_ATTR_SSL_CERT => '/certs/client-cert.pem',
                PDO::MYSQL_ATTR_SSL_CA => '/certs/ca.pem',
            ),
        ],

**Comment by leogaggl** [comment]
Hi @marcelfolaron,

Will this be looked at? It's becoming a bit of a showstopper for us.

**Comment by leogaggl** [comment]
This seems to be the helpful https://callisto.digital/posts/php/enable-mysql-over-ssl-in-php-pdo/

**Comment by marcelfolaron** [comment]
We recently moved a lot of our core code to laravel and this is now possible as of 3.3.0
