### ISSUE TITLE
Profile Settings not in Dark Mode | Error 404 on Project Settings [BUG]

### ISSUE THREAD

**Issue by root9191** [Leantime/leantime#900]
**To Reproduce**
1. Go to 'My Profile'
2. Click on 'Theme - Dark Mode'

**Leantime Version**
2.2.5

**Server**
Apache, nginx, IIS etc

**PHP / MySQL Version**
PHP 8.0.20 / 10.3.35-MariaDB - MariaDB Server 

**Additional context**

![5WqeKxNaW6](https://user-images.githubusercontent.com/47309435/185855719-1cd41a5a-244e-4be3-9ee6-a8a677ab27d4.png)

**To Reproduce**
1. Go to 'Project Settings'
![yZEjpLqWfL](https://user-images.githubusercontent.com/47309435/185856325-7b12b066-f57b-49f6-8e8b-a96340ee0c05.png)

btw: in your Github Release Tags there is a tipping Error ;)
![s1MeaAWCEN](https://user-images.githubusercontent.com/47309435/185856400-3d4bca6d-bf28-4df3-bcab-2bcc097bcc67.png)

**Comment by root9191** [comment]
EDIT:
Can be closed now - After taking a new private Tab in the Browser i got the report to Update the Database.
Now everything looks good :)

**Comment by marcelfolaron** [comment]
I'll create another issue though: the system currently doesn't forward to the update/ page when you are logged in. 
That needs to change.

**Comment by marcelfolaron** [comment]
Thanks!
