### ISSUE TITLE
[BUG] - To-Do "Save" and "Save and Close" buttons do the same thing.

### ISSUE THREAD

**Issue by dw1979** [Leantime/leantime#911]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
To-Do "Save" and "Save and Close" buttons do the same thing. ("Save and Close" button saves, but does not close)

**To Reproduce**

Using Firefox 103.0.2 or current Edge

1 Go to To_Dos
2a Click three dot menu (in Kanban View) and select 'edit To-Do' [or]
2b Click To-Do title (in table view), 
3. Make desired edits
4. Scroll down to "Save " or "Save and Close" buttons
5. Click "Save and Close" and observe save (edits do in actually save and if set, a notification email is sent) but popup doesn't close

**Expected behavior**
"Save and close" should save, but not leave the edit popup on screen for further edits.

**Leantime Version**
2.2.4

**Server**
Apache2

**PHP / MySQL Version**
PHP 8.0.21
mysql  Ver 15.1 Distrib 10.6.8-MariaDB, for debian-linux-gnu (x86_64)

**Additional context**
Served over SSL via cloudflare proxy and local NGINX proxy manager with self-signed SSL

**This is my first ever bug reported to github, I think I've supplied the right amount of detail etc. but yell at me if not!!!**

**Comment by marcelfolaron** [comment]
Thanks, this was actually fixed in 2.2.5
Please update and let me know if that is still an issue

**Comment by dw1979** [comment]
Thanks Marcel,

Very sorry I missed this. Only learned about Leantime a few days ago.
Downloaded it, boarded a plane, installed, slept, filed bug report. Assumed
I was on the latest version. Sorry to waste your time, I promse my next bug
report will be more helpful.

Thanks for the great work!!

Damien
Damien Watson


p: +61409005430 <0409005430> Australia
p: +6792325116 <0409005430> Fiji
e: ***@***.***
e:  ***@***.******@***.***
***@***.***>

**Comment by marcelfolaron** [comment]
No worries at all! Thank you for taking the time to submit bugs and give
feedback!
