### ISSUE TITLE
Add Zulip weboook

### ISSUE THREAD

**Issue by GhaziTriki** [Leantime/leantime#92]
Hello,

We still think that Leantime is awesome and we are using it more and more. Could you please add the Zulip webhook integration please?

Thanks,
Ghazi

**Comment by marcelfolaron** [comment]
Thanks, I'll take a look at their API

**Comment by GhaziTriki** [comment]
This amazing. I will test it today. Thank you @marcelfolaron

**Comment by marcelfolaron** [comment]
Thanks, let me know if you find any issues with it!

**Comment by GhaziTriki** [comment]
![image](https://user-images.githubusercontent.com/4991088/73980549-bc062a80-4930-11ea-8a6c-bc702e13b566.png)

🙌
