### ISSUE TITLE
[FEATURE] Refactor CSS to SCSS

### ISSUE THREAD

**Issue by broskees** [Leantime/leantime#920]
**Is your feature request related to a problem? Please describe.**
I think development time and contributing would be more efficient and accessible if the project used SCSS.

**Describe the solution you'd like**
- CSS managed with SCSS instead of vanilla css and less.

**Comment by gloriafolaron** [comment]
Thanks for the suggestion! Have you had any luck with the converter platforms out there or any you'd recommend? - Signed the non-engineering product person.

**Comment by marcelfolaron** [comment]
We started using LESS (didn't get very far). A grunt process to transpile
LESS is already present so that might be the quicker option.
Are you volunteering to update and clean up the CSS :D ?

**Comment by broskees** [comment]
@marcelfolaron I'm already working on another PR for you guys at the moment lol. That's actually why this came up. 

I'd be happy to make this happen in another PR, obviously post the one I'm doing, and post my actual job being done for the day. It sounds like you're open to using SCSS instead of less.

Would you guys be open to an implementation of templates using [Twig](https://github.com/twigphp/Twig) or Laravel's [Blade](https://github.com/illuminate/view) instead of how we're doing templates now? 

Changes like this will attract a lot more contributors too I believe.

**Comment by marcelfolaron** [comment]
Hey,

Thank you! I just took a look at the draft PR. This is amazing, thank you! 
To answer you questions: Yes, I don't have a preference on SCSS vs LESS.

> I'd be happy to contribute to this plugin relatively often as it fits my use-case very well for my company, provided I can expect not to get slammed with paywalls down the road for core features when this project eventually becomes monetized.

I can promise you that none of the core features will be behind a paywall. A little bit about our current thinking:
Leantime as a "productivity suite" will always remain open source and I have no intention of taking any features away.

Our current commercialization strategy revolves around an employee engagement system on top of Leantime. such as rewards, peer bonuses etc. 

I think this is a fair split and ensures we are advancing productivity with our open source community while building a business around "employee engagement".

@gloriafolaron Can dive deeper on the strategy as well/ 

Side Note Reply:
Yes please! It's been on my mind for a long time, but I have been shying away from the work involved to refactor all the templates. If you start I'd be happy to jump in with the refactoring.

**Comment by gloriafolaron** [comment]
Happy to add to this conversation as these things have been on my agenda; and make a more global discussion of it.

I have some things going on today but can likely put something together more thoroughly by end of tomorrow. 

At least a map out to get the conversation going.

P.s. I love this call out and it's really important to us to stay true to the work contributed.

**Comment by broskees** [comment]
@marcelfolaron Thank you for the info. I'll move on to these other PRs as I get the time and after I finish the one I'm currently working on.

I don't totally understand how the employee engagement system works you're referring to, but it doesn't sound like something I'd object to.

I'm looking forward more info about this as you flesh out the details.
