### ISSUE TITLE
Docker Image Lastest Exec Error

### ISSUE THREAD

**Issue by heatwebs22** [Leantime/leantime#928]
While trying to pull down leantime/leantime docker image. I get a exec error while trying to run docker image. I looked on docker hub and found that the latest tag only supports arm64 and no amd64. To solve this for now I had to use the tag 2.2.7. Can this be fixed so when an update is released it can pull the lastest release with the supported arch. Thank You!

Here attach image showing the lastest image:

![image](https://user-images.githubusercontent.com/94069195/187544879-accca091-9274-4fde-bf4e-24da64549fba.png)

I hope this helps.

**Comment by marcelfolaron** [comment]
Thanks. I just pushed new images and now with support for ARM64, AMD64 and ARMv7
