### ISSUE TITLE
[BUG] CurlMultiHandler Long Execution Time

### ISSUE THREAD

**Issue by Whos0who** [Leantime/leantime#932]
Hello,
I have updated to the last version, but I got the following error when logging on and navigating through pages:

PHP Fatal error:  Maximum execution time of 30 seconds exceeded in *******\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php on line 160

**Leantime Version**
2.2.7

**Server**
Apache 2.4

**PHP / MySQL Version**
PHP 8.1

**Additional context**
Note: I'm using local server without internet.

**Comment by marcelfolaron** [comment]
Thanks for submitting.
Can you navigate to pages (and see the UI at all)?

I assume you haven’t tried to set up an integration (slack or so)?

It might be related to telemetry, you can turn this off in Company
Settings. If you can’t navigate to it you can turn that off in the database
table zp_settings

**Comment by marcelfolaron** [comment]
In any case, this needs to be fixed on our end as well. Ill make sure to
include it in the next release.

**Comment by Whos0who** [comment]
> Thanks for submitting. Can you navigate to pages (and see the UI at all)? I assume you haven’t tried to set up an integration (slack or so)? It might be related to telemetry, you can turn this off in Company Settings. If you can’t navigate to it you can turn that off in the database table zp_settings
> […](#)

Great! 
I have deleted the record related to telemetry from the database, and the no longer page delay. Thank you.

However, some warnings are logged such as:
PHP Deprecated:  setcookie(): Passing null to parameter #2 ($value) of type string is deprecated in *****\src\core\class.session.php on line 141

PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in *****\src\domain\api\controllers\class.sessions.php on line 74
