### ISSUE TITLE
[BUG] Problem sprints burndown

### ISSUE THREAD

**Issue by Community-Mailex** [Leantime/leantime#938]
Description

Burndown sprints do not work in project reports.
No matter what changes are made on a task, none of them are taken into account (task, effort and hours).

Expected behavior

Display of the graph in burndown sprints when adding task, effort and time.

Leantime Version
2.2.7

Server
Apache 2.4.51

PHP / MySQL Version
8.1.7 / 4.9.6

Additional context
Empty log file.

![1](https://user-images.githubusercontent.com/109607773/188840078-71d27b9c-1e24-4d72-a90b-9d2bd9bb83e5.PNG)
![2](https://user-images.githubusercontent.com/109607773/188840084-3d7fd543-b9c3-4fb7-8a99-2c39a23908a1.PNG)
![3](https://user-images.githubusercontent.com/109607773/188840086-6b119d66-f446-40f3-a0c2-58ca5bb43e8f.PNG)

**Comment by marcelfolaron** [comment]
Hi, sorry for the delay. Sprint burndown updates happen only once a day (basically the first time a user logs in) so they are not realtime.
