### ISSUE TITLE
[BUG] Calendar events can not be created in german profile language

### ISSUE THREAD

**Issue by wiihaa** [Leantime/leantime#940]
**Describe the bug**

When I change the user language to german i can not create events. While creating an event, i get a message that says 'event created successfully' but the event does not appear in the calendar overview.
When i change the language to english(US) it works perfectly.

**To Reproduce**
1. Go to 'My Profile'
2. Change Language to 'Deutsch'
3. Go to 'My Calendar'
4. Create an Event
5. Event not showing in Calendar (event was not created)

**Expected behavior**
I would expect, that the event was created and visible in the Calendar

**Leantime Version**
2.2.7

**Server**/**PHP / MySQL Version**
Installed with current docker-compose from docker-leantime repo

**Comment by datWeazel** [comment]
Can confirm. Would be nice to have this fixed.
