### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by joaobrazuna** [Leantime/leantime#941]
After importing a user from AD, the user is created but it is impossible to change any item on the user profile.
It reports the following errors:
Warning: Undefined array key "firstname" in /var/www/html/leantime/src/domain/users/controllers/class.editOwn.php on line 58
Warning: Undefined array key "lastname" in /var/www/html/leantime/src/domain/users/controllers/class.editOwn.php on line 59
Warning: Undefined array key "user" in /var/www/html/leantime/src/domain/users/controllers/class.editOwn.php on line 60
Warning: Undefined array key "newPassword" in /var/www/html/leantime/src/domain/users/controllers/class.editOwn.php on line 62
Deprecated: password_hash(): Passing null to parameter #1 ($password) of type string is deprecated in /var/www/html/leantime/src/domain/users/controllers/class.editOwn.php on line 62

**To Reproduce**
1. Add a new user to AD
2. Enter user credentials in leantime for the 1st time
3. Goto user profile
4. Try to save the profile,

![Screenshot_1](https://user-images.githubusercontent.com/44297535/189310077-59d8c3ea-84be-4492-b11f-5d37e76661f9.png)

**Expected behavior**
Data is updated.

**Leantime Version**
2.2.7

**Server**
Ubuntu 20.04.5 LTS
Server version: Apache/2.4.41 (Ubuntu)
Server built:   2022-06-14T13:30:55

**PHP / MySQL Version**
php 8.1.9
mysql  Ver 15.1 Distrib 10.3.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Additional context**
Although in configuration.php the phonenumber is set to be retrieved from the AD, it is not.

   public $ldapKeys = '{ 
        "username":"samaccountname",
        "groups":"memberof",
        "email":"mail",
        "firstname":"givenname",
        "lastname":"sn",
        "phonenumber":"telephonenumber"
        }';

**Comment by gloriafolaron** [comment]
@marcelfolaron
