### ISSUE TITLE
[FEATURE REQUEST] To-Dos page - View and Group By

### ISSUE THREAD

**Issue by Wavee7** [Leantime/leantime#947]
**Describe the bug**
On **To-Dos** page, I think that there is two bugs :
1. If I select **Table View** and sign out, when I sign in again, **Table View** is not kept, it come back to **Kanban View**
2. When I select **Table View** and select **Group By - Status**, the tasks are not on the right group when I change their status. I need to go on another page then come back to the **To-Dos** page to see the update

**To Reproduce**
For the "View" bug :
1. Go to **To-Dos** page
3. Select **Table View**
4. Sign out
5. Sign in
6. Go to **To-Dos** page
7. The view will be **Kanban View** instead of **Table View**

For the "Group By" bug :
1. Go to **To-Dos** page
2. Select **Table View**
3. Group by Status
4. Change the status of a task
5. The task will stay on the original status group instead of moving to the new status group

**Expected behavior**
For the "View" bug I expect that it keeps the view that I selected _(and the other settings like the Group By)_
For the "Group By" bug I expect that the task moves to the right group every time I change the status when I group my tasks by Status

**Leantime Version**
2.2.7

Thanks for your help and thanks for this good product !

**Comment by gloriafolaron** [comment]
Thanks for sharing this! This is actually a conversation we've had recently internally and is a feature request more than a bug at this point as the functionality is not currently built the way you described. Completely agree that this should be in there, though, and will relabel this as a feature request so it isn't missed in our tracking.

**Comment by Wavee7** [comment]
Thanks for your feedback !

**Comment by marcelfolaron** [comment]
These should all be fixed now. Please let me know if you are still running into issues

**Comment by Wavee7** [comment]
@marcelfolaron unfortunately the two bugs are still there
