### ISSUE TITLE
[BUG] Duplicating a project

### ISSUE THREAD

**Issue by joaobrazuna** [Leantime/leantime#949]
**Describe the bug**
When duplicating a project "loaded" with itens, it reports the following warnings:
_Warning: Undefined array key "psettings" in /var/www/html/leantime/src/domain/projects/repositories/class.projects.php on line 521
Warning: Undefined array key "priority" in /var/www/html/leantime/src/domain/tickets/repositories/class.tickets.php on line 1065
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/leantime/src/domain/tickets/repositories/class.tickets.php:1065) in /var/www/html/leantime/src/core/class.template.php on line 327_

The project is duplicated, but the SPRINTs are missing.

**To Reproduce**
1. Go to project config
2. Click on duplicate project
![image](https://user-images.githubusercontent.com/44297535/189619942-a6f97f66-ef4e-42ec-9bec-f1af00e47710.png)

*Leantime Version
2.2.7

Server
Ubuntu 20.04.5 LTS
Server version: Apache/2.4.41 (Ubuntu)
Server built: 2022-06-14T13:30:55

PHP / MySQL Version
php 8.1.9
mysql Ver 15.1 Distrib 10.3.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by marcelfolaron** [comment]
Thanks, will take a look at that!
