### ISSUE TITLE
[BUG] Full Lean Canvas breaks after specific string

### ISSUE THREAD

**Issue by Pheggas** [Leantime/leantime#951]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
I've been testing LeanTime for couple of minutes already and found this bug. It is tied with "Conclusion" section of "Problem" view in Research -> Describe the problem. With this very specific string "edfsdfasdferfaerA" (without quotes) you can easily force the text to overflow it's card and be visible over other cards / columns. 

**To Reproduce**
1. Go to Research
2. Click on "Add new" in "Describe the problem"
3. Enter any text in "Hypothesis"
4. Enter text "edfsdfasdferfaerA" couple of times in "Conclusion" section
5. Click "Save & Close"
6. See the bug

**Expected behavior**
The text in "Conclusion" shouldn't overflow it's card. It is considered as unwanted behaviour and potentially can break whole "Full Lean Canvas" view to the point it's unreadable / unclear.

**Leantime Version**
2.2.7

**Server**
Hosting it on Docker through Portainer WebUI. Made stack with LeanTime's default docker_compose file. Edited just volumes and passwords.

**PHP / MySQL Version**
MySQL 8.0 (defined in docker_compose file)

**Additional context**
Screenshots:
![image](https://user-images.githubusercontent.com/9994511/189962983-dbd797b8-10e3-4edd-b3f3-9f1cc16e89a0.png)
![image](https://user-images.githubusercontent.com/9994511/189963033-082d9564-b52a-43ce-bff1-40be640dfaf0.png)

**Comment by marcelfolaron** [comment]
Just to confirm, this only happens when there are no spaces in the word, correct? 
The size of the word is highly unlikely and if it wraps with regular sized words I would consider this low priority right now.

**Comment by Pheggas** [comment]
> this only happens when there are no spaces in the word, correct?

I didn't tested it without spaces. Yes it is low priority but it should be considered as bug and, eventually, should be fixed sometime.

**Comment by gloriafolaron** [comment]
I've seen this in ideas on personal use as well. In the process of organizing bugs on our backend and will filter this in.

**Comment by marcelfolaron** [comment]
Can you confirm that this is still an issue in 2.3.2 ?
