### ISSUE TITLE
[FEATURE] More colors for To-Do statuses

### ISSUE THREAD

**Issue by FalxDraco** [Leantime/leantime#957]
**Is your feature request related to a problem? Please describe.**

One can add multiple custom statuses in **Project Settings - To-Do Status Settings** but is limited to BLUE, YELLOW, GREEN, RED, GREY colors.

**Describe the solution you'd like**
It would be nice if more colors choices were added to the color selector.

**Additional context**
N/A

**Comment by marcelfolaron** [comment]
The reason for the static list right now is that we are using css classes
to color the borders and backgrounds in the cards.
I guess I could change that to be inline styles with color definitions.
Otherwise if you tell me which colors you would like to add I can add at
least a few more colors to the select list.

**Comment by FalxDraco** [comment]
@gloriafolaron && @marcelfolaron 

- Any colors would do, as long as there are more than currently available. The more, the better.
- I personally never thought about user assigned colors. If such a feature existed, I would probably never use it.

**Comment by rivimey** [comment]
ToDo status colours currently include : Blue Red, Green, Yellow and Grey.

I don't know whether we need to be aware of Dark mode - which colours will be invisble etc?

The file /etc/X11/rgb.txt on Unix systems (and widely available elsewhere) may be useful for color names with RGB values attached.

For example, I suggest adding:
  SkyBlue, DarkTurquoise,
  SeaGreen, DarkOliveGreen, LawnGreen,
  PaleGoldenrod, GreenYellow, DarkGoldenrod
  RosyBrown, MistyRose, SaddleBrown,
  DarkOrange, HotPink, DarkOrchid

**Comment by marcelfolaron** [comment]
Some additional colors added in 2.3.4
