### ISSUE TITLE
[BUG] "Report as" doesn't work

### ISSUE THREAD

**Issue by Pheggas** [Leantime/leantime#965]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
I tried to use "Report as" feature. When i did the steps i described below, it didn't change it's behaviour to treat To-dos as done but they're still acting as in-progress or as new.

**To Reproduce**
1. Go to Poject Settings
2. Go to To-Do Status Settings
3. Change one or more items to Report as Done
4. Go back to Project Dashboard
5. All the to-dos that has flag reported as done aren't show as done in Project progress and still show in To-Dos Later.

**Expected behavior**
Treat to-dos that are marked with item that is reported as done - to be done, so show in Project Progress that it's done, remove it from To-Dos Later etc.

**Leantime Version**
2.2.7

**Server**
Docker -> Portainer

**PHP / MySQL Version**
One that is pre-set in docker compose file

**Additional context**
Item "Odmietnuté" ("Dismissed" in translation) is set as "Report as done"
![image](https://user-images.githubusercontent.com/9994511/190867473-00a54dc8-a06b-4bf1-b0c2-173f38c0ec67.png)

Hit Save, mark some To-Dos as "Odmietnuté" and see nothing changes:

![image](https://user-images.githubusercontent.com/9994511/190867552-150c4f45-88a1-43e5-8cb2-2f6121364869.png)

**Comment by marcelfolaron** [comment]
Thank you for submitting this. I will take a look and make sure a fix gets in into the next release.

**Comment by Pheggas** [comment]
Thank you very much. This made me sick so many times i even stopped realising it is wrong lol.
