### ISSUE TITLE
Calendar - ICS File Generation

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#975]
**Is your feature request related to a problem? Please describe.**
I see no ability to use the calendar data in any external software or mobile device

**Describe the solution you'd like**
Any method that would allow us to generate an iCalendar standard ICS file.  At a minimum a simple PHP file we an execute via the command line.  In the future you may consider a built in editable cron that generates this ICS file to a predictable location via a calendar ID.  

**Additional context**
We consider this to be a required feature for ourselves to migrate to Leantime but more importantly I think it is a barrier to businesses  everywhere that are using Outlook, Thunderbird, Google and other platforms that support ICS subscription for read only calendar as a common method to bring all important calendar data into focus on one platform.

I have seen issue #333 which is related but is requiring CalDAV.   An ICS subscription file would be a much less complicated feature to implement while providing the most important aspects of the need.   In the future CalDAV of course would be of value to 'edit' or 'delete' previously created events.

**Comment by marcelfolaron** [comment]
Thanks. I agree ics file would be a good first step. It wouldn't even have to be static. We can create a dynamic ics file.

**Comment by compumatter** [comment]
I'm glad you agree.   For starters you could regenerate the file every 5 minutes per user calendar.  As long as I knew where to find the file I can use that url immediately.  Alternatively even if it is a manual process a cron job could be set on the server to do this as a further first step.  Do you have any thoughts at this point about a timetable for this ?

**Comment by marcelfolaron** [comment]
I am currently tied up with other features for a release this week. But I
can take a look at this in about 3-4 weeks.

**Comment by calawhkbu** [comment]
> **Is your feature request related to a problem? Please describe.** I see no ability to use the calendar data in any external software or mobile device
> 
> **Describe the solution you'd like** Any method that would allow us to generate an iCalendar standard ICS file. At a minimum a simple PHP file we an execute via the command line. In the future you may consider a built in editable cron that generates this ICS file to a predictable location via a calendar ID.
> 
> **Additional context** We consider this to be a required feature for ourselves to migrate to Leantime but more importantly I think it is a barrier to businesses everywhere that are using Outlook, Thunderbird, Google and other platforms that support ICS subscription for read only calendar as a common method to bring all important calendar data into focus on one platform.
> 
> I have seen issue #333 which is related but is requiring CalDAV. An ICS subscription file would be a much less complicated feature to implement while providing the most important aspects of the need. In the future CalDAV of course would be of value to 'edit' or 'delete' previously created events.

I have created A interim solution that export ICS file as of today.
https://github.com/Leantime/leantime/issues/333#issuecomment-1259458020

Future Implementation of my wish list

- CalDAV Implementation so I can sync with google calendar dynamically
- select tickets to sync 
- github integration

**Comment by compumatter** [comment]
Marcel, any idea how long before the next version will be released that includes this feature?  We're ready to test with multiple employees but this one feature is a hold back for us.  It's just too important to the process of project management to do without. Your thoughts?
