### ISSUE TITLE
Height of To-Do's - 'normalize' or 'max-height'

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#976]
**Is your feature request related to a problem? Please describe.**
The heights of the To-Do items are highly variable depending upon the content.  I am unsure what vector is being used to terminate the height ie; (...)   

As it is, a to-do that is a low priority could cover more screen real-estate than a more important to-do just be the sheer size of the draggable to-do.   Bullets which are commonly used in the to-do description area become a billboard on the to-do pane.

**Describe the solution you'd like**
I would like to see the kanban to-do be either:
- uniform in height or 
- provide a max-height or
- show only the Title and icons below

**Additional context**
Normalizing these heights would make the presentation more professional.  It would also allow the person viewing to take in or grasp more completely a larger number of to-do's than current heights would allow.   Trello and Wekan both provide a simple icon which indicates there is more text behind this to-do 

Example Trello Approach (note the arrows to the 'more text' icon.
![image](https://user-images.githubusercontent.com/121611/191166483-f9f9028a-dc90-4cbe-ab73-8634866825cc.png)

Leantime example board as is
![image](https://user-images.githubusercontent.com/121611/191168911-e664f8a1-7d54-4b40-ba99-e27e14d043f4.png)

**Comment by marcelfolaron** [comment]
thank you I think this is great feedback and easily implemented. I agree
that this is a problem. Let me see if I can squeeze that in.

**Comment by compumatter** [comment]
Very nice.  Perfect.  Thank you!

**Comment by compumatter** [comment]
Marcel.  Somehow this reversed itself with the most recent source checkout.  I will create a new issue.
