### ISSUE TITLE
User avatar strange rendering

### ISSUE THREAD

**Issue by GhaziTriki** [Leantime/leantime#98]
A screen-shot that tell us much

![image](https://user-images.githubusercontent.com/4991088/74152357-6ff80600-4c0e-11ea-8b01-857569dddd9b.png)

**Comment by marcelfolaron** [comment]
Hi, 

When did this start happening? 
That usually happens when switching from local file system to S3 (or vice versa). Did you change the config recently? The system does not perform a migration so when moving from one file storage system to another you'll have to move the files manually.

**Comment by GhaziTriki** [comment]
I just updated to version 2.0.6

**Comment by marcelfolaron** [comment]
Can you check if the file it is trying to load, something like: 

/download.php?module=user&encName=XXX&ext=XXX&realName=userPicture

throws any error or if it is a 404?

**Comment by ducdung0909** [comment]
Hi, I got same problem while uploading and choose new avatar image for any user.
I got logs as below:
NOTICE: PHP message: PHP Notice:  ob_end_clean(): failed to delete buffer. No buffer to delete in /var/www/html/public/download.php on line 78

**Comment by ducdung0909** [comment]
Hi,
I edit line 78 of download.php file in /var/www/html/public/ like below:
# ob_end_clean();
 (ob_get_length() > 0) { ob_end_clean(); } 
Image are now uploaded and display well.

**Comment by marcelfolaron** [comment]
Thank you, good catch. I'll cut a new release this weekend and will include the fix.
