### ISSUE TITLE
To-Do's - Calendar popup missing on "initial creation"

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#984]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
When you create a new "To-Do" the calendar popup associated with the Due Date does not popup.
- However, if you "save" the To-Do and then re-select it, the Due Date popup works normally

**To Reproduce**
Create a new To-Do and place your cursor in the "Due Date" field.

**Expected behavior**
The calendar popup should display and be selectable

**Leantime Version**
2.2.7

**Server**
NGINX

**PHP / MySQL Version**
8.1 / Maria DB 10.6.7

**Additional context**
I have created a short video to make obvious the issue

- https://www.youtube.com/watch?v=NSFvd23NWLA

**Comment by yudhaprimadiansyah** [comment]
Same issue here, any solution?

**Comment by compumatter** [comment]
Thank you ! Looks good.
