### ISSUE TITLE
[BUG] Restart logo and User-Avatar missing

### ISSUE THREAD

**Issue by ZoXx** [Leantime/leantime#986]
Good morning everyone,

We are on the latest stable docker version.
What surprised me when setting up the docker is that no volumes need to be specified.

We have now rebooted the system and the user avatars and logo are no longer present. Where are they stored by default?

Is there anyway to provide a volume for where such files are stored? Especially when it comes to updates, this would be very helpful.

**Comment by ZoXx** [comment]
Nobody?

**Comment by ZoXx** [comment]
Great! Thank you very much i havent found the volumes till now. It works.

**Comment by marcelfolaron** [comment]
Good to hear. Thanks.
If the issue is resolved please close the ticket.
