### ISSUE TITLE
To-Do Image uploads but cannot delete or download it

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#995]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
When I click on the ... menu next to the image it shows a window that goes off the screen.  No choices are available.

**To Reproduce**
Create a To-Do,  click on the Files tab, upload a file and then close / reload that image

**Expected behavior**
A dialog window with the expected options.

**Leantime Version**
2.2.1

**Server**
NGINX

**PHP / MySQL Version**
8.1 / 5.7.4

**Additional context**
I have created a video to make this more obvious
- https://www.youtube.com/watch?v=CGGpTQeDSHA&ab_channel=ServerMatter

Would love to also see some text field associated with the image to allow us to describe any background associated with it.

**Comment by OneScripter** [comment]
I can repro this.

**Comment by marcelfolaron** [comment]
Can you update to the latest version? 2.2.7? There were quite a few UI
updates.

**Comment by compumatter** [comment]
Thank you.  Works now.
