### ISSUE TITLE
[FEATURE] Reset button needed for Search

### ISSUE THREAD

**Issue by javaindian** [Leantime/leantime#998]
**Is your feature request related to a problem? Please describe.**
After every search, we are required to change the search criteria to (whatever we think as) default.

**Describe the solution you'd like**
A reset button for search

**Additional context**

**Comment by calawhkbu** [comment]
I created an interim solution for myself

- Clear the Search term When click reset

Once I am able to clear the entire Search Term Criteria I will make a pull request

Flow
1. Create id element in  search button
2. create a Reset button
3. Onclick the reset clear input fields
4. Send the request to the server 


Files Involve
pm/src/domain/tickets/templates/showKanban.tpl.php
pm/src/domain/tickets/controllers/class.showKanban.php

<img width="1183" alt="Screenshot 2022-09-28 at 1 27 17 PM" src="https://user-images.githubusercontent.com/69632978/192695108-32d3d8c9-b8c7-408c-ace6-b5d94785eb1b.png">


Code Snippet
`        //2022-09-28 calaw reset search
        jQuery(".reset").on("click", function() {
            jQuery("input").val("")
            jQuery(".search").click()

        })`

**Comment by javaindian** [comment]
Thanks. That was fast. A small query though. Does this work in Table view as well?

**Comment by calawhkbu** [comment]
> Thanks. That was fast. A small query though. Does this work in Table view as well?

Do you mean the list view?
<example.com>/tickets/showAll
Toggle between kanabn vs list ?

I don’t see the filtering panel in list view
Could you post the URL and screenshot

**Comment by javaindian** [comment]
@calawhkbu I am using 2.2.7 latest one.

**Comment by javaindian** [comment]
I am not a programmer. But i am sure your solution should work if it is pasted in proper file and place. Just that i do not know where though, sadly.

**Comment by calawhkbu** [comment]
> I am not a programmer. But i am sure your solution should work if it is pasted in proper file and place. Just that i do not know where though, sadly.

My Solution may not be complete because in old version 2.0.14
There isn't Priority , Status Fields 

I will come up a better solution later.
If you really Need this solution 
Here is a overview 
Files

/src/domain/tickets/templates/showKanban.tpl.php

1) Add a Button Element
Search 
```
                        <input type="submit" value="Search" name="search" class="search form-control btn btn-primary" />
```
Add 
```
 <input type="button" value="Reset" name="reset" class="reset form-control btn btn-secondary" />

```

2.  Look for 
```
<script type="text/javascript">
```

Add this below 
```
    jQuery(".reset").on("click", function() {
            jQuery("input").val("")
            jQuery('select[name="searchUsers[]"]').val('')
            jQuery('select[name="searchType"]').val('')
            jQuery('select[name="searchMilestone"]').val('')
            jQuery(".search").click()
        })
```

Please note I haven't test in the new version , this is only an interim solution if you really need the reset button feature

**Comment by javaindian** [comment]
Thanks for the effort @calawhkbu.

**Comment by calawhkbu** [comment]
> Hi @calawhkbu
> 
> An update:
> 
> Ver.2.2.8
> 
> Edited showkanban.tbl.php file.
> 
> After restting, it shows only some rectangles.
> 
> Pls check the attachments.
> 
> Table view does not show the Reset button. ![chrome_lz3SpabPik](https://user-images.githubusercontent.com/61616901/196226041-5fd1b1a2-865f-4f53-8794-5d644347e4a7.jpg) ![chrome_l8cj0JDilj](https://user-images.githubusercontent.com/61616901/196226050-01d449ba-ffd6-45f3-999b-91502f8836cd.jpg)

- Does the buttons have functionality?
- can you show me the Element of the button

Suppose you are using chrome,
Right click, Inspect element.
Click on Select an element
Show me the element


![image](https://user-images.githubusercontent.com/69632978/196353241-f379bd88-aac3-489e-b5ff-fdef6abb683a.png)

**Comment by javaindian** [comment]
> > Hi @calawhkbu
> > An update:
> > Ver.2.2.8
> > Edited showkanban.tbl.php file.
> > After restting, it shows only some rectangles.
> > Pls check the attachments.
> > Table view does not show the Reset button. ![chrome_lz3SpabPik](https://user-images.githubusercontent.com/61616901/196226041-5fd1b1a2-865f-4f53-8794-5d644347e4a7.jpg) ![chrome_l8cj0JDilj](https://user-images.githubusercontent.com/61616901/196226050-01d449ba-ffd6-45f3-999b-91502f8836cd.jpg)
> 
> * Does the buttons have functionality?
> * Are you using the latest build and added some features by manually editing the code base ?
> * can you show me the Element of the button
> 
> Suppose you are using chrome, Right click, Inspect element. Click on Select an element Show me the element
> 
> ![image](https://user-images.githubusercontent.com/69632978/196353241-f379bd88-aac3-489e-b5ff-fdef6abb683a.png)

1. Yes. Reset button works once. The Blue rectangle comes after i press reset button once.
2. Yes. Added new Types.
3. Below:
<div class="filterBoxLeft">
                        <label class="inline">Search Term</label><br>
                        <input type="text" class="form-control input-default" id="termInput" name="term" placeholder="Search" value="test">
                         <input type="button" value="" name="reset" class="reset form-control btn btn-secondary">
						<input type="submit" value="" name="submitSearch" class="form-control btn btn-primary pull-left" id="filterFormSubmit">
                    </div>

**Comment by calawhkbu** [comment]
> > > Hi @calawhkbu
> > > An update:
> > > Ver.2.2.8
> > > Edited showkanban.tbl.php file.
> > > After restting, it shows only some rectangles.
> > > Pls check the attachments.
> > > Table view does not show the Reset button. ![chrome_lz3SpabPik](https://user-images.githubusercontent.com/61616901/196226041-5fd1b1a2-865f-4f53-8794-5d644347e4a7.jpg) ![chrome_l8cj0JDilj](https://user-images.githubusercontent.com/61616901/196226050-01d449ba-ffd6-45f3-999b-91502f8836cd.jpg)
> > 
> > 
> > 
> > * Does the buttons have functionality?
> > * Are you using the latest build and added some features by manually editing the code base ?
> > * can you show me the Element of the button
> > 
> > Suppose you are using chrome, Right click, Inspect element. Click on Select an element Show me the element
> > ![image](https://user-images.githubusercontent.com/69632978/196353241-f379bd88-aac3-489e-b5ff-fdef6abb683a.png)
> 
> 1. Yes. Reset button works once. The Blue rectangle comes after i press reset button once.
> 2. Yes. Added new Types.
> 3. Below:
> 
> Search Term

> 

Sorry the Ver.2.2.8 requires PHP8,
I do not have resources to setup PHP8 in my local/ cloud environment.
I developed in  2.0.14, may be others can help.

Please note my code only work in 2.0.14 (Stable) branch.
It might be CSS / other reasons.

**Comment by javaindian** [comment]
> 

@calawhkbu Thanks anyways.

**Comment by marcelfolaron** [comment]
Based on current usability best practices we will ommit the reset button for now. https://www.nngroup.com/articles/reset-and-cancel-buttons/
