### ISSUE TITLE
[BUG] Images in To-Do description aren't displayed

### ISSUE THREAD

**Issue by OneScripter** [Leantime/leantime#999]
**Describe the bug**
Images pasted into a To-Do description field do not show up if Leantime is accessed from a different hostname than was used by the user who pasted the images.

**To Reproduce**
1. Log into Leantime using the server's hostname. Example: http://server01
2. Paste an image into the description editor for a new or existing To-Do.
3. Click Save & Close.
4. Log out of Leantime.
5. Log into Leantime using the server's IP address. Example: http://192.168.0.10
6. Click on To-Dos
7. The previously edited To-Do will show an image placeholder on the Kanban board.
8. Opening the To-Do will also show an image placeholder in the description editor.

**Expected behavior**
Images should show up normally regardless of whether the app is accessed by hostname or IP address and whether http or https is used.

**Leantime Version**
2.2.7

**Server**
Apache/2.4.54 (Unix)

**PHP / MySQL Version**
PHP 8.0.21
 Ver 15.1 Distrib 10.6.9-MariaDB, for Linux (x86_64) using readline 5.1

**Additional context**
Using relative paths like "/img/this.png" should resolve this and also prevent issues if the app is moved to a different server with a different name, port, etc.

**Comment by OneScripter** [comment]
Any update on this?

**Comment by marcelfolaron** [comment]
Hi,
Sorry for the delay. 

Unfortunately relative paths won't work due to issues with subfolder installations:
eg domain.com/leantime/ 
In those cases setting the image to /img/... would result in a call to domain.com/img which would fail. Leaving the slash alltogether won't work either since that would be appended to the current call path. 

I am unsure if the use case of switching domains (using 2 domains at the same time) is a very widely used use case. What is the reason behind that on your end?

**Comment by OneScripter** [comment]
If images or other assets are stored as relative paths (/some/item.png) and the base URL includes an optional subfolder, it can be concatenated to get the full path. That way if User A accesses the app via https://server:8080/leantime and User B accesses the same app via https://192.168.0.50/leantime, they both see images correctly. Also, if the app is moved to a different server, different port or from http to https, images and any relative paths will still work.

**Comment by marcelfolaron** [comment]
Hey, I found a way to manage relative paths within tinymce and then in PHP. 
This will go out with the next release. The only issue is that current todos with images that have been stored with the absolute URL need to be saved ones (which will trigger a replacement process in tinymce).

**Comment by OneScripter** [comment]
Awesome. I don't follow you on the last part regarding "saved ones". Will the update fix them or will they need to be done by hand?

**Comment by marcelfolaron** [comment]
The "old" images were stored using the absolute appURL. 
So to make the old images work you will have to open the To-Do and just click "save". The save should take care of the URL update. 
I know this might be an inconvenience but I didn't want to just update everyone's todo decscription out of fear to break something.

**Comment by OneScripter** [comment]
I see what you mean now. We have a relatively low number so not a big deal. Thanks for putting this in place. Now we just need Docker update instructions. :)
